import Foundation

extension AppStrings {
    static let ukrainian = AppStrings(
        // Tabs
        tabHome: "Головна",
        tabStats: "Статистика",
        tabPremium: "Преміум",
        tabProfile: "Профіль",

        // Dashboard
        greeting: { "Привіт, \($0)!" },
        goodMorning: "Доброго ранку",
        goodAfternoon: "Доброго дня",
        goodEvening: "Доброго вечора",
        goodNight: "Доброї ночі",
        readyForAdventure: "Готові до нової пригоди?",
        level: "Рівень",
        totalXP: "Загалом XP",
        activeDays: "Активні дні",
        chooseYourAdventure: "Оберіть свою пригоду",
        startGameToBoost: "Розпочніть гру, щоб покращити навички",
        flashCards: "Флеш-картки",
        flashCardsDescription: "Вивчайте нові слова за допомогою інтерактивних карток і інтервального повторення",
        masterNewWords: "Опануйте нові слова",
        grammarChallenge: "Граматичний виклик",
        grammarDescription: "Перевірте свої знання складними питаннями та правилами граматики",
        testYourSkills: "Перевірте свої навички",
        wordConstructor: "Конструктор слів",
        wordBuilderDescription: "Складайте слова літера за літерою з перемішаних підказок",
        craftAndDiscover: "Створюйте та відкривайте",
        recentActivity: "Остання активність",
        resetProgress: "Скинути прогрес",
        resetProgressMessage: "Це видалить усі XP, рівні, серії, історію ігор та засвоєний контент. Цю дію неможливо скасувати.",
        progressReset: "Прогрес було скинуто",
        startFreshDescription: "Очистіть увесь прогрес, XP, серії та історію ігор, щоб почати навчання з нуля.",

        // Language Selection
        languages: "Мови",
        cancel: "Скасувати",
        searchLanguages: "Шукати мови\u{2026}",
        chooseYourLanguages: "Оберіть свої мови",
        selectWhatYouKnow: "Вкажіть, що ви знаєте і що вивчаєте",
        iSpeak: "Я говорю",
        imLearning: "Я вивчаю",
        noLanguagesAvailable: "Немає доступних мов для цього джерела.",
        betaLanguagePairs: "Бета-мовні пари",
        showExperimentalPairs: "Показати експериментальні пари з обмеженим вмістом",
        confirm: "Підтвердити:",

        // Categories
        back: "Назад",
        searchCategories: "Шукати категорії",
        noCategories: "Немає категорій",
        noFavouritesYet: "Поки що немає обраних",
        allComplete: "Все завершено!",
        noResults: "Нічого не знайдено",
        tapHeartToSave: "Натисніть \u{2764}\u{FE0F} на будь-якій категорії, щоб зберегти її тут",
        youveFinishedEverything: "Ви все завершили — чудова робота!",
        tryDifferentSearch: "Спробуйте інший пошуковий запит",
        categoriesWillAppear: "Категорії з'являться після завантаження вмісту",
        clearFilters: "Очистити фільтри",
        items: "елементів",
        complete: "Завершено",
        doubleTapToStart: "Натисніть двічі, щоб почати",

        // Flash Cards
        loadingCards: "Завантаження карток\u{2026}",
        tapToReveal: "Натисніть, щоб відкрити",
        stillLearning: "Ще вивчаю",
        gotIt: "Зрозуміло",
        noCardsAvailable: "Немає доступних карток",
        goBack: "Повернутися",

        // Grammar
        loadingQuestions: "Завантаження питань\u{2026}",
        grammarTip: "Граматична підказка",
        next: "Далі",
        noQuestionsAvailable: "Немає доступних питань",

        // Word Builder
        loadingWords: "Завантаження слів\u{2026}",
        buildTheWord: "Складіть слово",
        availableLetters: "Доступні літери",
        undo: "Скасувати",
        clear: "Очистити",
        check: "Перевірити",
        hint: "Підказка",
        noWordsAvailable: "Немає доступних слів",

        // Game Complete
        excellent: "Чудово!",
        greatJob: "Відмінна робота!",
        goodWork: "Гарна робота!",
        keepGoing: "Продовжуйте!",
        excellentSubtitle: "Видатний результат! Ви — природний талант!",
        greatJobSubtitle: "Вражаюча робота! Тримайте темп!",
        goodWorkSubtitle: "Гарний результат! Практика — запорука успіху!",
        keepGoingSubtitle: "Кожне заняття робить вас кращими. Не здавайтеся!",
        points: "балів",
        accuracy: "Точність",
        correct: "Правильно",
        toReview: "На повторення",
        playAgain: "Грати знову",
        backToCategories: "До категорій",

        // Journey
        yourLearningJourney: "Ваш шлях навчання",
        trackYourProgress: "Відстежуйте прогрес і святкуйте досягнення",
        milestones: "Досягнення",
        firstSteps: "Перші кроки",
        gettingStarted: "Початок шляху",
        dedicatedLearner: "Відданий учень",
        wordWarrior: "Воїн слів",
        languageMaster: "Майстер мови",
        polyglotLegend: "Легенда-поліглот",
        xpRequired: "Потрібно XP",
        overview: "Огляд",
        sessions: "Сесії",
        streak: "Серія",
        gamePerformance: "Результати ігор",
        currentStreak: "Поточна серія",
        days: "днів",
        keepLearningEveryDay: "Навчайтеся щодня, щоб підтримувати свою серію!",

        // Profile
        appearance: "Вигляд",
        sound: "Звук",
        beta: "Бета",
        sync: "Синхронізація",
        signOut: "Вийти",
        darkLight: "Темна/Світла",
        orbs: "Сфери",
        quantum: "Квант",
        nebula: "Туманність",
        learner: "Учень",
        xp: "XP",
        darkMode: "Темна тема",
        cosmicDarkTheme: "Космічна темна тема активна",
        lightModeActive: "Світла тема активна",
        animationSpeed: "Швидкість анімації",
        slow: "Повільно",
        normal: "Звичайно",
        fast: "Швидко",
        languagePair: "Мовна пара",
        version: "Версія 1.0.0",
        madeWithLove: "Зроблено з \u{2764}\u{FE0F} для тих, хто вивчає мови",

        // Sound Settings
        masterSound: "Головний звук",
        allSoundsEnabled: "Усі звуки увімкнено",
        allSoundsMuted: "Усі звуки вимкнено",
        allGames: "Усі ігри",
        toggleAllGameSounds: "Увімкнути/вимкнути звуки всіх ігор",
        flashcardsSound: "Флеш-картки",
        grammarSound: "Граматика",
        wordBuilderSound: "Конструктор слів",
        uiInteractions: "Взаємодія з інтерфейсом",
        buttonTapsNavigation: "Звуки натискань і навігації",
        achievements: "Досягнення",
        levelUpFanfares: "Фанфари за підвищення рівня та серії",
        ambientAudio: "Фонове аудіо",
        backgroundAtmospheric: "Фонові атмосферні звуки",

        // Beta Languages
        betaLanguages: "Бета-мови",
        experimentalLanguagePairs: "Експериментальні мовні пари",
        experimentalFeatures: "Експериментальні функції",
        betaLimitedContent: "Бета-мови можуть мати обмежений вміст або випадкові неточності в перекладі.",
        coreLanguages: "Основні мови",
        alwaysOn: "Завжди увімкнено",
        active: "Активно",
        experimentalLanguagesSection: "Експериментальні мови",
        on: "Увімк.",
        off: "Вимк.",

        // Sync
        cloudSync: "Хмарна синхронізація",
        backupRestore: "Резервне копіювання та відновлення прогресу",
        upload: "Завантажити",
        download: "Завантажити",
        lastSynced: "Остання синхронізація:",
        never: "Ніколи",
        justNow: "Щойно",
        changesPending: "Є незбережені зміни",
        dataUploaded: "Дані успішно завантажено",
        dataDownloaded: "Дані успішно отримано",
        syncSecurityNote: "Ваші дані зберігаються надійно. Для синхронізації потрібне інтернет-з'єднання.",
        minAgo: "хв тому",
        hoursAgo: "год тому",
        daysAgo: "дн тому",

        // Sign Out
        connected: "Підключено",
        offline: "Офлайн",
        signOutRequiresInternet: "Для виходу потрібен інтернет",
        email: "Електронна пошта",
        name: "Ім'я",
        membership: "Підписка",
        freeTier: "Безкоштовний план",
        areYouSure: "Ви впевнені?",
        progressWillBeSaved: "Ваш прогрес буде збережено перед виходом.",
        savingProgress: "Збереження прогресу\u{2026}",
        clearingLocalData: "Очищення локальних даних\u{2026}",
        signingOut: "Вихід із системи\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Пульсуючі сфери",
        ambientBackgroundAnimation: "Фонова анімація оточення",
        raveMode: "Режим рейву",
        rapidColorCycling: "Швидка зміна кольорів через усі схеми",
        colorScheme: "Кольорова схема",
        intensity: "Інтенсивність",
        subtle: "Ледь помітно",
        balanced: "Збалансовано",
        celestial: "Небесно",
        speed: "Швидкість",
        calm: "Спокійно",
        flowing: "Плавно",
        swift_: "Жваво",
        perfectStillness: "Ідеальний спокій",
        gentleAndPeaceful: "М'яко і спокійно",
        balancedRhythm: "Збалансований ритм",
        quickAndEnergetic: "Швидко та енергійно",

        // Quantum Flow
        quantumFlow: "Квантовий потік",
        dynamicParticleAnimation: "Динамічна анімація частинок",
        scene: "Сцена",
        particleDensity: "Щільність частинок",
        sparse: "Рідко",
        dense: "Щільно",
        flowSpeed: "Швидкість потоку",
        serene: "Мирно",
        rhythmic: "Ритмічно",
        energetic: "Енергійно",
        exitPreview: "Закрити попередній перегляд",

        // Nebula Drift
        nebulaDrift: "Дрейф туманності",
        cosmicNebulaBackground: "Фоновий шар космічної туманності",
        nebulaOptimizedDarkMode: "Дрейф туманності оптимізовано для темної теми",
        nebulaPreset: "Пресет туманності",
        nebulaIntensity: "Інтенсивність туманності",
        vivid: "Яскраво",
        driftSpeed: "Швидкість дрейфу",
        frozen: "Заморожено",

        // Membership
        plansAndPricing: "Плани та ціни",
        investInYour: "Інвестуйте у своє",
        languageMastery: "Володіння мовою",
        membershipSubtitle: "Приєднуйтесь до тисяч людей, які навчаються розумніше, а не важче.",
        monthly: "Щомісяця",
        yearlyDiscount: "Щорічно  -17%",
        featureComparison: "Порівняння можливостей",
        feature: "Функція",
        free: "Безкоштовно",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Часті запитання",
        secure: "Безпечно",
        dayRefund: "30-денне повернення",
        cancelAnytime: "Скасування будь-коли",
        pricesShownUSD: "Ціни вказано в USD. Можуть застосовуватися податки.",
        popular: "ПОПУЛЯРНЕ",
        starter: "Початковий",
        beginYourJourney: "Розпочніть свій шлях",
        masterLanguagesFaster: "Опановуйте мови швидше",
        unlockFullPotential: "Розкрийте свій повний потенціал",
        ultimateExperience: "Найкращий досвід",
        currentPlan: "Поточний план",
        startPro: "Почати Pro",
        upgradeToElite: "Перейти на Elite",
        ascendToRoyal: "Піднятися до Royal",

        // Game Type Names
        gameFlashCards: "Флеш-картки",
        gameGrammar: "Граматика",
        gameWordBuilder: "Конструктор слів",

        // Additional UI
        languageMasteryEngine: "Рушій Опанування Мов",
        user: "Користувач",
        perMonth: "/міс.",
        perYear: "/рік",

        // Membership Feature Names
        featureLanguagePairs: "Мовні Пари",
        featureDailyPractice: "Щоденна Практика",
        featureGameModes: "Режими Гри",
        featureBreathingOrbs: "Сфери Дихання",
        featureQuantumFlow: "Квантовий Потік",
        featureNebulaDrift: "Дрейф Туманності",
        featureOfflineMode: "Офлайн Режим",
        featureCloudSync: "Хмарна Синхронізація",
        featurePrioritySupport: "Пріоритетна Підтримка",
        unlimited: "Необмежено",
        allModes: "Усі 3",
        scheme1: "1 схема",
        schemes3: "3 схеми",
        allSchemes: "Усі схеми",
        scenes2: "2 сцени",
        allScenes: "Усі сцени",
        presets3: "3 пресети",
        allPresets: "Усі пресети",
        min15: "15 хв"
    )
}
