import Foundation

extension AppStrings {
    static let english = AppStrings(
        // Tabs
        tabHome: "Home",
        tabStats: "Stats",
        tabPremium: "Premium",
        tabSettings: "Settings",
        tabProfile: "Profile",

        // Settings Header
        settingsHeaderTitle: "Preferences",
        settingsHeaderSubtitle: "Personalize your experience",

        // Dashboard
        greeting: { "Hello, \($0)!" },
        goodMorning: "Good morning",
        goodAfternoon: "Good afternoon",
        goodEvening: "Good evening",
        goodNight: "Good night",
        readyForAdventure: "Ready for a new adventure?",
        level: "Level",
        totalXP: "Total XP",
        activeDays: "Active Days",
        chooseYourAdventure: "Choose Your Adventure",
        startGameToBoost: "Start a game to boost your skills",
        flashCards: "Flash Cards",
        flashCardsDescription: "Master new vocabulary with interactive flip cards and spaced repetition",
        masterNewWords: "Master New Words",
        grammarChallenge: "Grammar Challenge",
        grammarDescription: "Test your knowledge with challenging questions and grammar rules",
        testYourSkills: "Test Your Skills",
        wordConstructor: "Word Constructor",
        wordBuilderDescription: "Construct words letter by letter from scrambled clues and hints",
        craftAndDiscover: "Craft & Discover",
        recentActivity: "Recent Activity",
        resetProgress: "Reset Progress",
        resetProgressMessage: "This will erase all your XP, levels, streaks, game history, and mastered content. This action cannot be undone.",
        progressReset: "Progress has been reset",
        startFreshDescription: "Clear all your progress, XP, streaks, and game history to start your learning journey from scratch.",

        // Language Selection
        languages: "Languages",
        cancel: "Cancel",
        searchLanguages: "Search languages\u{2026}",
        chooseYourLanguages: "Choose Your Languages",
        selectWhatYouKnow: "Select what you know and what you're learning",
        iSpeak: "I speak",
        imLearning: "I'm learning",
        noLanguagesAvailable: "No languages available for this source.",
        confirm: "Confirm:",
        done: "Done",
        languagesAvailable: "languages available",
        startYourAdventure: "Start Your Adventure",
        keepLearning: "Keep Learning",

        // Categories
        back: "Back",
        searchCategories: "Search categories",
        noCategories: "No Categories",
        noFavouritesYet: "No Favourites Yet",
        allComplete: "All Complete!",
        noResults: "No Results",
        tapHeartToSave: "Tap the heart on any category to save it here",
        youveFinishedEverything: "You've finished everything — nice work!",
        tryDifferentSearch: "Try a different search term",
        categoriesWillAppear: "Categories will appear once content is loaded",
        clearFilters: "Clear Filters",
        items: "items",
        complete: "Complete",
        doubleTapToStart: "Double tap to start",

        // Flash Cards
        loadingCards: "Loading cards\u{2026}",
        tapToReveal: "Tap to reveal",
        stillLearning: "Still Learning",
        gotIt: "Got It",
        noCardsAvailable: "No cards available",
        goBack: "Go Back",

        // Grammar
        loadingQuestions: "Loading questions\u{2026}",
        grammarTip: "Grammar Tip",
        next: "Next",
        noQuestionsAvailable: "No questions available",

        // Word Builder
        loadingWords: "Loading words\u{2026}",
        buildTheWord: "Build the word",
        availableLetters: "Available Letters",
        undo: "Undo",
        clear: "Clear",
        check: "Check",
        hint: "Hint",
        noWordsAvailable: "No words available",

        // Game Complete
        excellent: "Excellent!",
        greatJob: "Great Job!",
        goodWork: "Good Work!",
        keepGoing: "Keep Going!",
        excellentSubtitle: "Outstanding performance! You're a natural!",
        greatJobSubtitle: "Impressive work! Keep up the momentum!",
        goodWorkSubtitle: "Solid effort! Practice makes perfect!",
        keepGoingSubtitle: "Every session makes you better. Don't give up!",
        points: "points",
        accuracy: "Accuracy",
        correct: "Correct",
        toReview: "To Review",
        playAgain: "Play Again",
        nextCategory: "Next Category",
        backToCategories: "Back to Categories",

        // Journey
        yourLearningJourney: "Your Learning Journey",
        trackYourProgress: "Track your progress and celebrate achievements",
        milestones: "Milestones",
        firstSteps: "First Steps",
        gettingStarted: "Getting Started",
        dedicatedLearner: "Dedicated Learner",
        risingStar: "Rising Star",
        wordWarrior: "Word Warrior",
        knowledgeSeeker: "Knowledge Seeker",
        sentenceCrafter: "Sentence Crafter",
        grammarGuardian: "Grammar Guardian",
        vocabularyVirtuoso: "Vocabulary Virtuoso",
        languageMaster: "Language Master",
        fluencyPioneer: "Fluency Pioneer",
        polyglotLegend: "Polyglot Legend",
        xpRequired: "XP required",
        overview: "Overview",
        sessions: "Sessions",
        streak: "Streak",
        gamePerformance: "Game Performance",
        currentStreak: "Current Streak",
        days: "days",
        keepLearningEveryDay: "Keep learning every day to maintain your streak!",

        // Profile
        account: "Account",
        appearance: "Appearance",
        sound: "Sound",
        sync: "Sync",
        signOut: "Sign Out",
        darkLight: "Dark/Light",
        orbs: "Orbs",
        quantum: "Quantum",
        nebula: "Nebula",
        learner: "Learner",
        xp: "XP",
        words: "Words",
        activityCalendar: "Activity Calendar",
        dayStreak: "day streak",
        darkMode: "Dark Mode",
        cosmicDarkTheme: "Cosmic Night",
        lightModeActive: "Tropical Island",
        animationSpeed: "Animation Speed",
        slow: "Slow",
        normal: "Normal",
        fast: "Fast",
        languagePair: "Language Pair",
        version: "Version 1.0.0",
        madeWithLove: "Made with \u{2764}\u{FE0F} for language learners",

        // Sound Settings
        masterSound: "Master Sound",
        allSoundsEnabled: "All sounds enabled",
        allSoundsMuted: "All sounds muted",
        allGames: "All Games",
        toggleAllGameSounds: "Toggle all game category sounds",
        flashcardsSound: "Flashcards",
        grammarSound: "Grammar",
        wordBuilderSound: "Word Builder",
        uiInteractions: "UI Interactions",
        buttonTapsNavigation: "Button taps & navigation sounds",
        achievements: "Achievements",
        levelUpFanfares: "Level-up fanfares & streak bonuses",
        ambientAudio: "Ambient Audio",
        backgroundAtmospheric: "Background atmospheric sounds",

        // Sync
        cloudSync: "Cloud Sync",
        backupRestore: "Backup & restore your progress",
        upload: "Upload",
        download: "Download",
        lastSynced: "Last synced:",
        never: "Never",
        justNow: "Just now",
        changesPending: "Changes pending",
        dataUploaded: "Data uploaded successfully",
        dataDownloaded: "Data downloaded successfully",
        syncSecurityNote: "Your data is stored securely. Sync requires an internet connection.",
        minAgo: "min ago",
        hoursAgo: "hours ago",
        daysAgo: "days ago",

        // Sign Out
        connected: "Connected",
        offline: "Offline",
        signOutRequiresInternet: "Sign out requires internet",
        email: "Email",
        name: "Name",
        membership: "Membership",
        freeTier: "Free Tier",
        areYouSure: "Are you sure?",
        progressWillBeSaved: "Your progress will be saved before signing out.",
        savingProgress: "Saving progress\u{2026}",
        clearingLocalData: "Clearing local data\u{2026}",
        signingOut: "Signing out\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Breathing Orbs",
        ambientBackgroundAnimation: "Ambient background animation",
        raveMode: "Rave Mode",
        rapidColorCycling: "Rapid color cycling through all schemes",
        colorScheme: "Color Scheme",
        intensity: "Intensity",
        subtle: "Subtle",
        balanced: "Balanced",
        celestial: "Celestial",
        speed: "Speed",
        calm: "Calm",
        flowing: "Flowing",
        swift_: "Swift",
        perfectStillness: "Perfect stillness",
        gentleAndPeaceful: "Gentle and peaceful",
        balancedRhythm: "Balanced rhythm",
        quickAndEnergetic: "Quick and energetic",

        // Quantum Flow
        quantumFlow: "Quantum Flow",
        dynamicParticleAnimation: "Dynamic particle animation layer",
        scene: "Scene",
        particleDensity: "Particle Density",
        sparse: "Sparse",
        dense: "Dense",
        flowSpeed: "Flow Speed",
        serene: "Serene",
        rhythmic: "Rhythmic",
        energetic: "Energetic",
        exitPreview: "Exit Preview",

        // Nebula Drift
        nebulaDrift: "Nebula Drift",
        cosmicNebulaBackground: "Cosmic nebula background layer",
        nebulaOptimizedDarkMode: "Nebula Drift is optimized for Dark Mode",
        nebulaPreset: "Nebula Preset",
        nebulaIntensity: "Nebula Intensity",
        vivid: "Vivid",
        driftSpeed: "Drift Speed",
        frozen: "Frozen",
        nebulaDescLagoon: "Ethereal pink and violet clouds where newborn stars ignite within pillars of interstellar dust",
        nebulaDescCelestial: "An infinite turquoise ocean of luminous gas, shimmering with cyan and teal starlight reflections",
        nebulaDescAndromeda: "A trillion suns suspended at the galaxy's edge, amber light dissolving into deep indigo space",
        nebulaDescSolarAurora: "Golden ribbons of charged particles cascade through magnetic fields, painting the void with warmth",
        nebulaDescSpiralHalo: "A hundred billion stars spiral in perfect harmony, their violet glow tracing gravitational paths",
        nebulaDescStarburst: "A brilliant ring of rapid star formation, electric blue and magenta arcs blazing with radiant energy",

        // Membership
        plansAndPricing: "Plans & Pricing",
        investInYour: "Invest in Your",
        languageMastery: "Language Mastery",
        membershipSubtitle: "Join thousands who are learning smarter, not harder.",
        monthly: "Monthly",
        yearlyDiscount: "Yearly  -17%",
        featureComparison: "Feature Comparison",
        feature: "Feature",
        free: "Free",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Frequently Asked Questions",
        secure: "Secure",
        dayRefund: "30-day refund",
        cancelAnytime: "Cancel anytime",
        pricesShownUSD: "Prices shown in USD. Taxes may apply.",
        popular: "POPULAR",
        starter: "Starter",
        beginYourJourney: "Begin your journey",
        masterLanguagesFaster: "Master languages faster",
        unlockFullPotential: "Unlock your full potential",
        ultimateExperience: "The ultimate experience",
        currentPlan: "Current Plan",
        getStarted: "Get Started",
        startPro: "Start Pro",
        upgradeToElite: "Upgrade to Elite",
        ascendToRoyal: "Ascend to Royal",

        // Game Type Names
        gameFlashCards: "Flash Cards",
        gameGrammar: "Grammar",
        gameWordBuilder: "Word Builder",

        // Additional UI
        languageMasteryEngine: "Language Mastery Engine",
        user: "User",
        perMonth: "/mo",
        perYear: "/yr",

        // Membership Feature Names
        featureLanguagePairs: "Language Pairs",
        featureDailyPractice: "Daily Practice",
        featureGameModes: "Game Modes",
        featureBreathingOrbs: "Breathing Orbs",
        featureQuantumFlow: "Quantum Flow",
        featureNebulaDrift: "Nebula Drift",
        featureOfflineMode: "Offline Mode",
        featureCloudSync: "Cloud Sync",
        featurePrioritySupport: "Priority Support",
        unlimited: "Unlimited",
        allModes: "All 3",
        scheme1: "1 scheme",
        schemes3: "3 schemes",
        allSchemes: "All schemes",
        scenes2: "2 scenes",
        allScenes: "All scenes",
        presets3: "3 presets",
        allPresets: "All presets",
        min15: "15 min",

        // Offline Mode / Connectivity
        offlineMode: "Offline Mode",
        offlineModeDescription: "Use content without an internet connection",
        offlineModeLockedDescription: "Upgrade to Pro to use content offline",
        connectToUse: "Connect to use content",
        connectivityRequired: "Free tier requires an internet connection to access content",
        offlineModeInfo: "When offline mode is enabled, content is available without a network connection. Pro and above tiers can learn anywhere.",
        offlineModeDisabled: "Offline Mode Disabled",
        offlineModeDisabledDetail: "Your tier no longer includes offline access",
        offlineModeActive: "Offline Mode Active",
        offlineModeIncluded: "Your subscription includes offline access",
        onlineOnly: "Online Only",
        offlineModeActivated: "Offline Mode Activated",
        offlineModeActivatedDetail: "Offline access is now available",

        // MARK: - Upgrade Prompts
        unlockPremium: "Unlock Premium",
        viewPlans: "View Plans",
        maybeLater: "Maybe Later",
        requires: "Requires",
        learnMore: "Learn More",
        hideForever: "Hide Forever",
        dontShowAgain: "Don't Show Again",

        // MARK: - Royal Trial
        trialActivated: "Trial Activated!",
        trialWelcomeMessage: "Welcome to 14 days of full Royal access. Every premium feature is yours to explore.",
        trialDuration: "14 Days of Royal Access",
        trialAfterExpiry: "After 14 days, you'll move to Free tier. No charge, ever.",
        trialStartExploring: "Start Exploring",
        trialBannerTitle: "Royal Trial",
        trialExpiringToday: "Expiring today",
        trialOneDayLeft: "1 day remaining",
        trialDaysLeft: "days remaining",
        trialEndedTitle: "Your Trial Has Ended",
        trialEndedSubtitle: "Thanks for trying Royal! Your progress is safe and sound.",
        trialYourProgress: "Your Trial Progress",
        trialLevel: "Level",
        trialStreak: "Streak",
        trialYouStillHave: "You Still Have",
        trialChoosePlan: "Choose a Plan",
        trialContinueFree: "Continue with Free",
        trialCompleted: "Trial Completed",
        trialCompletedTagline: "You've experienced Royal",
        trialStartFree: "Start Free Trial",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Welcome, \($0)!" },
        daysLeftInTrial: { "\($0) days left in your trial" },
        thirtyMinPerDay: "30 min/day",
        resetsIn: { "Resets in \($0)" },
        nowPlaying: "Playing",
        paused: "Paused",

        // MARK: - Game Session Results
        xpBonus: "XP Bonus",
        timeSpentLabel: "Time",
        streakActive: "Active",
        streakLabel: "Streak",
        vsPreviousSession: "vs Previous Session",
        keepImproving: "Keep improving every session!",
        recentPerformance: "Recent Performance",
        last7Sessions: "Last 7 sessions",
        areasToImprove: "Areas to Improve",
        reviewIncorrect: { "Review \($0) incorrect answers" },
        shareResult: "Share Result",
        availableOn: { "Available on \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "Daily XP",
        last7Days: "Last 7 days",
        weeklyTrend: "Weekly Trend",
        thisWeekVsLastWeek: "This week vs last week",
        thisWeekLabel: "This week",
        lastWeekLabel: "Last week",
        totalThisWeek: "Total this week",
        accuracyHeatmap: "Accuracy Heatmap",
        accuracyByCategory: "Accuracy by category",
        playSessionsToSeeData: "Play sessions to see data",
        monthlyReport: "Monthly Report",
        last30Days: "Last 30 days",
        activeDaysLabel: "Active Days",
        milestonePredictionsTitle: "Milestone Predictions",
        basedOnYourPace: "Based on your current pace",
        allMilestonesReached: "All milestones reached!",
        tapToUpgrade: "Tap to upgrade",
        unlockFeature: "Unlock this feature",
        gameBreakdownDesc: "See exactly where you shine — track scores, accuracy & time across every game mode",
        dailyXPChartDesc: "Visualise your momentum — watch your daily XP unfold across the week",
        weeklyTrendDesc: "Compare this week to last and spot the patterns that drive your growth",
        accuracyHeatmapDesc: "Instantly reveal your strongest and weakest categories at a glance",
        monthlyReportDesc: "Your personalised 30-day snapshot — sessions, streaks, accuracy & active days",
        milestonePredictionsDesc: "See exactly when you'll hit your next milestone based on your learning pace",

        // MARK: - Data Export & Insights (Epic 18)
        exportData: "Export Data",
        exportDataDesc: "Download your learning history — review progress offline, share with tutors or keep a personal record",
        exportAsCSV: "Export as CSV",
        exportAsJSON: "Export as JSON",
        exportAsPDF: "Export as PDF",
        exportReady: "Your data is ready to share",
        noDataToExport: "No data to export yet",
        sessionsLabel: "Sessions",
        learningInsights: "Learning Insights",
        insightsDesc: "Unlock deep analytics — discover your optimal study times, track mastery across categories and predict your fluency timeline",
        optimalPracticeTimes: "Optimal Practice Times",
        bestTimeToLearn: "Your best time to learn",
        categoryMastery: "Category Mastery",
        masteryByCategory: "Mastery by category",
        retentionCurve: "Retention Curve",
        retentionOverTime: "Retention over time",
        fluencyTimeline: "Fluency Timeline",
        predictedMilestones: "Predicted milestones",
        morning: "Morning",
        afternoon: "Afternoon",
        evening: "Evening",
        night: "Night",
        needMoreData: "Play more sessions for insights",

        // MARK: - Tier Upgrade Celebration
        upgradedExclamation: "Upgraded!",
        tierChangedExclamation: "Welcome!",
        upgradeMessagePro: "You speak the language of progress — every lesson shapes your voice in the world.",
        upgradeMessageElite: "Your words carry the weight of dedication — excellence is becoming your mother tongue.",
        upgradeMessageRoyal: "You've crowned your journey with words — the language of legends is yours to command.",
        upgradeMessageTrial: "A royal chapter begins — the full story of your linguistic potential awaits.",
        celebrationWelcomeTo: "Welcome to",
        celebrationWelcomeBackTo: "Welcome back to",
        celebrationContinue: "Continue",
        celebrationFirstSubscription: "Thank you for subscribing!",

        // MARK: - Subscription Onboarding (Story 7.3)
        onboardingExploreTitle: "Your Premium Features",
        onboardingTryIt: "Try It!",
        onboardingExplore: "Explore",
        onboardingNext: "Next",
        onboardingSkip: "I'll explore on my own",
        onboardingSummaryTitle: "You just unlocked",
        onboardingSummaryFeatures: "new features",
        onboardingWelcomeBack: "Welcome back! Here's what you have",
        onboardingDone: "Let's Go!",

        // MARK: - Value Framing (Story 7.4)
        valueFramingTitle: "Your Investment",
        valueFramingJust: "Just",
        valueFramingPerDay: "/day",
        valueFramingFeatures: "features",
        valueFramingCoffeePro: "Less than your morning coffee",
        valueFramingCoffeeElite: "Less than a sandwich",
        valueFramingCoffeeRoyal: "Less than a lunch out",
        valueFramingWordsLearned: "You've learned {count} words — that's just {cost} per word with {tier}",
        valueFramingProjected: "Most learners master 300+ words in their first month",

        // MARK: - Legal Consent
        legalConsentTitle: "Before We Begin",
        legalConsentSubtitle: "Please review our policies to continue using LumenLingo",
        privacyPolicyTitle: "Privacy Policy",
        termsOfServiceTitle: "Terms of Service",
        legalVersion: "Version 2.1",
        legalLastUpdated: "Last updated: 23 March 2026",
        legalPrivacySummary: "LumenLingo is operated by LumenShore Ltd. We respect your privacy and are committed to protecting your personal data. This policy covers both our website and iOS app.",
        legalTermsSummary: "These Terms of Service govern your use of the LumenLingo mobile application operated by LumenShore Ltd. By using LumenLingo, you agree to be bound by these Terms.",
        legalPrivacyHighlight1: "Your learning data stays on your device and your personal iCloud account",
        legalPrivacyHighlight2: "We use cookie-free Vercel Analytics — no tracking cookies on our website",
        legalPrivacyHighlight3: "Sentry error monitoring helps us fix bugs (session replay requires consent)",
        legalPrivacyHighlight4: "We never sell your personal data to third parties",
        legalTermsHighlight1: "Free and premium tiers available — subscriptions managed through Apple",
        legalTermsHighlight2: "Your content and learning progress belong to you",
        legalTermsHighlight3: "We may use aggregated, anonymous data for product improvement",
        legalTermsHighlight4: "Governed by the laws of England and Wales",
        legalAcceptAll: "I Agree",
        legalDecline: "Decline",
        legalDeclineTitle: "Are you sure?",
        legalDeclineMessage: "You must accept our Privacy Policy and Terms of Service to use LumenLingo.",
        legalDeclineConfirm: "Decline & Exit",
        legalReadFull: "Read Full Policy",
        legalScrollToAccept: "Scroll to review",

        // MARK: - EULA
        eulaTitle: "End-User Licence Agreement",
        eulaSummary: "This licence agreement governs your use of the LumenLingo app, distributed through the Apple App Store by LumenShore Ltd.",
        eulaHighlight1: "Non-exclusive, revocable licence for personal language learning",
        eulaHighlight2: "Tier-based access — Free, Pro, Elite, and Royal memberships",
        eulaHighlight3: "You own your learning data; we own the app content",
        eulaHighlight4: "Apple-specific terms included per App Store requirements",

        // MARK: - Subscription Disclosure
        subscriptionAutoRenew: "Subscriptions auto-renew monthly unless cancelled at least 24 hours before the current period ends.",
        subscriptionPaymentNotice: "Payment is charged to your Apple ID at confirmation of purchase.",
        subscriptionManageCancel: "Manage or cancel in Settings → Apple ID → Subscriptions.",
        subscriptionTrialNotice: "14-day Royal trial at no charge. Downgrades to Free after trial ends.",
        restorePurchases: "Restore Purchases",
        subscriptionLegalPrefix: "By subscribing, you agree to our",
        subscriptionLegalAnd: "and",

        // MARK: - Subscription Compliance (CCR 2013 / CRD)
        subscriptionTraderInfo: "Provided by LumenShore Limited, registered in England & Wales (#09607326). VAT: GB 270411929.",
        subscriptionCoolingOff: "By purchasing, you consent to immediate access to digital content and acknowledge that this waives your 14-day cooling-off right under the Consumer Contracts Regulations 2013.",
        subscriptionRefundNotice: "Refunds are processed by Apple. To request a refund, visit reportaproblem.apple.com.",
        subscriptionContractDuration: "Monthly rolling contract. No minimum commitment.",
        subscriptionEUConsumerRights: "Your rights under the EU Consumer Rights Directive (2011/83/EU) and UK Consumer Contracts Regulations 2013 are fully respected. Pre-contractual information, right of withdrawal, and prohibition of hidden charges all apply.",
        subscriptionCancelSteps: "To cancel: open Settings > tap your name > Subscriptions > LumenLingo > Cancel Subscription. Cancellation takes effect at the end of the current billing period.",
        subscriptionVATNotice: "Prices include applicable taxes. All purchases are processed and billed by Apple. Actual price may vary by region and currency.",

        // MARK: - Account Deletion
        deleteAccount: "Delete Account",
        deleteAccountWarning: "This will permanently delete all your learning data, progress, streaks, and preferences. This action cannot be undone.",
        deleteAccountConfirm: "Delete Everything",
        deletingAccount: "Deleting account…",
        clearingUserData: "Clearing user data",
        accountDeleted: "Account deleted",

        // MARK: - GDPR Data Export
        gdprExportTitle: "Export My Data",
        gdprExportDesc: "Download all your personal data as a machine-readable JSON file. This is your right under GDPR Article 20 — free for all users.",
        gdprExportButton: "Export Personal Data",
        gdprExportSuccess: "Data exported successfully",
        gdprExportEmpty: "No personal data to export",

        trademarkAttribution: "Apple, the Apple logo, iPhone, iPad, App Store, iCloud, Apple ID, and iOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions.",

        companyName: "Lumenshore Limited",
        companyNumber: "Company No. 09607326",
        companyRegistration: "Registered in England and Wales",
        companyAddress: "Windsor House, Troon Way Business Centre, Humberstone Lane, Leicester, England, LE4 9HA",
        companyVAT: "VAT: GB 270411929",

        cookiePolicyTitle: "Cookie Policy",
        legalUpdated: "Updated March 2025",

        viewMyDataTitle: "View My Data",
        viewMyDataDesc: "See what data LumenLingo stores about you",
        dataProfileInfo: "Profile Information",
        dataGameRecords: "Game Progress Records",
        dataMasteredItems: "Mastered Items",
        dataFavorites: "Favourite Categories",
        dataICloudSync: "iCloud Sync",
        dataEnabled: "Enabled",
        dataDisabled: "Disabled",
        dataStorageEstimate: "Estimated Storage"
    )
}
