import Foundation

extension AppStrings {
    static let french = AppStrings(
        // Tabs
        tabHome: "Accueil",
        tabStats: "Statistiques",
        tabPremium: "Premium",
        tabProfile: "Profil",

        // Dashboard
        greeting: { "Bonjour, \($0) !" },
        goodMorning: "Bonjour",
        goodAfternoon: "Bon après-midi",
        goodEvening: "Bonsoir",
        goodNight: "Bonne nuit",
        readyForAdventure: "Prêt pour une nouvelle aventure ?",
        level: "Niveau",
        totalXP: "XP total",
        activeDays: "Jours actifs",
        chooseYourAdventure: "Choisissez votre aventure",
        startGameToBoost: "Lancez un jeu pour améliorer vos compétences",
        flashCards: "Cartes éclair",
        flashCardsDescription: "Maîtrisez du nouveau vocabulaire avec des cartes interactives et la répétition espacée",
        masterNewWords: "Maîtrisez de nouveaux mots",
        grammarChallenge: "Défi de grammaire",
        grammarDescription: "Testez vos connaissances avec des questions stimulantes et des règles de grammaire",
        testYourSkills: "Testez vos compétences",
        wordConstructor: "Constructeur de mots",
        wordBuilderDescription: "Construisez des mots lettre par lettre à partir d'indices mélangés",
        craftAndDiscover: "Créez et découvrez",
        recentActivity: "Activité récente",
        resetProgress: "Réinitialiser la progression",
        resetProgressMessage: "Cela effacera tous vos XP, niveaux, séries, historique de jeu et contenu maîtrisé. Cette action est irréversible.",
        progressReset: "La progression a été réinitialisée",
        startFreshDescription: "Effacez toute votre progression, XP, séries et historique de jeu pour recommencer votre apprentissage à zéro.",

        // Language Selection
        languages: "Langues",
        cancel: "Annuler",
        searchLanguages: "Rechercher des langues\u{2026}",
        chooseYourLanguages: "Choisissez vos langues",
        selectWhatYouKnow: "Sélectionnez ce que vous connaissez et ce que vous apprenez",
        iSpeak: "Je parle",
        imLearning: "J'apprends",
        noLanguagesAvailable: "Aucune langue disponible pour cette source.",
        confirm: "Confirmer :",
        done: "Terminé",
        languagesAvailable: "langues disponibles",
        startYourAdventure: "Lancez Votre Aventure",
        keepLearning: "Continuez à Apprendre",

        // Categories
        back: "Retour",
        searchCategories: "Rechercher des catégories",
        noCategories: "Aucune catégorie",
        noFavouritesYet: "Aucun favori pour l'instant",
        allComplete: "Tout est terminé !",
        noResults: "Aucun résultat",
        tapHeartToSave: "Appuyez sur le cœur d'une catégorie pour l'enregistrer ici",
        youveFinishedEverything: "Vous avez tout terminé — bravo !",
        tryDifferentSearch: "Essayez un autre terme de recherche",
        categoriesWillAppear: "Les catégories apparaîtront une fois le contenu chargé",
        clearFilters: "Effacer les filtres",
        items: "éléments",
        complete: "Terminé",
        doubleTapToStart: "Appuyez deux fois pour commencer",

        // Flash Cards
        loadingCards: "Chargement des cartes\u{2026}",
        tapToReveal: "Appuyez pour révéler",
        stillLearning: "En cours d'apprentissage",
        gotIt: "Compris",
        noCardsAvailable: "Aucune carte disponible",
        goBack: "Retour",

        // Grammar
        loadingQuestions: "Chargement des questions\u{2026}",
        grammarTip: "Astuce de grammaire",
        next: "Suivant",
        noQuestionsAvailable: "Aucune question disponible",

        // Word Builder
        loadingWords: "Chargement des mots\u{2026}",
        buildTheWord: "Construisez le mot",
        availableLetters: "Lettres disponibles",
        undo: "Annuler",
        clear: "Effacer",
        check: "Vérifier",
        hint: "Indice",
        noWordsAvailable: "Aucun mot disponible",

        // Game Complete
        excellent: "Excellent !",
        greatJob: "Bravo !",
        goodWork: "Bon travail !",
        keepGoing: "Continuez !",
        excellentSubtitle: "Performance exceptionnelle ! Vous êtes un naturel !",
        greatJobSubtitle: "Travail impressionnant ! Gardez cet élan !",
        goodWorkSubtitle: "Bel effort ! C'est en forgeant qu'on devient forgeron !",
        keepGoingSubtitle: "Chaque session vous rend meilleur. N'abandonnez pas !",
        points: "points",
        accuracy: "Précision",
        correct: "Correct",
        toReview: "À revoir",
        playAgain: "Rejouer",
        nextCategory: "Catégorie suivante",
        backToCategories: "Retour aux catégories",

        // Journey
        yourLearningJourney: "Votre parcours d'apprentissage",
        trackYourProgress: "Suivez vos progrès et célébrez vos réussites",
        milestones: "Jalons",
        firstSteps: "Premiers pas",
        gettingStarted: "Mise en route",
        dedicatedLearner: "Apprenant assidu",
        risingStar: "Étoile montante",
        wordWarrior: "Guerrier des mots",
        knowledgeSeeker: "Chercheur de savoir",
        sentenceCrafter: "Artisan des phrases",
        grammarGuardian: "Gardien de la grammaire",
        vocabularyVirtuoso: "Virtuose du vocabulaire",
        languageMaster: "Maître des langues",
        fluencyPioneer: "Pionnier de la fluidité",
        polyglotLegend: "Légende polyglotte",
        xpRequired: "XP requis",
        overview: "Aperçu",
        sessions: "Sessions",
        streak: "Série",
        gamePerformance: "Performance de jeu",
        currentStreak: "Série en cours",
        days: "jours",
        keepLearningEveryDay: "Apprenez chaque jour pour maintenir votre série !",

        // Profile
        appearance: "Apparence",
        sound: "Son",
        sync: "Synchronisation",
        signOut: "Déconnexion",
        darkLight: "Sombre/Clair",
        orbs: "Orbes",
        quantum: "Quantum",
        nebula: "Nébuleuse",
        learner: "Apprenant",
        xp: "XP",
        darkMode: "Mode sombre",
        cosmicDarkTheme: "Thème cosmique sombre actif",
        lightModeActive: "Mode clair actif",
        animationSpeed: "Vitesse d'animation",
        slow: "Lent",
        normal: "Normal",
        fast: "Rapide",
        languagePair: "Paire de langues",
        version: "Version 1.0.0",
        madeWithLove: "Fait avec \u{2764}\u{FE0F} pour les passionnés de langues",

        // Sound Settings
        masterSound: "Son principal",
        allSoundsEnabled: "Tous les sons activés",
        allSoundsMuted: "Tous les sons désactivés",
        allGames: "Tous les jeux",
        toggleAllGameSounds: "Activer/désactiver tous les sons de jeu",
        flashcardsSound: "Cartes éclair",
        grammarSound: "Grammaire",
        wordBuilderSound: "Constructeur de mots",
        uiInteractions: "Interactions de l'interface",
        buttonTapsNavigation: "Sons des boutons et de navigation",
        achievements: "Succès",
        levelUpFanfares: "Fanfares de niveau supérieur et bonus de série",
        ambientAudio: "Audio ambiant",
        backgroundAtmospheric: "Sons atmosphériques de fond",

        // Beta Languages
        // Sync
        cloudSync: "Synchronisation cloud",
        backupRestore: "Sauvegardez et restaurez votre progression",
        upload: "Envoyer",
        download: "Télécharger",
        lastSynced: "Dernière synchronisation :",
        never: "Jamais",
        justNow: "À l'instant",
        changesPending: "Modifications en attente",
        dataUploaded: "Données envoyées avec succès",
        dataDownloaded: "Données téléchargées avec succès",
        syncSecurityNote: "Vos données sont stockées en toute sécurité. La synchronisation nécessite une connexion internet.",
        minAgo: "min",
        hoursAgo: "heures",
        daysAgo: "jours",

        // Sign Out
        connected: "Connecté",
        offline: "Hors ligne",
        signOutRequiresInternet: "La déconnexion nécessite une connexion internet",
        email: "E-mail",
        name: "Nom",
        membership: "Abonnement",
        freeTier: "Gratuit",
        areYouSure: "Êtes-vous sûr ?",
        progressWillBeSaved: "Votre progression sera sauvegardée avant la déconnexion.",
        savingProgress: "Sauvegarde en cours\u{2026}",
        clearingLocalData: "Suppression des données locales\u{2026}",
        signingOut: "Déconnexion en cours\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Orbes respirantes",
        ambientBackgroundAnimation: "Animation d'arrière-plan ambiante",
        raveMode: "Mode rave",
        rapidColorCycling: "Cycle rapide de couleurs à travers tous les thèmes",
        colorScheme: "Palette de couleurs",
        intensity: "Intensité",
        subtle: "Subtil",
        balanced: "Équilibré",
        celestial: "Céleste",
        speed: "Vitesse",
        calm: "Calme",
        flowing: "Fluide",
        swift_: "Vif",
        perfectStillness: "Immobilité parfaite",
        gentleAndPeaceful: "Doux et paisible",
        balancedRhythm: "Rythme équilibré",
        quickAndEnergetic: "Rapide et énergique",

        // Quantum Flow
        quantumFlow: "Flux quantique",
        dynamicParticleAnimation: "Couche d'animation de particules dynamique",
        scene: "Scène",
        particleDensity: "Densité des particules",
        sparse: "Clairsemé",
        dense: "Dense",
        flowSpeed: "Vitesse du flux",
        serene: "Serein",
        rhythmic: "Rythmique",
        energetic: "Énergique",
        exitPreview: "Quitter l'aperçu",

        // Nebula Drift
        nebulaDrift: "Dérive nébulaire",
        cosmicNebulaBackground: "Couche d'arrière-plan nébuleuse cosmique",
        nebulaOptimizedDarkMode: "Dérive nébulaire est optimisée pour le mode sombre",
        nebulaPreset: "Préréglage nébulaire",
        nebulaIntensity: "Intensité de la nébuleuse",
        vivid: "Vif",
        driftSpeed: "Vitesse de dérive",
        frozen: "Figé",
        nebulaDescLagoon: "Nuages éthérés roses et violets où de jeunes étoiles s'enflamment dans des piliers de poussière cosmique",
        nebulaDescCelestial: "Un océan turquoise infini de gaz lumineux, scintillant de reflets stellaires cyan et sarcelle",
        nebulaDescAndromeda: "Un billion de soleils suspendus au bord de la galaxie, lumière ambrée se fondant dans l'espace indigo",
        nebulaDescSolarAurora: "Des rubans dorés de particules chargées cascadent à travers les champs magnétiques, peignant le vide de chaleur",
        nebulaDescSpiralHalo: "Cent milliards d'étoiles spiralent en harmonie parfaite, leur lueur violette traçant des chemins gravitationnels",
        nebulaDescStarburst: "Un anneau brillant de formation stellaire rapide, arcs bleu électrique et magenta flamboyant d'énergie radiante",

        // Membership
        plansAndPricing: "Forfaits et tarifs",
        investInYour: "Investissez dans votre",
        languageMastery: "maîtrise des langues",
        membershipSubtitle: "Rejoignez des milliers de personnes qui apprennent plus efficacement.",
        monthly: "Mensuel",
        yearlyDiscount: "Annuel  -17%",
        featureComparison: "Comparaison des fonctionnalités",
        feature: "Fonctionnalité",
        free: "Gratuit",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Questions fréquentes",
        secure: "Sécurisé",
        dayRefund: "Remboursement sous 30 jours",
        cancelAnytime: "Annulation à tout moment",
        pricesShownUSD: "Prix affichés en USD. Des taxes peuvent s'appliquer.",
        popular: "POPULAIRE",
        starter: "Débutant",
        beginYourJourney: "Commencez votre parcours",
        masterLanguagesFaster: "Maîtrisez les langues plus rapidement",
        unlockFullPotential: "Libérez tout votre potentiel",
        ultimateExperience: "L'expérience ultime",
        currentPlan: "Forfait actuel",
        getStarted: "Commencer",
        startPro: "Commencer Pro",
        upgradeToElite: "Passer à Elite",
        ascendToRoyal: "Accéder à Royal",

        // Game Type Names
        gameFlashCards: "Cartes éclair",
        gameGrammar: "Grammaire",
        gameWordBuilder: "Constructeur de mots",

        // Additional UI
        languageMasteryEngine: "Moteur de Maîtrise Linguistique",
        user: "Utilisateur",
        perMonth: "/mois",
        perYear: "/an",

        // Membership Feature Names
        featureLanguagePairs: "Paires de Langues",
        featureDailyPractice: "Pratique Quotidienne",
        featureGameModes: "Modes de Jeu",
        featureBreathingOrbs: "Orbes Respirants",
        featureQuantumFlow: "Flux Quantique",
        featureNebulaDrift: "Dérive Nébulaire",
        featureOfflineMode: "Mode Hors Ligne",
        featureCloudSync: "Synchronisation Cloud",
        featurePrioritySupport: "Support Prioritaire",
        unlimited: "Illimité",
        allModes: "Les 3",
        scheme1: "1 thème",
        schemes3: "3 thèmes",
        allSchemes: "Tous les thèmes",
        scenes2: "2 scènes",
        allScenes: "Toutes les scènes",
        presets3: "3 préréglages",
        allPresets: "Tous les préréglages",
        min15: "15 min",

        // Offline Mode / Connectivity
        offlineMode: "Mode hors ligne",
        offlineModeDescription: "Utilisez le contenu sans connexion internet",
        offlineModeLockedDescription: "Passez à Pro pour utiliser le contenu hors ligne",
        connectToUse: "Connectez-vous pour utiliser",
        connectivityRequired: "Le niveau gratuit nécessite une connexion internet pour accéder au contenu",
        offlineModeInfo: "Lorsque le mode hors ligne est activé, le contenu est disponible sans connexion réseau. Les niveaux Pro et supérieurs peuvent apprendre partout.",
        offlineModeDisabled: "Mode hors ligne désactivé",
        offlineModeDisabledDetail: "Votre niveau n'inclut plus l'accès hors ligne",

        // MARK: - Upgrade Prompts
        unlockPremium: "Débloquer Premium",
        viewPlans: "Voir les offres",
        maybeLater: "Peut-être plus tard",
        requires: "Nécessite",
        learnMore: "En savoir plus",
        hideForever: "Masquer définitivement",
        dontShowAgain: "Ne plus afficher",

        // MARK: - Royal Trial
        trialActivated: "Essai Activé !",
        trialWelcomeMessage: "Bienvenue pour 14 jours d'accès Royal complet. Toutes les fonctionnalités premium sont à vous.",
        trialDuration: "14 Jours d'Accès Royal",
        trialAfterExpiry: "Après 14 jours, vous passerez au niveau Gratuit. Sans frais.",
        trialStartExploring: "Commencer à Explorer",
        trialBannerTitle: "Essai Royal",
        trialExpiringToday: "Expire aujourd'hui",
        trialOneDayLeft: "1 jour restant",
        trialDaysLeft: "jours restants",
        trialEndedTitle: "Votre Essai Est Terminé",
        trialEndedSubtitle: "Merci d'avoir essayé Royal ! Votre progression est sauvegardée.",
        trialYourProgress: "Votre Progression d'Essai",
        trialLevel: "Niveau",
        trialStreak: "Série",
        trialYouStillHave: "Vous Avez Encore",
        trialChoosePlan: "Choisir un Forfait",
        trialContinueFree: "Continuer en Gratuit",
        trialCompleted: "Essai Terminé",
        trialCompletedTagline: "Vous avez découvert Royal",
        trialStartFree: "Démarrer l'Essai Gratuit",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Bienvenue, \($0) !" },
        daysLeftInTrial: { "\($0) jours restants d'essai" },
        thirtyMinPerDay: "30 min/jour",
        resetsIn: { "Réinitialise dans \($0)" },
        nowPlaying: "En lecture",
        paused: "En pause",

        // MARK: - Game Session Results
        xpBonus: "Bonus XP",
        timeSpentLabel: "Temps",
        streakActive: "Actif",
        streakLabel: "Série",
        vsPreviousSession: "vs Session précédente",
        keepImproving: "Continuez à progresser à chaque session !",
        recentPerformance: "Performance récente",
        last7Sessions: "7 dernières sessions",
        areasToImprove: "Points à améliorer",
        reviewIncorrect: { "Revoir \($0) réponses incorrectes" },
        shareResult: "Partager le résultat",
        availableOn: { "Disponible sur \($0)" }
    )
}
