import Foundation

extension AppStrings {
    static let japanese = AppStrings(
        // Tabs
        tabHome: "ホーム",
        tabStats: "統計",
        tabPremium: "プレミアム",
        tabSettings: "設定",
        tabProfile: "プロフィール",

        // Settings Header
        settingsHeaderTitle: "環境設定",
        settingsHeaderSubtitle: "自分好みにカスタマイズ",

        // Dashboard
        greeting: { "こんにちは、\($0)さん！" },
        goodMorning: "おはようございます",
        goodAfternoon: "こんにちは",
        goodEvening: "こんばんは",
        goodNight: "おやすみなさい",
        readyForAdventure: "新しい冒険の準備はできましたか？",
        level: "レベル",
        totalXP: "合計 XP",
        activeDays: "アクティブ日数",
        chooseYourAdventure: "冒険を選ぼう",
        startGameToBoost: "ゲームを始めてスキルを磨こう",
        flashCards: "フラッシュカード",
        flashCardsDescription: "インタラクティブなカードと間隔反復で新しい単語をマスターしよう",
        masterNewWords: "新しい単語をマスター",
        grammarChallenge: "文法チャレンジ",
        grammarDescription: "難問や文法ルールで知識を試そう",
        testYourSkills: "スキルを試そう",
        wordConstructor: "ワードコンストラクター",
        wordBuilderDescription: "スクランブルされたヒントから一文字ずつ単語を組み立てよう",
        craftAndDiscover: "組み立てて発見",
        recentActivity: "最近のアクティビティ",
        resetProgress: "進捗をリセット",
        resetProgressMessage: "すべてのXP、レベル、連続記録、ゲーム履歴、習得済みコンテンツが削除されます。この操作は元に戻せません。",
        progressReset: "進捗がリセットされました",
        startFreshDescription: "すべての進捗、XP、連続記録、ゲーム履歴をクリアして、学習を最初からやり直しましょう。",

        // Language Selection
        languages: "言語",
        cancel: "キャンセル",
        searchLanguages: "言語を検索\u{2026}",
        chooseYourLanguages: "言語を選択してください",
        selectWhatYouKnow: "話せる言語と学びたい言語を選択してください",
        iSpeak: "話せる言語",
        imLearning: "学習中の言語",
        noLanguagesAvailable: "このソース言語で利用できる言語はありません。",
        confirm: "確認：",
        done: "完了",
        languagesAvailable: "言語が利用可能",
        startYourAdventure: "冒険を始めよう",
        keepLearning: "学び続けよう",

        // Categories
        back: "戻る",
        searchCategories: "カテゴリーを検索",
        noCategories: "カテゴリーなし",
        noFavouritesYet: "お気に入りはまだありません",
        allComplete: "すべて完了！",
        noResults: "結果なし",
        tapHeartToSave: "カテゴリーのハートをタップしてここに保存できます",
        youveFinishedEverything: "すべて完了しました — お見事！",
        tryDifferentSearch: "別の検索キーワードをお試しください",
        categoriesWillAppear: "コンテンツが読み込まれるとカテゴリーが表示されます",
        clearFilters: "フィルターをクリア",
        items: "項目",
        complete: "完了",
        doubleTapToStart: "ダブルタップで開始",

        // Flash Cards
        loadingCards: "カードを読み込み中\u{2026}",
        tapToReveal: "タップして表示",
        stillLearning: "学習中",
        gotIt: "覚えた",
        noCardsAvailable: "利用可能なカードがありません",
        goBack: "戻る",

        // Grammar
        loadingQuestions: "問題を読み込み中\u{2026}",
        grammarTip: "文法のヒント",
        next: "次へ",
        noQuestionsAvailable: "利用可能な問題がありません",

        // Word Builder
        loadingWords: "単語を読み込み中\u{2026}",
        buildTheWord: "単語を組み立てよう",
        availableLetters: "使用可能な文字",
        undo: "元に戻す",
        clear: "クリア",
        check: "チェック",
        hint: "ヒント",
        noWordsAvailable: "利用可能な単語がありません",

        // Game Complete
        excellent: "素晴らしい！",
        greatJob: "よくできました！",
        goodWork: "がんばりました！",
        keepGoing: "この調子で！",
        excellentSubtitle: "圧倒的なパフォーマンス！才能にあふれています！",
        greatJobSubtitle: "見事な成果です！この勢いを続けましょう！",
        goodWorkSubtitle: "しっかり取り組めました！練習を重ねれば完璧に！",
        keepGoingSubtitle: "学ぶたびに上達します。あきらめないで！",
        points: "ポイント",
        accuracy: "正答率",
        correct: "正解",
        toReview: "復習",
        playAgain: "もう一度プレイ",
        nextCategory: "次のカテゴリー",
        backToCategories: "カテゴリーに戻る",

        // Journey
        yourLearningJourney: "あなたの学習の旅",
        trackYourProgress: "進捗を確認して成果を祝おう",
        milestones: "マイルストーン",
        firstSteps: "最初の一歩",
        gettingStarted: "スタート",
        dedicatedLearner: "熱心な学習者",
        risingStar: "ライジングスター",
        wordWarrior: "ワードウォリアー",
        knowledgeSeeker: "知識の探求者",
        sentenceCrafter: "文章の職人",
        grammarGuardian: "文法の守護者",
        vocabularyVirtuoso: "語彙の達人",
        languageMaster: "ランゲージマスター",
        fluencyPioneer: "流暢さの先駆者",
        polyglotLegend: "ポリグロットレジェンド",
        xpRequired: "必要 XP",
        overview: "概要",
        sessions: "セッション",
        streak: "連続記録",
        gamePerformance: "ゲーム成績",
        currentStreak: "現在の連続記録",
        days: "日",
        keepLearningEveryDay: "毎日学習して連続記録を維持しましょう！",

        // Profile
        appearance: "外観",
        sound: "サウンド",
        sync: "同期",
        signOut: "サインアウト",
        darkLight: "ダーク/ライト",
        orbs: "オーブ",
        quantum: "クォンタム",
        nebula: "ネビュラ",
        learner: "学習者",
        xp: "XP",
        words: "単語",
        activityCalendar: "アクティビティカレンダー",
        dayStreak: "日連続",
        darkMode: "ダークモード",
        cosmicDarkTheme: "コズミックナイト",
        lightModeActive: "トロピカルアイランド",
        animationSpeed: "アニメーション速度",
        slow: "遅い",
        normal: "普通",
        fast: "速い",
        languagePair: "言語ペア",
        version: "バージョン 1.0.0",
        madeWithLove: "言語学習者のために\u{2764}\u{FE0F}を込めて作りました",

        // Sound Settings
        masterSound: "マスターサウンド",
        allSoundsEnabled: "すべてのサウンドが有効",
        allSoundsMuted: "すべてのサウンドがミュート",
        allGames: "すべてのゲーム",
        toggleAllGameSounds: "全ゲームカテゴリーのサウンドを切り替え",
        flashcardsSound: "フラッシュカード",
        grammarSound: "文法",
        wordBuilderSound: "ワードビルダー",
        uiInteractions: "UI インタラクション",
        buttonTapsNavigation: "ボタンタップとナビゲーション音",
        achievements: "実績",
        levelUpFanfares: "レベルアップファンファーレと連続ボーナス",
        ambientAudio: "アンビエントオーディオ",
        backgroundAtmospheric: "バックグラウンド環境サウンド",

        // Sync
        cloudSync: "クラウド同期",
        backupRestore: "進捗のバックアップと復元",
        upload: "アップロード",
        download: "ダウンロード",
        lastSynced: "最終同期：",
        never: "未同期",
        justNow: "たった今",
        changesPending: "未同期の変更あり",
        dataUploaded: "データのアップロードが完了しました",
        dataDownloaded: "データのダウンロードが完了しました",
        syncSecurityNote: "データは安全に保管されます。同期にはインターネット接続が必要です。",
        minAgo: "分前",
        hoursAgo: "時間前",
        daysAgo: "日前",

        // Sign Out
        connected: "接続済み",
        offline: "オフライン",
        signOutRequiresInternet: "サインアウトにはインターネット接続が必要です",
        email: "メールアドレス",
        name: "名前",
        membership: "メンバーシップ",
        freeTier: "無料プラン",
        areYouSure: "よろしいですか？",
        progressWillBeSaved: "サインアウト前に進捗が保存されます。",
        savingProgress: "進捗を保存中\u{2026}",
        clearingLocalData: "ローカルデータを消去中\u{2026}",
        signingOut: "サインアウト中\u{2026}",

        // Breathing Orbs
        breathingOrbs: "ブリージングオーブ",
        ambientBackgroundAnimation: "アンビエント背景アニメーション",
        raveMode: "レイブモード",
        rapidColorCycling: "全カラースキームの高速サイクル",
        colorScheme: "カラースキーム",
        intensity: "強度",
        subtle: "控えめ",
        balanced: "バランス",
        celestial: "セレスティアル",
        speed: "速度",
        calm: "穏やか",
        flowing: "流れるように",
        swift_: "素早い",
        perfectStillness: "完全な静止",
        gentleAndPeaceful: "穏やかで安らか",
        balancedRhythm: "バランスの取れたリズム",
        quickAndEnergetic: "速くてエネルギッシュ",

        // Quantum Flow
        quantumFlow: "クォンタムフロー",
        dynamicParticleAnimation: "ダイナミックパーティクルアニメーションレイヤー",
        scene: "シーン",
        particleDensity: "パーティクル密度",
        sparse: "少なめ",
        dense: "多め",
        flowSpeed: "フロー速度",
        serene: "静穏",
        rhythmic: "リズミカル",
        energetic: "エネルギッシュ",
        exitPreview: "プレビューを終了",

        // Nebula Drift
        nebulaDrift: "ネビュラドリフト",
        cosmicNebulaBackground: "コズミックネビュラ背景レイヤー",
        nebulaOptimizedDarkMode: "ネビュラドリフトはダークモードに最適化されています",
        nebulaPreset: "ネビュラプリセット",
        nebulaIntensity: "ネビュラ強度",
        vivid: "鮮やか",
        driftSpeed: "ドリフト速度",
        frozen: "静止",
        nebulaDescLagoon: "淡いピンクと紫の雲の中で生まれたばかりの星が星間塵の柱の中で輝きを放つ",
        nebulaDescCelestial: "無限に広がるターコイズ色の輝くガスの海、シアンとティールの星明かりが揺らめく",
        nebulaDescAndromeda: "銀河の果てに浮かぶ一兆の太陽、琥珀色の光が深い藍色の宇宙に溶けてゆく",
        nebulaDescSolarAurora: "帯電した粒子の金色のリボンが磁場を流れ落ち、虚空をあたたかく彩る",
        nebulaDescSpiralHalo: "千億の星が完璧な調和を描きながら渦を巻き、紫の輝きが重力の軌跡をたどる",
        nebulaDescStarburst: "急速な星形成の輝くリング、エレクトリックブルーとマゼンタのアークが眩い光を放つ",

        // Membership
        plansAndPricing: "プランと料金",
        investInYour: "あなたの",
        languageMastery: "語学力に投資",
        membershipSubtitle: "よりスマートに学ぶ仲間に加わろう。",
        monthly: "月額",
        yearlyDiscount: "年額  -17%",
        featureComparison: "機能比較",
        feature: "機能",
        free: "無料",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "よくある質問",
        secure: "安全",
        dayRefund: "30日間返金",
        cancelAnytime: "いつでもキャンセル可能",
        pricesShownUSD: "価格はUSD表示です。税金が適用される場合があります。",
        popular: "人気",
        starter: "スターター",
        beginYourJourney: "学習の旅を始めよう",
        masterLanguagesFaster: "より速く言語をマスター",
        unlockFullPotential: "あなたの可能性を最大限に",
        ultimateExperience: "究極の体験",
        currentPlan: "現在のプラン",
        getStarted: "始める",
        startPro: "Pro を始める",
        upgradeToElite: "Elite にアップグレード",
        ascendToRoyal: "Royal に昇格",

        // Game Type Names
        gameFlashCards: "フラッシュカード",
        gameGrammar: "文法",
        gameWordBuilder: "ワードビルダー",

        // Additional UI
        languageMasteryEngine: "言語マスタリーエンジン",
        user: "ユーザー",
        perMonth: "/月",
        perYear: "/年",

        // Membership Feature Names
        featureLanguagePairs: "言語ペア",
        featureDailyPractice: "デイリー練習",
        featureGameModes: "ゲームモード",
        featureBreathingOrbs: "ブリージングオーブ",
        featureQuantumFlow: "クォンタムフロー",
        featureNebulaDrift: "ネビュラドリフト",
        featureOfflineMode: "オフラインモード",
        featureCloudSync: "クラウド同期",
        featurePrioritySupport: "優先サポート",
        unlimited: "無制限",
        allModes: "全3種",
        scheme1: "1スキーム",
        schemes3: "3スキーム",
        allSchemes: "全スキーム",
        scenes2: "2シーン",
        allScenes: "全シーン",
        presets3: "3プリセット",
        allPresets: "全プリセット",
        min15: "15分",

        // Offline Mode / Connectivity
        offlineMode: "オフラインモード",
        offlineModeDescription: "インターネット接続なしでコンテンツを使用",
        offlineModeLockedDescription: "Proにアップグレードしてオフラインでコンテンツを使用",
        connectToUse: "接続してコンテンツを使用",
        connectivityRequired: "無料プランではコンテンツへのアクセスにインターネット接続が必要です",
        offlineModeInfo: "オフラインモードを有効にすると、ネットワーク接続なしでコンテンツが利用可能になります。Pro以上のプランではどこでも学習できます。",
        offlineModeDisabled: "オフラインモードが無効",
        offlineModeDisabledDetail: "お使いのプランにはオフラインアクセスが含まれなくなりました",
        offlineModeActive: "オフラインモードが有効",
        offlineModeIncluded: "サブスクリプションにオフラインアクセスが含まれています",
        onlineOnly: "オンラインのみ",
        offlineModeActivated: "オフラインモードが有効化されました",
        offlineModeActivatedDetail: "オフラインアクセスが利用可能になりました",

        // MARK: - Upgrade Prompts
        unlockPremium: "プレミアムを解除",
        viewPlans: "プランを見る",
        maybeLater: "また後で",
        requires: "必要",
        learnMore: "詳しく見る",
        hideForever: "永久に非表示",
        dontShowAgain: "今後表示しない",

        // MARK: - Royal Trial
        trialActivated: "トライアル開始！",
        trialWelcomeMessage: "14日間のRoyalフルアクセスへようこそ。すべてのプレミアム機能をお楽しみください。",
        trialDuration: "14日間のRoyalアクセス",
        trialAfterExpiry: "14日後、無料プランに移行します。料金は発生しません。",
        trialStartExploring: "探索を始める",
        trialBannerTitle: "Royalトライアル",
        trialExpiringToday: "本日期限切れ",
        trialOneDayLeft: "残り1日",
        trialDaysLeft: "日残り",
        trialEndedTitle: "トライアルが終了しました",
        trialEndedSubtitle: "Royalをお試しいただきありがとうございます！進捗は安全に保存されています。",
        trialYourProgress: "トライアルの進捗",
        trialLevel: "レベル",
        trialStreak: "連続",
        trialYouStillHave: "まだ利用可能",
        trialChoosePlan: "プランを選ぶ",
        trialContinueFree: "無料で続ける",
        trialCompleted: "トライアル完了",
        trialCompletedTagline: "Royalを体験済み",
        trialStartFree: "無料トライアルを開始",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "ようこそ、\($0)さん！" },
        daysLeftInTrial: { "トライアル残り\($0)日" },
        thirtyMinPerDay: "30分/日",
        resetsIn: { "\($0)後にリセット" },
        nowPlaying: "再生中",
        paused: "一時停止",

        // MARK: - Game Session Results
        xpBonus: "XPボーナス",
        timeSpentLabel: "時間",
        streakActive: "アクティブ",
        streakLabel: "連続",
        vsPreviousSession: "vs 前回のセッション",
        keepImproving: "毎回成長しています！",
        recentPerformance: "最近の成績",
        last7Sessions: "過去7セッション",
        areasToImprove: "改善点",
        reviewIncorrect: { "\($0)件の不正解を復習" },
        shareResult: "結果を共有",
        availableOn: { "\($0)で利用可能" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "デイリーXP",
        last7Days: "過去7日間",
        weeklyTrend: "週間トレンド",
        thisWeekVsLastWeek: "今週 vs 先週",
        thisWeekLabel: "今週",
        lastWeekLabel: "先週",
        totalThisWeek: "今週の合計",
        accuracyHeatmap: "正答率ヒートマップ",
        accuracyByCategory: "カテゴリ別正答率",
        playSessionsToSeeData: "データを見るにはプレイしてください",
        monthlyReport: "月次レポート",
        last30Days: "過去30日間",
        activeDaysLabel: "アクティブ日数",
        milestonePredictionsTitle: "マイルストーン予測",
        basedOnYourPace: "現在のペースに基づく",
        allMilestonesReached: "全マイルストーン達成！",
        tapToUpgrade: "タップしてアップグレード",
        unlockFeature: "この機能をアンロック",
        gameBreakdownDesc: "あなたの得意分野を発見 — 全ゲームモードのスコア・正確率・時間を追跡",
        dailyXPChartDesc: "勢いを可視化 — 一週間の日別XPの推移を確認",
        weeklyTrendDesc: "今週と先週を比較し、成長を加速させるパターンを見つけよう",
        accuracyHeatmapDesc: "最も得意・不得意なカテゴリーを一目で把握",
        monthlyReportDesc: "あなた専用の30日レポート — セッション数・連続記録・正確率・アクティブ日数",
        milestonePredictionsDesc: "学習ペースに基づいて、次のマイルストーン到達日を正確に予測",
        exportData: "データをエクスポート",
        exportDataDesc: "学習履歴をダウンロード — オフラインで進捗を確認、チューターと共有、または個人記録として保存",
        exportAsCSV: "CSVでエクスポート",
        exportAsJSON: "JSONでエクスポート",
        exportAsPDF: "PDFでエクスポート",
        exportReady: "データの共有準備ができました",
        noDataToExport: "エクスポートするデータがありません",
        sessionsLabel: "セッション",
        learningInsights: "学習インサイト",
        insightsDesc: "深い分析をアンロック — 最適な学習時間を発見、カテゴリー別の習得度を追跡、流暢さのタイムラインを予測",
        optimalPracticeTimes: "最適な練習時間",
        bestTimeToLearn: "学習に最適な時間",
        categoryMastery: "カテゴリー習得度",
        masteryByCategory: "カテゴリー別習得度",
        retentionCurve: "記憶保持曲線",
        retentionOverTime: "時間経過による記憶保持",
        fluencyTimeline: "流暢さタイムライン",
        predictedMilestones: "予測されたマイルストーン",
        morning: "朝",
        afternoon: "午後",
        evening: "夕方",
        night: "夜",
        needMoreData: "インサイトを得るにはもっとセッションをプレイ",
        upgradedExclamation: "アップグレード完了！",
        tierChangedExclamation: "ようこそ！",
        upgradeMessagePro: "あなたは進歩の言葉を話しています——すべてのレッスンが世界でのあなたの声を形作ります。",
        upgradeMessageElite: "あなたの言葉には献身の重みがあります——卓越があなたの母語になりつつあります。",
        upgradeMessageRoyal: "言葉であなたの旅に冠を——伝説の言語はあなたのものです。",
        upgradeMessageTrial: "ロイヤルな章が始まります——あなたの言語的可能性の全物語が待っています。"
    )
}
