import Foundation

extension AppStrings {
    static let german = AppStrings(
        // Tabs
        tabHome: "Startseite",
        tabStats: "Statistiken",
        tabPremium: "Premium",
        tabProfile: "Profil",

        // Dashboard
        greeting: { "Hallo, \($0)!" },
        goodMorning: "Guten Morgen",
        goodAfternoon: "Guten Tag",
        goodEvening: "Guten Abend",
        goodNight: "Gute Nacht",
        readyForAdventure: "Bereit für ein neues Abenteuer?",
        level: "Stufe",
        totalXP: "Gesamt-XP",
        activeDays: "Aktive Tage",
        chooseYourAdventure: "Wähle dein Abenteuer",
        startGameToBoost: "Starte ein Spiel, um deine Fähigkeiten zu verbessern",
        flashCards: "Karteikarten",
        flashCardsDescription: "Lerne neuen Wortschatz mit interaktiven Wendekarten und verteilter Wiederholung",
        masterNewWords: "Neue Wörter meistern",
        grammarChallenge: "Grammatik-Challenge",
        grammarDescription: "Teste dein Wissen mit anspruchsvollen Fragen und Grammatikregeln",
        testYourSkills: "Teste deine Fähigkeiten",
        wordConstructor: "Wortbaukasten",
        wordBuilderDescription: "Baue Wörter Buchstabe für Buchstabe aus durcheinander gewürfelten Hinweisen zusammen",
        craftAndDiscover: "Bauen & Entdecken",
        recentActivity: "Letzte Aktivität",
        resetProgress: "Fortschritt zurücksetzen",
        resetProgressMessage: "Dies löscht alle XP, Level, Streaks, Spielverlauf und gemeisterte Inhalte. Diese Aktion kann nicht rückgängig gemacht werden.",
        progressReset: "Fortschritt wurde zurückgesetzt",
        startFreshDescription: "Lösche deinen gesamten Fortschritt, XP, Streaks und Spielverlauf, um deine Lernreise von vorne zu beginnen.",

        // Language Selection
        languages: "Sprachen",
        cancel: "Abbrechen",
        searchLanguages: "Sprachen suchen\u{2026}",
        chooseYourLanguages: "Wähle deine Sprachen",
        selectWhatYouKnow: "Wähle, was du kannst und was du lernst",
        iSpeak: "Ich spreche",
        imLearning: "Ich lerne",
        noLanguagesAvailable: "Keine Sprachen für diese Ausgangssprache verfügbar.",
        confirm: "Bestätigen:",
        done: "Fertig",
        languagesAvailable: "Sprachen verfügbar",
        startYourAdventure: "Starte Dein Abenteuer",
        keepLearning: "Weiter Lernen",

        // Categories
        back: "Zurück",
        searchCategories: "Kategorien suchen",
        noCategories: "Keine Kategorien",
        noFavouritesYet: "Noch keine Favoriten",
        allComplete: "Alles erledigt!",
        noResults: "Keine Ergebnisse",
        tapHeartToSave: "Tippe auf das Herz einer Kategorie, um sie hier zu speichern",
        youveFinishedEverything: "Du hast alles geschafft — super Arbeit!",
        tryDifferentSearch: "Versuche einen anderen Suchbegriff",
        categoriesWillAppear: "Kategorien erscheinen, sobald der Inhalt geladen ist",
        clearFilters: "Filter zurücksetzen",
        items: "Einträge",
        complete: "Abgeschlossen",
        doubleTapToStart: "Doppeltippen zum Starten",

        // Flash Cards
        loadingCards: "Karten werden geladen\u{2026}",
        tapToReveal: "Tippen zum Aufdecken",
        stillLearning: "Noch am Lernen",
        gotIt: "Gewusst!",
        noCardsAvailable: "Keine Karten verfügbar",
        goBack: "Zurück",

        // Grammar
        loadingQuestions: "Fragen werden geladen\u{2026}",
        grammarTip: "Grammatik-Tipp",
        next: "Weiter",
        noQuestionsAvailable: "Keine Fragen verfügbar",

        // Word Builder
        loadingWords: "Wörter werden geladen\u{2026}",
        buildTheWord: "Bilde das Wort",
        availableLetters: "Verfügbare Buchstaben",
        undo: "Rückgängig",
        clear: "Löschen",
        check: "Prüfen",
        hint: "Tipp",
        noWordsAvailable: "Keine Wörter verfügbar",

        // Game Complete
        excellent: "Ausgezeichnet!",
        greatJob: "Tolle Leistung!",
        goodWork: "Gute Arbeit!",
        keepGoing: "Weiter so!",
        excellentSubtitle: "Hervorragende Leistung! Du bist ein Naturtalent!",
        greatJobSubtitle: "Beeindruckende Arbeit! Bleib am Ball!",
        goodWorkSubtitle: "Solider Einsatz! Übung macht den Meister!",
        keepGoingSubtitle: "Jede Übung macht dich besser. Gib nicht auf!",
        points: "Punkte",
        accuracy: "Genauigkeit",
        correct: "Richtig",
        toReview: "Zu wiederholen",
        playAgain: "Nochmal spielen",
        nextCategory: "Nächste Kategorie",
        backToCategories: "Zurück zu den Kategorien",

        // Journey
        yourLearningJourney: "Deine Lernreise",
        trackYourProgress: "Verfolge deinen Fortschritt und feiere Erfolge",
        milestones: "Meilensteine",
        firstSteps: "Erste Schritte",
        gettingStarted: "Einstieg",
        dedicatedLearner: "Engagierter Lerner",
        risingStar: "Aufsteigender Stern",
        wordWarrior: "Wortkämpfer",
        knowledgeSeeker: "Wissenssuchender",
        sentenceCrafter: "Satzbaumeister",
        grammarGuardian: "Grammatikhüter",
        vocabularyVirtuoso: "Wortschatzvirtuose",
        languageMaster: "Sprachmeister",
        fluencyPioneer: "Fließend-Pionier",
        polyglotLegend: "Polyglott-Legende",
        xpRequired: "XP erforderlich",
        overview: "Übersicht",
        sessions: "Sitzungen",
        streak: "Serie",
        gamePerformance: "Spielleistung",
        currentStreak: "Aktuelle Serie",
        days: "Tage",
        keepLearningEveryDay: "Lerne jeden Tag, um deine Serie beizubehalten!",

        // Profile
        appearance: "Aussehen",
        sound: "Ton",
        sync: "Sync",
        signOut: "Abmelden",
        darkLight: "Dunkel/Hell",
        orbs: "Kugeln",
        quantum: "Quantum",
        nebula: "Nebel",
        learner: "Lerner",
        xp: "XP",
        darkMode: "Dunkelmodus",
        cosmicDarkTheme: "Kosmisches dunkles Thema aktiv",
        lightModeActive: "Heller Modus aktiv",
        animationSpeed: "Animationsgeschwindigkeit",
        slow: "Langsam",
        normal: "Normal",
        fast: "Schnell",
        languagePair: "Sprachpaar",
        version: "Version 1.0.0",
        madeWithLove: "Mit \u{2764}\u{FE0F} für Sprachlernende gemacht",

        // Sound Settings
        masterSound: "Hauptlautstärke",
        allSoundsEnabled: "Alle Töne aktiviert",
        allSoundsMuted: "Alle Töne stummgeschaltet",
        allGames: "Alle Spiele",
        toggleAllGameSounds: "Alle Spieltöne ein-/ausschalten",
        flashcardsSound: "Karteikarten",
        grammarSound: "Grammatik",
        wordBuilderSound: "Wortbaukasten",
        uiInteractions: "UI-Interaktionen",
        buttonTapsNavigation: "Tastentöne & Navigationsklänge",
        achievements: "Erfolge",
        levelUpFanfares: "Stufenaufstiegs-Fanfaren & Serienbelohnungen",
        ambientAudio: "Hintergrundklänge",
        backgroundAtmospheric: "Atmosphärische Hintergrundgeräusche",

        // Beta Languages
        // Sync
        cloudSync: "Cloud-Sync",
        backupRestore: "Sicherung & Wiederherstellung deines Fortschritts",
        upload: "Hochladen",
        download: "Herunterladen",
        lastSynced: "Zuletzt synchronisiert:",
        never: "Nie",
        justNow: "Gerade eben",
        changesPending: "Änderungen ausstehend",
        dataUploaded: "Daten erfolgreich hochgeladen",
        dataDownloaded: "Daten erfolgreich heruntergeladen",
        syncSecurityNote: "Deine Daten werden sicher gespeichert. Synchronisierung erfordert eine Internetverbindung.",
        minAgo: "Min. her",
        hoursAgo: "Std. her",
        daysAgo: "Tage her",

        // Sign Out
        connected: "Verbunden",
        offline: "Offline",
        signOutRequiresInternet: "Abmelden erfordert eine Internetverbindung",
        email: "E-Mail",
        name: "Name",
        membership: "Mitgliedschaft",
        freeTier: "Kostenlose Stufe",
        areYouSure: "Bist du sicher?",
        progressWillBeSaved: "Dein Fortschritt wird vor dem Abmelden gespeichert.",
        savingProgress: "Fortschritt wird gespeichert\u{2026}",
        clearingLocalData: "Lokale Daten werden gelöscht\u{2026}",
        signingOut: "Abmeldung läuft\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Atmende Kugeln",
        ambientBackgroundAnimation: "Ambiente Hintergrundanimation",
        raveMode: "Rave-Modus",
        rapidColorCycling: "Schneller Farbwechsel durch alle Schemata",
        colorScheme: "Farbschema",
        intensity: "Intensität",
        subtle: "Dezent",
        balanced: "Ausgewogen",
        celestial: "Himmlisch",
        speed: "Geschwindigkeit",
        calm: "Ruhig",
        flowing: "Fließend",
        swift_: "Flink",
        perfectStillness: "Vollkommene Stille",
        gentleAndPeaceful: "Sanft und friedlich",
        balancedRhythm: "Ausgewogener Rhythmus",
        quickAndEnergetic: "Schnell und energisch",

        // Quantum Flow
        quantumFlow: "Quantum Flow",
        dynamicParticleAnimation: "Dynamische Partikelanimationsebene",
        scene: "Szene",
        particleDensity: "Partikeldichte",
        sparse: "Dünn",
        dense: "Dicht",
        flowSpeed: "Flussgeschwindigkeit",
        serene: "Gelassen",
        rhythmic: "Rhythmisch",
        energetic: "Energisch",
        exitPreview: "Vorschau beenden",

        // Nebula Drift
        nebulaDrift: "Nebula Drift",
        cosmicNebulaBackground: "Kosmische Nebelschicht im Hintergrund",
        nebulaOptimizedDarkMode: "Nebula Drift ist für den Dunkelmodus optimiert",
        nebulaPreset: "Nebel-Voreinstellung",
        nebulaIntensity: "Nebelintensität",
        vivid: "Lebendig",
        driftSpeed: "Driftgeschwindigkeit",
        frozen: "Eingefroren",
        nebulaDescLagoon: "Ätherische rosa-violette Wolken, in denen neugeborene Sterne in Säulen aus kosmischem Staub entflammen",
        nebulaDescCelestial: "Ein endloser türkiser Ozean aus leuchtendem Gas, schimmernd in Cyan- und dunkeltürkisen Sternenreflexen",
        nebulaDescAndromeda: "Eine Billion Sonnen schweben am Rand der Galaxie, bernsteinfarbenes Licht löst sich im Indigo-Raum auf",
        nebulaDescSolarAurora: "Goldene Bänder geladener Teilchen strömen durch Magnetfelder und malen das Nichts mit sanfter Wärme",
        nebulaDescSpiralHalo: "Hundert Milliarden Sterne spiralen in Harmonie, ihr violetter Schein zeichnet Gravitationspfade nach",
        nebulaDescStarburst: "Ein strahlender Ring rasanter Sternentstehung, elektrisch blaue und magentafarbene Bögen voller Energie",

        // Membership
        plansAndPricing: "Pläne & Preise",
        investInYour: "Investiere in deine",
        languageMastery: "Sprachbeherrschung",
        membershipSubtitle: "Schließe dich Tausenden an, die klüger lernen, nicht härter.",
        monthly: "Monatlich",
        yearlyDiscount: "Jährlich  -17%",
        featureComparison: "Funktionsvergleich",
        feature: "Funktion",
        free: "Kostenlos",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Häufig gestellte Fragen",
        secure: "Sicher",
        dayRefund: "30-Tage-Rückgabe",
        cancelAnytime: "Jederzeit kündbar",
        pricesShownUSD: "Preise in USD. Es können Steuern anfallen.",
        popular: "BELIEBT",
        starter: "Einsteiger",
        beginYourJourney: "Beginne deine Reise",
        masterLanguagesFaster: "Sprachen schneller meistern",
        unlockFullPotential: "Entfalte dein volles Potenzial",
        ultimateExperience: "Das ultimative Erlebnis",
        currentPlan: "Aktueller Plan",
        getStarted: "Loslegen",
        startPro: "Pro starten",
        upgradeToElite: "Auf Elite upgraden",
        ascendToRoyal: "Zu Royal aufsteigen",

        // Game Type Names
        gameFlashCards: "Karteikarten",
        gameGrammar: "Grammatik",
        gameWordBuilder: "Wortbaukasten",

        // Additional UI
        languageMasteryEngine: "Sprachmeisterungs-Engine",
        user: "Benutzer",
        perMonth: "/Monat",
        perYear: "/Jahr",

        // Membership Feature Names
        featureLanguagePairs: "Sprachpaare",
        featureDailyPractice: "Tägliches Üben",
        featureGameModes: "Spielmodi",
        featureBreathingOrbs: "Atmende Kugeln",
        featureQuantumFlow: "Quantenfluss",
        featureNebulaDrift: "Nebeldrift",
        featureOfflineMode: "Offline-Modus",
        featureCloudSync: "Cloud-Synchronisierung",
        featurePrioritySupport: "Prioritäts-Support",
        unlimited: "Unbegrenzt",
        allModes: "Alle 3",
        scheme1: "1 Schema",
        schemes3: "3 Schemata",
        allSchemes: "Alle Schemata",
        scenes2: "2 Szenen",
        allScenes: "Alle Szenen",
        presets3: "3 Voreinstellungen",
        allPresets: "Alle Voreinstellungen",
        min15: "15 Min.",

        // Offline Mode / Connectivity
        offlineMode: "Offline-Modus",
        offlineModeDescription: "Inhalte ohne Internetverbindung nutzen",
        offlineModeLockedDescription: "Upgrade auf Pro, um Inhalte offline zu nutzen",
        connectToUse: "Verbinden, um Inhalte zu nutzen",
        connectivityRequired: "Die kostenlose Stufe erfordert eine Internetverbindung für den Zugriff auf Inhalte",
        offlineModeInfo: "Bei aktiviertem Offline-Modus sind Inhalte ohne Netzwerkverbindung verfügbar. Pro und höhere Stufen können überall lernen.",
        offlineModeDisabled: "Offline-Modus deaktiviert",
        offlineModeDisabledDetail: "Ihre Stufe beinhaltet keinen Offline-Zugriff mehr",

        // MARK: - Upgrade Prompts
        unlockPremium: "Premium freischalten",
        viewPlans: "Pläne ansehen",
        maybeLater: "Vielleicht später",
        requires: "Erfordert",
        learnMore: "Mehr erfahren",
        hideForever: "Für immer ausblenden",
        dontShowAgain: "Nicht mehr anzeigen",

        // MARK: - Royal Trial
        trialActivated: "Testversion Aktiviert!",
        trialWelcomeMessage: "Willkommen zu 14 Tagen vollem Royal-Zugang. Alle Premium-Funktionen gehören Ihnen.",
        trialDuration: "14 Tage Royal-Zugang",
        trialAfterExpiry: "Nach 14 Tagen wechseln Sie zur kostenlosen Stufe. Keine Kosten.",
        trialStartExploring: "Jetzt Entdecken",
        trialBannerTitle: "Royal-Testversion",
        trialExpiringToday: "Läuft heute ab",
        trialOneDayLeft: "1 Tag verbleibend",
        trialDaysLeft: "Tage verbleibend",
        trialEndedTitle: "Ihre Testversion Ist Beendet",
        trialEndedSubtitle: "Danke fürs Ausprobieren von Royal! Ihr Fortschritt ist sicher.",
        trialYourProgress: "Ihr Testfortschritt",
        trialLevel: "Stufe",
        trialStreak: "Serie",
        trialYouStillHave: "Sie Haben Noch",
        trialChoosePlan: "Plan Wählen",
        trialContinueFree: "Kostenlos Fortfahren",
        trialCompleted: "Testversion Abgeschlossen",
        trialCompletedTagline: "Sie haben Royal erlebt",
        trialStartFree: "Kostenlose Testversion Starten",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Willkommen, \($0)!" },
        daysLeftInTrial: { "\($0) Tage Testversion übrig" },
        thirtyMinPerDay: "30 Min/Tag",
        resetsIn: { "Zurücksetzen in \($0)" },
        nowPlaying: "Wird abgespielt",
        paused: "Pausiert",

        // MARK: - Game Session Results
        xpBonus: "XP-Bonus",
        timeSpentLabel: "Zeit",
        streakActive: "Aktiv",
        streakLabel: "Serie",
        vsPreviousSession: "vs Vorherige Sitzung",
        keepImproving: "Verbessere dich mit jeder Sitzung!",
        recentPerformance: "Letzte Leistung",
        last7Sessions: "Letzte 7 Sitzungen",
        areasToImprove: "Verbesserungsbereiche",
        reviewIncorrect: { "\($0) falsche Antworten überprüfen" },
        shareResult: "Ergebnis teilen",
        availableOn: { "Verfügbar auf \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "Tägliche XP",
        last7Days: "Letzte 7 Tage",
        weeklyTrend: "Wochentrend",
        thisWeekVsLastWeek: "Diese Woche vs letzte Woche",
        thisWeekLabel: "Diese Woche",
        lastWeekLabel: "Letzte Woche",
        totalThisWeek: "Gesamt diese Woche",
        accuracyHeatmap: "Genauigkeitskarte",
        accuracyByCategory: "Genauigkeit nach Kategorie",
        playSessionsToSeeData: "Spiele Sitzungen um Daten zu sehen",
        monthlyReport: "Monatsbericht",
        last30Days: "Letzte 30 Tage",
        activeDaysLabel: "Aktive Tage",
        milestonePredictionsTitle: "Meilenstein-Vorhersagen",
        basedOnYourPace: "Basierend auf deinem aktuellen Tempo",
        allMilestonesReached: "Alle Meilensteine erreicht!",
        tapToUpgrade: "Tippen zum Upgraden",
        unlockFeature: "Funktion freischalten",
        gameBreakdownDesc: "Sieh genau, wo du glänzt — verfolge Punkte, Genauigkeit und Zeit in jedem Spielmodus",
        dailyXPChartDesc: "Visualisiere deinen Schwung — beobachte deine täglichen XP über die Woche",
        weeklyTrendDesc: "Vergleiche diese Woche mit der letzten und erkenne die Muster deines Wachstums",
        accuracyHeatmapDesc: "Erkenne sofort deine stärksten und schwächsten Kategorien auf einen Blick",
        monthlyReportDesc: "Dein persönlicher 30-Tage-Überblick — Sitzungen, Serien, Genauigkeit und aktive Tage",
        milestonePredictionsDesc: "Erfahre genau, wann du deinen nächsten Meilenstein basierend auf deinem Lerntempo erreichst",
        exportData: "Daten Exportieren",
        exportDataDesc: "Lade deinen Lernverlauf herunter — überprüfe Fortschritte offline, teile mit Tutoren oder behalte ein persönliches Protokoll",
        exportAsCSV: "Als CSV exportieren",
        exportAsJSON: "Als JSON exportieren",
        exportAsPDF: "Als PDF exportieren",
        exportReady: "Deine Daten sind bereit zum Teilen",
        noDataToExport: "Noch keine Daten zum Exportieren",
        sessionsLabel: "Sitzungen",
        learningInsights: "Lern-Einblicke",
        insightsDesc: "Schalte tiefe Analysen frei — entdecke deine optimalen Lernzeiten, verfolge die Beherrschung nach Kategorie und sage deinen Sprachfluss voraus",
        optimalPracticeTimes: "Optimale Übungszeiten",
        bestTimeToLearn: "Deine beste Lernzeit",
        categoryMastery: "Kategoriebeherrschung",
        masteryByCategory: "Beherrschung nach Kategorie",
        retentionCurve: "Behaltenskurve",
        retentionOverTime: "Behalten im Zeitverlauf",
        fluencyTimeline: "Sprachfluss-Zeitachse",
        predictedMilestones: "Vorhergesagte Meilensteine",
        morning: "Morgen",
        afternoon: "Nachmittag",
        evening: "Abend",
        night: "Nacht",
        needMoreData: "Spiele mehr Sitzungen für Einblicke",
        upgradedExclamation: "Aufgestuft!",
        upgradeMessagePro: "Du sprichst die Sprache des Fortschritts — jede Lektion formt deine Stimme in der Welt.",
        upgradeMessageElite: "Deine Worte tragen das Gewicht der Hingabe — Exzellenz wird deine Muttersprache.",
        upgradeMessageRoyal: "Du hast deine Reise mit Worten gekrönt — die Sprache der Legenden gehört dir.",
        upgradeMessageTrial: "Ein königliches Kapitel beginnt — die ganze Geschichte deines sprachlichen Potenzials wartet."
    )
}
