import Foundation

extension AppStrings {
    static let ukrainian = AppStrings(
        // Tabs
        tabHome: "Головна",
        tabStats: "Статистика",
        tabPremium: "Преміум",
        tabSettings: "Налаштування",
        tabProfile: "Профіль",

        // Settings Header
        settingsHeaderTitle: "Уподобання",
        settingsHeaderSubtitle: "Персоналізуйте свій досвід",

        // Dashboard
        greeting: { "Привіт, \($0)!" },
        goodMorning: "Доброго ранку",
        goodAfternoon: "Доброго дня",
        goodEvening: "Доброго вечора",
        goodNight: "Доброї ночі",
        readyForAdventure: "Готові до нової пригоди?",
        level: "Рівень",
        totalXP: "Загалом XP",
        activeDays: "Активні дні",
        chooseYourAdventure: "Оберіть свою пригоду",
        startGameToBoost: "Розпочніть гру, щоб покращити навички",
        flashCards: "Флеш-картки",
        flashCardsDescription: "Вивчайте нові слова за допомогою інтерактивних карток і інтервального повторення",
        masterNewWords: "Опануйте нові слова",
        grammarChallenge: "Граматичний виклик",
        grammarDescription: "Перевірте свої знання складними питаннями та правилами граматики",
        testYourSkills: "Перевірте свої навички",
        wordConstructor: "Конструктор слів",
        wordBuilderDescription: "Складайте слова літера за літерою з перемішаних підказок",
        craftAndDiscover: "Створюйте та відкривайте",
        recentActivity: "Остання активність",
        resetProgress: "Скинути прогрес",
        resetProgressMessage: "Це видалить усі XP, рівні, серії, історію ігор та засвоєний контент. Цю дію неможливо скасувати.",
        progressReset: "Прогрес було скинуто",
        startFreshDescription: "Очистіть увесь прогрес, XP, серії та історію ігор, щоб почати навчання з нуля.",

        // Language Selection
        languages: "Мови",
        cancel: "Скасувати",
        searchLanguages: "Шукати мови\u{2026}",
        chooseYourLanguages: "Оберіть свої мови",
        selectWhatYouKnow: "Вкажіть, що ви знаєте і що вивчаєте",
        iSpeak: "Я говорю",
        imLearning: "Я вивчаю",
        noLanguagesAvailable: "Немає доступних мов для цього джерела.",
        confirm: "Підтвердити:",
        done: "Готово",
        languagesAvailable: "доступних мов",
        startYourAdventure: "Почни Свою Пригоду",
        keepLearning: "Продовжуй Вчитися",

        // Categories
        back: "Назад",
        searchCategories: "Шукати категорії",
        noCategories: "Немає категорій",
        noFavouritesYet: "Поки що немає обраних",
        allComplete: "Все завершено!",
        noResults: "Нічого не знайдено",
        tapHeartToSave: "Натисніть \u{2764}\u{FE0F} на будь-якій категорії, щоб зберегти її тут",
        youveFinishedEverything: "Ви все завершили — чудова робота!",
        tryDifferentSearch: "Спробуйте інший пошуковий запит",
        categoriesWillAppear: "Категорії з'являться після завантаження вмісту",
        clearFilters: "Очистити фільтри",
        items: "елементів",
        complete: "Завершено",
        doubleTapToStart: "Натисніть двічі, щоб почати",

        // Flash Cards
        loadingCards: "Завантаження карток\u{2026}",
        tapToReveal: "Натисніть, щоб відкрити",
        stillLearning: "Ще вивчаю",
        gotIt: "Зрозуміло",
        noCardsAvailable: "Немає доступних карток",
        goBack: "Повернутися",

        // Grammar
        loadingQuestions: "Завантаження питань\u{2026}",
        grammarTip: "Граматична підказка",
        next: "Далі",
        noQuestionsAvailable: "Немає доступних питань",

        // Word Builder
        loadingWords: "Завантаження слів\u{2026}",
        buildTheWord: "Складіть слово",
        availableLetters: "Доступні літери",
        undo: "Скасувати",
        clear: "Очистити",
        check: "Перевірити",
        hint: "Підказка",
        noWordsAvailable: "Немає доступних слів",

        // Game Complete
        excellent: "Чудово!",
        greatJob: "Відмінна робота!",
        goodWork: "Гарна робота!",
        keepGoing: "Продовжуйте!",
        excellentSubtitle: "Видатний результат! Ви — природний талант!",
        greatJobSubtitle: "Вражаюча робота! Тримайте темп!",
        goodWorkSubtitle: "Гарний результат! Практика — запорука успіху!",
        keepGoingSubtitle: "Кожне заняття робить вас кращими. Не здавайтеся!",
        points: "балів",
        accuracy: "Точність",
        correct: "Правильно",
        toReview: "На повторення",
        playAgain: "Грати знову",
        nextCategory: "Наступна категорія",
        backToCategories: "До категорій",

        // Journey
        yourLearningJourney: "Ваш шлях навчання",
        trackYourProgress: "Відстежуйте прогрес і святкуйте досягнення",
        milestones: "Досягнення",
        firstSteps: "Перші кроки",
        gettingStarted: "Початок шляху",
        dedicatedLearner: "Відданий учень",
        risingStar: "Зірка, що сходить",
        wordWarrior: "Воїн слів",
        knowledgeSeeker: "Шукач знань",
        sentenceCrafter: "Майстер речень",
        grammarGuardian: "Страж граматики",
        vocabularyVirtuoso: "Віртуоз словника",
        languageMaster: "Майстер мови",
        fluencyPioneer: "Піонер вільного мовлення",
        polyglotLegend: "Легенда-поліглот",
        xpRequired: "Потрібно XP",
        overview: "Огляд",
        sessions: "Сесії",
        streak: "Серія",
        gamePerformance: "Результати ігор",
        currentStreak: "Поточна серія",
        days: "днів",
        keepLearningEveryDay: "Навчайтеся щодня, щоб підтримувати свою серію!",

        // Profile
        appearance: "Вигляд",
        sound: "Звук",
        sync: "Синхронізація",
        signOut: "Вийти",
        darkLight: "Темна/Світла",
        orbs: "Сфери",
        quantum: "Квант",
        nebula: "Туманність",
        learner: "Учень",
        xp: "XP",
        words: "Слова",
        activityCalendar: "Календар активності",
        dayStreak: "днів поспіль",
        darkMode: "Темна тема",
        cosmicDarkTheme: "Космічна ніч",
        lightModeActive: "Тропічний острів",
        animationSpeed: "Швидкість анімації",
        slow: "Повільно",
        normal: "Звичайно",
        fast: "Швидко",
        languagePair: "Мовна пара",
        version: "Версія 1.0.0",
        madeWithLove: "Зроблено з \u{2764}\u{FE0F} для тих, хто вивчає мови",

        // Sound Settings
        masterSound: "Головний звук",
        allSoundsEnabled: "Усі звуки увімкнено",
        allSoundsMuted: "Усі звуки вимкнено",
        allGames: "Усі ігри",
        toggleAllGameSounds: "Увімкнути/вимкнути звуки всіх ігор",
        flashcardsSound: "Флеш-картки",
        grammarSound: "Граматика",
        wordBuilderSound: "Конструктор слів",
        uiInteractions: "Взаємодія з інтерфейсом",
        buttonTapsNavigation: "Звуки натискань і навігації",
        achievements: "Досягнення",
        levelUpFanfares: "Фанфари за підвищення рівня та серії",
        ambientAudio: "Фонове аудіо",
        backgroundAtmospheric: "Фонові атмосферні звуки",

        // Sync
        cloudSync: "Хмарна синхронізація",
        backupRestore: "Резервне копіювання та відновлення прогресу",
        upload: "Завантажити",
        download: "Завантажити",
        lastSynced: "Остання синхронізація:",
        never: "Ніколи",
        justNow: "Щойно",
        changesPending: "Є незбережені зміни",
        dataUploaded: "Дані успішно завантажено",
        dataDownloaded: "Дані успішно отримано",
        syncSecurityNote: "Ваші дані зберігаються надійно. Для синхронізації потрібне інтернет-з'єднання.",
        minAgo: "хв тому",
        hoursAgo: "год тому",
        daysAgo: "дн тому",

        // Sign Out
        connected: "Підключено",
        offline: "Офлайн",
        signOutRequiresInternet: "Для виходу потрібен інтернет",
        email: "Електронна пошта",
        name: "Ім'я",
        membership: "Підписка",
        freeTier: "Безкоштовний план",
        areYouSure: "Ви впевнені?",
        progressWillBeSaved: "Ваш прогрес буде збережено перед виходом.",
        savingProgress: "Збереження прогресу\u{2026}",
        clearingLocalData: "Очищення локальних даних\u{2026}",
        signingOut: "Вихід із системи\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Пульсуючі сфери",
        ambientBackgroundAnimation: "Фонова анімація оточення",
        raveMode: "Режим рейву",
        rapidColorCycling: "Швидка зміна кольорів через усі схеми",
        colorScheme: "Кольорова схема",
        intensity: "Інтенсивність",
        subtle: "Ледь помітно",
        balanced: "Збалансовано",
        celestial: "Небесно",
        speed: "Швидкість",
        calm: "Спокійно",
        flowing: "Плавно",
        swift_: "Жваво",
        perfectStillness: "Ідеальний спокій",
        gentleAndPeaceful: "М'яко і спокійно",
        balancedRhythm: "Збалансований ритм",
        quickAndEnergetic: "Швидко та енергійно",

        // Quantum Flow
        quantumFlow: "Квантовий потік",
        dynamicParticleAnimation: "Динамічна анімація частинок",
        scene: "Сцена",
        particleDensity: "Щільність частинок",
        sparse: "Рідко",
        dense: "Щільно",
        flowSpeed: "Швидкість потоку",
        serene: "Мирно",
        rhythmic: "Ритмічно",
        energetic: "Енергійно",
        exitPreview: "Закрити попередній перегляд",

        // Nebula Drift
        nebulaDrift: "Дрейф туманності",
        cosmicNebulaBackground: "Фоновий шар космічної туманності",
        nebulaOptimizedDarkMode: "Дрейф туманності оптимізовано для темної теми",
        nebulaPreset: "Пресет туманності",
        nebulaIntensity: "Інтенсивність туманності",
        vivid: "Яскраво",
        driftSpeed: "Швидкість дрейфу",
        frozen: "Заморожено",
        nebulaDescLagoon: "Ефірні рожево-фіолетові хмари, де новонароджені зорі спалахують серед стовпів космічного пилу",
        nebulaDescCelestial: "Нескінченний бірюзовий океан сяйного газу, що мерехтить відблисками зоряного світла",
        nebulaDescAndromeda: "Трильйон сонць завис на краю галактики, бурштинове світло розчиняється в глибокому індиго космосу",
        nebulaDescSolarAurora: "Золоті стрічки заряджених частинок ллються крізь магнітні поля, забарвлюючи порожнечу теплом",
        nebulaDescSpiralHalo: "Сто мільярдів зірок кружляють у досконалій гармонії, їхнє фіолетове сяйво вкриває гравітаційні стежки",
        nebulaDescStarburst: "Яскравий кільцевий спалах зореутворення, електрично-сині та маджентові дуги палають сяйною енергією",

        // Membership
        plansAndPricing: "Плани та ціни",
        investInYour: "Інвестуйте у своє",
        languageMastery: "Володіння мовою",
        membershipSubtitle: "Приєднуйтесь до тисяч людей, які навчаються розумніше, а не важче.",
        monthly: "Щомісяця",
        yearlyDiscount: "Щорічно  -17%",
        featureComparison: "Порівняння можливостей",
        feature: "Функція",
        free: "Безкоштовно",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Часті запитання",
        secure: "Безпечно",
        dayRefund: "30-денне повернення",
        cancelAnytime: "Скасування будь-коли",
        pricesShownUSD: "Ціни вказано в USD. Можуть застосовуватися податки.",
        popular: "ПОПУЛЯРНЕ",
        starter: "Початковий",
        beginYourJourney: "Розпочніть свій шлях",
        masterLanguagesFaster: "Опановуйте мови швидше",
        unlockFullPotential: "Розкрийте свій повний потенціал",
        ultimateExperience: "Найкращий досвід",
        currentPlan: "Поточний план",
        getStarted: "Розпочати",
        startPro: "Почати Pro",
        upgradeToElite: "Перейти на Elite",
        ascendToRoyal: "Піднятися до Royal",

        // Game Type Names
        gameFlashCards: "Флеш-картки",
        gameGrammar: "Граматика",
        gameWordBuilder: "Конструктор слів",

        // Additional UI
        languageMasteryEngine: "Рушій Опанування Мов",
        user: "Користувач",
        perMonth: "/міс.",
        perYear: "/рік",

        // Membership Feature Names
        featureLanguagePairs: "Мовні Пари",
        featureDailyPractice: "Щоденна Практика",
        featureGameModes: "Режими Гри",
        featureBreathingOrbs: "Сфери Дихання",
        featureQuantumFlow: "Квантовий Потік",
        featureNebulaDrift: "Дрейф Туманності",
        featureOfflineMode: "Офлайн Режим",
        featureCloudSync: "Хмарна Синхронізація",
        featurePrioritySupport: "Пріоритетна Підтримка",
        unlimited: "Необмежено",
        allModes: "Усі 3",
        scheme1: "1 схема",
        schemes3: "3 схеми",
        allSchemes: "Усі схеми",
        scenes2: "2 сцени",
        allScenes: "Усі сцени",
        presets3: "3 пресети",
        allPresets: "Усі пресети",
        min15: "15 хв",

        // Offline Mode / Connectivity
        offlineMode: "Офлайн-режим",
        offlineModeDescription: "Використовуйте контент без підключення до інтернету",
        offlineModeLockedDescription: "Оновіть до Pro для використання контенту офлайн",
        connectToUse: "Підключіться для використання контенту",
        connectivityRequired: "Безкоштовний план потребує підключення до інтернету для доступу до контенту",
        offlineModeInfo: "Коли офлайн-режим увімкнено, контент доступний без мережевого підключення. Плани Pro та вище дозволяють навчатися будь-де.",
        offlineModeDisabled: "Офлайн-режим вимкнено",
        offlineModeDisabledDetail: "Ваш план більше не включає офлайн-доступ",
        offlineModeActive: "Офлайн-режим активний",
        offlineModeIncluded: "Ваша підписка включає офлайн-доступ",
        onlineOnly: "Тільки онлайн",
        offlineModeActivated: "Офлайн-режим активовано",
        offlineModeActivatedDetail: "Офлайн-доступ тепер доступний",

        // MARK: - Upgrade Prompts
        unlockPremium: "Розблокувати Premium",
        viewPlans: "Переглянути плани",
        maybeLater: "Може пізніше",
        requires: "Потребує",
        learnMore: "Дізнатися більше",
        hideForever: "Приховати назавжди",
        dontShowAgain: "Більше не показувати",

        // MARK: - Royal Trial
        trialActivated: "Пробну Версію Активовано!",
        trialWelcomeMessage: "Ласкаво просимо до 14 днів повного доступу Royal. Усі преміум-функції ваші.",
        trialDuration: "14 Днів Доступу Royal",
        trialAfterExpiry: "Через 14 днів ви перейдете на безкоштовний план. Без оплати.",
        trialStartExploring: "Почати Дослідження",
        trialBannerTitle: "Пробна Версія Royal",
        trialExpiringToday: "Закінчується сьогодні",
        trialOneDayLeft: "Залишився 1 день",
        trialDaysLeft: "днів залишилось",
        trialEndedTitle: "Ваша Пробна Версія Закінчилась",
        trialEndedSubtitle: "Дякуємо за випробування Royal! Ваш прогрес у безпеці.",
        trialYourProgress: "Ваш Прогрес за Пробний Період",
        trialLevel: "Рівень",
        trialStreak: "Серія",
        trialYouStillHave: "Ви Все Ще Маєте",
        trialChoosePlan: "Обрати План",
        trialContinueFree: "Продовжити Безкоштовно",
        trialCompleted: "Пробну Версію Завершено",
        trialCompletedTagline: "Ви спробували Royal",
        trialStartFree: "Почати Безкоштовну Пробну Версію",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Ласкаво просимо, \($0)!" },
        daysLeftInTrial: { "\($0) днів пробної версії залишилось" },
        thirtyMinPerDay: "30 хв/день",
        resetsIn: { "Оновиться через \($0)" },
        nowPlaying: "Відтворення",
        paused: "Призупинено",

        // MARK: - Game Session Results
        xpBonus: "Бонус XP",
        timeSpentLabel: "Час",
        streakActive: "Активна",
        streakLabel: "Серія",
        vsPreviousSession: "порівняно з попередньою",
        keepImproving: "Продовжуйте покращуватися кожну сесію!",
        recentPerformance: "Останні результати",
        last7Sessions: "Останні 7 сесій",
        areasToImprove: "Що покращити",
        reviewIncorrect: { "Переглянути \($0) неправильних відповідей" },
        shareResult: "Поділитися результатом",
        availableOn: { "Доступно на \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "Щоденний XP",
        last7Days: "Останні 7 днів",
        weeklyTrend: "Тижневий Тренд",
        thisWeekVsLastWeek: "Цей тиждень проти минулого",
        thisWeekLabel: "Цей тиждень",
        lastWeekLabel: "Минулий тиждень",
        totalThisWeek: "Загалом цього тижня",
        accuracyHeatmap: "Карта Точності",
        accuracyByCategory: "Точність за категоріями",
        playSessionsToSeeData: "Грайте щоб побачити дані",
        monthlyReport: "Місячний Звіт",
        last30Days: "Останні 30 днів",
        activeDaysLabel: "Активні Дні",
        milestonePredictionsTitle: "Прогнози Досягнень",
        basedOnYourPace: "На основі вашого темпу",
        allMilestonesReached: "Всі досягнення отримано!",
        tapToUpgrade: "Натисніть для покращення",
        unlockFeature: "Розблокувати цю функцію",
        gameBreakdownDesc: "Дізнайтесь, де ви найкращі — відстежуйте бали, точність і час у кожному режимі гри",
        dailyXPChartDesc: "Візуалізуйте свій прогрес — спостерігайте за щоденним XP протягом тижня",
        weeklyTrendDesc: "Порівняйте цей тиждень з минулим і виявіть патерни вашого зростання",
        accuracyHeatmapDesc: "Миттєво визначте свої найсильніші та найслабші категорії одним поглядом",
        monthlyReportDesc: "Ваш персональний огляд за 30 днів — сесії, серії, точність та активні дні",
        milestonePredictionsDesc: "Дізнайтесь, коли ви досягнете наступного рубежу на основі вашого темпу навчання",
        exportData: "Експорт Даних",
        exportDataDesc: "Завантажте історію навчання — переглядайте прогрес офлайн, діліться з репетиторами або зберігайте особистий запис",
        exportAsCSV: "Експорт як CSV",
        exportAsJSON: "Експорт як JSON",
        exportAsPDF: "Експорт як PDF",
        exportReady: "Ваші дані готові до поширення",
        noDataToExport: "Немає даних для експорту",
        sessionsLabel: "Сесії",
        learningInsights: "Аналітика Навчання",
        insightsDesc: "Розблокуйте глибоку аналітику — відкрийте оптимальні години навчання, відстежуйте опанування за категоріями та прогнозуйте часову лінію володіння",
        optimalPracticeTimes: "Оптимальні Години Практики",
        bestTimeToLearn: "Ваш найкращий час для навчання",
        categoryMastery: "Опанування Категорій",
        masteryByCategory: "Опанування за категоріями",
        retentionCurve: "Крива Запам’ятовування",
        retentionOverTime: "Запам’ятовування з часом",
        fluencyTimeline: "Часова Лінія Володіння",
        predictedMilestones: "Прогнозовані досягнення",
        morning: "Ранок",
        afternoon: "Після обіду",
        evening: "Вечір",
        night: "Ніч",
        needMoreData: "Зіграйте більше сесій для аналітики",
        upgradedExclamation: "Покращено!",
        tierChangedExclamation: "Ласкаво просимо!",
        upgradeMessagePro: "Ви говорите мовою прогресу — кожен урок формує ваш голос у світі.",
        upgradeMessageElite: "Ваші слова несуть вагу відданості — досконалість стає вашою рідною мовою.",
        upgradeMessageRoyal: "Ви увінчали свою подорож словами — мова легенд належить вам.",
        upgradeMessageTrial: "Королівський розділ починається — повна історія вашого мовного потенціалу чекає.",
        // MARK: - Legal Consent
        legalConsentTitle: "Перш ніж почати",
        legalConsentSubtitle: "Будь ласка, ознайомтеся з нашими правилами, щоб продовжити користування LumenLingo",
        privacyPolicyTitle: "Політика конфіденційності",
        termsOfServiceTitle: "Умови використання",
        legalVersion: "Версія 2.0",
        legalLastUpdated: "Останнє оновлення: 23 березня 2026",
        legalPrivacySummary: "LumenLingo керується LumenShore Ltd. Ми поважаємо вашу конфіденційність і зобов'язуємося захищати ваші персональні дані. Ця політика охоплює наш веб-сайт та додаток iOS.",
        legalTermsSummary: "Ці Умови використання регулюють користування мобільним додатком LumenLingo, який керується LumenShore Ltd. Використовуючи LumenLingo, ви погоджуєтесь з цими Умовами.",
        legalPrivacyHighlight1: "Ваші дані навчання залишаються на вашому пристрої та особистому обліковому записі iCloud",
        legalPrivacyHighlight2: "Ми використовуємо Vercel Analytics без cookies — жодних відстежувальних cookies на нашому сайті",
        legalPrivacyHighlight3: "Sentry допомагає нам виправляти помилки (запис сеансу потребує згоди)",
        legalPrivacyHighlight4: "Ми ніколи не продаємо ваші персональні дані третім сторонам",
        legalTermsHighlight1: "Доступні безкоштовний та преміум плани — підписки керуються через Apple",
        legalTermsHighlight2: "Ваш контент та прогрес навчання належать вам",
        legalTermsHighlight3: "Ми можемо використовувати агреговані анонімні дані для покращення продукту",
        legalTermsHighlight4: "Регулюється законодавством Англії та Уельсу",
        legalAcceptAll: "Я погоджуюсь",
        legalDecline: "Відхилити",
        legalDeclineTitle: "Ви впевнені?",
        legalDeclineMessage: "Для використання LumenLingo необхідно прийняти нашу Політику конфіденційності та Умови використання.",
        legalDeclineConfirm: "Відхилити та вийти",
        legalReadFull: "Читати повну політику",
        legalScrollToAccept: "Прокрутіть для перегляду",

        // MARK: - EULA
        eulaTitle: "Ліцензійна угода кінцевого користувача",
        eulaSummary: "Ця ліцензійна угода регулює використання вами додатку LumenLingo, який розповсюджується через Apple App Store компанією LumenShore Ltd.",
        eulaHighlight1: "Невиключна, відкликна ліцензія для особистого вивчення мов",
        eulaHighlight2: "Рівневий доступ — безкоштовне, Pro, Elite та Royal членство",
        eulaHighlight3: "Ваші дані навчання належать вам; контент додатку належить нам",
        eulaHighlight4: "Умови, специфічні для Apple, включені відповідно до вимог App Store",

        // MARK: - Subscription Disclosure
        subscriptionAutoRenew: "Підписки автоматично поновлюються щомісяця, якщо не скасовані щонайменше за 24 години до закінчення поточного періоду.",
        subscriptionPaymentNotice: "Оплата буде списана з вашого облікового запису Apple ID при підтвердженні покупки.",
        subscriptionManageCancel: "Керуйте або скасовуйте в Налаштування → Apple ID → Підписки.",
        subscriptionTrialNotice: "14-денна безкоштовна пробна версія Royal. Після пробного періоду переходить на безкоштовний план.",
        restorePurchases: "Відновити покупки",
        subscriptionLegalPrefix: "Підписуючись, ви погоджуєтесь з нашими",
        subscriptionLegalAnd: "та"
,

        // MARK: - Account Deletion
        deleteAccount: "Видалити обліковий запис",
        deleteAccountWarning: "Це назавжди видалить усі ваші дані навчання, прогрес, серії та налаштування. Цю дію не можна скасувати.",
        deleteAccountConfirm: "Видалити все",
        deletingAccount: "Видалення облікового запису…",
        clearingUserData: "Очищення даних користувача",
        accountDeleted: "Обліковий запис видалено",

        // MARK: - GDPR Data Export
        gdprExportTitle: "Експортувати мої дані",
        gdprExportDesc: "Завантажте всі ваші персональні дані у машинозчитуваному форматі JSON. Це ваше право згідно зі статтею 20 GDPR — безкоштовно для всіх користувачів.",
        gdprExportButton: "Експортувати персональні дані",
        gdprExportSuccess: "Дані успішно експортовано",
        gdprExportEmpty: "Немає персональних даних для експорту",

        trademarkAttribution: "Apple, the Apple logo, iPhone, iPad, App Store, iCloud, Apple ID, and iOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions.",

        companyName: "Lumenshore Limited",
        companyNumber: "Номер компанії 09607326",
        companyRegistration: "Зареєстрована в Англії та Уельсі",
        companyAddress: "Windsor House, Troon Way Business Centre, Humberstone Lane, Leicester, England, LE4 9HA",
        companyVAT: "Реєстраційний номер ПДВ: GB 270411929",

        cookiePolicyTitle: "Політика файлів cookie",
        legalUpdated: "Оновлено березень 2025",

        viewMyDataTitle: "Переглянути мої дані",
        viewMyDataDesc: "Дізнайтеся, які дані зберігає LumenLingo про вас",
        dataProfileInfo: "Інформація профілю",
        dataGameRecords: "Записи ігрового прогресу",
        dataMasteredItems: "Засвоєні елементи",
        dataFavorites: "Улюблені категорії",
        dataICloudSync: "Синхронізація iCloud",
        dataEnabled: "Увімкнено",
        dataDisabled: "Вимкнено",
        dataStorageEstimate: "Оцінка сховища"
    )
}