import Foundation

extension AppStrings {
    static let english = AppStrings(
        // Tabs
        tabHome: "Home",
        tabStats: "Stats",
        tabPremium: "Premium",
        tabProfile: "Profile",

        // Dashboard
        greeting: { "Hello, \($0)!" },
        goodMorning: "Good morning",
        goodAfternoon: "Good afternoon",
        goodEvening: "Good evening",
        goodNight: "Good night",
        readyForAdventure: "Ready for a new adventure?",
        level: "Level",
        totalXP: "Total XP",
        activeDays: "Active Days",
        chooseYourAdventure: "Choose Your Adventure",
        startGameToBoost: "Start a game to boost your skills",
        flashCards: "Flash Cards",
        flashCardsDescription: "Master new vocabulary with interactive flip cards and spaced repetition",
        masterNewWords: "Master New Words",
        grammarChallenge: "Grammar Challenge",
        grammarDescription: "Test your knowledge with challenging questions and grammar rules",
        testYourSkills: "Test Your Skills",
        wordConstructor: "Word Constructor",
        wordBuilderDescription: "Construct words letter by letter from scrambled clues and hints",
        craftAndDiscover: "Craft & Discover",
        recentActivity: "Recent Activity",
        resetProgress: "Reset Progress",
        resetProgressMessage: "This will erase all your XP, levels, streaks, game history, and mastered content. This action cannot be undone.",
        progressReset: "Progress has been reset",
        startFreshDescription: "Clear all your progress, XP, streaks, and game history to start your learning journey from scratch.",

        // Language Selection
        languages: "Languages",
        cancel: "Cancel",
        searchLanguages: "Search languages\u{2026}",
        chooseYourLanguages: "Choose Your Languages",
        selectWhatYouKnow: "Select what you know and what you're learning",
        iSpeak: "I speak",
        imLearning: "I'm learning",
        noLanguagesAvailable: "No languages available for this source.",
        confirm: "Confirm:",
        done: "Done",
        languagesAvailable: "languages available",
        startYourAdventure: "Start Your Adventure",
        keepLearning: "Keep Learning",

        // Categories
        back: "Back",
        searchCategories: "Search categories",
        noCategories: "No Categories",
        noFavouritesYet: "No Favourites Yet",
        allComplete: "All Complete!",
        noResults: "No Results",
        tapHeartToSave: "Tap the heart on any category to save it here",
        youveFinishedEverything: "You've finished everything — nice work!",
        tryDifferentSearch: "Try a different search term",
        categoriesWillAppear: "Categories will appear once content is loaded",
        clearFilters: "Clear Filters",
        items: "items",
        complete: "Complete",
        doubleTapToStart: "Double tap to start",

        // Flash Cards
        loadingCards: "Loading cards\u{2026}",
        tapToReveal: "Tap to reveal",
        stillLearning: "Still Learning",
        gotIt: "Got It",
        noCardsAvailable: "No cards available",
        goBack: "Go Back",

        // Grammar
        loadingQuestions: "Loading questions\u{2026}",
        grammarTip: "Grammar Tip",
        next: "Next",
        noQuestionsAvailable: "No questions available",

        // Word Builder
        loadingWords: "Loading words\u{2026}",
        buildTheWord: "Build the word",
        availableLetters: "Available Letters",
        undo: "Undo",
        clear: "Clear",
        check: "Check",
        hint: "Hint",
        noWordsAvailable: "No words available",

        // Game Complete
        excellent: "Excellent!",
        greatJob: "Great Job!",
        goodWork: "Good Work!",
        keepGoing: "Keep Going!",
        excellentSubtitle: "Outstanding performance! You're a natural!",
        greatJobSubtitle: "Impressive work! Keep up the momentum!",
        goodWorkSubtitle: "Solid effort! Practice makes perfect!",
        keepGoingSubtitle: "Every session makes you better. Don't give up!",
        points: "points",
        accuracy: "Accuracy",
        correct: "Correct",
        toReview: "To Review",
        playAgain: "Play Again",
        backToCategories: "Back to Categories",

        // Journey
        yourLearningJourney: "Your Learning Journey",
        trackYourProgress: "Track your progress and celebrate achievements",
        milestones: "Milestones",
        firstSteps: "First Steps",
        gettingStarted: "Getting Started",
        dedicatedLearner: "Dedicated Learner",
        wordWarrior: "Word Warrior",
        languageMaster: "Language Master",
        polyglotLegend: "Polyglot Legend",
        xpRequired: "XP required",
        overview: "Overview",
        sessions: "Sessions",
        streak: "Streak",
        gamePerformance: "Game Performance",
        currentStreak: "Current Streak",
        days: "days",
        keepLearningEveryDay: "Keep learning every day to maintain your streak!",

        // Profile
        appearance: "Appearance",
        sound: "Sound",
        sync: "Sync",
        signOut: "Sign Out",
        darkLight: "Dark/Light",
        orbs: "Orbs",
        quantum: "Quantum",
        nebula: "Nebula",
        learner: "Learner",
        xp: "XP",
        darkMode: "Dark Mode",
        cosmicDarkTheme: "Cosmic dark theme active",
        lightModeActive: "Light mode active",
        animationSpeed: "Animation Speed",
        slow: "Slow",
        normal: "Normal",
        fast: "Fast",
        languagePair: "Language Pair",
        version: "Version 1.0.0",
        madeWithLove: "Made with \u{2764}\u{FE0F} for language learners",

        // Sound Settings
        masterSound: "Master Sound",
        allSoundsEnabled: "All sounds enabled",
        allSoundsMuted: "All sounds muted",
        allGames: "All Games",
        toggleAllGameSounds: "Toggle all game category sounds",
        flashcardsSound: "Flashcards",
        grammarSound: "Grammar",
        wordBuilderSound: "Word Builder",
        uiInteractions: "UI Interactions",
        buttonTapsNavigation: "Button taps & navigation sounds",
        achievements: "Achievements",
        levelUpFanfares: "Level-up fanfares & streak bonuses",
        ambientAudio: "Ambient Audio",
        backgroundAtmospheric: "Background atmospheric sounds",

        // Sync
        cloudSync: "Cloud Sync",
        backupRestore: "Backup & restore your progress",
        upload: "Upload",
        download: "Download",
        lastSynced: "Last synced:",
        never: "Never",
        justNow: "Just now",
        changesPending: "Changes pending",
        dataUploaded: "Data uploaded successfully",
        dataDownloaded: "Data downloaded successfully",
        syncSecurityNote: "Your data is stored securely. Sync requires an internet connection.",
        minAgo: "min ago",
        hoursAgo: "hours ago",
        daysAgo: "days ago",

        // Sign Out
        connected: "Connected",
        offline: "Offline",
        signOutRequiresInternet: "Sign out requires internet",
        email: "Email",
        name: "Name",
        membership: "Membership",
        freeTier: "Free Tier",
        areYouSure: "Are you sure?",
        progressWillBeSaved: "Your progress will be saved before signing out.",
        savingProgress: "Saving progress\u{2026}",
        clearingLocalData: "Clearing local data\u{2026}",
        signingOut: "Signing out\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Breathing Orbs",
        ambientBackgroundAnimation: "Ambient background animation",
        raveMode: "Rave Mode",
        rapidColorCycling: "Rapid color cycling through all schemes",
        colorScheme: "Color Scheme",
        intensity: "Intensity",
        subtle: "Subtle",
        balanced: "Balanced",
        celestial: "Celestial",
        speed: "Speed",
        calm: "Calm",
        flowing: "Flowing",
        swift_: "Swift",
        perfectStillness: "Perfect stillness",
        gentleAndPeaceful: "Gentle and peaceful",
        balancedRhythm: "Balanced rhythm",
        quickAndEnergetic: "Quick and energetic",

        // Quantum Flow
        quantumFlow: "Quantum Flow",
        dynamicParticleAnimation: "Dynamic particle animation layer",
        scene: "Scene",
        particleDensity: "Particle Density",
        sparse: "Sparse",
        dense: "Dense",
        flowSpeed: "Flow Speed",
        serene: "Serene",
        rhythmic: "Rhythmic",
        energetic: "Energetic",
        exitPreview: "Exit Preview",

        // Nebula Drift
        nebulaDrift: "Nebula Drift",
        cosmicNebulaBackground: "Cosmic nebula background layer",
        nebulaOptimizedDarkMode: "Nebula Drift is optimized for Dark Mode",
        nebulaPreset: "Nebula Preset",
        nebulaIntensity: "Nebula Intensity",
        vivid: "Vivid",
        driftSpeed: "Drift Speed",
        frozen: "Frozen",

        // Membership
        plansAndPricing: "Plans & Pricing",
        investInYour: "Invest in Your",
        languageMastery: "Language Mastery",
        membershipSubtitle: "Join thousands who are learning smarter, not harder.",
        monthly: "Monthly",
        yearlyDiscount: "Yearly  -17%",
        featureComparison: "Feature Comparison",
        feature: "Feature",
        free: "Free",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Frequently Asked Questions",
        secure: "Secure",
        dayRefund: "30-day refund",
        cancelAnytime: "Cancel anytime",
        pricesShownUSD: "Prices shown in USD. Taxes may apply.",
        popular: "POPULAR",
        starter: "Starter",
        beginYourJourney: "Begin your journey",
        masterLanguagesFaster: "Master languages faster",
        unlockFullPotential: "Unlock your full potential",
        ultimateExperience: "The ultimate experience",
        currentPlan: "Current Plan",
        startPro: "Start Pro",
        upgradeToElite: "Upgrade to Elite",
        ascendToRoyal: "Ascend to Royal",

        // Game Type Names
        gameFlashCards: "Flash Cards",
        gameGrammar: "Grammar",
        gameWordBuilder: "Word Builder",

        // Additional UI
        languageMasteryEngine: "Language Mastery Engine",
        user: "User",
        perMonth: "/mo",
        perYear: "/yr",

        // Membership Feature Names
        featureLanguagePairs: "Language Pairs",
        featureDailyPractice: "Daily Practice",
        featureGameModes: "Game Modes",
        featureBreathingOrbs: "Breathing Orbs",
        featureQuantumFlow: "Quantum Flow",
        featureNebulaDrift: "Nebula Drift",
        featureOfflineMode: "Offline Mode",
        featureCloudSync: "Cloud Sync",
        featurePrioritySupport: "Priority Support",
        unlimited: "Unlimited",
        allModes: "All 3",
        scheme1: "1 scheme",
        schemes3: "3 schemes",
        allSchemes: "All schemes",
        scenes2: "2 scenes",
        allScenes: "All scenes",
        presets3: "3 presets",
        allPresets: "All presets",
        min15: "15 min"
    )
}
