import Foundation

extension AppStrings {
    static let spanish = AppStrings(
        // Tabs
        tabHome: "Inicio",
        tabStats: "Estadísticas",
        tabPremium: "Premium",
        tabProfile: "Perfil",

        // Dashboard
        greeting: { "¡Hola, \($0)!" },
        goodMorning: "Buenos días",
        goodAfternoon: "Buenas tardes",
        goodEvening: "Buenas tardes",
        goodNight: "Buenas noches",
        readyForAdventure: "¿Listo para una nueva aventura?",
        level: "Nivel",
        totalXP: "XP Total",
        activeDays: "Días Activos",
        chooseYourAdventure: "Elige Tu Aventura",
        startGameToBoost: "Comienza un juego para mejorar tus habilidades",
        flashCards: "Tarjetas",
        flashCardsDescription: "Domina vocabulario nuevo con tarjetas interactivas y repetición espaciada",
        masterNewWords: "Domina Palabras Nuevas",
        grammarChallenge: "Desafío Gramatical",
        grammarDescription: "Pon a prueba tus conocimientos con preguntas desafiantes y reglas gramaticales",
        testYourSkills: "Pon a Prueba Tus Habilidades",
        wordConstructor: "Constructor de Palabras",
        wordBuilderDescription: "Construye palabras letra por letra a partir de pistas y sugerencias",
        craftAndDiscover: "Crea y Descubre",
        recentActivity: "Actividad Reciente",

        // Language Selection
        languages: "Idiomas",
        cancel: "Cancelar",
        searchLanguages: "Buscar idiomas\u{2026}",
        chooseYourLanguages: "Elige Tus Idiomas",
        selectWhatYouKnow: "Selecciona lo que sabes y lo que estás aprendiendo",
        iSpeak: "Yo hablo",
        imLearning: "Estoy aprendiendo",
        noLanguagesAvailable: "No hay idiomas disponibles para este origen.",
        betaLanguagePairs: "Pares de Idiomas Beta",
        showExperimentalPairs: "Mostrar pares experimentales con contenido limitado",
        confirm: "Confirmar:",

        // Categories
        back: "Atrás",
        searchCategories: "Buscar categorías",
        noCategories: "Sin Categorías",
        noFavouritesYet: "Aún Sin Favoritos",
        allComplete: "¡Todo Completo!",
        noResults: "Sin Resultados",
        tapHeartToSave: "Toca el corazón en cualquier categoría para guardarla aquí",
        youveFinishedEverything: "¡Has terminado todo — buen trabajo!",
        tryDifferentSearch: "Prueba con un término de búsqueda diferente",
        categoriesWillAppear: "Las categorías aparecerán cuando el contenido esté cargado",
        clearFilters: "Limpiar Filtros",
        items: "elementos",
        complete: "Completo",
        doubleTapToStart: "Toca dos veces para comenzar",

        // Flash Cards
        loadingCards: "Cargando tarjetas\u{2026}",
        tapToReveal: "Toca para revelar",
        stillLearning: "Aún Aprendiendo",
        gotIt: "¡Entendido!",
        noCardsAvailable: "No hay tarjetas disponibles",
        goBack: "Volver",

        // Grammar
        loadingQuestions: "Cargando preguntas\u{2026}",
        grammarTip: "Consejo Gramatical",
        next: "Siguiente",
        noQuestionsAvailable: "No hay preguntas disponibles",

        // Word Builder
        loadingWords: "Cargando palabras\u{2026}",
        buildTheWord: "Construye la palabra",
        availableLetters: "Letras Disponibles",
        undo: "Deshacer",
        clear: "Borrar",
        check: "Comprobar",
        noWordsAvailable: "No hay palabras disponibles",

        // Game Complete
        excellent: "¡Excelente!",
        greatJob: "¡Gran Trabajo!",
        goodWork: "¡Buen Trabajo!",
        keepGoing: "¡Sigue Así!",
        excellentSubtitle: "¡Rendimiento sobresaliente! ¡Eres un talento natural!",
        greatJobSubtitle: "¡Trabajo impresionante! ¡Mantén el impulso!",
        goodWorkSubtitle: "¡Buen esfuerzo! ¡La práctica hace al maestro!",
        keepGoingSubtitle: "Cada sesión te hace mejor. ¡No te rindas!",
        points: "puntos",
        accuracy: "Precisión",
        correct: "Correcto",
        toReview: "Para Repasar",
        playAgain: "Jugar de Nuevo",
        backToCategories: "Volver a Categorías",

        // Journey
        yourLearningJourney: "Tu Viaje de Aprendizaje",
        trackYourProgress: "Sigue tu progreso y celebra tus logros",
        milestones: "Hitos",
        firstSteps: "Primeros Pasos",
        gettingStarted: "Empezando",
        dedicatedLearner: "Estudiante Dedicado",
        wordWarrior: "Guerrero de las Palabras",
        languageMaster: "Maestro del Idioma",
        polyglotLegend: "Leyenda Políglota",
        xpRequired: "XP requeridos",
        overview: "Resumen",
        sessions: "Sesiones",
        streak: "Racha",
        gamePerformance: "Rendimiento del Juego",
        currentStreak: "Racha Actual",
        days: "días",
        keepLearningEveryDay: "¡Sigue aprendiendo cada día para mantener tu racha!",

        // Profile
        appearance: "Apariencia",
        sound: "Sonido",
        beta: "Beta",
        sync: "Sincronizar",
        signOut: "Cerrar Sesión",
        darkLight: "Oscuro/Claro",
        orbs: "Orbes",
        quantum: "Quantum",
        nebula: "Nebulosa",
        learner: "Estudiante",
        xp: "XP",
        darkMode: "Modo Oscuro",
        cosmicDarkTheme: "Tema cósmico oscuro activo",
        lightModeActive: "Modo claro activo",
        animationSpeed: "Velocidad de Animación",
        slow: "Lento",
        normal: "Normal",
        fast: "Rápido",
        languagePair: "Par de Idiomas",
        version: "Versión 1.0.0",
        madeWithLove: "Hecho con \u{2764}\u{FE0F} para estudiantes de idiomas",

        // Sound Settings
        masterSound: "Sonido Principal",
        allSoundsEnabled: "Todos los sonidos activados",
        allSoundsMuted: "Todos los sonidos silenciados",
        allGames: "Todos los Juegos",
        toggleAllGameSounds: "Activar/desactivar todos los sonidos de juego",
        flashcardsSound: "Tarjetas",
        grammarSound: "Gramática",
        wordBuilderSound: "Constructor de Palabras",
        uiInteractions: "Interacciones de UI",
        buttonTapsNavigation: "Toques de botón y sonidos de navegación",
        achievements: "Logros",
        levelUpFanfares: "Fanfarrias de subida de nivel y bonificaciones de racha",
        ambientAudio: "Audio Ambiental",
        backgroundAtmospheric: "Sonidos atmosféricos de fondo",

        // Beta Languages
        betaLanguages: "Idiomas Beta",
        experimentalLanguagePairs: "Pares de idiomas experimentales",
        experimentalFeatures: "Funciones Experimentales",
        betaLimitedContent: "Los idiomas beta pueden tener contenido limitado o peculiaridades de traducción ocasionales.",
        coreLanguages: "Idiomas Principales",
        alwaysOn: "Siempre activo",
        active: "Activo",
        experimentalLanguagesSection: "Idiomas Experimentales",
        on: "Sí",
        off: "No",

        // Sync
        cloudSync: "Sincronización en la Nube",
        backupRestore: "Respalda y restaura tu progreso",
        upload: "Subir",
        download: "Descargar",
        lastSynced: "Última sincronización:",
        never: "Nunca",
        justNow: "Justo ahora",
        changesPending: "Cambios pendientes",
        dataUploaded: "Datos subidos correctamente",
        dataDownloaded: "Datos descargados correctamente",
        syncSecurityNote: "Tus datos se almacenan de forma segura. La sincronización requiere conexión a internet.",
        minAgo: "min atrás",
        hoursAgo: "horas atrás",
        daysAgo: "días atrás",

        // Sign Out
        connected: "Conectado",
        offline: "Sin conexión",
        signOutRequiresInternet: "Cerrar sesión requiere internet",
        email: "Correo",
        name: "Nombre",
        membership: "Membresía",
        freeTier: "Plan Gratuito",
        areYouSure: "¿Estás seguro?",
        progressWillBeSaved: "Tu progreso se guardará antes de cerrar sesión.",
        savingProgress: "Guardando progreso\u{2026}",
        clearingLocalData: "Borrando datos locales\u{2026}",
        signingOut: "Cerrando sesión\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Orbes Respirantes",
        ambientBackgroundAnimation: "Animación de fondo ambiental",
        raveMode: "Modo Rave",
        rapidColorCycling: "Ciclo rápido de colores por todos los esquemas",
        colorScheme: "Esquema de Colores",
        intensity: "Intensidad",
        subtle: "Sutil",
        balanced: "Equilibrado",
        celestial: "Celestial",
        speed: "Velocidad",
        calm: "Calma",
        flowing: "Fluido",
        swift_: "Veloz",
        perfectStillness: "Quietud perfecta",
        gentleAndPeaceful: "Suave y tranquilo",
        balancedRhythm: "Ritmo equilibrado",
        quickAndEnergetic: "Rápido y enérgico",

        // Quantum Flow
        quantumFlow: "Flujo Cuántico",
        dynamicParticleAnimation: "Capa de animación de partículas dinámicas",
        scene: "Escena",
        particleDensity: "Densidad de Partículas",
        sparse: "Disperso",
        dense: "Denso",
        flowSpeed: "Velocidad del Flujo",
        serene: "Sereno",
        rhythmic: "Rítmico",
        energetic: "Enérgico",
        exitPreview: "Salir de Vista Previa",

        // Nebula Drift
        nebulaDrift: "Deriva de Nebulosa",
        cosmicNebulaBackground: "Capa de fondo de nebulosa cósmica",
        nebulaOptimizedDarkMode: "Deriva de Nebulosa está optimizada para el Modo Oscuro",
        nebulaPreset: "Preset de Nebulosa",
        nebulaIntensity: "Intensidad de Nebulosa",
        vivid: "Vívido",
        driftSpeed: "Velocidad de Deriva",
        frozen: "Congelado",

        // Membership
        plansAndPricing: "Planes y Precios",
        investInYour: "Invierte en Tu",
        languageMastery: "Dominio del Idioma",
        membershipSubtitle: "Únete a miles que aprenden de forma más inteligente, no más difícil.\nGarantía de devolución de 30 días \u{00B7} Cancela en cualquier momento",
        monthly: "Mensual",
        yearlyDiscount: "Anual  -17%",
        featureComparison: "Comparación de Funciones",
        feature: "Función",
        free: "Gratis",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Preguntas Frecuentes",
        secure: "Seguro",
        dayRefund: "Devolución en 30 días",
        cancelAnytime: "Cancela en cualquier momento",
        pricesShownUSD: "Precios en USD. Pueden aplicarse impuestos.",
        popular: "POPULAR",
        starter: "Inicial",
        beginYourJourney: "Comienza tu viaje",
        masterLanguagesFaster: "Domina idiomas más rápido",
        unlockFullPotential: "Desbloquea todo tu potencial",
        ultimateExperience: "La experiencia definitiva",
        currentPlan: "Plan Actual",
        startPro: "Comenzar Pro",
        upgradeToElite: "Mejorar a Elite",
        ascendToRoyal: "Ascender a Royal",

        // Game Type Names
        gameFlashCards: "Tarjetas",
        gameGrammar: "Gramática",
        gameWordBuilder: "Constructor de Palabras",

        // Additional UI
        languageMasteryEngine: "Motor de Dominio Lingüístico",
        user: "Usuario",
        perMonth: "/mes",
        perYear: "/año",

        // Membership Feature Names
        featureLanguagePairs: "Pares de Idiomas",
        featureDailyPractice: "Práctica Diaria",
        featureGameModes: "Modos de Juego",
        featureBreathingOrbs: "Orbes Respirantes",
        featureQuantumFlow: "Flujo Cuántico",
        featureNebulaDrift: "Deriva Nebular",
        featureOfflineMode: "Modo Sin Conexión",
        featureCloudSync: "Sincronización en la Nube",
        featurePrioritySupport: "Soporte Prioritario",
        unlimited: "Ilimitado",
        allModes: "Los 3",
        scheme1: "1 esquema",
        schemes3: "3 esquemas",
        allSchemes: "Todos los esquemas",
        scenes2: "2 escenas",
        allScenes: "Todas las escenas",
        presets3: "3 preajustes",
        allPresets: "Todos los preajustes",
        min15: "15 min"
    )
}
