import Foundation

extension AppStrings {
    static let spanish = AppStrings(
        // Tabs
        tabHome: "Inicio",
        tabStats: "Estadísticas",
        tabPremium: "Premium",
        tabSettings: "Ajustes",
        tabProfile: "Perfil",

        // Settings Header
        settingsHeaderTitle: "Preferencias",
        settingsHeaderSubtitle: "Personaliza tu experiencia",

        // Dashboard
        greeting: { "¡Hola, \($0)!" },
        goodMorning: "Buenos días",
        goodAfternoon: "Buenas tardes",
        goodEvening: "Buenas tardes",
        goodNight: "Buenas noches",
        readyForAdventure: "¿Listo para una nueva aventura?",
        level: "Nivel",
        totalXP: "XP Total",
        activeDays: "Días Activos",
        chooseYourAdventure: "Elige Tu Aventura",
        startGameToBoost: "Comienza un juego para mejorar tus habilidades",
        flashCards: "Tarjetas",
        flashCardsDescription: "Domina vocabulario nuevo con tarjetas interactivas y repetición espaciada",
        masterNewWords: "Domina Palabras Nuevas",
        grammarChallenge: "Desafío Gramatical",
        grammarDescription: "Pon a prueba tus conocimientos con preguntas desafiantes y reglas gramaticales",
        testYourSkills: "Pon a Prueba Tus Habilidades",
        wordConstructor: "Constructor de Palabras",
        wordBuilderDescription: "Construye palabras letra por letra a partir de pistas y sugerencias",
        craftAndDiscover: "Crea y Descubre",
        recentActivity: "Actividad Reciente",
        resetProgress: "Restablecer progreso",
        resetProgressMessage: "Esto borrará todos tus XP, niveles, rachas, historial de juegos y contenido dominado. Esta acción no se puede deshacer.",
        progressReset: "El progreso ha sido restablecido",
        startFreshDescription: "Borra todo tu progreso, XP, rachas e historial de juegos para comenzar tu aprendizaje desde cero.",

        // Language Selection
        languages: "Idiomas",
        cancel: "Cancelar",
        searchLanguages: "Buscar idiomas\u{2026}",
        chooseYourLanguages: "Elige Tus Idiomas",
        selectWhatYouKnow: "Selecciona lo que sabes y lo que estás aprendiendo",
        iSpeak: "Yo hablo",
        imLearning: "Estoy aprendiendo",
        noLanguagesAvailable: "No hay idiomas disponibles para este origen.",
        confirm: "Confirmar:",
        done: "Listo",
        languagesAvailable: "idiomas disponibles",
        startYourAdventure: "Comienza Tu Aventura",
        keepLearning: "Sigue Aprendiendo",

        // Categories
        back: "Atrás",
        searchCategories: "Buscar categorías",
        noCategories: "Sin Categorías",
        noFavouritesYet: "Aún Sin Favoritos",
        allComplete: "¡Todo Completo!",
        noResults: "Sin Resultados",
        tapHeartToSave: "Toca el corazón en cualquier categoría para guardarla aquí",
        youveFinishedEverything: "¡Has terminado todo — buen trabajo!",
        tryDifferentSearch: "Prueba con un término de búsqueda diferente",
        categoriesWillAppear: "Las categorías aparecerán cuando el contenido esté cargado",
        clearFilters: "Limpiar Filtros",
        items: "elementos",
        complete: "Completo",
        doubleTapToStart: "Toca dos veces para comenzar",

        // Flash Cards
        loadingCards: "Cargando tarjetas\u{2026}",
        tapToReveal: "Toca para revelar",
        stillLearning: "Aún Aprendiendo",
        gotIt: "¡Entendido!",
        noCardsAvailable: "No hay tarjetas disponibles",
        goBack: "Volver",

        // Grammar
        loadingQuestions: "Cargando preguntas\u{2026}",
        grammarTip: "Consejo Gramatical",
        next: "Siguiente",
        noQuestionsAvailable: "No hay preguntas disponibles",

        // Word Builder
        loadingWords: "Cargando palabras\u{2026}",
        buildTheWord: "Construye la palabra",
        availableLetters: "Letras Disponibles",
        undo: "Deshacer",
        clear: "Borrar",
        check: "Comprobar",
        hint: "Pista",
        noWordsAvailable: "No hay palabras disponibles",

        // Game Complete
        excellent: "¡Excelente!",
        greatJob: "¡Gran Trabajo!",
        goodWork: "¡Buen Trabajo!",
        keepGoing: "¡Sigue Así!",
        excellentSubtitle: "¡Rendimiento sobresaliente! ¡Eres un talento natural!",
        greatJobSubtitle: "¡Trabajo impresionante! ¡Mantén el impulso!",
        goodWorkSubtitle: "¡Buen esfuerzo! ¡La práctica hace al maestro!",
        keepGoingSubtitle: "Cada sesión te hace mejor. ¡No te rindas!",
        points: "puntos",
        accuracy: "Precisión",
        correct: "Correcto",
        toReview: "Para Repasar",
        playAgain: "Jugar de Nuevo",
        nextCategory: "Siguiente categoría",
        backToCategories: "Volver a Categorías",

        // Journey
        yourLearningJourney: "Tu Viaje de Aprendizaje",
        trackYourProgress: "Sigue tu progreso y celebra tus logros",
        milestones: "Hitos",
        firstSteps: "Primeros Pasos",
        gettingStarted: "Empezando",
        dedicatedLearner: "Estudiante Dedicado",
        risingStar: "Estrella en Ascenso",
        wordWarrior: "Guerrero de Palabras",
        knowledgeSeeker: "Buscador de Saber",
        sentenceCrafter: "Artesano de Frases",
        grammarGuardian: "Guardián Gramatical",
        vocabularyVirtuoso: "Virtuoso del Vocabulario",
        languageMaster: "Maestro del Idioma",
        fluencyPioneer: "Pionero de la Fluidez",
        polyglotLegend: "Leyenda Políglota",
        xpRequired: "XP requeridos",
        overview: "Resumen",
        sessions: "Sesiones",
        streak: "Racha",
        gamePerformance: "Rendimiento del Juego",
        currentStreak: "Racha Actual",
        days: "días",
        keepLearningEveryDay: "¡Sigue aprendiendo cada día para mantener tu racha!",

        // Profile
        appearance: "Apariencia",
        sound: "Sonido",
        sync: "Sincronizar",
        signOut: "Cerrar Sesión",
        darkLight: "Oscuro/Claro",
        orbs: "Orbes",
        quantum: "Quantum",
        nebula: "Nebulosa",
        learner: "Estudiante",
        xp: "XP",
        words: "Palabras",
        activityCalendar: "Calendario de actividad",
        dayStreak: "días consecutivos",
        darkMode: "Modo Oscuro",
        cosmicDarkTheme: "Noche cósmica",
        lightModeActive: "Isla tropical",
        animationSpeed: "Velocidad de Animación",
        slow: "Lento",
        normal: "Normal",
        fast: "Rápido",
        languagePair: "Par de Idiomas",
        version: "Versión 1.0.0",
        madeWithLove: "Hecho con \u{2764}\u{FE0F} para estudiantes de idiomas",

        // Sound Settings
        masterSound: "Sonido Principal",
        allSoundsEnabled: "Todos los sonidos activados",
        allSoundsMuted: "Todos los sonidos silenciados",
        allGames: "Todos los Juegos",
        toggleAllGameSounds: "Activar/desactivar todos los sonidos de juego",
        flashcardsSound: "Tarjetas",
        grammarSound: "Gramática",
        wordBuilderSound: "Constructor de Palabras",
        uiInteractions: "Interacciones de UI",
        buttonTapsNavigation: "Toques de botón y sonidos de navegación",
        achievements: "Logros",
        levelUpFanfares: "Fanfarrias de subida de nivel y bonificaciones de racha",
        ambientAudio: "Audio Ambiental",
        backgroundAtmospheric: "Sonidos atmosféricos de fondo",

        // Beta Languages
        // Sync
        cloudSync: "Sincronización en la Nube",
        backupRestore: "Respalda y restaura tu progreso",
        upload: "Subir",
        download: "Descargar",
        lastSynced: "Última sincronización:",
        never: "Nunca",
        justNow: "Justo ahora",
        changesPending: "Cambios pendientes",
        dataUploaded: "Datos subidos correctamente",
        dataDownloaded: "Datos descargados correctamente",
        syncSecurityNote: "Tus datos se almacenan de forma segura. La sincronización requiere conexión a internet.",
        minAgo: "min atrás",
        hoursAgo: "horas atrás",
        daysAgo: "días atrás",

        // Sign Out
        connected: "Conectado",
        offline: "Sin conexión",
        signOutRequiresInternet: "Cerrar sesión requiere internet",
        email: "Correo",
        name: "Nombre",
        membership: "Membresía",
        freeTier: "Plan Gratuito",
        areYouSure: "¿Estás seguro?",
        progressWillBeSaved: "Tu progreso se guardará antes de cerrar sesión.",
        savingProgress: "Guardando progreso\u{2026}",
        clearingLocalData: "Borrando datos locales\u{2026}",
        signingOut: "Cerrando sesión\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Orbes Respirantes",
        ambientBackgroundAnimation: "Animación de fondo ambiental",
        raveMode: "Modo Rave",
        rapidColorCycling: "Ciclo rápido de colores por todos los esquemas",
        colorScheme: "Esquema de Colores",
        intensity: "Intensidad",
        subtle: "Sutil",
        balanced: "Equilibrado",
        celestial: "Celestial",
        speed: "Velocidad",
        calm: "Calma",
        flowing: "Fluido",
        swift_: "Veloz",
        perfectStillness: "Quietud perfecta",
        gentleAndPeaceful: "Suave y tranquilo",
        balancedRhythm: "Ritmo equilibrado",
        quickAndEnergetic: "Rápido y enérgico",

        // Quantum Flow
        quantumFlow: "Flujo Cuántico",
        dynamicParticleAnimation: "Capa de animación de partículas dinámicas",
        scene: "Escena",
        particleDensity: "Densidad de Partículas",
        sparse: "Disperso",
        dense: "Denso",
        flowSpeed: "Velocidad del Flujo",
        serene: "Sereno",
        rhythmic: "Rítmico",
        energetic: "Enérgico",
        exitPreview: "Salir de Vista Previa",

        // Nebula Drift
        nebulaDrift: "Deriva de Nebulosa",
        cosmicNebulaBackground: "Capa de fondo de nebulosa cósmica",
        nebulaOptimizedDarkMode: "Deriva de Nebulosa está optimizada para el Modo Oscuro",
        nebulaPreset: "Preset de Nebulosa",
        nebulaIntensity: "Intensidad de Nebulosa",
        vivid: "Vívido",
        driftSpeed: "Velocidad de Deriva",
        frozen: "Congelado",
        nebulaDescLagoon: "Nubes etéreas rosa y violeta donde estrellas recién nacidas se encienden entre pilares de polvo cósmico",
        nebulaDescCelestial: "Un océano turquesa infinito de gas luminoso, resplandeciente con reflejos de luz estelar cian y verde azulado",
        nebulaDescAndromeda: "Un billón de soles suspendidos al borde de la galaxia, luz ámbar disolviéndose en el espacio índigo",
        nebulaDescSolarAurora: "Cintas doradas de partículas cargadas que caen por campos magnéticos, pintando el vacío con calidez",
        nebulaDescSpiralHalo: "Cien mil millones de estrellas en espiral perfecta, su brillo violeta trazando senderos gravitacionales",
        nebulaDescStarburst: "Un anillo brillante de rápida formación estelar, arcos azul eléctrico y magenta ardiendo con energía radiante",

        // Membership
        plansAndPricing: "Planes y Precios",
        investInYour: "Invierte en Tu",
        languageMastery: "Dominio del Idioma",
        membershipSubtitle: "Únete a miles que aprenden de forma más inteligente, no más difícil.",
        monthly: "Mensual",
        yearlyDiscount: "Anual  -17%",
        featureComparison: "Comparación de Funciones",
        feature: "Función",
        free: "Gratis",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Preguntas Frecuentes",
        secure: "Seguro",
        dayRefund: "Devolución en 30 días",
        cancelAnytime: "Cancela en cualquier momento",
        pricesShownUSD: "Precios en USD. Pueden aplicarse impuestos.",
        popular: "POPULAR",
        starter: "Inicial",
        beginYourJourney: "Comienza tu viaje",
        masterLanguagesFaster: "Domina idiomas más rápido",
        unlockFullPotential: "Desbloquea todo tu potencial",
        ultimateExperience: "La experiencia definitiva",
        currentPlan: "Plan Actual",
        getStarted: "Comenzar",
        startPro: "Comenzar Pro",
        upgradeToElite: "Mejorar a Elite",
        ascendToRoyal: "Ascender a Royal",

        // Game Type Names
        gameFlashCards: "Tarjetas",
        gameGrammar: "Gramática",
        gameWordBuilder: "Constructor de Palabras",

        // Additional UI
        languageMasteryEngine: "Motor de Dominio Lingüístico",
        user: "Usuario",
        perMonth: "/mes",
        perYear: "/año",

        // Membership Feature Names
        featureLanguagePairs: "Pares de Idiomas",
        featureDailyPractice: "Práctica Diaria",
        featureGameModes: "Modos de Juego",
        featureBreathingOrbs: "Orbes Respirantes",
        featureQuantumFlow: "Flujo Cuántico",
        featureNebulaDrift: "Deriva Nebular",
        featureOfflineMode: "Modo Sin Conexión",
        featureCloudSync: "Sincronización en la Nube",
        featurePrioritySupport: "Soporte Prioritario",
        unlimited: "Ilimitado",
        allModes: "Los 3",
        scheme1: "1 esquema",
        schemes3: "3 esquemas",
        allSchemes: "Todos los esquemas",
        scenes2: "2 escenas",
        allScenes: "Todas las escenas",
        presets3: "3 preajustes",
        allPresets: "Todos los preajustes",
        min15: "15 min",

        // Offline Mode / Connectivity
        offlineMode: "Modo sin conexión",
        offlineModeDescription: "Usa el contenido sin conexión a internet",
        offlineModeLockedDescription: "Actualiza a Pro para usar contenido sin conexión",
        connectToUse: "Conéctate para usar el contenido",
        connectivityRequired: "El nivel gratuito requiere conexión a internet para acceder al contenido",
        offlineModeInfo: "Cuando el modo sin conexión está activado, el contenido está disponible sin red. Los niveles Pro y superiores pueden aprender en cualquier lugar.",
        offlineModeDisabled: "Modo sin conexión desactivado",
        offlineModeDisabledDetail: "Tu nivel ya no incluye acceso sin conexión",
        offlineModeActive: "Modo sin conexión activo",
        offlineModeIncluded: "Tu suscripción incluye acceso sin conexión",
        onlineOnly: "Solo en línea",
        offlineModeActivated: "Modo sin conexión activado",
        offlineModeActivatedDetail: "El acceso sin conexión ya está disponible",

        // MARK: - Upgrade Prompts
        unlockPremium: "Desbloquear Premium",
        viewPlans: "Ver planes",
        maybeLater: "Quizás después",
        requires: "Requiere",
        learnMore: "Más información",
        hideForever: "Ocultar para siempre",
        dontShowAgain: "No mostrar de nuevo",

        // MARK: - Royal Trial
        trialActivated: "¡Prueba Activada!",
        trialWelcomeMessage: "Bienvenido a 14 días de acceso Royal completo. Todas las funciones premium son tuyas.",
        trialDuration: "14 Días de Acceso Royal",
        trialAfterExpiry: "Después de 14 días, pasarás al nivel Gratuito. Sin cargos.",
        trialStartExploring: "Empezar a Explorar",
        trialBannerTitle: "Prueba Royal",
        trialExpiringToday: "Expira hoy",
        trialOneDayLeft: "1 día restante",
        trialDaysLeft: "días restantes",
        trialEndedTitle: "Tu Prueba Ha Terminado",
        trialEndedSubtitle: "¡Gracias por probar Royal! Tu progreso está a salvo.",
        trialYourProgress: "Tu Progreso de Prueba",
        trialLevel: "Nivel",
        trialStreak: "Racha",
        trialYouStillHave: "Aún Tienes",
        trialChoosePlan: "Elegir un Plan",
        trialContinueFree: "Continuar con Gratuito",
        trialCompleted: "Prueba Completada",
        trialCompletedTagline: "Has experimentado Royal",
        trialStartFree: "Iniciar Prueba Gratuita",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Bienvenido, \($0)!" },
        daysLeftInTrial: { "\($0) días de prueba restantes" },
        thirtyMinPerDay: "30 min/día",
        resetsIn: { "Se reinicia en \($0)" },
        nowPlaying: "Reproduciendo",
        paused: "Pausado",

        // MARK: - Game Session Results
        xpBonus: "Bono de XP",
        timeSpentLabel: "Tiempo",
        streakActive: "Activo",
        streakLabel: "Racha",
        vsPreviousSession: "vs Sesión anterior",
        keepImproving: "¡Sigue mejorando cada sesión!",
        recentPerformance: "Rendimiento reciente",
        last7Sessions: "Últimas 7 sesiones",
        areasToImprove: "Áreas a mejorar",
        reviewIncorrect: { "Revisar \($0) respuestas incorrectas" },
        shareResult: "Compartir resultado",
        availableOn: { "Disponible en \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "XP Diario",
        last7Days: "Últimos 7 días",
        weeklyTrend: "Tendencia Semanal",
        thisWeekVsLastWeek: "Esta semana vs la anterior",
        thisWeekLabel: "Esta semana",
        lastWeekLabel: "Semana pasada",
        totalThisWeek: "Total esta semana",
        accuracyHeatmap: "Mapa de Precisión",
        accuracyByCategory: "Precisión por categoría",
        playSessionsToSeeData: "Juega sesiones para ver datos",
        monthlyReport: "Informe Mensual",
        last30Days: "Últimos 30 días",
        activeDaysLabel: "Días Activos",
        milestonePredictionsTitle: "Predicción de Hitos",
        basedOnYourPace: "Basado en tu ritmo actual",
        allMilestonesReached: "¡Todos los hitos alcanzados!",
        tapToUpgrade: "Toca para mejorar",
        unlockFeature: "Desbloquea esta función",
        gameBreakdownDesc: "Descubre dónde brillas — sigue puntuaciones, precisión y tiempo en cada modo de juego",
        dailyXPChartDesc: "Visualiza tu impulso — observa cómo se despliega tu XP diario a lo largo de la semana",
        weeklyTrendDesc: "Compara esta semana con la anterior y detecta los patrones que impulsan tu crecimiento",
        accuracyHeatmapDesc: "Revela al instante tus categorías más fuertes y débiles de un vistazo",
        monthlyReportDesc: "Tu resumen personalizado de 30 días — sesiones, rachas, precisión y días activos",
        milestonePredictionsDesc: "Descubre cuándo alcanzarás tu próximo hito según tu ritmo de aprendizaje",
        exportData: "Exportar Datos",
        exportDataDesc: "Descarga tu historial de aprendizaje — revisa el progreso sin conexión, comparte con tutores o guárdalo como registro personal",
        exportAsCSV: "Exportar como CSV",
        exportAsJSON: "Exportar como JSON",
        exportAsPDF: "Exportar como PDF",
        exportReady: "Tus datos están listos para compartir",
        noDataToExport: "Aún no hay datos para exportar",
        sessionsLabel: "Sesiones",
        learningInsights: "Análisis de Aprendizaje",
        insightsDesc: "Desbloquea analíticas profundas — descubre tus mejores horarios de estudio, dominio por categoría y predice tu línea de fluidez",
        optimalPracticeTimes: "Horarios Óptimos de Práctica",
        bestTimeToLearn: "Tu mejor momento para aprender",
        categoryMastery: "Dominio por Categoría",
        masteryByCategory: "Dominio por categoría",
        retentionCurve: "Curva de Retención",
        retentionOverTime: "Retención a lo largo del tiempo",
        fluencyTimeline: "Línea de Fluidez",
        predictedMilestones: "Hitos predichos",
        morning: "Mañana",
        afternoon: "Tarde",
        evening: "Noche",
        night: "Madrugada",
        needMoreData: "Juega más sesiones para obtener análisis",
        upgradedExclamation: "¡Mejorado!",
        tierChangedExclamation: "¡Bienvenido!",
        upgradeMessagePro: "Hablas el idioma del progreso — cada lección da forma a tu voz en el mundo.",
        upgradeMessageElite: "Tus palabras llevan el peso de la dedicación — la excelencia se convierte en tu lengua materna.",
        upgradeMessageRoyal: "Has coronado tu viaje con palabras — el lenguaje de las leyendas es tuyo.",
        upgradeMessageTrial: "Un capítulo real comienza — la historia completa de tu potencial lingüístico te espera.",
        // MARK: - Legal Consent
        legalConsentTitle: "Antes de comenzar",
        legalConsentSubtitle: "Revisa nuestras políticas para continuar usando LumenLingo",
        privacyPolicyTitle: "Política de privacidad",
        termsOfServiceTitle: "Términos de servicio",
        legalVersion: "Versión 2.0",
        legalLastUpdated: "Última actualización: 23 de marzo de 2026",
        legalPrivacySummary: "LumenLingo es operado por LumenShore Ltd. Respetamos tu privacidad y nos comprometemos a proteger tus datos personales. Esta política cubre tanto nuestro sitio web como la app iOS.",
        legalTermsSummary: "Estos Términos de Servicio rigen el uso de la aplicación móvil LumenLingo operada por LumenShore Ltd. Al usar LumenLingo, aceptas estos Términos.",
        legalPrivacyHighlight1: "Tus datos de aprendizaje permanecen en tu dispositivo y tu cuenta personal de iCloud",
        legalPrivacyHighlight2: "Usamos Vercel Analytics sin cookies — sin cookies de rastreo en nuestro sitio web",
        legalPrivacyHighlight3: "Sentry nos ayuda a corregir errores (la grabación de sesión requiere consentimiento)",
        legalPrivacyHighlight4: "Nunca vendemos tus datos personales a terceros",
        legalTermsHighlight1: "Niveles gratuitos y premium disponibles — suscripciones gestionadas a través de Apple",
        legalTermsHighlight2: "Tu contenido y progreso de aprendizaje te pertenecen",
        legalTermsHighlight3: "Podemos usar datos agregados y anónimos para mejorar el producto",
        legalTermsHighlight4: "Regido por las leyes de Inglaterra y Gales",
        legalAcceptAll: "Acepto",
        legalDecline: "Rechazar",
        legalDeclineTitle: "¿Estás seguro?",
        legalDeclineMessage: "Debes aceptar nuestra Política de Privacidad y Términos de Servicio para usar LumenLingo.",
        legalDeclineConfirm: "Rechazar y salir",
        legalReadFull: "Leer política completa",
        legalScrollToAccept: "Desplázate para revisar"
    )
}
