import Foundation

extension AppStrings {
    static let arabic = AppStrings(
        // Tabs
        tabHome: "الرئيسية",
        tabStats: "الإحصائيات",
        tabPremium: "المميّز",
        tabSettings: "الإعدادات",
        tabProfile: "الملف الشخصي",

        // Settings Header
        settingsHeaderTitle: "التفضيلات",
        settingsHeaderSubtitle: "خصّص تجربتك",

        // Dashboard
        greeting: { "مرحبًا، \($0)!" },
        goodMorning: "صباح الخير",
        goodAfternoon: "مساء الخير",
        goodEvening: "مساء الخير",
        goodNight: "تصبح على خير",
        readyForAdventure: "هل أنت مستعد لمغامرة جديدة؟",
        level: "المستوى",
        totalXP: "إجمالي XP",
        activeDays: "الأيام النشطة",
        chooseYourAdventure: "اختر مغامرتك",
        startGameToBoost: "ابدأ لعبة لتعزيز مهاراتك",
        flashCards: "البطاقات التعليمية",
        flashCardsDescription: "أتقن مفردات جديدة باستخدام بطاقات تفاعلية والتكرار المتباعد",
        masterNewWords: "أتقن كلمات جديدة",
        grammarChallenge: "تحدّي القواعد",
        grammarDescription: "اختبر معرفتك بأسئلة وقواعد نحوية صعبة",
        testYourSkills: "اختبر مهاراتك",
        wordConstructor: "بناء الكلمات",
        wordBuilderDescription: "ركّب الكلمات حرفًا بحرف من تلميحات مبعثرة",
        craftAndDiscover: "ركّب واكتشف",
        recentActivity: "النشاط الأخير",
        resetProgress: "إعادة تعيين التقدم",
        resetProgressMessage: "سيؤدي هذا إلى مسح جميع نقاط الخبرة والمستويات والسلاسل وسجل الألعاب والمحتوى المتقن. لا يمكن التراجع عن هذا الإجراء.",
        progressReset: "تم إعادة تعيين التقدم",
        startFreshDescription: "امسح كل تقدمك ونقاط الخبرة والسلاسل وسجل الألعاب لبدء رحلة التعلم من الصفر.",

        // Language Selection
        languages: "اللغات",
        cancel: "إلغاء",
        searchLanguages: "البحث عن لغات\u{2026}",
        chooseYourLanguages: "اختر لغاتك",
        selectWhatYouKnow: "حدّد ما تعرفه وما تتعلّمه",
        iSpeak: "أتحدّث",
        imLearning: "أتعلّم",
        noLanguagesAvailable: "لا تتوفر لغات لهذا المصدر.",
        confirm: "تأكيد:",
        done: "تم",
        languagesAvailable: "لغات متاحة",
        startYourAdventure: "ابدأ مغامرتك",
        keepLearning: "واصل التعلّم",

        // Categories
        back: "رجوع",
        searchCategories: "البحث في الفئات",
        noCategories: "لا توجد فئات",
        noFavouritesYet: "لا توجد مفضّلات بعد",
        allComplete: "اكتمل الكل!",
        noResults: "لا توجد نتائج",
        tapHeartToSave: "انقر على القلب في أي فئة لحفظها هنا",
        youveFinishedEverything: "لقد أنهيت كل شيء — عمل رائع!",
        tryDifferentSearch: "جرّب مصطلح بحث مختلف",
        categoriesWillAppear: "ستظهر الفئات بمجرد تحميل المحتوى",
        clearFilters: "مسح عوامل التصفية",
        items: "عناصر",
        complete: "مكتمل",
        doubleTapToStart: "انقر مرتين للبدء",

        // Flash Cards
        loadingCards: "جارٍ تحميل البطاقات\u{2026}",
        tapToReveal: "انقر للكشف",
        stillLearning: "لا يزال قيد التعلّم",
        gotIt: "فهمتها",
        noCardsAvailable: "لا تتوفر بطاقات",
        goBack: "العودة",

        // Grammar
        loadingQuestions: "جارٍ تحميل الأسئلة\u{2026}",
        grammarTip: "نصيحة نحوية",
        next: "التالي",
        noQuestionsAvailable: "لا تتوفر أسئلة",

        // Word Builder
        loadingWords: "جارٍ تحميل الكلمات\u{2026}",
        buildTheWord: "ركّب الكلمة",
        availableLetters: "الأحرف المتاحة",
        undo: "تراجع",
        clear: "مسح",
        check: "تحقّق",
        hint: "تلميح",
        noWordsAvailable: "لا تتوفر كلمات",

        // Game Complete
        excellent: "ممتاز!",
        greatJob: "عمل رائع!",
        goodWork: "أحسنت!",
        keepGoing: "واصل!",
        excellentSubtitle: "أداء متميّز! أنت موهوب بالفطرة!",
        greatJobSubtitle: "عمل مبهر! حافظ على الزخم!",
        goodWorkSubtitle: "جهد متين! الممارسة تصنع الكمال!",
        keepGoingSubtitle: "كل جلسة تجعلك أفضل. لا تستسلم!",
        points: "نقاط",
        accuracy: "الدقة",
        correct: "صحيح",
        toReview: "للمراجعة",
        playAgain: "العب مجددًا",        nextCategory: "الفئة التالية",        backToCategories: "العودة إلى الفئات",

        // Journey
        yourLearningJourney: "رحلتك التعليمية",
        trackYourProgress: "تتبّع تقدّمك واحتفل بإنجازاتك",
        milestones: "المراحل",
        firstSteps: "الخطوات الأولى",
        gettingStarted: "البداية",
        dedicatedLearner: "متعلّم مُلتزم",
        risingStar: "نجم صاعد",
        wordWarrior: "محارب الكلمات",
        knowledgeSeeker: "باحث عن المعرفة",
        sentenceCrafter: "صانع الجمل",
        grammarGuardian: "حارس القواعد",
        vocabularyVirtuoso: "ماهر المفردات",
        languageMaster: "سيّد اللغة",
        fluencyPioneer: "رائد الطلاقة",
        polyglotLegend: "أسطورة متعدد اللغات",
        xpRequired: "XP المطلوبة",
        overview: "نظرة عامة",
        sessions: "الجلسات",
        streak: "السلسلة",
        gamePerformance: "أداء اللعبة",
        currentStreak: "السلسلة الحالية",
        days: "أيام",
        keepLearningEveryDay: "واصل التعلّم كل يوم للحفاظ على سلسلتك!",

        // Profile
        appearance: "المظهر",
        sound: "الصوت",
        sync: "المزامنة",
        signOut: "تسجيل الخروج",
        darkLight: "داكن/فاتح",
        orbs: "الأجرام",
        quantum: "الكمّي",
        nebula: "السديم",
        learner: "متعلّم",
        xp: "XP",
        words: "كلمات",
        activityCalendar: "تقويم النشاط",
        dayStreak: "يوم متتالي",
        darkMode: "الوضع الداكن",
        cosmicDarkTheme: "ليلة كونية",
        lightModeActive: "جزيرة استوائية",
        animationSpeed: "سرعة الرسوم المتحركة",
        slow: "بطيء",
        normal: "عادي",
        fast: "سريع",
        languagePair: "زوج اللغات",
        version: "الإصدار 1.0.0",
        madeWithLove: "صُنع بـ \u{2764}\u{FE0F} لمتعلّمي اللغات",

        // Sound Settings
        masterSound: "الصوت الرئيسي",
        allSoundsEnabled: "جميع الأصوات مفعّلة",
        allSoundsMuted: "جميع الأصوات مكتومة",
        allGames: "جميع الألعاب",
        toggleAllGameSounds: "تبديل جميع أصوات فئات الألعاب",
        flashcardsSound: "البطاقات التعليمية",
        grammarSound: "القواعد",
        wordBuilderSound: "بناء الكلمات",
        uiInteractions: "تفاعلات الواجهة",
        buttonTapsNavigation: "أصوات النقر والتنقّل",
        achievements: "الإنجازات",
        levelUpFanfares: "احتفالات الترقية ومكافآت السلسلة",
        ambientAudio: "الصوت المحيطي",
        backgroundAtmospheric: "أصوات الخلفية الجوية",

        // Sync
        cloudSync: "المزامنة السحابية",
        backupRestore: "نسخ احتياطي واستعادة تقدّمك",
        upload: "رفع",
        download: "تنزيل",
        lastSynced: "آخر مزامنة:",
        never: "أبدًا",
        justNow: "الآن",
        changesPending: "تغييرات معلّقة",
        dataUploaded: "تم رفع البيانات بنجاح",
        dataDownloaded: "تم تنزيل البيانات بنجاح",
        syncSecurityNote: "بياناتك مخزّنة بأمان. تتطلّب المزامنة اتصالًا بالإنترنت.",
        minAgo: "دقيقة مضت",
        hoursAgo: "ساعات مضت",
        daysAgo: "أيام مضت",

        // Sign Out
        connected: "متصل",
        offline: "غير متصل",
        signOutRequiresInternet: "تسجيل الخروج يتطلّب الإنترنت",
        email: "البريد الإلكتروني",
        name: "الاسم",
        membership: "العضوية",
        freeTier: "الباقة المجانية",
        areYouSure: "هل أنت متأكد؟",
        progressWillBeSaved: "سيتم حفظ تقدّمك قبل تسجيل الخروج.",
        savingProgress: "جارٍ حفظ التقدّم\u{2026}",
        clearingLocalData: "جارٍ مسح البيانات المحلية\u{2026}",
        signingOut: "جارٍ تسجيل الخروج\u{2026}",

        // Breathing Orbs
        breathingOrbs: "الأجرام المتنفّسة",
        ambientBackgroundAnimation: "رسوم متحركة محيطية للخلفية",
        raveMode: "وضع الإيقاع",
        rapidColorCycling: "تدوير سريع للألوان عبر جميع الأنماط",
        colorScheme: "نظام الألوان",
        intensity: "الشدّة",
        subtle: "خفيف",
        balanced: "متوازن",
        celestial: "سماوي",
        speed: "السرعة",
        calm: "هادئ",
        flowing: "انسيابي",
        swift_: "سريع",
        perfectStillness: "سكون تام",
        gentleAndPeaceful: "لطيف وهادئ",
        balancedRhythm: "إيقاع متوازن",
        quickAndEnergetic: "سريع ونشيط",

        // Quantum Flow
        quantumFlow: "التدفّق الكمّي",
        dynamicParticleAnimation: "طبقة رسوم متحركة ديناميكية للجسيمات",
        scene: "المشهد",
        particleDensity: "كثافة الجسيمات",
        sparse: "متفرّق",
        dense: "كثيف",
        flowSpeed: "سرعة التدفّق",
        serene: "هادئ",
        rhythmic: "إيقاعي",
        energetic: "نشيط",
        exitPreview: "إنهاء المعاينة",

        // Nebula Drift
        nebulaDrift: "انجراف السديم",
        cosmicNebulaBackground: "طبقة خلفية سديمية كونية",
        nebulaOptimizedDarkMode: "انجراف السديم مُحسّن للوضع الداكن",
        nebulaPreset: "إعداد السديم",
        nebulaIntensity: "شدّة السديم",
        vivid: "زاهٍ",
        driftSpeed: "سرعة الانجراف",
        frozen: "مُجمّد",
        nebulaDescLagoon: "سحب أثيرية وردية وبنفسجية حيث تشتعل نجوم وليدة بين أعمدة الغبار الكوني",
        nebulaDescCelestial: "محيط فيروزي لا نهائي من الغاز المضيء، يتلألأ بانعكاسات ضوء النجوم السماوية",
        nebulaDescAndromeda: "تريليون شمس معلّقة على حافة المجرة، ضوء كهرماني يذوب في عمق الفضاء النيلي",
        nebulaDescSolarAurora: "شرائط ذهبية من الجسيمات المشحونة تتدفق عبر حقول مغناطيسية، ترسم الفراغ بالدفء",
        nebulaDescSpiralHalo: "مائة مليار نجم تدور في تناغم مثالي، وهجها البنفسجي يرسم مسارات الجاذبية",
        nebulaDescStarburst: "حلقة مشرقة من تكوّن نجمي سريع، أقواس زرقاء كهربائية وأرجوانية متوهجة بالطاقة",

        // Membership
        plansAndPricing: "الخطط والأسعار",
        investInYour: "استثمر في",
        languageMastery: "إتقانك للغات",
        membershipSubtitle: "انضم إلى الآلاف الذين يتعلّمون بذكاء وليس بجهد أكبر.",
        monthly: "شهري",
        yearlyDiscount: "سنوي  -17%",
        featureComparison: "مقارنة الميزات",
        feature: "الميزة",
        free: "مجاني",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "الأسئلة الشائعة",
        secure: "آمن",
        dayRefund: "استرداد خلال 30 يومًا",
        cancelAnytime: "إلغاء في أي وقت",
        pricesShownUSD: "الأسعار بالدولار الأمريكي. قد تُطبّق ضرائب.",
        popular: "الأكثر رواجًا",
        starter: "مبتدئ",
        beginYourJourney: "ابدأ رحلتك",
        masterLanguagesFaster: "أتقن اللغات بشكل أسرع",
        unlockFullPotential: "أطلق العنان لإمكاناتك الكاملة",
        ultimateExperience: "التجربة المطلقة",
        currentPlan: "الخطة الحالية",
        getStarted: "ابدأ الآن",
        startPro: "ابدأ Pro",
        upgradeToElite: "ترقية إلى Elite",
        ascendToRoyal: "الارتقاء إلى Royal",

        // Game Type Names
        gameFlashCards: "البطاقات التعليمية",
        gameGrammar: "القواعد",
        gameWordBuilder: "بناء الكلمات",

        // Additional UI
        languageMasteryEngine: "محرك إتقان اللغات",
        user: "مستخدم",
        perMonth: "/شهر",
        perYear: "/سنة",

        // Membership Feature Names
        featureLanguagePairs: "أزواج اللغات",
        featureDailyPractice: "التدريب اليومي",
        featureGameModes: "أوضاع اللعب",
        featureBreathingOrbs: "الكرات المتنفسة",
        featureQuantumFlow: "التدفق الكمي",
        featureNebulaDrift: "انجراف السديم",
        featureOfflineMode: "وضع عدم الاتصال",
        featureCloudSync: "المزامنة السحابية",
        featurePrioritySupport: "الدعم ذو الأولوية",
        unlimited: "غير محدود",
        allModes: "الثلاثة",
        scheme1: "نظام واحد",
        schemes3: "٣ أنظمة",
        allSchemes: "جميع الأنظمة",
        scenes2: "مشهدان",
        allScenes: "جميع المشاهد",
        presets3: "٣ إعدادات",
        allPresets: "جميع الإعدادات",
        min15: "١٥ دقيقة",

        // Offline Mode / Connectivity
        offlineMode: "وضع عدم الاتصال",
        offlineModeDescription: "استخدم المحتوى بدون اتصال بالإنترنت",
        offlineModeLockedDescription: "قم بالترقية إلى Pro لاستخدام المحتوى بدون اتصال",
        connectToUse: "اتصل لاستخدام المحتوى",
        connectivityRequired: "تتطلب الخطة المجانية اتصالاً بالإنترنت للوصول إلى المحتوى",
        offlineModeInfo: "عند تفعيل وضع عدم الاتصال، يكون المحتوى متاحاً بدون اتصال شبكي. يمكن لخطط Pro والأعلى التعلم في أي مكان.",
        offlineModeDisabled: "تم تعطيل وضع عدم الاتصال",
        offlineModeDisabledDetail: "لم تعد خطتك تتضمن الوصول بدون اتصال",
        offlineModeActive: "وضع عدم الاتصال نشط",
        offlineModeIncluded: "اشتراكك يتضمن الوصول بدون اتصال",
        onlineOnly: "متصل فقط",
        offlineModeActivated: "تم تفعيل وضع عدم الاتصال",
        offlineModeActivatedDetail: "الوصول بدون اتصال متاح الآن",

        // MARK: - Upgrade Prompts
        unlockPremium: "فتح Premium",
        viewPlans: "عرض الخطط",
        maybeLater: "ربما لاحقاً",
        requires: "يتطلب",
        learnMore: "اعرف المزيد",
        hideForever: "إخفاء للأبد",
        dontShowAgain: "عدم العرض مجدداً",

        // MARK: - Royal Trial
        trialActivated: "تم تفعيل النسخة التجريبية!",
        trialWelcomeMessage: "مرحباً بك في 14 يوماً من الوصول الملكي الكامل. جميع الميزات المميزة لك.",
        trialDuration: "14 يوماً من الوصول الملكي",
        trialAfterExpiry: "بعد 14 يوماً، ستنتقل إلى الخطة المجانية. بدون رسوم.",
        trialStartExploring: "ابدأ الاستكشاف",
        trialBannerTitle: "النسخة التجريبية الملكية",
        trialExpiringToday: "تنتهي اليوم",
        trialOneDayLeft: "يوم واحد متبقي",
        trialDaysLeft: "أيام متبقية",
        trialEndedTitle: "انتهت نسختك التجريبية",
        trialEndedSubtitle: "شكراً لتجربة Royal! تقدمك محفوظ.",
        trialYourProgress: "تقدمك في الفترة التجريبية",
        trialLevel: "المستوى",
        trialStreak: "السلسلة",
        trialYouStillHave: "لا يزال لديك",
        trialChoosePlan: "اختر خطة",
        trialContinueFree: "المتابعة مجاناً",
        trialCompleted: "اكتملت النسخة التجريبية",
        trialCompletedTagline: "لقد جربت Royal",
        trialStartFree: "ابدأ النسخة التجريبية المجانية",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "مرحباً، \($0)!" },
        daysLeftInTrial: { "\($0) أيام متبقية في تجربتك" },
        thirtyMinPerDay: "٣٠ دقيقة/يوم",
        resetsIn: { "يتجدد خلال \($0)" },
        nowPlaying: "قيد التشغيل",
        paused: "متوقف مؤقتاً",

        // MARK: - Game Session Results
        xpBonus: "مكافأة XP",
        timeSpentLabel: "الوقت",
        streakActive: "نشط",
        streakLabel: "السلسلة",
        vsPreviousSession: "مقابل الجلسة السابقة",
        keepImproving: "استمر في التحسّن كل جلسة!",
        recentPerformance: "الأداء الأخير",
        last7Sessions: "آخر ٧ جلسات",
        areasToImprove: "مجالات للتحسين",
        reviewIncorrect: { "راجع \($0) إجابات خاطئة" },
        shareResult: "مشاركة النتيجة",
        availableOn: { "متاح في \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "XP اليومي",
        last7Days: "آخر ٧ أيام",
        weeklyTrend: "الاتجاه الأسبوعي",
        thisWeekVsLastWeek: "هذا الأسبوع مقابل الأسبوع الماضي",
        thisWeekLabel: "هذا الأسبوع",
        lastWeekLabel: "الأسبوع الماضي",
        totalThisWeek: "إجمالي هذا الأسبوع",
        accuracyHeatmap: "خريطة الدقة",
        accuracyByCategory: "الدقة حسب الفئة",
        playSessionsToSeeData: "العب جلسات لرؤية البيانات",
        monthlyReport: "التقرير الشهري",
        last30Days: "آخر ٣٠ يوماً",
        activeDaysLabel: "الأيام النشطة",
        milestonePredictionsTitle: "توقعات الإنجازات",
        basedOnYourPace: "بناءً على وتيرتك الحالية",
        allMilestonesReached: "تم تحقيق جميع الإنجازات!",
        tapToUpgrade: "اضغط للترقية",
        unlockFeature: "افتح هذه الميزة",
        gameBreakdownDesc: "اكتشف أين تتألق — تتبع النتائج والدقة والوقت في كل وضع لعب",
        dailyXPChartDesc: "تصور زخمك — شاهد نقاط خبرتك اليومية تتكشف على مدار الأسبوع",
        weeklyTrendDesc: "قارن هذا الأسبوع بالسابق واكتشف الأنماط التي تدفع نموك",
        accuracyHeatmapDesc: "اكشف فوراً عن أقوى وأضعف فئاتك بنظرة واحدة",
        monthlyReportDesc: "ملخصك الشخصي لـ 30 يوماً — الجلسات والسلاسل والدقة والأيام النشطة",
        milestonePredictionsDesc: "اعرف بالضبط متى ستصل إلى إنجازك التالي بناءً على وتيرة تعلمك",
        exportData: "تصدير البيانات",
        exportDataDesc: "حمّل سجل تعلمك — راجع تقدمك بدون اتصال، شاركه مع المعلمين أو احتفظ بسجل شخصي",
        exportAsCSV: "تصدير كـ CSV",
        exportAsJSON: "تصدير كـ JSON",
        exportAsPDF: "تصدير كـ PDF",
        exportReady: "بياناتك جاهزة للمشاركة",
        noDataToExport: "لا توجد بيانات للتصدير بعد",
        sessionsLabel: "الجلسات",
        learningInsights: "تحليلات التعلم",
        insightsDesc: "افتح تحليلات عميقة — اكتشف أوقات دراستك المثلى، تتبع إتقانك عبر الفئات وتوقع جدولك الزمني للطلاقة",
        optimalPracticeTimes: "أوقات التمرين المثالية",
        bestTimeToLearn: "أفضل وقت للتعلم",
        categoryMastery: "إتقان الفئات",
        masteryByCategory: "الإتقان حسب الفئة",
        retentionCurve: "منحنى الاحتفاظ",
        retentionOverTime: "الاحتفاظ عبر الزمن",
        fluencyTimeline: "الجدول الزمني للطلاقة",
        predictedMilestones: "الإنجازات المتوقعة",
        morning: "صباحاً",
        afternoon: "ظهراً",
        evening: "مساءً",
        night: "ليلاً",
        needMoreData: "العب المزيد من الجلسات للحصول على تحليلات",
        upgradedExclamation: "تمت الترقية!",
        tierChangedExclamation: "!أهلاً",
        upgradeMessagePro: "أنت تتحدث لغة التقدم — كل درس يشكّل صوتك في العالم.",
        upgradeMessageElite: "كلماتك تحمل ثقل التفاني — التميّز يصبح لغتك الأم.",
        upgradeMessageRoyal: "توّجت رحلتك بالكلمات — لغة الأساطير ملكك.",
        upgradeMessageTrial: "يبدأ فصل ملكي — القصة الكاملة لإمكاناتك اللغوية بانتظارك."
    )
}
