import Foundation

extension AppStrings {
    static let chinese = AppStrings(
        // Tabs
        tabHome: "首页",
        tabStats: "统计",
        tabPremium: "高级版",
        tabSettings: "设置",
        tabProfile: "个人资料",

        // Settings Header
        settingsHeaderTitle: "偏好设置",
        settingsHeaderSubtitle: "打造专属体验",

        // Dashboard
        greeting: { "你好，\($0)！" },
        goodMorning: "早上好",
        goodAfternoon: "下午好",
        goodEvening: "晚上好",
        goodNight: "晚安",
        readyForAdventure: "准备好开始新的冒险了吗？",
        level: "等级",
        totalXP: "总 XP",
        activeDays: "活跃天数",
        chooseYourAdventure: "选择你的冒险",
        startGameToBoost: "开始游戏，提升你的技能",
        flashCards: "闪卡",
        flashCardsDescription: "通过互动翻转卡片和间隔重复法掌握新词汇",
        masterNewWords: "掌握新词汇",
        grammarChallenge: "语法挑战",
        grammarDescription: "通过具有挑战性的问题和语法规则测试你的知识",
        testYourSkills: "测试你的技能",
        wordConstructor: "单词构建器",
        wordBuilderDescription: "根据打乱的线索和提示逐字母构建单词",
        craftAndDiscover: "构建与发现",
        recentActivity: "最近活动",
        resetProgress: "重置进度",
        resetProgressMessage: "这将清除您所有的经验值、等级、连续记录、游戏历史和已掌握内容。此操作无法撤销。",
        progressReset: "进度已重置",
        startFreshDescription: "清除您所有的进度、经验值、连续记录和游戏历史，从头开始您的学习之旅。",

        // Language Selection
        languages: "语言",
        cancel: "取消",
        searchLanguages: "搜索语言\u{2026}",
        chooseYourLanguages: "选择你的语言",
        selectWhatYouKnow: "选择你会的语言和正在学习的语言",
        iSpeak: "我会说",
        imLearning: "我正在学习",
        noLanguagesAvailable: "该源语言暂无可用语言。",
        confirm: "确认：",
        done: "完成",
        languagesAvailable: "种语言可用",
        startYourAdventure: "开启你的冒险",
        keepLearning: "继续学习",

        // Categories
        back: "返回",
        searchCategories: "搜索分类",
        noCategories: "暂无分类",
        noFavouritesYet: "暂无收藏",
        allComplete: "全部完成！",
        noResults: "无结果",
        tapHeartToSave: "点击任意分类上的爱心即可收藏",
        youveFinishedEverything: "你已完成所有内容，干得漂亮！",
        tryDifferentSearch: "请尝试其他搜索词",
        categoriesWillAppear: "内容加载后将显示分类",
        clearFilters: "清除筛选",
        items: "项",
        complete: "完成",
        doubleTapToStart: "双击开始",

        // Flash Cards
        loadingCards: "正在加载卡片\u{2026}",
        tapToReveal: "点击揭晓",
        stillLearning: "还在学习",
        gotIt: "已掌握",
        noCardsAvailable: "暂无可用卡片",
        goBack: "返回",

        // Grammar
        loadingQuestions: "正在加载题目\u{2026}",
        grammarTip: "语法提示",
        next: "下一题",
        noQuestionsAvailable: "暂无可用题目",

        // Word Builder
        loadingWords: "正在加载单词\u{2026}",
        buildTheWord: "构建单词",
        availableLetters: "可用字母",
        undo: "撤销",
        clear: "清除",
        check: "检查",
        hint: "提示",
        noWordsAvailable: "暂无可用单词",

        // Game Complete
        excellent: "太棒了！",
        greatJob: "做得好！",
        goodWork: "干得不错！",
        keepGoing: "继续加油！",
        excellentSubtitle: "表现出色！你是天生的语言高手！",
        greatJobSubtitle: "令人印象深刻！保持这股势头！",
        goodWorkSubtitle: "扎实的努力！熟能生巧！",
        keepGoingSubtitle: "每一次练习都让你更进一步，不要放弃！",
        points: "分",
        accuracy: "准确率",
        correct: "正确",
        toReview: "待复习",
        playAgain: "再玩一次",
        nextCategory: "下一个分类",
        backToCategories: "返回分类",

        // Journey
        yourLearningJourney: "你的学习之旅",
        trackYourProgress: "追踪你的进度，庆祝每一项成就",
        milestones: "里程碑",
        firstSteps: "初出茅庐",
        gettingStarted: "崭露头角",
        dedicatedLearner: "勤奋学者",
        risingStar: "新星崛起",
        wordWarrior: "词汇达人",
        knowledgeSeeker: "知识探索者",
        sentenceCrafter: "造句工匠",
        grammarGuardian: "语法守护者",
        vocabularyVirtuoso: "词汇大师",
        languageMaster: "语言大师",
        fluencyPioneer: "流利先锋",
        polyglotLegend: "多语传奇",
        xpRequired: "所需 XP",
        overview: "总览",
        sessions: "学习记录",
        streak: "连续天数",
        gamePerformance: "游戏表现",
        currentStreak: "当前连续天数",
        days: "天",
        keepLearningEveryDay: "每天坚持学习以保持你的连续记录！",

        // Profile
        appearance: "外观",
        sound: "声音",
        sync: "同步",
        signOut: "退出登录",
        darkLight: "深色/浅色",
        orbs: "光球",
        quantum: "量子",
        nebula: "星云",
        learner: "学习者",
        xp: "XP",
        words: "单词",
        activityCalendar: "活动日历",
        dayStreak: "天连续",
        darkMode: "深色模式",
        cosmicDarkTheme: "宇宙夜晚",
        lightModeActive: "热带岛屿",
        animationSpeed: "动画速度",
        slow: "慢速",
        normal: "正常",
        fast: "快速",
        languagePair: "语言对",
        version: "版本 1.0.0",
        madeWithLove: "为语言学习者用 \u{2764}\u{FE0F} 打造",

        // Sound Settings
        masterSound: "主音量",
        allSoundsEnabled: "所有声音已启用",
        allSoundsMuted: "所有声音已静音",
        allGames: "所有游戏",
        toggleAllGameSounds: "切换所有游戏类别的声音",
        flashcardsSound: "闪卡",
        grammarSound: "语法",
        wordBuilderSound: "单词构建器",
        uiInteractions: "界面交互",
        buttonTapsNavigation: "按钮点击和导航音效",
        achievements: "成就",
        levelUpFanfares: "升级庆祝和连续奖励",
        ambientAudio: "环境音效",
        backgroundAtmospheric: "背景氛围音效",

        // Sync
        cloudSync: "云同步",
        backupRestore: "备份和恢复你的进度",
        upload: "上传",
        download: "下载",
        lastSynced: "上次同步：",
        never: "从未",
        justNow: "刚刚",
        changesPending: "有待同步的更改",
        dataUploaded: "数据上传成功",
        dataDownloaded: "数据下载成功",
        syncSecurityNote: "你的数据已安全存储。同步需要网络连接。",
        minAgo: "分钟前",
        hoursAgo: "小时前",
        daysAgo: "天前",

        // Sign Out
        connected: "已连接",
        offline: "离线",
        signOutRequiresInternet: "退出登录需要网络连接",
        email: "邮箱",
        name: "姓名",
        membership: "会员",
        freeTier: "免费版",
        areYouSure: "你确定吗？",
        progressWillBeSaved: "退出登录前将保存你的进度。",
        savingProgress: "正在保存进度\u{2026}",
        clearingLocalData: "正在清除本地数据\u{2026}",
        signingOut: "正在退出登录\u{2026}",

        // Breathing Orbs
        breathingOrbs: "呼吸光球",
        ambientBackgroundAnimation: "环境背景动画",
        raveMode: "炫彩模式",
        rapidColorCycling: "快速循环所有配色方案",
        colorScheme: "配色方案",
        intensity: "强度",
        subtle: "柔和",
        balanced: "均衡",
        celestial: "璀璨",
        speed: "速度",
        calm: "平静",
        flowing: "流动",
        swift_: "迅捷",
        perfectStillness: "完美静止",
        gentleAndPeaceful: "温柔而宁静",
        balancedRhythm: "均衡节奏",
        quickAndEnergetic: "快速而充满活力",

        // Quantum Flow
        quantumFlow: "量子流",
        dynamicParticleAnimation: "动态粒子动画层",
        scene: "场景",
        particleDensity: "粒子密度",
        sparse: "稀疏",
        dense: "密集",
        flowSpeed: "流动速度",
        serene: "宁静",
        rhythmic: "律动",
        energetic: "活力",
        exitPreview: "退出预览",

        // Nebula Drift
        nebulaDrift: "星云漂移",
        cosmicNebulaBackground: "宇宙星云背景层",
        nebulaOptimizedDarkMode: "星云漂移已针对深色模式优化",
        nebulaPreset: "星云预设",
        nebulaIntensity: "星云强度",
        vivid: "鲜明",
        driftSpeed: "漂移速度",
        frozen: "冻结",
        nebulaDescLagoon: "缥缈的粉紫色云雾中，新生的恒星在星际尘柱间燃起光芒",
        nebulaDescCelestial: "无垠的绿松石色发光气体海洋，闪烁着青色与深碧的星光倒影",
        nebulaDescAndromeda: "万亿颗太阳悬浮在星系边缘，琥珀色的光芒消融于深邃的靛蓝星空",
        nebulaDescSolarAurora: "金色的带电粒子丝带穿过磁场倾泻而下，为虚空涂上温暖的色调",
        nebulaDescSpiralHalo: "千亿颗恒星在完美和谐中旋转，紫色的光芒勾勒出引力的轨迹",
        nebulaDescStarburst: "一圈灿烂的恒星急速诞生，电蓝与品红的弧光迸发着璀璨能量",

        // Membership
        plansAndPricing: "套餐与价格",
        investInYour: "投资你的",
        languageMastery: "语言精通之路",
        membershipSubtitle: "加入数千名更聪明学习的伙伴。",
        monthly: "月付",
        yearlyDiscount: "年付  -17%",
        featureComparison: "功能对比",
        feature: "功能",
        free: "免费",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "常见问题",
        secure: "安全",
        dayRefund: "30天退款",
        cancelAnytime: "随时取消",
        pricesShownUSD: "价格以美元显示，可能另收税费。",
        popular: "热门",
        starter: "入门",
        beginYourJourney: "开启你的旅程",
        masterLanguagesFaster: "更快地掌握语言",
        unlockFullPotential: "释放你的全部潜力",
        ultimateExperience: "终极体验",
        currentPlan: "当前套餐",
        getStarted: "立即开始",
        startPro: "开通 Pro",
        upgradeToElite: "升级至 Elite",
        ascendToRoyal: "升级至 Royal",

        // Game Type Names
        gameFlashCards: "闪卡",
        gameGrammar: "语法",
        gameWordBuilder: "单词构建器",

        // Additional UI
        languageMasteryEngine: "语言精通引擎",
        user: "用户",
        perMonth: "/月",
        perYear: "/年",

        // Membership Feature Names
        featureLanguagePairs: "语言对",
        featureDailyPractice: "每日练习",
        featureGameModes: "游戏模式",
        featureBreathingOrbs: "呼吸光球",
        featureQuantumFlow: "量子流",
        featureNebulaDrift: "星云漂移",
        featureOfflineMode: "离线模式",
        featureCloudSync: "云同步",
        featurePrioritySupport: "优先支持",
        unlimited: "无限",
        allModes: "全部3种",
        scheme1: "1种方案",
        schemes3: "3种方案",
        allSchemes: "所有方案",
        scenes2: "2个场景",
        allScenes: "所有场景",
        presets3: "3个预设",
        allPresets: "所有预设",
        min15: "15分钟",

        // Offline Mode / Connectivity
        offlineMode: "离线模式",
        offlineModeDescription: "无需网络连接即可使用内容",
        offlineModeLockedDescription: "升级到Pro以离线使用内容",
        connectToUse: "连接网络以使用内容",
        connectivityRequired: "免费版需要网络连接才能访问内容",
        offlineModeInfo: "启用离线模式后，无需网络连接即可使用内容。Pro及以上等级可随时随地学习。",
        offlineModeDisabled: "离线模式已禁用",
        offlineModeDisabledDetail: "您的等级不再包含离线访问",
        offlineModeActive: "离线模式已激活",
        offlineModeIncluded: "您的订阅包含离线访问",
        onlineOnly: "仅在线",
        offlineModeActivated: "离线模式已启用",
        offlineModeActivatedDetail: "离线访问现已可用",

        // MARK: - Upgrade Prompts
        unlockPremium: "解锁高级版",
        viewPlans: "查看方案",
        maybeLater: "以后再说",
        requires: "需要",
        learnMore: "了解更多",
        hideForever: "永久隐藏",
        dontShowAgain: "不再显示",

        // MARK: - Royal Trial
        trialActivated: "试用已激活！",
        trialWelcomeMessage: "欢迎体验14天完整Royal访问权限。所有高级功能都是您的。",
        trialDuration: "14天Royal访问",
        trialAfterExpiry: "14天后，您将转为免费版。不收取任何费用。",
        trialStartExploring: "开始探索",
        trialBannerTitle: "Royal试用",
        trialExpiringToday: "今天到期",
        trialOneDayLeft: "剩余1天",
        trialDaysLeft: "天剩余",
        trialEndedTitle: "您的试用已结束",
        trialEndedSubtitle: "感谢试用Royal！您的进度已安全保存。",
        trialYourProgress: "您的试用进度",
        trialLevel: "等级",
        trialStreak: "连续",
        trialYouStillHave: "您仍然拥有",
        trialChoosePlan: "选择方案",
        trialContinueFree: "继续免费使用",
        trialCompleted: "试用已完成",
        trialCompletedTagline: "您已体验过Royal",
        trialStartFree: "开始免费试用",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "欢迎，\($0)！" },
        daysLeftInTrial: { "试用还剩 \($0) 天" },
        thirtyMinPerDay: "30分钟/天",
        resetsIn: { "\($0)后重置" },
        nowPlaying: "正在播放",
        paused: "已暂停",

        // MARK: - Game Session Results
        xpBonus: "XP加成",
        timeSpentLabel: "时间",
        streakActive: "活跃",
        streakLabel: "连续",
        vsPreviousSession: "对比上次",
        keepImproving: "每次练习都在进步！",
        recentPerformance: "近期表现",
        last7Sessions: "最近7次",
        areasToImprove: "待改进",
        reviewIncorrect: { "复习\($0)个错误答案" },
        shareResult: "分享结果",
        availableOn: { "\($0)可用" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "每日XP",
        last7Days: "最近7天",
        weeklyTrend: "周趋势",
        thisWeekVsLastWeek: "本周对比上周",
        thisWeekLabel: "本周",
        lastWeekLabel: "上周",
        totalThisWeek: "本周总计",
        accuracyHeatmap: "准确率热力图",
        accuracyByCategory: "按分类准确率",
        playSessionsToSeeData: "完成练习后查看数据",
        monthlyReport: "月度报告",
        last30Days: "最近30天",
        activeDaysLabel: "活跃天数",
        milestonePredictionsTitle: "里程碑预测",
        basedOnYourPace: "基于您当前的进度",
        allMilestonesReached: "所有里程碑已达成！",
        tapToUpgrade: "点击升级",
        unlockFeature: "解锁此功能",
        gameBreakdownDesc: "看看你在哪里最出色——追踪每种游戏模式的得分、准确率和时间",
        dailyXPChartDesc: "可视化你的势头——观察每日经验值在一周内的变化",
        weeklyTrendDesc: "对比本周与上周，发现驱动你成长的模式",
        accuracyHeatmapDesc: "一眼看清你最强和最弱的类别",
        monthlyReportDesc: "你的个性化30天快照——会话、连续记录、准确率和活跃天数",
        milestonePredictionsDesc: "根据你的学习节奏，精确预测你何时达到下一个里程碑",
        exportData: "导出数据",
        exportDataDesc: "下载你的学习记录 — 离线查看进度、与导师分享或保存个人记录",
        exportAsCSV: "导出为 CSV",
        exportAsJSON: "导出为 JSON",
        exportAsPDF: "导出为 PDF",
        exportReady: "你的数据已准备好分享",
        noDataToExport: "暂无数据可导出",
        sessionsLabel: "会话",
        learningInsights: "学习洞察",
        insightsDesc: "解锁深度分析 — 发现最佳学习时间、跟踪各类别掌握度并预测流利度时间线",
        optimalPracticeTimes: "最佳练习时间",
        bestTimeToLearn: "你的最佳学习时间",
        categoryMastery: "类别掌握度",
        masteryByCategory: "按类别掌握度",
        retentionCurve: "记忆曲线",
        retentionOverTime: "随时间的记忆保留",
        fluencyTimeline: "流利度时间线",
        predictedMilestones: "预测的里程碑",
        morning: "上午",
        afternoon: "下午",
        evening: "傍晚",
        night: "夜晚",
        needMoreData: "多玩几场以获取洞察",
        upgradedExclamation: "已升级！",
        tierChangedExclamation: "欢迎！",
        upgradeMessagePro: "你说着进步的语言——每一课都在塑造你在世界上的声音。",
        upgradeMessageElite: "你的文字承载着奉献的力量——卓越正成为你的母语。",
        upgradeMessageRoyal: "你用文字为旅程加冕——传奇的语言由你掌控。",
        upgradeMessageTrial: "皇家篇章开启——你语言潜能的完整故事正等待着你。",
        // MARK: - Legal Consent
        legalConsentTitle: "开始之前",
        legalConsentSubtitle: "请查看我们的政策以继续使用 LumenLingo",
        privacyPolicyTitle: "隐私政策",
        termsOfServiceTitle: "服务条款",
        legalVersion: "版本 2.0",
        legalLastUpdated: "最后更新：2026年3月23日",
        legalPrivacySummary: "LumenLingo 由 LumenShore Ltd 运营。我们尊重您的隐私并致力于保护您的个人数据。本政策涵盖我们的网站和 iOS 应用程序。",
        legalTermsSummary: "本服务条款管辖您对 LumenShore Ltd 运营的 LumenLingo 移动应用程序的使用。使用 LumenLingo 即表示您同意这些条款。",
        legalPrivacyHighlight1: "您的学习数据保存在您的设备和个人 iCloud 账户中",
        legalPrivacyHighlight2: "我们使用无 Cookie 的 Vercel Analytics — 网站上没有跟踪 Cookie",
        legalPrivacyHighlight3: "Sentry 帮助我们修复错误（会话回放需要同意）",
        legalPrivacyHighlight4: "我们从不向第三方出售您的个人数据",
        legalTermsHighlight1: "提供免费和高级层级 — 订阅通过 Apple 管理",
        legalTermsHighlight2: "您的内容和学习进度属于您",
        legalTermsHighlight3: "我们可能使用聚合的匿名数据来改进产品",
        legalTermsHighlight4: "受英格兰和威尔士法律管辖",
        legalAcceptAll: "我同意",
        legalDecline: "拒绝",
        legalDeclineTitle: "确定吗？",
        legalDeclineMessage: "您必须接受我们的隐私政策和服务条款才能使用 LumenLingo。",
        legalDeclineConfirm: "拒绝并退出",
        legalReadFull: "阅读完整政策",
        legalScrollToAccept: "滚动查看",

        // MARK: - EULA
        eulaTitle: "最终用户许可协议",
        eulaSummary: "本许可协议管理您对 LumenLingo 应用程序的使用，该应用由 LumenShore Ltd 通过 Apple App Store 分发。",
        eulaHighlight1: "用于个人语言学习的非独占性、可撤销许可",
        eulaHighlight2: "分级访问 — 免费、Pro、Elite 和 Royal 会员",
        eulaHighlight3: "您拥有您的学习数据；我们拥有应用内容",
        eulaHighlight4: "包含符合 App Store 要求的 Apple 特定条款",

        // MARK: - Subscription Disclosure
        subscriptionAutoRenew: "订阅每月自动续订，除非在当前期间结束前至少24小时取消。",
        subscriptionPaymentNotice: "确认购买时，费用将从您的 Apple ID 账户扣除。",
        subscriptionManageCancel: "在「设置」→ Apple ID →「订阅」中管理或取消。",
        subscriptionTrialNotice: "14天Royal免费试用。试用结束后将降级为免费版。",
        restorePurchases: "恢复购买",
        subscriptionLegalPrefix: "订阅即表示您同意我们的",
        subscriptionLegalAnd: "和"
,

        // MARK: - Account Deletion
        deleteAccount: "删除账户",
        deleteAccountWarning: "这将永久删除所有学习数据、进度、连续记录和偏好设置。此操作无法撤销。",
        deleteAccountConfirm: "删除所有内容",
        deletingAccount: "正在删除账户…",
        clearingUserData: "正在清除用户数据",
        accountDeleted: "账户已删除",

        // MARK: - GDPR Data Export
        gdprExportTitle: "导出我的数据",
        gdprExportDesc: "将您的所有个人数据下载为机器可读的JSON文件。这是您根据GDPR第20条享有的权利——所有用户免费。",
        gdprExportButton: "导出个人数据",
        gdprExportSuccess: "数据导出成功",
        gdprExportEmpty: "没有可导出的个人数据",

        trademarkAttribution: "Apple, the Apple logo, iPhone, iPad, App Store, iCloud, Apple ID, and iOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions.",

        companyName: "Lumenshore Limited",
        companyNumber: "公司编号 09607326",
        companyRegistration: "注册于英格兰和威尔士",
        companyAddress: "Windsor House, Troon Way Business Centre, Humberstone Lane, Leicester, England, LE4 9HA",
        companyVAT: "增值税登记号：GB 270411929",

        cookiePolicyTitle: "Cookie 政策",
        legalUpdated: "2025年3月更新",

        viewMyDataTitle: "查看我的数据",
        viewMyDataDesc: "查看 LumenLingo 存储的关于您的数据",
        dataProfileInfo: "个人资料信息",
        dataGameRecords: "游戏进度记录",
        dataMasteredItems: "已掌握项目",
        dataFavorites: "收藏分类",
        dataICloudSync: "iCloud 同步",
        dataEnabled: "已启用",
        dataDisabled: "已禁用",
        dataStorageEstimate: "预计存储空间"
    )
}