import Foundation

extension AppStrings {
    static let polish = AppStrings(
        // Tabs
        tabHome: "Główna",
        tabStats: "Statystyki",
        tabPremium: "Premium",
        tabSettings: "Ustawienia",
        tabProfile: "Profil",

        // Settings Header
        settingsHeaderTitle: "Preferencje",
        settingsHeaderSubtitle: "Spersonalizuj swoje wrażenia",

        // Dashboard
        greeting: { "Cześć, \($0)!" },
        goodMorning: "Dzień dobry",
        goodAfternoon: "Dzień dobry",
        goodEvening: "Dobry wieczór",
        goodNight: "Dobranoc",
        readyForAdventure: "Gotowy na nową przygodę?",
        level: "Poziom",
        totalXP: "Łączne XP",
        activeDays: "Aktywne dni",
        chooseYourAdventure: "Wybierz swoją przygodę",
        startGameToBoost: "Rozpocznij grę, aby rozwinąć swoje umiejętności",
        flashCards: "Fiszki",
        flashCardsDescription: "Opanuj nowe słówka dzięki interaktywnym fiszkom i powtórkom rozłożonym w czasie",
        masterNewWords: "Opanuj nowe słowa",
        grammarChallenge: "Wyzwanie gramatyczne",
        grammarDescription: "Sprawdź swoją wiedzę w wymagających pytaniach i regułach gramatycznych",
        testYourSkills: "Sprawdź swoje umiejętności",
        wordConstructor: "Konstruktor słów",
        wordBuilderDescription: "Buduj słowa litera po literze z pomieszanych liter i podpowiedzi",
        craftAndDiscover: "Twórz i odkrywaj",
        recentActivity: "Ostatnia aktywność",
        resetProgress: "Zresetuj postęp",
        resetProgressMessage: "Spowoduje to usunięcie wszystkich XP, poziomów, serii, historii gier i opanowanych treści. Tej operacji nie można cofnąć.",
        progressReset: "Postęp został zresetowany",
        startFreshDescription: "Wyczyść cały swój postęp, XP, serie i historię gier, aby rozpocząć naukę od początku.",

        // Language Selection
        languages: "Języki",
        cancel: "Anuluj",
        searchLanguages: "Szukaj języków\u{2026}",
        chooseYourLanguages: "Wybierz swoje języki",
        selectWhatYouKnow: "Wybierz język, który znasz, i ten, którego się uczysz",
        iSpeak: "Mówię po",
        imLearning: "Uczę się",
        noLanguagesAvailable: "Brak dostępnych języków dla tego źródła.",
        confirm: "Potwierdź:",
        done: "Gotowe",
        languagesAvailable: "dostępnych języków",
        startYourAdventure: "Rozpocznij Przygodę",
        keepLearning: "Ucz Się Dalej",

        // Categories
        back: "Wstecz",
        searchCategories: "Szukaj kategorii",
        noCategories: "Brak kategorii",
        noFavouritesYet: "Brak ulubionych",
        allComplete: "Wszystko ukończone!",
        noResults: "Brak wyników",
        tapHeartToSave: "Dotknij serduszko przy kategorii, aby ją zapisać tutaj",
        youveFinishedEverything: "Ukończyłeś wszystko — świetna robota!",
        tryDifferentSearch: "Spróbuj innego wyszukiwania",
        categoriesWillAppear: "Kategorie pojawią się po załadowaniu treści",
        clearFilters: "Wyczyść filtry",
        items: "elementy",
        complete: "Ukończono",
        doubleTapToStart: "Dotknij dwukrotnie, aby rozpocząć",

        // Flash Cards
        loadingCards: "Ładowanie kart\u{2026}",
        tapToReveal: "Dotknij, aby odkryć",
        stillLearning: "Jeszcze się uczę",
        gotIt: "Umiem!",
        noCardsAvailable: "Brak dostępnych kart",
        goBack: "Wróć",

        // Grammar
        loadingQuestions: "Ładowanie pytań\u{2026}",
        grammarTip: "Wskazówka gramatyczna",
        next: "Dalej",
        noQuestionsAvailable: "Brak dostępnych pytań",

        // Word Builder
        loadingWords: "Ładowanie słów\u{2026}",
        buildTheWord: "Zbuduj słowo",
        availableLetters: "Dostępne litery",
        undo: "Cofnij",
        clear: "Wyczyść",
        check: "Sprawdź",
        hint: "Podpowiedź",
        noWordsAvailable: "Brak dostępnych słów",

        // Game Complete
        excellent: "Doskonale!",
        greatJob: "Świetna robota!",
        goodWork: "Dobra robota!",
        keepGoing: "Tak trzymaj!",
        excellentSubtitle: "Wybitny wynik! Masz do tego talent!",
        greatJobSubtitle: "Imponująca praca! Nie zwalniaj tempa!",
        goodWorkSubtitle: "Solidny wysiłek! Praktyka czyni mistrza!",
        keepGoingSubtitle: "Każda sesja czyni Cię lepszym. Nie poddawaj się!",
        points: "punkty",
        accuracy: "Dokładność",
        correct: "Poprawne",
        toReview: "Do powtórki",
        playAgain: "Zagraj ponownie",
        nextCategory: "Następna kategoria",
        backToCategories: "Wróć do kategorii",

        // Journey
        yourLearningJourney: "Twoja droga nauki",
        trackYourProgress: "Śledź swoje postępy i świętuj osiągnięcia",
        milestones: "Kamienie milowe",
        firstSteps: "Pierwsze kroki",
        gettingStarted: "Początek drogi",
        dedicatedLearner: "Zaangażowany uczeń",
        risingStar: "Wschodząca gwiazda",
        wordWarrior: "Wojownik słów",
        knowledgeSeeker: "Poszukiwacz wiedzy",
        sentenceCrafter: "Budowniczy zdań",
        grammarGuardian: "Strażnik gramatyki",
        vocabularyVirtuoso: "Wirtuoz słownictwa",
        languageMaster: "Mistrz języka",
        fluencyPioneer: "Pionier płynności",
        polyglotLegend: "Legenda poliglotów",
        xpRequired: "Wymagane XP",
        overview: "Przegląd",
        sessions: "Sesje",
        streak: "Seria",
        gamePerformance: "Wyniki w grach",
        currentStreak: "Aktualna seria",
        days: "dni",
        keepLearningEveryDay: "Ucz się każdego dnia, aby utrzymać swoją serię!",

        // Profile
        appearance: "Wygląd",
        sound: "Dźwięk",
        sync: "Synchronizacja",
        signOut: "Wyloguj się",
        darkLight: "Ciemny/Jasny",
        orbs: "Kule",
        quantum: "Kwant",
        nebula: "Mgławica",
        learner: "Uczeń",
        xp: "XP",
        words: "Słowa",
        activityCalendar: "Kalendarz aktywności",
        dayStreak: "dni z rzędu",
        darkMode: "Tryb ciemny",
        cosmicDarkTheme: "Kosmiczna noc",
        lightModeActive: "Tropikalna wyspa",
        animationSpeed: "Szybkość animacji",
        slow: "Wolna",
        normal: "Normalna",
        fast: "Szybka",
        languagePair: "Para językowa",
        version: "Wersja 1.0.0",
        madeWithLove: "Stworzone z \u{2764}\u{FE0F} dla miłośników języków",

        // Sound Settings
        masterSound: "Dźwięk główny",
        allSoundsEnabled: "Wszystkie dźwięki włączone",
        allSoundsMuted: "Wszystkie dźwięki wyciszone",
        allGames: "Wszystkie gry",
        toggleAllGameSounds: "Przełącz dźwięki wszystkich gier",
        flashcardsSound: "Fiszki",
        grammarSound: "Gramatyka",
        wordBuilderSound: "Konstruktor słów",
        uiInteractions: "Interakcje interfejsu",
        buttonTapsNavigation: "Dźwięki przycisków i nawigacji",
        achievements: "Osiągnięcia",
        levelUpFanfares: "Fanfary za awans i bonusy za serie",
        ambientAudio: "Dźwięk otoczenia",
        backgroundAtmospheric: "Atmosferyczne dźwięki w tle",

        // Sync
        cloudSync: "Synchronizacja z chmurą",
        backupRestore: "Kopia zapasowa i przywracanie postępów",
        upload: "Wyślij",
        download: "Pobierz",
        lastSynced: "Ostatnia synchronizacja:",
        never: "Nigdy",
        justNow: "Właśnie teraz",
        changesPending: "Oczekujące zmiany",
        dataUploaded: "Dane wysłane pomyślnie",
        dataDownloaded: "Dane pobrane pomyślnie",
        syncSecurityNote: "Twoje dane są przechowywane bezpiecznie. Synchronizacja wymaga połączenia z internetem.",
        minAgo: "min temu",
        hoursAgo: "godz. temu",
        daysAgo: "dni temu",

        // Sign Out
        connected: "Połączono",
        offline: "Offline",
        signOutRequiresInternet: "Wylogowanie wymaga połączenia z internetem",
        email: "E-mail",
        name: "Imię",
        membership: "Członkostwo",
        freeTier: "Plan darmowy",
        areYouSure: "Czy na pewno?",
        progressWillBeSaved: "Twoje postępy zostaną zapisane przed wylogowaniem.",
        savingProgress: "Zapisywanie postępów\u{2026}",
        clearingLocalData: "Czyszczenie danych lokalnych\u{2026}",
        signingOut: "Wylogowywanie\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Oddychające kule",
        ambientBackgroundAnimation: "Animacja tła otoczenia",
        raveMode: "Tryb imprezowy",
        rapidColorCycling: "Szybka zmiana kolorów przez wszystkie schematy",
        colorScheme: "Schemat kolorów",
        intensity: "Intensywność",
        subtle: "Subtelna",
        balanced: "Zrównoważona",
        celestial: "Niebiańska",
        speed: "Szybkość",
        calm: "Spokojna",
        flowing: "Płynna",
        swift_: "Dynamiczna",
        perfectStillness: "Idealny bezruch",
        gentleAndPeaceful: "Łagodna i spokojna",
        balancedRhythm: "Zrównoważony rytm",
        quickAndEnergetic: "Szybka i energiczna",

        // Quantum Flow
        quantumFlow: "Przepływ kwantowy",
        dynamicParticleAnimation: "Dynamiczna warstwa animacji cząsteczek",
        scene: "Scena",
        particleDensity: "Gęstość cząsteczek",
        sparse: "Rzadka",
        dense: "Gęsta",
        flowSpeed: "Szybkość przepływu",
        serene: "Spokojna",
        rhythmic: "Rytmiczna",
        energetic: "Energiczna",
        exitPreview: "Zamknij podgląd",

        // Nebula Drift
        nebulaDrift: "Dryfująca mgławica",
        cosmicNebulaBackground: "Kosmiczna warstwa tła mgławicy",
        nebulaOptimizedDarkMode: "Dryfująca mgławica jest zoptymalizowana pod tryb ciemny",
        nebulaPreset: "Preset mgławicy",
        nebulaIntensity: "Intensywność mgławicy",
        vivid: "Żywa",
        driftSpeed: "Szybkość dryfu",
        frozen: "Zamrożona",
        nebulaDescLagoon: "Eteryczne różowo-fioletowe obłoki, gdzie nowo narodzone gwiazdy rozbłyskują w filarach kosmicznego pyłu",
        nebulaDescCelestial: "Nieskończony turkusowy ocean świecącego gazu, mieniący się cyjanowymi i morskimi refleksami gwiezdnego światła",
        nebulaDescAndromeda: "Bilion słońc zawieszonych na krawędzi galaktyki, bursztynowe światło rozpływa się w głębokim indygo kosmosu",
        nebulaDescSolarAurora: "Złote wstęgi naładowanych cząstek spływają przez pola magnetyczne, malując próżnię ciepłem i blaskiem",
        nebulaDescSpiralHalo: "Sto miliardów gwiazd wiruje w doskonałej harmonii, ich fioletowa poświata kreśli grawitacyjne ścieżki",
        nebulaDescStarburst: "Olśniewający pierścień szybkiej formacji gwiezdnej, łuki elektrycznego błękitu i magenty pełne energii",

        // Membership
        plansAndPricing: "Plany i cennik",
        investInYour: "Zainwestuj w swoją",
        languageMastery: "Biegłość językową",
        membershipSubtitle: "Dołącz do tysięcy osób, które uczą się mądrzej, nie ciężej.",
        monthly: "Miesięcznie",
        yearlyDiscount: "Rocznie  -17%",
        featureComparison: "Porównanie funkcji",
        feature: "Funkcja",
        free: "Darmowy",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Najczęściej zadawane pytania",
        secure: "Bezpieczne",
        dayRefund: "30-dniowy zwrot",
        cancelAnytime: "Anuluj w każdej chwili",
        pricesShownUSD: "Ceny podane w USD. Mogą obowiązywać podatki.",
        popular: "POPULARNE",
        starter: "Start",
        beginYourJourney: "Rozpocznij swoją podróż",
        masterLanguagesFaster: "Opanuj języki szybciej",
        unlockFullPotential: "Odblokuj swój pełny potencjał",
        ultimateExperience: "Najwyższa jakość doświadczenia",
        currentPlan: "Aktualny plan",
        getStarted: "Rozpocznij",
        startPro: "Rozpocznij Pro",
        upgradeToElite: "Ulepsz do Elite",
        ascendToRoyal: "Wejdź na poziom Royal",

        // Game Type Names
        gameFlashCards: "Fiszki",
        gameGrammar: "Gramatyka",
        gameWordBuilder: "Konstruktor słów",

        // Additional UI
        languageMasteryEngine: "Silnik Nauki Języków",
        user: "Użytkownik",
        perMonth: "/mies.",
        perYear: "/rok",

        // Membership Feature Names
        featureLanguagePairs: "Pary Językowe",
        featureDailyPractice: "Codzienna Praktyka",
        featureGameModes: "Tryby Gry",
        featureBreathingOrbs: "Oddychające Kule",
        featureQuantumFlow: "Przepływ Kwantowy",
        featureNebulaDrift: "Dryfująca Mgławica",
        featureOfflineMode: "Tryb Offline",
        featureCloudSync: "Synchronizacja w Chmurze",
        featurePrioritySupport: "Priorytetowe Wsparcie",
        unlimited: "Bez limitu",
        allModes: "Wszystkie 3",
        scheme1: "1 schemat",
        schemes3: "3 schematy",
        allSchemes: "Wszystkie schematy",
        scenes2: "2 sceny",
        allScenes: "Wszystkie sceny",
        presets3: "3 presety",
        allPresets: "Wszystkie presety",
        min15: "15 min",

        // Offline Mode / Connectivity
        offlineMode: "Tryb offline",
        offlineModeDescription: "Korzystaj z treści bez połączenia z internetem",
        offlineModeLockedDescription: "Ulepsz do Pro, aby korzystać z treści offline",
        connectToUse: "Połącz się, aby korzystać z treści",
        connectivityRequired: "Plan darmowy wymaga połączenia z internetem, aby uzyskać dostęp do treści",
        offlineModeInfo: "Gdy tryb offline jest włączony, treści są dostępne bez połączenia sieciowego. Plany Pro i wyższe pozwalają uczyć się wszędzie.",
        offlineModeDisabled: "Tryb offline wyłączony",
        offlineModeDisabledDetail: "Twój plan nie obejmuje już dostępu offline",
        offlineModeActive: "Tryb offline aktywny",
        offlineModeIncluded: "Twoja subskrypcja obejmuje dostęp offline",
        onlineOnly: "Tylko online",
        offlineModeActivated: "Tryb offline aktywowany",
        offlineModeActivatedDetail: "Dostęp offline jest teraz dostępny",

        // MARK: - Upgrade Prompts
        unlockPremium: "Odblokuj Premium",
        viewPlans: "Zobacz plany",
        maybeLater: "Może później",
        requires: "Wymaga",
        learnMore: "Dowiedz się więcej",
        hideForever: "Ukryj na zawsze",
        dontShowAgain: "Nie pokazuj ponownie",

        // MARK: - Royal Trial
        trialActivated: "Wersja Próbna Aktywowana!",
        trialWelcomeMessage: "Witaj w 14 dniach pełnego dostępu Royal. Wszystkie funkcje premium są Twoje.",
        trialDuration: "14 Dni Dostępu Royal",
        trialAfterExpiry: "Po 14 dniach przejdziesz na plan Darmowy. Bez opłat.",
        trialStartExploring: "Zacznij Odkrywać",
        trialBannerTitle: "Wersja Próbna Royal",
        trialExpiringToday: "Wygasa dzisiaj",
        trialOneDayLeft: "Pozostał 1 dzień",
        trialDaysLeft: "dni pozostało",
        trialEndedTitle: "Twoja Wersja Próbna Się Skończyła",
        trialEndedSubtitle: "Dziękujemy za wypróbowanie Royal! Twój postęp jest bezpieczny.",
        trialYourProgress: "Twój Postęp z Próby",
        trialLevel: "Poziom",
        trialStreak: "Seria",
        trialYouStillHave: "Nadal Masz",
        trialChoosePlan: "Wybierz Plan",
        trialContinueFree: "Kontynuuj za Darmo",
        trialCompleted: "Próba Zakończona",
        trialCompletedTagline: "Doświadczyłeś Royal",
        trialStartFree: "Rozpocznij Darmową Próbę",

        // MARK: - Dashboard Feature Visibility
        welcomeName: { "Witaj, \($0)!" },
        daysLeftInTrial: { "\($0) dni próby pozostało" },
        thirtyMinPerDay: "30 min/dzień",
        resetsIn: { "Odświeża za \($0)" },
        nowPlaying: "Odtwarzanie",
        paused: "Wstrzymano",

        // MARK: - Game Session Results
        xpBonus: "Bonus XP",
        timeSpentLabel: "Czas",
        streakActive: "Aktywna",
        streakLabel: "Seria",
        vsPreviousSession: "vs Poprzednia sesja",
        keepImproving: "Poprawiaj się z każdą sesją!",
        recentPerformance: "Ostatnie wyniki",
        last7Sessions: "Ostatnie 7 sesji",
        areasToImprove: "Obszary do poprawy",
        reviewIncorrect: { "Przejrzyj \($0) błędnych odpowiedzi" },
        shareResult: "Udostępnij wynik",
        availableOn: { "Dostępne w \($0)" },

        // MARK: - Journey Progress Gating
        dailyXPChart: "Dzienny XP",
        last7Days: "Ostatnie 7 dni",
        weeklyTrend: "Trend Tygodniowy",
        thisWeekVsLastWeek: "Ten tydzień vs poprzedni",
        thisWeekLabel: "Ten tydzień",
        lastWeekLabel: "Poprzedni tydzień",
        totalThisWeek: "Łącznie w tym tygodniu",
        accuracyHeatmap: "Mapa Dokładności",
        accuracyByCategory: "Dokładność wg kategorii",
        playSessionsToSeeData: "Graj aby zobaczyć dane",
        monthlyReport: "Raport Miesięczny",
        last30Days: "Ostatnie 30 dni",
        activeDaysLabel: "Aktywne Dni",
        milestonePredictionsTitle: "Prognozy Kamieni Milowych",
        basedOnYourPace: "Na podstawie twojego tempa",
        allMilestonesReached: "Wszystkie kamienie milowe osiągnięte!",
        tapToUpgrade: "Dotknij aby ulepszyć",
        unlockFeature: "Odblokuj tę funkcję",
        gameBreakdownDesc: "Sprawdź, w czym błyszczysz — śledź wyniki, dokładność i czas w każdym trybie gry",
        dailyXPChartDesc: "Wizualizuj swój postęp — obserwuj dzienny XP rozwijający się przez cały tydzień",
        weeklyTrendDesc: "Porównaj ten tydzień z poprzednim i odkryj wzorce napędzające Twój rozwój",
        accuracyHeatmapDesc: "Natychmiast odkryj swoje najsilniejsze i najsłabsze kategorie jednym spojrzeniem",
        monthlyReportDesc: "Twoje spersonalizowane podsumowanie 30 dni — sesje, serie, dokładność i aktywne dni",
        milestonePredictionsDesc: "Dowiedz się, kiedy osiągniesz kolejny kamień milowy na podstawie swojego tempa nauki",
        exportData: "Eksportuj Dane",
        exportDataDesc: "Pobierz swoją historię nauki — przeglądaj postępy offline, udostępniaj tutorom lub zachowaj jako osobisty zapis",
        exportAsCSV: "Eksportuj jako CSV",
        exportAsJSON: "Eksportuj jako JSON",
        exportAsPDF: "Eksportuj jako PDF",
        exportReady: "Twoje dane są gotowe do udostępnienia",
        noDataToExport: "Brak danych do eksportu",
        sessionsLabel: "Sesje",
        learningInsights: "Analiza Nauki",
        insightsDesc: "Odblokuj głęboką analitykę — odkryj optymalne godziny nauki, śledź postępy w kategoriach i przewiduj swoją linię biegłości",
        optimalPracticeTimes: "Optymalne Godziny Ćwiczeń",
        bestTimeToLearn: "Twój najlepszy czas na naukę",
        categoryMastery: "Opanowanie Kategorii",
        masteryByCategory: "Opanowanie według kategorii",
        retentionCurve: "Krzywa Zapamiętywania",
        retentionOverTime: "Zapamiętywanie w czasie",
        fluencyTimeline: "Oś Czasu Biegłości",
        predictedMilestones: "Przewidywane kamienie milowe",
        morning: "Rano",
        afternoon: "Popołudnie",
        evening: "Wieczór",
        night: "Noc",
        needMoreData: "Zagraj więcej sesji, aby uzyskać analizy",
        upgradedExclamation: "Ulepszono!",
        tierChangedExclamation: "Witaj!",
        upgradeMessagePro: "Mówisz językiem postępu — każda lekcja kształtuje Twój głos na świecie.",
        upgradeMessageElite: "Twoje słowa niosą ciężar poświęcenia — doskonałość staje się Twoim językiem ojczystym.",
        upgradeMessageRoyal: "Ukoronowałeś swoją podróż słowami — język legend należy do Ciebie.",
        upgradeMessageTrial: "Królewski rozdział się zaczyna — pełna historia Twojego potencjału językowego czeka.",
        // MARK: - Legal Consent
        legalConsentTitle: "Zanim zaczniemy",
        legalConsentSubtitle: "Zapoznaj się z naszymi zasadami, aby kontynuować korzystanie z LumenLingo",
        privacyPolicyTitle: "Polityka prywatności",
        termsOfServiceTitle: "Regulamin",
        legalVersion: "Wersja 2.0",
        legalLastUpdated: "Ostatnia aktualizacja: 23 marca 2026",
        legalPrivacySummary: "LumenLingo jest obsługiwane przez LumenShore Ltd. Szanujemy Twoją prywatność i zobowiązujemy się do ochrony Twoich danych osobowych. Ta polityka obejmuje naszą stronę internetową i aplikację iOS.",
        legalTermsSummary: "Niniejszy Regulamin reguluje korzystanie z aplikacji mobilnej LumenLingo obsługiwanej przez LumenShore Ltd. Korzystając z LumenLingo, akceptujesz niniejszy Regulamin.",
        legalPrivacyHighlight1: "Twoje dane nauki pozostają na Twoim urządzeniu i osobistym koncie iCloud",
        legalPrivacyHighlight2: "Używamy Vercel Analytics bez ciasteczek — żadnych śledzących plików cookie na naszej stronie",
        legalPrivacyHighlight3: "Sentry pomaga nam naprawiać błędy (nagrywanie sesji wymaga zgody)",
        legalPrivacyHighlight4: "Nigdy nie sprzedajemy Twoich danych osobowych stronom trzecim",
        legalTermsHighlight1: "Dostępne plany darmowe i premium — subskrypcje zarządzane przez Apple",
        legalTermsHighlight2: "Twoje treści i postępy w nauce należą do Ciebie",
        legalTermsHighlight3: "Możemy używać zagregowanych, anonimowych danych do ulepszania produktu",
        legalTermsHighlight4: "Podlega prawu Anglii i Walii",
        legalAcceptAll: "Akceptuję",
        legalDecline: "Odrzuć",
        legalDeclineTitle: "Czy na pewno?",
        legalDeclineMessage: "Musisz zaakceptować naszą Politykę Prywatności i Regulamin, aby korzystać z LumenLingo.",
        legalDeclineConfirm: "Odrzuć i wyjdź",
        legalReadFull: "Przeczytaj pełną politykę",
        legalScrollToAccept: "Przewiń, aby przejrzeć",

        // MARK: - EULA
        eulaTitle: "Umowa Licencyjna Użytkownika Końcowego",
        eulaSummary: "Niniejsza umowa licencyjna reguluje korzystanie z aplikacji LumenLingo, dystrybuowanej przez LumenShore Ltd za pośrednictwem Apple App Store.",
        eulaHighlight1: "Niewyłączna, odwołalna licencja na osobistą naukę języków",
        eulaHighlight2: "Dostęp warstwowy — członkostwo Darmowe, Pro, Elite i Royal",
        eulaHighlight3: "Twoje dane nauki należą do Ciebie; treść aplikacji należy do nas",
        eulaHighlight4: "Warunki specyficzne dla Apple zgodnie z wymaganiami App Store",

        // MARK: - Subscription Disclosure
        subscriptionAutoRenew: "Subskrypcje odnawiają się automatycznie co miesiąc, chyba że zostaną anulowane co najmniej 24 godziny przed końcem bieżącego okresu.",
        subscriptionPaymentNotice: "Płatność zostanie pobrana z konta Apple ID po potwierdzeniu zakupu.",
        subscriptionManageCancel: "Zarządzaj lub anuluj w Ustawienia → Apple ID → Subskrypcje.",
        subscriptionTrialNotice: "14-dniowy bezpłatny okres próbny Royal. Po zakończeniu przechodzi na plan Darmowy.",
        restorePurchases: "Przywróć zakupy",
        subscriptionLegalPrefix: "Subskrybując, akceptujesz nasze",
        subscriptionLegalAnd: "i"
,

        // MARK: - Account Deletion
        deleteAccount: "Usuń konto",
        deleteAccountWarning: "Spowoduje to trwałe usunięcie wszystkich danych nauki, postępów, serii i preferencji. Tej czynności nie można cofnąć.",
        deleteAccountConfirm: "Usuń wszystko",
        deletingAccount: "Usuwanie konta…",
        clearingUserData: "Usuwanie danych użytkownika",
        accountDeleted: "Konto usunięte",

        // MARK: - GDPR Data Export
        gdprExportTitle: "Eksportuj moje dane",
        gdprExportDesc: "Pobierz wszystkie swoje dane osobowe jako plik JSON w formacie czytelnym maszynowo. To Twoje prawo na mocy art. 20 RODO — bezpłatnie dla wszystkich użytkowników.",
        gdprExportButton: "Eksportuj dane osobowe",
        gdprExportSuccess: "Dane wyeksportowane pomyślnie",
        gdprExportEmpty: "Brak danych osobowych do eksportu",

        trademarkAttribution: "Apple, the Apple logo, iPhone, iPad, App Store, iCloud, Apple ID, and iOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions."
    )
}