import Foundation

extension AppStrings {
    static let polish = AppStrings(
        // Tabs
        tabHome: "Główna",
        tabStats: "Statystyki",
        tabPremium: "Premium",
        tabProfile: "Profil",

        // Dashboard
        greeting: { "Cześć, \($0)!" },
        goodMorning: "Dzień dobry",
        goodAfternoon: "Dzień dobry",
        goodEvening: "Dobry wieczór",
        goodNight: "Dobranoc",
        readyForAdventure: "Gotowy na nową przygodę?",
        level: "Poziom",
        totalXP: "Łączne XP",
        activeDays: "Aktywne dni",
        chooseYourAdventure: "Wybierz swoją przygodę",
        startGameToBoost: "Rozpocznij grę, aby rozwinąć swoje umiejętności",
        flashCards: "Fiszki",
        flashCardsDescription: "Opanuj nowe słówka dzięki interaktywnym fiszkom i powtórkom rozłożonym w czasie",
        masterNewWords: "Opanuj nowe słowa",
        grammarChallenge: "Wyzwanie gramatyczne",
        grammarDescription: "Sprawdź swoją wiedzę w wymagających pytaniach i regułach gramatycznych",
        testYourSkills: "Sprawdź swoje umiejętności",
        wordConstructor: "Konstruktor słów",
        wordBuilderDescription: "Buduj słowa litera po literze z pomieszanych liter i podpowiedzi",
        craftAndDiscover: "Twórz i odkrywaj",
        recentActivity: "Ostatnia aktywność",

        // Language Selection
        languages: "Języki",
        cancel: "Anuluj",
        searchLanguages: "Szukaj języków\u{2026}",
        chooseYourLanguages: "Wybierz swoje języki",
        selectWhatYouKnow: "Wybierz język, który znasz, i ten, którego się uczysz",
        iSpeak: "Mówię po",
        imLearning: "Uczę się",
        noLanguagesAvailable: "Brak dostępnych języków dla tego źródła.",
        betaLanguagePairs: "Pary językowe w wersji beta",
        showExperimentalPairs: "Pokaż eksperymentalne pary z ograniczoną zawartością",
        confirm: "Potwierdź:",

        // Categories
        back: "Wstecz",
        searchCategories: "Szukaj kategorii",
        noCategories: "Brak kategorii",
        noFavouritesYet: "Brak ulubionych",
        allComplete: "Wszystko ukończone!",
        noResults: "Brak wyników",
        tapHeartToSave: "Dotknij serduszko przy kategorii, aby ją zapisać tutaj",
        youveFinishedEverything: "Ukończyłeś wszystko — świetna robota!",
        tryDifferentSearch: "Spróbuj innego wyszukiwania",
        categoriesWillAppear: "Kategorie pojawią się po załadowaniu treści",
        clearFilters: "Wyczyść filtry",
        items: "elementy",
        complete: "Ukończono",
        doubleTapToStart: "Dotknij dwukrotnie, aby rozpocząć",

        // Flash Cards
        loadingCards: "Ładowanie kart\u{2026}",
        tapToReveal: "Dotknij, aby odkryć",
        stillLearning: "Jeszcze się uczę",
        gotIt: "Umiem!",
        noCardsAvailable: "Brak dostępnych kart",
        goBack: "Wróć",

        // Grammar
        loadingQuestions: "Ładowanie pytań\u{2026}",
        grammarTip: "Wskazówka gramatyczna",
        next: "Dalej",
        noQuestionsAvailable: "Brak dostępnych pytań",

        // Word Builder
        loadingWords: "Ładowanie słów\u{2026}",
        buildTheWord: "Zbuduj słowo",
        availableLetters: "Dostępne litery",
        undo: "Cofnij",
        clear: "Wyczyść",
        check: "Sprawdź",
        noWordsAvailable: "Brak dostępnych słów",

        // Game Complete
        excellent: "Doskonale!",
        greatJob: "Świetna robota!",
        goodWork: "Dobra robota!",
        keepGoing: "Tak trzymaj!",
        excellentSubtitle: "Wybitny wynik! Masz do tego talent!",
        greatJobSubtitle: "Imponująca praca! Nie zwalniaj tempa!",
        goodWorkSubtitle: "Solidny wysiłek! Praktyka czyni mistrza!",
        keepGoingSubtitle: "Każda sesja czyni Cię lepszym. Nie poddawaj się!",
        points: "punkty",
        accuracy: "Dokładność",
        correct: "Poprawne",
        toReview: "Do powtórki",
        playAgain: "Zagraj ponownie",
        backToCategories: "Wróć do kategorii",

        // Journey
        yourLearningJourney: "Twoja droga nauki",
        trackYourProgress: "Śledź swoje postępy i świętuj osiągnięcia",
        milestones: "Kamienie milowe",
        firstSteps: "Pierwsze kroki",
        gettingStarted: "Początek drogi",
        dedicatedLearner: "Zaangażowany uczeń",
        wordWarrior: "Wojownik słów",
        languageMaster: "Mistrz języka",
        polyglotLegend: "Legenda poliglotów",
        xpRequired: "Wymagane XP",
        overview: "Przegląd",
        sessions: "Sesje",
        streak: "Seria",
        gamePerformance: "Wyniki w grach",
        currentStreak: "Aktualna seria",
        days: "dni",
        keepLearningEveryDay: "Ucz się każdego dnia, aby utrzymać swoją serię!",

        // Profile
        appearance: "Wygląd",
        sound: "Dźwięk",
        beta: "Beta",
        sync: "Synchronizacja",
        signOut: "Wyloguj się",
        darkLight: "Ciemny/Jasny",
        orbs: "Kule",
        quantum: "Kwant",
        nebula: "Mgławica",
        learner: "Uczeń",
        xp: "XP",
        darkMode: "Tryb ciemny",
        cosmicDarkTheme: "Kosmiczny ciemny motyw aktywny",
        lightModeActive: "Tryb jasny aktywny",
        animationSpeed: "Szybkość animacji",
        slow: "Wolna",
        normal: "Normalna",
        fast: "Szybka",
        languagePair: "Para językowa",
        version: "Wersja 1.0.0",
        madeWithLove: "Stworzone z \u{2764}\u{FE0F} dla miłośników języków",

        // Sound Settings
        masterSound: "Dźwięk główny",
        allSoundsEnabled: "Wszystkie dźwięki włączone",
        allSoundsMuted: "Wszystkie dźwięki wyciszone",
        allGames: "Wszystkie gry",
        toggleAllGameSounds: "Przełącz dźwięki wszystkich gier",
        flashcardsSound: "Fiszki",
        grammarSound: "Gramatyka",
        wordBuilderSound: "Konstruktor słów",
        uiInteractions: "Interakcje interfejsu",
        buttonTapsNavigation: "Dźwięki przycisków i nawigacji",
        achievements: "Osiągnięcia",
        levelUpFanfares: "Fanfary za awans i bonusy za serie",
        ambientAudio: "Dźwięk otoczenia",
        backgroundAtmospheric: "Atmosferyczne dźwięki w tle",

        // Beta Languages
        betaLanguages: "Języki w wersji beta",
        experimentalLanguagePairs: "Eksperymentalne pary językowe",
        experimentalFeatures: "Funkcje eksperymentalne",
        betaLimitedContent: "Języki w wersji beta mogą mieć ograniczoną zawartość lub sporadyczne niedokładności w tłumaczeniu.",
        coreLanguages: "Główne języki",
        alwaysOn: "Zawsze włączone",
        active: "Aktywne",
        experimentalLanguagesSection: "Języki eksperymentalne",
        on: "Wł.",
        off: "Wył.",

        // Sync
        cloudSync: "Synchronizacja z chmurą",
        backupRestore: "Kopia zapasowa i przywracanie postępów",
        upload: "Wyślij",
        download: "Pobierz",
        lastSynced: "Ostatnia synchronizacja:",
        never: "Nigdy",
        justNow: "Właśnie teraz",
        changesPending: "Oczekujące zmiany",
        dataUploaded: "Dane wysłane pomyślnie",
        dataDownloaded: "Dane pobrane pomyślnie",
        syncSecurityNote: "Twoje dane są przechowywane bezpiecznie. Synchronizacja wymaga połączenia z internetem.",
        minAgo: "min temu",
        hoursAgo: "godz. temu",
        daysAgo: "dni temu",

        // Sign Out
        connected: "Połączono",
        offline: "Offline",
        signOutRequiresInternet: "Wylogowanie wymaga połączenia z internetem",
        email: "E-mail",
        name: "Imię",
        membership: "Członkostwo",
        freeTier: "Plan darmowy",
        areYouSure: "Czy na pewno?",
        progressWillBeSaved: "Twoje postępy zostaną zapisane przed wylogowaniem.",
        savingProgress: "Zapisywanie postępów\u{2026}",
        clearingLocalData: "Czyszczenie danych lokalnych\u{2026}",
        signingOut: "Wylogowywanie\u{2026}",

        // Breathing Orbs
        breathingOrbs: "Oddychające kule",
        ambientBackgroundAnimation: "Animacja tła otoczenia",
        raveMode: "Tryb imprezowy",
        rapidColorCycling: "Szybka zmiana kolorów przez wszystkie schematy",
        colorScheme: "Schemat kolorów",
        intensity: "Intensywność",
        subtle: "Subtelna",
        balanced: "Zrównoważona",
        celestial: "Niebiańska",
        speed: "Szybkość",
        calm: "Spokojna",
        flowing: "Płynna",
        swift_: "Dynamiczna",
        perfectStillness: "Idealny bezruch",
        gentleAndPeaceful: "Łagodna i spokojna",
        balancedRhythm: "Zrównoważony rytm",
        quickAndEnergetic: "Szybka i energiczna",

        // Quantum Flow
        quantumFlow: "Przepływ kwantowy",
        dynamicParticleAnimation: "Dynamiczna warstwa animacji cząsteczek",
        scene: "Scena",
        particleDensity: "Gęstość cząsteczek",
        sparse: "Rzadka",
        dense: "Gęsta",
        flowSpeed: "Szybkość przepływu",
        serene: "Spokojna",
        rhythmic: "Rytmiczna",
        energetic: "Energiczna",
        exitPreview: "Zamknij podgląd",

        // Nebula Drift
        nebulaDrift: "Dryfująca mgławica",
        cosmicNebulaBackground: "Kosmiczna warstwa tła mgławicy",
        nebulaOptimizedDarkMode: "Dryfująca mgławica jest zoptymalizowana pod tryb ciemny",
        nebulaPreset: "Preset mgławicy",
        nebulaIntensity: "Intensywność mgławicy",
        vivid: "Żywa",
        driftSpeed: "Szybkość dryfu",
        frozen: "Zamrożona",

        // Membership
        plansAndPricing: "Plany i cennik",
        investInYour: "Zainwestuj w swoją",
        languageMastery: "Biegłość językową",
        membershipSubtitle: "Dołącz do tysięcy osób, które uczą się mądrzej, nie ciężej.\n30-dniowa gwarancja zwrotu \u{00B7} Anuluj w każdej chwili",
        monthly: "Miesięcznie",
        yearlyDiscount: "Rocznie  -17%",
        featureComparison: "Porównanie funkcji",
        feature: "Funkcja",
        free: "Darmowy",
        pro: "Pro",
        elite: "Elite",
        royal: "Royal",
        faq: "Najczęściej zadawane pytania",
        secure: "Bezpieczne",
        dayRefund: "30-dniowy zwrot",
        cancelAnytime: "Anuluj w każdej chwili",
        pricesShownUSD: "Ceny podane w USD. Mogą obowiązywać podatki.",
        popular: "POPULARNE",
        starter: "Start",
        beginYourJourney: "Rozpocznij swoją podróż",
        masterLanguagesFaster: "Opanuj języki szybciej",
        unlockFullPotential: "Odblokuj swój pełny potencjał",
        ultimateExperience: "Najwyższa jakość doświadczenia",
        currentPlan: "Aktualny plan",
        startPro: "Rozpocznij Pro",
        upgradeToElite: "Ulepsz do Elite",
        ascendToRoyal: "Wejdź na poziom Royal",

        // Game Type Names
        gameFlashCards: "Fiszki",
        gameGrammar: "Gramatyka",
        gameWordBuilder: "Konstruktor słów",

        // Additional UI
        languageMasteryEngine: "Silnik Nauki Języków",
        user: "Użytkownik",
        perMonth: "/mies.",
        perYear: "/rok",

        // Membership Feature Names
        featureLanguagePairs: "Pary Językowe",
        featureDailyPractice: "Codzienna Praktyka",
        featureGameModes: "Tryby Gry",
        featureBreathingOrbs: "Oddychające Kule",
        featureQuantumFlow: "Przepływ Kwantowy",
        featureNebulaDrift: "Dryfująca Mgławica",
        featureOfflineMode: "Tryb Offline",
        featureCloudSync: "Synchronizacja w Chmurze",
        featurePrioritySupport: "Priorytetowe Wsparcie",
        unlimited: "Bez limitu",
        allModes: "Wszystkie 3",
        scheme1: "1 schemat",
        schemes3: "3 schematy",
        allSchemes: "Wszystkie schematy",
        scenes2: "2 sceny",
        allScenes: "Wszystkie sceny",
        presets3: "3 presety",
        allPresets: "Wszystkie presety",
        min15: "15 min"
    )
}
