import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const MESSAGES = join(new URL('.', import.meta.url).pathname, '..', 'lumen-lingo-frontend', 'messages');
const LOCALES = ['en','es','fr','ja','de','pl','ar','zh','uk'];

/* ─── New keys per locale ─── */
const keys = {
  en: {
    comparison: {
      feature: 'Feature',
      mostPopular: 'Most Popular',
      categories: {
        learning: 'Learning Features',
        immersive: 'Immersive Experience',
        productivity: 'Productivity',
        analytics: 'Analytics & Insights',
        royalExclusive: 'Royal Exclusive',
      },
      features: {
        languagePairs: 'Language Pairs',
        practiceModes: 'Practice Modes',
        dailyLimit: 'Daily Practice Limit',
        deckSize: 'Flashcard Deck Size',
        breathingOrbs: 'Breathing Orbs',
        soundscapes: 'Soundscapes',
        quantumFlow: 'Quantum Flow Backgrounds',
        nebulaDrift: 'Nebula Drift Backgrounds',
        offlineMode: 'Offline Mode',
        xpMultiplier: 'XP Multiplier',
        advancedAnalytics: 'Advanced Analytics',
        dataExport: 'Data Export',
        shareCards: 'Shareable Result Cards',
        monthlyReports: 'Monthly Reports',
        personalisedTips: 'Personalised Tips',
      },
      values: {
        beginner: '3 (Beginner)',
        twoLevels: '3 (2 levels)',
        allLevels: '3 (All levels)',
        thirtyMin: '30 min',
        unlimited: 'Unlimited',
        fiftyCards: '50 cards',
        seventyFiveCards: '75 cards',
        hundredCards: '100 cards',
        fourScenes: '4 scenes',
        allSix: 'All 6',
        fourPresets: '4 presets',
        allTwelve: 'All 12',
      },
    },
    faq: {
      ariaLabel: 'Frequently Asked Questions',
      items: [
        { question: 'Is LumenLingo really free to start?', answer: 'Absolutely. The Free tier gives you 3 language pairs, all 3 practice modes at Beginner difficulty, and 30 minutes of daily practice — no credit card required, no trial expiration. You can learn at your own pace for as long as you like.' },
        { question: "What's included in the free tier?", answer: "Free users get English↔Spanish, English↔French, and English↔German language pairs, all three practice modes (Flashcards, Grammar Quizzes, Word Builder) at Beginner difficulty, 50-card flashcard decks, the Lagoon Nebula background, and basic progress tracking. It's a generous starting point." },
        { question: 'How does monthly billing work?', answer: 'All subscriptions are managed through the Apple App Store. You choose your tier in the app, confirm the purchase via Face ID or your Apple ID, and billing happens automatically each month. Apple handles all payment processing securely.' },
        { question: 'How do I upgrade or downgrade my tier?', answer: "You can change your tier at any time from the Membership screen in the app or through your App Store subscription settings. Upgrades take effect immediately. Downgrades take effect at the end of your current billing period, so you don't lose paid access early." },
        { question: 'Is there a free trial?', answer: "Yes! New users can try Royal-level access — the highest tier with every feature unlocked — free for 14 days. You'll experience all 25+ language pairs, 12 soundscapes, all visual backgrounds, and the 2× XP multiplier. Cancel anytime during the trial and you won't be charged." },
        { question: 'What payment methods are accepted?', answer: 'LumenLingo uses Apple App Store subscriptions, so any payment method linked to your Apple ID works — including credit/debit cards, Apple Pay, and App Store gift card balance. Payment processing is handled entirely by Apple.' },
        { question: 'Can I cancel my subscription at any time?', answer: "Yes, you can cancel at any time with no penalties or fees. Go to Settings → Apple ID → Subscriptions on your iPhone, find LumenLingo, and tap Cancel. You'll keep your current tier's access until the end of your billing period." },
        { question: 'Do I lose my progress if I downgrade?', answer: 'Never. All your learning progress, streaks, XP, and mastery data are preserved regardless of tier changes. If you downgrade, certain premium features become locked, but your data stays intact. Upgrade again anytime to pick up right where you left off.' },
        { question: 'Are there family or student discounts?', answer: "We're exploring group and educational pricing options. For now, the Free tier offers generous access for students and casual learners, and the 14-day Royal trial gives everyone a chance to experience the full app before committing." },
        { question: 'How does offline mode work?', answer: 'Offline mode (Pro tier and above) downloads your active flashcard decks and practice content to your device. You can study without an internet connection — on the tube, on a plane, anywhere. Progress syncs automatically when you reconnect.' },
      ],
    },
  },
  es: {
    comparison: {
      feature: 'Función',
      mostPopular: 'Más popular',
      categories: {
        learning: 'Funciones de aprendizaje',
        immersive: 'Experiencia inmersiva',
        productivity: 'Productividad',
        analytics: 'Análisis y estadísticas',
        royalExclusive: 'Exclusivo Royal',
      },
      features: {
        languagePairs: 'Pares de idiomas',
        practiceModes: 'Modos de práctica',
        dailyLimit: 'Límite diario de práctica',
        deckSize: 'Tamaño del mazo',
        breathingOrbs: 'Orbes de respiración',
        soundscapes: 'Paisajes sonoros',
        quantumFlow: 'Fondos Quantum Flow',
        nebulaDrift: 'Fondos Nebula Drift',
        offlineMode: 'Modo sin conexión',
        xpMultiplier: 'Multiplicador de XP',
        advancedAnalytics: 'Análisis avanzado',
        dataExport: 'Exportar datos',
        shareCards: 'Tarjetas de resultados',
        monthlyReports: 'Informes mensuales',
        personalisedTips: 'Consejos personalizados',
      },
      values: {
        beginner: '3 (Principiante)',
        twoLevels: '3 (2 niveles)',
        allLevels: '3 (Todos los niveles)',
        thirtyMin: '30 min',
        unlimited: 'Ilimitado',
        fiftyCards: '50 tarjetas',
        seventyFiveCards: '75 tarjetas',
        hundredCards: '100 tarjetas',
        fourScenes: '4 escenas',
        allSix: 'Las 6',
        fourPresets: '4 preajustes',
        allTwelve: 'Las 12',
      },
    },
    faq: {
      ariaLabel: 'Preguntas frecuentes',
      items: [
        { question: '¿LumenLingo es realmente gratis para empezar?', answer: 'Por supuesto. El nivel Gratis te ofrece 3 pares de idiomas, los 3 modos de práctica en dificultad Principiante y 30 minutos de práctica diaria — sin tarjeta de crédito, sin fecha de expiración. Aprende a tu ritmo todo el tiempo que quieras.' },
        { question: '¿Qué incluye el nivel gratuito?', answer: 'Los usuarios gratuitos obtienen los pares inglés↔español, inglés↔francés e inglés↔alemán, los tres modos de práctica (Tarjetas, Cuestionarios de gramática, Constructor de palabras) en dificultad Principiante, mazos de 50 tarjetas, el fondo Lagoon Nebula y seguimiento básico de progreso.' },
        { question: '¿Cómo funciona la facturación mensual?', answer: 'Todas las suscripciones se gestionan a través del App Store de Apple. Eliges tu nivel en la app, confirmas la compra con Face ID o tu Apple ID y la facturación se realiza automáticamente cada mes.' },
        { question: '¿Cómo puedo subir o bajar de nivel?', answer: 'Puedes cambiar de nivel en cualquier momento desde la pantalla de Membresía o los ajustes de suscripción del App Store. Las mejoras se aplican de inmediato. Las bajadas entran en vigor al final del período de facturación actual.' },
        { question: '¿Hay una prueba gratuita?', answer: '¡Sí! Los nuevos usuarios pueden probar el acceso Royal — el nivel más alto — gratis durante 14 días. Disfrutarás de más de 25 pares de idiomas, 12 paisajes sonoros, todos los fondos visuales y el multiplicador 2× de XP. Cancela en cualquier momento durante la prueba sin cargos.' },
        { question: '¿Qué métodos de pago se aceptan?', answer: 'LumenLingo usa suscripciones del App Store de Apple, así que cualquier método de pago vinculado a tu Apple ID funciona — tarjetas de crédito/débito, Apple Pay y saldo de tarjetas regalo del App Store.' },
        { question: '¿Puedo cancelar mi suscripción en cualquier momento?', answer: 'Sí, puedes cancelar en cualquier momento sin penalizaciones. Ve a Ajustes → Apple ID → Suscripciones, busca LumenLingo y toca Cancelar. Mantendrás el acceso de tu nivel actual hasta el final del período de facturación.' },
        { question: '¿Pierdo mi progreso si bajo de nivel?', answer: 'Nunca. Todo tu progreso, rachas, XP y datos de dominio se conservan. Si bajas de nivel, ciertas funciones premium se bloquean, pero tus datos permanecen intactos. Vuelve a subir en cualquier momento.' },
        { question: '¿Hay descuentos familiares o para estudiantes?', answer: 'Estamos explorando opciones de precios grupales y educativos. Por ahora, el nivel Gratis ofrece acceso generoso para estudiantes, y la prueba Royal de 14 días permite a todos experimentar la app completa.' },
        { question: '¿Cómo funciona el modo sin conexión?', answer: 'El modo sin conexión (nivel Pro o superior) descarga tus mazos de tarjetas y contenido de práctica en tu dispositivo. Estudia sin conexión a internet — en el metro, en un avión, donde sea. El progreso se sincroniza automáticamente al reconectarte.' },
      ],
    },
  },
  fr: {
    comparison: {
      feature: 'Fonctionnalité',
      mostPopular: 'Le plus populaire',
      categories: {
        learning: "Fonctions d'apprentissage",
        immersive: 'Expérience immersive',
        productivity: 'Productivité',
        analytics: 'Analyses et statistiques',
        royalExclusive: 'Exclusivité Royal',
      },
      features: {
        languagePairs: 'Paires de langues',
        practiceModes: "Modes d'entraînement",
        dailyLimit: "Limite quotidienne d'entraînement",
        deckSize: 'Taille du paquet de cartes',
        breathingOrbs: 'Orbes de respiration',
        soundscapes: 'Ambiances sonores',
        quantumFlow: 'Arrière-plans Quantum Flow',
        nebulaDrift: 'Arrière-plans Nebula Drift',
        offlineMode: 'Mode hors ligne',
        xpMultiplier: 'Multiplicateur XP',
        advancedAnalytics: 'Analyses avancées',
        dataExport: 'Export de données',
        shareCards: 'Cartes de résultats partageables',
        monthlyReports: 'Rapports mensuels',
        personalisedTips: 'Conseils personnalisés',
      },
      values: {
        beginner: '3 (Débutant)',
        twoLevels: '3 (2 niveaux)',
        allLevels: '3 (Tous les niveaux)',
        thirtyMin: '30 min',
        unlimited: 'Illimité',
        fiftyCards: '50 cartes',
        seventyFiveCards: '75 cartes',
        hundredCards: '100 cartes',
        fourScenes: '4 scènes',
        allSix: 'Les 6',
        fourPresets: '4 préréglages',
        allTwelve: 'Les 12',
      },
    },
    faq: {
      ariaLabel: 'Questions fréquemment posées',
      items: [
        { question: 'LumenLingo est-il vraiment gratuit pour commencer ?', answer: "Absolument. Le niveau Gratuit vous offre 3 paires de langues, les 3 modes d'entraînement en difficulté Débutant et 30 minutes de pratique quotidienne — sans carte bancaire ni date d'expiration. Apprenez à votre rythme aussi longtemps que vous le souhaitez." },
        { question: "Qu'est-ce qui est inclus dans le niveau gratuit ?", answer: "Les utilisateurs gratuits bénéficient des paires anglais↔espagnol, anglais↔français et anglais↔allemand, des trois modes d'entraînement (Cartes mémoire, Quiz de grammaire, Constructeur de mots) en difficulté Débutant, de paquets de 50 cartes, de l'arrière-plan Lagoon Nebula et du suivi de progression de base." },
        { question: 'Comment fonctionne la facturation mensuelle ?', answer: "Tous les abonnements sont gérés via l'App Store d'Apple. Choisissez votre niveau dans l'app, confirmez l'achat via Face ID ou votre Apple ID, et la facturation est automatique chaque mois." },
        { question: 'Comment passer à un niveau supérieur ou inférieur ?', answer: "Vous pouvez changer de niveau à tout moment depuis l'écran Abonnement dans l'app ou les réglages de l'App Store. Les mises à niveau prennent effet immédiatement. Les rétrogradations prennent effet à la fin de la période de facturation en cours." },
        { question: "Y a-t-il un essai gratuit ?", answer: "Oui ! Les nouveaux utilisateurs peuvent essayer l'accès Royal — le niveau le plus élevé — gratuitement pendant 14 jours. Profitez de plus de 25 paires de langues, 12 ambiances sonores, tous les arrière-plans visuels et le multiplicateur 2× XP. Annulez à tout moment pendant l'essai sans frais." },
        { question: 'Quels modes de paiement sont acceptés ?', answer: "LumenLingo utilise les abonnements App Store d'Apple, donc tout mode de paiement lié à votre Apple ID fonctionne — cartes bancaires, Apple Pay et solde de cartes cadeaux App Store." },
        { question: 'Puis-je annuler mon abonnement à tout moment ?', answer: "Oui, vous pouvez annuler à tout moment sans pénalité. Allez dans Réglages → Apple ID → Abonnements, trouvez LumenLingo et touchez Annuler. Vous conserverez l'accès de votre niveau jusqu'à la fin de la période de facturation." },
        { question: 'Est-ce que je perds ma progression si je rétrograde ?', answer: 'Jamais. Toute votre progression, vos séries, XP et données de maîtrise sont préservées. Si vous rétrogradez, certaines fonctionnalités premium sont verrouillées, mais vos données restent intactes. Repassez à un niveau supérieur à tout moment.' },
        { question: 'Y a-t-il des réductions familiales ou étudiantes ?', answer: "Nous explorons des options de tarification pour les groupes et l'éducation. Pour l'instant, le niveau Gratuit offre un accès généreux aux étudiants, et l'essai Royal de 14 jours permet à chacun de découvrir l'app complète." },
        { question: 'Comment fonctionne le mode hors ligne ?', answer: "Le mode hors ligne (niveau Pro et supérieur) télécharge vos paquets de cartes et contenus d'entraînement sur votre appareil. Étudiez sans connexion internet — dans le métro, en avion, n'importe où. La progression se synchronise automatiquement à la reconnexion." },
      ],
    },
  },
  ja: {
    comparison: {
      feature: '機能',
      mostPopular: '一番人気',
      categories: {
        learning: '学習機能',
        immersive: '没入体験',
        productivity: '生産性',
        analytics: '分析とインサイト',
        royalExclusive: 'Royal限定',
      },
      features: {
        languagePairs: '言語ペア',
        practiceModes: '練習モード',
        dailyLimit: '1日の練習上限',
        deckSize: 'フラッシュカードデッキ数',
        breathingOrbs: 'ブリージングオーブ',
        soundscapes: 'サウンドスケープ',
        quantumFlow: 'Quantum Flow背景',
        nebulaDrift: 'Nebula Drift背景',
        offlineMode: 'オフラインモード',
        xpMultiplier: 'XP倍率',
        advancedAnalytics: '高度な分析',
        dataExport: 'データエクスポート',
        shareCards: '共有可能な結果カード',
        monthlyReports: '月次レポート',
        personalisedTips: 'パーソナライズされたヒント',
      },
      values: {
        beginner: '3（初級）',
        twoLevels: '3（2レベル）',
        allLevels: '3（全レベル）',
        thirtyMin: '30分',
        unlimited: '無制限',
        fiftyCards: '50枚',
        seventyFiveCards: '75枚',
        hundredCards: '100枚',
        fourScenes: '4シーン',
        allSix: '全6種',
        fourPresets: '4プリセット',
        allTwelve: '全12種',
      },
    },
    faq: {
      ariaLabel: 'よくある質問',
      items: [
        { question: 'LumenLingoは本当に無料で始められますか？', answer: 'はい。Freeプランでは3つの言語ペア、初級難易度の3つの練習モード、1日30分の練習が可能です。クレジットカード不要、期限なし。お好きなペースで学習できます。' },
        { question: '無料プランには何が含まれますか？', answer: '無料ユーザーは英語↔スペイン語、英語↔フランス語、英語↔ドイツ語の言語ペア、3つの練習モード（フラッシュカード、文法クイズ、ワードビルダー）を初級難易度で利用でき、50枚のフラッシュカードデッキ、Lagoon Nebula背景、基本的な進捗追跡が含まれます。' },
        { question: '月額課金はどのように機能しますか？', answer: 'すべてのサブスクリプションはApple App Storeで管理されます。アプリでプランを選択し、Face IDまたはApple IDで購入を確認すると、毎月自動的に課金されます。' },
        { question: 'プランの変更方法は？', answer: 'アプリのメンバーシップ画面またはApp Storeのサブスクリプション設定から、いつでもプランを変更できます。アップグレードは即時適用されます。ダウングレードは現在の請求期間の終了時に適用されます。' },
        { question: '無料トライアルはありますか？', answer: 'はい！新規ユーザーは14日間、すべての機能が使えるRoyalレベルのアクセスを無料でお試しいただけます。25以上の言語ペア、12のサウンドスケープ、すべてのビジュアル背景、2倍XPをお楽しみください。トライアル中はいつでもキャンセル可能です。' },
        { question: '利用可能な支払い方法は？', answer: 'LumenLingoはApple App Storeのサブスクリプションを使用しているため、Apple IDに登録された支払い方法（クレジットカード/デビットカード、Apple Pay、App Storeギフトカード残高）がご利用いただけます。' },
        { question: 'いつでもサブスクリプションを解約できますか？', answer: 'はい、ペナルティなくいつでも解約できます。設定→Apple ID→サブスクリプションからLumenLingoを見つけ、解約をタップしてください。現在の請求期間終了まで利用を継続できます。' },
        { question: 'ダウングレードすると進捗は失われますか？', answer: 'いいえ。学習の進捗、連続記録、XP、習熟データはすべてプラン変更に関係なく保持されます。ダウングレードするとプレミアム機能の一部がロックされますが、データはそのまま残ります。' },
        { question: 'ファミリー割引や学生割引はありますか？', answer: 'グループ向けおよび教育向けの料金オプションを検討中です。現在、Freeプランは学生やカジュアルな学習者に十分なアクセスを提供しており、14日間のRoyalトライアルですべての機能を体験できます。' },
        { question: 'オフラインモードはどのように機能しますか？', answer: 'オフラインモード（Proプラン以上）では、フラッシュカードデッキと練習コンテンツをデバイスにダウンロードします。インターネット接続なしで学習でき、再接続時に自動的に同期されます。' },
      ],
    },
  },
  de: {
    comparison: {
      feature: 'Funktion',
      mostPopular: 'Am beliebtesten',
      categories: {
        learning: 'Lernfunktionen',
        immersive: 'Immersives Erlebnis',
        productivity: 'Produktivität',
        analytics: 'Analysen & Einblicke',
        royalExclusive: 'Royal Exklusiv',
      },
      features: {
        languagePairs: 'Sprachpaare',
        practiceModes: 'Übungsmodi',
        dailyLimit: 'Tägliches Übungslimit',
        deckSize: 'Karteikarten-Deckgröße',
        breathingOrbs: 'Atemorben',
        soundscapes: 'Klanglandschaften',
        quantumFlow: 'Quantum Flow Hintergründe',
        nebulaDrift: 'Nebula Drift Hintergründe',
        offlineMode: 'Offline-Modus',
        xpMultiplier: 'XP-Multiplikator',
        advancedAnalytics: 'Erweiterte Analysen',
        dataExport: 'Datenexport',
        shareCards: 'Teilbare Ergebniskarten',
        monthlyReports: 'Monatsberichte',
        personalisedTips: 'Persönliche Tipps',
      },
      values: {
        beginner: '3 (Anfänger)',
        twoLevels: '3 (2 Stufen)',
        allLevels: '3 (Alle Stufen)',
        thirtyMin: '30 Min.',
        unlimited: 'Unbegrenzt',
        fiftyCards: '50 Karten',
        seventyFiveCards: '75 Karten',
        hundredCards: '100 Karten',
        fourScenes: '4 Szenen',
        allSix: 'Alle 6',
        fourPresets: '4 Voreinstellungen',
        allTwelve: 'Alle 12',
      },
    },
    faq: {
      ariaLabel: 'Häufig gestellte Fragen',
      items: [
        { question: 'Ist LumenLingo wirklich kostenlos zum Starten?', answer: 'Absolut. Die kostenlose Stufe bietet 3 Sprachpaare, alle 3 Übungsmodi auf Anfänger-Niveau und 30 Minuten tägliches Üben — keine Kreditkarte erforderlich, kein Ablaufdatum. Lernen Sie in Ihrem eigenen Tempo, so lange Sie möchten.' },
        { question: 'Was ist in der kostenlosen Stufe enthalten?', answer: 'Kostenlose Nutzer erhalten die Sprachpaare Englisch↔Spanisch, Englisch↔Französisch und Englisch↔Deutsch, alle drei Übungsmodi (Karteikarten, Grammatik-Quiz, Wortbaukasten) auf Anfänger-Niveau, 50 Karteikarten-Decks, den Lagoon-Nebula-Hintergrund und grundlegendes Fortschritts-Tracking.' },
        { question: 'Wie funktioniert die monatliche Abrechnung?', answer: 'Alle Abonnements werden über den Apple App Store verwaltet. Wählen Sie Ihre Stufe in der App, bestätigen Sie den Kauf per Face ID oder Apple ID, und die Abrechnung erfolgt automatisch jeden Monat.' },
        { question: 'Wie kann ich meine Stufe ändern?', answer: 'Sie können Ihre Stufe jederzeit im Mitgliedschafts-Bildschirm der App oder in den App Store Abo-Einstellungen ändern. Upgrades gelten sofort. Downgrades gelten am Ende des aktuellen Abrechnungszeitraums.' },
        { question: 'Gibt es eine kostenlose Testphase?', answer: 'Ja! Neue Nutzer können den Royal-Zugang — die höchste Stufe mit allen Funktionen — 14 Tage lang kostenlos testen. Genießen Sie 25+ Sprachpaare, 12 Klanglandschaften, alle visuellen Hintergründe und den 2× XP-Multiplikator. Jederzeit während des Tests kündbar.' },
        { question: 'Welche Zahlungsmethoden werden akzeptiert?', answer: 'LumenLingo nutzt Apple App Store Abonnements, daher funktioniert jede mit Ihrer Apple ID verknüpfte Zahlungsmethode — Kredit-/Debitkarten, Apple Pay und App Store Geschenkkarten-Guthaben.' },
        { question: 'Kann ich mein Abo jederzeit kündigen?', answer: 'Ja, Sie können jederzeit ohne Strafen kündigen. Gehen Sie zu Einstellungen → Apple ID → Abonnements, finden Sie LumenLingo und tippen Sie auf Kündigen. Ihr Zugang bleibt bis zum Ende des Abrechnungszeitraums bestehen.' },
        { question: 'Verliere ich meinen Fortschritt bei einem Downgrade?', answer: 'Niemals. Ihr gesamter Lernfortschritt, Ihre Serien, XP und Beherrschungsdaten bleiben erhalten. Bei einem Downgrade werden bestimmte Premium-Funktionen gesperrt, aber Ihre Daten bleiben intakt.' },
        { question: 'Gibt es Familien- oder Studentenrabatte?', answer: 'Wir prüfen Gruppen- und Bildungspreise. Derzeit bietet die kostenlose Stufe großzügigen Zugang für Studenten, und das 14-tägige Royal-Probeabo gibt jedem die Chance, die vollständige App zu erleben.' },
        { question: 'Wie funktioniert der Offline-Modus?', answer: 'Der Offline-Modus (Pro-Stufe und höher) lädt Ihre aktiven Karteikarten-Decks und Übungsinhalte auf Ihr Gerät. Lernen Sie ohne Internetverbindung — in der U-Bahn, im Flugzeug, überall. Der Fortschritt wird automatisch synchronisiert, wenn Sie sich wieder verbinden.' },
      ],
    },
  },
  pl: {
    comparison: {
      feature: 'Funkcja',
      mostPopular: 'Najpopularniejszy',
      categories: {
        learning: 'Funkcje nauki',
        immersive: 'Doświadczenie immersyjne',
        productivity: 'Produktywność',
        analytics: 'Analizy i statystyki',
        royalExclusive: 'Ekskluzywne Royal',
      },
      features: {
        languagePairs: 'Pary językowe',
        practiceModes: 'Tryby ćwiczeń',
        dailyLimit: 'Dzienny limit ćwiczeń',
        deckSize: 'Rozmiar talii fiszek',
        breathingOrbs: 'Sfery oddechowe',
        soundscapes: 'Krajobrazy dźwiękowe',
        quantumFlow: 'Tła Quantum Flow',
        nebulaDrift: 'Tła Nebula Drift',
        offlineMode: 'Tryb offline',
        xpMultiplier: 'Mnożnik XP',
        advancedAnalytics: 'Zaawansowane analizy',
        dataExport: 'Eksport danych',
        shareCards: 'Karty wyników do udostępniania',
        monthlyReports: 'Raporty miesięczne',
        personalisedTips: 'Spersonalizowane wskazówki',
      },
      values: {
        beginner: '3 (Początkujący)',
        twoLevels: '3 (2 poziomy)',
        allLevels: '3 (Wszystkie poziomy)',
        thirtyMin: '30 min',
        unlimited: 'Bez limitu',
        fiftyCards: '50 kart',
        seventyFiveCards: '75 kart',
        hundredCards: '100 kart',
        fourScenes: '4 sceny',
        allSix: 'Wszystkie 6',
        fourPresets: '4 presety',
        allTwelve: 'Wszystkie 12',
      },
    },
    faq: {
      ariaLabel: 'Często zadawane pytania',
      items: [
        { question: 'Czy LumenLingo jest naprawdę darmowy na start?', answer: 'Oczywiście. Plan Darmowy daje 3 pary językowe, wszystkie 3 tryby ćwiczeń na poziomie Początkującym i 30 minut dziennej praktyki — bez karty kredytowej, bez daty wygaśnięcia. Ucz się we własnym tempie tak długo, jak chcesz.' },
        { question: 'Co zawiera darmowy plan?', answer: 'Darmowi użytkownicy otrzymują pary angielski↔hiszpański, angielski↔francuski i angielski↔niemiecki, wszystkie trzy tryby ćwiczeń (Fiszki, Quizy gramatyczne, Kreator słów) na poziomie Początkującym, talie po 50 fiszek, tło Lagoon Nebula i podstawowe śledzenie postępów.' },
        { question: 'Jak działa miesięczne rozliczanie?', answer: 'Wszystkie subskrypcje są zarządzane przez Apple App Store. Wybierasz plan w aplikacji, potwierdzasz zakup przez Face ID lub Apple ID, a rozliczenie odbywa się automatycznie co miesiąc.' },
        { question: 'Jak mogę zmienić plan?', answer: 'Możesz zmienić plan w dowolnym momencie z ekranu Członkostwo w aplikacji lub ustawień subskrypcji App Store. Ulepszenia obowiązują natychmiast. Obniżenia zaczynają obowiązywać na koniec bieżącego okresu rozliczeniowego.' },
        { question: 'Czy jest darmowy okres próbny?', answer: 'Tak! Nowi użytkownicy mogą przetestować dostęp Royal — najwyższy poziom ze wszystkimi funkcjami — za darmo przez 14 dni. Skorzystaj z 25+ par językowych, 12 krajobrazów dźwiękowych, wszystkich tła wizualnych i mnożnika 2× XP. Anuluj w dowolnym momencie podczas próby bez opłat.' },
        { question: 'Jakie metody płatności są akceptowane?', answer: 'LumenLingo korzysta z subskrypcji Apple App Store, więc działa każda metoda płatności przypisana do Twojego Apple ID — karty kredytowe/debetowe, Apple Pay i saldo kart podarunkowych App Store.' },
        { question: 'Czy mogę anulować subskrypcję w dowolnym momencie?', answer: 'Tak, możesz anulować w dowolnym momencie bez kar. Przejdź do Ustawienia → Apple ID → Subskrypcje, znajdź LumenLingo i dotknij Anuluj. Zachowasz dostęp do swojego planu do końca okresu rozliczeniowego.' },
        { question: 'Czy tracę postępy po obniżeniu planu?', answer: 'Nigdy. Cały Twój postęp w nauce, serie, XP i dane o biegłości są zachowane niezależnie od zmian planu. Przy obniżeniu pewne funkcje premium zostają zablokowane, ale dane pozostają nienaruszone.' },
        { question: 'Czy są zniżki rodzinne lub studenckie?', answer: 'Rozważamy opcje cenowe dla grup i instytucji edukacyjnych. Na razie Plan Darmowy oferuje hojny dostęp dla studentów, a 14-dniowy okres próbny Royal pozwala wszystkim wypróbować pełną aplikację.' },
        { question: 'Jak działa tryb offline?', answer: 'Tryb offline (plan Pro i wyższe) pobiera aktywne talie fiszek i treści ćwiczeniowe na urządzenie. Ucz się bez połączenia z internetem — w metrze, w samolocie, gdziekolwiek. Postępy synchronizują się automatycznie po ponownym połączeniu.' },
      ],
    },
  },
  ar: {
    comparison: {
      feature: 'الميزة',
      mostPopular: 'الأكثر شعبية',
      categories: {
        learning: 'ميزات التعلم',
        immersive: 'تجربة غامرة',
        productivity: 'الإنتاجية',
        analytics: 'التحليلات والرؤى',
        royalExclusive: 'حصري Royal',
      },
      features: {
        languagePairs: 'أزواج اللغات',
        practiceModes: 'أوضاع التمرين',
        dailyLimit: 'الحد اليومي للتمرين',
        deckSize: 'حجم مجموعة البطاقات',
        breathingOrbs: 'كرات التنفس',
        soundscapes: 'مشاهد صوتية',
        quantumFlow: 'خلفيات Quantum Flow',
        nebulaDrift: 'خلفيات Nebula Drift',
        offlineMode: 'وضع عدم الاتصال',
        xpMultiplier: 'مضاعف XP',
        advancedAnalytics: 'تحليلات متقدمة',
        dataExport: 'تصدير البيانات',
        shareCards: 'بطاقات نتائج قابلة للمشاركة',
        monthlyReports: 'تقارير شهرية',
        personalisedTips: 'نصائح مخصصة',
      },
      values: {
        beginner: '٣ (مبتدئ)',
        twoLevels: '٣ (مستويان)',
        allLevels: '٣ (جميع المستويات)',
        thirtyMin: '٣٠ دقيقة',
        unlimited: 'غير محدود',
        fiftyCards: '٥٠ بطاقة',
        seventyFiveCards: '٧٥ بطاقة',
        hundredCards: '١٠٠ بطاقة',
        fourScenes: '٤ مشاهد',
        allSix: 'جميع الـ ٦',
        fourPresets: '٤ إعدادات',
        allTwelve: 'جميع الـ ١٢',
      },
    },
    faq: {
      ariaLabel: 'الأسئلة الشائعة',
      items: [
        { question: 'هل LumenLingo مجاني فعلاً للبدء؟', answer: 'بالتأكيد. المستوى المجاني يمنحك ٣ أزواج لغات، جميع أوضاع التمرين الثلاثة بصعوبة المبتدئ، و٣٠ دقيقة من التمرين اليومي — بدون بطاقة ائتمان، بدون انتهاء صلاحية. تعلّم بالسرعة التي تناسبك.' },
        { question: 'ماذا يتضمن المستوى المجاني؟', answer: 'يحصل المستخدمون المجانيون على أزواج اللغات إنجليزي↔إسباني وإنجليزي↔فرنسي وإنجليزي↔ألماني، وجميع أوضاع التمرين الثلاثة (بطاقات تعليمية، اختبارات قواعد، بناء الكلمات) بصعوبة المبتدئ، ومجموعات من ٥٠ بطاقة، وخلفية Lagoon Nebula، وتتبع التقدم الأساسي.' },
        { question: 'كيف تعمل الفوترة الشهرية؟', answer: 'تُدار جميع الاشتراكات عبر متجر Apple App Store. اختر مستواك في التطبيق، وأكد الشراء عبر Face ID أو Apple ID، وتتم الفوترة تلقائياً كل شهر.' },
        { question: 'كيف أقوم بترقية أو تخفيض مستواي؟', answer: 'يمكنك تغيير مستواك في أي وقت من شاشة العضوية في التطبيق أو من إعدادات اشتراكات App Store. الترقيات تسري فوراً. التخفيضات تسري في نهاية فترة الفوترة الحالية.' },
        { question: 'هل هناك فترة تجريبية مجانية؟', answer: 'نعم! يمكن للمستخدمين الجدد تجربة الوصول Royal — أعلى مستوى — مجاناً لمدة ١٤ يوماً. استمتع بأكثر من ٢٥ زوج لغات، و١٢ مشهداً صوتياً، وجميع الخلفيات، ومضاعف XP بمقدار ٢×. ألغِ في أي وقت خلال الفترة التجريبية بدون رسوم.' },
        { question: 'ما طرق الدفع المقبولة؟', answer: 'يستخدم LumenLingo اشتراكات Apple App Store، لذا تعمل أي طريقة دفع مرتبطة بـ Apple ID — بطاقات الائتمان/الخصم، Apple Pay، ورصيد بطاقات الهدايا.' },
        { question: 'هل يمكنني إلغاء اشتراكي في أي وقت؟', answer: 'نعم، يمكنك الإلغاء في أي وقت بدون غرامات. اذهب إلى الإعدادات ← Apple ID ← الاشتراكات، وابحث عن LumenLingo وانقر إلغاء. ستحتفظ بالوصول حتى نهاية فترة الفوترة.' },
        { question: 'هل أفقد تقدمي إذا خفّضت مستواي؟', answer: 'أبداً. يتم الحفاظ على جميع تقدمك وسلاسلك ونقاط XP وبيانات الإتقان بغض النظر عن تغييرات المستوى. عند التخفيض تُقفل بعض الميزات المتقدمة، لكن بياناتك تبقى سليمة.' },
        { question: 'هل هناك خصومات عائلية أو للطلاب؟', answer: 'نحن نستكشف خيارات أسعار جماعية وتعليمية. حالياً، المستوى المجاني يوفر وصولاً سخياً للطلاب، والفترة التجريبية Royal لمدة ١٤ يوماً تتيح للجميع تجربة التطبيق الكامل.' },
        { question: 'كيف يعمل وضع عدم الاتصال؟', answer: 'وضع عدم الاتصال (مستوى Pro وأعلى) يقوم بتحميل مجموعات البطاقات والمحتوى التمريني على جهازك. ادرس بدون اتصال بالإنترنت — في المترو، في الطائرة، في أي مكان. يتم المزامنة تلقائياً عند إعادة الاتصال.' },
      ],
    },
  },
  zh: {
    comparison: {
      feature: '功能',
      mostPopular: '最受欢迎',
      categories: {
        learning: '学习功能',
        immersive: '沉浸式体验',
        productivity: '生产力',
        analytics: '分析与洞察',
        royalExclusive: 'Royal 专属',
      },
      features: {
        languagePairs: '语言对',
        practiceModes: '练习模式',
        dailyLimit: '每日练习限制',
        deckSize: '闪卡组大小',
        breathingOrbs: '呼吸光球',
        soundscapes: '声景',
        quantumFlow: 'Quantum Flow 背景',
        nebulaDrift: 'Nebula Drift 背景',
        offlineMode: '离线模式',
        xpMultiplier: 'XP 倍率',
        advancedAnalytics: '高级分析',
        dataExport: '数据导出',
        shareCards: '可分享结果卡',
        monthlyReports: '月度报告',
        personalisedTips: '个性化建议',
      },
      values: {
        beginner: '3（初级）',
        twoLevels: '3（2个级别）',
        allLevels: '3（所有级别）',
        thirtyMin: '30 分钟',
        unlimited: '无限',
        fiftyCards: '50 张',
        seventyFiveCards: '75 张',
        hundredCards: '100 张',
        fourScenes: '4 个场景',
        allSix: '全部 6 个',
        fourPresets: '4 个预设',
        allTwelve: '全部 12 个',
      },
    },
    faq: {
      ariaLabel: '常见问题',
      items: [
        { question: 'LumenLingo 真的可以免费开始吗？', answer: '当然。免费计划提供 3 个语言对、3 种初级难度练习模式和每天 30 分钟的练习——无需信用卡，无过期时间。按自己的节奏学习，想学多久就学多久。' },
        { question: '免费计划包含什么？', answer: '免费用户可获得英语↔西班牙语、英语↔法语和英语↔德语语言对，三种练习模式（闪卡、语法测验、单词构建器）的初级难度，50 张闪卡组，Lagoon Nebula 背景和基本进度跟踪。' },
        { question: '月度计费如何运作？', answer: '所有订阅均通过 Apple App Store 管理。在应用中选择计划，通过 Face ID 或 Apple ID 确认购买，每月自动计费。' },
        { question: '如何升级或降级计划？', answer: '您可以随时从应用的会员屏幕或 App Store 订阅设置中更改计划。升级立即生效。降级在当前计费周期结束时生效。' },
        { question: '有免费试用吗？', answer: '有！新用户可以免费试用 14 天 Royal 级别——最高等级，所有功能解锁。体验 25+ 语言对、12 个声景、所有视觉背景和 2 倍 XP。试用期间随时取消，不收费。' },
        { question: '接受哪些支付方式？', answer: 'LumenLingo 使用 Apple App Store 订阅，因此与您 Apple ID 关联的任何支付方式均可使用——信用卡/借记卡、Apple Pay 和 App Store 礼品卡余额。' },
        { question: '可以随时取消订阅吗？', answer: '可以，随时取消，无任何罚款。前往设置 → Apple ID → 订阅，找到 LumenLingo 并点击取消。您将保留当前计划的访问权限直到计费周期结束。' },
        { question: '降级后会丢失进度吗？', answer: '不会。您的所有学习进度、连续记录、XP 和掌握数据都会保留。降级后某些高级功能会被锁定，但数据完好无损。随时升级即可继续。' },
        { question: '有家庭或学生折扣吗？', answer: '我们正在探索团体和教育定价方案。目前，免费计划为学生提供充裕的访问权限，14 天 Royal 试用让每个人都能体验完整应用。' },
        { question: '离线模式如何工作？', answer: '离线模式（Pro 计划及以上）将闪卡组和练习内容下载到设备。无需网络即可学习——地铁上、飞机上、任何地方。重新连接后自动同步进度。' },
      ],
    },
  },
  uk: {
    comparison: {
      feature: 'Функція',
      mostPopular: 'Найпопулярніший',
      categories: {
        learning: 'Функції навчання',
        immersive: 'Занурювальний досвід',
        productivity: 'Продуктивність',
        analytics: 'Аналітика та огляд',
        royalExclusive: 'Ексклюзив Royal',
      },
      features: {
        languagePairs: 'Мовні пари',
        practiceModes: 'Режими практики',
        dailyLimit: 'Денний ліміт практики',
        deckSize: 'Розмір колоди карток',
        breathingOrbs: 'Дихальні сфери',
        soundscapes: 'Звукові ландшафти',
        quantumFlow: 'Фони Quantum Flow',
        nebulaDrift: 'Фони Nebula Drift',
        offlineMode: 'Офлайн-режим',
        xpMultiplier: 'Множник XP',
        advancedAnalytics: 'Розширена аналітика',
        dataExport: 'Експорт даних',
        shareCards: 'Картки результатів для поширення',
        monthlyReports: 'Щомісячні звіти',
        personalisedTips: 'Персоналізовані поради',
      },
      values: {
        beginner: '3 (Початковий)',
        twoLevels: '3 (2 рівні)',
        allLevels: '3 (Усі рівні)',
        thirtyMin: '30 хв',
        unlimited: 'Без обмежень',
        fiftyCards: '50 карток',
        seventyFiveCards: '75 карток',
        hundredCards: '100 карток',
        fourScenes: '4 сцени',
        allSix: 'Усі 6',
        fourPresets: '4 пресети',
        allTwelve: 'Усі 12',
      },
    },
    faq: {
      ariaLabel: 'Часті запитання',
      items: [
        { question: 'Чи справді LumenLingo безкоштовний для початку?', answer: 'Звісно. Безкоштовний план дає 3 мовні пари, усі 3 режими практики на рівні Початковий та 30 хвилин щоденної практики — без кредитної картки, без терміну дії. Навчайтесь у своєму темпі стільки, скільки хочете.' },
        { question: 'Що входить у безкоштовний план?', answer: 'Безкоштовні користувачі отримують пари англійська↔іспанська, англійська↔французька та англійська↔німецька, всі три режими практики (Картки, Граматичні тести, Конструктор слів) на рівні Початковий, колоди по 50 карток, фон Lagoon Nebula та базове відстеження прогресу.' },
        { question: 'Як працює щомісячна оплата?', answer: 'Усі підписки керуються через Apple App Store. Оберіть план у додатку, підтвердіть покупку через Face ID або Apple ID, і оплата стягується автоматично щомісяця.' },
        { question: 'Як змінити план?', answer: 'Ви можете змінити план будь-коли з екрану Членство в додатку або налаштувань підписки App Store. Покращення діють негайно. Зниження діють з кінця поточного платіжного періоду.' },
        { question: 'Чи є безкоштовний пробний період?', answer: 'Так! Нові користувачі можуть спробувати доступ Royal — найвищий рівень з усіма функціями — безкоштовно протягом 14 днів. Насолоджуйтесь 25+ мовними парами, 12 звуковими ландшафтами, усіма візуальними фонами та множником 2× XP. Скасуйте будь-коли під час пробного періоду без оплати.' },
        { question: 'Які способи оплати приймаються?', answer: "LumenLingo використовує підписки Apple App Store, тому працює будь-який спосіб оплати, прив'язаний до вашого Apple ID — кредитні/дебетні картки, Apple Pay та баланс подарункових карток App Store." },
        { question: 'Чи можу я скасувати підписку будь-коли?', answer: 'Так, ви можете скасувати будь-коли без штрафів. Перейдіть до Налаштування → Apple ID → Підписки, знайдіть LumenLingo та натисніть Скасувати. Ваш доступ збережеться до кінця платіжного періоду.' },
        { question: 'Чи втрачу я прогрес при зниженні плану?', answer: 'Ніколи. Увесь ваш прогрес навчання, серії, XP та дані майстерності зберігаються незалежно від змін плану. При зниженні деякі преміум-функції блокуються, але ваші дані залишаються цілими.' },
        { question: 'Чи є сімейні або студентські знижки?', answer: 'Ми вивчаємо варіанти групових та освітніх цін. Наразі безкоштовний план пропонує щедрий доступ для студентів, а 14-денний пробний період Royal дає кожному можливість випробувати повний додаток.' },
        { question: 'Як працює офлайн-режим?', answer: "Офлайн-режим (план Pro і вище) завантажує активні колоди карток та навчальний контент на ваш пристрій. Навчайтесь без інтернету — у метро, в літаку, де завгодно. Прогрес синхронізується автоматично при повторному з'єднанні." },
      ],
    },
  },
};

for (const locale of LOCALES) {
  const filePath = join(MESSAGES, `${locale}.json`);
  const data = JSON.parse(readFileSync(filePath, 'utf8'));

  if (!data.Pricing) data.Pricing = {};

  // Merge comparison keys (deep merge into existing comparison object)
  const existing = data.Pricing.comparison || {};
  data.Pricing.comparison = { ...existing, ...keys[locale].comparison };

  // Merge faq keys (deep merge into existing faq object)
  const existingFaq = data.Pricing.faq || {};
  data.Pricing.faq = { ...existingFaq, ...keys[locale].faq };

  writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`✓ ${locale}.json — Pricing comparison + FAQ keys added`);
}
console.log('Done — all 9 locale files updated.');
