#!/usr/bin/env python3
import json, os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
f = os.path.join(base, 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json')
data = json.load(open(f, encoding='utf-8'))
print(f"Before: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")

new_cats = [
  {
    "id": "gp_pers_pron",
    "key": "personal_pronouns",
    "name": "Zaimki osobowe (Personalpronomen)",
    "items": [
      {"id": "gp_prp1", "question": "_____ jestem z Niemiec.", "translation": "Ich bin aus Deutschland.", "options": ["Ja", "Ty", "On", "My"], "correct": "Ja", "explanation": "'Ja' (ich) ist das Personalpronomen der 1. Person Singular. Im Polnischen wird das Subjektpronomen oft weggelassen, weil die Verbendung die Person schon zeigt: 'Jestem z Niemiec' reicht aus. Aber 'Ja jestem z Niemiec' betont das Subjekt: 'ICH bin aus Deutschland'. Im Deutschen ist das Pronomen obligatorisch, im Polnischen ist es optional und dient der Betonung."},
      {"id": "gp_prp2", "question": "Czy _____ m\u00f3wisz po polsku?", "translation": "Sprichst du Polnisch?", "options": ["ty", "ja", "on", "oni"], "correct": "ty", "explanation": "'Ty' (du) ist das informelle Anredepronomen der 2. Person Singular. Im Polnischen wird 'ty' f\u00fcr Familie, Freunde und Gleichaltrige verwendet, \u00e4hnlich wie im Deutschen 'du'. Beachten Sie: in h\u00f6flicher Anrede verwendet man 'Pan/Pani' (Herr/Frau) + 3. Person Singular statt 'ty'. Dies unterscheidet sich grundlegend vom deutschen 'Sie', das die 3. Person Plural verwendet."},
      {"id": "gp_prp3", "question": "_____ pracuje w szpitalu.", "translation": "Er arbeitet im Krankenhaus.", "options": ["On", "Ona", "Ono", "Oni"], "correct": "On", "explanation": "'On' (er) ist das m\u00e4nnliche Personalpronomen der 3. Person Singular. Im Polnischen gibt es drei Geschlechter in der 3. Person Singular: 'on' (er, m\u00e4nnlich), 'ona' (sie, weiblich), 'ono' (es, s\u00e4chlich). Im Deutschen existiert dieselbe Dreiteilung (er/sie/es). Das Pronomen 'on' bleibt auch im h\u00f6flichen Kontext gleich, w\u00e4hrend man \u00fcber eine anwesende Person h\u00f6flich 'Pan' sagt."},
      {"id": "gp_prp4", "question": "Widzisz _____? Stoi przy oknie.", "translation": "Siehst du sie? Sie steht am Fenster.", "options": ["j\u0105", "jej", "ona", "ni\u0105"], "correct": "j\u0105", "explanation": "'J\u0105' ist der Akkusativ von 'ona' (sie). Im Polnischen haben Personalpronomen verschiedene Formen je nach Kasus: 'ona' (Nom.), 'j\u0105' (Akk.), 'jej' (Gen./Dat.), 'ni\u0105' (Instr.), 'niej' (Lok./nach Pr\u00e4positionen). Die Kurzform 'j\u0105' steht ohne Pr\u00e4position, die Langform 'ni\u0105' nach Pr\u00e4positionen: 'widz\u0119 j\u0105' vs. 'z ni\u0105'. Im Deutschen bleibt 'sie' in allen F\u00e4llen gleich."},
      {"id": "gp_prp5", "question": "Daj _____ t\u0119 ksi\u0105\u017ck\u0119, prosz\u0119.", "translation": "Gib mir bitte dieses Buch.", "options": ["mi", "mnie", "ja", "mn\u0105"], "correct": "mi", "explanation": "'Mi' ist die unbetonte Dativform von 'ja' (ich). Im Polnischen gibt es zwei Dativformen: 'mi' (unbetont/kurz) und 'mnie' (betont/lang). 'Daj mi' (gib mir) ist neutral, 'daj mnie' betont 'MIR'. Im Deutschen gibt es diesen Unterschied nicht \u2013 'mir' ist immer gleich. Die unbetonten Kurzformen: 'mi' (mir), 'ci' (dir), 'mu' (ihm). Sie stehen nie am Satzanfang und nicht nach Pr\u00e4positionen."},
      {"id": "gp_prp6", "question": "Id\u0119 do _____ na obiad.", "translation": "Ich gehe zum Mittagessen zu ihnen.", "options": ["nich", "ich", "im", "nimi"], "correct": "nich", "explanation": "'Do nich' (zu ihnen) \u2013 nach Pr\u00e4positionen verwenden Pronomen der 3. Person die n-Formen: 'niego' (seiner/ihm), 'niej' (ihrer/ihr), 'nich' (ihrer/ihnen). Ohne Pr\u00e4position: 'ich' (ihrer/sie), 'im' (ihnen). Dieser Wechsel existiert im Deutschen nicht. Merkhilfe: Nach jeder Pr\u00e4position (do, z, na, w, przy, od...) wird ein 'n-' vorangestellt. 'Widz\u0119 ich' vs. 'id\u0119 do nich'."},
      {"id": "gp_prp7", "question": "Chc\u0119 _____ o co\u015b zapyta\u0107.", "translation": "Ich m\u00f6chte dich etwas fragen.", "options": ["ci\u0119", "ciebie", "tobie", "ty"], "correct": "ci\u0119", "explanation": "'Ci\u0119' ist die unbetonte Akkusativform von 'ty' (du). Im Polnischen hat 'ty' mehrere Kasusformen: 'ty' (Nom.), 'ci\u0119/ciebie' (Akk.), 'ci/tobie' (Dat.), 'tob\u0105' (Instr.), 'tobie' (Lok.). Die Kurzform 'ci\u0119' ist in der Alltagssprache Standard: 'Kocham ci\u0119' (Ich liebe dich). Die Langform 'ciebie' betont: 'Ciebie kocham!' (DICH liebe ich!). Im Deutschen hat 'du' nur: 'du/dich/dir'."},
      {"id": "gp_prp8", "question": "Rozmawiali\u015bmy o _____ wczoraj.", "translation": "Wir haben gestern \u00fcber ihn gesprochen.", "options": ["nim", "go", "jemu", "on"], "correct": "nim", "explanation": "'O nim' (\u00fcber ihn) \u2013 'nim' ist die Lokativform/Pr\u00e4positionalform von 'on' (er). Nach Pr\u00e4positionen: 'o nim' (\u00fcber ihn), 'z nim' (mit ihm), 'przy nim' (bei ihm), 'w nim' (in ihm). Ohne Pr\u00e4position stehen andere Formen: 'go' (Akk./Gen. kurz), 'mu' (Dat. kurz), 'jego/jemu' (betonte Formen). Im Deutschen bleibt 'ihm/ihn' gleich, unabh\u00e4ngig von der Pr\u00e4position."},
      {"id": "gp_prp9", "question": "To jest prezent dla _____.", "translation": "Das ist ein Geschenk f\u00fcr dich.", "options": ["ciebie", "ci\u0119", "ci", "ty"], "correct": "ciebie", "explanation": "'Dla ciebie' (f\u00fcr dich) \u2013 nach Pr\u00e4positionen steht die betonte (lange) Form: 'ciebie', nicht 'ci\u0119'. Regel: Kurzformen (ci\u0119, ci, go, mu, mi) stehen NUR ohne Pr\u00e4position. Nach Pr\u00e4positionen (dla, do, od, z, na...) stehen die vollen Formen: 'dla mnie' (f\u00fcr mich), 'dla ciebie' (f\u00fcr dich), 'dla niego' (f\u00fcr ihn). Diese Regel ist absolut und hat keine Ausnahmen im Polnischen."},
      {"id": "gp_prp10", "question": "_____ lubimy polsk\u0105 kuchni\u0119.", "translation": "Wir m\u00f6gen die polnische K\u00fcche.", "options": ["My", "Wy", "Oni", "Ja"], "correct": "My", "explanation": "'My' (wir) ist das Personalpronomen der 1. Person Plural. Wie bei 'ja' wird 'my' im Polnischen oft weggelassen, da die Verbendung '-my' die Person schon anzeigt: 'Lubimy polsk\u0105 kuchni\u0119' (Wir m\u00f6gen polnische K\u00fcche). 'My lubimy' betont 'WIR'. Im Deutschen muss 'wir' immer stehen. Die Kasusformen von 'my': 'nas' (Gen./Akk.), 'nam' (Dat.), 'nami' (Instr.), 'nas' (Lok.)."},
      {"id": "gp_prp11", "question": "Czy mogliby\u015bcie pomoc _____?", "translation": "K\u00f6nntet ihr uns helfen?", "options": ["nam", "nami", "nas", "my"], "correct": "nam", "explanation": "'Nam' (uns, Dativ) \u2013 'pom\u00f3c' (helfen) verlangt den Dativ, genau wie im Deutschen 'jemandem helfen'. Dativformen der Pronomen: 'mi/mnie' (mir), 'ci/tobie' (dir), 'mu/jemu' (ihm), 'jej' (ihr), 'nam' (uns), 'wam' (euch), 'im' (ihnen). Im Polnischen ist die Kasusrektion vieler Verben dieselbe wie im Deutschen, was f\u00fcr deutschsprachige Lernende ein Vorteil ist."},
      {"id": "gp_prp12", "question": "Powiem _____ prawd\u0119.", "translation": "Ich werde euch die Wahrheit sagen.", "options": ["wam", "was", "wy", "wami"], "correct": "wam", "explanation": "'Wam' (euch, Dativ) \u2013 'powiedzie\u0107 komu\u015b' (jemandem sagen) verlangt den Dativ. Die Deklination von 'wy' (ihr): 'wy' (Nom.), 'was' (Gen./Akk.), 'wam' (Dat.), 'wami' (Instr.), 'was' (Lok.). Beachten Sie: die h\u00f6fliche 'Sie'-Form verwendet im Polnischen 'Pan/Pani/Pa\u0144stwo' + 3. Person, nicht 'wy' wie im Deutschen mit 'Sie' + 3. Person Plural."},
      {"id": "gp_prp13", "question": "Zadzwoni\u0119 do _____ wieczorem.", "translation": "Ich rufe dich heute Abend an.", "options": ["ciebie", "ci\u0119", "ty", "ci"], "correct": "ciebie", "explanation": "'Do ciebie' (zu dir/dich) \u2013 nach der Pr\u00e4position 'do' steht die volle Genitivform 'ciebie'. 'Zadzwoni\u0107 do kogo\u015b' (jemanden anrufen) verwendet 'do + Genitiv'. Im Deutschen: 'dich anrufen' (Akkusativ, ohne Pr\u00e4position). Dieser Strukturunterschied ist typisch: polnische Verben verwenden oft Pr\u00e4positionen, wo das Deutsche direkte Objekte hat, und umgekehrt. Das Verb muss mit seiner Rektion gelernt werden."},
      {"id": "gp_prp14", "question": "Mi\u0119dzy _____ a tob\u0105 m\u00f3wi\u0105c...", "translation": "Unter uns gesagt...", "options": ["mn\u0105", "mnie", "mi", "ja"], "correct": "mn\u0105", "explanation": "'Mi\u0119dzy mn\u0105 a tob\u0105' (zwischen mir und dir) \u2013 'mi\u0119dzy' (zwischen) verlangt den Instrumental: 'mn\u0105' (mir, Instr.), 'tob\u0105' (dir, Instr.). Die Instrumentalformen: 'mn\u0105' (mir), 'tob\u0105' (dir), 'nim' (ihm), 'ni\u0105' (ihr), 'nami' (uns), 'wami' (euch), 'nimi' (ihnen). Im Deutschen: 'zwischen mir und dir' (Dativ). Diese idiomatische Wendung ist im Gespr\u00e4ch sehr n\u00fctzlich."},
      {"id": "gp_prp15", "question": "Nie k\u0142\u00f3\u0107 si\u0119 z _____!", "translation": "Streit dich nicht mit ihr!", "options": ["ni\u0105", "j\u0105", "jej", "ona"], "correct": "ni\u0105", "explanation": "'Z ni\u0105' (mit ihr) \u2013 nach der Pr\u00e4position 'z' steht die Instrumentalform mit n-Anlaut: 'ni\u0105'. Vergleichen Sie: 'Widz\u0119 j\u0105' (Ich sehe sie \u2013 Akk. ohne n-) vs. 'Id\u0119 z ni\u0105' (Ich gehe mit ihr \u2013 Instr. mit n-). Diese Regel gilt f\u00fcr alle Pronomen der 3. Person: on \u2192 nim/niego/niemu, ona \u2192 ni\u0105/niej, oni/one \u2192 nimi/nich. Im Deutschen gibt es keine solche Laut\u00e4nderung bei Pronomen."}
    ]
  },
  {
    "id": "gp_dem_pron",
    "key": "demonstrative_pronouns",
    "name": "Zaimki wskazuj\u0105ce (Demonstrativpronomen)",
    "items": [
      {"id": "gp_dem1", "question": "_____ ksi\u0105\u017cka jest bardzo ciekawa.", "translation": "Dieses Buch ist sehr interessant.", "options": ["Ta", "Ten", "To", "Te"], "correct": "Ta", "explanation": "'Ta' (diese) ist die weibliche Form des Demonstrativpronomens. Die polnischen Demonstrativpronomen richten sich nach dem Genus: 'ten' (m\u00e4nnlich), 'ta' (weiblich), 'to' (s\u00e4chlich). 'Ksi\u0105\u017cka' ist weiblich, daher 'ta ksi\u0105\u017cka'. Im Deutschen: 'dieses Buch' (\u2013 s\u00e4chlich, weil 'Buch' Neutrum ist). Im Polnischen ist 'ksi\u0105\u017cka' aber Femininum! Genus\u00fcbereinstimmung ist oft unterschiedlich."},
      {"id": "gp_dem2", "question": "_____ dom jest bardzo du\u017cy.", "translation": "Dieses Haus ist sehr gro\u00df.", "options": ["Ten", "Ta", "To", "Te"], "correct": "Ten", "explanation": "'Ten dom' (dieses Haus) \u2013 'ten' ist die m\u00e4nnliche Form. 'Dom' (Haus) ist im Polnischen maskulin, im Deutschen ist 'Haus' Neutrum (das Haus). Solche Genusunterschiede zwischen Polnisch und Deutsch sind h\u00e4ufig und eine wichtige Fehlerquelle. Weitere Beispiele: 'ten st\u00f3\u0142' (dieser Tisch \u2013 PL: mask., DE: mask.), 'ta lampa' (diese Lampe \u2013 PL: fem., DE: fem.), 'to dziecko' (dieses Kind \u2013 PL: neutr., DE: neutr.)."},
      {"id": "gp_dem3", "question": "Chc\u0119 kupi\u0107 _____ samoch\u00f3d.", "translation": "Ich m\u00f6chte dieses Auto kaufen.", "options": ["ten", "t\u0105", "to", "t\u0119"], "correct": "ten", "explanation": "'Ten samoch\u00f3d' (dieses Auto) \u2013 'samoch\u00f3d' ist maskulin unbelebt, daher steht 'ten' im Akkusativ (= Nominativ bei unbelebten Maskulina). W\u00e4re es belebt ('ten psa' \u2192 'tego psa'), w\u00fcrde der Akkusativ die Genitivform annehmen. Diese Unterscheidung belebt/unbelebt gibt es im Deutschen nicht und ist eine wichtige Besonderheit des Polnischen: 'Widz\u0119 ten dom' vs. 'Widz\u0119 tego ch\u0142opca'."},
      {"id": "gp_dem4", "question": "Podoba mi si\u0119 _____ sukienka.", "translation": "Mir gef\u00e4llt dieses Kleid.", "options": ["ta", "ten", "to", "te"], "correct": "ta", "explanation": "'Ta sukienka' (dieses Kleid) \u2013 'sukienka' (Kleid) ist im Polnischen feminin, w\u00e4hrend 'Kleid' im Deutschen Neutrum (das Kleid) ist. Daher 'ta sukienka' statt 'to sukienka'. Der Satz zeigt auch die Konstruktion 'podoba\u0107 si\u0119 komu\u015b' (jemandem gefallen \u2013 Dativ): 'Podoba mi si\u0119' = Es gef\u00e4llt mir. Die Wortstellung ist im Polnischen flexibler als im Deutschen."},
      {"id": "gp_dem5", "question": "_____ dzieci s\u0105 bardzo g\u0142o\u015bne.", "translation": "Diese Kinder sind sehr laut.", "options": ["Te", "Ta", "Ci", "Tamte"], "correct": "Te", "explanation": "'Te dzieci' (diese Kinder) \u2013 'te' ist die Pluralform f\u00fcr nicht-m\u00e4nnlich-personale Substantive. Im Polnischen gibt es zwei Pluralformen der Demonstrativpronomen: 'ci' (m\u00e4nnlich-personal: diese M\u00e4nner/Leute) und 'te' (alles andere: diese Kinder/Frauen/Dinge/Tiere). Im Deutschen gibt es nur 'diese' f\u00fcr alle Plurale. Diese Unterscheidung ist einzigartig polnisch und f\u00fcr Deutschsprachige neu."},
      {"id": "gp_dem6", "question": "Znam _____ ludzi od lat.", "translation": "Ich kenne diese Leute seit Jahren.", "options": ["tych", "tymi", "ci", "te"], "correct": "tych", "explanation": "'Tych ludzi' (diese Leute/Menschen \u2013 Akkusativ/Genitiv) \u2013 'zna\u0107' (kennen) verlangt den Akkusativ. Bei belebten maskulinen Pluralformen ist der Akkusativ = Genitiv: 'tych ludzi'. Die Deklination im Plural: 'ci/te' (Nom.), 'tych' (Gen./Akk. belebt), 'tym' (Dat.), 'tymi' (Instr.), 'tych' (Lok.). Im Deutschen: 'diese Leute' (Akkusativ = Nominativ). Die polnische Kasusvielfalt bei Pronomen ist deutlich reicher."},
      {"id": "gp_dem7", "question": "Wr\u00f3ci\u0142em z _____ konferencji wczoraj.", "translation": "Ich bin gestern von dieser Konferenz zur\u00fcckgekommen.", "options": ["tej", "ta", "t\u0105", "t\u0119"], "correct": "tej", "explanation": "'Z tej konferencji' (von dieser Konferenz) \u2013 'tej' ist der Genitiv/Dativ/Lokativ feminin von 'ta'. Nach 'z' (von/aus) steht der Genitiv: 'z tej konferencji'. Die weibliche Deklination von 'ta': 'ta' (Nom.), 'tej' (Gen.), 't\u0119' (Akk.), 'tej' (Dat.), 't\u0105' (Instr.), 'tej' (Lok.). Im Deutschen: 'von dieser Konferenz'. Die Mehrdeutigkeit von 'tej' (Gen. = Dat. = Lok.) vereinfacht das Lernen etwas."},
      {"id": "gp_dem8", "question": "W _____ mie\u015bcie jest du\u017co park\u00f3w.", "translation": "In dieser Stadt gibt es viele Parks.", "options": ["tym", "ten", "tego", "t\u0105"], "correct": "tym", "explanation": "'W tym mie\u015bcie' (in dieser Stadt) \u2013 'tym' ist der Lokativ maskulin/neutrum von 'ten/to'. Nach 'w' steht der Lokativ: 'w tym mie\u015bcie'. 'Miasto' (Stadt) ist im Polnischen Neutrum, im Deutschen Femininum (die Stadt). Die Deklination von 'ten' (mask.): 'ten' (Nom.), 'tego' (Gen./Akk. belebt), 'temu' (Dat.), 'tym' (Instr./Lok.). 'Tym' dient sowohl als Instrumental als auch Lokativ."},
      {"id": "gp_dem9", "question": "Tamten budynek jest starszy od _____.", "translation": "Jenes Geb\u00e4ude ist \u00e4lter als dieses.", "options": ["tego", "ten", "tym", "te"], "correct": "tego", "explanation": "'Tamten' (jener/jenes) vs. 'ten' (dieser/dieses) \u2013 das Polnische unterscheidet wie das Deutsche 'dieser/jener': 'ten' (nah) vs. 'tamten' (fern). 'Od tego' (als dieses \u2013 Genitiv nach 'od' im Vergleich). Im Deutschen ist 'jener' veraltet und wird durch 'der dort/das dort' ersetzt. Im Polnischen ist 'tamten/tamta/tamto' im Alltag hingegen noch lebendig und gebr\u00e4uchlich."},
      {"id": "gp_dem10", "question": "Prosz\u0119 mi da\u0107 _____ jab\u0142ko.", "translation": "Geben Sie mir bitte diesen Apfel.", "options": ["to", "ten", "ta", "te"], "correct": "to", "explanation": "'To jab\u0142ko' (dieser Apfel/dieses Apfel) \u2013 'jab\u0142ko' (Apfel) ist im Polnischen Neutrum, daher 'to'. Im Deutschen ist 'Apfel' maskulin (der Apfel), daher 'diesen Apfel'. Beachten Sie auch die h\u00f6fliche Form: 'Prosz\u0119 mi da\u0107' (Geben Sie mir bitte) \u2013 'prosz\u0119 + Infinitiv' ist die polnische H\u00f6flichkeitsform f\u00fcr Aufforderungen, die oft anstelle des Imperativs verwendet wird."},
      {"id": "gp_dem11", "question": "Mus\u0119 porozmawia\u0107 z _____ panem.", "translation": "Ich muss mit diesem Herrn sprechen.", "options": ["tym", "ten", "tego", "temu"], "correct": "tym", "explanation": "'Z tym panem' (mit diesem Herrn) \u2013 'z' verlangt den Instrumental. 'Tym' ist die Instrumentalform von 'ten'. Die Instrumentaldeklination: 'ten \u2192 tym', 'ta \u2192 t\u0105', 'to \u2192 tym', 'ci \u2192 tymi', 'te \u2192 tymi'. Im Deutschen: 'mit diesem Herrn' (Dativ). Beachten Sie auch: 'pan' (Herr) im Instrumental = 'panem', eine regelm\u00e4\u00dfige maskuline Endung."},
      {"id": "gp_dem12", "question": "Nie znam _____ piosenki.", "translation": "Ich kenne dieses Lied nicht.", "options": ["tej", "ta", "t\u0105", "to"], "correct": "tej", "explanation": "'Tej piosenki' (dieses Liedes) \u2013 Genitiv femininum bei Verneinung. Im Polnischen steht nach verneinter transitiver Verben der Genitiv statt des Akkusativs: 'Znam t\u0119 piosenk\u0119' (Akk.) aber 'Nie znam tej piosenki' (Gen.). Diese Genitivregel bei Verneinung ist eine der wichtigsten Besonderheiten des Polnischen, die es im Deutschen nicht gibt. Sie gilt f\u00fcr alle transitiven Verben."},
      {"id": "gp_dem13", "question": "_____ pani\u0105 m\u00f3wi\u0142 pan wczoraj.", "translation": "\u00dcber diese Dame haben Sie gestern gesprochen.", "options": ["O tej", "Ta", "T\u0119", "T\u0105"], "correct": "O tej", "explanation": "'O tej pani' (\u00fcber diese Dame) \u2013 'o + Lokativ'. 'Tej' ist der Lokativ feminin. Die polnische Wortstellung erlaubt es, das Thema ('o tej pani') an den Satzanfang zu stellen f\u00fcr Betonung: 'O tej pani m\u00f3wi\u0142 pan wczoraj.' Im Deutschen funktioniert das \u00e4hnlich: '\u00dcber diese Dame haben Sie gestern gesprochen.' Die freie Wortstellung ist beiden Sprachen gemein."},
      {"id": "gp_dem14", "question": "Dajcie _____ dzieciom lody.", "translation": "Gebt diesen Kindern Eis.", "options": ["tym", "tych", "te", "ci"], "correct": "tym", "explanation": "'Tym dzieciom' (diesen Kindern) \u2013 Dativ Plural von 'to/te'. 'Da\u0107 komu\u015b co\u015b' (jemandem etwas geben) verlangt Dativ f\u00fcr den Empf\u00e4nger. Die Pluralform 'tym' gilt f\u00fcr den Dativ aller Geschlechter im Plural. Beachten Sie auch den unregelm\u00e4\u00dfigen Dativ Plural: 'dzieci \u2192 dzieciom'. Im Deutschen: 'diesen Kindern' (Dativ Plural). Die Struktur ist hier direkt vergleichbar."},
      {"id": "gp_dem15", "question": "Na _____ zdj\u0119ciu jestem z rodzin\u0105.", "translation": "Auf diesem Foto bin ich mit meiner Familie.", "options": ["tym", "ten", "to", "tego"], "correct": "tym", "explanation": "'Na tym zdj\u0119ciu' (auf diesem Foto) \u2013 'na + Lokativ'. 'Zdj\u0119cie' (Foto) ist Neutrum, Lokativ: 'zdj\u0119ciu'. Das Demonstrativpronomen 'to' wird im Lokativ zu 'tym'. Im Deutschen: 'auf diesem Foto'. Die Konstruktion ist parallel: Pr\u00e4position + Demonstrativpronomen + Substantiv, beide im gleichen Kasus. Die Lokativformen Neutrum und Maskulinum sind bei Demonstrativpronomen identisch ('tym')."}
    ]
  },
  {
    "id": "gp_poss_pron",
    "key": "possessive_pronouns",
    "name": "Zaimki dzier\u017cawcze (Possessivpronomen)",
    "items": [
      {"id": "gp_pos1", "question": "To jest _____ samoch\u00f3d.", "translation": "Das ist mein Auto.", "options": ["m\u00f3j", "moja", "moje", "moi"], "correct": "m\u00f3j", "explanation": "'M\u00f3j samoch\u00f3d' (mein Auto) \u2013 'm\u00f3j' ist die maskuline Form. Die Possessivpronomen richten sich im Polnischen nach dem Geschlecht des besessenen Objekts: 'm\u00f3j' (mask.), 'moja' (fem.), 'moje' (neutr.). 'Samoch\u00f3d' ist maskulin. Im Deutschen: 'mein Auto' \u2013 'Auto' ist Neutrum, aber 'mein' hat dieselbe Form f\u00fcr Mask. und Neutr. im Nominativ. Im Polnischen ist die Formenvielfalt gr\u00f6\u00dfer."},
      {"id": "gp_pos2", "question": "Gdzie jest _____ torba?", "translation": "Wo ist deine Tasche?", "options": ["twoja", "tw\u00f3j", "twoje", "twoi"], "correct": "twoja", "explanation": "'Twoja torba' (deine Tasche) \u2013 'twoja' ist feminin, weil 'torba' (Tasche) feminin ist. Die Possessivpronomen 'tw\u00f3j/twoja/twoje' (dein/deine) werden wie Adjektive dekliniert und m\u00fcssen in Genus, Numerus und Kasus mit dem Substantiv \u00fcbereinstimmen. Im Deutschen: 'deine Tasche' \u2013 auch hier Femininum. Die Formvielfalt im Polnischen ist jedoch gr\u00f6\u00dfer durch sieben Kasus."},
      {"id": "gp_pos3", "question": "_____ dzieci chodz\u0105 do szko\u0142y.", "translation": "Unsere Kinder gehen in die Schule.", "options": ["Nasze", "Nasi", "Nasz", "Nasza"], "correct": "Nasze", "explanation": "'Nasze dzieci' (unsere Kinder) \u2013 'nasze' ist die Pluralform f\u00fcr nicht-m\u00e4nnlich-personale Substantive. Im Polnischen gibt es im Plural die Unterscheidung: 'nasi' (m\u00e4nnlich-personal: unsere S\u00f6hne/Br\u00fcder/Freunde) vs. 'nasze' (alles andere: unsere Kinder/T\u00f6chter/Sachen). 'Dzieci' ist nicht-m\u00e4nnlich-personal, daher 'nasze'. Im Deutschen gibt es nur 'unsere' f\u00fcr alle Plurale."},
      {"id": "gp_pos4", "question": "Sp\u0119dzili\u015bmy wakacje u _____ babci.", "translation": "Wir haben den Urlaub bei unserer Oma verbracht.", "options": ["naszej", "nasza", "nasz", "nasze"], "correct": "naszej", "explanation": "'U naszej babci' (bei unserer Oma) \u2013 'u' verlangt Genitiv. 'Naszej' ist der Genitiv feminin von 'nasza'. Die Deklination der Possessivpronomen im Femininum: 'nasza' (Nom.), 'naszej' (Gen.), 'nasz\u0105' (Akk.), 'naszej' (Dat.), 'nasz\u0105' (Instr.), 'naszej' (Lok.). Beachten Sie: Gen. = Dat. = Lok. bei Feminina \u2013 das erleichtert das Lernen. Im Deutschen: 'bei unserer Oma' (Dativ)."},
      {"id": "gp_pos5", "question": "Pami\u0119tasz _____ adres?", "translation": "Erinnerst du dich an seine Adresse?", "options": ["jego", "jej", "ich", "sw\u00f3j"], "correct": "jego", "explanation": "'Jego adres' (seine Adresse) \u2013 'jego' (sein) ist unverf\u00e4nderlich! Im Polnischen werden die Possessivpronomen der 3. Person ('jego' = sein, 'jej' = ihr, 'ich' = ihr/Plural) NICHT dekliniert. Sie bleiben in allen Kasus gleich: 'jego adres/adresu/adresowi'. Im Deutschen wird 'sein' dagegen dekliniert: 'sein/seines/seinem/seinen'. Diese Vereinfachung im Polnischen ist f\u00fcr Deutschsprachige ein Vorteil."},
      {"id": "gp_pos6", "question": "Prosz\u0119 zapisa\u0107 _____ numer telefonu.", "translation": "Bitte notieren Sie Ihre Telefonnummer.", "options": ["sw\u00f3j", "tw\u00f3j", "m\u00f3j", "jego"], "correct": "sw\u00f3j", "explanation": "'Sw\u00f3j numer' (Ihre/seine/ihre eigene Nummer) \u2013 'sw\u00f3j/swoja/swoje' ist das reflexive Possessivpronomen und bedeutet 'eigen'. Es bezieht sich immer auf das Subjekt des Satzes. Wenn das Subjekt 'Sie' ist (h\u00f6flich), bedeutet 'sw\u00f3j' 'Ihr eigen'. Im Deutschen gibt es kein separates reflexives Possessivpronomen. Man sagt 'sein/ihr', w\u00e4hrend das Polnische 'sw\u00f3j' verlangt, wenn Besitzer = Subjekt."},
      {"id": "gp_pos7", "question": "Lubi\u0119 _____ prac\u0119.", "translation": "Ich mag meine (eigene) Arbeit.", "options": ["swoj\u0105", "moj\u0105", "twoj\u0105", "jej"], "correct": "swoj\u0105", "explanation": "'Lubi\u0119 swoj\u0105 prac\u0119' (Ich mag meine eigene Arbeit) \u2013 wenn Besitzer = Subjekt (hier: 'ja'), muss im Polnischen 'sw\u00f3j' statt 'm\u00f3j' stehen. 'Moj\u0105 prac\u0119' w\u00e4re auch verst\u00e4ndlich, aber 'swoj\u0105' ist grammatisch korrekt und stilistisch bevorzugt. Vergleichen Sie: 'On lubi swoj\u0105 prac\u0119' (Er mag seine eigene Arbeit) vs. 'On lubi jego prac\u0119' (Er mag DESSEN Arbeit \u2013 eine andere Person!). Dieser Unterschied ist im Deutschen nicht vorhanden."},
      {"id": "gp_pos8", "question": "Widzimy _____ nauczycieli codziennie.", "translation": "Wir sehen unsere Lehrer jeden Tag.", "options": ["swoich", "naszych", "ich", "twoich"], "correct": "swoich", "explanation": "'Swoich nauczycieli' (unsere eigenen Lehrer) \u2013 Akkusativ/Genitiv Plural maskulin-personal von 'sw\u00f3j'. Da Subjekt ('my') = Besitzer, wird 'sw\u00f3j' bevorzugt. Die Deklination von 'sw\u00f3j' im Plural: 'swoi' (Nom. m\u00e4nnl.-pers.), 'swoje' (Nom. andere), 'swoich' (Gen./Akk. belebt), 'swoim' (Dat.), 'swoimi' (Instr.), 'swoich' (Lok.). Im Deutschen: 'unsere Lehrer' \u2013 ohne reflexive Alternative."},
      {"id": "gp_pos9", "question": "To jest _____ kot czy wasz?", "translation": "Ist das eure Katze oder eure?", "options": ["wasz", "m\u00f3j", "tw\u00f3j", "ich"], "correct": "wasz", "explanation": "'Wasz kot' (euer Kater/eure Katze) \u2013 'wasz' ist maskulin, weil 'kot' (Katze/Kater) maskulin ist. Die Possessivpronomen f\u00fcr 'ihr' (Plural): 'wasz' (mask.), 'wasza' (fem.), 'wasze' (neutr.). Im Deutschen: 'euer/eure'. Beachten Sie: 'kot' ist im Polnischen immer maskulin, unabh\u00e4ngig vom Geschlecht des Tieres. Die weibliche Form w\u00e4re 'kotka' (K\u00e4tzin). Im Deutschen hat 'Katze' kein grammatisches Maskulinum."},
      {"id": "gp_pos10", "question": "Daj mi _____ r\u0119k\u0119.", "translation": "Gib mir deine Hand.", "options": ["swoj\u0105", "twoj\u0105", "moj\u0105", "jej"], "correct": "swoj\u0105", "explanation": "'Daj mi swoj\u0105 r\u0119k\u0119' (Gib mir deine eigene Hand) \u2013 im Imperativ bezieht sich 'sw\u00f3j' auf die angeredete Person (= Subjekt der Handlung). 'Twoj\u0105 r\u0119k\u0119' w\u00e4re auch verst\u00e4ndlich, aber 'swoj\u0105' ist die grammatisch pr\u00e4zisere Wahl, da Besitzer = handelnde Person. 'R\u0119ka' (Hand) ist feminin, Akkusativ = 'r\u0119k\u0119'. Im Deutschen: 'deine Hand' \u2013 ohne M\u00f6glichkeit der reflexiven Unterscheidung."},
      {"id": "gp_pos11", "question": "Poznali\u015bmy _____ rodzin\u0119.", "translation": "Wir haben ihre (= der anderen Person) Familie kennengelernt.", "options": ["jego", "swoj\u0105", "nasz\u0105", "moj\u0105"], "correct": "jego", "explanation": "'Jego rodzin\u0119' (seine Familie \u2013 einer anderen Person) \u2013 hier passt 'jego', weil der Besitzer NICHT das Subjekt ist. Vergleichen Sie: 'On pozna\u0142 swoj\u0105 rodzin\u0119' (Er lernte seine EIGENE Familie kennen) vs. 'My poznali\u015bmy jego rodzin\u0119' (Wir lernten SEINE Familie kennen). Im Deutschen: 'seine Familie' in beiden F\u00e4llen \u2013 ununterscheidbar! Das polnische System ist pr\u00e4ziser, aber fordert mehr Aufmerksamkeit."},
      {"id": "gp_pos12", "question": "Marzy _____ o wakacjach.", "translation": "Sie (= die Frau) tr\u00e4umt von Urlaub.", "options": ["jej", "jego", "ich", "swoje"], "correct": "jej", "explanation": "Achtung, Fangfrage! 'Jej' w\u00e4re richtig, wenn es um einen Besitz g\u00e4nge ('jej wakacje' = ihre Ferien). Aber hier ist 'ona marzy' (sie tr\u00e4umt) \u2013 hier braucht man gar kein Possessivpronomen. 'Marzy\u0107 o + Lokativ' (tr\u00e4umen von). Der Satz 'Marzy o wakacjach' ist vollst\u00e4ndig. 'Jej' als Option zeigt: die Pronominalformen 'jego/jej/ich' haben einen Doppelcharakter \u2013 sie sind sowohl Possessivpronomen als auch Genitivformen der Personalpronomen."},
      {"id": "gp_pos13", "question": "Zostawi\u0142em parasol w _____ biurze.", "translation": "Ich habe den Regenschirm in meinem B\u00fcro gelassen.", "options": ["swoim", "moim", "twoim", "jego"], "correct": "swoim", "explanation": "'W swoim biurze' (in meinem eigenen B\u00fcro) \u2013 'swoim' ist der Lokativ maskulin/neutrum von 'sw\u00f3j'. Da ich (Subjekt) den Schirm in MEINEM (eigenen) B\u00fcro gelassen habe, steht 'sw\u00f3j'. 'Biuro' (B\u00fcro) ist Neutrum, Lokativ: 'biurze'. Die Lokativformen: 'swoim' (mask./neutr.), 'swojej' (fem.), 'swoich' (Plural). Im Deutschen: 'in meinem B\u00fcro' \u2013 'mein' wird hier einfach dekliniert."},
      {"id": "gp_pos14", "question": "Czy to s\u0105 _____ okulary?", "translation": "Sind das Ihre Brillen?", "options": ["Pa\u0144stwa", "wasz", "twoje", "ich"], "correct": "Pa\u0144stwa", "explanation": "'Pa\u0144stwa okulary' (Ihre Brillen \u2013 h\u00f6flich, Plural) \u2013 in der h\u00f6flichen Anrede verwendet das Polnische 'Pana' (Ihr \u2013 an einen Mann), 'Pani' (Ihr \u2013 an eine Frau) oder 'Pa\u0144stwa' (Ihr \u2013 an mehrere Personen). Diese Formen sind unverf\u00e4nderlich! Im Deutschen: 'Ihre' (h\u00f6flich). Im Polnischen werden sie gro\u00dfgeschrieben. Das h\u00f6fliche System ist anders als im Deutschen: Polnisch nutzt 3. Person statt Pluralformen."},
      {"id": "gp_pos15", "question": "Ka\u017cdy ma _____ zdanie.", "translation": "Jeder hat seine eigene Meinung.", "options": ["swoje", "jego", "ich", "moje"], "correct": "swoje", "explanation": "'Ka\u017cdy ma swoje zdanie' (Jeder hat seine eigene Meinung) \u2013 'ka\u017cdy' (jeder) ist das Subjekt, 'swoje' bezieht sich reflexiv darauf. 'Zdanie' (Meinung) ist Neutrum, daher 'swoje' (Akk. neutr.). Wenn man 'jego zdanie' sagen w\u00fcrde, w\u00fcrde es die Meinung einer ANDEREN spezifischen m\u00e4nnlichen Person bedeuten. 'Sw\u00f3j' bei unbestimmten Pronomen wie 'ka\u017cdy/nikt/kto\u015b' ist im Polnischen obligatorisch."}
    ]
  },
  {
    "id": "gp_refl_pron",
    "key": "reflexive_pronouns",
    "name": "Zaimki zwrotne (Reflexivpronomen)",
    "items": [
      {"id": "gp_ref1", "question": "Myj\u0119 _____ rano pod prysznicem.", "translation": "Ich wasche mich morgens unter der Dusche.", "options": ["si\u0119", "siebie", "sobie", "sob\u0105"], "correct": "si\u0119", "explanation": "'Myj\u0119 si\u0119' (ich wasche mich) \u2013 'si\u0119' ist das allgemeine Reflexivpronomen im Polnischen. Im Gegensatz zum Deutschen hat das Polnische NUR eine Form f\u00fcr alle Personen: 'si\u0119'. Im Deutschen: 'ich wasche mich, du w\u00e4schst dich, er w\u00e4scht sich' \u2013 verschiedene Formen. Im Polnischen: 'myj\u0119 si\u0119, myjesz si\u0119, myje si\u0119' \u2013 immer 'si\u0119'. Diese Vereinfachung ist f\u00fcr Deutschsprachige ein gro\u00dfer Vorteil."},
      {"id": "gp_ref2", "question": "Kupi\u0142am _____ now\u0105 sukienk\u0119.", "translation": "Ich habe mir ein neues Kleid gekauft.", "options": ["sobie", "si\u0119", "siebie", "mn\u0105"], "correct": "sobie", "explanation": "'Kupi\u0142am sobie' (ich habe mir gekauft) \u2013 'sobie' ist der Dativ des Reflexivpronomens. Die Kasusformen: 'siebie' (Gen./Akk. betont), 'si\u0119' (Akk. unbetont), 'sobie' (Dat.), 'sob\u0105' (Instr.), 'sobie' (Lok.). Im Deutschen: 'mir' (Dativ). Der Unterschied: Polnisch hat ein eigenes Reflexivpronomen f\u00fcr den Dativ ('sobie'), im Deutschen steht einfach 'mir'. 'Kupi\u0107 sobie' ist im Alltag sehr h\u00e4ufig."},
      {"id": "gp_ref3", "question": "Czy jeste\u015b z _____ zadowolony?", "translation": "Bist du mit dir selbst zufrieden?", "options": ["siebie", "si\u0119", "sobie", "sob\u0105"], "correct": "siebie", "explanation": "'Z siebie' (mit sich selbst) \u2013 'siebie' ist die betonte Genitiv/Akkusativ-Form. Nach Pr\u00e4positionen steht immer die volle Form, nie 'si\u0119': 'z siebie' (mit sich/von sich), 'dla siebie' (f\u00fcr sich), 'o sobie' (\u00fcber sich). 'Zadowolony z + Genitiv' (zufrieden mit). Im Deutschen: 'mit dir selbst' \u2013 hier zeigt sich, dass das Deutsche die Person unterscheidet ('mir/dir/sich'), das Polnische nicht."},
      {"id": "gp_ref4", "question": "Ciesz\u0119 _____ na weekendowy wyjazd.", "translation": "Ich freue mich auf den Wochenendausflug.", "options": ["si\u0119", "siebie", "sobie", "mn\u0105"], "correct": "si\u0119", "explanation": "'Ciesz\u0119 si\u0119' (ich freue mich) \u2013 viele polnische reflexive Verben entsprechen deutschen reflexiven Verben: 'cieszy\u0107 si\u0119' = 'sich freuen', 'ba\u0107 si\u0119' = 'sich f\u00fcrchten', 'uczy\u0107 si\u0119' = 'sich lehren/lernen', 'nudzi\u0107 si\u0119' = 'sich langweilen'. Aber Vorsicht: nicht alle Reflexivverben stimmen \u00fcberein. 'Cieszy\u0107 si\u0119 na + Akkusativ' (sich freuen auf). Im Deutschen: 'sich freuen auf + Akkusativ'. Die Pr\u00e4positionalstruktur ist hier gleich."},
      {"id": "gp_ref5", "question": "Porozmawiajmy mi\u0119dzy _____.", "translation": "Lass uns unter uns reden.", "options": ["sob\u0105", "si\u0119", "siebie", "sobie"], "correct": "sob\u0105", "explanation": "'Mi\u0119dzy sob\u0105' (unter sich/untereinander) \u2013 'sob\u0105' ist der Instrumental des Reflexivpronomens. 'Mi\u0119dzy' (zwischen/unter) verlangt den Instrumental. Im Deutschen: 'unter uns/sich'. Die Wendung 'mi\u0119dzy sob\u0105' ist in Gespr\u00e4chen sehr h\u00e4ufig und bedeutet 'unter Vertrauten/im Vertrauen'. Beachten Sie: auch 'nawzajem' (gegenseitig) wird oft mit reflexiven Konstruktionen kombiniert."},
      {"id": "gp_ref6", "question": "Nie powiniene\u015b by\u0107 taki surowy dla _____.", "translation": "Du solltest nicht so streng zu dir selbst sein.", "options": ["siebie", "si\u0119", "sobie", "ty"], "correct": "siebie", "explanation": "'Dla siebie' (f\u00fcr sich selbst) \u2013 nach der Pr\u00e4position 'dla' steht der Genitiv: 'siebie'. Dieser Ausdruck zeigt die reflexive Bedeutung: 'streng zu sich selbst'. Vergleichen Sie: 'surowy dla siebie' (streng zu sich selbst) vs. 'surowy dla innych' (streng zu anderen). Im Deutschen: 'streng zu dir selbst'. Die Unterscheidung reflexiv/nicht-reflexiv ist im Polnischen durch das universelle 'siebie/sobie' eleganter gel\u00f6st."},
      {"id": "gp_ref7", "question": "Oni pomagaj\u0105 _____ nawzajem.", "translation": "Sie helfen sich gegenseitig.", "options": ["sobie", "si\u0119", "siebie", "im"], "correct": "sobie", "explanation": "'Pomagaj\u0105 sobie nawzajem' (sie helfen sich gegenseitig) \u2013 'pom\u00f3c/pomaga\u0107' (helfen) verlangt den Dativ, daher 'sobie' (sich, Dativ). 'Nawzajem' (gegenseitig/einander) verst\u00e4rkt die reziproke Bedeutung. Im Polnischen gibt es kein separates Reziprokpronomen wie 'einander' im Deutschen. Man verwendet das Reflexivpronomen + 'nawzajem' oder 'wzajemnie'. Weitere Beispiele: 'rozumie\u0107 si\u0119 nawzajem' (sich gegenseitig verstehen)."},
      {"id": "gp_ref8", "question": "Patrz\u0119 na _____ w lustrze.", "translation": "Ich schaue mich im Spiegel an.", "options": ["siebie", "si\u0119", "sobie", "mnie"], "correct": "siebie", "explanation": "'Na siebie' (auf sich selbst) \u2013 nach der Pr\u00e4position 'na' steht die volle Form 'siebie', nicht 'si\u0119'. 'Patrze\u0107 na + Akkusativ' (schauen auf). Im Deutschen: 'mich anschauen' \u2013 ohne Pr\u00e4position. Im Polnischen ist die Pr\u00e4position obligatorisch. Die Regel: 'si\u0119' steht nur ohne Pr\u00e4position als unbetontes Akkusativobjekt. In allen anderen F\u00e4llen (mit Pr\u00e4position, betont, im Genitiv) steht 'siebie'."},
      {"id": "gp_ref9", "question": "Wzi\u0105\u0142 ze _____ parasol.", "translation": "Er nahm einen Regenschirm mit.", "options": ["sob\u0105", "siebie", "si\u0119", "sobie"], "correct": "sob\u0105", "explanation": "'Ze sob\u0105' (mit sich) \u2013 'z/ze + Instrumental'. 'Sob\u0105' ist der Instrumental von 'siebie'. Die Wendung 'wzi\u0105\u0107 ze sob\u0105' (mitnehmen) ist im Alltag \u00e4u\u00dferst h\u00e4ufig: 'Wzi\u0119\u0142am ze sob\u0105 ksi\u0105\u017ck\u0119' (Ich habe ein Buch mitgenommen). 'Ze' statt 'z' wegen der Konsonantengruppe 'so-'. Im Deutschen: 'mit sich nehmen/mitnehmen'. Die polnische Konstruktion ist w\u00f6rtlicher als die deutsche."},
      {"id": "gp_ref10", "question": "On m\u00f3wi tylko o _____.", "translation": "Er spricht nur \u00fcber sich selbst.", "options": ["sobie", "siebie", "si\u0119", "sob\u0105"], "correct": "sobie", "explanation": "'O sobie' (\u00fcber sich selbst) \u2013 'o + Lokativ'. 'Sobie' ist sowohl Dativ als auch Lokativ. 'M\u00f3wi\u0107 o + Lokativ' (sprechen \u00fcber). Im Deutschen: '\u00fcber sich selbst sprechen'. Im Polnischen kann 'o sobie' auch 'von sich/\u00fcber sich' bei Vorstellungen bedeuten: 'Powiedz co\u015b o sobie' (Erz\u00e4hl etwas \u00fcber dich). Das reflexive 'sobie' ist hier f\u00fcr alle Personen gleich, w\u00e4hrend das Deutsche variiert ('\u00fcber mich/dich/sich')."},
      {"id": "gp_ref11", "question": "Nie mo\u017cemy _____ na to pozwoli\u0107.", "translation": "Wir k\u00f6nnen uns das nicht leisten.", "options": ["sobie", "si\u0119", "siebie", "nas"], "correct": "sobie", "explanation": "'Pozwoli\u0107 sobie na co\u015b' (sich etwas leisten) \u2013 'sobie' (Dativ) + 'na + Akkusativ'. Im Deutschen: 'sich etwas leisten' (Dativ + Akkusativ). Weitere reflexive Ausdr\u00fccke mit 'sobie': 'wyobrazi\u0107 sobie' (sich vorstellen), 'poradzi\u0107 sobie' (sich zurechtfinden/zurechtkommen), '\u017cyczy\u0107 sobie' (sich w\u00fcnschen), 'da\u0107 sobie rad\u0119' (sich zu helfen wissen). 'Sobie' im Dativ ist eine der h\u00e4ufigsten Reflexivkonstruktionen."},
      {"id": "gp_ref12", "question": "Wed\u0142ug _____ wszystko jest w porz\u0105dku.", "translation": "Meiner Meinung nach ist alles in Ordnung.", "options": ["mnie", "siebie", "sobie", "ja"], "correct": "mnie", "explanation": "Achtung: 'Wed\u0142ug mnie' (meiner Meinung nach), NICHT 'wed\u0142ug siebie'! Hier ist 'wed\u0142ug' + Genitiv, und das Subjekt ist nicht explizit 'ja'. In unpersondlichen Konstruktionen oder wenn die Person ihre eigene Meinung ausdr\u00fcckt, steht das Personalpronomen, nicht das Reflexivpronomen. 'Siebie' w\u00fcrde nur stehen, wenn ein anderes Subjekt auf sich selbst verweist. Dieser Unterschied ist subtil und erfordert \u00dcbung."},
      {"id": "gp_ref13", "question": "Zostawcie to mi\u0119dzy _____.", "translation": "Lasst das unter euch.", "options": ["sob\u0105", "si\u0119", "siebie", "wami"], "correct": "sob\u0105", "explanation": "'Mi\u0119dzy sob\u0105' (untereinander/unter sich) \u2013 Instrumental nach 'mi\u0119dzy'. Diese Wendung funktioniert f\u00fcr alle Personen: 'Mi\u0119dzy sob\u0105 m\u00f3wi\u0105 po polsku' (Untereinander sprechen sie Polnisch). Im Deutschen: 'unter sich/untereinander'. Die Universalit\u00e4t des polnischen Reflexivpronomens (eine Form f\u00fcr alle Personen) ist hier besonders deutlich \u2013 'sob\u0105' deckt 'mir/dir/sich/uns/euch' ab."},
      {"id": "gp_ref14", "question": "Chcia\u0142bym _____ zrobi\u0107 kaw\u0119.", "translation": "Ich w\u00fcrde mir gern einen Kaffee machen.", "options": ["sobie", "si\u0119", "siebie", "mi"], "correct": "sobie", "explanation": "'Zrobi\u0107 sobie kaw\u0119' (sich einen Kaffee machen) \u2013 'sobie' als Dativus commodi (Dativ des Nutzens). Im Polnischen dr\u00fcckt 'sobie' oft aus, dass die Handlung f\u00fcr die handelnde Person selbst ist. Im Deutschen: 'mir einen Kaffee machen'. Weitere Alltagsbeispiele: 'ugotowa\u0107 sobie obiad' (sich Mittagessen kochen), 'kupi\u0107 sobie loda' (sich ein Eis kaufen), 'za\u0142atwi\u0107 sobie co\u015b' (sich etwas beschaffen)."},
      {"id": "gp_ref15", "question": "Jest pewna _____ w ka\u017cdej sytuacji.", "translation": "Sie ist in jeder Situation selbstsicher.", "options": ["siebie", "sobie", "si\u0119", "sob\u0105"], "correct": "siebie", "explanation": "'Pewna siebie' (selbstsicher, w\u00f6rtl.: sicher ihrer selbst) \u2013 'pewny/pewna + Genitiv'. Das Adjektiv 'pewny' (sicher) verlangt den Genitiv: 'pewny siebie' (seiner/ihrer selbst sicher). Im Deutschen: 'selbstsicher'. Weitere Adjektive mit 'siebie': '\u015bwiadomy siebie' (seiner selbst bewusst), 'dumny z siebie' (stolz auf sich). Diese Konstruktionen sind im psychologischen und pers\u00f6nlichen Vokabular wichtig und kommen im Alltag h\u00e4ufig vor."}
    ]
  },
  {
    "id": "gp_indef_pron",
    "key": "indefinite_pronouns",
    "name": "Zaimki nieokre\u015blone (Indefinitpronomen)",
    "items": [
      {"id": "gp_ind1", "question": "_____ puka do drzwi.", "translation": "Jemand klopft an die T\u00fcr.", "options": ["Kto\u015b", "Nikt", "Ka\u017cdy", "Ktokolwiek"], "correct": "Kto\u015b", "explanation": "'Kto\u015b' (jemand) ist das grundlegende Indefinitpronomen f\u00fcr unbestimmte Personen. Im Deutschen: 'jemand'. Die polnischen Indefinitpronomen werden durch das Suffix '-\u015b' gebildet: 'kto\u015b' (jemand), 'co\u015b' (etwas), 'jaki\u015b' (irgendein/irgendwelche), 'gdzie\u015b' (irgendwo), 'kiedy\u015b' (irgendwann). Diese Systematik mit '-\u015b' ist ein produktives Muster, das es im Deutschen nicht gibt."},
      {"id": "gp_ind2", "question": "Czy widzisz tam _____?", "translation": "Siehst du dort etwas?", "options": ["co\u015b", "nic", "co", "cokolwiek"], "correct": "co\u015b", "explanation": "'Co\u015b' (etwas) ist das Indefinitpronomen f\u00fcr unbestimmte Dinge. Im Deutschen: 'etwas'. In Fragen steht im Polnischen 'co\u015b' (erwartet eine bestimmte Antwort) vs. 'cokolwiek' (beliebig/egal was). Vergleichen Sie: 'Czy widzisz co\u015b?' (Siehst du etwas Bestimmtes?) vs. 'Widzisz cokolwiek?' (Siehst du \u00fcberhaupt irgendetwas?). Im Deutschen wird dieser Bedeutungsunterschied durch Kontext oder Zusatzw\u00f6rter ausgedr\u00fcckt."},
      {"id": "gp_ind3", "question": "_____ nie przyszed\u0142 na spotkanie.", "translation": "Niemand ist zum Treffen gekommen.", "options": ["Nikt", "Kto\u015b", "Ka\u017cdy", "Wszyscy"], "correct": "Nikt", "explanation": "'Nikt' (niemand) ist das negative Indefinitpronomen. Im Polnischen verwendet man doppelte Verneinung: 'Nikt NIE przyszed\u0142' (Niemand ist NICHT gekommen = Niemand ist gekommen). Im Deutschen ist doppelte Verneinung nicht Standard: 'Niemand ist gekommen'. Die polnischen negativen Pronomen: 'nikt' (niemand), 'nic' (nichts), '\u017caden' (kein), 'nigdy' (nie), 'nigdzie' (nirgendwo). Alle verlangen 'nie' vor dem Verb."},
      {"id": "gp_ind4", "question": "_____ student musi zda\u0107 egzamin.", "translation": "Jeder Student muss die Pr\u00fcfung bestehen.", "options": ["Ka\u017cdy", "Kto\u015b", "Nikt", "\u017baden"], "correct": "Ka\u017cdy", "explanation": "'Ka\u017cdy' (jeder) ist das universale Indefinitpronomen. Es wird wie ein Adjektiv dekliniert: 'ka\u017cdy' (mask.), 'ka\u017cda' (fem.), 'ka\u017cde' (neutr.). Im Deutschen: 'jeder/jede/jedes'. Beachten Sie: 'ka\u017cdy' steht mit dem Verb in der 3. Person Singular: 'ka\u017cdy wie' (jeder wei\u00df), genau wie im Deutschen. Im Gegensatz zu 'wszyscy' (alle) + Plural: 'wszyscy wiedz\u0105' (alle wissen)."},
      {"id": "gp_ind5", "question": "Nie mam _____ do powiedzenia.", "translation": "Ich habe nichts zu sagen.", "options": ["nic", "co\u015b", "co", "czego\u015b"], "correct": "nic", "explanation": "'Nic' (nichts) \u2013 das negative Pronomen f\u00fcr Sachen. Beachten Sie die doppelte Verneinung: 'Nie mam NIC' (Ich habe NICHT NICHTS = Ich habe nichts). Die Genitiv-Form von 'nic' ist 'niczego': 'Nie wymaga niczego' (Es erfordert nichts). Im Deutschen steht einfach 'nichts' ohne doppelte Verneinung. Die polnische Konstruktion 'nic + do + Genitiv des Verbalsubstantivs' ('do powiedzenia') ist eine produktive Wendung: 'nic do dodania' (nichts hinzuzuf\u00fcgen)."},
      {"id": "gp_ind6", "question": "Chcia\u0142bym _____ kawy.", "translation": "Ich h\u00e4tte gern etwas Kaffee.", "options": ["troch\u0119", "co\u015b", "jaki\u015b", "du\u017co"], "correct": "troch\u0119", "explanation": "'Troch\u0119 kawy' (etwas Kaffee) \u2013 'troch\u0119' bedeutet 'ein wenig/etwas' bei unz\u00e4hlbaren Substantiven und steht mit Genitiv. Vergleichen Sie mit 'co\u015b': 'Co\u015b do picia' (etwas zum Trinken). Im Deutschen hat 'etwas' beide Funktionen (Pronomen und Quantifikator). Im Polnischen wird differenziert: 'co\u015b' = unbestimmtes Etwas, 'troch\u0119' = kleine Menge. Weitere Mengenpronomen: 'du\u017co' (viel), 'ma\u0142o' (wenig), 'kilka' (einige)."},
      {"id": "gp_ind7", "question": "Musz\u0119 _____ kupi\u0107 w sklepie.", "translation": "Ich muss einiges im Gesch\u00e4ft kaufen.", "options": ["co\u015b", "nic", "ka\u017cdy", "nikt"], "correct": "co\u015b", "explanation": "'Co\u015b kupi\u0107' (etwas kaufen) \u2013 'co\u015b' als unbestimmtes Akkusativobjekt. Im Polnischen bleibt 'co\u015b' in Nom./Akk. unver\u00e4ndert, \u00e4ndert sich aber in anderen Kasus: 'czego\u015b' (Gen.), 'czemu\u015b' (Dat.), 'czym\u015b' (Instr.), 'czym\u015b' (Lok.). Im Deutschen bleibt 'etwas' unver\u00e4ndert. Die polnische Deklination von Indefinitpronomen ist ein Merkmal, das Deutschsprachige besonders \u00fcben m\u00fcssen."},
      {"id": "gp_ind8", "question": "_____ pi\u0119knego dzi\u015b tu widzia\u0142em.", "translation": "Heute habe ich hier etwas Sch\u00f6nes gesehen.", "options": ["Co\u015b", "Nic", "Ka\u017cdy", "Co"], "correct": "Co\u015b", "explanation": "'Co\u015b pi\u0119knego' (etwas Sch\u00f6nes) \u2013 nach 'co\u015b/nic/co' steht das Adjektiv im Genitiv Neutrum: 'pi\u0119kne' \u2192 'pi\u0119knego'. Im Deutschen steht das Adjektiv nach 'etwas' ebenso in einer speziellen Form: 'etwas Sch\u00f6nes' (substantiviertes Adjektiv). Weitere Beispiele: 'co\u015b nowego' (etwas Neues), 'nic ciekawego' (nichts Interessantes), 'co\u015b wa\u017cnego' (etwas Wichtiges). Das Muster ist in beiden Sprachen \u00e4hnlich."},
      {"id": "gp_ind9", "question": "_____ cz\u0142owiek by to zrobi\u0142.", "translation": "Jeder (beliebige) Mensch w\u00fcrde das tun.", "options": ["Ka\u017cdy", "Kto\u015b", "Nikt", "Jaki\u015b"], "correct": "Ka\u017cdy", "explanation": "'Ka\u017cdy cz\u0142owiek' (jeder Mensch) \u2013 'ka\u017cdy' als adjektivisches Pronomen vor einem Substantiv. Im Polnischen kann 'ka\u017cdy' sowohl substantivisch ('Ka\u017cdy to wie' \u2013 Jeder wei\u00df das) als auch adjektivisch ('Ka\u017cdy student...' \u2013 Jeder Student...) verwendet werden. Im Deutschen ebenso: 'jeder' (substantivisch) vs. 'jeder Mensch' (adjektivisch). Die Konditionalform 'by to zrobi\u0142' entspricht dem deutschen 'w\u00fcrde das tun'."},
      {"id": "gp_ind10", "question": "Z\u0142\u00f3\u017c podanie do _____ firmy.", "translation": "Bewirb dich bei irgendeiner Firma.", "options": ["jakiejkolwiek", "jakiej\u015b", "ka\u017cdej", "\u017cadnej"], "correct": "jakiejkolwiek", "explanation": "'Jakiejkolwiek firmy' (irgendeiner beliebigen Firma, Gen.) \u2013 die '-kolwiek'-Pronomen dr\u00fccken Beliebigkeit aus: 'jakikolwiek' (irgendein beliebiger), 'ktokolwiek' (wer auch immer), 'cokolwiek' (was auch immer), 'gdziekolwiek' (wo auch immer). Im Deutschen: 'irgendein(e)'. Der Unterschied zu '-\u015b': 'jaki\u015b' (irgendein bestimmter) vs. 'jakikolwiek' (irgendein beliebiger). Diese Nuance ist im Deutschen schwerer auszudr\u00fccken."},
      {"id": "gp_ind11", "question": "_____ ma swoje wady i zalety.", "translation": "Alles hat seine Vor- und Nachteile.", "options": ["Wszystko", "Ka\u017cdy", "Co\u015b", "Nikt"], "correct": "Wszystko", "explanation": "'Wszystko' (alles) ist das universale Pronomen f\u00fcr Sachen/abstrakte Konzepte. Im Deutschen: 'alles'. Vergleichen Sie: 'wszystko' (alles \u2013 Sachen) vs. 'wszyscy' (alle \u2013 Personen). Im Deutschen wird 'alles/alle' ebenfalls unterschieden, aber weniger streng. Die Kasusformen: 'wszystko' (Nom./Akk.), 'wszystkiego' (Gen.), 'wszystkiemu' (Dat.), 'wszystkim' (Instr./Lok.). Diese Deklination folgt dem Neutrum-Muster."},
      {"id": "gp_ind12", "question": "Wol\u0119 siada\u0107 gdzie _____ w kinie.", "translation": "Ich setze mich am liebsten irgendwo vorn im Kino.", "options": ["indziej", "niegdzie", "gdzie\u015b", "nigdzie"], "correct": "indziej", "explanation": "'Gdzie indziej' (woanders/anderswo) \u2013 'indziej' ist ein spezielles Adverbialpronomen: 'gdzie indziej' (woanders), 'kiedy indziej' (ein andermal), 'co innego' (etwas anderes), 'kto inny' (jemand anderer). Im Deutschen: 'woanders/anderswo'. Die Konstruktion 'Pronomen + inny/indziej' (anders) ist produktiv und idiomatisch. Achtung: In der Frage war 'irgendwo vorn' gemeint \u2013 das w\u00e4re 'gdzie\u015b z przodu'. Aber 'gdzie indziej' als Wortschatz ist ebenso wichtig."},
      {"id": "gp_ind13", "question": "_____ z was nie zda\u0142 egzaminu?", "translation": "Hat keiner von euch die Pr\u00fcfung bestanden?", "options": ["\u017baden", "Ka\u017cdy", "Kto\u015b", "Nikt"], "correct": "\u017baden", "explanation": "'\u017baden z was' (keiner von euch) \u2013 '\u017caden' (kein/keiner) wird wie ein Adjektiv dekliniert: '\u017caden' (mask.), '\u017cadna' (fem.), '\u017cadne' (neutr.). Im Deutschen: 'keiner'. Beachten Sie den Unterschied: 'nikt' (niemand \u2013 allgemein) vs. '\u017caden' (keiner \u2013 aus einer bestimmten Gruppe). '\u017baden z was nie zda\u0142' \u2013 wieder doppelte Verneinung mit 'nie'. Im Deutschen: 'Keiner von euch hat bestanden' (ohne doppelte Verneinung)."},
      {"id": "gp_ind14", "question": "Dam ci _____, co b\u0119dziesz potrzebowa\u0142.", "translation": "Ich gebe dir alles, was du brauchen wirst.", "options": ["wszystko", "co\u015b", "nic", "cokolwiek"], "correct": "wszystko", "explanation": "'Dam ci wszystko, co...' (Ich gebe dir alles, was...) \u2013 nach 'wszystko' steht das Relativpronomen 'co' (was), nicht 'kt\u00f3re'. Im Deutschen: 'alles, was...'. Diese Konstruktion ist identisch strukturiert. Beachten Sie das Futur: 'b\u0119dziesz potrzebowa\u0142' (du wirst brauchen \u2013 zusammengesetztes Futur mit imperfektivem Verb). Im Polnischen gibt es kein Futur I/II wie im Deutschen, sondern einfaches vs. zusammengesetztes Futur."},
      {"id": "gp_ind15", "question": "Przyjd\u017a _____ chcesz, drzwi s\u0105 otwarte.", "translation": "Komm wann immer du willst, die T\u00fcr ist offen.", "options": ["kiedy", "kiedy\u015b", "kiedykolwiek", "nigdy"], "correct": "kiedy", "explanation": "'Kiedy chcesz' (wann du willst) oder 'kiedykolwiek chcesz' (wann auch immer du willst) \u2013 beide sind korrekt. 'Kiedy' (wann) in Verbindung mit 'chcesz' (du willst) dr\u00fcckt bereits Beliebigkeit aus: 'wann (auch immer) du m\u00f6chtest'. Im Deutschen: 'wann du willst/wann immer du willst'. Die polnischen temporalen Pronomen: 'kiedy' (wann), 'kiedy\u015b' (irgendwann/einmal), 'kiedykolwiek' (wann auch immer), 'nigdy' (nie), 'zawsze' (immer)."}
    ]
  }
]

data.extend(new_cats)

# Validate
ids = set()
dupes = []
for cat in data:
    for item in cat['items']:
        if item['id'] in ids:
            dupes.append(item['id'])
        ids.add(item['id'])

short = [item['id'] for cat in new_cats for item in cat['items'] if len(item['explanation']) < 200]
no_blank = [item['id'] for cat in new_cats for item in cat['items'] if '_____' not in item['question']]

with open(f, 'w', encoding='utf-8') as fout:
    json.dump(data, fout, ensure_ascii=False, indent=2)

print(f"After: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")
print(f"Duplicate IDs: {dupes if dupes else 'None'}")
print(f"Short explanations: {short if short else 'None'}")
print(f"Missing blanks: {no_blank if no_blank else 'None'}")
print(f"Added: {[c['key'] for c in new_cats]}")
