#!/usr/bin/env python3
import json
import os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
f = os.path.join(base, 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json')
data = json.load(open(f, encoding='utf-8'))
print(f"Before: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")

new_cats = [
  {
    "id": "gp_prep_z",
    "key": "prepositions_z",
    "name": "Przyimek \u201ez\u201d (mit/aus)",
    "items": [
      {"id": "gp_pz1", "question": "Pij\u0119 kaw\u0119 _____ mlekiem.", "translation": "Ich trinke Kaffee mit Milch.", "options": ["z", "ze", "od", "na"], "correct": "z", "explanation": "Der polnische Pr\u00e4position 'z' mit Instrumental bedeutet 'mit' (wie das deutsche 'mit'). 'Pij\u0119 kaw\u0119 z mlekiem' \u2013 hier verlangt 'z' den Instrumental. F\u00fcr deutschsprachige Lernende: 'z + Instrumental' = 'mit + Dativ'. Das ist eine der h\u00e4ufigsten Pr\u00e4positionen im Polnischen und wird in vielen allt\u00e4glichen Ausdr\u00fccken verwendet, z.B. 'chleb z mas\u0142em' (Brot mit Butter)."},
      {"id": "gp_pz2", "question": "Wracam _____ pracy o pi\u0105tej.", "translation": "Ich komme um f\u00fcnf von der Arbeit zur\u00fcck.", "options": ["z", "od", "ze", "do"], "correct": "z", "explanation": "Die Pr\u00e4position 'z' mit Genitiv bedeutet 'aus/von' (entspricht dem deutschen 'von/aus'). 'Wracam z pracy' \u2013 hier steht 'praca' im Genitiv ('pracy'). Beachten Sie den Unterschied: 'z + Instrumental' = 'mit', aber 'z + Genitiv' = 'von/aus'. Diese Doppelfunktion gibt es im Deutschen nicht, daher ist es wichtig, den Fall (Kasus) zu beachten."},
      {"id": "gp_pz3", "question": "Rozmawiam _____ koleg\u0105 z pracy.", "translation": "Ich spreche mit einem Arbeitskollegen.", "options": ["z", "od", "do", "na"], "correct": "z", "explanation": "Nach 'rozmawia\u0107' (sprechen) steht die Pr\u00e4position 'z' mit Instrumental: 'z koleg\u0105'. Das Verb 'rozmawia\u0107 z kim\u015b' entspricht dem deutschen 'mit jemandem sprechen'. Im Polnischen muss man sich merken, welche Verben 'z + Instrumental' verlangen. Weitere Beispiele: 'spotyka\u0107 si\u0119 z kim\u015b' (sich mit jemandem treffen), 'zgadza\u0107 si\u0119 z kim\u015b' (mit jemandem \u00fcbereinstimmen)."},
      {"id": "gp_pz4", "question": "Jestem _____ Niemiec.", "translation": "Ich bin aus Deutschland.", "options": ["z", "od", "w", "do"], "correct": "z", "explanation": "Um die Herkunft auszudr\u00fccken, verwendet man 'z + Genitiv': 'Jestem z Niemiec' (Ich bin aus Deutschland). 'Niemcy' (Deutschland) steht im Genitiv als 'Niemiec'. F\u00fcr deutschsprachige Lernende: 'z' bei Herkunftsangaben entspricht dem deutschen 'aus'. Weitere Beispiele: 'z Polski' (aus Polen), 'z Berlina' (aus Berlin), 'z Wiednia' (aus Wien)."},
      {"id": "gp_pz5", "question": "_____ przyjemno\u015bci\u0105 ci pomog\u0119.", "translation": "Ich helfe dir mit Vergn\u00fcgen.", "options": ["Z", "Ze", "Na", "Od"], "correct": "Z", "explanation": "'Z przyjemno\u015bci\u0105' (mit Vergn\u00fcgen) ist eine feste Wendung mit 'z + Instrumental'. Im Polnischen gibt es viele solche festen Ausdr\u00fccke: 'z trudem' (mit M\u00fche), 'z rado\u015bci\u0105' (mit Freude), 'z \u0142atwo\u015bci\u0105' (mit Leichtigkeit). Diese Konstruktionen entsprechen dem deutschen 'mit + Dativ' bei abstrakten Begriffen und sind im formellen wie informellen Polnisch sehr gebr\u00e4uchlich."},
      {"id": "gp_pz6", "question": "Spad\u0142 _____ drzewa.", "translation": "Er ist vom Baum gefallen.", "options": ["z", "od", "ze", "na"], "correct": "z", "explanation": "'Z drzewa' (vom Baum) verwendet 'z + Genitiv' f\u00fcr eine Bewegung von oben nach unten oder von einer Oberfl\u00e4che weg. Vergleichen Sie: 'z g\u00f3ry' (vom Berg), 'z dachu' (vom Dach), 'z p\u00f3\u0142ki' (vom Regal). Im Deutschen verwendet man hier 'von + Dativ'. Die Regel: wenn etwas von einer erh\u00f6hten Position oder Oberfl\u00e4che kommt, benutzt man 'z + Genitiv'."},
      {"id": "gp_pz7", "question": "Ciasto _____ jab\u0142kami jest pyszne.", "translation": "Der Kuchen mit \u00c4pfeln ist lecker.", "options": ["z", "od", "na", "do"], "correct": "z", "explanation": "'Z jab\u0142kami' (mit \u00c4pfeln) \u2013 'z + Instrumental' dr\u00fcckt Begleitung oder Zutat aus, genau wie das deutsche 'mit'. Bei Speisen ist diese Konstruktion besonders h\u00e4ufig: 'pierogi z mi\u0119sem' (Piroggen mit Fleisch), 'sa\u0142atka z pomidorami' (Salat mit Tomaten), 'herbata z cytryn\u0105' (Tee mit Zitrone). Der Instrumental Plural von 'jab\u0142ko' ist 'jab\u0142kami'."},
      {"id": "gp_pz8", "question": "_____ roku na rok jest coraz lepiej.", "translation": "Von Jahr zu Jahr wird es immer besser.", "options": ["Z", "Od", "Na", "Do"], "correct": "Z", "explanation": "'Z roku na rok' (von Jahr zu Jahr) ist eine feste Redewendung, die Ver\u00e4nderung \u00fcber Zeit ausdr\u00fcckt. Im Polnischen gibt es \u00e4hnliche Konstruktionen: 'z dnia na dzie\u0144' (von Tag zu Tag), 'z godziny na godzin\u0119' (von Stunde zu Stunde). Diese Ausdr\u00fccke verwenden 'z + Genitiv... na + Akkusativ' und entsprechen dem deutschen 'von... zu...'."},
      {"id": "gp_pz9", "question": "Zrobi\u0142em to _____ w\u0142asnej woli.", "translation": "Ich habe das aus eigenem Willen getan.", "options": ["z", "od", "na", "ze"], "correct": "z", "explanation": "'Z w\u0142asnej woli' (aus eigenem Willen) verwendet 'z + Genitiv' zur Angabe des Grundes oder der Ursache. \u00c4hnlich wie im Deutschen 'aus + Dativ' bei Gr\u00fcnden. Weitere Beispiele: 'z ciekawo\u015bci' (aus Neugier), 'z g\u0142upoty' (aus Dummheit), 'z mi\u0142o\u015bci' (aus Liebe), 'z zazdro\u015bci' (aus Eifersucht). Diese kausale Bedeutung von 'z' ist eine wichtige dritte Funktion neben 'mit' und 'von/aus'."},
      {"id": "gp_pz10", "question": "Prosz\u0119 _____ \u015bmietan\u0105 do kawy.", "translation": "Sahne zum Kaffee, bitte.", "options": ["ze", "z", "od", "na"], "correct": "ze", "explanation": "Vor Konsonantengruppen, die mit 's', '\u015b', 'z', '\u017a', 'sz', '\u017c' beginnen, wird 'z' zu 'ze' erweitert: 'ze \u015bmietan\u0105' (mit Sahne). Diese phonetische Regel erleichtert die Aussprache. Weitere Beispiele: 'ze szko\u0142y' (aus der Schule), 'ze sto\u0142u' (vom Tisch), 'ze znajomymi' (mit Bekannten). Im Deutschen gibt es keine direkte Parallele zu dieser Lautanpassung."},
      {"id": "gp_pz11", "question": "Wyje\u017cd\u017camy _____ Warszawy jutro rano.", "translation": "Wir fahren morgen fr\u00fch aus Warschau ab.", "options": ["z", "od", "do", "na"], "correct": "z", "explanation": "'Z Warszawy' (aus Warschau) \u2013 bei St\u00e4dten verwendet man 'z + Genitiv' f\u00fcr die Abfahrt. Die Gegenrichtung: 'do Warszawy' (nach Warschau). Diese Paarung 'z/do' bei St\u00e4dten ist regelm\u00e4\u00dfig: 'z Berlina do Krakowa' (von Berlin nach Krakau). Im Deutschen: 'aus/nach'. Bei L\u00e4ndern gilt dasselbe Muster: 'z Niemiec do Polski' (aus Deutschland nach Polen)."},
      {"id": "gp_pz12", "question": "Zupa jest _____ wczoraj.", "translation": "Die Suppe ist von gestern.", "options": ["z", "od", "ze", "na"], "correct": "z", "explanation": "'Z wczoraj' (von gestern) \u2013 'z + Genitiv' kann auch zeitliche Herkunft ausdr\u00fccken. Diese Verwendung ist umgangssprachlich und im Alltag h\u00e4ufig. Weitere Beispiele: 'z zesz\u0142ego tygodnia' (von letzter Woche), 'z ubieg\u0142ego roku' (vom vergangenen Jahr). Vergleichen Sie mit dem Deutschen 'von gestern', das \u00e4hnlich funktioniert. Diese Konstruktion wird besonders bei Lebensmitteln und Nachrichten verwendet."},
      {"id": "gp_pz13", "question": "Spotkajmy si\u0119 _____ nim w kawiarni.", "translation": "Lass uns ihn im Caf\u00e9 treffen.", "options": ["z", "od", "do", "na"], "correct": "z", "explanation": "'Z nim' (mit ihm) \u2013 'z + Instrumental' bei Personalpronomen. Die Formen lauten: 'ze mn\u0105' (mit mir), 'z tob\u0105' (mit dir), 'z nim' (mit ihm), 'z ni\u0105' (mit ihr), 'z nami' (mit uns), 'z wami' (mit euch), 'z nimi' (mit ihnen). Beachten Sie: bei 'ja' (ich) wird 'ze' verwendet wegen der Konsonantengruppe 'mn'. Im Deutschen: 'mit mir/dir/ihm/ihr/uns/euch/ihnen'."},
      {"id": "gp_pz14", "question": "Czyta\u0142em t\u0119 ksi\u0105\u017ck\u0119 _____ zainteresowaniem.", "translation": "Ich habe dieses Buch mit Interesse gelesen.", "options": ["z", "ze", "od", "pod"], "correct": "z", "explanation": "'Z zainteresowaniem' (mit Interesse) \u2013 'z + Instrumental' dr\u00fcckt die Art und Weise einer Handlung aus. Das entspricht dem deutschen 'mit + Dativ' in adverbialer Funktion. Weitere Beispiele: 'z uwag\u0105' (mit Aufmerksamkeit), 'z entuzjazmem' (mit Enthusiasmus), 'z niecierpliwo\u015bci\u0105' (mit Ungeduld). Im Polnischen sind solche Wendungen oft eine elegante Alternative zu Adverbien."},
      {"id": "gp_pz15", "question": "Jestem zadowolony _____ wyniku egzaminu.", "translation": "Ich bin mit dem Pr\u00fcfungsergebnis zufrieden.", "options": ["z", "od", "na", "ze"], "correct": "z", "explanation": "'Zadowolony z + Genitiv' (zufrieden mit) \u2013 einige polnische Adjektive verlangen 'z + Genitiv', obwohl das Deutsche 'mit + Dativ' verwendet. Weitere Beispiele: 'dumny z' (stolz auf), 'znany z' (bekannt f\u00fcr), 'z\u0142o\u017cony z' (bestehend aus). Diese Abweichungen zwischen polnischer und deutscher Kasusrektion sind h\u00e4ufige Fehlerquellen und sollten als feste Wendungen gelernt werden."}
    ]
  },
  {
    "id": "gp_prep_na",
    "key": "prepositions_na",
    "name": "Przyimek \u201ena\u201d (auf/an)",
    "items": [
      {"id": "gp_pn1", "question": "Ksi\u0105\u017cka le\u017cy _____ stole.", "translation": "Das Buch liegt auf dem Tisch.", "options": ["na", "w", "przy", "pod"], "correct": "na", "explanation": "'Na stole' (auf dem Tisch) \u2013 'na + Lokativ' f\u00fcr Ruhelage auf einer Oberfl\u00e4che. Im Deutschen: 'auf dem Tisch' (Dativ bei Ruhelage). Die Wechselpr\u00e4position im Polnischen: 'na stole' (wo? \u2013 Lokativ) vs. 'na st\u00f3\u0142' (wohin? \u2013 Akkusativ). F\u00fcr deutschsprachige Lernende ist diese Unterscheidung vertraut, da auch im Deutschen 'auf dem/auf den' wechselt."},
      {"id": "gp_pn2", "question": "Id\u0119 _____ poczt\u0119.", "translation": "Ich gehe zur Post.", "options": ["na", "do", "w", "pod"], "correct": "na", "explanation": "'Na poczt\u0119' (zur Post) \u2013 bestimmte Orte verlangen im Polnischen 'na' statt 'do': 'na poczt\u0119' (zur Post), 'na dworzec' (zum Bahnhof), 'na lotnisko' (zum Flughafen), 'na uczelni\u0119' (zur Universit\u00e4t). Diese Auswahl ist idiomatisch und muss auswendig gelernt werden. Im Deutschen gibt es keine direkte Parallele \u2013 man sagt einfach 'zu/zur/zum'. Hier steht 'na + Akkusativ' f\u00fcr die Richtung."},
      {"id": "gp_pn3", "question": "Czekam _____ ciebie od godziny.", "translation": "Ich warte seit einer Stunde auf dich.", "options": ["na", "za", "o", "do"], "correct": "na", "explanation": "'Czeka\u0107 na + Akkusativ' (auf jemanden/etwas warten). Im Polnischen verlangt 'czeka\u0107' die Pr\u00e4position 'na', \u00e4hnlich wie im Deutschen 'warten auf'. Weitere Verben mit 'na': 'patrze\u0107 na' (schauen auf), 'liczy\u0107 na' (z\u00e4hlen auf), 'narzeka\u0107 na' (sich beschweren \u00fcber), 'skar\u017cy\u0107 si\u0119 na' (sich beklagen \u00fcber). Diese Verbindungen sollten als feste Wendungen gelernt werden."},
      {"id": "gp_pn4", "question": "Byli\u015bmy _____ wakacjach w Hiszpanii.", "translation": "Wir waren im Urlaub in Spanien.", "options": ["na", "w", "do", "przy"], "correct": "na", "explanation": "'Na wakacjach' (im Urlaub) \u2013 einige abstrakte Konzepte verwenden 'na + Lokativ': 'na wakacjach' (im Urlaub), 'na lekcji' (im Unterricht), 'na spotkaniu' (bei einer Besprechung), 'na koncercie' (bei einem Konzert). Im Deutschen steht hier oft 'in/bei/auf'. Diese Zuordnung ist im Polnischen lexikalisch festgelegt und muss als feste Verbindung gelernt werden."},
      {"id": "gp_pn5", "question": "Mieszkam _____ trzecim pi\u0119trze.", "translation": "Ich wohne im dritten Stock.", "options": ["na", "w", "pod", "przy"], "correct": "na", "explanation": "'Na trzecim pi\u0119trze' (im dritten Stock) \u2013 bei Stockwerken verwendet das Polnische 'na + Lokativ'. Im Deutschen: 'im dritten Stock'. Weitere Beispiele: 'na parterze' (im Erdgeschoss), 'na poddaszu' (auf dem Dachboden). Beachten Sie die Ordnungszahl im Lokativ: 'trzecim' (drittem). Diese Besonderheit \u00fcberrascht oft deutschsprachige Lernende."},
      {"id": "gp_pn6", "question": "Po\u0142\u00f3\u017c talerz _____ p\u00f3\u0142k\u0119.", "translation": "Stell den Teller auf das Regal.", "options": ["na", "w", "do", "pod"], "correct": "na", "explanation": "'Na p\u00f3\u0142k\u0119' (auf das Regal) \u2013 'na + Akkusativ' f\u00fcr Richtung/Ziel. Im Unterschied zu 'na p\u00f3\u0142ce' (Lokativ = auf dem Regal). Dieser Wechsel Lokativ/Akkusativ ist das polnische \u00c4quivalent zum deutschen Dativ/Akkusativ-Wechsel bei Wechselpr\u00e4positionen. Weitere Paare: 'na stole/na st\u00f3\u0142', 'na \u0142\u00f3\u017cku/na \u0142\u00f3\u017cko', 'na \u015bcianie/na \u015bcian\u0119'."},
      {"id": "gp_pn7", "question": "Gram _____ gitarze od pi\u0119ciu lat.", "translation": "Ich spiele seit f\u00fcnf Jahren Gitarre.", "options": ["na", "w", "z", "przy"], "correct": "na", "explanation": "'Gra\u0107 na + Lokativ' (ein Instrument spielen). Im Polnischen sagt man 'gra\u0107 na gitarze' (Gitarre spielen), 'gra\u0107 na pianinie' (Klavier spielen), 'gra\u0107 na skrzypcach' (Geige spielen). Beachten Sie: 'gra\u0107 w + Akkusativ' bedeutet dagegen ein Spiel spielen \u2013 'gra\u0107 w pi\u0142k\u0119' (Ball spielen). Diese Unterscheidung 'na/w' bei 'gra\u0107' ist f\u00fcr Deutschsprachige wichtig zu merken."},
      {"id": "gp_pn8", "question": "Um\u00f3wi\u0142em si\u0119 _____ spotkanie o pi\u0105tej.", "translation": "Ich habe ein Treffen um f\u00fcnf vereinbart.", "options": ["na", "do", "w", "za"], "correct": "na", "explanation": "'Um\u00f3wi\u0107 si\u0119 na + Akkusativ' (sich verabreden zu/f\u00fcr). Die Pr\u00e4position 'na' steht hier im Sinne von 'zu/f\u00fcr'. Weitere solche Verbindungen: 'zapisa\u0107 si\u0119 na' (sich anmelden f\u00fcr), 'przygotowa\u0107 si\u0119 na' (sich vorbereiten auf), 'zdecydowa\u0107 si\u0119 na' (sich entscheiden f\u00fcr). Im Deutschen werden verschiedene Pr\u00e4positionen verwendet, was das Lernen erschwert."},
      {"id": "gp_pn9", "question": "Jestem _____ ciebie z\u0142y.", "translation": "Ich bin b\u00f6se auf dich.", "options": ["na", "z", "od", "do"], "correct": "na", "explanation": "'Z\u0142y na + Akkusativ' (b\u00f6se auf jemanden). Polnische Adjektive mit emotionaler Bedeutung verwenden oft 'na': 'z\u0142y na kogo\u015b' (b\u00f6se auf jemanden), 'gotowy na co\u015b' (bereit f\u00fcr etwas), 'wra\u017cliwy na co\u015b' (empfindlich auf etwas). Im Deutschen stehen hier verschiedene Pr\u00e4positionen ('auf', 'f\u00fcr', 'gegen\u00fcber'). Diese Verbindungen m\u00fcssen als Einheiten gelernt werden."},
      {"id": "gp_pn10", "question": "Prosz\u0119 jedno piwo _____ wynos.", "translation": "Bitte ein Bier zum Mitnehmen.", "options": ["na", "do", "w", "za"], "correct": "na", "explanation": "'Na wynos' (zum Mitnehmen) ist eine feste Wendung, die besonders in Gastronomie und Alltag h\u00e4ufig vorkommt. Weitere feste Ausdr\u00fccke mit 'na': 'na pewno' (sicherlich), 'na przyk\u0142ad' (zum Beispiel), 'na razie' (vorl\u00e4ufig), 'na co dzie\u0144' (allt\u00e4glich). Diese Redewendungen sollten als Ganzes gelernt und nicht Wort f\u00fcr Wort \u00fcbersetzt werden."},
      {"id": "gp_pn11", "question": "_____ og\u00f3\u0142 jestem zadowolony z pracy.", "translation": "Im Allgemeinen bin ich zufrieden mit der Arbeit.", "options": ["Na", "W", "Do", "Z"], "correct": "Na", "explanation": "'Na og\u00f3\u0142' (im Allgemeinen) ist ein h\u00e4ufiger Ausdruck im formellen und informellen Polnisch. Weitere diskursive Wendungen mit 'na': 'na pocz\u0105tku' (am Anfang), 'na ko\u0144cu' (am Ende), 'na szcz\u0119\u015bcie' (zum Gl\u00fcck), 'na nieszcz\u0119\u015bcie' (leider/ungl\u00fccklicherweise). Diese Ausdr\u00fccke helfen, Texte und Gespr\u00e4che zu strukturieren, und kommen in der gesprochenen wie geschriebenen Sprache vor."},
      {"id": "gp_pn12", "question": "Poczekaj _____ mnie przy wej\u015bciu.", "translation": "Warte auf mich am Eingang.", "options": ["na", "za", "o", "do"], "correct": "na", "explanation": "'Poczeka\u0107 na + Akkusativ' (auf jemanden warten). Der perfektive Aspekt 'poczeka\u0107' (= abwarten/kurz warten) funktioniert genau wie 'czeka\u0107' mit derselben Pr\u00e4position 'na'. Beachten Sie das Pronomen: 'na mnie' (auf mich). Die Pronominalformen nach 'na': 'na mnie/ciebie/niego/ni\u0105/nas/was/nich'. Im Deutschen ist das Muster identisch: 'auf mich/dich/ihn/sie/uns/euch/sie'."},
      {"id": "gp_pn13", "question": "Mam alergi\u0119 _____ kurz.", "translation": "Ich habe eine Allergie gegen Staub.", "options": ["na", "do", "od", "z"], "correct": "na", "explanation": "'Alergia na + Akkusativ' (Allergie gegen etwas). Im Polnischen steht bei medizinischen und gesundheitlichen Ausdr\u00fccken oft 'na': 'chorowa\u0107 na gryp\u0119' (an Grippe erkrankt sein), 'cierpie\u0107 na bezsenno\u015b\u0107' (an Schlaflosigkeit leiden), 'umrze\u0107 na zawa\u0142' (an einem Herzinfarkt sterben). Im Deutschen stehen verschiedene Pr\u00e4positionen ('gegen', 'an', 'vor'), was Verwechslungen beg\u00fcnstigt."},
      {"id": "gp_pn14", "question": "To jest _____ sprzeda\u017c.", "translation": "Das ist zum Verkauf.", "options": ["na", "do", "w", "za"], "correct": "na", "explanation": "'Na sprzeda\u017c' (zum Verkauf) \u2013 'na + Akkusativ' dr\u00fcckt hier den Zweck aus. \u00c4hnliche Konstruktionen: 'na wynajem' (zur Miete), 'na wymian\u0119' (zum Tausch), 'na prezent' (als Geschenk). Im Deutschen werden unterschiedliche Konstruktionen verwendet ('zum', 'als', 'f\u00fcr'). Diese Zweckangabe mit 'na' ist im gesch\u00e4ftlichen und allt\u00e4glichen Polnisch sehr verbreitet."},
      {"id": "gp_pn15", "question": "Jad\u0119 _____ wie\u015b na weekend.", "translation": "Ich fahre \u00fcbers Wochenende aufs Land.", "options": ["na", "do", "w", "pod"], "correct": "na", "explanation": "'Na wie\u015b' (aufs Land) \u2013 bei bestimmten geographischen Konzepten steht 'na' statt 'do': 'na wie\u015b/na wsi' (aufs Land/auf dem Land), 'na wysp\u0119/na wyspie' (auf eine Insel/auf einer Insel), 'na pla\u017c\u0119/na pla\u017cy' (an den Strand/am Strand). Die Regel: offene Fl\u00e4chen und bestimmte Gebiete verwenden 'na', geschlossene R\u00e4ume verwenden 'w/do'. Dies hat keine direkte Parallele im Deutschen."}
    ]
  },
  {
    "id": "gp_prep_w",
    "key": "prepositions_w",
    "name": "Przyimek \u201ew/we\u201d (in)",
    "items": [
      {"id": "gp_pw1", "question": "Mieszkam _____ Berlinie od dziesi\u0119ciu lat.", "translation": "Ich wohne seit zehn Jahren in Berlin.", "options": ["w", "na", "do", "z"], "correct": "w", "explanation": "'W Berlinie' (in Berlin) \u2013 'w + Lokativ' f\u00fcr Aufenthaltsort in einer Stadt. Im Polnischen steht bei den meisten St\u00e4dten 'w': 'w Krakowie', 'w Warszawie', 'w Monachium', 'w Wiedniu'. Ausnahmen sind selten. Im Deutschen: 'in Berlin' (ohne Artikel). Die Lokativform des Stadtnamens muss dekliniert werden: 'Berlin \u2192 Berlinie', 'Krak\u00f3w \u2192 Krakowie'."},
      {"id": "gp_pw2", "question": "W\u0142\u00f3\u017c klucze _____ torb\u0119.", "translation": "Steck die Schl\u00fcssel in die Tasche.", "options": ["do", "w", "na", "pod"], "correct": "do", "explanation": "'Do torby' (in die Tasche) \u2013 f\u00fcr Richtung ins Innere verwendet das Polnische 'do + Genitiv', nicht 'w + Akkusativ'. Im Deutschen: 'in die Tasche' (Akkusativ f\u00fcr Richtung). Beachten Sie den Unterschied: 'w torbie' (in der Tasche, Lokativ f\u00fcr Lage) vs. 'do torby' (in die Tasche, Genitiv f\u00fcr Richtung). Im Deutschen wird beides mit 'in' ausgedr\u00fcckt."},
      {"id": "gp_pw3", "question": "Spotkanie jest _____ poniedzia\u0142ek o dziesi\u0105tej.", "translation": "Das Treffen ist am Montag um zehn.", "options": ["w", "na", "do", "za"], "correct": "w", "explanation": "'W poniedzia\u0142ek' (am Montag) \u2013 Wochentage stehen mit 'w + Akkusativ': 'w poniedzia\u0142ek', 'we wtorek' (beachte 'we' vor 'wt-'), 'w \u015brod\u0119', 'w czwartek', 'w pi\u0105tek', 'w sobot\u0119', 'w niedziel\u0119'. Im Deutschen: 'am Montag'. Der Akkusativ zeigt hier einen Zeitpunkt an, was f\u00fcr deutschsprachige Lernende ungewohnt sein kann."},
      {"id": "gp_pw4", "question": "Urodzi\u0142em si\u0119 _____ 1990 roku.", "translation": "Ich bin 1990 geboren.", "options": ["w", "na", "do", "z"], "correct": "w", "explanation": "'W 1990 roku' (im Jahr 1990) \u2013 Jahreszahlen stehen mit 'w + Lokativ': 'w tysi\u0105c dziewi\u0119\u0107set dziewi\u0119\u0107dziesi\u0105tym roku'. Im Alltag sagt man oft einfach 'w dziewi\u0119\u0107dziesi\u0105tym roku'. Im Deutschen: 'im Jahr 1990' oder einfach '1990'. Auch bei Monaten: 'w styczniu' (im Januar), 'w lutym' (im Februar). Die Lokativformen der Monatsnamen m\u00fcssen gelernt werden."},
      {"id": "gp_pw5", "question": "Dzieci bawi\u0105 si\u0119 _____ ogrodzie.", "translation": "Die Kinder spielen im Garten.", "options": ["w", "na", "do", "przy"], "correct": "w", "explanation": "'W ogrodzie' (im Garten) \u2013 'w + Lokativ' f\u00fcr umschlossene oder abgegrenzte Orte. Im Deutschen: 'im Garten'. Vergleichen Sie: 'w domu' (zu Hause/im Haus), 'w szkole' (in der Schule), 'w ko\u015bciele' (in der Kirche), 'w sklepie' (im Gesch\u00e4ft). Die Grundregel: 'w' f\u00fcr geschlossene R\u00e4ume und klar abgegrenzte Bereiche, 'na' f\u00fcr offene Fl\u00e4chen und bestimmte feste Ausdr\u00fccke."},
      {"id": "gp_pw6", "question": "No\u015b\u0119 okulary _____ czytania.", "translation": "Ich trage eine Lesebrille.", "options": ["do", "w", "na", "za"], "correct": "do", "explanation": "'Do czytania' (zum Lesen) \u2013 'do + Genitiv' dr\u00fcckt den Zweck aus. Im Deutschen: 'zum Lesen'. Weitere Beispiele: 'do picia' (zum Trinken), 'do jedzenia' (zum Essen), 'do u\u017cytku' (zum Gebrauch). Beachten Sie: Im Polnischen wird 'do' sowohl f\u00fcr Richtung ('do szko\u0142y' \u2013 zur Schule) als auch f\u00fcr Zweck ('do czytania' \u2013 zum Lesen) verwendet. Dies kann anfangs verwirrend sein."},
      {"id": "gp_pw7", "question": "_____ \u015brod\u0119 mam wolne.", "translation": "Am Mittwoch habe ich frei.", "options": ["W", "Na", "Do", "Ze"], "correct": "W", "explanation": "'W \u015brod\u0119' (am Mittwoch) \u2013 wie bei allen Wochentagen steht 'w + Akkusativ'. Beachten Sie: '\u015broda' (Mittwoch) ist weiblich, daher 'w \u015brod\u0119' (Akkusativ feminin). Die m\u00e4nnlichen Wochentage (poniedzia\u0142ek, czwartek, pi\u0105tek) bleiben im Akkusativ unver\u00e4ndert: 'w poniedzia\u0142ek', 'w czwartek', 'w pi\u0105tek'. Bei 'wtorek' wird 'w' zu 'we' erweitert: 'we wtorek'."},
      {"id": "gp_pw8", "question": "Pracuj\u0119 _____ firmie informatycznej.", "translation": "Ich arbeite in einer IT-Firma.", "options": ["w", "na", "do", "przy"], "correct": "w", "explanation": "'W firmie' (in einer Firma) \u2013 'w + Lokativ' bei Arbeitspl\u00e4tzen. Im Deutschen: 'in einer Firma'. Weitere Beispiele: 'w szpitalu' (im Krankenhaus), 'w banku' (in der Bank), 'w biurze' (im B\u00fcro). Ausnahme: 'na poczcie' (bei der Post), 'na uniwersytecie' (an der Universit\u00e4t) \u2013 diese verwenden 'na'. Die korrekte Zuordnung 'w' oder 'na' ist lexikalisch festgelegt."},
      {"id": "gp_pw9", "question": "Trzymam pieni\u0105dze _____ portfelu.", "translation": "Ich bewahre das Geld im Portemonnaie auf.", "options": ["w", "na", "do", "z"], "correct": "w", "explanation": "'W portfelu' (im Portemonnaie) \u2013 'w + Lokativ' f\u00fcr den Ort, an dem sich etwas befindet. Das Verb 'trzyma\u0107' (aufbewahren/halten) kann mit verschiedenen Pr\u00e4positionen stehen: 'w szufladzie' (in der Schublade), 'w szafie' (im Schrank), 'w kieszeni' (in der Tasche). Im Deutschen entspricht dies 'in + Dativ' bei Ruhelage. Die Lokativform 'portfelu' von 'portfel' folgt einer regelm\u00e4\u00dfigen Deklination."},
      {"id": "gp_pw10", "question": "Ta sukienka jest _____ kwiaty.", "translation": "Dieses Kleid hat ein Blumenmuster.", "options": ["w", "z", "na", "do"], "correct": "w", "explanation": "'W kwiaty' (mit Blumenmuster/gebl\u00fcmt) \u2013 'w + Akkusativ' beschreibt Muster und Designs. Weitere Beispiele: 'w paski' (gestreift), 'w krat\u0119' (kariert), 'w groszki' (gepunktet). Im Deutschen verwendet man Adjektive (gebl\u00fcmt, gestreift) oder 'mit + Dativ'. Diese polnische Konstruktion ist idiomatisch und besonders beim Einkaufen und bei Beschreibungen von Kleidung relevant."},
      {"id": "gp_pw11", "question": "Woda zamieni\u0142a si\u0119 _____ l\u00f3d.", "translation": "Das Wasser hat sich in Eis verwandelt.", "options": ["w", "na", "do", "z"], "correct": "w", "explanation": "'Zamieni\u0107 si\u0119 w + Akkusativ' (sich in etwas verwandeln). Im Polnischen dr\u00fcckt 'w' hier eine Transformation aus. Vergleichen Sie mit dem Deutschen 'in + Akkusativ' (sich in etwas verwandeln). Weitere Beispiele: 'zmieni\u0107 si\u0119 w motyla' (sich in einen Schmetterling verwandeln), 'zamieni\u0107 dom w muzeum' (das Haus in ein Museum umwandeln). Diese Bedeutung von 'w' ist f\u00fcr Deutschsprachige relativ intuitiv."},
      {"id": "gp_pw12", "question": "_____ nocy pada deszcz.", "translation": "In der Nacht regnet es.", "options": ["W", "Na", "Do", "Z"], "correct": "W", "explanation": "'W nocy' (in der Nacht) \u2013 Tageszeiten verwenden 'w + Lokativ': 'w nocy' (nachts), 'w dzie\u0144' (tags\u00fcber \u2013 Akkusativ, Ausnahme!). Aber: 'rano' (morgens \u2013 ohne Pr\u00e4position), 'wieczorem' (abends \u2013 Instrumental ohne Pr\u00e4position). Diese Unregelm\u00e4\u00dfigkeiten bei Tageszeiten m\u00fcssen als feste Ausdr\u00fccke gelernt werden, da es kein einheitliches Muster gibt."},
      {"id": "gp_pw13", "question": "Jestem dobry _____ matematyce.", "translation": "Ich bin gut in Mathematik.", "options": ["w", "z", "na", "do"], "correct": "w", "explanation": "'Dobry w + Lokativ' (gut in etwas). Im Polnischen steht bei F\u00e4higkeiten und Kompetenzen 'w': 'dobry w matematyce' (gut in Mathe), 's\u0142aby w j\u0119zykach' (schwach in Sprachen), 'bieg\u0142y w programowaniu' (versiert im Programmieren). Im Deutschen: 'gut in Mathematik' \u2013 die Konstruktion ist hier direkt vergleichbar. Bei sportlichen Disziplinen jedoch: 'dobry w pi\u0142ce no\u017cnej' (gut im Fu\u00dfball)."},
      {"id": "gp_pw14", "question": "Lubi\u0119 spacerowa\u0107 _____ deszczu.", "translation": "Ich spaziere gern im Regen.", "options": ["w", "na", "pod", "z"], "correct": "w", "explanation": "'W deszczu' (im Regen) \u2013 Wetterbedingungen verwenden 'w + Lokativ': 'w deszczu' (im Regen), 'w s\u0142o\u0144cu' (in der Sonne), 'w \u015bniegu' (im Schnee), 'w mgle' (im Nebel). Man kann auch 'na deszczu' sagen (ausgesetzt dem Regen). Der Unterschied: 'w deszczu' betont die Umgebung, 'na deszczu' die direkte Einwirkung. Im Deutschen wird meist 'im' verwendet."},
      {"id": "gp_pw15", "question": "Z\u0142o\u017cy\u0142em podanie _____ tej sprawie.", "translation": "Ich habe in dieser Angelegenheit einen Antrag gestellt.", "options": ["w", "na", "do", "o"], "correct": "w", "explanation": "'W tej sprawie' (in dieser Angelegenheit) \u2013 'w + Lokativ' bei abstrakten Bez\u00fcgen. Im formellen Polnisch sehr h\u00e4ufig: 'w tej kwestii' (in dieser Frage), 'w tym zakresie' (in diesem Bereich), 'w zwi\u0105zku z tym' (in diesem Zusammenhang), 'w tej chwili' (in diesem Moment). Im Deutschen entspricht das dem Muster 'in + Dativ' bei abstrakten Begriffen. Diese Wendungen sind im Gesch\u00e4fts- und Amtspolnisch unverzichtbar."}
    ]
  },
  {
    "id": "gp_prep_do",
    "key": "prepositions_do",
    "name": "Przyimek \u201edo\u201d (zu/nach/bis)",
    "items": [
      {"id": "gp_pd1", "question": "Jad\u0119 _____ Krakowa poci\u0105giem.", "translation": "Ich fahre mit dem Zug nach Krakau.", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'Do Krakowa' (nach Krakau) \u2013 'do + Genitiv' gibt das Ziel an. Bei St\u00e4dten und L\u00e4ndern steht immer 'do': 'do Warszawy' (nach Warschau), 'do Niemiec' (nach Deutschland), 'do Polski' (nach Polen). Im Deutschen: 'nach + Stadt/Land'. Beachten Sie: 'do' verlangt immer den Genitiv. Die Gegenrichtung verwendet 'z + Genitiv': 'z Krakowa do Warszawy' (von Krakau nach Warschau)."},
      {"id": "gp_pd2", "question": "Dzieci id\u0105 _____ szko\u0142y rano.", "translation": "Die Kinder gehen morgens in die Schule.", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'Do szko\u0142y' (in die Schule/zur Schule) \u2013 'do + Genitiv' f\u00fcr Richtung zu einem geschlossenen Ort. Im Deutschen: 'in die Schule'. Weitere Beispiele: 'do kina' (ins Kino), 'do sklepu' (ins Gesch\u00e4ft), 'do lekarza' (zum Arzt), 'do ko\u015bcio\u0142a' (in die Kirche). Merken Sie sich: F\u00fcr geschlossene Geb\u00e4ude und Orte steht im Polnischen meist 'do' (nicht 'do' bei 'na'-Orten wie 'na poczt\u0119')."},
      {"id": "gp_pd3", "question": "Pracuj\u0119 od \u00f3smej _____ szesnastej.", "translation": "Ich arbeite von acht bis sechzehn Uhr.", "options": ["do", "na", "w", "za"], "correct": "do", "explanation": "'Od... do...' (von... bis...) \u2013 'do + Genitiv' f\u00fcr zeitliche Begrenzung. Im Deutschen: 'von... bis...'. Weitere Beispiele: 'od poniedzia\u0142ku do pi\u0105tku' (von Montag bis Freitag), 'od rana do wieczora' (von morgens bis abends), 'od stycznia do marca' (von Januar bis M\u00e4rz). Diese Konstruktion ist dem Deutschen sehr \u00e4hnlich und daher f\u00fcr deutschsprachige Lernende leicht zu merken."},
      {"id": "gp_pd4", "question": "Ta ksi\u0105\u017cka nie jest _____ dzieci.", "translation": "Dieses Buch ist nicht f\u00fcr Kinder.", "options": ["dla", "do", "na", "z"], "correct": "dla", "explanation": "'Dla dzieci' (f\u00fcr Kinder) \u2013 f\u00fcr den Empf\u00e4nger/die Zielgruppe steht 'dla + Genitiv', nicht 'do'. Im Deutschen: 'f\u00fcr + Akkusativ'. Beachten Sie den Unterschied zwischen 'dla' (f\u00fcr eine Person/Zielgruppe) und 'do' (f\u00fcr einen Zweck): 'prezent dla mamy' (Geschenk f\u00fcr Mama) vs. 'do czytania' (zum Lesen). Dies ist ein h\u00e4ufiger Fehler bei deutschsprachigen Lernenden."},
      {"id": "gp_pd5", "question": "Podejd\u017a _____ okna i otw\u00f3rz je.", "translation": "Geh zum Fenster und \u00f6ffne es.", "options": ["do", "na", "w", "pod"], "correct": "do", "explanation": "'Do okna' (zum Fenster) \u2013 'do + Genitiv' f\u00fcr Ann\u00e4herung an einen Punkt. Im Deutschen: 'zum Fenster'. Verben der Bewegung mit 'do': 'podej\u015b\u0107 do' (herangehen an), 'podjecha\u0107 do' (heranfahren an), 'doj\u015b\u0107 do' (gelangen zu), 'doi\u015b\u0107 do wniosku' (zu einem Schluss kommen). Diese Verben mit dem Pr\u00e4fix 'do-' und der Pr\u00e4position 'do' sind im Polnischen sehr produktiv und h\u00e4ufig."},
      {"id": "gp_pd6", "question": "Mam _____ ciebie pytanie.", "translation": "Ich habe eine Frage an dich.", "options": ["do", "dla", "na", "z"], "correct": "do", "explanation": "'Do ciebie' (an dich) \u2013 'do + Genitiv' zeigt hier den Adressaten. Im Deutschen: 'an dich' oder 'f\u00fcr dich'. \u00c4hnliche Konstruktionen: 'list do matki' (Brief an die Mutter), 'telefon do szefa' (Anruf beim Chef), 'pro\u015bba do was' (Bitte an euch). Im formellen Kontext wird 'do' oft f\u00fcr offizielle Kommunikation verwendet: 'pismo do urz\u0119du' (Schreiben an das Amt)."},
      {"id": "gp_pd7", "question": "Woda jest _____ picia, nie do k\u0105pieli.", "translation": "Das Wasser ist zum Trinken, nicht zum Baden.", "options": ["do", "na", "dla", "w"], "correct": "do", "explanation": "'Do picia' (zum Trinken) \u2013 'do + Genitiv' f\u00fcr Verwendungszweck. Im Deutschen: 'zum + Infinitiv'. Diese Konstruktion ist produktiv: 'do jedzenia' (zum Essen), 'do spania' (zum Schlafen), 'do prania' (zum Waschen), 'do u\u017cytku' (zum Gebrauch). Im Polnischen steht hier der Genitiv des Verbalsubstantivs, im Deutschen der substantivierte Infinitiv."},
      {"id": "gp_pd8", "question": "Dodaj soli _____ smaku.", "translation": "F\u00fcge Salz nach Geschmack hinzu.", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'Do smaku' (nach Geschmack) ist eine feste Wendung in der Kochanleitung. 'Do' hat hier eine abstrakte Bedeutung 'bis zu/entsprechend'. Weitere kulinarische Wendungen: 'doprawi\u0107 do smaku' (nach Geschmack w\u00fcrzen), 'zagotowa\u0107 do wrzenia' (zum Kochen bringen). Diese spezialisierten Ausdr\u00fccke sind im Alltag n\u00fctzlich und zeigen die Vielseitigkeit der Pr\u00e4position 'do' im Polnischen."},
      {"id": "gp_pd9", "question": "T\u0119skni\u0119 _____ domu.", "translation": "Ich habe Heimweh.", "options": ["do", "za", "na", "z"], "correct": "do", "explanation": "'T\u0119skni\u0107 do + Genitiv' oder 'za + Instrumental' (sich sehnen nach). Beide Formen sind korrekt, 'do' ist formeller und literarischer: 't\u0119skni\u0119 do domu' (w\u00f6rtl.: ich sehne mich zum Haus). Im Alltag ist 't\u0119skni\u0119 za domem' (Instrumental) h\u00e4ufiger. Im Deutschen: 'sich sehnen nach + Dativ'. Beachten Sie diesen Doppelgebrauch, er ist eine Besonderheit des Polnischen, die beim Lesen und Schreiben begegnet."},
      {"id": "gp_pd10", "question": "Jestem podobny _____ ojca.", "translation": "Ich sehe meinem Vater \u00e4hnlich.", "options": ["do", "z", "na", "od"], "correct": "do", "explanation": "'Podobny do + Genitiv' (\u00e4hnlich wie jemand/etwas). Im Deutschen: '\u00e4hnlich + Dativ'. Polnische Adjektive mit 'do': 'podobny do' (\u00e4hnlich), 'przyzwyczajony do' (gew\u00f6hnt an), 'zdolny do' (f\u00e4hig zu), 'gotowy do' (bereit zu). Diese Rektion weicht oft vom Deutschen ab, was zu Fehlern f\u00fchrt. Die korrekte Pr\u00e4position muss zusammen mit dem Adjektiv gelernt werden."},
      {"id": "gp_pd11", "question": "Przyjed\u017a _____ mnie na obiad.", "translation": "Komm zum Mittagessen zu mir.", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'Do mnie' (zu mir) \u2013 'do + Genitiv' bei Personen f\u00fcr Richtung. Im Deutschen: 'zu mir'. Die Pronominalformen: 'do mnie' (zu mir), 'do ciebie' (zu dir), 'do niego' (zu ihm), 'do niej' (zu ihr), 'do nas' (zu uns), 'do was' (zu euch), 'do nich' (zu ihnen). Beachten Sie: nach Pr\u00e4positionen verwenden die Pronomen der 3. Person die n-Formen: 'niego/niej/nich' statt 'jego/jej/ich'."},
      {"id": "gp_pd12", "question": "Nie mam _____ tego cierpliwo\u015bci.", "translation": "Ich habe keine Geduld daf\u00fcr.", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'Do tego' (daf\u00fcr/dazu) \u2013 'do + Genitiv' bei abstraktem Bezug. Im Deutschen: 'daf\u00fcr/dazu'. Weitere Beispiele: 'do czego to prowadzi?' (wozu f\u00fchrt das?), 'nie jestem do tego zdolny' (ich bin dazu nicht f\u00e4hig). Die Konstruktionen mit 'do' + Demonstrativpronomen im Genitiv ('tego/tej/tych') sind im Polnischen sehr h\u00e4ufig und entsprechen den deutschen da-Komposita ('daf\u00fcr, dazu, davon')."},
      {"id": "gp_pd13", "question": "Samoch\u00f3d jest _____ naprawy.", "translation": "Das Auto muss repariert werden.", "options": ["do", "na", "w", "za"], "correct": "do", "explanation": "'Do naprawy' (zur Reparatur/reparaturbed\u00fcrftig) \u2013 'do + Genitiv' kann Notwendigkeit ausdr\u00fccken. Im Deutschen: 'Das Auto muss repariert werden' oder 'Das Auto ist reparaturbed\u00fcrftig'. \u00c4hnlich: 'do wymiany' (zum Austausch), 'do wyrzucenia' (zum Wegwerfen), 'do zrobienia' (zu erledigen). Diese Konstruktion ist im Alltag und in der Werkstatt, im B\u00fcro usw. sehr praktisch."},
      {"id": "gp_pd14", "question": "Przylecieli _____ Niemiec wczoraj wieczorem.", "translation": "Sie sind gestern Abend aus Deutschland angekommen.", "options": ["z", "do", "od", "w"], "correct": "z", "explanation": "'Z Niemiec' (aus Deutschland) \u2013 Herkunft bei L\u00e4ndern steht mit 'z + Genitiv'. Im Deutschen: 'aus Deutschland'. Beachten Sie das Gegenpaar: 'do Niemiec' (nach Deutschland) \u2194 'z Niemiec' (aus Deutschland). 'Niemcy' (Deutschland) hat den Genitiv 'Niemiec'. Dieses Paar 'do/z' ist die Grundkonstruktion f\u00fcr alle L\u00e4ndernamen und St\u00e4dte und sollte fr\u00fch gelernt werden."},
      {"id": "gp_pd15", "question": "Pracuj\u0119 od \u00f3smej _____ czwartej.", "translation": "Ich arbeite von acht bis vier.", "options": ["do", "na", "w", "za"], "correct": "do", "explanation": "'Od \u00f3smej do czwartej' (von acht bis vier) \u2013 'do + Genitiv' f\u00fcr den Endpunkt einer Zeitspanne. Im Deutschen: 'von... bis...'. Diese Uhrzeitangabe ist eine der grundlegendsten Konstruktionen im Polnischen. Die Ordnungszahlen stehen im Genitiv Femininum: 'do czwartej' (bis vier), 'do si\u00f3dmej' (bis sieben). Im Alltag und Beruf ist 'od...do...' bei Arbeitszeiten und \u00d6ffnungszeiten unverzichtbar."}
    ]
  },
  {
    "id": "gp_prep_przy",
    "key": "prepositions_przy",
    "name": "Przyimek \u201eprzy\u201d (bei/an)",
    "items": [
      {"id": "gp_pp1", "question": "Siedz\u0119 _____ stole i jem obiad.", "translation": "Ich sitze am Tisch und esse Mittagessen.", "options": ["przy", "na", "w", "pod"], "correct": "przy", "explanation": "'Przy stole' (am Tisch) \u2013 'przy + Lokativ' f\u00fcr N\u00e4he/unmittelbare Position. Im Deutschen: 'am Tisch' ('an dem Tisch'). 'Przy' dr\u00fcckt aus, dass man sich direkt neben etwas befindet: 'przy oknie' (am Fenster), 'przy drzwiach' (an der T\u00fcr), 'przy komputerze' (am Computer). Die Grundbedeutung ist immer 'in unmittelbarer N\u00e4he von'. F\u00fcr Deutschsprachige: 'bei/an + Dativ'."},
      {"id": "gp_pp2", "question": "Spotkajmy si\u0119 _____ wej\u015bciu do kina.", "translation": "Treffen wir uns am Eingang zum Kino.", "options": ["przy", "na", "w", "do"], "correct": "przy", "explanation": "'Przy wej\u015bciu' (am Eingang) \u2013 'przy + Lokativ' f\u00fcr Treffpunkte und Orientierungspunkte. Im Deutschen: 'am/beim Eingang'. Im Polnischen wird 'przy' oft f\u00fcr Verabredungen genutzt: 'przy fontannie' (am Brunnen), 'przy pomniku' (am Denkmal), 'przy przystanku' (an der Haltestelle). Die Lokativform des Neutrums: 'wej\u015bcie \u2192 wej\u015bciu'. 'Przy' ist die nat\u00fcrliche Pr\u00e4position f\u00fcr Treffpunkte."},
      {"id": "gp_pp3", "question": "_____ okazji chcia\u0142bym co\u015b powiedzie\u0107.", "translation": "Bei dieser Gelegenheit m\u00f6chte ich etwas sagen.", "options": ["Przy", "Na", "W", "Z"], "correct": "Przy", "explanation": "'Przy okazji' (bei Gelegenheit/\u00fcbrigens) ist eine h\u00e4ufige diskursive Wendung. Im Deutschen: 'bei der Gelegenheit' oder '\u00fcbrigens'. Weitere abstrakte Verwendungen: 'przy odrobinie szcz\u0119\u015bcia' (mit etwas Gl\u00fcck), 'przy dobrej woli' (bei gutem Willen), 'przy pomocy' (mit Hilfe von). 'Przy' in abstrakten Kontexten entspricht dem deutschen 'bei' und wird im formellen und informellen Polnisch gleicherma\u00dfen verwendet."},
      {"id": "gp_pp4", "question": "Nie m\u00f3w tak _____ dzieciach.", "translation": "Sprich nicht so vor den Kindern.", "options": ["przy", "o", "z", "do"], "correct": "przy", "explanation": "'Przy dzieciach' (vor/bei den Kindern = in ihrer Anwesenheit). Im Deutschen: 'vor den Kindern' oder 'in Gegenwart der Kinder'. Diese Bedeutung von 'przy' \u2013 die Anwesenheit einer Person \u2013 ist f\u00fcr Deutschsprachige manchmal \u00fcberraschend. Weitere Beispiele: 'przy \u015bwiadkach' (vor Zeugen), 'przy go\u015bciach' (vor G\u00e4sten). 'Przy' dr\u00fcckt hier nicht Ort, sondern Anwesenheit aus."},
      {"id": "gp_pp5", "question": "Zawsze s\u0142ucham muzyki _____ pracy.", "translation": "Ich h\u00f6re immer Musik bei der Arbeit.", "options": ["przy", "w", "na", "do"], "correct": "przy", "explanation": "'Przy pracy' (bei der Arbeit) \u2013 'przy + Lokativ' kann auch 'w\u00e4hrend einer T\u00e4tigkeit' bedeuten. Im Deutschen: 'bei der Arbeit'. \u00c4hnliche Ausdr\u00fccke: 'przy jedzeniu' (beim Essen), 'przy gotowaniu' (beim Kochen), 'przy czytaniu' (beim Lesen). Diese Konstruktion entspricht dem deutschen 'beim + substantiviertem Infinitiv' und ist im Alltag sehr h\u00e4ufig verwendbar."},
      {"id": "gp_pp6", "question": "Apteka jest _____ szpitala.", "translation": "Die Apotheke ist beim Krankenhaus.", "options": ["przy", "w", "na", "do"], "correct": "przy", "explanation": "'Przy szpitalu' (beim Krankenhaus) \u2013 'przy + Lokativ' zeigt r\u00e4umliche N\u00e4he. Im Deutschen: 'beim Krankenhaus'. 'Przy' wird h\u00e4ufig bei Ortsangaben verwendet, wenn zwei Geb\u00e4ude oder Orte nahe beieinander liegen: 'sklep przy ulicy G\u0142\u00f3wnej' (Gesch\u00e4ft an der Hauptstra\u00dfe), 'kawiarnia przy rynku' (Caf\u00e9 am Marktplatz). Die Lokativform 'szpitalu' folgt dem Maskulinum-Muster."},
      {"id": "gp_pp7", "question": "Mieszkam _____ rodzic\u00f3w.", "translation": "Ich wohne bei meinen Eltern.", "options": ["u", "przy", "z", "do"], "correct": "u", "explanation": "'U rodzic\u00f3w' (bei den Eltern) \u2013 wenn man bei Personen wohnt, steht 'u + Genitiv', nicht 'przy'. Im Deutschen: 'bei den Eltern'. Vergleichen Sie: 'przy rodzicach' (in Anwesenheit der Eltern) vs. 'u rodzic\u00f3w' (bei den Eltern wohnend). Weitere Beispiele: 'u przyjaci\u00f3\u0142' (bei Freunden), 'u lekarza' (beim Arzt = in seiner Praxis). 'U' ist die korrekte Wahl f\u00fcr Personen als Gastgeber oder Dienstleister."},
      {"id": "gp_pp8", "question": "_____ tej temperaturze woda zamarza.", "translation": "Bei dieser Temperatur gefriert Wasser.", "options": ["Przy", "W", "Na", "Z"], "correct": "Przy", "explanation": "'Przy tej temperaturze' (bei dieser Temperatur) \u2013 'przy + Lokativ' dr\u00fcckt Bedingungen aus. Im Deutschen: 'bei + Dativ'. Im wissenschaftlichen und technischen Kontext: 'przy ci\u015bnieniu' (bei Druck), 'przy pr\u0119dko\u015bci' (bei Geschwindigkeit), 'przy wysoko\u015bci' (bei H\u00f6he). Diese konditionale Verwendung von 'przy' ist dem deutschen 'bei' in technischen Kontexten sehr \u00e4hnlich."},
      {"id": "gp_pp9", "question": "Stoj\u0119 _____ kasie i czekam.", "translation": "Ich stehe an der Kasse und warte.", "options": ["przy", "na", "w", "do"], "correct": "przy", "explanation": "'Przy kasie' (an der Kasse) \u2013 'przy + Lokativ' f\u00fcr die Position in der Warteschlange. Im Deutschen: 'an der Kasse'. Im Einkaufskontext h\u00e4ufig: 'przy ladzie' (am Tresen), 'przy wej\u015bciu' (am Eingang), 'przy wyj\u015bciu' (am Ausgang). Die Lokativform 'kasie' kommt von 'kasa' (Kasse). 'Przy' zeigt hier die unmittelbare N\u00e4he zum Objekt, an dem man steht oder arbeitet."},
      {"id": "gp_pp10", "question": "Zapomnia\u0142em portfela _____ sobie.", "translation": "Ich habe keine Geldb\u00f6rse bei mir.", "options": ["przy", "z", "na", "w"], "correct": "przy", "explanation": "'Przy sobie' (bei sich) \u2013 'przy + Lokativ' des Reflexivpronomens 'siebie/sobie'. Im Deutschen: 'bei sich haben'. Die Wendung 'mie\u0107 przy sobie' (bei sich haben) ist im Alltag unverzichtbar: 'Masz przy sobie dokumenty?' (Hast du Dokumente bei dir?). Weitere Formen: 'przy mnie' (bei mir), 'przy tobie' (bei dir). Diese Konstruktion ist direkt vom Deutschen \u00fcbertragbar."},
      {"id": "gp_pp11", "question": "Nie zachowuj si\u0119 tak _____ ludziach.", "translation": "Benimm dich nicht so vor Leuten.", "options": ["przy", "z", "na", "do"], "correct": "przy", "explanation": "'Przy ludziach' (vor Leuten/in Gesellschaft) \u2013 'przy + Lokativ' f\u00fcr Anwesenheit anderer Menschen. Im Deutschen: 'vor Leuten'. Diese soziale Bedeutung von 'przy' ist besonders wichtig: 'zachowywa\u0107 si\u0119 przy go\u015bciach' (sich vor G\u00e4sten benehmen), 'm\u00f3wi\u0107 przy obcych' (vor Fremden sprechen). Die Lokativform Plural 'ludziach' (von 'ludzie') ist unregelm\u00e4\u00dfig und muss auswendig gelernt werden."},
      {"id": "gp_pp12", "question": "Hotel jest _____ samej pla\u017cy.", "translation": "Das Hotel ist direkt am Strand.", "options": ["przy", "na", "w", "do"], "correct": "przy", "explanation": "'Przy samej pla\u017cy' (direkt am Strand) \u2013 'przy + Lokativ' mit dem Verst\u00e4rker 'sam/sama/samo' (selbst/direkt) betont extreme N\u00e4he. Im Deutschen: 'direkt am Strand'. Diese Konstruktion ist im Tourismus und bei Immobilienbeschreibungen h\u00e4ufig: 'przy samym morzu' (direkt am Meer), 'przy samej granicy' (direkt an der Grenze). Der Verst\u00e4rker 'sam' wird hier vor das Substantiv gestellt."},
      {"id": "gp_pp13", "question": "Zostawi\u0142em klucze _____ recepcji.", "translation": "Ich habe die Schl\u00fcssel an der Rezeption gelassen.", "options": ["na", "przy", "w", "do"], "correct": "na", "explanation": "'Na recepcji' (an der Rezeption) \u2013 hier steht 'na + Lokativ', nicht 'przy'. Im Hotelkontext: 'na recepcji' ist idiomatisch korrekt. Vergleichen Sie: 'przy recepcji' w\u00fcrde 'neben der Rezeption (stehend)' bedeuten, w\u00e4hrend 'na recepcji' 'am Rezeptionsschalter (beim Dienst)' hei\u00dft. Diese Feinheiten zwischen 'na' und 'przy' sind kontextabh\u00e4ngig und erfordern \u00dcbung im allt\u00e4glichen Gebrauch."},
      {"id": "gp_pp14", "question": "_____ kawie porozmawiamy o szczeg\u00f3\u0142ach.", "translation": "Bei einem Kaffee besprechen wir die Details.", "options": ["Przy", "Na", "Z", "W"], "correct": "Przy", "explanation": "'Przy kawie' (bei einem Kaffee) \u2013 'przy + Lokativ' als gesellschaftlicher Rahmen. Im Deutschen: 'bei einem Kaffee'. Weitere gesellige Wendungen: 'przy herbacie' (bei einem Tee), 'przy piwie' (bei einem Bier), 'przy obiedzie' (beim Mittagessen), 'przy kolacji' (beim Abendessen). Diese Konstruktionen verbinden den Ort/die Aktivit\u00e4t mit sozialer Interaktion und sind im polnischen Alltag allgegenw\u00e4rtig."},
      {"id": "gp_pp15", "question": "Przysz\u0142am _____ pie\u015bni\u0105 na ustach.", "translation": "Ich kam mit einem Lied auf den Lippen.", "options": ["z", "przy", "na", "w"], "correct": "z", "explanation": "'Z pie\u015bni\u0105 na ustach' (mit einem Lied auf den Lippen) \u2013 hier steht 'z + Instrumental', nicht 'przy'. Diese poetische Wendung zeigt den Unterschied: 'z' dr\u00fcckt Begleitung aus (mit etwas kommen), w\u00e4hrend 'przy' N\u00e4he oder Anwesenheit bedeutet. Im Deutschen: 'mit einem Lied auf den Lippen'. Solche literarischen Wendungen bereichern den Wortschatz und zeigen die feinen Unterschiede zwischen \u00e4hnlichen Pr\u00e4positionen."}
    ]
  }
]

data.extend(new_cats)

# Validate
ids = set()
dupes = []
for cat in data:
    for item in cat['items']:
        if item['id'] in ids:
            dupes.append(item['id'])
        ids.add(item['id'])

short = [item['id'] for cat in new_cats for item in cat['items'] if len(item['explanation']) < 200]
no_blank = [item['id'] for cat in new_cats for item in cat['items'] if '_____' not in item['question']]

with open(f, 'w', encoding='utf-8') as fout:
    json.dump(data, fout, ensure_ascii=False, indent=2)

print(f"After: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")
print(f"Duplicate IDs: {dupes if dupes else 'None'}")
print(f"Short explanations: {short if short else 'None'}")
print(f"Missing blanks: {no_blank if no_blank else 'None'}")
print(f"Added: {[c['key'] for c in new_cats]}")
