#!/usr/bin/env python3
import json, os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
f = os.path.join(base, 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json')
data = json.load(open(f, encoding='utf-8'))
print(f"Before: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")

new_cats = [
  {
    "id": "gp_adj_decl",
    "key": "adjective_declension",
    "name": "Odmiana przymiotnik\u00f3w (Adjektivdeklination)",
    "items": [
      {"id": "gp_ad1", "question": "To jest _____ ksi\u0105\u017cka.", "translation": "Das ist ein interessantes Buch.", "options": ["ciekawa", "ciekawy", "ciekawe", "ciekawi"], "correct": "ciekawa", "explanation": "'Ciekawa ksi\u0105\u017cka' (interessantes Buch) \u2013 'ksi\u0105\u017cka' ist feminin, daher die feminine Endung '-a'. Die Grundendungen der Adjektive im Nominativ: '-y/-i' (mask.), '-a' (fem.), '-e' (neutr.). Im Deutschen: 'ein interessantes Buch' (Neutrum!). Beachten Sie: 'Buch' ist im Polnischen feminin ('ksi\u0105\u017cka'), im Deutschen Neutrum ('das Buch'). Die Genusunterschiede zwischen den Sprachen erfordern besondere Aufmerksamkeit bei der Adjektivkongruenz."},
      {"id": "gp_ad2", "question": "Widz\u0119 _____ samoch\u00f3d.", "translation": "Ich sehe ein neues Auto.", "options": ["nowy", "now\u0105", "nowe", "nowego"], "correct": "nowy", "explanation": "'Nowy samoch\u00f3d' (neues Auto, Akk.) \u2013 bei unbelebten Maskulina ist der Akkusativ = Nominativ: 'nowy samoch\u00f3d'. Bei belebten Maskulina w\u00e4re es 'nowego psa' (Akk. = Gen.). Diese Unterscheidung belebt/unbelebt im Akkusativ Maskulin ist eine Kernregel des Polnischen, die im Deutschen nicht existiert. Merkhilfe: Tiere und Menschen = Genitiv im Akkusativ, Dinge = Nominativ im Akkusativ."},
      {"id": "gp_ad3", "question": "Rozmawiam z _____ koleg\u0105.", "translation": "Ich spreche mit einem polnischen Kollegen.", "options": ["polskim", "polski", "polsk\u0105", "polskiego"], "correct": "polskim", "explanation": "'Z polskim koleg\u0105' (mit einem polnischen Kollegen) \u2013 'z + Instrumental'. Adjektivendung im Instrumental maskulin: '-im/-ym'. Die Instrumentalendungen: '-ym/-im' (mask./neutr.), '-\u0105' (fem.). Im Deutschen: 'mit einem polnischen Kollegen' (Dativ). Die Regel f\u00fcr '-im' vs. '-ym': nach weichen Konsonanten und k, g steht '-im' (polskim), sonst '-ym' (nowym). Diese Lautregel gilt f\u00fcr alle Kasus."},
      {"id": "gp_ad4", "question": "Mieszkam w _____ mie\u015bcie.", "translation": "Ich wohne in einer gro\u00dfen Stadt.", "options": ["du\u017cym", "du\u017ca", "du\u017ce", "du\u017cych"], "correct": "du\u017cym", "explanation": "'W du\u017cym mie\u015bcie' (in einer gro\u00dfen Stadt) \u2013 'w + Lokativ'. Adjektiv im Lokativ Neutrum: '-ym/-im'. 'Miasto' (Stadt) ist Neutrum. Im Deutschen: 'in einer gro\u00dfen Stadt' (Femininum \u2013 Dativ). Die Lokativformen sind im Maskulinum und Neutrum identisch: 'w du\u017cym domu' (mask.) = 'w du\u017cym mie\u015bcie' (neutr.). Nur das Femininum hat eine andere Form: 'w du\u017cej kuchni' (in einer gro\u00dfen K\u00fcche)."},
      {"id": "gp_ad5", "question": "Nie ma tu _____ restauracji.", "translation": "Es gibt hier kein gutes Restaurant.", "options": ["dobrej", "dobra", "dobre", "dobrych"], "correct": "dobrej", "explanation": "'Dobrej restauracji' (Gen. fem.) \u2013 'nie ma + Genitiv' (es gibt nicht). Die Adjektivendung im Genitiv feminin ist '-ej'. Im Deutschen: 'kein gutes Restaurant' (Akkusativ). Im Polnischen steht nach verneintem 'ma\u0107/by\u0107' immer der Genitiv. Die Genitivformen der Adjektive: '-ego' (mask./neutr.), '-ej' (fem.), '-ych/-ich' (Plural). Diese Formen sind sehr h\u00e4ufig, da der Genitiv der meist gebrauchte Kasus im Polnischen ist."},
      {"id": "gp_ad6", "question": "Dam prezent _____ siostrze.", "translation": "Ich gebe meiner \u00e4lteren Schwester ein Geschenk.", "options": ["starszej", "starsza", "starszym", "starsze"], "correct": "starszej", "explanation": "'Starszej siostrze' (der \u00e4lteren Schwester, Dat. fem.) \u2013 die Dativendung feminin ist '-ej', identisch mit dem Genitiv feminin. Im Deutschen: 'meiner \u00e4lteren Schwester' (Dativ). Diese \u00dcbereinstimmung Gen. = Dat. = Lok. im Femininum vereinfacht das Lernen erheblich: 'dobrej' kann Genitiv, Dativ oder Lokativ sein. Der Kontext und die Pr\u00e4position verraten den genauen Kasus."},
      {"id": "gp_ad7", "question": "Lubi\u0119 _____ kaw\u0119.", "translation": "Ich mag starken Kaffee.", "options": ["mocn\u0105", "mocna", "mocny", "mocne"], "correct": "mocn\u0105", "explanation": "'Mocn\u0105 kaw\u0119' (starken Kaffee, Akk. fem.) \u2013 die Akkusativendung feminin ist '-\u0105'. Im Deutschen: 'starken Kaffee' (Akkusativ mask. \u2013 'Kaffee' ist maskulin). Im Polnischen ist 'kawa' feminin. Die femininen Adjektivendungen: '-a' (Nom.), '-ej' (Gen./Dat./Lok.), '-\u0105' (Akk./Instr.). Im Femininum stimmen Akkusativ und Instrumental \u00fcberein, was eine weitere Vereinfachung ist."},
      {"id": "gp_ad8", "question": "To s\u0105 _____ ludzie.", "translation": "Das sind nette Leute.", "options": ["mili", "mi\u0142e", "mi\u0142y", "mi\u0142ych"], "correct": "mili", "explanation": "'Mili ludzie' (nette Leute, Nom. Pl. m\u00e4nnl.-pers.) \u2013 im Polnischen gibt es zwei Pluralformen: m\u00e4nnlich-personal ('-i/-y') und nicht-m\u00e4nnlich-personal ('-e'). 'Ludzie' (Leute) ist m\u00e4nnlich-personal, daher 'mili'. Bei 'mi\u0142y \u2192 mili' ver\u00e4ndert sich der Stammkonsonant (\u0142 \u2192 l) wegen der Erweichung. Im Deutschen: 'nette Leute' \u2013 ohne Genusunterscheidung im Plural. Diese polnische Pluraldifferenzierung ist f\u00fcr Deutschsprachige v\u00f6llig neu."},
      {"id": "gp_ad9", "question": "Nie mam _____ pomys\u0142\u00f3w.", "translation": "Ich habe keine neuen Ideen.", "options": ["nowych", "nowe", "nowi", "nowym"], "correct": "nowych", "explanation": "'Nowych pomys\u0142\u00f3w' (neuer Ideen, Gen. Pl.) \u2013 nach verneinter 'mie\u0107' steht der Genitiv. Die Genitivendung Plural der Adjektive ist immer '-ych/-ich': 'nowych' (neuer), 'dobrych' (guter), 'polskich' (polnischer). Diese Endung ist f\u00fcr alle Geschlechter im Plural gleich! Im Deutschen: 'keine neuen Ideen' (Akkusativ). Die Einheitlichkeit der Genitiv-Plural-Endung '-ych/-ich' ist eine willkommene Vereinfachung."},
      {"id": "gp_ad10", "question": "Jedziem _____ drog\u0105.", "translation": "Wir fahren auf einer schmalen Stra\u00dfe.", "options": ["w\u0105sk\u0105", "w\u0105ski", "w\u0105skie", "w\u0105skim"], "correct": "w\u0105sk\u0105", "explanation": "'W\u0105sk\u0105 drog\u0105' (auf einer schmalen Stra\u00dfe, Instr. fem.) \u2013 ohne Pr\u00e4position bedeutet der Instrumental hier 'auf/entlang'. Die Instrumentalendung feminin bei Adjektiven: '-\u0105'. Im Deutschen: 'auf einer schmalen Stra\u00dfe' (Dativ mit Pr\u00e4position). Der pr\u00e4positionslose Instrumental f\u00fcr Wege und Mittel ist eine Besonderheit des Polnischen: 'jecha\u0107 drog\u0105' (eine Stra\u00dfe entlangfahren), 'p\u0142yn\u0105\u0107 rzek\u0105' (einen Fluss entlangfahren)."},
      {"id": "gp_ad11", "question": "Przeczyta\u0142em ten tekst w _____ j\u0119zyku.", "translation": "Ich habe diesen Text in einer fremden Sprache gelesen.", "options": ["obcym", "obcy", "obca", "obce"], "correct": "obcym", "explanation": "'W obcym j\u0119zyku' (in einer fremden Sprache, Lok. mask.) \u2013 Adjektivendung im Lokativ maskulin: '-ym/-im'. 'J\u0119zyk' (Sprache) ist maskulin. Im Deutschen: 'in einer fremden Sprache' (Dativ fem.). Die Lokativendungen Maskulin/Neutrum sind identisch: '-ym/-im'. Die Grundregel: nach harten Konsonanten '-ym', nach weichen und k/g '-im'. Diese Aufteilung zieht sich durch die gesamte Adjektivdeklination."},
      {"id": "gp_ad12", "question": "Szukam _____ mieszkania.", "translation": "Ich suche eine g\u00fcnstige Wohnung.", "options": ["taniego", "tanie", "tania", "tanim"], "correct": "taniego", "explanation": "'Taniego mieszkania' (einer g\u00fcnstigen Wohnung, Gen. neutr.) \u2013 'szuka\u0107 + Genitiv' (suchen). Die Genitivendung mask./neutr. ist '-ego': 'taniego', 'nowego', 'dobrego'. Im Deutschen: 'eine g\u00fcnstige Wohnung' (Akkusativ). Beachten Sie: 'szuka\u0107' verlangt im Polnischen den Genitiv, 'suchen' im Deutschen den Akkusativ. Solche Rektionsunterschiede sind eine h\u00e4ufige Fehlerquelle f\u00fcr deutschsprachige Lernende."},
      {"id": "gp_ad13", "question": "Daj _____ dzieciom wi\u0119cej czasu.", "translation": "Gib den kleinen Kindern mehr Zeit.", "options": ["ma\u0142ym", "ma\u0142e", "mali", "ma\u0142ych"], "correct": "ma\u0142ym", "explanation": "'Ma\u0142ym dzieciom' (den kleinen Kindern, Dat. Pl.) \u2013 die Dativendung Plural ist '-ym/-im' f\u00fcr alle Geschlechter. 'Dzieci' (Kinder) ist nicht-m\u00e4nnlich-personal. Die Pluraldeklination der Adjektive: Nom. '-i/-e', Gen./Lok. '-ych/-ich', Dat. '-ym/-im', Akk. '-ych/-ich (belebt)/-e (unbelebt)', Instr. '-ymi/-imi'. Im Deutschen: 'den kleinen Kindern' (Dativ Plural). Die Endung '-ym' im Dativ Plural ist einheitlich und leicht zu merken."},
      {"id": "gp_ad14", "question": "Spotkali\u015bmy si\u0119 z _____ przyjaci\u00f3\u0142mi.", "translation": "Wir trafen uns mit alten Freunden.", "options": ["starymi", "stare", "starzy", "starych"], "correct": "starymi", "explanation": "'Ze starymi przyjaci\u00f3\u0142mi' (mit alten Freunden, Instr. Pl.) \u2013 Instrumentalendung Plural: '-ymi/-imi'. Im Deutschen: 'mit alten Freunden' (Dativ Plural). Die Instrumentalformen sind f\u00fcr alle Geschlechter gleich: '-ymi/-imi'. Beachten Sie den Wechsel 'z \u2192 ze' vor 'st-' (Konsonantengruppe). Die Instrumentalplural-Endung ist eine der regelm\u00e4\u00dfigsten im Polnischen: 'dobrymi', 'nowymi', 'polskimi'."},
      {"id": "gp_ad15", "question": "Opowiedz mi o _____ wakacjach.", "translation": "Erz\u00e4hl mir von deinem letzten Urlaub.", "options": ["ostatnich", "ostatnie", "ostatni", "ostatnimi"], "correct": "ostatnich", "explanation": "'O ostatnich wakacjach' (\u00fcber den letzten Urlaub, Lok. Pl.) \u2013 'o + Lokativ'. Die Lokativendung Plural: '-ych/-ich'. 'Ostatnich' kommt von 'ostatni' (letzte). Beachten Sie: Genitiv Plural und Lokativ Plural haben bei Adjektiven dieselbe Endung '-ych/-ich'. Im Deutschen: 'von deinem letzten Urlaub' (Dativ). Die polnische Gen. = Lok. Plural-\u00dcbereinstimmung bei Adjektiven ist eine weitere lernfreundliche Regelm\u00e4\u00dfigkeit."}
    ]
  },
  {
    "id": "gp_adj_comp",
    "key": "adjective_comparison",
    "name": "Stopniowanie przymiotnik\u00f3w (Adjektivsteigerung)",
    "items": [
      {"id": "gp_ac1", "question": "Ten dom jest _____ od tamtego.", "translation": "Dieses Haus ist gr\u00f6\u00dfer als jenes.", "options": ["wi\u0119kszy", "du\u017cy", "najwi\u0119kszy", "wielki"], "correct": "wi\u0119kszy", "explanation": "'Wi\u0119kszy' (gr\u00f6\u00dfer) ist der Komparativ von 'du\u017cy' (gro\u00df). Im Polnischen wird der Vergleich mit 'od + Genitiv' oder 'ni\u017c + Nominativ' gebildet: 'wi\u0119kszy od tamtego' oder 'wi\u0119kszy ni\u017c tamten'. Im Deutschen: 'gr\u00f6\u00dfer als'. Die unregelm\u00e4\u00dfige Steigerung 'du\u017cy \u2192 wi\u0119kszy \u2192 najwi\u0119kszy' entspricht dem deutschen 'gro\u00df \u2192 gr\u00f6\u00dfer \u2192 am gr\u00f6\u00dften'. Beide Sprachen haben \u00e4hnliche Unregelm\u00e4\u00dfigkeiten bei h\u00e4ufigen Adjektiven."},
      {"id": "gp_ac2", "question": "Ona jest _____ uczennic\u0105 w klasie.", "translation": "Sie ist die beste Sch\u00fclerin in der Klasse.", "options": ["najlepsz\u0105", "lepsza", "dobra", "najlepsza"], "correct": "najlepsz\u0105", "explanation": "'Najlepsz\u0105 uczennic\u0105' (die beste Sch\u00fclerin, Instr. fem.) \u2013 der Superlativ mit 'naj-' Pr\u00e4fix. Beachten Sie: 'jest + Instrumental' f\u00fcr Beruf/Eigenschaft. 'Dobry \u2192 lepszy \u2192 najlepszy' entspricht dem deutschen 'gut \u2192 besser \u2192 am besten'. Die Instrumentalform 'najlepsz\u0105' steht, weil nach 'by\u0107' (sein) bei Beschreibungen der Instrumental bevorzugt wird. Im Deutschen: 'die beste Sch\u00fclerin' (Nominativ nach 'ist')."},
      {"id": "gp_ac3", "question": "Ta herbata jest _____ ni\u017c kawa.", "translation": "Dieser Tee ist billiger als Kaffee.", "options": ["ta\u0144sza", "tania", "najta\u0144sza", "dro\u017csza"], "correct": "ta\u0144sza", "explanation": "'Ta\u0144sza' (billiger) ist der Komparativ von 'tania' (billig). Die regelm\u00e4\u00dfige Steigerung: 'tani \u2192 ta\u0144szy \u2192 najta\u0144szy'. Die Endung '-szy/-sza/-sze' wird an den ge\u00e4nderten Stamm angeh\u00e4ngt (t > \u0144). 'Ni\u017c' (als) leitet den Vergleich ein: 'ta\u0144sza ni\u017c kawa'. Im Deutschen: 'billiger als Kaffee'. Die polnische Steigerung mit Stammkonsonanten\u00e4nderung ist typisch: 'drogi \u2192 dro\u017cszy' (teuer \u2192 teurer), '\u0142adny \u2192 \u0142adniejszy' (h\u00fcbsch \u2192 h\u00fcbscher)."},
      {"id": "gp_ac4", "question": "To jest _____ ciekawy film.", "translation": "Das ist der interessanteste Film.", "options": ["najbardziej", "bardziej", "wcale", "bardzo"], "correct": "najbardziej", "explanation": "'Najbardziej ciekawy' (der interessanteste) \u2013 l\u00e4ngere Adjektive werden analytisch gesteigert mit 'bardziej' (Komparativ) und 'najbardziej' (Superlativ). Im Deutschen: 'der interessanteste' (synthetisch). Im Polnischen gibt es beide M\u00f6glichkeiten: 'ciekawszy' (synthetisch) und 'bardziej ciekawy' (analytisch \u2013 eher umgangssprachlich). Generell verwenden k\u00fcrzere Adjektive die synthetische Form, l\u00e4ngere die analytische. Diese Parallele zum Deutschen ('mehr interessant' vs. 'interessanter') hilft beim Verst\u00e4ndnis."},
      {"id": "gp_ac5", "question": "Zima jest _____ por\u0105 roku.", "translation": "Winter ist die k\u00e4lteste Jahreszeit.", "options": ["najzimniejsz\u0105", "zimniejsza", "zimna", "najzimniejsza"], "correct": "najzimniejsz\u0105", "explanation": "'Najzimniejsz\u0105 por\u0105' (die k\u00e4lteste Jahreszeit, Instr. fem.) \u2013 Superlativ mit 'naj-' + Instrumental nach 'jest'. 'Zimny \u2192 zimniejszy \u2192 najzimniejszy'. Die Endung '-iejszy/-niejszy' ist sehr produktiv. Im Deutschen: 'die k\u00e4lteste Jahreszeit' (Nominativ). Beachten Sie: Im Polnischen steht nach 'by\u0107' + Eigenschaft bevorzugt der Instrumental, im Deutschen der Nominativ. Beide Formen sind im Polnischen m\u00f6glich, aber der Instrumental ist h\u00e4ufiger."},
      {"id": "gp_ac6", "question": "Brat jest _____ ode mnie.", "translation": "Mein Bruder ist j\u00fcnger als ich.", "options": ["m\u0142odszy", "m\u0142ody", "najm\u0142odszy", "m\u0142odsza"], "correct": "m\u0142odszy", "explanation": "'M\u0142odszy ode mnie' (j\u00fcnger als ich) \u2013 'od + Genitiv' f\u00fcr den Vergleich. 'Ode' statt 'od' vor 'mnie' wegen der Aussprache. 'M\u0142ody \u2192 m\u0142odszy \u2192 najm\u0142odszy' (jung \u2192 j\u00fcnger \u2192 am j\u00fcngsten). Im Deutschen: 'j\u00fcnger als ich' (mit Umlaut). Beachten Sie die Konsonantenwechsel bei der Steigerung: d \u2192 dz in manchen Formen. Die \u00c4hnlichkeit der unregelm\u00e4\u00dfigen Steigerungen in beiden Sprachen erleichtert das Lernen."},
      {"id": "gp_ac7", "question": "Ta jest _____ droga w mie\u015bcie.", "translation": "Das ist die l\u00e4ngste Stra\u00dfe in der Stadt.", "options": ["najd\u0142u\u017csza", "d\u0142u\u017csza", "d\u0142uga", "najd\u0142u\u017cszej"], "correct": "najd\u0142u\u017csza", "explanation": "'Najd\u0142u\u017csza droga' (die l\u00e4ngste Stra\u00dfe) \u2013 Superlativ: 'd\u0142ugi \u2192 d\u0142u\u017cszy \u2192 najd\u0142u\u017cszy'. Der Konsonantenwechsel g \u2192 \u017c ist regelm\u00e4\u00dfig. Im Deutschen: 'die l\u00e4ngste Stra\u00dfe' (mit Umlaut a \u2192 \u00e4). Sowohl Polnisch als auch Deutsch haben Stammver\u00e4nderungen bei der Steigerung. Die polnischen Konsonantenwechsel: g \u2192 \u017c, d \u2192 dz, t \u2192 c, s \u2192 sz, z \u2192 \u017c. Diese phonetischen Regeln sind systematisch und lernbar."},
      {"id": "gp_ac8", "question": "Jego wynik jest _____ ni\u017c m\u00f3j.", "translation": "Sein Ergebnis ist schlechter als meins.", "options": ["gorszy", "z\u0142y", "najgorszy", "gorsza"], "correct": "gorszy", "explanation": "'Gorszy' (schlechter/schlimmer) ist der Komparativ von 'z\u0142y' (schlecht). Die unregelm\u00e4\u00dfige Steigerung: 'z\u0142y \u2192 gorszy \u2192 najgorszy'. Im Deutschen: 'schlecht \u2192 schlechter \u2192 am schlechtesten' (regelm\u00e4\u00dfig!) oder 'b\u00f6se \u2192 b\u00f6ser'. Im Polnischen ist die Steigerung von 'z\u0142y' suppletiv (anderer Stamm), \u00e4hnlich wie im Englischen 'bad \u2192 worse \u2192 worst'. Auch 'dobry \u2192 lepszy \u2192 najlepszy' und 'du\u017cy \u2192 wi\u0119kszy \u2192 najwi\u0119kszy' sind suppletiv."},
      {"id": "gp_ac9", "question": "To jest o wiele _____ rozwi\u0105zanie.", "translation": "Das ist eine viel einfachere L\u00f6sung.", "options": ["prostsze", "proste", "najprostsze", "prostszy"], "correct": "prostsze", "explanation": "'Prostsze rozwi\u0105zanie' (einfachere L\u00f6sung, Nom. neutr.) \u2013 'prosty \u2192 prostszy \u2192 najprostszy'. 'Rozwi\u0105zanie' ist Neutrum, daher 'prostsze' (Endung '-e'). 'O wiele' (um vieles/viel) verst\u00e4rkt den Komparativ. Im Deutschen: 'eine viel einfachere L\u00f6sung'. Weitere Verst\u00e4rker: 'znacznie' (deutlich), 'o wiele' (um vieles), 'troch\u0119' (ein wenig), 'nieco' (etwas). Im Deutschen: 'viel, deutlich, etwas, ein wenig'."},
      {"id": "gp_ac10", "question": "Ten hotel jest tak samo _____ jak tamten.", "translation": "Dieses Hotel ist genauso teuer wie jenes.", "options": ["drogi", "dro\u017cszy", "najdro\u017cszy", "dro\u017csza"], "correct": "drogi", "explanation": "'Tak samo drogi jak...' (genauso teuer wie...) \u2013 der Gleichheitsvergleich verwendet die Grundform (Positiv): 'tak samo + Adjektiv + jak'. Im Deutschen: 'genauso teuer wie'. Beide Sprachen verwenden f\u00fcr den Gleichheitsvergleich die Grundform des Adjektivs mit 'so...wie'/'tak...jak'. Dies ist ein Bereich, in dem die Konstruktionen nahezu identisch sind und keine besonderen Schwierigkeiten bereiten."},
      {"id": "gp_ac11", "question": "Im _____ sobie pomy\u015blisz, tym _____ b\u0119dzie.", "translation": "Je schneller du dir \u00fcberlegst, desto besser wird es.", "options": ["szybciej / lepiej", "szybko / dobrze", "najszybciej / najlepiej", "szybszy / lepszy"], "correct": "szybciej / lepiej", "explanation": "'Im szybciej... tym lepiej' (je schneller... desto besser) \u2013 die proportionale Konstruktion verwendet 'im + Komparativ... tym + Komparativ', \u00e4hnlich dem deutschen 'je + Komparativ... desto + Komparativ'. Beachten Sie: hier stehen die Adverb-Komparative 'szybciej' (schneller) und 'lepiej' (besser), nicht die Adjektivformen. Im Polnischen und Deutschen ist diese Konstruktion strukturell identisch und daher leicht \u00fcbertragbar."},
      {"id": "gp_ac12", "question": "Masz _____ brata ni\u017c siostr\u0119.", "translation": "Du hast einen \u00e4lteren Bruder als deine Schwester.", "options": ["starszego", "starszy", "starszym", "najstarszego"], "correct": "starszego", "explanation": "'Starszego brata' (\u00e4lteren Bruder, Akk. mask. belebt) \u2013 bei belebten Maskulina ist der Akkusativ = Genitiv: 'starszego'. Im Deutschen: 'einen \u00e4lteren Bruder' (Akkusativ). Das Komparativadjektiv wird im Polnischen normal dekliniert: 'starszy' (Nom.), 'starszego' (Gen./Akk. belebt), 'starszemu' (Dat.), 'starszym' (Instr./Lok.). Die Steigerungsformen verhalten sich deklinatorisch wie regul\u00e4re Adjektive."},
      {"id": "gp_ac13", "question": "To najpi\u0119kniejsze miasto, _____ odwiedzi\u0142em.", "translation": "Das ist die sch\u00f6nste Stadt, die ich besucht habe.", "options": ["jakie", "kt\u00f3re", "co", "jak"], "correct": "jakie", "explanation": "'Najpi\u0119kniejsze miasto, jakie odwiedzi\u0142em' (die sch\u00f6nste Stadt, die ich besucht habe) \u2013 nach Superlativen steht im Polnischen oft 'jaki/jaka/jakie' statt 'kt\u00f3ry'. Im Deutschen: 'die sch\u00f6nste Stadt, die...' (Relativpronomen 'die'). Die Steigerung: 'pi\u0119kny \u2192 pi\u0119kniejszy \u2192 najpi\u0119kniejszy' (sch\u00f6n \u2192 sch\u00f6ner \u2192 am sch\u00f6nsten). Im Polnischen wird der Superlativ als Pr\u00e4fix 'naj-' + Komparativ gebildet, im Deutschen mit 'am ...sten'."},
      {"id": "gp_ac14", "question": "Jest coraz _____ na zewn\u0105trz.", "translation": "Es wird drau\u00dfen immer w\u00e4rmer.", "options": ["cieplej", "ciep\u0142o", "najcieplej", "cieplejszy"], "correct": "cieplej", "explanation": "'Coraz cieplej' (immer w\u00e4rmer) \u2013 'coraz + Komparativ' dr\u00fcckt progressive Ver\u00e4nderung aus. 'Ciep\u0142o \u2192 cieplej \u2192 najcieplej' (warm \u2192 w\u00e4rmer \u2192 am w\u00e4rmsten \u2013 Adverbformen). Im Deutschen: 'immer w\u00e4rmer'. 'Coraz' entspricht dem deutschen 'immer' in steigernder Bedeutung. Weitere Beispiele: 'coraz lepiej' (immer besser), 'coraz wi\u0119cej' (immer mehr), 'coraz szybciej' (immer schneller). Diese Konstruktion ist im Alltag sehr h\u00e4ufig."},
      {"id": "gp_ac15", "question": "Ma\u0142gosia jest _____ ze wszystkich.", "translation": "Ma\u0142gosia ist die Klügste von allen.", "options": ["najm\u0105drzejsza", "m\u0105drzejsza", "m\u0105dra", "najm\u0105drzejszej"], "correct": "najm\u0105drzejsza", "explanation": "'Najm\u0105drzejsza ze wszystkich' (die Kl\u00fcgste von allen) \u2013 Superlativ + 'ze wszystkich' (von allen, Gen. Pl.). Die Steigerung: 'm\u0105dry \u2192 m\u0105drzejszy \u2192 najm\u0105drzejszy' (klug \u2192 kl\u00fcger \u2192 am kl\u00fcgsten). Der Konsonantenwechsel dr \u2192 drz ist typisch polnisch. Im Deutschen \u00e4ndert sich der Vokal (klug \u2192 kl\u00fcger). Im Polnischen kann der Superlativ wie im Deutschen frei im Satz stehen: 'Ona jest najm\u0105drzejsza' = 'Sie ist die Kl\u00fcgste'."}
    ]
  },
  {
    "id": "gp_adverbs",
    "key": "adverbs",
    "name": "Przys\u0142\u00f3wki (Adverbien)",
    "items": [
      {"id": "gp_adv1", "question": "On m\u00f3wi po polsku bardzo _____.", "translation": "Er spricht sehr gut Polnisch.", "options": ["dobrze", "dobry", "dobre", "dobra"], "correct": "dobrze", "explanation": "'Dobrze' (gut) ist das Adverb von 'dobry' (gut, Adjektiv). Im Polnischen werden Adverbien meist aus Adjektiven gebildet: '-y/-i' \u2192 '-e/-o/-ie'. Beispiele: 'szybki \u2192 szybko' (schnell), '\u0142adny \u2192 \u0142adnie' (h\u00fcbsch), 'dobry \u2192 dobrze' (gut). Im Deutschen enden Adverbien nicht anders als Adjektive in pr\u00e4dikativer Stellung: 'Er spricht gut'. Im Polnischen gibt es immer eine eigene Adverbform, was Deutschsprachige zuerst \u00fcben m\u00fcssen."},
      {"id": "gp_adv2", "question": "Prosz\u0119 m\u00f3wi\u0107 _____, nie rozumiem.", "translation": "Bitte sprechen Sie langsamer, ich verstehe nicht.", "options": ["wolniej", "wolno", "wolny", "najwolniej"], "correct": "wolniej", "explanation": "'Wolniej' (langsamer) ist der Komparativ des Adverbs 'wolno' (langsam). Im Polnischen wird der Adverb-Komparativ mit '-iej/-ej' gebildet: 'wolno \u2192 wolniej', 'szybko \u2192 szybciej', '\u0142adnie \u2192 \u0142adniej'. Im Deutschen: 'langsamer' \u2013 identische Form mit Adjektivkomparativ. Im Polnischen gibt es eigene Adverb-Komparativformen, die sich von den Adjektivkomparativen unterscheiden. Eine h\u00e4ufige und n\u00fctzliche Bitte im Alltag!"},
      {"id": "gp_adv3", "question": "Wszyscy byli _____ ubrani.", "translation": "Alle waren elegant gekleidet.", "options": ["elegancko", "elegancki", "elegancka", "eleganckie"], "correct": "elegancko", "explanation": "'Elegancko ubrani' (elegant gekleidet) \u2013 das Adverb 'elegancko' modifiziert das Partizip 'ubrani'. Die Adverbendung '-o' kommt von Adjektiven auf '-ny/-ki/-wy': 'elegancki \u2192 elegancko', 'pi\u0119kny \u2192 pi\u0119knie' (Ausnahme '-nie'), 'nowy \u2192 nowo'. Im Deutschen: 'elegant gekleidet' \u2013 das Adjektiv steht unver\u00e4ndert als Adverb. Diese getrennte Adverbform ist eine wichtige Besonderheit des Polnischen."},
      {"id": "gp_adv4", "question": "_____ nie by\u0142em u lekarza.", "translation": "Ich war lange nicht beim Arzt.", "options": ["D\u0142ugo", "D\u0142ugi", "D\u0142uga", "D\u0142u\u017cej"], "correct": "D\u0142ugo", "explanation": "'D\u0142ugo' (lange, Adverb) von 'd\u0142ugi' (lang, Adjektiv). Im Polnischen: 'd\u0142ugo nie by\u0142em' \u2013 die Wortstellung ist flexibel, das Adverb kann am Satzanfang stehen f\u00fcr Betonung. Im Deutschen: 'Ich war lange nicht...' Temporale Adverbien im Polnischen: 'd\u0142ugo' (lange), 'kr\u00f3tko' (kurz), 'dawno' (vor langer Zeit), 'niedawno' (vor Kurzem), 'od dawna' (seit Langem). Diese Zeitadverbien sind im Alltag unverzichtbar."},
      {"id": "gp_adv5", "question": "Pracuje _____ nad projektem.", "translation": "Er arbeitet hart an dem Projekt.", "options": ["ci\u0119\u017cko", "ci\u0119\u017cki", "ci\u0119\u017ckiej", "ci\u0119\u017cka"], "correct": "ci\u0119\u017cko", "explanation": "'Ci\u0119\u017cko pracowa\u0107' (hart arbeiten) \u2013 'ci\u0119\u017cko' kann 'hart/schwer' bedeuten. Im Polnischen haben manche Adverbien mehrere Bedeutungen: 'ci\u0119\u017cko' = 'schwer/hart', 'lekko' = 'leicht', '\u0142atwo' = 'einfach'. Im Deutschen: 'hart arbeiten'. 'Nad projektem' (an dem Projekt \u2013 'nad + Instrumental'). Im Deutschen: 'an + Dativ'. Die Pr\u00e4position 'nad' (über/an) wird f\u00fcr Arbeit an etwas und r\u00e4umliches 'über etwas' verwendet."},
      {"id": "gp_adv6", "question": "Przyjd\u017a _____, bo si\u0119 sp\u00f3\u017animy.", "translation": "Komm schnell, sonst kommen wir zu sp\u00e4t.", "options": ["szybko", "szybki", "szybciej", "szybka"], "correct": "szybko", "explanation": "'Szybko' (schnell) ist eines der h\u00e4ufigsten polnischen Adverbien. 'Szybki \u2192 szybko \u2192 szybciej \u2192 najszybciej' (schnell \u2192 schneller \u2192 am schnellsten). Im Deutschen: 'schnell' (Adjektiv = Adverb in der Form). Im Polnischen sind die Formen getrennt: 'szybki samoch\u00f3d' (Adj.: schnelles Auto) vs. 'szybko biega\u0107' (Adv.: schnell laufen). 'Sp\u00f3\u017cni\u0107 si\u0119' (zu sp\u00e4t kommen/sich versp\u00e4ten) ist ein wichtiges reflexives Verb im Alltag."},
      {"id": "gp_adv7", "question": "_____ pada \u015bnieg w marcu.", "translation": "Manchmal schneit es im M\u00e4rz.", "options": ["Czasami", "Zawsze", "Nigdy", "Cz\u0119sto"], "correct": "Czasami", "explanation": "'Czasami' (manchmal) ist ein H\u00e4ufigkeitsadverb. Die polnischen H\u00e4ufigkeitsadverbien: 'zawsze' (immer), 'cz\u0119sto' (oft), 'czasami/czasem' (manchmal), 'rzadko' (selten), 'nigdy' (nie). Im Deutschen: 'immer, oft, manchmal, selten, nie'. Die Reihenfolge und Bedeutung sind in beiden Sprachen parallel. 'Pada \u015bnieg' (es schneit, w\u00f6rtl.: Schnee f\u00e4llt) \u2013 im Polnischen wird 'pada\u0107' f\u00fcr alle Niederschl\u00e4ge verwendet: 'pada deszcz' (es regnet)."},
      {"id": "gp_adv8", "question": "Musz\u0119 i\u015b\u0107 tam _____.", "translation": "Ich muss sofort dorthin gehen.", "options": ["natychmiast", "wczoraj", "jutro", "nigdy"], "correct": "natychmiast", "explanation": "'Natychmiast' (sofort/auf der Stelle) ist ein Zeitadverb mit dr\u00e4ngender Bedeutung. Synonyme: 'od razu' (sofort), 'zaraz' (gleich), 'niezw\u0142ocznie' (unverz\u00fcglich, formell). Im Deutschen: 'sofort/gleich/unverz\u00fcglich'. Ortsadverb 'tam' (dort/dorthin) \u2013 im Polnischen sowohl f\u00fcr Lage als auch Richtung, im Deutschen unterscheidet man 'dort' (Lage) vs. 'dorthin' (Richtung). 'I\u015b\u0107 tam' = 'dorthin gehen' (Richtung)."},
      {"id": "gp_adv9", "question": "Ten egzamin by\u0142 _____ trudny.", "translation": "Diese Pr\u00fcfung war extrem schwer.", "options": ["niezwykle", "niezwyk\u0142y", "niezwyk\u0142e", "niezwyk\u0142a"], "correct": "niezwykle", "explanation": "'Niezwykle trudny' (au\u00dfergew\u00f6hnlich/extrem schwer) \u2013 das Adverb 'niezwykle' (au\u00dfergew\u00f6hnlich) modifiziert das Adjektiv 'trudny'. Intensit\u00e4tsadverbien im Polnischen: 'bardzo' (sehr), 'niezwykle' (au\u00dfergew\u00f6hnlich), 'nadzwyczaj' (au\u00dferordentlich), 'ogromnie' (enorm), 'niesamowicie' (unglaublich). Im Deutschen: 'sehr, \u00e4u\u00dferst, enorm, unglaublich'. Die Stellung vor dem Adjektiv ist in beiden Sprachen identisch."},
      {"id": "gp_adv10", "question": "Spotkali\u015bmy si\u0119 _____.", "translation": "Wir haben uns zuf\u00e4llig getroffen.", "options": ["przypadkiem", "przypadkowy", "przypadkowo", "przypadek"], "correct": "przypadkiem", "explanation": "'Przypadkiem' (zuf\u00e4llig, w\u00f6rtl.: durch Zufall) \u2013 im Polnischen k\u00f6nnen Substantive im Instrumental als Adverbien fungieren: 'przypadkiem' (zuf\u00e4llig), 'pieszo' und 'piechot\u0105' (zu Fu\u00df), 'po\u015bpiechem' (in Eile). Auch 'przypadkowo' (das eigentliche Adverb) ist m\u00f6glich. Im Deutschen: 'zuf\u00e4llig'. Diese instrumentale Adverbverwendung ist eine elegante Eigenheit des Polnischen, die es im Deutschen in dieser Form nicht gibt."},
      {"id": "gp_adv11", "question": "_____ m\u00f3wi po niemiecku ni\u017c po angielsku.", "translation": "Er spricht besser Deutsch als Englisch.", "options": ["Lepiej", "Lepszy", "Lepsza", "Najlepiej"], "correct": "Lepiej", "explanation": "'Lepiej' (besser, Adverb) ist der Komparativ von 'dobrze' (gut). Die unregelm\u00e4\u00dfige Adverb-Steigerung: 'dobrze \u2192 lepiej \u2192 najlepiej', '\u017ale \u2192 gorzej \u2192 najgorzej', 'du\u017co \u2192 wi\u0119cej \u2192 najwi\u0119cej', 'ma\u0142o \u2192 mniej \u2192 najmniej'. Im Deutschen: 'gut \u2192 besser \u2192 am besten'. Die Parallele ist offensichtlich: beide Sprachen haben suppletive Adverbsteigerungen bei den h\u00e4ufigsten W\u00f6rtern."},
      {"id": "gp_adv12", "question": "Wst\u0105d\u017a _____, t\u0119dy jest bli\u017cej.", "translation": "Steig hier ein, hier ist es n\u00e4her.", "options": ["tu", "tam", "tutaj", "gdzie\u015b"], "correct": "tu", "explanation": "'Tu' (hier) und 'tutaj' (hier/hierher) sind Synonyme f\u00fcr den nahen Ort. Im Polnischen: 'tu/tutaj' (hier, nah), 'tam' (dort, fern). Im Deutschen: 'hier/da/dort'. 'Bli\u017cej' (n\u00e4her) ist der Komparativ von 'blisko' (nah). 'T\u0119dy' (hier entlang/diesen Weg) ist ein Richtungsadverb: 't\u0119dy' (diesen Weg), 'tam t\u0119dy' (dort entlang). Im Deutschen: 'hier entlang/lang'. Diese Richtungsadverbien sind f\u00fcr die Navigation im Alltag wichtig."},
      {"id": "gp_adv13", "question": "Prosz\u0119 _____ g\u0142o\u015bno nie m\u00f3wi\u0107.", "translation": "Bitte sprechen Sie nicht zu laut.", "options": ["zbyt", "bardzo", "za", "do\u015b\u0107"], "correct": "zbyt", "explanation": "'Zbyt g\u0142o\u015bno' (zu laut) \u2013 'zbyt' und 'za' (zu, \u00fcberm\u00e4\u00dfig) dr\u00fccken \u00dcberma\u00df aus. 'Zbyt' ist formeller, 'za' umgangssprachlich: 'za g\u0142o\u015bno' = 'zbyt g\u0142o\u015bno'. Im Deutschen: 'zu laut'. Weitere Graduierung: 'do\u015b\u0107/dostatecznie' (genug/ausreichend), 'wystarczaj\u0105co' (gen\u00fcgend), 'zbyt/za' (zu viel). Die Position vor dem Adverb/Adjektiv ist wie im Deutschen."},
      {"id": "gp_adv14", "question": "Rozmawiali _____ o polityce.", "translation": "Sie unterhielten sich leidenschaftlich \u00fcber Politik.", "options": ["gor\u0105co", "gor\u0105cy", "gor\u0105ca", "najgor\u0119cej"], "correct": "gor\u0105co", "explanation": "'Gor\u0105co' (hei\u00df/leidenschaftlich/hitzig) \u2013 Adverbien k\u00f6nnen im Polnischen wie im Deutschen \u00fcbertragene Bedeutungen haben. 'Gor\u0105co dyskutowa\u0107' (hitzig diskutieren), 'zimno patrze\u0107' (kalt blicken), 'ciep\u0142o przyjmowa\u0107' (warm empfangen). Im Deutschen: 'leidenschaftlich/hitzig \u00fcber Politik diskutieren'. Diese metaphorische Verwendung von Temperatur-Adverbien ist in beiden Sprachen verbreitet und bereichert den Sprachstil."},
      {"id": "gp_adv15", "question": "Zrobi\u0142 to _____, \u017ceby nikomu nie przeszkadza\u0107.", "translation": "Er tat es leise, um niemanden zu st\u00f6ren.", "options": ["cicho", "cichy", "cichszej", "ciche"], "correct": "cicho", "explanation": "'Cicho' (leise/still) von 'cichy' (leise, Adjektiv). Im Polnischen: 'cichy \u2192 cicho \u2192 ciszej \u2192 najciszej'. Beachten Sie den Konsonantenwechsel ch \u2192 sz im Komparativ. Im Deutschen: 'leise \u2192 leiser \u2192 am leisesten' (regelm\u00e4\u00dfig). Der Finalsatz '\u017ceby + Infinitiv' (um zu) entspricht dem deutschen 'um... zu...'. Aber mit Subjektwechsel: '\u017ceby + Konjunktiv': '\u017ceby nikomu nie przeszkadza\u0107' = 'um niemanden zu st\u00f6ren'. Doppelte Verneinung: 'nikomu nie'."}
    ]
  },
  {
    "id": "gp_noun_gender",
    "key": "noun_gender",
    "name": "Rodzaj rzeczownik\u00f3w (Substantivgenus)",
    "items": [
      {"id": "gp_ng1", "question": "_____ jest gor\u0105ca.", "translation": "Die Suppe ist hei\u00df.", "options": ["Zupa", "Zup\u0105", "Zupy", "Zupie"], "correct": "Zupa", "explanation": "'Zupa' (Suppe) ist feminin (Endung '-a'). Die Genuszuordnung im Polnischen folgt meist den Endungen: '-a' = feminin, Konsonant = maskulin, '-o/-e/-\u0119/-um' = neutrum. Im Deutschen: 'die Suppe' (auch feminin). Die Grundregel der polnischen Genusbestimmung ist systematischer als im Deutschen, wo das Genus oft willk\u00fcrlich erscheint. Die \u00dcbereinstimmung mit dem Pr\u00e4dikat 'gor\u0105ca' (feminin) best\u00e4tigt das Genus."},
      {"id": "gp_ng2", "question": "_____ jest nowoczesny.", "translation": "Das Krankenhaus ist modern.", "options": ["Szpital", "Szpitala", "Szpitalem", "Szpitale"], "correct": "Szpital", "explanation": "'Szpital' (Krankenhaus) ist maskulin (endet auf Konsonant). Im Deutschen: 'das Krankenhaus' (Neutrum). Hier zeigt sich ein typischer Genusunterschied: polnisch maskulin, deutsch neutrum. Weitere Beispiele f\u00fcr abweichendes Genus: 'klucz' (Schl\u00fcssel, PL: mask., DE: mask.), 'most' (Br\u00fccke, PL: mask., DE: fem.), 'muzeum' (Museum, PL: neutr., DE: neutr.). Die Genusunterschiede m\u00fcssen f\u00fcr jedes Wort einzeln gelernt werden."},
      {"id": "gp_ng3", "question": "_____ jest smaczne.", "translation": "Das Essen ist lecker.", "options": ["Jedzenie", "Jedzeniu", "Jedzeniam", "Jedze\u0144"], "correct": "Jedzenie", "explanation": "'Jedzenie' (Essen) ist Neutrum (Endung '-e'). Im Polnischen sind Verbalsubstantive auf '-anie/-enie/-cie' immer Neutrum: 'czytanie' (Lesen), 'pisanie' (Schreiben), 'gotowanie' (Kochen). Im Deutschen: 'das Essen' (auch Neutrum). Diese Kategorie von W\u00f6rtern stimmt im Genus meist \u00fcberein, da beide Sprachen aus Verben abgeleitete Substantive als s\u00e4chlich behandeln. Im Pr\u00e4dikat steht 'smaczne' (Neutr. Nom.)."},
      {"id": "gp_ng4", "question": "_____ le\u017cy na \u0142\u00f3\u017cku.", "translation": "Die Katze liegt auf dem Bett.", "options": ["Kot", "Kotka", "Koty", "Kotem"], "correct": "Kot", "explanation": "'Kot' (Katze/Kater) ist maskulin belebt. Im Polnischen gibt es drei Unterkategorien des Maskulinums: m\u00e4nnlich-personal (Menschen), m\u00e4nnlich-belebt (Tiere) und m\u00e4nnlich-unbelebt (Dinge). Im Deutschen: 'die Katze' (feminin!). Dieser Genusunterschied (PL: mask. \u2013 DE: fem.) ist besonders auff\u00e4llig. Die B\u00e4lebt-Kategorie beeinflusst den Akkusativ: 'Widz\u0119 kota' (Akk. = Gen.), nicht 'widz\u0119 kot'."},
      {"id": "gp_ng5", "question": "_____ jest na stole.", "translation": "Das Salz ist auf dem Tisch.", "options": ["S\u00f3l", "Soli", "Sol\u0105", "Sole"], "correct": "S\u00f3l", "explanation": "'S\u00f3l' (Salz) ist im Polnischen feminin, obwohl es auf einen Konsonanten endet (Ausnahme zur Regel!). Im Deutschen: 'das Salz' (Neutrum). Einige polnische Feminina enden auf einen weichen Konsonanten: 's\u00f3l', 'noc' (Nacht), 'krew' (Blut), 'mi\u0142o\u015b\u0107' (Liebe), 'jesie\u0144' (Herbst). Diese Ausnahmen m\u00fcssen einzeln gelernt werden. Die Endung '-\u015b\u0107/-\u0107' bei abstrakten Substantiven ist fast immer feminin."},
      {"id": "gp_ng6", "question": "To jest ma\u0142e _____.", "translation": "Das ist ein kleines Kind.", "options": ["dziecko", "dziecka", "dzieci", "dzieckiem"], "correct": "dziecko", "explanation": "'Dziecko' (Kind) ist Neutrum (Endung '-o'). Im Deutschen: 'das Kind' (auch Neutrum). Die \u00dcbereinstimmung hier erleichtert das Lernen. Neutra auf '-o' im Polnischen: 'okno' (Fenster), 'mleko' (Milch), 'wino' (Wein), 'jab\u0142ko' (Apfel). Neutra auf '-e': 'morze' (Meer), 's\u0142o\u0144ce' (Sonne), 'zdj\u0119cie' (Foto). Neutra auf '-\u0119': 'imi\u0119' (Name), 'zwierz\u0119' (Tier). Jede Endung hat eigene Deklinationsmuster."},
      {"id": "gp_ng7", "question": "_____ jest zamkni\u0119ty.", "translation": "Das Gesch\u00e4ft ist geschlossen.", "options": ["Sklep", "Sklepu", "Sklepem", "Sklepy"], "correct": "Sklep", "explanation": "'Sklep' (Gesch\u00e4ft/Laden) ist maskulin unbelebt. Im Deutschen: 'das Gesch\u00e4ft' (Neutrum). Das Adjektiv 'zamkni\u0119ty' (geschlossen) zeigt das maskuline Genus: '-y'. W\u00e4re es feminin: 'zamkni\u0119ta', neutrum: 'zamkni\u0119te'. Im Polnischen gibt der pr\u00e4dikative Adjektiv immer den Genus des Subjekts an \u2013 ein n\u00fctzliches Hilfsmittel zur Genusbestimmung, das im Deutschen in dieser Form nicht existiert."},
      {"id": "gp_ng8", "question": "_____ jest ciekawy.", "translation": "Der Film ist interessant.", "options": ["Film", "Filmu", "Filmem", "Filmy"], "correct": "Film", "explanation": "'Film' ist im Polnischen maskulin unbelebt \u2013 und im Deutschen auch maskulin: 'der Film'. Das ist ein Internationalismus, der in beiden Sprachen dasselbe Genus hat. Weitere \u00fcbereinstimmende Maskulina: 'komputer' (der Computer), 'telefon' (das Telefon \u2013 hier weicht DE ab: Neutrum!), 'program' (das Programm \u2013 DE: Neutrum!). Die Genuszuordnung von Lehnw\u00f6rtern ist oft unvorhersehbar und muss einzeln gepr\u00fcft werden."},
      {"id": "gp_ng9", "question": "_____ jest bardzo du\u017ca.", "translation": "Das Zimmer ist sehr gro\u00df.", "options": ["Sala", "Pok\u00f3j", "Pokoju", "Sal\u0119"], "correct": "Sala", "explanation": "'Sala' (Saal/Zimmer) ist feminin (Endung '-a'). Aber 'pok\u00f3j' (Zimmer) ist maskulin! Im Polnischen k\u00f6nnen synonyme W\u00f6rter verschiedene Genera haben. Im Deutschen: 'das Zimmer' (Neutrum), 'der Saal' (maskulin). 'Du\u017ca' (gro\u00df, fem.) zeigt das Genus. Es ist wichtig, das Genus jedes Substantivs mitzulernen, da es Adjektive, Pronomen und Verformen beeinflusst. Merkhilfe: Neues Wort = immer mit Genus lernen!"},
      {"id": "gp_ng10", "question": "_____ jest ciep\u0142e.", "translation": "Die Milch ist warm.", "options": ["Mleko", "Mleka", "Mlekiem", "Mleku"], "correct": "Mleko", "explanation": "'Mleko' (Milch) ist im Polnischen Neutrum (Endung '-o'). Im Deutschen: 'die Milch' (feminin!). Das pr\u00e4dikative Adjektiv 'ciep\u0142e' (warm, neutr.) best\u00e4tigt das Genus. Weitere ber\u00fchmte Genus\u00e4nderungen PL \u2192 DE: 'mo\u015bt' (Br\u00fccke, PL: mask., DE: fem.), 'krzes\u0142o' (Stuhl, PL: neutr., DE: mask.), 'mi\u0119so' (Fleisch, PL: neutr., DE: neutr.). Dreimal umdenken ist beim Sprachwechsel normal!"},
      {"id": "gp_ng11", "question": "Nowi _____ przyszli dzi\u015b do klasy.", "translation": "Neue Sch\u00fcler kamen heute in die Klasse.", "options": ["uczniowie", "uczennice", "uczni\u00f3w", "uczniowi"], "correct": "uczniowie", "explanation": "'Nowi uczniowie' (neue Sch\u00fcler, Nom. Pl. m\u00e4nnl.-pers.) \u2013 m\u00e4nnlich-personale Substantive haben besondere Pluralendungen: '-owie', '-i/-y' mit Konsonantenwechsel oder '-e'. 'Ucze\u0144 \u2192 uczniowie' (Sch\u00fcler). Im Deutschen: 'die Sch\u00fcler' (Plural gleich Singular). Der polnische m\u00e4nnlich-personale Plural ist eine der komplexesten Kategorien: er beeinflusst Substantiv- und Adjektivendungen sowie Verbformen ('przyszli' statt 'przysz\u0142y')."},
      {"id": "gp_ng12", "question": "Kupi\u0142em nowe _____.", "translation": "Ich habe ein neues Telefon gekauft.", "options": ["urz\u0105dzenie", "urz\u0105dzenia", "urz\u0105dzeniem", "urz\u0105dze\u0144"], "correct": "urz\u0105dzenie", "explanation": "'Nowe urz\u0105dzenie' (neues Ger\u00e4t, Akk. neutr.) \u2013 bei Neutra ist der Akkusativ = Nominativ: 'nowe urz\u0105dzenie'. Die Endung '-enie' zeigt Neutrum an (Verbalsubstantiv). Im Deutschen: 'ein neues Telefon/Ger\u00e4t' (Neutrum, Akkusativ). Hier stimmen die Genera \u00fcberein und der Akkusativ = Nominativ in beiden Sprachen bei Neutra. Die Deklination: 'urz\u0105dzenie' (Nom./Akk.), 'urz\u0105dzenia' (Gen.), 'urz\u0105dzeniu' (Dat./Lok.), 'urz\u0105dzeniem' (Instr.)."},
      {"id": "gp_ng13", "question": "_____ jest m\u00f3j ulubiony kolor.", "translation": "Blau ist meine Lieblingsfarbe.", "options": ["Niebieski", "Niebieska", "Niebieskie", "Niebieskiego"], "correct": "Niebieski", "explanation": "'Niebieski' (Blau) steht hier als substantiviertes Adjektiv im Maskulinum \u2013 Farben als Substantive sind im Polnischen maskulin: 'niebieski jest...' (Blau ist...). Im Deutschen: 'Blau' (Neutrum als substantiviertes Adjektiv). 'Kolor' (Farbe) ist maskulin. Im Polnischen: 'M\u00f3j ulubiony kolor' (meine Lieblingsfarbe, mask. Genus!). Im Deutschen: 'meine Lieblingsfarbe' (fem., weil 'Farbe' fem. ist). Genus folgt dem Bezugswort."},
      {"id": "gp_ng14", "question": "To jest drogie _____.", "translation": "Das ist ein teures Museum.", "options": ["muzeum", "muzea", "muzeu", "muzeami"], "correct": "muzeum", "explanation": "'Muzeum' (Museum) ist Neutrum mit der lateinischen Endung '-um'. W\u00f6rter auf '-um' sind im Polnischen undeklinierbar im Singular: 'muzeum' in allen Kasus! Aber der Plural ist regelm\u00e4\u00dfig: 'muzea' (Nom. Pl.). Weitere '-um'-W\u00f6rter: 'centrum' (Zentrum), 'stadium' (Stadium), 'akwarium' (Aquarium). Im Deutschen: 'das Museum' (auch Neutrum). Diese Lateinischen Neutra behalten in beiden Sprachen ihr s\u00e4chliches Genus."},
      {"id": "gp_ng15", "question": "Dzi\u015b jest _____ pogoda.", "translation": "Heute ist sch\u00f6nes Wetter.", "options": ["\u0142adna", "\u0142adny", "\u0142adne", "\u0142adnych"], "correct": "\u0142adna", "explanation": "'\u0141adna pogoda' (sch\u00f6nes Wetter) \u2013 'pogoda' (Wetter) ist feminin (Endung '-a'), daher '\u0142adna' (fem.). Im Deutschen: 'das Wetter' (Neutrum) \u2192 'sch\u00f6nes Wetter'. Wieder ein Genusunterschied: PL feminin, DE neutrum. Die Kongruenz zwischen Adjektiv und Substantiv im Genus ist im Polnischen immer sichtbar: '\u0142adny' (m.), '\u0142adna' (f.), '\u0142adne' (n.). Im Deutschen ist die Kongruenz in pr\u00e4dikativer Stellung unsichtbar: 'Das Wetter ist sch\u00f6n' (ohne Endung)."}
    ]
  },
  {
    "id": "gp_noun_plural",
    "key": "noun_plural",
    "name": "Liczba mnoga (Pluralbildung)",
    "items": [
      {"id": "gp_np1", "question": "Mam dwa _____.", "translation": "Ich habe zwei Hunde.", "options": ["psy", "psami", "ps\u00f3w", "pies"], "correct": "psy", "explanation": "'Dwa psy' (zwei Hunde) \u2013 nach 'dwa' (zwei) steht der Nominativ Plural. 'Pies \u2192 psy' (Hund \u2192 Hunde) ist eine unregelm\u00e4\u00dfige Pluralbildung mit Stammwechsel. Im Deutschen: 'zwei Hunde' (Plural mit '-e'). Im Polnischen gibt es zahlreiche Muster der Pluralbildung: Maskulina: '-y/-i/-owie/-e', Feminina: '-y/-i/-e', Neutra: '-a/-e'. Der korrekte Plural jedes Substantivs muss gelernt werden, \u00e4hnlich wie im Deutschen."},
      {"id": "gp_np2", "question": "W moim mie\u015bcie jest pi\u0119\u0107 _____.", "translation": "In meiner Stadt gibt es f\u00fcnf Kirchen.", "options": ["ko\u015bcio\u0142\u00f3w", "ko\u015bcio\u0142y", "ko\u015bcio\u0142ami", "ko\u015bci\u00f3\u0142"], "correct": "ko\u015bcio\u0142\u00f3w", "explanation": "'Pi\u0119\u0107 ko\u015bcio\u0142\u00f3w' (f\u00fcnf Kirchen) \u2013 nach Zahlen ab 5 steht im Polnischen der Genitiv Plural! 'Ko\u015bci\u00f3\u0142 \u2192 ko\u015bcio\u0142y' (Nom. Pl.) aber 'ko\u015bcio\u0142\u00f3w' (Gen. Pl.). Die Zahlenrektion: 2-4 + Nom. Pl., 5+ + Gen. Pl. Im Deutschen: 'f\u00fcnf Kirchen' (immer Plural, kein Kasuswechsel). Diese polnische Regel ist eine der schwierigsten f\u00fcr Deutschsprachige, da das Deutsche keine zahlabh\u00e4ngige Kasusrektion kennt."},
      {"id": "gp_np3", "question": "Te _____ s\u0105 bardzo wygodne.", "translation": "Diese Schuhe sind sehr bequem.", "options": ["buty", "but\u00f3w", "butami", "but"], "correct": "buty", "explanation": "'Te buty' (diese Schuhe, Nom. Pl.) \u2013 'but \u2192 buty' (Schuh \u2192 Schuhe). Im Polnischen bilden Maskulina unbelebt den Plural meist mit '-y/-i'. Im Deutschen: 'die Schuhe' (Plural mit '-e'). Die Genuszuordnung im Plural ist im Polnischen anders als im Singular: 'buty' wird als nicht-m\u00e4nnlich-personal behandelt, daher 'te buty' (nicht 'ci buty'). Die Plural-Demonstrativpronomen: 'ci' (m\u00e4nnl.-pers.), 'te' (alle anderen)."},
      {"id": "gp_np4", "question": "Na stole le\u017c\u0105 trzy _____.", "translation": "Auf dem Tisch liegen drei B\u00fccher.", "options": ["ksi\u0105\u017cki", "ksi\u0105\u017ck\u0105", "ksi\u0105\u017cek", "ksi\u0105\u017cka"], "correct": "ksi\u0105\u017cki", "explanation": "'Trzy ksi\u0105\u017cki' (drei B\u00fccher) \u2013 nach 2-4 steht Nominativ Plural: 'ksi\u0105\u017cka \u2192 ksi\u0105\u017cki'. Bei Feminina auf '-ka' wird der Plural mit '-ki' gebildet (nach k bleibt k). Im Deutschen: 'drei B\u00fccher' (Plural mit Umlaut + '-er'). Beachten Sie: 'le\u017c\u0105' (liegen, 3. Pers. Pl.) \u2013 das polnische Verb kongruiert mit dem Plural-Subjekt, genau wie im Deutschen 'liegen'. Die Wortstellung ist im Polnischen flexibler."},
      {"id": "gp_np5", "question": "W naszej rodzinie jest pi\u0119cioro _____.", "translation": "In unserer Familie gibt es f\u00fcnf Kinder.", "options": ["dzieci", "dziecko", "dzieciom", "dzie\u0107mi"], "correct": "dzieci", "explanation": "'Pi\u0119cioro dzieci' (f\u00fcnf Kinder) \u2013 'dziecko \u2192 dzieci' (Kind \u2192 Kinder) ist suppletiv (anderer Stamm). Beachten Sie: 'pi\u0119cioro' ist eine Sammelzahlform, die f\u00fcr gemischte Gruppen verwendet wird. Im Deutschen: 'f\u00fcnf Kinder'. Der polnische Plural 'dzieci' ist wie der deutsche 'Kinder' unregelm\u00e4\u00dfig. 'Dzieci' ist immer nicht-m\u00e4nnlich-personal, auch wenn Jungen darunter sind \u2013 eine Besonderheit, die bei Genera im Plural oft \u00fcberrascht."},
      {"id": "gp_np6", "question": "Ci _____ s\u0105 bardzo pracowici.", "translation": "Diese M\u00e4nner sind sehr flei\u00dfig.", "options": ["m\u0119\u017cczy\u017ani", "m\u0119\u017cczyzn", "m\u0119\u017czyznami", "m\u0119\u017cczyzna"], "correct": "m\u0119\u017cczy\u017ani", "explanation": "'Ci m\u0119\u017cczy\u017ani' (diese M\u00e4nner, Nom. Pl. m\u00e4nnl.-pers.) \u2013 'm\u0119\u017cczyzna \u2192 m\u0119\u017cczy\u017ani' (Mann \u2192 M\u00e4nner). Obwohl 'm\u0119\u017cczyzna' auf '-a' endet (typisch feminin!), ist es maskulin. Der Plural folgt dem m\u00e4nnlich-personalen Muster mit Erweichung: zn \u2192 \u017an. Im Deutschen: 'die M\u00e4nner' (unregelm\u00e4\u00dfig). Beachten Sie 'pracowici' \u2013 Adjektiv im m\u00e4nnl.-pers. Plural mit Konsonantenwechsel: t \u2192 c. Im Deutschen: 'flei\u00dfig' (unver\u00e4ndert)."},
      {"id": "gp_np7", "question": "Mamy dwadzie\u015bcia _____ w klasie.", "translation": "Wir haben zwanzig Sch\u00fcler in der Klasse.", "options": ["uczni\u00f3w", "uczniowie", "uczniami", "ucze\u0144"], "correct": "uczni\u00f3w", "explanation": "'Dwadzie\u015bcia uczni\u00f3w' (zwanzig Sch\u00fcler, Gen. Pl.) \u2013 nach Zahlen ab 5 steht Gen. Pl. 'Ucze\u0144 \u2192 uczniowie' (Nom. Pl.) \u2192 'uczni\u00f3w' (Gen. Pl.). Die Genitivplural-Endung von maskulinen Substantiven auf '-\u00f3w' ist eine der h\u00e4ufigsten. Im Deutschen: 'zwanzig Sch\u00fcler' (Plural ohne Kasuswechsel). Weitere Beispiele: 'sto student\u00f3w' (hundert Studenten), 'tysi\u0105c mieszka\u0144c\u00f3w' (tausend Einwohner)."},
      {"id": "gp_np8", "question": "Na talerzu s\u0105 trzy _____.", "translation": "Auf dem Teller sind drei \u00c4pfel.", "options": ["jab\u0142ka", "jab\u0142ek", "jab\u0142ko", "jab\u0142kami"], "correct": "jab\u0142ka", "explanation": "'Trzy jab\u0142ka' (drei \u00c4pfel, Nom. Pl.) \u2013 Neutra auf '-o' bilden den Plural mit '-a': 'jab\u0142ko \u2192 jab\u0142ka', 'okno \u2192 okna', 'piwo \u2192 piwa'. Im Deutschen: '\u00c4pfel' (Umlaut). Nach 2-4 steht der Nominativ Plural. Beachten Sie: 'jab\u0142ko' ist im Polnischen Neutrum, 'Apfel' im Deutschen maskulin. Die Neutra-Pluralendung '-a' ist sehr regelm\u00e4\u00dfig und leicht zu lernen \u2013 fast alle Neutra auf '-o' bilden den Plural mit '-a'."},
      {"id": "gp_np9", "question": "W tym parku jest wiele _____.", "translation": "In diesem Park gibt es viele B\u00e4ume.", "options": ["drzew", "drzewa", "drzewami", "drzewie"], "correct": "drzew", "explanation": "'Wiele drzew' (viele B\u00e4ume, Gen. Pl.) \u2013 nach 'wiele' (viele) steht der Genitiv Plural. 'Drzewo \u2192 drzewa' (Nom. Pl.) \u2192 'drzew' (Gen. Pl. = Null-Endung). Bei Neutra hat der Genitiv Plural oft eine Null-Endung: 'jab\u0142ek' (der \u00c4pfel), 'okien' (der Fenster), 'drzew' (der B\u00e4ume). Im Deutschen: 'viele B\u00e4ume' (Plural mit Umlaut). Die Null-Endung im polnischen Gen. Pl. ist \u00fcberraschend f\u00fcr Deutschsprachige."},
      {"id": "gp_np10", "question": "Na \u015bcianie wisz\u0105 du\u017ce _____.", "translation": "An der Wand h\u00e4ngen gro\u00dfe Bilder.", "options": ["obrazy", "obraz\u00f3w", "obrazami", "obraz"], "correct": "obrazy", "explanation": "'Du\u017ce obrazy' (gro\u00dfe Bilder, Nom. Pl.) \u2013 'obraz \u2192 obrazy' (Bild \u2192 Bilder). Maskulina unbelebt bilden den Plural meist mit '-y': 'stol \u2192 sto\u0142y', 'samoch\u00f3d \u2192 samochody', 'obraz \u2192 obrazy'. Im Deutschen: 'Bilder' (Plural mit '-er'). Das Verb 'wisie\u0107' (h\u00e4ngen, intransitiv) im Plural: 'wisz\u0105'. Im Deutschen: 'h\u00e4ngen'. Die Wortstellung 'na \u015bcianie wisz\u0105...' (an der Wand h\u00e4ngen...) ist in beiden Sprachen m\u00f6glich."},
      {"id": "gp_np11", "question": "Zna\u0142am wielu _____.", "translation": "Ich kannte viele Frauen.", "options": ["kobiet", "kobiety", "kobietami", "kobieta"], "correct": "kobiet", "explanation": "'Wielu kobiet' (vieler Frauen, Gen. Pl.) \u2013 nach 'wielu' steht Gen. Pl. 'Kobieta \u2192 kobiety' (Nom. Pl.) \u2192 'kobiet' (Gen. Pl. = Null-Endung). Feminina auf '-a' haben im Gen. Pl. meist eine Null-Endung: 'kobiet' (Frauen), 'ksi\u0105\u017cek' (B\u00fccher), 'lamp' (Lampen). Im Deutschen: 'viele Frauen'. Die polnische Null-Endung bedeutet, dass der Stamm allein steht \u2013 manchmal mit Vokaleinschub: 'ksi\u0105\u017cka \u2192 ksi\u0105\u017cek'."},
      {"id": "gp_np12", "question": "Na niebie \u015bwiec\u0105 _____.", "translation": "Am Himmel leuchten die Sterne.", "options": ["gwiazdy", "gwiazd", "gwiazdami", "gwiazda"], "correct": "gwiazdy", "explanation": "'Gwiazdy \u015bwiec\u0105' (die Sterne leuchten, Nom. Pl.) \u2013 'gwiazda \u2192 gwiazdy' (Stern \u2192 Sterne). Feminina auf '-da' bilden den Plural regelm\u00e4\u00dfig: '-da \u2192 -dy'. Im Deutschen: 'die Sterne' (Stern ist maskulin, Plural mit '-e'). Im Polnischen ist 'gwiazda' feminin. Das Verb '\u015bwieci\u0107' (\u015bwiec\u0105 = 3. Pl.) entspricht dem deutschen 'leuchten'. Die poetische Wortstellung 'Na niebie \u015bwiec\u0105 gwiazdy' ist in beiden Sprachen m\u00f6glich."},
      {"id": "gp_np13", "question": "Mia\u0142am kilka _____ z kursu.", "translation": "Ich hatte einige Freundinnen aus dem Kurs.", "options": ["kole\u017canek", "kole\u017canki", "kole\u017cankami", "kole\u017canka"], "correct": "kole\u017canek", "explanation": "'Kilka kole\u017canek' (einige Freundinnen, Gen. Pl.) \u2013 'kilka' (einige) verlangt Gen. Pl. 'Kole\u017canka \u2192 kole\u017canki' (Nom. Pl.) \u2192 'kole\u017canek' (Gen. Pl. mit Vokaleinschub '-e-'). Feminina auf '-ka' bilden den Gen. Pl. oft mit dem Muster '-ek': 'studentka \u2192 studentek', 'Polka \u2192 Polek'. Im Deutschen: 'einige Freundinnen'. Der Vokaleinschub hilft, Konsonantengruppen auszusprechen."},
      {"id": "gp_np14", "question": "W pokoju s\u0105 dwa _____.", "translation": "Im Zimmer sind zwei Fenster.", "options": ["okna", "okien", "okno", "oknami"], "correct": "okna", "explanation": "'Dwa okna' (zwei Fenster, Nom. Pl.) \u2013 'okno \u2192 okna' (Fenster, Pl.). Neutra auf '-o' bilden den Plural mit '-a'. Im Deutschen: 'zwei Fenster' (Plural = Singular). Der Gen. Pl. w\u00e4re 'okien' (mit Vokaleinschub '-ie-'). Im Polnischen ist die Pluralbildung vielf\u00e4ltiger als im Deutschen: es gibt keine Umlaute, daf\u00fcr verschiedene Endungen und Vokaleinsch\u00fcbe im Gen. Pl. Diese Muster m\u00fcssen systematisch gelernt werden."},
      {"id": "gp_np15", "question": "Przyszli wszyscy moi _____.", "translation": "Alle meine Br\u00fcder sind gekommen.", "options": ["bracia", "brat\u00f3w", "bra\u0107mi", "brat"], "correct": "bracia", "explanation": "'Moi bracia' (meine Br\u00fcder, Nom. Pl. m\u00e4nnl.-pers.) \u2013 'brat \u2192 bracia' (Bruder \u2192 Br\u00fcder) ist stark unregelm\u00e4\u00dfig. Im Deutschen: 'Br\u00fcder' (Umlaut). Beachten Sie: 'przyszli' (sie kamen, mask.-pers. Vergangenheit) und 'moi' (meine, mask.-pers.) \u2013 alle Formen zeigen das m\u00e4nnlich-personale Genus. Das Verb in der m\u00e4nnlich-personalen Vergangenheitsform endet auf '-li', alle anderen auf '-\u0142y'. Diese Kongruenz im gesamten Satz ist typisch polnisch."}
    ]
  }
]

data.extend(new_cats)

# Validate
ids = set()
dupes = []
for cat in data:
    for item in cat['items']:
        if item['id'] in ids:
            dupes.append(item['id'])
        ids.add(item['id'])

short = [item['id'] for cat in new_cats for item in cat['items'] if len(item['explanation']) < 200]
no_blank = [item['id'] for cat in new_cats for item in cat['items'] if '_____' not in item['question']]

with open(f, 'w', encoding='utf-8') as fout:
    json.dump(data, fout, ensure_ascii=False, indent=2)

print(f"After: {len(data)} categories, {sum(len(c.get('items',[])) for c in data)} items")
print(f"Duplicates (new only): {[d for d in dupes if d.startswith('gp_ad') or d.startswith('gp_ac') or d.startswith('gp_adv') or d.startswith('gp_ng') or d.startswith('gp_np')]}")
print(f"Short explanations: {short if short else 'None'}")
print(f"Missing blanks: {no_blank if no_blank else 'None'}")
print(f"Added: {[c['key'] for c in new_cats]}")
