#!/usr/bin/env python3
"""Batch 17: cats 87-91 for german_polish grammar."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "environment_nature",
        "name": "Umwelt und Natur (Środowisko i natura)",
        "description": "Wortschatz und Grammatik rund um Natur, Umwelt und Ökologie auf Polnisch",
        "icon": "leaf.circle",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_env1", "question": "Musimy _____ środowisko naturalne.", "translation": "Wir müssen die natürliche Umwelt schützen.", "options": ["chronić", "chronieć", "ochronić", "chroniać"], "correct": "chronić", "explanation": "'Chronić' (schützen) ist ein Verb der 2. Konjugation (chroni-ę, chroni-sz). Es regiert den Akkusativ: 'chronić środowisko' (die Umwelt schützen). Die unvollendete Form betont die Notwendigkeit des fortlaufenden Schutzes, was im Umweltkontext besonders passend ist.", "difficulty": "intermediate"},
            {"id": "gp_env2", "question": "W lesie rosną _____ drzewa.", "translation": "Im Wald wachsen hohe Bäume.", "options": ["wysokie", "wysoko", "wysoki", "wysoką"], "correct": "wysokie", "explanation": "'Wysokie' ist die Nominativ-Plural-Form des Adjektivs 'wysoki' (hoch). Im Nominativ Plural für unbelebte maskuline und alle femininen/neutralen Substantive wird die Endung '-ie' verwendet. 'Drzewa' (Bäume) ist Neutrum Plural, daher 'wysokie drzewa' (hohe Bäume).", "difficulty": "beginner"},
            {"id": "gp_env3", "question": "Zanieczyszczenie powietrza jest _____ dla zdrowia.", "translation": "Luftverschmutzung ist schädlich für die Gesundheit.", "options": ["szkodliwe", "szkodliwy", "szkodliwą", "szkodliwego"], "correct": "szkodliwe", "explanation": "'Szkodliwe' (schädlich) steht im Nominativ Neutrum Singular, da es sich auf 'zanieczyszczenie' (Verschmutzung, Neutrum) bezieht. 'Dla zdrowia' (für die Gesundheit) – 'dla' regiert den Genitiv: 'zdrowie' → 'zdrowia'. Die Konstruktion entspricht dem deutschen 'schädlich für + Akk.'", "difficulty": "intermediate"},
            {"id": "gp_env4", "question": "Nad _____ mieszka wiele gatunków ptaków.", "translation": "Am See leben viele Vogelarten.", "options": ["jeziorem", "jezioro", "jeziorze", "jeziora"], "correct": "jeziorem", "explanation": "'Nad' (über/am) mit lokaler Bedeutung regiert den Instrumental: 'nad jeziorem' (am See). Vergleiche: 'nad' + Akkusativ = Richtung (wohin), 'nad' + Instrumental = Ort (wo). 'Jezioro' wird zu 'jeziorem' im Instrumental Singular – typische Endung für Neutra auf '-o'.", "difficulty": "intermediate"},
            {"id": "gp_env5", "question": "Powinniśmy segregować _____.", "translation": "Wir sollten den Müll trennen.", "options": ["śmieci", "śmieć", "śmieciami", "śmieciów"], "correct": "śmieci", "explanation": "'Śmieci' (Müll/Abfall) ist ein Pluraliatantum – existiert nur im Plural. Hier steht es im Akkusativ (= Genitiv bei belebten, = Nominativ bei unbelebten Pluralsubstantiven). 'Segregować' (trennen/sortieren) regiert den Akkusativ. 'Powinniśmy' (wir sollten) – die Endung '-śmy' markiert die 1. Person Plural.", "difficulty": "intermediate"},
            {"id": "gp_env6", "question": "Rzeka _____ przez całe miasto.", "translation": "Der Fluss fließt durch die ganze Stadt.", "options": ["płynie", "płynąć", "płyną", "płynę"], "correct": "płynie", "explanation": "'Płynąć' (fließen/schwimmen) ist ein Verb der Bewegung (jak: iść, jechać). Die 3. Person Singular lautet 'płynie' (er/sie/es fließt). Beachte: 'płyną' wäre 3. Person Plural. 'Przez' (durch) regiert den Akkusativ: 'przez całe miasto' (durch die ganze Stadt).", "difficulty": "beginner"},
            {"id": "gp_env7", "question": "Temperatura _____ o pięć stopni.", "translation": "Die Temperatur ist um fünf Grad gestiegen.", "options": ["wzrosła", "wzrósł", "wzrosło", "wzrosły"], "correct": "wzrosła", "explanation": "'Wzrosnąć' (steigen/wachsen) – Vergangenheitsform richtet sich nach dem Genus: 'temperatura' ist feminin, daher 'wzrosła' (fem. Singular). 'O pięć stopni' – 'o' + Akkusativ drückt die Differenz aus (um fünf Grad). 'Wzrósł' (mask.), 'wzrosło' (neutr.), 'wzrosły' (Plural).", "difficulty": "intermediate"},
            {"id": "gp_env8", "question": "Wiele zwierząt jest _____ wyginięciem.", "translation": "Viele Tiere sind vom Aussterben bedroht.", "options": ["zagrożonych", "zagrożone", "zagrożony", "zagrożeni"], "correct": "zagrożonych", "explanation": "'Zagrożonych' (bedroht) steht im Genitiv Plural, weil 'wiele' (viele) den Genitiv regiert: 'wiele zwierząt zagrożonych'. Die Konstruktion 'zagrożony wyginięciem' (bedroht durch Aussterben) – 'wyginięciem' im Instrumental als Ursache/Bedrohung. Beachte: Nach 'wiele' steht das Verb in der 3. Person Singular Neutrum.", "difficulty": "advanced"},
            {"id": "gp_env9", "question": "Trzeba oszczędzać _____ pitną.", "translation": "Man muss Trinkwasser sparen.", "options": ["wodę", "woda", "wody", "wodą"], "correct": "wodę", "explanation": "'Oszczędzać' (sparen) regiert den Akkusativ: 'wodę pitną' (Trinkwasser). 'Woda' → 'wodę' (Akk. Sing. fem.). 'Pitna' (trinkbar) → 'pitną' (Akk. Sing. fem.). 'Trzeba' ist eine unpersönliche Konstruktion für 'man muss' – danach folgt der Infinitiv. Im Deutschen: 'Man muss Trinkwasser sparen.'", "difficulty": "beginner"},
            {"id": "gp_env10", "question": "Energia słoneczna jest _____ odnawialna.", "translation": "Solarenergie ist erneuerbar.", "options": ["źródłem odnawialnym", "odnawialnym źródłem", "odnawialna", "odnawialną"], "correct": "odnawialna", "explanation": "'Odnawialna' (erneuerbar) – Nominativ Singular feminin als Prädikatsadjektiv. 'Energia' ist feminin, daher muss das Adjektiv die feminine Endung '-a' haben. Vergleiche: 'energia jest odnawialna' (Energie ist erneuerbar) vs. 'energię odnawialną' (erneuerbare Energie im Akkusativ).", "difficulty": "beginner"},
            {"id": "gp_env11", "question": "W Polsce jest wiele _____ narodowych.", "translation": "In Polen gibt es viele Nationalparks.", "options": ["parków", "parki", "parkiem", "parkach"], "correct": "parków", "explanation": "'Wiele' (viele) regiert den Genitiv Plural: 'parków narodowych' (Nationalparks). 'Park' → 'parków' (Gen. Pl.) – maskuline Substantive auf Konsonant bekommen '-ów'. 'Narodowy' → 'narodowych' (Gen. Pl.) – Adjektive im Genitiv Plural enden auf '-ych/-ich'. Diese Genitiv-nach-Zahlwort-Regel ist typisch polnisch.", "difficulty": "intermediate"},
            {"id": "gp_env12", "question": "Klimat się _____ bardzo szybko.", "translation": "Das Klima verändert sich sehr schnell.", "options": ["zmienia", "zmienić", "zmieniał", "zmieni"], "correct": "zmienia", "explanation": "'Zmieniać się' (sich verändern) ist ein reflexives Verb im Präsens. 3. Person Singular: 'zmienia się'. Beachte die Wortstellung: 'się' kann vor oder nach dem Verb stehen, aber nie am Satzanfang. 'Bardzo szybko' (sehr schnell) – zwei Adverbien, die sich verstärken. Unvollendeter Aspekt betont den laufenden Prozess.", "difficulty": "intermediate"},
            {"id": "gp_env13", "question": "Nie wolno _____ śmieci w lesie.", "translation": "Es ist verboten, Müll im Wald wegzuwerfen.", "options": ["wyrzucać", "wyrzucić", "wyrzuca", "wyrzucał"], "correct": "wyrzucać", "explanation": "'Nie wolno' (es ist verboten/man darf nicht) + Infinitiv. Nach 'nie wolno' steht gewöhnlich der unvollendete Aspekt 'wyrzucać' (wegwerfen), weil das Verbot generell gilt. 'Wyrzucić' (vollendeter Aspekt) wäre für ein einmaliges Ereignis. 'W lesie' – 'w' + Lokativ: 'las' → 'lesie' (im Wald).", "difficulty": "intermediate"},
            {"id": "gp_env14", "question": "Poziom _____ w rzekach jest niski.", "translation": "Der Wasserstand in den Flüssen ist niedrig.", "options": ["wody", "woda", "wodę", "wodą"], "correct": "wody", "explanation": "'Poziom wody' (Wasserstand) – 'wody' im Genitiv als Attribut (wie im Deutschen: 'Stand des Wassers'). Der Genitiv bei 'poziom' ist obligatorisch – ähnlich wie bei 'ilość' (Menge), 'jakość' (Qualität). 'W rzekach' – Lokativ Plural: 'rzeka' → 'rzekach'. 'Niski' bleibt als mask. Prädikatsadjektiv.", "difficulty": "intermediate"},
            {"id": "gp_env15", "question": "Recykling _____ zmniejszyć ilość odpadów.", "translation": "Recycling hilft, die Abfallmenge zu reduzieren.", "options": ["pomaga", "pomagać", "pomógł", "pomoże"], "correct": "pomaga", "explanation": "'Pomagać' (helfen) im Präsens: 'pomaga' (3. Pers. Sing.). 'Pomagać' + Infinitiv = 'helfen zu + Infinitiv'. 'Zmniejszyć' (reduzieren, vollendeter Aspekt) – nach 'pomagać' steht oft der vollendete Infinitiv als Ziel. 'Ilość odpadów' – Genitiv: 'ilość' (Menge) regiert immer den Genitiv.", "difficulty": "intermediate"}
        ]
    },
    {
        "key": "education_learning",
        "name": "Bildung und Lernen (Edukacja i nauka)",
        "description": "Grammatik und Wortschatz rund um Schule, Studium und Lernen",
        "icon": "graduationcap",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_edu1", "question": "Studiuję _____ na uniwersytecie.", "translation": "Ich studiere Medizin an der Universität.", "options": ["medycynę", "medycyna", "medycyny", "medycyną"], "correct": "medycynę", "explanation": "'Studiować' (studieren) regiert den Akkusativ: 'medycynę' (Medizin). 'Medycyna' → 'medycynę' (Akk. Sing. fem.). 'Na uniwersytecie' – 'na' + Lokativ für Institutionen: 'uniwersytet' → 'uniwersytecie'. Beachte: Man sagt 'na uniwersytecie' (an der Uni), aber 'w szkole' (in der Schule) – verschiedene Präpositionen!", "difficulty": "beginner"},
            {"id": "gp_edu2", "question": "Egzamin z matematyki jest _____.", "translation": "Die Mathematikprüfung ist schwierig.", "options": ["trudny", "trudna", "trudne", "trudno"], "correct": "trudny", "explanation": "'Trudny' (schwierig) – Nominativ maskulin Singular, da 'egzamin' maskulin ist. Vergleiche: 'trudna lekcja' (fem.), 'trudne zadanie' (neutr.). 'Z matematyki' – 'z' + Genitiv für Fachbereich: 'matematyka' → 'matematyki'. Im Deutschen: 'Prüfung in Mathematik' (in + Dativ).", "difficulty": "beginner"},
            {"id": "gp_edu3", "question": "Uczę się polskiego od _____ lat.", "translation": "Ich lerne seit drei Jahren Polnisch.", "options": ["trzech", "trzy", "trzema", "trzem"], "correct": "trzech", "explanation": "'Od trzech lat' (seit drei Jahren) – 'od' regiert den Genitiv, 'trzy' → 'trzech' (Gen.), 'lata' → 'lat' (Gen. Pl.). Beachte: Nach Zahlen 5+ steht im Polnischen der Genitiv Plural + Verb in der 3. Person Singular Neutrum. 'Uczę się' (ich lerne) – reflexives Verb, 'polskiego' im Genitiv nach 'uczyć się'.", "difficulty": "intermediate"},
            {"id": "gp_edu4", "question": "Nauczyciel _____ nam nowe słówka.", "translation": "Der Lehrer erklärt uns die neuen Vokabeln.", "options": ["tłumaczy", "tłumaczyć", "tłumaczył", "tłumaczą"], "correct": "tłumaczy", "explanation": "'Tłumaczyć' (erklären/übersetzen) – 3. Person Singular Präsens: 'tłumaczy'. 'Nam' (uns) im Dativ – der indirekte Empfänger. 'Nowe słówka' (neue Vokabeln) im Akkusativ als direktes Objekt. Beachte: 'Tłumaczyć' kann auch 'übersetzen' bedeuten – der Kontext entscheidet.", "difficulty": "beginner"},
            {"id": "gp_edu5", "question": "Muszę napisać _____ na jutro.", "translation": "Ich muss bis morgen einen Aufsatz schreiben.", "options": ["wypracowanie", "wypracowania", "wypracowaniu", "wypracowaniem"], "correct": "wypracowanie", "explanation": "'Napisać' (schreiben, vollendet) regiert den Akkusativ: 'wypracowanie' (Aufsatz, Neutrum). Bei Neutra ist der Akkusativ = Nominativ. 'Na jutro' (bis morgen/für morgen) – 'na' + Akkusativ in zeitlicher Bedeutung. 'Muszę' (ich muss) + Infinitiv – identische Konstruktion wie im Deutschen.", "difficulty": "beginner"},
            {"id": "gp_edu6", "question": "Studenci przygotowują się _____ egzaminu.", "translation": "Die Studenten bereiten sich auf die Prüfung vor.", "options": ["do", "na", "z", "od"], "correct": "do", "explanation": "'Przygotowywać się do' (sich vorbereiten auf) – 'do' + Genitiv. Im Deutschen: 'sich vorbereiten auf + Akkusativ'. Die Präpositionen unterscheiden sich! 'Do egzaminu' (auf die Prüfung). Vergleiche: 'przygotować się na coś' existiert auch, hat aber eine andere Nuance (sich auf etwas gefasst machen).", "difficulty": "intermediate"},
            {"id": "gp_edu7", "question": "W _____ klasie było trzydziestu uczniów.", "translation": "In meiner Klasse waren dreißig Schüler.", "options": ["mojej", "moją", "mój", "moim"], "correct": "mojej", "explanation": "'W mojej klasie' – 'w' + Lokativ: 'moja klasa' → 'w mojej klasie'. Feminin Lokativ Singular des Possessivpronomens: 'moja' → 'mojej'. Beachte: 'Trzydziestu uczniów' – nach Zahlen ab 5 steht das Substantiv im Genitiv Plural: 'uczeń' → 'uczniów'. Die männlich-personale Form 'trzydziestu' ist hier obligatorisch.", "difficulty": "intermediate"},
            {"id": "gp_env_edu8", "question": "Dostała piątkę _____ sprawdzianu.", "translation": "Sie hat eine Fünf (Bestnote) in der Klassenarbeit bekommen.", "options": ["ze", "na", "w", "od"], "correct": "ze", "explanation": "'Dostać piątkę ze sprawdzianu' (eine Fünf in der Klassenarbeit bekommen) – 'ze' (= z vor bestimmten Konsonantengruppen) + Genitiv. In Polen ist 5 die Bestnote (wie 1 in Deutschland!). 'Sprawdzian' → 'sprawdzianu' (Gen.). 'Piątka' – die Note als umgangssprachliches Femininum.", "difficulty": "intermediate"},
            {"id": "gp_edu9", "question": "Na lekcji _____ notatki.", "translation": "Im Unterricht mache ich mir Notizen.", "options": ["robię", "robić", "zrobię", "robiłem"], "correct": "robię", "explanation": "'Robić notatki' (Notizen machen) – feste Wendung. 'Robię' – 1. Person Singular Präsens des Verbs 'robić' (machen). Unvollendeter Aspekt für wiederholte Handlung. 'Na lekcji' – 'na' + Lokativ: 'lekcja' → 'lekcji' (im Unterricht). Beachte: 'na lekcji' (im Unterricht), nicht 'w lekcji'!", "difficulty": "beginner"},
            {"id": "gp_edu10", "question": "Chciałbym się _____ na kurs językowy.", "translation": "Ich würde mich gerne für einen Sprachkurs anmelden.", "options": ["zapisać", "zapisywać", "zapisu", "zapisem"], "correct": "zapisać", "explanation": "'Zapisać się na' (sich anmelden für) – 'na' + Akkusativ für Kurse/Veranstaltungen: 'na kurs'. 'Chciałbym' (ich würde gerne) – Konditionalform von 'chcieć'. Nach 'chciałbym' steht der Infinitiv, hier vollendeter Aspekt 'zapisać się' (einmalige Handlung: sich anmelden). 'Językowy' (Sprach-) – Adjektiv von 'język' (Sprache).", "difficulty": "intermediate"},
            {"id": "gp_edu11", "question": "Biblioteka jest otwarta do godziny _____.", "translation": "Die Bibliothek ist bis achtzehn Uhr geöffnet.", "options": ["osiemnastej", "osiemnaście", "osiemnasta", "osiemnastą"], "correct": "osiemnastej", "explanation": "'Do godziny osiemnastej' (bis 18 Uhr) – 'do' + Genitiv: 'godzina osiemnasta' → 'godziny osiemnastej'. Ordinalzahlen als Uhrzeiten stehen im Genitiv nach 'do'. Die feminine Endung '-ej' (Gen. Sing. fem.) folgt dem Genus von 'godzina' (Stunde, feminin). In Polen wird die 24-Stunden-Uhr verwendet.", "difficulty": "intermediate"},
            {"id": "gp_edu12", "question": "Zdałem egzamin _____ dobrym wynikiem.", "translation": "Ich habe die Prüfung mit einem guten Ergebnis bestanden.", "options": ["z", "na", "do", "w"], "correct": "z", "explanation": "'Zdać egzamin z dobrym wynikiem' (Prüfung mit gutem Ergebnis bestehen) – 'z' + Instrumental = 'mit': 'z dobrym wynikiem'. 'Zdać' (bestehen, vollendet) vs. 'zdawać' (ablegen, unvollendet). 'Dobrym' – Instrumental maskulin Singular des Adjektivs 'dobry'. 'Zdałem' – Vergangenheitsform maskulin.", "difficulty": "intermediate"},
            {"id": "gp_edu13", "question": "Umiem _____ w trzech językach.", "translation": "Ich kann in drei Sprachen schreiben.", "options": ["pisać", "napisać", "piszę", "pisałem"], "correct": "pisać", "explanation": "'Umieć' (können/fähig sein) + unvollendeter Infinitiv für eine allgemeine Fähigkeit: 'umiem pisać' (ich kann schreiben). 'W trzech językach' – 'w' + Lokativ Plural: 'język' → 'językach', 'trzy' → 'trzech'. Beachte: 'Umieć' betont erlernte Fähigkeit (können), während 'móc' eher Möglichkeit ausdrückt (dürfen/können).", "difficulty": "intermediate"},
            {"id": "gp_edu14", "question": "Profesor wyjaśnił nam _____ problem.", "translation": "Der Professor hat uns das schwierige Problem erklärt.", "options": ["trudny", "trudnego", "trudne", "trudnym"], "correct": "trudny", "explanation": "'Trudny problem' – Akkusativ maskulin unbelebt = Nominativ: 'trudny'. Bei unbelebten maskulinen Substantiven bleibt der Akkusativ gleich dem Nominativ. 'Wyjaśnić' (erklären, vollendet) regiert den Dativ der Person ('nam' = uns) und den Akkusativ der Sache ('trudny problem'). Im Deutschen: erklären + Dativ + Akkusativ – parallel!", "difficulty": "beginner"},
            {"id": "gp_edu15", "question": "Po _____ studiów szukam pracy.", "translation": "Nach dem Abschluss des Studiums suche ich Arbeit.", "options": ["ukończeniu", "ukończenie", "ukończyć", "ukończony"], "correct": "ukończeniu", "explanation": "'Po ukończeniu' (nach dem Abschluss) – 'po' + Lokativ: 'ukończenie' → 'ukończeniu'. 'Ukończenie studiów' (Abschluss des Studiums) – Genitiv: 'studia' → 'studiów'. 'Szukać' (suchen) regiert den Genitiv: 'szukam pracy' (ich suche Arbeit). Im Deutschen: 'suchen' + Akkusativ, im Polnischen: 'szukać' + Genitiv!", "difficulty": "advanced"}
        ]
    },
    {
        "key": "sports_hobbies",
        "name": "Sport und Hobbys (Sport i hobby)",
        "description": "Grammatik und Wortschatz rund um Freizeit, Sport und Hobbys",
        "icon": "sportscourt",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_spo1", "question": "Lubię _____ w piłkę nożną.", "translation": "Ich spiele gerne Fußball.", "options": ["grać", "zagrać", "gram", "grając"], "correct": "grać", "explanation": "'Lubić' (mögen/gerne tun) + unvollendeter Infinitiv: 'lubię grać' (ich spiele gerne). Der unvollendete Aspekt nach 'lubić' drückt eine generelle Vorliebe aus. 'Grać w' + Akkusativ für Spiele: 'w piłkę nożną' (Fußball). Im Deutschen: 'Fußball spielen' – im Polnischen mit Präposition 'w'!", "difficulty": "beginner"},
            {"id": "gp_spo2", "question": "Co tydzień chodzę na _____.", "translation": "Jede Woche gehe ich ins Schwimmbad.", "options": ["basen", "basenie", "basenu", "basenem"], "correct": "basen", "explanation": "'Chodzić na' + Akkusativ = regelmäßig hingehen (Richtung): 'na basen' (ins Schwimmbad). 'Basen' bleibt unverändert im Akkusativ (maskulin unbelebt). Vergleiche: 'na basenie' (Lokativ = im Schwimmbad, Ort). 'Co tydzień' (jede Woche) – 'co' + Akkusativ drückt Regelmäßigkeit aus.", "difficulty": "beginner"},
            {"id": "gp_spo3", "question": "Mój brat jest _____ piłkarzem.", "translation": "Mein Bruder ist ein guter Fußballspieler.", "options": ["dobrym", "dobry", "dobrze", "dobrą"], "correct": "dobrym", "explanation": "'Być' (sein) + Instrumental: 'jest dobrym piłkarzem' (ist ein guter Fußballspieler). Im Polnischen steht nach 'być' das Prädikativ im Instrumental, nicht im Nominativ wie im Deutschen! 'Dobry' → 'dobrym' (Instr. mask. Sing.), 'piłkarz' → 'piłkarzem' (Instr. mask. Sing.).", "difficulty": "intermediate"},
            {"id": "gp_spo4", "question": "Zawody pływackie _____ się w sobotę.", "translation": "Der Schwimmwettbewerb findet am Samstag statt.", "options": ["odbędą", "odbędzie", "odbywa", "odbywać"], "correct": "odbędą", "explanation": "'Odbywać się' / 'odbyć się' (stattfinden) – reflexives Verb. 'Zawody' (Wettbewerb) ist Pluraliatantum, daher 3. Person Plural: 'odbędą się' (werden stattfinden, vollendet Futur). 'W sobotę' – 'w' + Akkusativ für Wochentage: 'sobota' → 'sobotę'. Dieses Muster gilt für alle Wochentage.", "difficulty": "intermediate"},
            {"id": "gp_spo5", "question": "Biegam _____ rano.", "translation": "Ich jogge jeden Morgen.", "options": ["codziennie", "codzienny", "codzienną", "codziennym"], "correct": "codziennie", "explanation": "'Codziennie' (täglich/jeden Tag) ist ein Adverb, abgeleitet vom Adjektiv 'codzienny'. Adverbien enden oft auf '-ie' oder '-o' (von Adjektiven auf '-ny' → '-nie'). 'Rano' (morgens) ist ebenfalls ein Adverb. 'Biegać' (joggen, unvollendet, für wiederholte Handlung) – 1. Person Singular: 'biegam'.", "difficulty": "beginner"},
            {"id": "gp_spo6", "question": "Interesuje się _____ i muzyką.", "translation": "Ich interessiere mich für Malerei und Musik.", "options": ["malarstwem", "malarstwo", "malarstwa", "malarstwu"], "correct": "malarstwem", "explanation": "'Interesować się' (sich interessieren für) + Instrumental: 'malarstwem' (Malerei) und 'muzyką' (Musik). Die Rektion ist anders als im Deutschen: 'interessieren sich für + Akk.' vs. 'interesować się + Instr.' 'Malarstwo' → 'malarstwem' (Instr. Neutr. Sing.). 'Muzyka' → 'muzyką' (Instr. Fem. Sing.).", "difficulty": "intermediate"},
            {"id": "gp_spo7", "question": "Zaczęłam _____ na gitarze rok temu.", "translation": "Ich habe vor einem Jahr angefangen, Gitarre zu spielen.", "options": ["grać", "zagrać", "gram", "grałam"], "correct": "grać", "explanation": "'Zacząć' (anfangen) + unvollendeter Infinitiv: 'zaczęłam grać' (ich habe angefangen zu spielen). 'Zaczęłam' – Vergangenheitsform feminin (die Sprecherin ist weiblich). 'Na gitarze' (auf der Gitarre) – 'na' + Lokativ für Instrumente: 'gitara' → 'gitarze'. 'Rok temu' (vor einem Jahr) – 'temu' = 'ago'.", "difficulty": "intermediate"},
            {"id": "gp_spo8", "question": "Nasz zespół _____ mecz trzy do jednego.", "translation": "Unsere Mannschaft hat das Spiel drei zu eins gewonnen.", "options": ["wygrał", "wygrali", "wygrała", "wygrało"], "correct": "wygrał", "explanation": "'Wygrać' (gewinnen, vollendet) – 'zespół' (Mannschaft/Team) ist maskulin, daher 'wygrał' (mask. Sing. Vergangenheit). Obwohl das Team aus vielen Personen besteht, ist das grammatische Geschlecht entscheidend! 'Trzy do jednego' (drei zu eins) – typische Ergebnisangabe im Sport.", "difficulty": "beginner"},
            {"id": "gp_spo9", "question": "Jeżdżę na _____ zimą.", "translation": "Im Winter fahre ich Ski.", "options": ["nartach", "narty", "nart", "nartami"], "correct": "nartach", "explanation": "'Jeździć na nartach' (Ski fahren) – feste Wendung mit 'na' + Lokativ: 'narty' → 'nartach'. Beachte: 'Jechać na narty' (Akkusativ = Richtung: zum Skifahren fahren) vs. 'jeździć na nartach' (Lokativ = die Tätigkeit des Skifahrens). Dieser Unterschied zwischen Richtung und Tätigkeit ist typisch polnisch.", "difficulty": "intermediate"},
            {"id": "gp_spo10", "question": "Moje hobby to _____ znaczków.", "translation": "Mein Hobby ist Briefmarkensammeln.", "options": ["zbieranie", "zbierać", "zbiera", "zbierając"], "correct": "zbieranie", "explanation": "'Zbieranie' (das Sammeln) – Verbalsubstantiv von 'zbierać' (sammeln). 'Zbieranie znaczków' (Briefmarkensammeln) – 'znaczków' im Genitiv Plural weil Verbalsubstantive den Genitiv des Objekts verlangen. 'Moje hobby to...' – 'to' als Kopula in Definitionssätzen. 'Znaczek' → 'znaczków' (Gen. Pl. mask.).", "difficulty": "intermediate"},
            {"id": "gp_spo11", "question": "Po treningu jestem bardzo _____.", "translation": "Nach dem Training bin ich sehr müde.", "options": ["zmęczony", "zmęczona", "zmęczone", "zmęczoną"], "correct": "zmęczony", "explanation": "'Zmęczony' (müde, maskulin) – Prädikatsadjektiv im Nominativ, da es nach 'jestem' (ich bin) steht. Bei 'być' im Präsens: Nominativ (nicht Instrumental!). Die Form richtet sich nach dem Geschlecht des Sprechers: 'zmęczony' (Mann), 'zmęczona' (Frau). 'Po treningu' – 'po' + Lokativ: 'trening' → 'treningu'.", "difficulty": "beginner"},
            {"id": "gp_spo12", "question": "Chciałbym nauczyć się _____ konno.", "translation": "Ich würde gerne Reiten lernen.", "options": ["jeździć", "jechać", "jazdy", "jeżdżę"], "correct": "jeździć", "explanation": "'Nauczyć się' (lernen) + unvollendeter Infinitiv für Fähigkeiten: 'nauczyć się jeździć' (Reiten lernen). 'Jeździć konno' (reiten) – 'konno' ist ein Adverb (zu Pferd). 'Jeździć' (unvollendet, wiederholte Bewegung) vs. 'jechać' (einmalige Bewegung). 'Chciałbym' (ich würde gerne) – Konditional.", "difficulty": "intermediate"},
            {"id": "gp_spo13", "question": "W wolnym _____ czytam książki.", "translation": "In meiner Freizeit lese ich Bücher.", "options": ["czasie", "czas", "czasu", "czasem"], "correct": "czasie", "explanation": "'W wolnym czasie' (in der Freizeit) – 'w' + Lokativ: 'czas' → 'czasie', 'wolny' → 'wolnym' (Lok. mask. Sing.). 'Czytać książki' (Bücher lesen) – Akkusativ Plural: 'książka' → 'książki'. Der Akkusativ Plural femininer Substantive auf '-a' endet auf '-i/-y'. Die Konstruktion ist dem Deutschen parallel.", "difficulty": "beginner"},
            {"id": "gp_spo14", "question": "Trener kazał _____ biegać dookoła boiska.", "translation": "Der Trainer hat uns befohlen, um den Platz zu laufen.", "options": ["nam", "nas", "nami", "nasz"], "correct": "nam", "explanation": "'Kazać' (befehlen) regiert den Dativ der Person + Infinitiv: 'kazał nam biegać' (hat uns befohlen zu laufen). 'Nam' (uns) im Dativ. Im Deutschen: 'befehlen' + Dativ – gleiche Rektion! 'Dookoła boiska' (um den Platz herum) – 'dookoła' + Genitiv: 'boisko' → 'boiska'.", "difficulty": "intermediate"},
            {"id": "gp_spo15", "question": "Mecz zakończył się _____ remisem.", "translation": "Das Spiel endete mit einem Unentschieden.", "options": ["bezbramkowym", "bezbramkowy", "bezbramkowego", "bezbramkowe"], "correct": "bezbramkowym", "explanation": "'Zakończyć się' + Instrumental: 'zakończył się bezbramkowym remisem' (endete mit einem torlosen Unentschieden). 'Remis' → 'remisem' (Instr. mask.), 'bezbramkowy' → 'bezbramkowym' (Instr. mask.). 'Bezbramkowy' ist ein Kompositum: 'bez' (ohne) + 'bramka' (Tor) + '-owy' (Adjektivsuffix). Vergleiche: deutsch 'torlos'.", "difficulty": "advanced"}
        ]
    },
    {
        "key": "feelings_emotions_advanced",
        "name": "Gefühle und Emotionen – Fortgeschritten (Uczucia i emocje zaawansowane)",
        "description": "Erweiterte Ausdrücke für Emotionen, Stimmungen und psychische Zustände",
        "icon": "brain.head.profile",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_fea1", "question": "Nie mogę się _____ z tą stratą.", "translation": "Ich kann mich mit diesem Verlust nicht abfinden.", "options": ["pogodzić", "godzić", "pogodzi", "pogodził"], "correct": "pogodzić", "explanation": "'Pogodzić się z' + Instrumental (sich abfinden mit): 'pogodzić się z tą stratą'. 'Nie mogę' + vollendeter Infinitiv für eine konkrete Unfähigkeit. 'Tą stratą' – Instrumental feminin: 'ta strata' → 'tą stratą'. Das reflexive 'się' steht typischerweise nach 'móc' und vor dem Infinitiv: 'nie mogę się pogodzić'.", "difficulty": "advanced"},
            {"id": "gp_fea2", "question": "Jest mi _____ z powodu wypadku.", "translation": "Mir ist bange wegen des Unfalls.", "options": ["przykro", "przykra", "przykry", "przykre"], "correct": "przykro", "explanation": "'Jest mi przykro' (es tut mir leid/mir ist unangenehm) – unpersönliche Konstruktion mit Dativ + Adverb. 'Przykro' ist die adverbiale Form von 'przykry' (unangenehm). 'Z powodu' + Genitiv (wegen): 'z powodu wypadku' (wegen des Unfalls). Im Deutschen: 'wegen' + Genitiv – gleiche Kasusrektion!", "difficulty": "intermediate"},
            {"id": "gp_fea3", "question": "Jestem _____ na całą sytuację.", "translation": "Ich bin wütend über die ganze Situation.", "options": ["wściekły", "wściekła", "wściekłym", "wściekłe"], "correct": "wściekły", "explanation": "'Wściekły na' + Akkusativ (wütend auf/über): 'wściekły na całą sytuację'. Nach 'jestem' (bin) stehen Prädikatsadjektive im Nominativ. 'Wściekły' (mask. Nom.) – Form für männlichen Sprecher. Eine Frau sagt 'jestem wściekła'. 'Całą sytuację' – Akkusativ feminin: 'cała sytuacja' → 'całą sytuację'.", "difficulty": "intermediate"},
            {"id": "gp_fea4", "question": "Cieszę się _____ twoich sukcesów.", "translation": "Ich freue mich über deine Erfolge.", "options": ["z", "na", "w", "do"], "correct": "z", "explanation": "'Cieszyć się z' + Genitiv (sich freuen über): 'cieszę się z twoich sukcesów'. Im Deutschen: 'freuen sich über + Akkusativ'. Die Rektion ist verschieden! 'Twoich sukcesów' – Genitiv Plural: 'twój sukces' → 'twoich sukcesów'. Alternativ: 'cieszyć się na' + Akkusativ = sich auf etwas freuen (Zukunft).", "difficulty": "intermediate"},
            {"id": "gp_fea5", "question": "Współczuję _____ z powodu choroby.", "translation": "Ich bedauere ihn/sie wegen der Krankheit.", "options": ["mu", "go", "nim", "jemu"], "correct": "mu", "explanation": "'Współczuć' (bedauern/mitfühlen) + Dativ der Person: 'współczuję mu' (ich bedauere ihm). 'Mu' ist die kurze Dativform von 'on/ono' (er/es). 'Z powodu choroby' (wegen der Krankheit) – 'choroba' → 'choroby' (Gen. Sing.). Im Deutschen: 'jemandem sein Mitgefühl aussprechen' – auch mit Dativ!", "difficulty": "intermediate"},
            {"id": "gp_fea6", "question": "Strasznie się _____, że nie zdążę.", "translation": "Ich habe schreckliche Angst, dass ich es nicht rechtzeitig schaffe.", "options": ["boję", "boje", "boisz", "bali"], "correct": "boję", "explanation": "'Bać się' (Angst haben/sich fürchten) – 1. Person Singular: 'boję się'. Beachte den Akzentwechsel: 'bać' → 'boję'. 'Strasznie' (schrecklich) als Intensivierer. 'Że nie zdążę' (dass ich es nicht schaffe) – Nebensatz mit 'że'. 'Zdążyć' (rechtzeitig schaffen) – vollendeter Aspekt im Futur: 'zdążę'.", "difficulty": "intermediate"},
            {"id": "gp_fea7", "question": "Tęsknię _____ domem rodzinnym.", "translation": "Ich vermisse mein Elternhaus.", "options": ["za", "do", "po", "na"], "correct": "za", "explanation": "'Tęsknić za' + Instrumental (vermissen/sich sehnen nach): 'tęsknię za domem rodzinnym'. 'Dom rodzinny' → 'domem rodzinnym' (Instr. mask.). Im Deutschen: 'sich sehnen nach + Dativ'. Beachte: 'Tęsknić do' + Genitiv existiert auch (veraltet, literarisch). Die Version mit 'za' ist die moderne Standardform.", "difficulty": "intermediate"},
            {"id": "gp_fea8", "question": "Czuję się _____ w nowym miejscu.", "translation": "Ich fühle mich unsicher am neuen Ort.", "options": ["niepewnie", "niepewny", "niepewna", "niepewną"], "correct": "niepewnie", "explanation": "'Czuć się' + Adverb: 'czuję się niepewnie' (ich fühle mich unsicher). Nach 'czuć się' kann ein Adverb oder ein Adjektiv stehen. Das Adverb 'niepewnie' von 'niepewny' (unsicher) ist hier korrekt. 'W nowym miejscu' – Lokativ: 'nowe miejsce' → 'nowym miejscu'. 'Nie-' als Verneinungspräfix (wie dt. 'un-').", "difficulty": "intermediate"},
            {"id": "gp_fea9", "question": "Żałuję, że nie _____ jej prawdy.", "translation": "Ich bereue, dass ich ihr nicht die Wahrheit gesagt habe.", "options": ["powiedziałem", "powiedzieć", "mówię", "powiem"], "correct": "powiedziałem", "explanation": "'Żałować, że' (bereuen, dass) + Vergangenheitsform: 'żałuję, że nie powiedziałem'. 'Powiedzieć' (sagen, vollendet) → 'powiedziałem' (ich habe gesagt, mask.). 'Jej' – Dativ feminin (ihr). 'Prawdy' – Genitiv nach Negation: 'nie powiedziałem prawdy' statt 'prawdę'. Diese Genitivregel nach Negation ist obligatorisch!", "difficulty": "advanced"},
            {"id": "gp_fea10", "question": "Martwię się _____ przyszłość.", "translation": "Ich mache mir Sorgen um die Zukunft.", "options": ["o", "za", "z", "na"], "correct": "o", "explanation": "'Martwić się o' + Akkusativ (sich Sorgen machen um): 'martwię się o przyszłość'. 'Przyszłość' (Zukunft, feminin) bleibt im Akkusativ unverändert (da feminin auf Konsonant). Im Deutschen: 'sich Sorgen machen um + Akkusativ' – gleiche Kasusrektion! Vergleiche: 'martwić się czymś' (Instr.) = sich wegen etwas grämen.", "difficulty": "intermediate"},
            {"id": "gp_fea11", "question": "Jest mi _____ za twój podarunek.", "translation": "Ich bin dir für dein Geschenk dankbar.", "options": ["wdzięcznie", "wdzięczny", "wdzięczna", "wdzięczne"], "correct": "wdzięcznie", "explanation": "'Jest mi wdzięcznie' (ich bin dankbar) – unpersönliche Konstruktion mit Dativ 'mi' + Adverb 'wdzięcznie'. Alternativ: 'jestem wdzięczny/a' (persönliche Konstruktion mit Adjektiv im Nominativ). 'Za' + Akkusativ für den Grund der Dankbarkeit: 'za twój podarunek' (für dein Geschenk). Beide Konstruktionen sind korrekt.", "difficulty": "intermediate"},
            {"id": "gp_fea12", "question": "Podziwiam go _____ odwagę.", "translation": "Ich bewundere ihn für seinen Mut.", "options": ["za", "na", "z", "w"], "correct": "za", "explanation": "'Podziwiać kogoś za' + Akkusativ (jemanden bewundern für): 'podziwiam go za odwagę'. 'Go' – Akkusativ männlich (ihn). 'Odwaga' → 'odwagę' (Akk. fem.). Im Deutschen: 'bewundern für + Akkusativ' – parallel! 'Podziwiać' ist ein Verb der psychischen Einstellung mit der Rektion: Akkusativ der Person + 'za' + Akkusativ des Grundes.", "difficulty": "intermediate"},
            {"id": "gp_fea13", "question": "Nie potrafię _____ swojego gniewu.", "translation": "Ich kann meine Wut nicht kontrollieren.", "options": ["kontrolować", "kontroluję", "skontrolować", "kontrolą"], "correct": "kontrolować", "explanation": "'Nie potrafić' (nicht können/nicht in der Lage sein) + unvollendeter Infinitiv: 'nie potrafię kontrolować'. 'Kontrolować' + Genitiv nach Negation: 'swojego gniewu' (meiner Wut). 'Swój' → 'swojego' (Gen. mask. Sing.) – reflexives Possessivpronomen. Ohne Negation: 'potrafię kontrolować swój gniew' (Akkusativ).", "difficulty": "advanced"},
            {"id": "gp_fea14", "question": "Cały dzień byłem w _____ nastroju.", "translation": "Den ganzen Tag war ich schlechter Laune.", "options": ["złym", "złego", "zły", "złe"], "correct": "złym", "explanation": "'W złym nastroju' (in schlechter Laune) – 'w' + Lokativ: 'zły nastrój' → 'w złym nastroju'. 'Zły' → 'złym' (Lok. mask. Sing.). 'Cały dzień' (den ganzen Tag) – Akkusativ der Zeitdauer ohne Präposition. 'Byłem' – Vergangenheitsform maskulin von 'być'. Vergleiche: 'w dobrym nastroju' (in guter Laune).", "difficulty": "intermediate"},
            {"id": "gp_fea15", "question": "Z trudem _____ łzy.", "translation": "Mit Mühe hielt ich die Tränen zurück.", "options": ["powstrzymałem", "powstrzymywać", "powstrzymuje", "powstrzymać"], "correct": "powstrzymałem", "explanation": "'Powstrzymać' (zurückhalten, vollendet) – 'powstrzymałem' (ich habe zurückgehalten, mask. Verg.). 'Z trudem' (mit Mühe) – 'z' + Instrumental: 'trud' → 'trudem'. 'Łzy' (Tränen) im Akkusativ (= Nominativ bei femininen Plural). Die vollendete Form 'powstrzymałem' zeigt, dass es gelungen ist – die unvollendete 'powstrzymywałem' würde Kampf ohne Ergebnis betonen.", "difficulty": "advanced"}
        ]
    },
    {
        "key": "weather_seasons",
        "name": "Wetter und Jahreszeiten (Pogoda i pory roku)",
        "description": "Grammatik und Wortschatz rund um Wetter, Klima und Jahreszeiten",
        "icon": "cloud.sun",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_wea1", "question": "Dzisiaj _____ słońce.", "translation": "Heute scheint die Sonne.", "options": ["świeci", "świecić", "świecą", "świecił"], "correct": "świeci", "explanation": "'Świecić' (scheinen/leuchten) – 3. Person Singular Präsens: 'świeci'. 'Słońce' (Sonne, Neutrum) ist das Subjekt. 'Dzisiaj' (heute) als temporales Adverb am Satzanfang – im Polnischen flexibler als im Deutschen (keine V2-Regel). Beachte: 'słońce świeci' – die natürliche Wortstellung im Polnischen.", "difficulty": "beginner"},
            {"id": "gp_wea2", "question": "W zimie często _____.", "translation": "Im Winter schneit es oft.", "options": ["pada śnieg", "pada deszcz", "świeci słońce", "wieje wiatr"], "correct": "pada śnieg", "explanation": "'Padać' (fallen) wird für Niederschlag verwendet: 'pada śnieg' (es schneit, wörtl.: Schnee fällt), 'pada deszcz' (es regnet). Im Deutschen: 'es schneit/regnet' – unpersönlich mit 'es'. Im Polnischen: Subjekt 'śnieg/deszcz' + Verb 'pada'. 'W zimie' – 'w' + Lokativ: 'zima' → 'zimie'.", "difficulty": "beginner"},
            {"id": "gp_wea3", "question": "Latem jest _____ niż zimą.", "translation": "Im Sommer ist es wärmer als im Winter.", "options": ["cieplej", "ciepło", "ciepły", "cieplejszy"], "correct": "cieplej", "explanation": "'Cieplej' ist der Komparativ des Adverbs 'ciepło' (warm). Adverb-Komparativ: 'ciepło' → 'cieplej' (wärmer). 'Niż' (als) leitet den Vergleich ein: 'cieplej niż zimą'. 'Latem' und 'zimą' – Instrumental ohne Präposition für Jahreszeiten! Dies ist eine Besonderheit: 'latem' (im Sommer), 'zimą' (im Winter), 'wiosną' (im Frühling), 'jesienią' (im Herbst).", "difficulty": "intermediate"},
            {"id": "gp_wea4", "question": "Temperatura spadła _____ zera.", "translation": "Die Temperatur ist unter null gefallen.", "options": ["poniżej", "ponad", "powyżej", "około"], "correct": "poniżej", "explanation": "'Poniżej' (unter/unterhalb) + Genitiv: 'poniżej zera' (unter null). Vergleiche: 'powyżej zera' (über null), 'ponad' (über/mehr als). 'Spadła' – Vergangenheitsform fem. von 'spaść' (fallen), weil 'temperatura' feminin ist. 'Zero' → 'zera' (Gen. Neutr.).", "difficulty": "intermediate"},
            {"id": "gp_wea5", "question": "Na _____ wieje silny wiatr.", "translation": "Draußen weht ein starker Wind.", "options": ["dworze", "dwór", "dworu", "dworem"], "correct": "dworze", "explanation": "'Na dworze' (draußen) – feste Wendung mit 'na' + Lokativ: 'dwór' → 'dworze'. 'Wiać' (wehen) – 3. Person Singular: 'wieje'. 'Silny wiatr' (starker Wind) im Nominativ als Subjekt. Im Deutschen: unpersönlich ('es weht'), im Polnischen: 'wiatr wieje' (der Wind weht) – mit Subjekt.", "difficulty": "beginner"},
            {"id": "gp_wea6", "question": "Wiosną _____ kwitną.", "translation": "Im Frühling blühen die Blumen.", "options": ["kwiaty", "kwiatów", "kwiatami", "kwiatom"], "correct": "kwiaty", "explanation": "'Kwiaty' (Blumen) im Nominativ Plural als Subjekt: 'kwiaty kwitną' (Blumen blühen). 'Kwitnąć' (blühen) – 3. Person Plural: 'kwitną'. 'Wiosną' – Instrumental ohne Präposition für 'im Frühling'. Die Endung '-ą' ist typisch für den Instrumental Singular femininer Substantive auf '-a'. Beachte: 'kwiat' (Blume) ist maskulin!", "difficulty": "beginner"},
            {"id": "gp_wea7", "question": "Pada _____, weź parasol.", "translation": "Es regnet, nimm einen Regenschirm.", "options": ["deszcz", "deszczu", "deszczem", "deszcze"], "correct": "deszcz", "explanation": "'Pada deszcz' (es regnet) – 'deszcz' im Nominativ als Subjekt. 'Weź' ist der Imperativ von 'wziąć' (nehmen) – 2. Person Singular: 'weź!'. 'Parasol' (Regenschirm) im Akkusativ (= Nominativ bei maskulin unbelebt). Die zwei Sätze sind durch Komma verbunden – im Polnischen ist das Komma vor Konjunktionen/neuen Teilen obligatorisch.", "difficulty": "beginner"},
            {"id": "gp_wea8", "question": "Jesienią _____ są krótsze.", "translation": "Im Herbst sind die Tage kürzer.", "options": ["dni", "dzień", "dniom", "dniami"], "correct": "dni", "explanation": "'Dni' (Tage) – Nominativ Plural von 'dzień' (Tag). 'Dzień' hat einen unregelmäßigen Plural: 'dni' (nicht 'dzienie'). 'Krótsze' ist der Komparativ Plural von 'krótki' (kurz): 'krótki' → 'krótszy' → 'krótsze' (Plural). 'Jesienią' (im Herbst) – Instrumental ohne Präposition für Jahreszeiten.", "difficulty": "beginner"},
            {"id": "gp_wea9", "question": "Prognoza pogody mówi, że jutro _____ burza.", "translation": "Die Wettervorhersage sagt, dass morgen ein Gewitter kommt.", "options": ["będzie", "była", "jest", "były"], "correct": "będzie", "explanation": "'Będzie burza' (es wird ein Gewitter geben) – Futur von 'być': 'będzie'. 'Burza' (Gewitter, feminin) als Subjekt im Nominativ. 'Prognoza pogody' (Wettervorhersage) – 'pogody' im Genitiv als Attribut. 'Że jutro będzie' – Nebensatz mit 'że'; im Polnischen geht das Verb nicht ans Ende (anders als im Deutschen!).", "difficulty": "beginner"},
            {"id": "gp_wea10", "question": "Dzisiaj jest _____ stopni Celsjusza.", "translation": "Heute sind es zwanzig Grad Celsius.", "options": ["dwadzieścia", "dwadzieście", "dwudziesty", "dwudziestu"], "correct": "dwadzieścia", "explanation": "'Dwadzieścia' (zwanzig) – Grundzahlwort. Zahlwörter 5-20 stehen mit dem Genitiv Plural: 'dwadzieścia stopni' (zwanzig Grad). 'Stopień' → 'stopni' (Gen. Pl.). Beachte: Das Verb steht in der 3. Person Singular Neutrum: 'jest dwadzieścia stopni' (es sind zwanzig Grad). Typisch polnische Numeruskonstruktion!", "difficulty": "intermediate"},
            {"id": "gp_wea11", "question": "Niebo jest _____ chmur.", "translation": "Der Himmel ist wolkenlos.", "options": ["bez", "z", "pod", "nad"], "correct": "bez", "explanation": "'Bez chmur' (ohne Wolken/wolkenlos) – 'bez' + Genitiv: 'chmura' → 'chmur' (Gen. Pl.). Im Deutschen: zusammengesetztes Adjektiv 'wolkenlos'. Im Polnischen: meist Präpositionalphrase 'bez chmur' statt eines Kompositums. 'Niebo' (Himmel, Neutrum) – 'jest' (ist) als Kopula. Vergleiche: 'zachmurzony' (bewölkt) als Adjektiv-Alternative.", "difficulty": "beginner"},
            {"id": "gp_wea12", "question": "Po _____ wyszło słońce.", "translation": "Nach dem Regen kam die Sonne heraus.", "options": ["deszczu", "deszcz", "deszczem", "deszcze"], "correct": "deszczu", "explanation": "'Po deszczu' (nach dem Regen) – 'po' + Lokativ: 'deszcz' → 'deszczu'. 'Wyjść' (herauskommen, vollendet) – 'wyszło' (Neutrum Vergangenheit, weil 'słońce' Neutrum ist). Beachte: 'Wyjść' wird metaphorisch für die Sonne verwendet (herauskommen), wie im Deutschen: 'die Sonne kam heraus'.", "difficulty": "beginner"},
            {"id": "gp_wea13", "question": "Mróz jest tak silny, że _____ zamarzła.", "translation": "Der Frost ist so stark, dass die Straße zugefroren ist.", "options": ["droga", "drodze", "drogę", "drogą"], "correct": "droga", "explanation": "'Droga zamarzła' (die Straße ist zugefroren) – 'droga' im Nominativ als Subjekt. 'Zamarzła' – feminin Vergangenheitsform von 'zamarznąć' (zufrieren). 'Tak silny, że...' = 'so stark, dass...' – Konsekutivsatz mit 'że'. 'Mróz' (Frost, maskulin) – 'jest tak silny' (ist so stark, mask. Prädikatsadjektiv).", "difficulty": "intermediate"},
            {"id": "gp_wea14", "question": "Lubię spacerować _____ deszczu.", "translation": "Ich gehe gerne im Regen spazieren.", "options": ["w", "na", "pod", "z"], "correct": "w", "explanation": "'W deszczu' (im Regen) – 'w' + Lokativ: 'deszcz' → 'deszczu'. 'Spacerować' (spazieren gehen) – unvollendeter Aspekt für eine allgemeine Gewohnheit. 'Lubię spacerować' (ich gehe gerne spazieren) – 'lubić' + unvollendeter Infinitiv. Im Deutschen: 'im Regen' – gleiche Struktur mit 'in' + Dativ.", "difficulty": "beginner"},
            {"id": "gp_wea15", "question": "Zachód _____ jest piękny o tej porze roku.", "translation": "Der Sonnenuntergang ist zu dieser Jahreszeit wunderschön.", "options": ["słońca", "słońce", "słońcem", "słońcu"], "correct": "słońca", "explanation": "'Zachód słońca' (Sonnenuntergang) – 'słońca' im Genitiv als Attribut. 'Zachód' (Untergang/Westen) + Genitiv = Zusammensetzung. 'O tej porze roku' (zu dieser Jahreszeit) – 'o' + Lokativ: 'ta pora' → 'tej porze'. 'Roku' – Genitiv: 'rok' → 'roku'. Im Deutschen: einfaches Kompositum 'Sonnenuntergang'.", "difficulty": "intermediate"}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)
data.extend(new_categories)
with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"Added {len(new_categories)} categories")
print(f"Total: {len(data)} categories, {sum(len(c['items']) for c in data)} items")
from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
print(f"Duplicates: {dupes if dupes else 'None'}")
