#!/usr/bin/env python3
"""Batch 16: Practical Domains (categories 82-86) for german_polish grammar."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "travel_transport",
        "name": "Podróże i transport (Reisen und Verkehr)",
        "description": "Słownictwo i konstrukcje gramatyczne związane z podróżami i transportem",
        "icon": "airplane",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_trav1", "question": "Chcę _____ bilet do Krakowa.", "translation": "Ich möchte eine Fahrkarte nach Krakau kaufen.", "options": ["kupić", "kupować", "kupienie", "kupię"], "correct": "kupić", "explanation": "Nach dem Modalverb 'chcieć' (wollen) steht immer der Infinitiv. Im Polnischen wählt man den perfektiven Aspekt 'kupić' (kaufen, einmalig), weil es um einen konkreten, einmaligen Kauf geht. 'Kupować' wäre der imperfektive Aspekt für wiederholte Handlungen.", "difficulty": "beginner"},
            {"id": "gp_trav2", "question": "Pociąg do Warszawy odjeżdża z _____ trzeciego.", "translation": "Der Zug nach Warschau fährt von Gleis drei ab.", "options": ["peronu", "peron", "peronem", "peronie"], "correct": "peronu", "explanation": "Die Präposition 'z' (von/aus) verlangt im Polnischen den Genitiv. 'Peron' (Bahnsteig, maskulin) wird im Genitiv zu 'peronu'. Im Deutschen steht nach 'von' der Dativ, aber im Polnischen ist es immer der Genitiv bei 'z' in der Bedeutung 'von...weg'.", "difficulty": "intermediate"},
            {"id": "gp_trav3", "question": "Czy ten autobus jedzie do _____?", "translation": "Fährt dieser Bus ins Zentrum?", "options": ["centrum", "centrumu", "centrem", "centrze"], "correct": "centrum", "explanation": "Die Präposition 'do' (nach/zu) verlangt den Genitiv. 'Centrum' ist ein Neutrum lateinischen Ursprungs und bleibt im Genitiv unverändert – 'centrum'. Das ist eine Besonderheit vieler Fremdwörter im Polnischen, die in einigen Fällen nicht dekliniert werden.", "difficulty": "beginner"},
            {"id": "gp_trav4", "question": "Samolot _____ o godzinie piątej.", "translation": "Das Flugzeug landet um fünf Uhr.", "options": ["ląduje", "lądować", "lądował", "wyląduje"], "correct": "ląduje", "explanation": "Für den Fahrplan und regelmäßige Abläufe verwendet man im Polnischen das Präsens. 'Ląduje' (landet) ist die 3. Person Singular Präsens des imperfektiven Verbs 'lądować'. Im Deutschen verwendet man ebenfalls das Präsens für Fahrpläne ('Das Flugzeug landet').", "difficulty": "beginner"},
            {"id": "gp_trav5", "question": "Muszę _____ na następny autobus.", "translation": "Ich muss auf den nächsten Bus warten.", "options": ["czekać", "poczekać", "czekam", "czekając"], "correct": "czekać", "explanation": "Nach 'musieć' (müssen) steht der Infinitiv. Hier passt der imperfektive Aspekt 'czekać', weil das Warten ein andauernder Prozess ist, kein einmaliges Ereignis. 'Poczekać' (perfektiv) betont das erfolgreiche Abwarten bis zum Ergebnis.", "difficulty": "intermediate"},
            {"id": "gp_trav6", "question": "Podróż _____ pociągiem trwa trzy godziny.", "translation": "Die Reise mit dem Zug dauert drei Stunden.", "options": ["pociągiem", "pociąg", "pociągu", "pociągowi"], "correct": "pociągiem", "explanation": "Das Transportmittel steht im Polnischen im Instrumental ohne Präposition: 'pociągiem' (mit dem Zug), 'samolotem' (mit dem Flugzeug), 'autobusem' (mit dem Bus). Im Deutschen verwendet man 'mit' + Dativ. Der Instrumental ist hier die natürliche polnische Konstruktion.", "difficulty": "intermediate"},
            {"id": "gp_trav7", "question": "Proszę o miejsce przy _____.", "translation": "Ich hätte gerne einen Platz am Fenster.", "options": ["oknie", "okno", "oknem", "okna"], "correct": "oknie", "explanation": "Die Präposition 'przy' (bei/an) verlangt im Polnischen den Lokativ. 'Okno' (Fenster, Neutrum) wird im Lokativ zu 'oknie'. Der Lokativ wird verwendet für statische Position neben/bei etwas. Im Deutschen steht nach 'am' der Dativ.", "difficulty": "intermediate"},
            {"id": "gp_trav8", "question": "Wysiądę na _____ przystanku.", "translation": "Ich steige an der nächsten Haltestelle aus.", "options": ["następnym", "następny", "następnego", "następnej"], "correct": "następnym", "explanation": "'Na' mit Lokativ für den Ort, an dem man aussteigt. 'Następny' (nächster) muss als Adjektiv mit dem maskulinen Substantiv 'przystanek' im Lokativ übereinstimmen → 'następnym przystanku'. Der Lokativ Singular maskulin für Adjektive endet auf '-ym/-im'.", "difficulty": "intermediate"},
            {"id": "gp_trav9", "question": "Przepraszam, jak _____ na dworzec?", "translation": "Entschuldigung, wie komme ich zum Bahnhof?", "options": ["dojść", "dojechać", "dojdę", "dochodzić"], "correct": "dojść", "explanation": "Im Polnischen fragt man nach dem Weg mit dem Infinitiv: 'jak dojść do...' (wie kommt man zu...). 'Dojść' (zu Fuß ankommen) ist perfektiv. 'Dojechać' wäre mit einem Fahrzeug. Die Frage ist unpersönlich formuliert, daher steht der Infinitiv.", "difficulty": "beginner"},
            {"id": "gp_trav10", "question": "Nie mogę znaleźć _____ paszportu.", "translation": "Ich kann meinen Pass nicht finden.", "options": ["mojego", "mój", "moim", "mojemu"], "correct": "mojego", "explanation": "Das Verb 'znaleźć' (finden) wird hier verneint ('nie mogę znaleźć'), daher wechselt das direkte Objekt vom Akkusativ zum Genitiv – eine Grundregel im Polnischen. 'Mój paszport' (Akk.) wird zu 'mojego paszportu' (Gen.). Diese Genitivierung nach Verneinung gibt es im Deutschen nicht.", "difficulty": "intermediate"},
            {"id": "gp_trav11", "question": "Lot został _____ z powodu mgły.", "translation": "Der Flug wurde wegen Nebel gestrichen.", "options": ["odwołany", "odwołane", "odwołać", "odwołaniu"], "correct": "odwołany", "explanation": "Passivkonstruktion mit 'zostać' + Partizip. 'Lot' (Flug) ist maskulin, daher muss das Partizip ebenfalls maskulin sein: 'odwołany' (gestrichen). Im Deutschen: 'wurde gestrichen'. Die Kongruenz des Partizips mit dem Subjekt in Genus und Numerus ist im Polnischen obligatorisch.", "difficulty": "advanced"},
            {"id": "gp_trav12", "question": "Zarezerwowałem hotel w pobliżu _____.", "translation": "Ich habe ein Hotel in der Nähe des Meeres gebucht.", "options": ["morza", "morze", "morzem", "morzu"], "correct": "morza", "explanation": "'W pobliżu' (in der Nähe von) verlangt den Genitiv. 'Morze' (Meer, Neutrum) wird im Genitiv zu 'morza'. Viele polnische Ortsangaben verlangen den Genitiv: 'w pobliżu', 'obok', 'naprzeciwko', 'w centrum'. Im Deutschen steht nach 'in der Nähe' ebenfalls der Genitiv.", "difficulty": "intermediate"},
            {"id": "gp_trav13", "question": "Na lotnisku trzeba _____ wcześniej.", "translation": "Am Flughafen muss man früher da sein.", "options": ["być", "będzie", "jest", "bywać"], "correct": "być", "explanation": "'Trzeba' (man muss) ist eine unpersönliche Konstruktion, nach der immer der Infinitiv steht. 'Trzeba być' = man muss sein. 'Trzeba' hat keine Konjugation – es ist ein unveränderliches Prädikativum. Im Deutschen: 'man muss' + Infinitiv, ähnliche Struktur.", "difficulty": "beginner"},
            {"id": "gp_trav14", "question": "Wsiadłam do _____ jadącego do Gdańska.", "translation": "Ich bin in den Zug nach Danzig eingestiegen.", "options": ["pociągu", "pociąg", "pociągiem", "pociągi"], "correct": "pociągu", "explanation": "'Do' (in/zu) verlangt den Genitiv. 'Wsiadać do pociągu' (in den Zug einsteigen) – 'pociąg' wird im Genitiv zu 'pociągu'. Beachte den Unterschied: 'wsiadać do' (einsteigen in) + Genitiv vs. Deutsch 'einsteigen in' + Akkusativ. Polnisch verwendet hier den Genitiv der Richtung.", "difficulty": "intermediate"},
            {"id": "gp_trav15", "question": "Podróż była _____ i przyjemna.", "translation": "Die Reise war lang und angenehm.", "options": ["długa", "długi", "długie", "długo"], "correct": "długa", "explanation": "'Podróż' (Reise) ist feminin, daher muss das Prädikatsadjektiv ebenfalls feminin sein: 'długa'. Im Nominativ Singular Femininum enden die meisten Adjektive auf '-a'. 'Długi' wäre maskulin, 'długie' Neutrum/Plural, 'długo' ein Adverb. Genuskongruenz ist im Polnischen streng.", "difficulty": "beginner"}
        ]
    },
    {
        "key": "food_restaurant",
        "name": "Jedzenie i restauracja (Essen und Restaurant)",
        "description": "Zamawianie jedzenia, opis potraw i konstrukcje przy stole",
        "icon": "fork.knife",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_food1", "question": "Poproszę _____ zupy pomidorowej.", "translation": "Ich hätte gerne eine Portion Tomatensuppe.", "options": ["talerz", "talerzem", "talerza", "talerzu"], "correct": "talerz", "explanation": "'Poproszę' (ich hätte gerne) als höfliche Bestellform – danach steht der Akkusativ. 'Talerz' (Teller, maskulin unbelebt) hat im Akkusativ dieselbe Form wie im Nominativ. 'Zupy pomidorowej' steht im Genitiv als Teilungsgenitiv (eine Portion von der Suppe).", "difficulty": "beginner"},
            {"id": "gp_food2", "question": "Czy mogę prosić o _____?", "translation": "Könnte ich die Speisekarte bekommen?", "options": ["kartę", "karta", "karty", "kartą"], "correct": "kartę", "explanation": "'Prosić o' (bitten um) verlangt den Akkusativ. 'Karta' (Karte/Speisekarte, feminin) wird im Akkusativ zu 'kartę'. Im Polnischen enden feminine Substantive im Akkusativ Singular auf '-ę'. Im Deutschen steht nach 'um' ebenfalls der Akkusativ.", "difficulty": "beginner"},
            {"id": "gp_food3", "question": "To danie jest bardzo _____.", "translation": "Dieses Gericht ist sehr lecker.", "options": ["smaczne", "smaczny", "smaczna", "smacznie"], "correct": "smaczne", "explanation": "'Danie' (Gericht/Speise) ist Neutrum, daher muss das Prädikatsadjektiv Neutrum sein: 'smaczne'. Die Endung '-e' kennzeichnet das Neutrum im Nominativ Singular. 'Smaczny' wäre maskulin, 'smaczna' feminin, 'smacznie' das Adverb.", "difficulty": "beginner"},
            {"id": "gp_food4", "question": "Wolę herbatę _____ kawy.", "translation": "Ich bevorzuge Tee gegenüber Kaffee.", "options": ["od", "niż", "z", "do"], "correct": "od", "explanation": "'Woleć' (bevorzugen) + Akkusativ + 'od' + Genitiv ist die typische polnische Konstruktion für Präferenzen. 'Herbatę' (Akk.) + 'od kawy' (Gen.) = Tee gegenüber Kaffee. Alternativ: 'woleć A niż B' (A lieber als B). 'Od' + Genitiv ist die häufigere Form.", "difficulty": "intermediate"},
            {"id": "gp_food5", "question": "Nie jem _____, jestem wegetarianinem.", "translation": "Ich esse kein Fleisch, ich bin Vegetarier.", "options": ["mięsa", "mięso", "mięsem", "mięsu"], "correct": "mięsa", "explanation": "Nach einem verneinten Verb wechselt das direkte Objekt vom Akkusativ zum Genitiv: 'nie jem mięsa' (ich esse kein Fleisch). 'Mięso' (Fleisch, Neutrum) → Genitiv 'mięsa'. Diese Genitivregel nach Verneinung ist eine der wichtigsten polnischen Grammatikregeln ohne deutsches Äquivalent.", "difficulty": "intermediate"},
            {"id": "gp_food6", "question": "Proszę o rachunek _____ obiad.", "translation": "Die Rechnung für das Mittagessen bitte.", "options": ["za", "dla", "na", "po"], "correct": "za", "explanation": "'Za' + Akkusativ bedeutet 'für' im Sinne einer Bezahlung: 'rachunek za obiad' (Rechnung für das Mittagessen). 'Dla' (für) wird für Personen verwendet, nicht für Preise. 'Za' drückt den Gegenwert/Preis aus. Im Deutschen deckt 'für' beide Bedeutungen ab.", "difficulty": "intermediate"},
            {"id": "gp_food7", "question": "Piję kawę _____ cukru.", "translation": "Ich trinke Kaffee ohne Zucker.", "options": ["bez", "z", "od", "przy"], "correct": "bez", "explanation": "'Bez' (ohne) + Genitiv: 'bez cukru' (ohne Zucker). 'Cukier' (Zucker, maskulin) → Genitiv 'cukru'. 'Bez' funktioniert wie deutsches 'ohne', verlangt aber den Genitiv statt des Akkusativs. Andere Beispiele: 'bez mleka' (ohne Milch), 'bez lodu' (ohne Eis).", "difficulty": "beginner"},
            {"id": "gp_food8", "question": "Ta restauracja jest _____ od tamtej.", "translation": "Dieses Restaurant ist besser als jenes.", "options": ["lepsza", "lepszy", "lepsze", "lepiej"], "correct": "lepsza", "explanation": "'Restauracja' ist feminin, daher muss der Komparativ feminin sein: 'lepsza' (besser, fem.). 'Od tamtej' (als jene) mit 'od' + Genitiv für Vergleiche. Im Deutschen: 'besser als' + Nominativ. Polnisch verwendet 'od' + Genitiv oder 'niż' + Nominativ für Vergleiche.", "difficulty": "intermediate"},
            {"id": "gp_food9", "question": "Zamówiłem _____ z frytkami.", "translation": "Ich habe ein Schnitzel mit Pommes bestellt.", "options": ["schabowego", "schabowy", "schabowym", "schabowe"], "correct": "schabowego", "explanation": "'Zamówić' (bestellen) verlangt den Akkusativ. 'Schabowy' (Schnitzel) ist ein substantiviertes Adjektiv maskulin. Im Akkusativ maskulin belebt: 'schabowego'. Aber Achtung: 'schabowy' gilt als belebt in der Küchenterminologie – ein seltener grammatischer Sonderfall im Polnischen!", "difficulty": "advanced"},
            {"id": "gp_food10", "question": "Chciałbym zarezerwować stolik _____ dwie osoby.", "translation": "Ich würde gerne einen Tisch für zwei Personen reservieren.", "options": ["na", "dla", "za", "po"], "correct": "na", "explanation": "'Na' + Akkusativ bei Reservierungen für eine bestimmte Anzahl: 'stolik na dwie osoby' (Tisch für zwei Personen). 'Dla' (für) bezieht sich auf konkrete Personen ('dla nas' = für uns), während 'na' die Kapazität angibt. Diese Unterscheidung gibt es im Deutschen nicht.", "difficulty": "intermediate"},
            {"id": "gp_food11", "question": "Dodaj trochę _____ do sałatki.", "translation": "Gib etwas Salz an den Salat.", "options": ["soli", "sól", "solą", "sole"], "correct": "soli", "explanation": "'Trochę' (etwas/ein wenig) verlangt den Genitiv als Teilungsgenitiv. 'Sól' (Salz, feminin) → Genitiv 'soli'. Mengenangaben im Polnischen ('trochę', 'dużo', 'mało', 'kilka') stehen immer mit dem Genitiv. Im Deutschen: 'etwas Salz' (ohne Kasusmarkierung).", "difficulty": "intermediate"},
            {"id": "gp_food12", "question": "Ugotowałam obiad dla całej _____.", "translation": "Ich habe das Mittagessen für die ganze Familie gekocht.", "options": ["rodziny", "rodzina", "rodziną", "rodzinie"], "correct": "rodziny", "explanation": "'Dla' (für) verlangt den Genitiv. 'Rodzina' (Familie, feminin) → Genitiv 'rodziny'. 'Cała' (ganze) muss ebenfalls im Genitiv feminin stehen: 'całej'. Im Polnischen stimmen Adjektiv und Substantiv in Fall, Genus und Numerus überein – hier beide im Genitiv Singular Femininum.", "difficulty": "intermediate"},
            {"id": "gp_food13", "question": "Zupa jest za _____.", "translation": "Die Suppe ist zu salzig.", "options": ["słona", "słone", "słony", "słono"], "correct": "słona", "explanation": "'Zupa' ist feminin, daher: 'za słona' (zu salzig, feminin). 'Za' + Adjektiv = 'zu' + Adjektiv. Das Prädikatsadjektiv muss mit dem Subjekt im Genus übereinstimmen. Beachte: 'za' hier bedeutet 'zu (viel)', nicht 'für' oder 'hinter'. Kontextabhängige Präposition!", "difficulty": "beginner"},
            {"id": "gp_food14", "question": "Napijemy _____ czegoś zimnego?", "translation": "Trinken wir etwas Kaltes?", "options": ["się", "siebie", "sobie", "nam"], "correct": "się", "explanation": "'Napić się' (etwas trinken) ist ein reflexives Verb mit dem Reflexivpronomen 'się'. Es verlangt den Genitiv: 'napić się czegoś' (etwas trinken). 'Czegoś zimnego' – beide im Genitiv. Im Deutschen nicht reflexiv: 'etwas trinken'. Polnisch markiert die Selbstbezüglichkeit.", "difficulty": "intermediate"},
            {"id": "gp_food15", "question": "Najlepsza restauracja w _____ mieście.", "translation": "Das beste Restaurant in der ganzen Stadt.", "options": ["całym", "cały", "całego", "całej"], "correct": "całym", "explanation": "'W' (in) + Lokativ für Ortsangaben. 'Miasto' (Stadt, Neutrum) → Lokativ 'mieście'. Das Adjektiv 'cały' (ganz) muss ebenfalls im Lokativ Neutrum stehen: 'całym'. Der Superlativ 'najlepsza' steht im Nominativ, weil er zum Subjekt 'restauracja' gehört.", "difficulty": "intermediate"}
        ]
    },
    {
        "key": "health_body",
        "name": "Zdrowie i ciało (Gesundheit und Körper)",
        "description": "Opis stanu zdrowia, wizyta u lekarza i części ciała",
        "icon": "heart.text.square",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_hlth1", "question": "Boli _____ głowa.", "translation": "Ich habe Kopfschmerzen. (Mir tut der Kopf weh.)", "options": ["mnie", "mi", "ja", "mój"], "correct": "mnie", "explanation": "'Boleć' (wehtun/schmerzen) wird unpersönlich konstruiert: das Subjekt ist der Körperteil, der Experiencer steht im Akkusativ: 'boli mnie głowa' (wörtlich: es schmerzt mich der Kopf). Im Deutschen: 'mir tut ... weh' mit Dativ. Diese unpersönliche Konstruktion ist typisch fürs Polnische.", "difficulty": "beginner"},
            {"id": "gp_hlth2", "question": "Muszę iść do _____.", "translation": "Ich muss zum Arzt gehen.", "options": ["lekarza", "lekarz", "lekarzem", "lekarzu"], "correct": "lekarza", "explanation": "'Do' (zu/nach) + Genitiv: 'do lekarza' (zum Arzt). 'Lekarz' (Arzt, maskulin belebt) → Genitiv 'lekarza'. Bei belebten Maskulina ist der Akkusativ = Genitiv. Aber hier verlangt die Präposition 'do' ohnehin den Genitiv, unabhängig von der Belebtheit.", "difficulty": "beginner"},
            {"id": "gp_hlth3", "question": "Jestem _____ na grypę.", "translation": "Ich bin gegen Grippe geimpft.", "options": ["zaszczepiony", "zaszczepiona", "szczepiony", "zaszczepieni"], "correct": "zaszczepiony", "explanation": "Partizip Perfekt 'zaszczepiony' (geimpft) als Prädikativ – muss mit dem Subjekt in Genus und Numerus übereinstimmen. Hier maskulin Singular. 'Na grypę' (gegen Grippe) mit 'na' + Akkusativ für Krankheiten. Im Deutschen: 'gegen' + Akkusativ, ähnliche Struktur.", "difficulty": "intermediate"},
            {"id": "gp_hlth4", "question": "Czuję _____ źle od rana.", "translation": "Ich fühle mich seit heute Morgen schlecht.", "options": ["się", "siebie", "sobie", "mi"], "correct": "się", "explanation": "'Czuć się' (sich fühlen) ist reflexiv mit 'się'. 'Od rana' (seit dem Morgen) – 'od' + Genitiv für den Zeitpunkt des Beginns. 'Źle' ist das Adverb (schlecht), nicht das Adjektiv. Im Polnischen steht nach 'czuć się' ein Adverb oder 'dobrze/źle', nicht ein Adjektiv.", "difficulty": "beginner"},
            {"id": "gp_hlth5", "question": "Lekarz przepisał mi _____ przeciwbólowe.", "translation": "Der Arzt hat mir Schmerzmittel verschrieben.", "options": ["leki", "leków", "lekami", "lekom"], "correct": "leki", "explanation": "'Przepisać' (verschreiben) + Akkusativ: 'leki' (Medikamente, Plural) steht im Akkusativ. Im Plural unbelebt ist der Akkusativ = Nominativ. 'Mi' (mir) ist der Dativ des Empfängers. 'Przeciwbólowe' (Schmerz-/schmerzstillend) ist ein Adjektiv im Plural, das mit 'leki' übereinstimmt.", "difficulty": "intermediate"},
            {"id": "gp_hlth6", "question": "Złamałem _____ na nartach.", "translation": "Ich habe mir beim Skifahren das Bein gebrochen.", "options": ["nogę", "noga", "nogi", "nogą"], "correct": "nogę", "explanation": "'Złamać' (brechen) + Akkusativ: 'noga' (Bein, feminin) → Akkusativ 'nogę'. Im Polnischen sagt man 'złamałem nogę' (ich brach ein Bein), ohne das reflexive 'mir' des Deutschen. 'Na nartach' (beim Skifahren, wörtlich: auf den Skiern) – 'na' + Lokativ.", "difficulty": "beginner"},
            {"id": "gp_hlth7", "question": "Mam _____ w gardle.", "translation": "Ich habe Halsschmerzen. (Es kratzt im Hals.)", "options": ["ból", "bólu", "bólowi", "bólem"], "correct": "ból", "explanation": "'Mieć' (haben) + Akkusativ: 'ból' (Schmerz, maskulin unbelebt) bleibt im Akkusativ gleich dem Nominativ (unbelebt!). 'W gardle' – 'w' + Lokativ ('gardło' → 'gardle'). Im Polnischen beschreibt man Schmerzen häufig mit 'mieć ból' + Lokativ des Körperteils.", "difficulty": "beginner"},
            {"id": "gp_hlth8", "question": "Proszę _____ głęboko.", "translation": "Bitte atmen Sie tief ein.", "options": ["oddychać", "oddycham", "oddech", "oddychanie"], "correct": "oddychać", "explanation": "'Proszę' (bitte) + Infinitiv ist die höfliche Befehlsform im Polnischen, äquivalent zum deutschen 'Bitte + Sie-Imperativ'. 'Oddychać głęboko' (tief atmen) – Adverb 'głęboko' modifiziert den Infinitiv. Diese Konstruktion 'proszę + Infinitiv' ist die höflichste Form der Aufforderung.", "difficulty": "beginner"},
            {"id": "gp_hlth9", "question": "Mam alergię na _____.", "translation": "Ich bin allergisch gegen Pollen.", "options": ["pyłki", "pyłek", "pyłków", "pyłkami"], "correct": "pyłki", "explanation": "'Na' + Akkusativ nach 'alergia': 'alergia na pyłki' (Allergie gegen Pollen). 'Pyłki' ist der Akkusativ Plural (= Nominativ Plural bei unbelebten). Im Deutschen: 'allergisch gegen' + Akkusativ. Polnisch verwendet 'na' statt 'gegen' für Allergien und Krankheiten.", "difficulty": "intermediate"},
            {"id": "gp_hlth10", "question": "Powinnaś więcej _____ na świeżym powietrzu.", "translation": "Du solltest dich mehr an der frischen Luft bewegen.", "options": ["spacerować", "spaceruję", "spacerowanie", "spacerując"], "correct": "spacerować", "explanation": "Nach 'powinien/powinna' (sollen) steht der Infinitiv: 'powinnaś spacerować' (du solltest spazieren gehen). 'Na świeżym powietrzu' (an der frischen Luft) – 'na' + Lokativ. 'Więcej' (mehr) steht als Adverb vor dem Infinitiv. Beachte die feminine Form 'powinnaś' mit dem '-ś' Suffix.", "difficulty": "intermediate"},
            {"id": "gp_hlth11", "question": "Operacja _____ pomyślnie.", "translation": "Die Operation ist erfolgreich verlaufen.", "options": ["przebiegła", "przebiegł", "przebiegło", "przebiegli"], "correct": "przebiegła", "explanation": "'Operacja' ist feminin, daher: 'przebiegła' (verlief, feminin Vergangenheit). Im Polnischen markiert die Vergangenheitsform das Genus des Subjekts: '-ła' (fem.), '-ł' (mask.), '-ło' (neutr.), '-li/-ły' (Plural). Diese Genusmarkierung im Verb ist einzigartig für slawische Sprachen.", "difficulty": "intermediate"},
            {"id": "gp_hlth12", "question": "Od tygodnia mam _____.", "translation": "Seit einer Woche habe ich Husten.", "options": ["kaszel", "kaszlu", "kaszlem", "kaszlowi"], "correct": "kaszel", "explanation": "'Mieć' (haben) + Akkusativ: 'kaszel' (Husten, maskulin unbelebt) bleibt im Akkusativ wie im Nominativ. 'Od tygodnia' (seit einer Woche) – 'od' + Genitiv für den Zeitpunkt des Beginns. Im Deutschen: 'seit' + Dativ. Polnisch: 'od' + Genitiv für zeitliches 'seit'.", "difficulty": "beginner"},
            {"id": "gp_hlth13", "question": "Trzeba regularnie _____ się u dentysty.", "translation": "Man sollte sich regelmäßig beim Zahnarzt untersuchen lassen.", "options": ["badać", "zbadać", "badam", "badanie"], "correct": "badać", "explanation": "'Trzeba' (man muss/sollte) + Infinitiv. Der imperfektive Aspekt 'badać' ist hier richtig, weil es um eine regelmäßige, wiederholte Handlung geht ('regularnie' = regelmäßig). 'Zbadać' (perfektiv) wäre für eine einmalige Untersuchung. Aspektwahl hängt vom Kontext ab.", "difficulty": "intermediate"},
            {"id": "gp_hlth14", "question": "Apteka jest _____ za rogiem.", "translation": "Die Apotheke ist gleich um die Ecke.", "options": ["zaraz", "już", "jeszcze", "dopiero"], "correct": "zaraz", "explanation": "'Zaraz za rogiem' (gleich um die Ecke) – 'zaraz' kann sowohl zeitlich (gleich/sofort) als auch räumlich (gleich hier/dort) sein. 'Za rogiem' – 'za' + Instrumental für Ort (hinter der Ecke). Im Deutschen: 'um die Ecke' mit Akkusativ, im Polnischen: 'za rogiem' mit Instrumental.", "difficulty": "beginner"},
            {"id": "gp_hlth15", "question": "Po _____ antybiotyku poczułem się lepiej.", "translation": "Nach Einnahme des Antibiotikums fühlte ich mich besser.", "options": ["zażyciu", "zażycie", "zażyciem", "zażyć"], "correct": "zażyciu", "explanation": "'Po' (nach) + Lokativ: 'zażycie' (Einnahme) → Lokativ 'zażyciu'. 'Antybiotyku' steht als nachgestellter Genitiv (Einnahme des Antibiotikums). 'Poczułem się lepiej' – perfektives 'poczuć się' für den Moment der Besserung. 'Lepiej' ist der Komparativ des Adverbs 'dobrze' (gut).", "difficulty": "advanced"}
        ]
    },
    {
        "key": "work_office",
        "name": "Praca i biuro (Arbeit und Büro)",
        "description": "Słownictwo i struktury gramatyczne związane z pracą zawodową",
        "icon": "briefcase",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_work1", "question": "Pracuję _____ programista.", "translation": "Ich arbeite als Programmierer.", "options": ["jako", "jak", "za", "na"], "correct": "jako", "explanation": "'Jako' (als) für Berufsbezeichnungen: 'pracuję jako programista'. Beachte: nach 'jako' steht der Nominativ, nicht der Instrumental! Das ist eine Ausnahme in der polnischen Grammatik. Bei 'być' (sein) steht die Berufsbezeichnung im Instrumental: 'jestem programistą'.", "difficulty": "beginner"},
            {"id": "gp_work2", "question": "Mam spotkanie z _____ o trzeciej.", "translation": "Ich habe um drei ein Meeting mit dem Chef.", "options": ["szefem", "szef", "szefa", "szefowi"], "correct": "szefem", "explanation": "'Z' (mit) + Instrumental: 'szef' (Chef, maskulin belebt) → Instrumental 'szefem'. Im Polnischen verlangt 'z' in der Bedeutung 'mit' immer den Instrumental. Im Deutschen steht nach 'mit' der Dativ. 'O trzeciej' (um drei) – 'o' + Lokativ für Uhrzeiten.", "difficulty": "beginner"},
            {"id": "gp_work3", "question": "Muszę _____ raport do piątku.", "translation": "Ich muss den Bericht bis Freitag fertigstellen.", "options": ["skończyć", "kończyć", "skończę", "kończenie"], "correct": "skończyć", "explanation": "'Musieć' (müssen) + Infinitiv. Der perfektive Aspekt 'skończyć' (fertigstellen, abschließen) betont das Ergebnis bis zum Termin. 'Kończyć' (imperfektiv) würde den Prozess des Arbeitens betonen. 'Do piątku' (bis Freitag) – 'do' + Genitiv als Frist. Aspektwahl ist kontextabhängig.", "difficulty": "intermediate"},
            {"id": "gp_work4", "question": "Szukam nowej _____ od miesięcy.", "translation": "Ich suche seit Monaten eine neue Arbeit.", "options": ["pracy", "pracę", "praca", "pracą"], "correct": "pracy", "explanation": "'Szukać' (suchen) verlangt im Polnischen den Genitiv, nicht den Akkusativ! 'Nowa praca' (neue Arbeit, fem.) → Genitiv 'nowej pracy'. Das ist ein typischer Fehler deutschsprachiger Lerner, da 'suchen' im Deutschen den Akkusativ verlangt. Andere Genitiv-Verben: 'potrzebować', 'unikać', 'pilnować'.", "difficulty": "intermediate"},
            {"id": "gp_work5", "question": "Zostałem _____ na wyższe stanowisko.", "translation": "Ich wurde auf eine höhere Position befördert.", "options": ["awansowany", "awansowana", "awansowane", "awansowani"], "correct": "awansowany", "explanation": "Passiv mit 'zostać' + Partizip: 'zostałem awansowany' (ich wurde befördert). Das Partizip muss mit dem Subjekt im Genus übereinstimmen – hier maskulin. 'Na wyższe stanowisko' – 'na' + Akkusativ für Ziel/Richtung der Beförderung. Im Deutschen: 'auf' + Akkusativ.", "difficulty": "intermediate"},
            {"id": "gp_work6", "question": "Nasz zespół składa się _____ dziesięciu osób.", "translation": "Unser Team besteht aus zehn Personen.", "options": ["z", "od", "na", "w"], "correct": "z", "explanation": "'Składać się z' (bestehen aus) + Genitiv: 'z dziesięciu osób'. Im Deutschen: 'bestehen aus' + Dativ. 'Dziesięciu osób' – nach Zahlwörtern ab 5 steht der Genitiv Plural! Das ist eine der schwierigsten Regeln: 2-4 + Nominativ Plural, 5+ + Genitiv Plural.", "difficulty": "intermediate"},
            {"id": "gp_work7", "question": "Proszę przesłać _____ na mój adres e-mail.", "translation": "Bitte senden Sie die Dokumente an meine E-Mail-Adresse.", "options": ["dokumenty", "dokumentów", "dokumentami", "dokumentom"], "correct": "dokumenty", "explanation": "'Proszę przesłać' (bitte senden Sie) – höfliche Form mit 'proszę' + Infinitiv. 'Dokumenty' (Dokumente) steht im Akkusativ (= Nominativ bei unbelebten Maskulina im Plural). 'Na mój adres' – 'na' + Akkusativ für die Ziel-/Empfangsadresse.", "difficulty": "beginner"},
            {"id": "gp_work8", "question": "Jestem _____ z wyników naszego projektu.", "translation": "Ich bin zufrieden mit den Ergebnissen unseres Projekts.", "options": ["zadowolony", "zadowolona", "zadowoleni", "zadowolonego"], "correct": "zadowolony", "explanation": "'Zadowolony z' (zufrieden mit) + Genitiv: 'z wyników' (mit den Ergebnissen). Im Deutschen: 'zufrieden mit' + Dativ. Polnisch verwendet 'z' + Genitiv (nicht Instrumental!). 'Naszego projektu' – ebenfalls Genitiv als Attribut zu 'wyników'. Beachte die Genitivkette.", "difficulty": "intermediate"},
            {"id": "gp_work9", "question": "Czy możesz _____ mi tę sprawę?", "translation": "Kannst du mir diese Angelegenheit erklären?", "options": ["wyjaśnić", "wyjaśniać", "wyjaśniam", "wyjaśnienie"], "correct": "wyjaśnić", "explanation": "'Czy możesz' (kannst du) + Infinitiv. Perfektiver Aspekt 'wyjaśnić' (erklären, einmalig) ist hier richtig, weil es um eine konkrete, einmalige Erklärung geht. 'Mi' ist der Dativ (mir). 'Tę sprawę' – Demonstrativpronomen + Substantiv im Akkusativ feminin ('ta sprawa' → 'tę sprawę').", "difficulty": "intermediate"},
            {"id": "gp_work10", "question": "Umowa została _____ na rok.", "translation": "Der Vertrag wurde für ein Jahr abgeschlossen.", "options": ["podpisana", "podpisany", "podpisane", "podpisani"], "correct": "podpisana", "explanation": "'Umowa' (Vertrag, feminin) verlangt das feminine Partizip: 'podpisana' (unterschrieben/abgeschlossen). 'Zostać' + Partizip = polnische Passivkonstruktion. 'Na rok' – 'na' + Akkusativ für die Zeitdauer. Im Deutschen: 'für ein Jahr' mit Präposition + Akkusativ, ähnliche Struktur.", "difficulty": "intermediate"},
            {"id": "gp_work11", "question": "Pracuję w tej firmie od _____ lat.", "translation": "Ich arbeite seit fünf Jahren in dieser Firma.", "options": ["pięciu", "pięć", "piątego", "piąty"], "correct": "pięciu", "explanation": "'Od' (seit) + Genitiv: 'od pięciu lat' (seit fünf Jahren). Zahlwörter ab 5 verlangen den Genitiv Plural: 'pięciu' (Genitiv von 'pięć'). 'Lat' ist Genitiv Plural von 'rok/lata' (Jahre). Beachte: 2-4 Jahre = 'dwa/trzy/cztery lata' (Nominativ), ab 5 = 'pięciu lat' (Genitiv).", "difficulty": "advanced"},
            {"id": "gp_work12", "question": "Na spotkaniu _____ o nowym projekcie.", "translation": "Im Meeting haben wir über das neue Projekt gesprochen.", "options": ["rozmawialiśmy", "rozmawiamy", "rozmawiać", "rozmawiali"], "correct": "rozmawialiśmy", "explanation": "Vergangenheitsform 1. Person Plural maskulin-personal: 'rozmawialiśmy' (wir haben gesprochen). Die Endung '-liśmy' markiert: Plural + maskulin-personal + Vergangenheit. Wenn alle Frauen: 'rozmawiałyśmy'. 'O nowym projekcie' – 'o' + Lokativ für 'über/von (Thema)'.", "difficulty": "intermediate"},
            {"id": "gp_work13", "question": "Praca zdalna pozwala _____ oszczędzać czas.", "translation": "Homeoffice ermöglicht es, Zeit zu sparen.", "options": ["mi", "mnie", "ja", "mój"], "correct": "mi", "explanation": "'Pozwalać' (ermöglichen/erlauben) + Dativ + Infinitiv: 'pozwala mi oszczędzać'. 'Mi' ist die kurze Form des Dativs (mir). Im Deutschen: 'ermöglicht mir zu...' – ähnliche Struktur! 'Mnie' wäre die betonte Form des Dativs, die am Satzanfang oder nach Präpositionen steht.", "difficulty": "intermediate"},
            {"id": "gp_work14", "question": "Zajmuję się _____ klientów.", "translation": "Ich kümmere mich um die Betreuung der Kunden.", "options": ["obsługą", "obsługa", "obsługi", "obsłudze"], "correct": "obsługą", "explanation": "'Zajmować się' (sich beschäftigen mit / sich kümmern um) + Instrumental: 'obsługą' (Betreuung, feminin → Instrumental 'obsługą'). 'Klientów' ist Genitiv Plural (Attribut: Betreuung der Kunden). Im Deutschen: 'sich um ... kümmern' + Akkusativ, im Polnischen: Instrumental!", "difficulty": "intermediate"},
            {"id": "gp_work15", "question": "Chciałbym _____ o podwyżkę.", "translation": "Ich würde gerne um eine Gehaltserhöhung bitten.", "options": ["poprosić", "prosić", "proszę", "proszenie"], "correct": "poprosić", "explanation": "'Chciałbym' (ich würde gerne, Konditional) + perfektiver Infinitiv 'poprosić' (bitten, einmalig). 'O podwyżkę' – 'prosić o' + Akkusativ (bitten um). Der perfektive Aspekt betont die Einmaligkeit der Bitte. 'Prosić' (imperfektiv) würde wiederholtes Bitten bedeuten. Die Aspektwahl ist hier bedeutungsentscheidend.", "difficulty": "advanced"}
        ]
    },
    {
        "key": "technology_media",
        "name": "Technologia i media (Technologie und Medien)",
        "description": "Nowoczesna technologia, internet i media w kontekście gramatycznym",
        "icon": "desktopcomputer",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_tech1", "question": "Nie mogę _____ do internetu.", "translation": "Ich kann mich nicht mit dem Internet verbinden.", "options": ["połączyć się", "łączyć się", "połączę się", "połączenie"], "correct": "połączyć się", "explanation": "'Nie mogę' (ich kann nicht) + Infinitiv. 'Połączyć się z' (sich verbinden mit) – perfektives reflexives Verb + 'z' + Instrumental. Aber nach 'do' steht der Genitiv: 'do internetu'. 'Połączyć się do internetu' ist umgangssprachlich für 'sich zum Internet verbinden'. Standardpolnisch bevorzugt 'z internetem'.", "difficulty": "intermediate"},
            {"id": "gp_tech2", "question": "Pobrałem nową _____ na telefon.", "translation": "Ich habe eine neue App aufs Handy heruntergeladen.", "options": ["aplikację", "aplikacja", "aplikacji", "aplikacją"], "correct": "aplikację", "explanation": "'Pobrać' (herunterladen) + Akkusativ: 'aplikacja' (App, feminin) → Akkusativ 'aplikację'. 'Na telefon' – 'na' + Akkusativ für das Ziel (aufs Handy). Im Polnischen wird '-ję' am Ende des Akkusativs feminin für Substantive auf '-ja' verwendet.", "difficulty": "beginner"},
            {"id": "gp_tech3", "question": "Hasło musi _____ z ośmiu znaków.", "translation": "Das Passwort muss aus acht Zeichen bestehen.", "options": ["składać się", "składa się", "złożyć się", "składanie"], "correct": "składać się", "explanation": "'Musieć' (müssen) + Infinitiv: 'składać się z' (bestehen aus) + Genitiv. 'Z ośmiu znaków' – Genitiv Plural nach Zahlwort 8. Der imperfektive Aspekt 'składać się' beschreibt einen dauerhaften Zustand (das Passwort besteht immer aus 8 Zeichen). Perfektiv wäre für einen einmaligen Vorgang.", "difficulty": "intermediate"},
            {"id": "gp_tech4", "question": "Aktualizacja _____ automatycznie.", "translation": "Das Update wird automatisch installiert.", "options": ["instaluje się", "instalować się", "zainstaluje się", "instalacja"], "correct": "instaluje się", "explanation": "'Instaluje się' (installiert sich) – reflexive Konstruktion als Passiv-Ersatz. Im Polnischen wird 'się' oft statt einer Passivkonstruktion verwendet: 'instaluje się' = wird installiert. Das ist natürlicher als 'jest instalowana'. 'Automatycznie' ist das Adverb von 'automatyczny'.", "difficulty": "intermediate"},
            {"id": "gp_tech5", "question": "Warto _____ kopię zapasową danych.", "translation": "Es lohnt sich, ein Backup der Daten zu machen.", "options": ["zrobić", "robić", "robi", "zrobienie"], "correct": "zrobić", "explanation": "'Warto' (es lohnt sich) + Infinitiv: unpersönliche Konstruktion. 'Zrobić kopię zapasową' (ein Backup machen) – perfektiver Aspekt, weil es um eine konkrete, einmalige Handlung geht. 'Danych' ist Genitiv Plural von 'dane' (Daten) – Teilungsgenitiv. In der IT-Sprache sind viele Begriffe femininum.", "difficulty": "intermediate"},
            {"id": "gp_tech6", "question": "Ten program jest _____ od poprzedniego.", "translation": "Dieses Programm ist schneller als das vorherige.", "options": ["szybszy", "szybsze", "szybsza", "szybciej"], "correct": "szybszy", "explanation": "'Program' ist maskulin, daher Komparativ maskulin: 'szybszy' (schneller). 'Od poprzedniego' – 'od' + Genitiv für Vergleiche. 'Szybciej' wäre das Adverb (schneller tun), nicht das Adjektiv. Im Polnischen gibt es strenge Unterscheidung: 'szybszy' (Adj.) vs. 'szybciej' (Adv.).", "difficulty": "intermediate"},
            {"id": "gp_tech7", "question": "Czy możesz mi _____ ten plik?", "translation": "Kannst du mir diese Datei schicken?", "options": ["wysłać", "wysyłać", "wyślij", "wysyłam"], "correct": "wysłać", "explanation": "'Czy możesz' + Infinitiv als höfliche Bitte. 'Wysłać' (senden, perfektiv) – einmaliges Senden einer bestimmten Datei. 'Mi' ist der kurze Dativ (mir). 'Ten plik' (diese Datei) im Akkusativ – 'plik' ist maskulin unbelebt, daher Akk. = Nom. Im Polnischen sind IT-Begriffe oft maskulin.", "difficulty": "beginner"},
            {"id": "gp_tech8", "question": "Nauczyłem się _____ w nowym programie.", "translation": "Ich habe gelernt, im neuen Programm zu arbeiten.", "options": ["pracować", "pracuję", "pracowanie", "popracować"], "correct": "pracować", "explanation": "'Nauczyć się' (lernen) + Infinitiv: 'nauczyłem się pracować' (ich habe gelernt zu arbeiten). Der imperfektive Aspekt 'pracować' ist hier richtig, weil man eine allgemeine Fähigkeit erworben hat. 'W nowym programie' – 'w' + Lokativ ('program' → 'programie', 'nowy' → 'nowym').", "difficulty": "intermediate"},
            {"id": "gp_tech9", "question": "Strona _____ się zbyt wolno.", "translation": "Die Seite lädt zu langsam.", "options": ["ładuje", "ładować", "załaduje", "ładowana"], "correct": "ładuje", "explanation": "'Strona' (Webseite, feminin) + 'ładuje się' (lädt sich). Reflexives 'się' als Passiv-Ersatz: 'ładuje się' = wird geladen / lädt. 'Zbyt wolno' (zu langsam) – 'zbyt' ist formaler als 'za' (zu). 'Wolno' ist das Adverb von 'wolny' (langsam). Imperfektiver Aspekt für andauernde Handlung.", "difficulty": "beginner"},
            {"id": "gp_tech10", "question": "Przed _____ komputera zapisz wszystkie pliki.", "translation": "Bevor du den Computer ausschaltest, speichere alle Dateien.", "options": ["wyłączeniem", "wyłączenie", "wyłączyć", "wyłącza"], "correct": "wyłączeniem", "explanation": "'Przed' (vor/bevor) + Instrumental: 'wyłączenie' (Ausschalten, Verbalsubstantiv) → Instrumental 'wyłączeniem'. 'Komputera' ist Genitiv als Objekt des Verbalsubstantivs. Im Polnischen kann 'przed' + Instrumental temporale Nebensätze ersetzen: statt 'zanim wyłączysz' sagt man kompakter 'przed wyłączeniem'.", "difficulty": "advanced"},
            {"id": "gp_tech11", "question": "Ten laptop jest _____ do pracy i do gier.", "translation": "Dieser Laptop ist sowohl zum Arbeiten als auch zum Spielen geeignet.", "options": ["odpowiedni", "odpowiednia", "odpowiednie", "odpowiednio"], "correct": "odpowiedni", "explanation": "'Laptop' ist maskulin, daher: 'odpowiedni' (geeignet, maskulin). 'Do pracy i do gier' – 'do' + Genitiv für Zweck: 'pracy' (Gen. von 'praca'), 'gier' (Gen. Pl. von 'gra'). 'Odpowiednio' wäre das Adverb (entsprechend/angemessen), nicht das Adjektiv.", "difficulty": "intermediate"},
            {"id": "gp_tech12", "question": "Korzystam z _____ codziennie.", "translation": "Ich nutze soziale Medien täglich.", "options": ["mediów społecznościowych", "media społecznościowe", "mediami społecznościowymi", "mediach społecznościowych"], "correct": "mediów społecznościowych", "explanation": "'Korzystać z' (nutzen/Gebrauch machen von) + Genitiv: 'media społecznościowe' → Genitiv Plural 'mediów społecznościowych'. Adjektiv und Substantiv müssen im selben Kasus stehen. 'Korzystać' ist eines der Verben, die den Genitiv mit 'z' verlangen, nicht den Akkusativ.", "difficulty": "advanced"},
            {"id": "gp_tech13", "question": "Kliknij _____ ten przycisk.", "translation": "Klicke auf diesen Button.", "options": ["na", "w", "do", "przy"], "correct": "na", "explanation": "'Kliknąć na' oder 'kliknąć w' + Akkusativ – beides ist im Polnischen korrekt für 'klicken auf'. 'Na ten przycisk' (auf diesen Knopf). Im IT-Polnisch verwendet man häufig 'kliknąć' als Lehnwort (Click). 'Przycisk' (Knopf/Button) ist maskulin unbelebt, Akk. = Nom.", "difficulty": "beginner"},
            {"id": "gp_tech14", "question": "Trzeba _____ hasło co trzy miesiące.", "translation": "Man muss das Passwort alle drei Monate ändern.", "options": ["zmieniać", "zmienić", "zmienia", "zmianę"], "correct": "zmieniać", "explanation": "'Trzeba' + Infinitiv: unpersönlich 'man muss'. Imperfektiver Aspekt 'zmieniać' (ändern, wiederholt), weil die Handlung regelmäßig erfolgen soll ('co trzy miesiące' = alle drei Monate). 'Zmienić' (perfektiv) wäre für eine einmalige Änderung. Die Aspektwahl wird durch 'co trzy miesiące' bestimmt.", "difficulty": "intermediate"},
            {"id": "gp_tech15", "question": "Dane zostały _____ z serwera.", "translation": "Die Daten wurden vom Server gelöscht.", "options": ["usunięte", "usunięty", "usunięta", "usunięci"], "correct": "usunięte", "explanation": "'Dane' (Daten) ist Plural Neutrum (Plurale tantum), daher: 'usunięte' (gelöscht, nicht-maskulin-personal Plural). Passiv mit 'zostać' + Partizip. 'Z serwera' – 'z' + Genitiv (von/aus dem Server). Im Polnischen unterscheidet man im Plural: maskulin-personal ('-eni/-ci') vs. Rest ('-e/-te').", "difficulty": "advanced"}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")

# Validate format
issues = []
for c in data:
    for item in c['items']:
        if '_____' not in item.get('question',''):
            issues.append(f"{item['id']}: missing _____")
        if len(item.get('options',[])) != 4:
            issues.append(f"{item['id']}: wrong options count")
        if len(item.get('explanation','')) < 200:
            issues.append(f"{item['id']}: explanation too short ({len(item.get('explanation',''))}ch)")
if issues:
    print(f"FORMAT ISSUES ({len(issues)}):")
    for i in issues:
        print(f"  {i}")
else:
    print("All items pass format validation!")
