#!/usr/bin/env python3
"""Batch 19: cats 98-102 for german_polish grammar."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "arts_culture",
        "name": "Sztuka i kultura (Kunst und Kultur)",
        "description": "Słownictwo i struktury gramatyczne związane ze sztuką, muzyką, literaturą i kulturą",
        "icon": "paintpalette",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_art1", "question": "Ten obraz _____ przez Picassa.", "translation": "(Dieses Bild wurde von Picasso gemalt.)", "options": ["został namalowany", "namalował się", "maluje się", "będzie malowany"], "correct": "został namalowany", "explanation": "Strona bierna z 'zostać' + imiesłów bierny: 'został namalowany' (wurde gemalt). Im Polnischen wird das Passiv mit 'zostać' (werden) + Partizip gebildet, ähnlich wie im Deutschen 'wurde gemalt'. Beachte, dass 'przez' + Akkusativ den Urheber angibt (von + Dativ im Deutschen)."},
            {"id": "gp_art2", "question": "Interesuje się _____ i rzeźbą.", "translation": "(Ich interessiere mich für Malerei und Bildhauerei.)", "options": ["malarstwem", "malarstwo", "malarstwu", "malarstwa"], "correct": "malarstwem", "explanation": "'Interesować się' (sich interessieren für) erfordert den Instrumental: 'malarstwem' (Malerei). Das Reflexivverb 'interesować się' regiert im Polnischen den Instrumental, während im Deutschen 'sich interessieren für' den Akkusativ verlangt. 'Rzeźba' (Bildhauerei) steht ebenfalls im Instrumental ('rzeźbą')."},
            {"id": "gp_art3", "question": "Byliśmy na wystawie _____ współczesnej.", "translation": "(Wir waren auf einer Ausstellung zeitgenössischer Kunst.)", "options": ["sztuki", "sztuka", "sztuką", "sztuce"], "correct": "sztuki", "explanation": "'Wystawa sztuki' – Genitiv nach dem Substantiv 'wystawa' (Ausstellung): 'sztuki współczesnej' (der zeitgenössischen Kunst). Der Genitiv drückt hier Zugehörigkeit aus, wie im Deutschen 'eine Ausstellung DER Kunst'. Das Adjektiv 'współczesny' stimmt im Genitiv Femininum überein."},
            {"id": "gp_art4", "question": "Ta powieść została _____ na wiele języków.", "translation": "(Dieser Roman wurde in viele Sprachen übersetzt.)", "options": ["przetłumaczona", "przetłumaczony", "przetłumaczone", "tłumaczona"], "correct": "przetłumaczona", "explanation": "Partizip im Femininum: 'przetłumaczona' (übersetzt), da 'powieść' (Roman) im Polnischen feminin ist. Im Deutschen ist 'Roman' maskulin, aber im Polnischen ist 'powieść' feminin – das Partizip muss im Genus übereinstimmen! Der perfektive Aspekt 'prze-' zeigt die abgeschlossene Handlung."},
            {"id": "gp_art5", "question": "Gramy w orkiestrze _____ trzy lata.", "translation": "(Wir spielen seit drei Jahren im Orchester.)", "options": ["od trzech lat", "od trzy lata", "za trzy lata", "przez trzy lata"], "correct": "od trzech lat", "explanation": "'Od' + Genitiv für 'seit': 'od trzech lat' (seit drei Jahren). 'Trzy lata' wird im Genitiv zu 'trzech lat'. 'Przez trzy lata' würde 'drei Jahre lang' (für/durch) bedeuten – eine abgeschlossene Zeitspanne. 'Od' drückt einen andauernden Zeitraum aus, der in der Gegenwart noch gilt."},
            {"id": "gp_art6", "question": "Lubię słuchać muzyki _____.", "translation": "(Ich höre gern klassische Musik.)", "options": ["klasycznej", "klasyczna", "klasyczną", "klasycznemu"], "correct": "klasycznej", "explanation": "'Słuchać' + Genitiv: 'muzyki klasycznej' (klassischer Musik). Das Verb 'słuchać' (hören/zuhören) regiert im Polnischen den Genitiv, nicht den Akkusativ wie im Deutschen. 'Muzyka klasyczna' wird im Genitiv zu 'muzyki klasycznej'. Das Adjektiv passt sich dem Genus und Kasus des Substantivs an."},
            {"id": "gp_art7", "question": "Aktor zagrał główną _____ w tym filmie.", "translation": "(Der Schauspieler spielte die Hauptrolle in diesem Film.)", "options": ["rolę", "rola", "roli", "rolą"], "correct": "rolę", "explanation": "'Zagrać rolę' – Akkusativ des direkten Objekts: 'główną rolę' (die Hauptrolle). 'Zagrać' (spielen, perfektiv) verlangt den Akkusativ. Im Femininum wird 'rola' zu 'rolę'. Das Adjektiv 'główna' (Haupt-) steht ebenfalls im Akkusativ Femininum: 'główną'."},
            {"id": "gp_art8", "question": "Ten _____ jest znany na całym świecie.", "translation": "(Dieser Komponist ist weltweit bekannt.)", "options": ["kompozytor", "kompozytora", "kompozytorowi", "kompozytorem"], "correct": "kompozytor", "explanation": "'Kompozytor' im Nominativ als Subjekt des Satzes: 'ten kompozytor jest znany' (dieser Komponist ist bekannt). Im Polnischen steht das Subjekt im Nominativ, genau wie im Deutschen. 'Znany na całym świecie' (bekannt auf der ganzen Welt) – 'na' + Lokativ für die Ortsangabe."},
            {"id": "gp_art9", "question": "Chodzę do teatru co _____.", "translation": "(Ich gehe jede Woche ins Theater.)", "options": ["tydzień", "tygodnia", "tygodniu", "tygodniem"], "correct": "tydzień", "explanation": "'Co tydzień' (jede Woche) – 'co' + Akkusativ/Nominativ drückt Regelmäßigkeit aus. 'Tydzień' bleibt unverändert. 'Chodzić do' + Genitiv für 'gehen zu/in' – 'do teatru' (ins Theater). Im Deutschen ist es 'ins Theater', im Polnischen 'do teatru' mit Genitiv des Ziels."},
            {"id": "gp_art10", "question": "Wszyscy byli pod _____ jej występu.", "translation": "(Alle waren von ihrem Auftritt beeindruckt.)", "options": ["wrażeniem", "wrażenie", "wrażeniu", "wrażenia"], "correct": "wrażeniem", "explanation": "'Pod wrażeniem' (unter dem Eindruck / beeindruckt) – feste Wendung mit 'pod' + Instrumental: 'wrażeniem'. Im Deutschen sagt man 'beeindruckt sein von', im Polnischen wörtlich 'unter dem Eindruck stehen'. Die Possessivkonstruktion 'jej występu' (ihres Auftritts) steht im Genitiv."},
            {"id": "gp_art11", "question": "Na koncercie _____ trzy utwory Chopina.", "translation": "(Beim Konzert wurden drei Stücke von Chopin gespielt.)", "options": ["zagrano", "zagrali", "zagrany", "zagra się"], "correct": "zagrano", "explanation": "Unpersönliche Vergangenheitsform '-no/-to': 'zagrano' (man spielte). Diese einzigartige polnische Konstruktion hat keine direkte deutsche Entsprechung – sie drückt eine unbestimmte Person in der Vergangenheit aus, ähnlich wie 'man hat gespielt'. Diese Form ist im Polnischen natürlicher als das vollständige Passiv."},
            {"id": "gp_art12", "question": "Muzeum jest otwarte od poniedziałku _____ piątku.", "translation": "(Das Museum ist von Montag bis Freitag geöffnet.)", "options": ["do", "na", "w", "za"], "correct": "do", "explanation": "'Od...do' (von...bis) – Zeitspanne: 'od poniedziałku do piątku' (von Montag bis Freitag). Die Wochentage stehen im Genitiv nach 'od' und 'do'. Im Deutschen verwendet man 'von...bis' + Dativ/Akkusativ, im Polnischen 'od...do' + Genitiv. Beachte: 'poniedziałek' → 'poniedziałku' (Genitiv)."},
            {"id": "gp_art13", "question": "Ta reżyserka jest _____ wszystkich ceniona.", "translation": "(Diese Regisseurin wird von allen geschätzt.)", "options": ["przez", "dla", "od", "za"], "correct": "przez", "explanation": "'Przez' + Akkusativ gibt den Urheber im Passiv an: 'przez wszystkich' (von allen). Im Deutschen steht 'von' + Dativ, im Polnischen 'przez' + Akkusativ! 'Ceniona' (geschätzt) ist ein Partizip Passiv Femininum, das mit dem Subjekt 'reżyserka' (Regisseurin) übereinstimmt."},
            {"id": "gp_art14", "question": "Znam się _____ sztuce nowoczesnej.", "translation": "(Ich kenne mich in moderner Kunst aus.)", "options": ["na", "w", "z", "o"], "correct": "na", "explanation": "'Znać się na' + Lokativ (sich auskennen in/mit): 'na sztuce nowoczesnej' (in moderner Kunst). Die Rektion 'znać się na' unterscheidet sich vom Deutschen 'sich auskennen in/mit'. 'Sztuka' → 'sztuce' (Lokativ), 'nowoczesna' → 'nowoczesnej' (Lokativ Femininum). Dieses Verb ist ein reflexives Verb mit fester Präposition."},
            {"id": "gp_art15", "question": "Właśnie skończyłem czytać tę _____ książkę.", "translation": "(Ich habe gerade dieses faszinierende Buch zu Ende gelesen.)", "options": ["fascynującą", "fascynujący", "fascynujące", "fascynująca"], "correct": "fascynującą", "explanation": "Akkusativ Femininum des Partizips: 'tę fascynującą książkę' (dieses faszinierende Buch). 'Fascynujący' (faszinierend) ist ein Partizip Präsens Aktiv, das als Adjektiv verwendet wird. Im Akkusativ Femininum wird es zu 'fascynującą'. 'Tę' ist der Demonstrativpronomen-Akkusativ von 'ta' (diese)."}
        ]
    },
    {
        "key": "science_research",
        "name": "Nauka i badania (Wissenschaft und Forschung)",
        "description": "Wissenschaftliche Terminologie und Strukturen für akademische Texte auf Polnisch",
        "icon": "atom",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_sci1", "question": "Naukowcy _____ nowe odkrycie.", "translation": "(Die Wissenschaftler machten eine neue Entdeckung.)", "options": ["dokonali", "dokonają", "dokonują", "dokonywali"], "correct": "dokonali", "explanation": "Perfektiver Aspekt 'dokonać' (machen/vollbringen) im Präteritum: 'dokonali' (sie machten). Der perfektive Aspekt betont die abgeschlossene, einmalige Handlung – die Entdeckung ist fertig. 'Dokonywali' (imperfektiv) würde eine wiederholte oder andauernde Handlung bedeuten. 'Odkrycie' (Entdeckung) steht im Akkusativ."},
            {"id": "gp_sci2", "question": "Wyniki badań _____ w czasopiśmie naukowym.", "translation": "(Die Forschungsergebnisse wurden in einer wissenschaftlichen Zeitschrift veröffentlicht.)", "options": ["opublikowano", "opublikowali", "publikuje się", "opublikowane"], "correct": "opublikowano", "explanation": "Die unpersönliche -no/-to Form: 'opublikowano' (man veröffentlichte). Diese typisch polnische Konstruktion ist in wissenschaftlichen Texten sehr häufig und vermeidet die Nennung des Handelnden. Im Deutschen verwendet man das Passiv ('wurden veröffentlicht'), im Polnischen bevorzugt man die -no/-to Form für formelle/wissenschaftliche Texte."},
            {"id": "gp_sci3", "question": "Według _____ badań, wyniki są obiecujące.", "translation": "(Laut neuesten Studien sind die Ergebnisse vielversprechend.)", "options": ["najnowszych", "najnowsze", "najnowszymi", "najnowszym"], "correct": "najnowszych", "explanation": "'Według' + Genitiv: 'według najnowszych badań' (laut neuester Studien). Die Präposition 'według' (laut/gemäß) regiert immer den Genitiv. 'Najnowszy' (neuester, Superlativ von 'nowy') wird im Genitiv Plural zu 'najnowszych'. 'Badania' (Studien/Forschungen) im Genitiv Plural bleibt 'badań'."},
            {"id": "gp_sci4", "question": "Eksperyment _____ w laboratorium.", "translation": "(Das Experiment wurde im Labor durchgeführt.)", "options": ["przeprowadzono", "przeprowadził się", "przeprowadza", "przeprowadzał"], "correct": "przeprowadzono", "explanation": "Wieder die -no/-to Form für wissenschaftliches Register: 'przeprowadzono' (man führte durch). 'Przeprowadzić eksperyment' (ein Experiment durchführen) – das Präfix 'prze-' bedeutet 'durch'. 'W laboratorium' – Lokativ nach 'w' für den Ort. In wissenschaftlichen polnischen Texten wird die -no/-to Form dem Passiv vorgezogen."},
            {"id": "gp_sci5", "question": "Hipoteza została _____ przez nowe dane.", "translation": "(Die Hypothese wurde durch neue Daten bestätigt.)", "options": ["potwierdzona", "potwierdzony", "potwierdzone", "potwierdzeni"], "correct": "potwierdzona", "explanation": "Partizip Passiv Femininum: 'potwierdzona' (bestätigt), weil 'hipoteza' (Hypothese) feminin ist. Im Deutschen ist 'Hypothese' auch feminin, aber in anderen Fällen können die Genera abweichen. 'Przez nowe dane' (durch neue Daten) – 'przez' + Akkusativ für den Urheber/das Mittel im Passiv."},
            {"id": "gp_sci6", "question": "Badacze analizują wpływ zanieczyszczeń _____ środowisko.", "translation": "(Die Forscher analysieren den Einfluss von Verschmutzung auf die Umwelt.)", "options": ["na", "do", "w", "z"], "correct": "na", "explanation": "'Wpływ na' + Akkusativ (Einfluss auf): 'wpływ na środowisko' (Einfluss auf die Umwelt). Die Rektion 'wpływ na' entspricht dem Deutschen 'Einfluss auf'. 'Środowisko' bleibt im Akkusativ unverändert (Neutrum). 'Zanieczyszczenia' (Verschmutzungen) stehen im Genitiv nach 'wpływ' als Besitzangabe."},
            {"id": "gp_sci7", "question": "Z badań wynika, _____ metoda jest skuteczna.", "translation": "(Aus den Studien geht hervor, dass die Methode wirksam ist.)", "options": ["że ta", "że ten", "która ta", "bo ta"], "correct": "że ta", "explanation": "'Że' (dass) – Konjunktion für Nebensätze: 'wynika, że...' (es ergibt sich, dass...). Im Polnischen bleibt die Wortstellung im Nebensatz normal (SVO), anders als im Deutschen, wo das Verb ans Ende geht! 'Ta metoda' (diese Methode) – Demonstrativpronomen + Substantiv im Nominativ als Subjekt des Nebensatzes."},
            {"id": "gp_sci8", "question": "Teoria ewolucji jest powszechnie _____ w nauce.", "translation": "(Die Evolutionstheorie ist in der Wissenschaft allgemein akzeptiert.)", "options": ["akceptowana", "akceptowany", "akceptowane", "akceptując"], "correct": "akceptowana", "explanation": "Partizip im Femininum: 'akceptowana' (akzeptiert), da 'teoria' (Theorie) feminin ist. 'Powszechnie' (allgemein) ist ein Adverb. 'W nauce' (in der Wissenschaft) – Lokativ nach 'w'. Beachte, dass im Polnischen das Partizip als Prädikativ mit 'jest' (ist) steht, ähnlich wie im Deutschen mit 'sein'."},
            {"id": "gp_sci9", "question": "Dokonano analizy _____ czterech zmiennych.", "translation": "(Eine Analyse von vier Variablen wurde durchgeführt.)", "options": ["obejmującej", "obejmujący", "obejmujące", "obejmująca"], "correct": "obejmującej", "explanation": "Genitiv Femininum des Partizips: 'analizy obejmującej' (einer Analyse, die umfasst). 'Analiza' ist feminin, im Genitiv 'analizy'. Das Partizip 'obejmujący' (umfassend) muss im selben Kasus stehen: Genitiv Femininum = 'obejmującej'. Partizipien als Attribute werden im Polnischen häufig in wissenschaftlichen Texten verwendet."},
            {"id": "gp_sci10", "question": "Nie udało się _____ wyników pierwszego eksperymentu.", "translation": "(Es gelang nicht, die Ergebnisse des ersten Experiments zu reproduzieren.)", "options": ["odtworzyć", "odtworzyli", "odtwarzać", "odtworzenie"], "correct": "odtworzyć", "explanation": "'Udać się' + Infinitiv: 'nie udało się odtworzyć' (es gelang nicht zu reproduzieren). Die unpersönliche Konstruktion 'udać się' (gelingen) im Neutrum + negierter Infinitiv. Nach der Negation 'nie' steht das Objekt im Genitiv: 'wyników' statt 'wyniki'. Der perfektive Infinitiv 'odtworzyć' betont das angestrebte Ergebnis."},
            {"id": "gp_sci11", "question": "Próbka została _____ pod mikroskopem.", "translation": "(Die Probe wurde unter dem Mikroskop untersucht.)", "options": ["zbadana", "zbadany", "zbadane", "badana"], "correct": "zbadana", "explanation": "Perfektives Partizip Femininum: 'zbadana' (untersucht), da 'próbka' (Probe) feminin ist. 'Zbadać' (untersuchen, perfektiv) vs. 'badać' (untersuchen, imperfektiv). Der perfektive Aspekt zeigt die abgeschlossene Handlung. 'Pod mikroskopem' – 'pod' + Instrumental für 'unter dem Mikroskop'."},
            {"id": "gp_sci12", "question": "Uczeni doszli do _____, że teoria jest błędna.", "translation": "(Die Gelehrten kamen zu dem Schluss, dass die Theorie fehlerhaft ist.)", "options": ["wniosku", "wniosek", "wnioskiem", "wnioskowi"], "correct": "wniosku", "explanation": "'Dojść do' + Genitiv: 'dojść do wniosku' (zu einem Schluss kommen). Die Wendung 'dojść do wniosku' verlangt den Genitiv. 'Wniosek' (Schlussfolgerung) wird im Genitiv zu 'wniosku'. Im Deutschen verwendet man 'zu einem Schluss kommen' mit 'zu' + Dativ. Der 'że'-Satz folgt als Inhalt der Schlussfolgerung."},
            {"id": "gp_sci13", "question": "Projekt jest _____ przez międzynarodowy zespół.", "translation": "(Das Projekt wird von einem internationalen Team realisiert.)", "options": ["realizowany", "realizowana", "realizowane", "realizowani"], "correct": "realizowany", "explanation": "Partizip im Maskulinum: 'realizowany' (realisiert/durchgeführt), da 'projekt' maskulin ist. 'Przez międzynarodowy zespół' (von einem internationalen Team) – 'przez' + Akkusativ für den Agenten. Das imperfektive Partizip 'realizowany' (vs. perfektiv 'zrealizowany') zeigt einen laufenden Prozess."},
            {"id": "gp_sci14", "question": "Dane należy _____ ostrożnie.", "translation": "(Die Daten sollten vorsichtig interpretiert werden.)", "options": ["interpretować", "interpretacji", "interpretowane", "interpretując"], "correct": "interpretować", "explanation": "'Należy' + Infinitiv: 'należy interpretować' (man sollte interpretieren). Die unpersönliche Konstruktion 'należy' (es gehört sich/man sollte) + Infinitiv ist im wissenschaftlichen Polnisch sehr verbreitet. Sie ist formeller als 'trzeba'. 'Ostrożnie' (vorsichtig) ist ein Adverb. 'Dane' (Daten) steht im Nominativ/Akkusativ (gleiche Form bei Nicht-Maskulin-Belebt)."},
            {"id": "gp_sci15", "question": "Odkrycie to przyczyni się _____ rozwoju medycyny.", "translation": "(Diese Entdeckung wird zur Entwicklung der Medizin beitragen.)", "options": ["do", "na", "w", "za"], "correct": "do", "explanation": "'Przyczynić się do' + Genitiv: 'do rozwoju medycyny' (zur Entwicklung der Medizin). Die Rektion 'przyczynić się do' (beitragen zu) verlangt den Genitiv. Im Deutschen steht 'beitragen zu' + Dativ. 'Rozwój' (Entwicklung) → 'rozwoju' (Genitiv), 'medycyna' (Medizin) → 'medycyny' (Genitiv). Diese Doppel-Genitiv-Kette ist typisch für polnische wissenschaftliche Texte."}
        ]
    },
    {
        "key": "academic_polish",
        "name": "Polski akademicki (Akademisches Polnisch)",
        "description": "Formelle Strukturen und Wendungen für akademisches Schreiben und Sprechen auf Polnisch",
        "icon": "graduationcap",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_acad1", "question": "_____ rozważyć aspekt ekonomiczny.", "translation": "(Es lohnt sich, den wirtschaftlichen Aspekt zu berücksichtigen.)", "options": ["Warto", "Trzeba", "Powinno", "Chce się"], "correct": "Warto", "explanation": "'Warto' (es lohnt sich) + Infinitiv – unpersönliche Empfehlung in akademischem Register. 'Warto' drückt aus, dass etwas empfehlenswert ist, ohne eine strenge Pflicht zu implizieren (wie 'trzeba'). Im Deutschen entspricht dies 'es lohnt sich/es ist wert'. In akademischen Texten wird 'warto' häufig für Forschungsvorschläge verwendet."},
            {"id": "gp_acad2", "question": "Jak _____ wcześniej, problem jest złożony.", "translation": "(Wie bereits erwähnt, ist das Problem komplex.)", "options": ["wspomniano", "wspomniał", "wspomniane", "wspomina się"], "correct": "wspomniano", "explanation": "'Wspomniano' – die -no/-to Form von 'wspomnieć' (erwähnen): 'jak wspomniano wcześniej' (wie zuvor erwähnt). Diese unpersönliche Passivform ist das Markenzeichen des polnischen akademischen Stils. Sie vermeidet die Nennung des Subjekts und klingt objektiver als 'wie ich erwähnte'. Im Deutschen verwendet man 'wie erwähnt wurde'."},
            {"id": "gp_acad3", "question": "Biorąc pod _____ wszystkie czynniki, wynik jest pozytywny.", "translation": "(Unter Berücksichtigung aller Faktoren ist das Ergebnis positiv.)", "options": ["uwagę", "uwagi", "uwagą", "uwadze"], "correct": "uwagę", "explanation": "'Brać pod uwagę' (berücksichtigen/in Betracht ziehen) – feste Wendung mit Akkusativ: 'pod uwagę'. 'Biorąc' ist ein Adverbialpartizip (Gerundium) von 'brać'. Diese Partizipialkonstruktion ist in akademischen Texten sehr häufig und entspricht dem Deutschen 'unter Berücksichtigung' oder 'wenn man berücksichtigt'."},
            {"id": "gp_acad4", "question": "Niniejszy artykuł ma _____ celu analizę problemu.", "translation": "(Der vorliegende Artikel hat zum Ziel, das Problem zu analysieren.)", "options": ["na", "do", "w", "za"], "correct": "na", "explanation": "'Mieć na celu' (zum Ziel haben) – feste Wendung: 'na' + Lokativ/Akkusativ. 'Niniejszy' (vorliegend/hiermit) ist ein typisches Wort des akademischen und offiziellen Registers. Im Deutschen: 'der vorliegende Artikel'. 'Analiza problemu' – Genitiv des Objekts, typisch für wissenschaftliche Aktivitäten auf Polnisch."},
            {"id": "gp_acad5", "question": "Z powyższych danych _____, że wzrost jest znaczący.", "translation": "(Aus den obigen Daten geht hervor, dass das Wachstum signifikant ist.)", "options": ["wynika", "wynikają", "wynikało", "wyniknie"], "correct": "wynika", "explanation": "'Wynikać' (hervorgehen/sich ergeben) im Singular: 'wynika, że...' (es ergibt sich, dass...). Obwohl 'dane' (Daten) Plural ist, verwendetet man 'wynika' unpersönlich mit der Konstruktion 'z danych wynika'. Im Deutschen: 'aus den Daten geht hervor'. 'Powyższy' (obig/obengenannt) ist ein typisches akademisches Adjektiv."},
            {"id": "gp_acad6", "question": "Problem ten wymaga _____ badań.", "translation": "(Dieses Problem erfordert weitere Untersuchungen.)", "options": ["dalszych", "dalsze", "dalszymi", "dalszym"], "correct": "dalszych", "explanation": "'Wymagać' (erfordern/verlangen) + Genitiv: 'dalszych badań' (weiterer Untersuchungen). 'Wymagać' regiert immer den Genitiv, anders als im Deutschen 'erfordern' + Akkusativ. 'Dalszy' (weiter/entfernter) im Genitiv Plural → 'dalszych'. 'Badania' (Untersuchungen) → 'badań' (Genitiv Plural). Doppelter Genitiv ist typisch für akademisches Polnisch."},
            {"id": "gp_acad7", "question": "Podsumowując, _____ stwierdzić, że hipoteza się potwierdziła.", "translation": "(Zusammenfassend lässt sich feststellen, dass die Hypothese bestätigt wurde.)", "options": ["można", "trzeba", "warto", "musi"], "correct": "można", "explanation": "'Można' (man kann) + Infinitiv – unpersönliche Möglichkeit: 'można stwierdzić' (es lässt sich feststellen). 'Podsumowując' (zusammenfassend) ist ein Adverbialpartizip. 'Potwierdzić się' (sich bestätigen) – reflexives Verb. Im Polnischen wird 'sich bestätigen' verwendet, wo im Deutschen 'bestätigt werden' stehen könnte."},
            {"id": "gp_acad8", "question": "W świetle powyższych _____ wnioski są jasne.", "translation": "(Im Lichte der obigen Überlegungen sind die Schlussfolgerungen klar.)", "options": ["rozważań", "rozważania", "rozważaniami", "rozważaniom"], "correct": "rozważań", "explanation": "'W świetle' (im Lichte/angesichts) + Genitiv: 'w świetle rozważań' (im Lichte der Überlegungen). Diese Wendung ist im akademischen Polnisch sehr gebräuchlich. 'Rozważania' (Überlegungen/Erwägungen) → 'rozważań' (Genitiv Plural). Im Deutschen: 'im Lichte der Überlegungen' – ähnliche Konstruktion mit Genitiv."},
            {"id": "gp_acad9", "question": "Autor _____ się do teorii Kowalskiego.", "translation": "(Der Autor bezieht sich auf die Theorie von Kowalski.)", "options": ["odnosi", "odniesie", "odniósł", "odnosi się"], "correct": "odnosi", "explanation": "'Odnosić się do' + Genitiv (sich beziehen auf): 'odnosi się do teorii' (bezieht sich auf die Theorie). Das Reflexivverb 'odnosić się do' regiert den Genitiv, während im Deutschen 'sich beziehen auf' den Akkusativ verlangt. 'Teorii Kowalskiego' – doppelter Genitiv: der Theorie (Gen.) von Kowalski (Gen. Nachname)."},
            {"id": "gp_acad10", "question": "Nie sposób _____ ten fakt.", "translation": "(Es ist unmöglich, diese Tatsache zu ignorieren.)", "options": ["zignorować", "ignoruje", "ignorowania", "ignorować się"], "correct": "zignorować", "explanation": "'Nie sposób' + perfektiver Infinitiv (es ist unmöglich zu): 'nie sposób zignorować' (es ist unmöglich zu ignorieren). 'Nie sposób' ist eine gehobene, akademische Form für 'es ist unmöglich'. Der perfektive Aspekt 'z-ignorować' betont, dass die Handlung nicht einmal einmalig möglich ist. Eine sehr elegante Formulierung im akademischen Register."},
            {"id": "gp_acad11", "question": "Celem niniejszej pracy jest _____ tego zjawiska.", "translation": "(Das Ziel der vorliegenden Arbeit ist die Beschreibung dieses Phänomens.)", "options": ["opis", "opisać", "opisanie", "opisem"], "correct": "opis", "explanation": "'Celem jest opis' (das Ziel ist die Beschreibung) – Nominativ des Nomens als Prädikativ. 'Opis' (Beschreibung) steht im Nominativ. Alternativ akzeptabel wäre 'opisanie' (das Beschreiben – Verbalsubstantiv). 'Tego zjawiska' (dieses Phänomens) – Genitiv des Objekts. 'Niniejszy' (vorliegend) ist typisch für den akademischen Stil."},
            {"id": "gp_acad12", "question": "Teza ta jest _____ z wynikami innych badaczy.", "translation": "(Diese These steht im Einklang mit den Ergebnissen anderer Forscher.)", "options": ["zgodna", "zgodny", "zgodne", "zgodni"], "correct": "zgodna", "explanation": "'Zgodny z' + Instrumental (übereinstimmend mit): 'zgodna z wynikami' (übereinstimmend mit den Ergebnissen). 'Teza' (These) ist feminin, daher 'zgodna' (Femininum). 'Innych badaczy' (anderer Forscher) – Genitiv Plural als Attribut. Im Deutschen: 'im Einklang mit' + Dativ, im Polnischen 'zgodny z' + Instrumental."},
            {"id": "gp_acad13", "question": "Na _____ tego artykułu warto wspomnieć o ograniczeniach.", "translation": "(Am Ende dieses Artikels lohnt es sich, die Einschränkungen zu erwähnen.)", "options": ["zakończenie", "zakończeniu", "końcu", "zakończenia"], "correct": "zakończenie", "explanation": "'Na zakończenie' (zum Abschluss/am Ende) – feste Wendung: 'na' + Akkusativ in temporal-abschließender Funktion. Alternativ: 'na końcu' (am Ende). 'Warto wspomnieć o' + Lokativ (es lohnt sich zu erwähnen über): 'o ograniczeniach' (über Einschränkungen). Im akademischen Stil sehr gebräuchlich."},
            {"id": "gp_acad14", "question": "Przedstawione dane _____ tezę autora.", "translation": "(Die präsentierten Daten stützen die These des Autors.)", "options": ["potwierdzają", "potwierdza", "potwierdziła", "potwierdzono"], "correct": "potwierdzają", "explanation": "Imperfektiver Plural: 'potwierdzają' (bestätigen/stützen), da 'dane' (Daten) Plural ist. Der imperfektive Aspekt zeigt eine allgemeine Gültigkeit, nicht eine einmalige Handlung. 'Przedstawione' (präsentiert) ist ein Partizip Passiv als Attribut. 'Tezę autora' – Akkusativ + Genitiv: die These (Akk.) des Autors (Gen.)."},
            {"id": "gp_acad15", "question": "Ze względu _____ ograniczenia badania, wyniki mają charakter wstępny.", "translation": "(Aufgrund der Einschränkungen der Studie haben die Ergebnisse vorläufigen Charakter.)", "options": ["na", "do", "z", "o"], "correct": "na", "explanation": "'Ze względu na' + Akkusativ (aufgrund/wegen): 'ze względu na ograniczenia' (aufgrund der Einschränkungen). Diese formelle Wendung ist das Äquivalent zum Deutschen 'aufgrund' + Genitiv. Im Polnischen steht nach 'ze względu na' der Akkusativ! 'Mieć charakter wstępny' (vorläufigen Charakter haben) ist eine typische akademische Formulierung."}
        ]
    },
    {
        "key": "business_economics",
        "name": "Biznes i ekonomia (Wirtschaft und Business)",
        "description": "Geschäftspolnisch – Vokabular und Strukturen für berufliche und wirtschaftliche Kontexte",
        "icon": "briefcase",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_biz1", "question": "Firma podpisała _____ z nowym partnerem.", "translation": "(Die Firma unterschrieb einen Vertrag mit dem neuen Partner.)", "options": ["umowę", "umowa", "umowy", "umową"], "correct": "umowę", "explanation": "Akkusativ Femininum: 'podpisać umowę' (einen Vertrag unterschreiben). 'Umowa' (Vertrag) → 'umowę' (Akkusativ). 'Z nowym partnerem' – 'z' + Instrumental: 'mit dem neuen Partner'. Im Deutschen: 'einen Vertrag mit jemandem unterschreiben' – ähnliche Struktur, aber im Polnischen ist 'Vertrag' feminin."},
            {"id": "gp_biz2", "question": "Obroty firmy wzrosły _____ dwadzieścia procent.", "translation": "(Der Umsatz der Firma stieg um zwanzig Prozent.)", "options": ["o", "na", "za", "do"], "correct": "o", "explanation": "'Wzrosnąć o' + Akkusativ (steigen um): 'o dwadzieścia procent' (um zwanzig Prozent). Die Präposition 'o' drückt das Maß einer Veränderung aus. Im Deutschen: 'um zwanzig Prozent steigen'. 'Obroty firmy' (Umsatz der Firma) – Genitiv 'firmy' als Attribut. 'Wzrosnąć' ist der perfektive Aspekt von 'rosnąć' (wachsen)."},
            {"id": "gp_biz3", "question": "Inwestycja przyniosła duże _____.", "translation": "(Die Investition brachte große Gewinne.)", "options": ["zyski", "zysk", "zysków", "zyskami"], "correct": "zyski", "explanation": "Akkusativ Plural: 'duże zyski' (große Gewinne). 'Przynieść' (bringen, perfektiv) + Akkusativ: 'przyniosła zyski'. 'Zysk' ist maskulin unbelebt, daher ist der Akkusativ Plural = Nominativ Plural: 'zyski'. Adjektiv 'duże' (große) im Akkusativ Plural für unbelebte Maskulina. Im Deutschen: 'Gewinne bringen'."},
            {"id": "gp_biz4", "question": "Szef poprosił nas _____ przygotowanie raportu.", "translation": "(Der Chef bat uns um die Vorbereitung des Berichts.)", "options": ["o", "za", "na", "do"], "correct": "o", "explanation": "'Prosić o' + Akkusativ (bitten um): 'poprosił nas o przygotowanie' (bat uns um die Vorbereitung). 'Prosić' im Polnischen regiert mit 'o' + Akkusativ, im Deutschen 'bitten um' + Akkusativ – ähnliche Struktur! 'Przygotowanie raportu' – Verbalsubstantiv + Genitiv des Objekts: die Vorbereitung (Akk.) des Berichts (Gen.)."},
            {"id": "gp_biz5", "question": "Na spotkaniu omówiliśmy _____ biznesowy.", "translation": "(Beim Meeting besprachen wir den Geschäftsplan.)", "options": ["plan", "planu", "planem", "planowi"], "correct": "plan", "explanation": "Akkusativ Maskulinum unbelebt: 'omówić plan' (einen Plan besprechen). Bei unbelebten Maskulina ist der Akkusativ = Nominativ: 'plan'. 'Na spotkaniu' (beim Meeting) – 'na' + Lokativ für den Ort des Treffens. 'Omówić' (besprechen, perfektiv) – der perfektive Aspekt zeigt ein abgeschlossenes Meeting."},
            {"id": "gp_biz6", "question": "Musimy obniżyć koszty _____ dwadzieścia procent.", "translation": "(Wir müssen die Kosten um zwanzig Prozent senken.)", "options": ["o", "na", "za", "do"], "correct": "o", "explanation": "'Obniżyć o' + Akkusativ (senken um): 'o dwadzieścia procent' (um zwanzig Prozent). Wie bei 'wzrosnąć o', drückt 'o' das Maß der Veränderung aus. 'Koszty' (Kosten) im Akkusativ Plural. 'Musieć' (müssen) + Infinitiv 'obniżyć' (senken, perfektiv). Die perfektive Form betont das angestrebte Ergebnis der Kostensenkung."},
            {"id": "gp_biz7", "question": "Budżet został _____ na przyszły rok.", "translation": "(Das Budget wurde für das nächste Jahr genehmigt.)", "options": ["zatwierdzony", "zatwierdzona", "zatwierdzone", "zatwierdzeni"], "correct": "zatwierdzony", "explanation": "Partizip Maskulinum: 'zatwierdzony' (genehmigt), da 'budżet' (Budget) maskulin ist. Im Deutschen ist 'Budget' neutrum, im Polnischen maskulin – die Genera unterscheiden sich! 'Na przyszły rok' (für das nächste Jahr) – 'na' + Akkusativ für zukünftige Zeitangaben. Das Passiv mit 'zostać' zeigt eine abgeschlossene Handlung."},
            {"id": "gp_biz8", "question": "Klienci byli _____ z jakości usług.", "translation": "(Die Kunden waren mit der Qualität der Dienstleistungen zufrieden.)", "options": ["zadowoleni", "zadowolony", "zadowolone", "zadowolonym"], "correct": "zadowoleni", "explanation": "'Zadowoleni' – Maskulin-Personal-Plural (Virilis): 'zadowoleni z' + Genitiv (zufrieden mit). Da 'klienci' männliche Personen sind, muss die sogenannte 'Virilis'-Form verwendet werden. Im Polnischen gibt es im Plural eine Sonderform für Gruppen mit mindestens einem Mann. 'Z jakości' (mit der Qualität) – Genitiv nach 'z'."},
            {"id": "gp_biz9", "question": "Proponuję, _____ przeanalizować tę ofertę.", "translation": "(Ich schlage vor, dass wir dieses Angebot analysieren.)", "options": ["żebyśmy", "żeby", "że", "abyśmy"], "correct": "żebyśmy", "explanation": "'Żebyśmy' (dass wir...) – Konjunktiv im Vorschlag: 'proponuję, żebyśmy przeanalizowali' (ich schlage vor, dass wir analysieren). '-byśmy' enthält die Personalendung der 1. Person Plural. Im Deutschen: 'dass wir analysieren' (Konjunktiv I). 'Abyśmy' wäre eine formellere Alternative, aber 'żebyśmy' ist in Geschäftsmeetings üblicher."},
            {"id": "gp_biz10", "question": "Rynek jest bardzo _____.", "translation": "(Der Markt ist sehr wettbewerbsfähig.)", "options": ["konkurencyjny", "konkurencyjna", "konkurencyjne", "konkurencyjni"], "correct": "konkurencyjny", "explanation": "'Konkurencyjny' (wettbewerbsfähig) – Maskulinum Singular für 'rynek' (Markt). 'Bardzo' (sehr) + Adjektiv – Intensifikator. Im Polnischen wird das Adjektiv prädikativ verwendet: 'rynek jest konkurencyjny' (der Markt ist wettbewerbsfähig). Die Endung '-ny/-na/-ne' ändert sich je nach Genus des Substantivs."},
            {"id": "gp_biz11", "question": "Pracuję w tej firmie _____ pięciu lat.", "translation": "(Ich arbeite seit fünf Jahren in dieser Firma.)", "options": ["od", "z", "za", "przez"], "correct": "od", "explanation": "'Od' + Genitiv (seit): 'od pięciu lat' (seit fünf Jahren). Die Präposition 'od' für andauernde Zeiträume, die in der Gegenwart noch gelten. 'Pięciu lat' – Genitiv von 'pięć lat' (fünf Jahre). Bei Zahlen ab 5 steht im Polnischen der Genitiv Plural. 'W tej firmie' (in dieser Firma) – 'w' + Lokativ für den Arbeitsort."},
            {"id": "gp_biz12", "question": "Eksport wzrósł dzięki _____ kursowi walutowemu.", "translation": "(Der Export stieg dank dem günstigen Wechselkurs.)", "options": ["korzystnemu", "korzystny", "korzystnym", "korzystnego"], "correct": "korzystnemu", "explanation": "'Dzięki' + Dativ: 'dzięki korzystnemu kursowi' (dank dem günstigen Kurs). Die Präposition 'dzięki' (dank) regiert immer den Dativ. 'Korzystny' (günstig/vorteilhaft) → 'korzystnemu' (Dativ Maskulinum). 'Kurs walutowy' (Wechselkurs) → 'kursowi walutowemu' (Dativ). Im Deutschen: 'dank' + Dativ/Genitiv."},
            {"id": "gp_biz13", "question": "Prezes zarządu podjął _____ o restrukturyzacji.", "translation": "(Der Vorstandsvorsitzende traf die Entscheidung über die Restrukturierung.)", "options": ["decyzję", "decyzja", "decyzji", "decyzją"], "correct": "decyzję", "explanation": "'Podjąć decyzję' (eine Entscheidung treffen) – feste Wendung: 'podjąć' + Akkusativ: 'decyzję'. 'O restrukturyzacji' (über die Restrukturierung) – 'o' + Lokativ für das Thema der Entscheidung. 'Prezes zarządu' (Vorstandsvorsitzender) – 'zarządu' im Genitiv als Attribut. Im Deutschen: 'eine Entscheidung treffen'."},
            {"id": "gp_biz14", "question": "Bankructwo firmy _____ z powodu złego zarządzania.", "translation": "(Die Insolvenz der Firma geschah wegen schlechter Führung.)", "options": ["nastąpiło", "nastąpił", "nastąpiła", "nastąpili"], "correct": "nastąpiło", "explanation": "'Nastąpić' (eintreten/geschehen) im Neutrum: 'nastąpiło', weil 'bankructwo' (Insolvenz/Bankrott) neutrum ist. 'Z powodu' + Genitiv (wegen): 'z powodu złego zarządzania' (wegen schlechter Führung). Im Deutschen: 'wegen' + Genitiv – gleiche Konstruktion! Das Verbalsubstantiv 'zarządzanie' (Führung/Management) steht im Genitiv."},
            {"id": "gp_biz15", "question": "Nasz _____ biznesowy przewiduje wzrost sprzedaży.", "translation": "(Unser Geschäftsplan sieht ein Umsatzwachstum vor.)", "options": ["plan", "planu", "planem", "planowi"], "correct": "plan", "explanation": "'Plan biznesowy' (Geschäftsplan) im Nominativ als Subjekt. 'Nasz' (unser) + Maskulinum: 'nasz plan'. 'Przewidywać' (vorsehen/prognostizieren) + Akkusativ: 'wzrost sprzedaży' (Wachstum des Umsatzes). 'Sprzedaż' (Umsatz/Verkauf) im Genitiv: 'sprzedaży'. Im Deutschen: 'der Geschäftsplan sieht vor' – identische Satzstruktur."}
        ]
    },
    {
        "key": "common_errors",
        "name": "Typowe błędy (Häufige Fehler)",
        "description": "Die häufigsten Fehler deutschsprachiger Polnischlerner – und wie man sie vermeidet",
        "icon": "exclamationmark.triangle",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_err1", "question": "Lubię _____ (Ich mag Kaffee – welcher Kasus nach 'lubić'?)", "translation": "(Ich mag Kaffee.)", "options": ["kawę", "kawy", "kawie", "kawą"], "correct": "kawę", "explanation": "Häufiger Fehler: Genitiv statt Akkusativ nach 'lubić'. Deutsche Lerner verwenden oft den Genitiv, weil 'lubić' wie ein 'Genitivverb' klingt. Richtig: 'lubić' + Akkusativ: 'lubię kawę'. Nur nach NEGATION wechselt es zum Genitiv: 'nie lubię kawy'. Diese Akkusativ→Genitiv-Verschiebung bei Negation gibt es im Deutschen nicht."},
            {"id": "gp_err2", "question": "Ona jest _____. (Fehler: Genus des Adjektivs)", "translation": "(Sie ist müde.)", "options": ["zmęczona", "zmęczony", "zmęczone", "zmęczeni"], "correct": "zmęczona", "explanation": "Häufiger Fehler: Maskulinform statt Femininform. Im Deutschen hat 'müde' keine Genusform, im Polnischen muss 'zmęczony' zum Subjekt passen: 'ona' (sie) = Femininum → 'zmęczona'. Deutsche Lerner vergessen oft die Genusendungen bei Adjektiven, weil das Deutsche diese Unterscheidung im Prädikativ nicht kennt."},
            {"id": "gp_err3", "question": "Nie mam _____. (nach Negation: welcher Kasus?)", "translation": "(Ich habe kein Geld.)", "options": ["pieniędzy", "pieniądze", "pieniądzami", "pieniądzom"], "correct": "pieniędzy", "explanation": "Häufiger Fehler: Akkusativ statt Genitiv nach negiertem 'mieć'. Im Polnischen wechselt das direkte Objekt bei Negation vom Akkusativ zum Genitiv: 'mam pieniądze' (Akk.) → 'nie mam pieniędzy' (Gen.). Diese Regel gibt es im Deutschen nicht! Der Genitiv nach Negation ist eine der wichtigsten Regeln des Polnischen."},
            {"id": "gp_err4", "question": "Idę _____ lekarza. (Richtung, nicht Ort!)", "translation": "(Ich gehe zum Arzt.)", "options": ["do", "w", "na", "u"], "correct": "do", "explanation": "Häufiger Fehler: 'u lekarza' statt 'do lekarza'. 'U lekarza' bedeutet 'beim Arzt' (Ort), aber 'do lekarza' bedeutet 'zum Arzt' (Richtung). Im Deutschen unterscheidet man 'beim' (wo?) vs. 'zum' (wohin?), im Polnischen 'u' + Genitiv (wo?) vs. 'do' + Genitiv (wohin?). Bei Bewegungsverben wie 'iść' (gehen) immer 'do'!"},
            {"id": "gp_err5", "question": "Moi bracia _____ lekarkami. (Maskulin-Personal-Plural!)", "translation": "(Meine Brüder sind Ärzte.)", "options": ["są lekarzami", "są lekarkami", "jest lekarzami", "są lekarze"], "correct": "są lekarzami", "explanation": "Häufiger Fehler: falsche Genus/Numerus-Übereinstimmung. 'Bracia' (Brüder) sind Maskulin-Personal → 'lekarzami' (Ärzten, masc. Instrumental), nicht 'lekarkami' (Ärztinnen, fem.). Im Polnischen gibt es die Virilis-Kategorie: bei Gruppen mit mindestens einem Mann verwendet man maskulin-personale Formen. 'Być' + Instrumental für Berufsbezeichnungen."},
            {"id": "gp_err6", "question": "Mieszkam w Polsce _____ pięciu lat. (seit fünf Jahren)", "translation": "(Ich wohne seit fünf Jahren in Polen.)", "options": ["od", "przez", "za", "przed"], "correct": "od", "explanation": "Häufiger Fehler: 'przez' statt 'od'. 'Od pięciu lat' = 'seit fünf Jahren' (andauernder Zustand). 'Przez pięć lat' = 'fünf Jahre lang' (abgeschlossener Zeitraum). Im Deutschen: 'seit' vs. 'während/lang'. Deutsche Lerner verwechseln diese Präpositionen, weil sie sich nur auf 'seit/für' konzentrieren, ohne den Aspektunterschied zu beachten."},
            {"id": "gp_err7", "question": "Chłopcy _____ do szkoły. (Maskulin-Personal-Plural Vergangenheit!)", "translation": "(Die Jungen gingen zur Schule.)", "options": ["poszli", "poszły", "poszło", "poszła"], "correct": "poszli", "explanation": "Häufiger Fehler: falsche Vergangenheitsform. Im Polnischen hat die Vergangenheitsform Genusformen! 'Chłopcy' (Jungen) = Maskulin-Personal → 'poszli' (-li Endung). Nicht-maskulin-personal wäre 'poszły'. Im Deutschen gibt es keine Genusunterscheidung im Präteritum. Diese Virilis-Unterscheidung ist für Deutsche besonders schwierig."},
            {"id": "gp_err8", "question": "Czytałem tę książkę przez dwie _____. (Stunden, Kasus nach 'dwie'!)", "translation": "(Ich habe dieses Buch zwei Stunden lang gelesen.)", "options": ["godziny", "godzin", "godzinom", "godzinami"], "correct": "godziny", "explanation": "Häufiger Fehler: Genitiv Plural statt Akkusativ nach 'dwie'. Die Zahlwörter 2-4 verlangen den Nominativ/Akkusativ Plural: 'dwie godziny'. Ab 5 steht der Genitiv Plural: 'pięć godzin'. Dieses System (2-4 vs. 5+) gibt es im Deutschen nicht und ist eine der schwierigsten polnischen Grammatikregeln für Deutsche. 'Durch zwei Stunden lang' = 'przez dwie godziny'."},
            {"id": "gp_err9", "question": "Interesuje się _____ polską. (sich interessieren FÜR)", "translation": "(Ich interessiere mich für polnische Geschichte.)", "options": ["historią", "historię", "historia", "historii"], "correct": "historią", "explanation": "Häufiger Fehler: Akkusativ statt Instrumental nach 'interesować się'. Im Deutschen: 'sich interessieren für' + Akkusativ. Im Polnischen: 'interesować się' + Instrumental! 'Historia polska' → 'historią polską' (Instrumental). Jedes reflexive Verb hat seine eigene Kasusrektion – man muss sie auswendig lernen. Dies ist ein typischer Transferfehler."},
            {"id": "gp_err10", "question": "On jest _____ niż ja. (Komparativ: größer ALS)", "translation": "(Er ist größer als ich.)", "options": ["wyższy ode mnie", "wyższy jak ja", "wyższy od mną", "więcej wysoki"], "correct": "wyższy ode mnie", "explanation": "Häufiger Fehler: 'jak' statt 'od' + Genitiv. Im Polnischen: Komparativ + 'od' + Genitiv ODER 'niż' + Nominativ. NICHT 'jak'! 'Ode mnie' ist die erweiterte Form von 'od mnie' vor 'mnie'. Auch 'więcej wysoki' (mehr groß) ist falsch – im Polnischen bildet man den Komparativ synthetisch: 'wysoki' → 'wyższy'. Analytische Komparative sind selten."},
            {"id": "gp_err11", "question": "Potrzebuję nowego _____. (brauchen + welcher Kasus?)", "translation": "(Ich brauche einen neuen Computer.)", "options": ["komputera", "komputer", "komputerem", "komputerowi"], "correct": "komputera", "explanation": "Häufiger Fehler: Akkusativ statt Genitiv nach 'potrzebować'. Im Deutschen: 'brauchen' + Akkusativ ('einen neuen Computer'). Im Polnischen: 'potrzebować' + Genitiv! 'Nowy komputer' → 'nowego komputera' (Gen.). Dies ist ein typischer Transferfehler, da deutsche Lerner die Kasusrektion aus dem Deutschen übertragen. 'Potrzebować' gehört zu den Genitivverben."},
            {"id": "gp_err12", "question": "Będę _____ jutro. (Futur von 'czytać' – imperfektiv!)", "translation": "(Ich werde morgen lesen.)", "options": ["czytać", "czytał", "przeczytam", "czytam"], "correct": "czytać", "explanation": "Häufiger Fehler: Verwechslung der Futurformen. Imperfektive Verben bilden das Futur mit 'będę' + Infinitiv: 'będę czytać' (ich werde lesen). Perfektive Verben bilden das Futur ohne 'będę': 'przeczytam' (ich werde fertig lesen). Im Deutschen gibt es nur ein Futur mit 'werden'. Die polnische Aspekt-Futur-Unterscheidung ist für Deutsche besonders verwirrend."},
            {"id": "gp_err13", "question": "Rozmawiałem z _____ przyjacielem. (mit meinem besten Freund)", "translation": "(Ich sprach mit meinem besten Freund.)", "options": ["moim najlepszym", "mój najlepszy", "mojego najlepszego", "moim najlepszy"], "correct": "moim najlepszym", "explanation": "Häufiger Fehler: Nicht alle Attribute im selben Kasus. Nach 'z' (mit) steht ALLES im Instrumental: 'z moim najlepszym przyjacielem'. Possessiv ('mój' → 'moim'), Superlativ ('najlepszy' → 'najlepszym'), Substantiv ('przyjaciel' → 'przyjacielem') – alle drei im Instrumental! Im Deutschen ändern sich die Adjektivendungen auch, aber weniger systematisch."},
            {"id": "gp_err14", "question": "Nie znam _____. (Negation + Person → welcher Kasus?)", "translation": "(Ich kenne diesen Mann nicht.)", "options": ["tego mężczyzny", "ten mężczyzna", "tego mężczyznę", "tym mężczyzną"], "correct": "tego mężczyzny", "explanation": "Doppelt schwierig: 1) Negation verlangt Genitiv statt Akkusativ. 2) 'Mężczyzna' (Mann) ist ein maskulin-belebtes Substantiv mit femininer Deklination! 'Ten mężczyzna' → 'tego mężczyzny' (Genitiv). Deutsche Lerner machen hier zwei Fehler gleichzeitig: den falschen Kasus (Akk. statt Gen.) und die falsche Deklinationsklasse. 'Mężczyzna' dekliniert wie ein Femininum!"},
            {"id": "gp_err15", "question": "Powinienem _____ to wcześniej. (hätte machen sollen – Vergangenheit!)", "translation": "(Ich hätte das früher machen sollen.)", "options": ["był zrobić", "zrobić", "robić", "zrobiłem"], "correct": "był zrobić", "explanation": "Häufiger Fehler: 'powinienem zrobić' (allgemein 'ich sollte') statt 'powinienem był zrobić' (ich hätte sollen). Die Vergangenheitsform des Modalverbs wird mit zusätzlichem 'był/była/było' gebildet. Im Deutschen: 'hätte machen sollen'. Im Polnischen: 'powinienem był zrobić'. Das kleine Wort 'był' macht den Unterschied zwischen Gegenwart und Vergangenheit aus."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")

# Validate format
issues = []
for c in data:
    for item in c['items']:
        if '_____' not in item.get('question',''):
            issues.append(f"{item['id']}: missing _____ in question")
        if len(item.get('options',[])) != 4:
            issues.append(f"{item['id']}: {len(item.get('options',[]))} options (need 4)")
        if item.get('correct','') not in item.get('options',[]):
            issues.append(f"{item['id']}: correct not in options")
        if len(item.get('explanation','')) < 200:
            issues.append(f"{item['id']}: explanation too short ({len(item.get('explanation',''))} chars)")
if issues:
    print(f"FORMAT ISSUES ({len(issues)}):")
    for i in issues:
        print(f"  {i}")
else:
    print("All format checks passed!")
