#!/usr/bin/env python3
"""Batch 10: Complex Structures (categories 53-57) - passive voice, reported speech, conditionals, impersonal, verbal nouns."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "passive_voice",
        "name": "Strona bierna (Passiv)",
        "description": "Tworzenie strony biernej w polskim – z użyciem form zwrotnych i bezosobowych",
        "icon": "arrow.uturn.left",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_pass1", "question": "Książka _____ napisana przez autora.", "translation": "(Das Buch wurde vom Autor geschrieben.)", "options": ["została", "zostaje", "będzie", "jest"], "correct": "została", "explanation": "Im Polnischen wird das Passiv mit 'zostać' + Partizip gebildet – ähnlich dem deutschen Vorgangspassiv mit 'werden'. 'Została napisana' = 'wurde geschrieben'. Beachten Sie: Das Partizip muss mit dem Subjekt übereinstimmen! 'Książka' ist feminin, daher 'została' (fem.) und 'napisana' (fem.). Bei maskulinem Subjekt wäre es 'został napisany'."},
            {"id": "gp_pass2", "question": "Dom _____ budowany od dwóch lat.", "translation": "(Das Haus wird seit zwei Jahren gebaut.)", "options": ["jest", "został", "będzie", "był"], "correct": "jest", "explanation": "Das Zustandspassiv im Polnischen verwendet 'być' (sein) + Partizip, ähnlich wie im Deutschen 'Das Haus ist gebaut'. 'Jest budowany' = andauernder Prozess (wird gebaut). Der Unterschied zu 'zostać': 'być' betont den Zustand/Prozess, 'zostać' das abgeschlossene Ergebnis. 'Dom jest budowany' = er wird gerade gebaut (Prozess läuft)."},
            {"id": "gp_pass3", "question": "Tu _____ się po polsku.", "translation": "(Hier spricht man Polnisch.)", "options": ["mówi", "mówią", "mówię", "mówisz"], "correct": "mówi", "explanation": "Die häufigste Passiv-Alternative im Polnischen! Statt echtem Passiv verwendet man 'się' + Verb in der 3. Person Singular. 'Mówi się' = 'man spricht' (wörtlich: 'es spricht sich'). Im Deutschen verwenden Sie 'man + Verb', im Polnischen 'Verb + się'. Das ist viel natürlicher als das echte Passiv und wird im Alltag bevorzugt!"},
            {"id": "gp_pass4", "question": "Wczoraj _____ wszystko naprawione.", "translation": "(Gestern wurde alles repariert.)", "options": ["zostało", "jest", "było", "będzie"], "correct": "zostało", "explanation": "'Zostało naprawione' – Passiv mit 'zostać' im Neutrum! 'Wszystko' (alles) ist Neutrum, daher 'zostało' (nicht 'został' oder 'została'). Im Deutschen bleibt 'wurde' unverändert, aber im Polnischen muss 'zostać' zum grammatischen Geschlecht passen. Das Partizip muss ebenfalls kongruent sein: 'naprawione' (Neutrum)."},
            {"id": "gp_pass5", "question": "Obiad jest _____ przez mamę.", "translation": "(Das Mittagessen wird von Mama gekocht.)", "options": ["gotowany", "gotowane", "gotowana", "gotowani"], "correct": "gotowany", "explanation": "Im Passiv muss das Partizip zum Subjekt passen: 'obiad' ist maskulin → 'gotowany'. Den Handelnden drückt man mit 'przez' + Akkusativ aus (wie 'von' + Dativ im Deutschen). 'Przez mamę' = 'von Mama'. Vergleichen Sie: 'zupa jest gotowana' (fem.), 'jajko jest gotowane' (neutr.), 'owoce są gotowane' (Plural)."},
            {"id": "gp_pass6", "question": "W Polsce _____ dużo kawy.", "translation": "(In Polen wird viel Kaffee getrunken.)", "options": ["pije się", "pijemy", "piją", "pijesz"], "correct": "pije się", "explanation": "Wieder die 'się'-Konstruktion – die natürlichste Art, unpersönliche Aussagen zu machen! 'Pije się' = 'man trinkt' / 'es wird getrunken'. Im Deutschen brauchen Sie das Passiv ('wird getrunken'), im Polnischen reicht 'się' + Verb. Diese Konstruktion ist der Schlüssel zum natürlichen Polnisch! Sie ist einfacher als das echte Passiv."},
            {"id": "gp_pass7", "question": "_____ wszystko, co było potrzebne.", "translation": "(Man hat alles gemacht, was nötig war.)", "options": ["Zrobiono", "Zrobili", "Zrobiło się", "Robiono"], "correct": "Zrobiono", "explanation": "Eine einzigartige polnische Form! '-no/-to' ist eine unpersönliche Vergangenheitsform, die es im Deutschen nicht gibt. 'Zrobiono' = 'man hat gemacht' – ohne Subjekt, ohne Passivhilfsverb. Es funktioniert nur in der Vergangenheit. Weitere Beispiele: 'Powiedziano' (man hat gesagt), 'Zbudowano' (man hat gebaut). Sehr häufig in Nachrichten und offiziellem Stil!"},
            {"id": "gp_pass8", "question": "Wszystkie bilety _____ sprzedane.", "translation": "(Alle Tickets wurden verkauft.)", "options": ["zostały", "zostali", "została", "został"], "correct": "zostały", "explanation": "'Bilety' ist Maskulinum unbelebt im Plural – und im Polnischen gibt es eine wichtige Unterscheidung: belebter vs. unbelebter Plural! Für unbelebte maskuline Nomen im Plural (wie 'bilety') verwendet man 'zostały' (nicht 'zostali'!). 'Zostali' wäre nur für männlich-persönlichen Plural. Diesen Unterschied gibt es im Deutschen nicht!"},
            {"id": "gp_pass9", "question": "Ta piosenka jest często _____ w radiu.", "translation": "(Dieses Lied wird oft im Radio gespielt.)", "options": ["grana", "grany", "grane", "grani"], "correct": "grana", "explanation": "Das Partizip muss zum Subjekt passen: 'piosenka' ist feminin → 'grana' (gespielt, fem.). Im Deutschen bleibt 'gespielt' unverändert, im Polnischen ändert sich die Endung: 'grany' (mask.), 'grana' (fem.), 'grane' (neutr./Pl. unbelebt), 'grani' (mask.-pers. Pl.). Das Zustandspassiv mit 'być' drückt eine regelmäßige Handlung aus."},
            {"id": "gp_pass10", "question": "Czy to _____ się zrobić?", "translation": "(Kann man das machen? / Ist das machbar?)", "options": ["da", "może", "wolno", "trzeba"], "correct": "da", "explanation": "'Da się' ist eine der nützlichsten polnischen Redewendungen! Es bedeutet 'es lässt sich / man kann / es ist möglich'. 'Czy da się to zrobić?' = 'Lässt sich das machen?' Die Verneinung ist 'nie da się' = 'es ist unmöglich'. Im Deutschen brauchen Sie das reflexive 'sich lassen' oder 'man kann', im Polnischen reichen zwei Wörter: 'da się'."},
            {"id": "gp_pass11", "question": "Tutaj nie _____ palić.", "translation": "(Hier darf man nicht rauchen.)", "options": ["wolno", "można", "da się", "trzeba"], "correct": "wolno", "explanation": "'Nie wolno' = 'man darf nicht' – ein unpersönliches Verbot. 'Wolno' allein bedeutet 'es ist erlaubt', mit 'nie' wird es zum Verbot. Unterschied zu 'nie można': 'nie wolno' ist strenger (Verbot!), 'nie można' kann auch physische Unmöglichkeit bedeuten. Am Flughafen sehen Sie: 'Nie wolno palić' – ein klares Verbot, nicht nur eine Empfehlung!"},
            {"id": "gp_pass12", "question": "List _____ pisany przez godzinę.", "translation": "(Der Brief wurde eine Stunde lang geschrieben.)", "options": ["był", "został", "jest", "będzie"], "correct": "był", "explanation": "'Był pisany' betont den Prozess (imperfektives Passiv mit 'być'), während 'został napisany' das Ergebnis betont (perfektives Passiv mit 'zostać'). 'Był pisany przez godzinę' = der Schreibprozess dauerte eine Stunde. Das ist wie der Unterschied zwischen 'Es wurde geschrieben' (Prozess) und 'Es wurde geschrieben' (fertig). Im Polnischen ist dieser Unterschied explizit!"},
            {"id": "gp_pass13", "question": "_____ nowy most na Wiśle.", "translation": "(Man hat eine neue Brücke über die Weichsel gebaut.)", "options": ["Wybudowano", "Wybudował", "Budowano", "Buduje się"], "correct": "Wybudowano", "explanation": "Wieder die '-no/-to'-Form! 'Wybudowano' = 'man hat (fertig) gebaut'. Beachten Sie den perfektiven Aspekt: 'wybudować' (fertig bauen) vs. 'budować' (bauen, Prozess). Die '-no/-to'-Form wird in Nachrichten, offiziellen Texten und Schildern bevorzugt, weil sie kurz und sachlich ist. Im Deutschen braucht man dafür das Passiv: 'wurde gebaut'."},
            {"id": "gp_pass14", "question": "Drzwi _____ otwarte.", "translation": "(Die Tür wurde geöffnet / Die Tür ist offen.)", "options": ["zostały", "został", "została", "zostało"], "correct": "zostały", "explanation": "Überraschung! 'Drzwi' (Tür) ist im Polnischen immer Plural (wie 'scissors' im Englischen)! Daher 'zostały' (Plural-Form). Das gibt es im Deutschen nicht – 'die Tür' ist Singular. Andere polnische Wörter, die nur im Plural existieren: 'spodnie' (Hose), 'nożyczki' (Schere), 'okulary' (Brille). Das beeinflusst natürlich auch die Passivform!"},
            {"id": "gp_pass15", "question": "_____ to zrobić inaczej.", "translation": "(Es sollte anders gemacht werden. / Man muss das anders machen.)", "options": ["Trzeba", "Wolno", "Można", "Da się"], "correct": "Trzeba", "explanation": "'Trzeba' = 'man muss / es ist nötig' – eine der wichtigsten unpersönlichen Konstruktionen im Polnischen. Es ersetzt oft das deutsche Passiv mit 'müssen': 'Das muss gemacht werden' → 'Trzeba to zrobić'. Kein Subjekt, kein Hilfsverb – nur 'trzeba' + Infinitiv. Ähnliche Wörter: 'warto' (es lohnt sich), 'wypada' (es gehört sich), 'należy' (man sollte)."}
        ]
    },
    {
        "key": "reported_speech",
        "name": "Mowa zależna (Indirekte Rede)",
        "description": "Przekazywanie wypowiedzi w mowie zależnej – bez Konjunktiv jak w niemieckim",
        "icon": "quote.bubble",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_rep1", "question": "Powiedział, _____ jest chory.", "translation": "(Er sagte, dass er krank sei.)", "options": ["że", "czy", "żeby", "bo"], "correct": "że", "explanation": "Im Polnischen leitet 'że' (dass) indirekte Aussagesätze ein – genau wie 'dass' im Deutschen. Der große Unterschied: Im Polnischen gibt es keinen Konjunktiv! 'Er sagte, dass er krank sei' (Konjunktiv I) wird einfach zu 'Powiedział, że jest chory' (Indikativ). Das macht indirekte Rede im Polnischen viel einfacher als im Deutschen!"},
            {"id": "gp_rep2", "question": "Zapytała, _____ lubię kawę.", "translation": "(Sie fragte, ob ich Kaffee mag.)", "options": ["czy", "że", "bo", "jak"], "correct": "czy", "explanation": "'Czy' leitet indirekte Ja/Nein-Fragen ein, genau wie 'ob' im Deutschen. 'She asked whether I like coffee' = 'Zapytała, czy lubię kawę'. Merken Sie sich: 'że' = 'dass' (für Aussagen), 'czy' = 'ob' (für Ja/Nein-Fragen). Bei W-Fragen verwendet man das Fragewort direkt: 'Zapytała, gdzie mieszkam' (Sie fragte, wo ich wohne)."},
            {"id": "gp_rep3", "question": "Powiedzieli, że _____ jutro.", "translation": "(Sie sagten, dass sie morgen kommen werden.)", "options": ["przyjdą", "przyszli", "przychodzą", "przychodzili"], "correct": "przyjdą", "explanation": "Im Polnischen gibt es keine Zeitverschiebung (Consecutio Temporum) in der indirekten Rede! Wenn jemand sagt 'Wir werden morgen kommen', bleibt es in der indirekten Rede Zukunft: 'przyjdą' (sie werden kommen). Im Deutschen kann man zwischen 'sie kommen' und 'sie kämen' schwanken. Im Polnischen: einfach die gleiche Zeit verwenden!"},
            {"id": "gp_rep4", "question": "Mama powiedziała, _____ posprzątał pokój.", "translation": "(Mama sagte, ich solle mein Zimmer aufräumen.)", "options": ["żebym", "że", "czy", "bo"], "correct": "żebym", "explanation": "'Żebym' ist eine Kombination aus 'żeby' (damit/dass) + personalem Marker '-m' (ich). Es drückt einen indirekten Befehl oder eine Bitte aus: 'żebym' = dass ich soll. Die Formen: żebym (ich), żebyś (du), żeby (er/sie), żebyśmy (wir), żebyście (ihr), żeby (sie). Im Deutschen braucht man den Konjunktiv I ('solle'), im Polnischen diese elegante Verschmelzung!"},
            {"id": "gp_rep5", "question": "Nauczyciel kazał nam _____ wypracowanie.", "translation": "(Der Lehrer hat uns aufgetragen, einen Aufsatz zu schreiben.)", "options": ["napisać", "napisał", "pisał", "napisali"], "correct": "napisać", "explanation": "'Kazać' (befehlen/auftragen) + Dativ + Infinitiv – eine wichtige Konstruktion für indirekte Befehle. 'Kazał nam napisać' = 'er befahl uns zu schreiben'. Im Deutschen: 'aufgetragen zu schreiben'. 'Kazać' ist stärker als 'prosić' (bitten). Beachten Sie: 'nam' ist Dativ von 'my' (wir) – wie 'uns' im Deutschen."},
            {"id": "gp_rep6", "question": "Twierdził, że nie _____ wypadku.", "translation": "(Er behauptete, dass er den Unfall nicht gesehen habe.)", "options": ["widział", "widzi", "zobaczy", "ogląda"], "correct": "widział", "explanation": "'Twierdził, że nie widział' – wieder: keine Konjunktivform im Polnischen! Im Deutschen: 'er habe nicht gesehen' (Konjunktiv I) oder 'er hätte nicht gesehen' (K. II). Im Polnischen bleibt einfach die Vergangenheitsform: 'widział' (er sah/hatte gesehen). Das Verb 'twierdzić' (behaupten) signalisiert bereits Distanz zur Aussage, ein Konjunktiv ist unnötig!"},
            {"id": "gp_rep7", "question": "Zapytał, gdzie _____.", "translation": "(Er fragte, wo ich wohne.)", "options": ["mieszkam", "mieszkasz", "mieszka", "mieszkają"], "correct": "mieszkam", "explanation": "Bei indirekten W-Fragen bleibt das Fragewort an der gleichen Position: 'Zapytał, gdzie mieszkam' = 'Er fragte, wo ich wohne'. Im Deutschen rutscht das Verb ans Ende des Nebensatzes, im Polnischen bleibt die Wortstellung normal (SVO). 'Mieszkam' (ich wohne) – 1. Person, weil die Frage an mich gerichtet war. Die Perspektive passt sich an den Sprecher an."},
            {"id": "gp_rep8", "question": "Obiecała, że _____ wieczorem.", "translation": "(Sie versprach, dass sie am Abend anrufen werde.)", "options": ["zadzwoni", "dzwoni", "dzwoniła", "zadzwoniła"], "correct": "zadzwoni", "explanation": "'Zadzwoni' – perfektive Zukunft (sie wird anrufen und fertig sein). 'Obiecać' (versprechen) + 'że' + Zukunft ist die natürliche Konstruktion für Versprechen. Im Polnischen drückt der perfektive Aspekt die Zukunft aus, OHNE ein Hilfsverb wie 'werden'! 'Zadzwoni' = sie wird anrufen (einmalig, abgeschlossen). 'Będzie dzwonić' wäre: sie wird (wiederholt) anrufen."},
            {"id": "gp_rep9", "question": "Prosił, _____ mu pomogli.", "translation": "(Er bat darum, dass wir ihm helfen.)", "options": ["żebyśmy", "żebym", "żebyś", "żeby"], "correct": "żebyśmy", "explanation": "'Żebyśmy' = 'żeby' + '-śmy' (wir). Die Personalendung verschmilzt mit der Konjunktion! Alle Formen: żebym (ich), żebyś (du), żeby (er/sie/es), żebyśmy (wir), żebyście (ihr), żeby (sie/Sie). 'Prosić' (bitten) verlangt 'żeby'-Konstruktion für die indirekte Bitte. Im Deutschen: 'Er bat, dass wir...' – im Polnischen ist die Person direkt in der Konjunktion kodiert!"},
            {"id": "gp_rep10", "question": "Odpowiedział, że nie _____.", "translation": "(Er antwortete, dass er es nicht wisse.)", "options": ["wie", "wiedział", "będzie wiedział", "wiedzieć"], "correct": "wie", "explanation": "Gegenwart in indirekter Rede bleibt Gegenwart: 'nie wie' (er weiß nicht). Im Deutschen: 'dass er nicht wisse' (Konjunktiv I) – im Polnischen einfach 'nie wie' (Indikativ). 'Wiedzieć' (wissen) konjugiert unregelmäßig: wiem, wiesz, wie, wiemy, wiecie, wiedzą. Besonders die 3. Person 'wie' ist kurz und sieht aus wie das deutsche 'wie' – aber bedeutet 'er/sie weiß'!"},
            {"id": "gp_rep11", "question": "Powiedział _____, że jest szczęśliwy.", "translation": "(Er hat mir gesagt, dass er glücklich ist.)", "options": ["mi", "mnie", "ja", "mną"], "correct": "mi", "explanation": "'Powiedzieć komuś' – 'jemandem sagen' verlangt den Dativ, genau wie im Deutschen! 'Mi' ist die kurze Dativform von 'ja' (ich). Die Formen: mi/mnie (mir), ci/tobie (dir), mu/jemu (ihm), jej (ihr), nam (uns), wam (euch), im (ihnen). 'Mi' statt 'mnie' – die kurze Form steht unbetont im Satz, die lange Form 'mnie' wird betont verwendet."},
            {"id": "gp_rep12", "question": "_____ jutro będzie padać.", "translation": "(Angeblich soll es morgen regnen.)", "options": ["Podobno", "Pewnie", "Chyba", "Może"], "correct": "Podobno", "explanation": "'Podobno' ist ein einzigartiges polnisches Modalwort, das 'angeblich/wie man hört' bedeutet. Es signalisiert Hörensagen – Information aus zweiter Hand – OHNE indirekte Rede zu bauen! Im Deutschen brauchen Sie 'Angeblich soll es...' oder den Konjunktiv, im Polnischen reicht ein Wort am Satzanfang. Ähnlich: 'jakoby' (angeblich, skeptischer), 'rzekomo' (vorgeblich)."},
            {"id": "gp_rep13", "question": "Ostrzegł nas, _____ byli ostrożni.", "translation": "(Er warnte uns, vorsichtig zu sein.)", "options": ["żebyśmy", "że", "bo", "czy"], "correct": "żebyśmy", "explanation": "'Ostrzec' (warnen) + 'żebyśmy' – Warnungen und Ratschläge verwenden die 'żeby'-Konstruktion. 'Żebyśmy byli ostrożni' = 'dass wir vorsichtig sein sollen'. Das Personalsuffix '-śmy' (wir) ist in 'żebyśmy' integriert. Das Verb 'byli' steht in der l-Form (Vergangenheitspartizip), die hier aber NICHT Vergangenheit bedeutet, sondern den irrealen/gewünschten Modus ausdrückt!"},
            {"id": "gp_rep14", "question": "Według _____ to był dobry pomysł.", "translation": "(Seiner Meinung nach war das eine gute Idee.)", "options": ["niego", "jego", "on", "nim"], "correct": "niego", "explanation": "'Według' (laut/gemäß) + Genitiv – eine elegante Art, Meinungen zu zitieren, ohne indirekte Rede zu verwenden. 'Według niego' = 'laut ihm / seiner Meinung nach'. Warum 'niego' statt 'jego'? Nach Präpositionen bekommen Pronomen der 3. Person ein 'n-' vorne: jego → niego, jemu → niemu, nim statt im. Diese n-Regel gilt für alle Präpositionen!"},
            {"id": "gp_rep15", "question": "Stwierdziła, że to _____.", "translation": "(Sie stellte fest, dass das unmöglich sei.)", "options": ["niemożliwe", "niemożliwy", "niemożliwa", "niemożliwi"], "correct": "niemożliwe", "explanation": "'To jest niemożliwe' – 'to' (das) ist Neutrum, daher 'niemożliwe' (neutr. Form). Im Deutschen: 'unmöglich' bleibt unverändert. Im Polnischen muss das Prädikatsadjektiv mit dem Subjekt übereinstimmen: 'on jest niemożliwy' (mask.), 'ona jest niemożliwa' (fem.), 'to jest niemożliwe' (neutr.). Der Stamm 'nie-' + 'możliwy' = unmöglich, genau wie 'un-' + 'möglich'."}
        ]
    },
    {
        "key": "conditional_sentences",
        "name": "Zdania warunkowe (Konditionalsätze)",
        "description": "Trzy typy zdań warunkowych w polskim – realne, potencjalne i nierealne",
        "icon": "arrow.triangle.branch",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_conds1", "question": "Jeśli będzie ładnie, _____ na spacer.", "translation": "(Wenn es schön wird, gehen wir spazieren.)", "options": ["pójdziemy", "poszlibyśmy", "chodzimy", "chodziliśmy"], "correct": "pójdziemy", "explanation": "Realer Konditionalsatz (Typ I): 'Jeśli' + Zukunft/Präsens, Hauptsatz im Futur. 'Pójdziemy' ist perfektive Zukunft (wir werden gehen). Im Deutschen: 'Wenn + Präsens, Präsens' – im Polnischen kann man auch Futur verwenden, was logischer ist! 'Jeśli będzie ładnie' = 'wenn es schön sein wird'. Beide Satzteile in der Zukunft – im Deutschen wäre das ein Fehler!"},
            {"id": "gp_conds2", "question": "_____ miał czas, pojechałbym do Polski.", "translation": "(Wenn ich Zeit hätte, würde ich nach Polen fahren.)", "options": ["Gdybym", "Jeśli", "Kiedy", "Gdy"], "correct": "Gdybym", "explanation": "Irrealer Konditionalsatz (Typ II): 'Gdybym' = 'wenn ich' (irreal). Das ist 'gdyby' + '-m' (ich). Im Deutschen: 'Wenn ich hätte, würde ich...' mit Konjunktiv II. Im Polnischen: 'gdyby-' + Personalendung + Verb in l-Form. Die Formen: gdybym (ich), gdybyś (du), gdyby (er/sie), gdybyśmy (wir), gdybyście (ihr), gdyby (sie). Die Personalendung ist direkt in der Konjunktion!"},
            {"id": "gp_conds3", "question": "Gdybym był bogaty, _____ dom.", "translation": "(Wenn ich reich wäre, würde ich ein Haus kaufen.)", "options": ["kupiłbym", "kupię", "kupuję", "kupiłem"], "correct": "kupiłbym", "explanation": "Der polnische Konditionalis: Verb in l-Form + '-bym' (ich). 'Kupiłbym' = 'ich würde kaufen'. Im Deutschen braucht man 'würde + Infinitiv', im Polnischen verschmilzt alles in einem Wort! Die Endungen: -bym (ich), -byś (du), -by (er/sie), -byśmy (wir), -byście (ihr), -by (sie). Das ist einfacher als der deutsche Konjunktiv II mit seinen vielen Formen!"},
            {"id": "gp_conds4", "question": "Gdybyś wcześniej _____, spotkałbyś ją.", "translation": "(Wenn du früher gekommen wärst, hättest du sie getroffen.)", "options": ["przyszedł", "przychodzisz", "przyjdziesz", "przychodzić"], "correct": "przyszedł", "explanation": "Irrealer Konditionalsatz der Vergangenheit (Typ III): Im Polnischen verwendet man dieselbe Form wie für Typ II! 'Gdybyś przyszedł' kann heißen: 'wenn du kämest' ODER 'wenn du gekommen wärst' – der Kontext entscheidet. Im Deutschen gibt es klar Konjunktiv II (Typ II) vs. Konjunktiv Plusquamperfekt (Typ III). Im Polnischen: eine Form für beide!"},
            {"id": "gp_conds5", "question": "Jeśli _____, mogę ci pomóc.", "translation": "(Wenn du willst, kann ich dir helfen.)", "options": ["chcesz", "chciałbyś", "chciałeś", "będziesz chciał"], "correct": "chcesz", "explanation": "Realer Konditionalsatz mit Präsens: 'Jeśli chcesz' = 'Wenn du willst'. Einfach und identisch mit dem Deutschen! 'Jeśli' wird für reale Bedingungen verwendet (es ist möglich, dass du willst), 'gdyby' für irreale (du willst wahrscheinlich nicht). Merken Sie sich: 'jeśli/jeżeli' = reale Bedingung, 'gdyby' = irreale Bedingung. Im Deutschen deckt 'wenn' beides ab!"},
            {"id": "gp_conds6", "question": "Gdyby nie _____, wyszlibyśmy.", "translation": "(Wenn es nicht regnen würde, würden wir rausgehen.)", "options": ["deszcz", "padało", "pada", "padać"], "correct": "deszcz", "explanation": "'Gdyby nie deszcz' = 'wenn nicht der Regen' / 'wenn es nicht regnen würde'. Von den Optionen ist 'deszcz' korrekt: 'Gdyby nie deszcz' ist eine verkürzte irreale Bedingung (wörtlich: 'wenn nicht Regen'). Alternativ: 'Gdyby nie padało, wyszlibyśmy' (wenn es nicht regnen würde). Die Kurzform mit Substantiv ist im Polnischen sehr natürlich und elegant!"},
            {"id": "gp_conds7", "question": "_____ że zdasz egzamin, dostaniesz nagrodę.", "translation": "(Unter der Bedingung, dass du die Prüfung bestehst, bekommst du eine Belohnung.)", "options": ["Pod warunkiem,", "Jeśli", "Gdyby", "Kiedy"], "correct": "Pod warunkiem,", "explanation": "'Pod warunkiem, że' = 'unter der Bedingung, dass' – eine formelle Konditionalkonstruktion. 'Pod' + Instrumental ('warunkiem') + 'że' + Satz. Im Vertragssprache und bei formellen Absprachen häufig. Weniger formelle Alternativen: 'jeśli' (wenn), 'o ile' (sofern/insofern), 'w razie gdyby' (für den Fall, dass). Die Wahl des Konnektors zeigt den Formalitätsgrad!"},
            {"id": "gp_conds8", "question": "_____ że zmienisz zdanie.", "translation": "(Es sei denn, du änderst deine Meinung.)", "options": ["Chyba", "Jeśli", "Gdyby", "Może"], "correct": "Chyba", "explanation": "'Chyba że' = 'es sei denn' / 'unless' – eine ausschließende Bedingung. 'Chyba' allein bedeutet 'wahrscheinlich/vielleicht', aber 'chyba że' ist eine feste Wendung für Ausnahmen. 'Przyjdę, chyba że zmienisz zdanie' = 'Ich komme, es sei denn, du änderst deine Meinung'. Diese Konstruktion ist im Alltag sehr häufig und klingt natürlicher als 'es sei denn' im Deutschen!"},
            {"id": "gp_conds9", "question": "W razie _____ padało, weź parasol.", "translation": "(Falls es regnen sollte, nimm einen Regenschirm.)", "options": ["gdyby", "jeśli", "że", "kiedy"], "correct": "gdyby", "explanation": "'W razie gdyby' = 'für den Fall, dass' / 'falls'. Es kombiniert 'w razie' (im Falle von) mit dem irrealen 'gdyby'. Diese Konstruktion drückt eine Vorsichtsmaßnahme aus – es ist unwahrscheinlich, aber möglich. 'W razie gdyby padało' = 'für den Fall, dass es regnen sollte'. Das 'gdyby' macht es hypothetischer als einfaches 'jeśli' (wenn)."},
            {"id": "gp_conds10", "question": "Gdybym to _____, powiedziałbym ci.", "translation": "(Wenn ich das gewusst hätte, hätte ich es dir gesagt.)", "options": ["wiedział", "wiem", "będę wiedział", "wiedzieć"], "correct": "wiedział", "explanation": "Irrealer Vergangenheitskonditionalsatz: 'Gdybym wiedział' = 'wenn ich gewusst hätte'. Im Polnischen gibt es KEINE separate Form für die irreale Vergangenheit (wie den deutschen Konjunktiv Plusquamperfekt 'hätte gewusst'). Man verwendet dieselbe l-Form wie für die irreale Gegenwart. Der Kontext (hier: es ist zu spät) zeigt, dass es um die Vergangenheit geht. Das vereinfacht das System enorm!"},
            {"id": "gp_conds11", "question": "Jak _____ grzeczny, dostaniesz lody.", "translation": "(Wenn du brav bist, bekommst du ein Eis.)", "options": ["będziesz", "byłbyś", "jesteś", "byłeś"], "correct": "będziesz", "explanation": "'Jak' = umgangssprachliches 'wenn' (statt 'jeśli'). In der Alltagssprache und besonders mit Kindern verwendet man 'jak' statt des formelleren 'jeśli'. 'Jak będziesz grzeczny' = 'wenn du brav sein wirst'. Beachten Sie: Im Polnischen steht hier logischerweise Futur ('wirst sein'), während das Deutsche Präsens verwendet ('wenn du brav BIST'). Die polnische Logik ist hier eigentlich klarer!"},
            {"id": "gp_conds12", "question": "Nawet _____ prosił, nie pomogłabym mu.", "translation": "(Selbst wenn er bitten würde, würde ich ihm nicht helfen.)", "options": ["gdyby", "jeśli", "kiedy", "jak"], "correct": "gdyby", "explanation": "'Nawet gdyby' = 'selbst wenn' – eine verstärkte irreale Bedingung. 'Nawet' (sogar/selbst) + 'gdyby' (wenn, irreal). 'Nie pomogłabym' – beachten Sie das '-a-' vor '-bym': das zeigt, dass die Sprecherin weiblich ist! 'Pomogłbym' = ich (Mann) würde helfen, 'pomogłabym' = ich (Frau) würde helfen. Im Deutschen gibt es diese Geschlechtsunterscheidung in der Verbform nicht!"},
            {"id": "gp_conds13", "question": "Gdyby tak _____ cofnąć czas!", "translation": "(Wenn man doch nur die Zeit zurückdrehen könnte!)", "options": ["można było", "można", "trzeba", "wolno"], "correct": "można było", "explanation": "'Gdyby tak można było' = 'wenn man doch nur könnte' – ein irrealer Wunsch. 'Gdyby tak' drückt Sehnsucht aus (wie 'wenn doch nur'). 'Można było' = man hätte können (unpersönlich + Vergangenheit). Im Deutschen: 'Wenn man doch nur... könnte!' Diese Ausrufe des Bedauerns sind in beiden Sprachen emotional geladen. Das 'tak' verstärkt den Wunschcharakter."},
            {"id": "gp_conds14", "question": "O ile dobrze _____, spotkanie jest o trzeciej.", "translation": "(Soweit ich mich richtig erinnere, ist das Meeting um drei.)", "options": ["pamiętam", "pamiętałem", "zapamiętam", "pamiętałbym"], "correct": "pamiętam", "explanation": "'O ile' = 'sofern/soweit' – ein einschränkender Konditionalsatz. 'O ile dobrze pamiętam' = 'soweit ich mich gut erinnere'. Dies ist eine häufige Floskel, die Unsicherheit ausdrückt. Andere 'o ile'-Wendungen: 'o ile wiem' (soweit ich weiß), 'o ile mi wiadomo' (soweit mir bekannt ist). Diese Konstruktion macht Aussagen vorsichtiger und höflicher."},
            {"id": "gp_conds15", "question": "_____ tylko nie padało, będzie dobrze.", "translation": "(Wenn es nur nicht regnet, wird alles gut.)", "options": ["Byleby", "Gdyby", "Jeśli", "Chyba że"], "correct": "Byleby", "explanation": "'Byleby' = 'wenn nur / solange nur' – drückt eine minimale Bedingung aus. 'Byleby nie padało' = 'wenn es nur nicht regnet' – mehr brauche ich nicht. Im Deutschen: 'Wenn es nur nicht regnet'. 'Byleby' kommt von 'by' (Konditionalpartikel) + 'le' (nur) + 'by' (Verstärkung). Es drückt aus, dass eine einzige Bedingung erfüllt sein muss, damit alles in Ordnung ist."}
        ]
    },
    {
        "key": "impersonal_constructions",
        "name": "Konstrukcje bezosobowe (Unpersönliche Konstruktionen)",
        "description": "Zdania bezosobowe w polskim – bez 'es' jako podmiot pozorny",
        "icon": "person.slash",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_impers1", "question": "_____ się uczyć codziennie.", "translation": "(Man muss jeden Tag lernen.)", "options": ["Trzeba", "Można", "Wolno", "Warto"], "correct": "Trzeba", "explanation": "'Trzeba' = 'man muss / es ist nötig' – die häufigste unpersönliche Notwendigkeit im Polnischen. Kein Subjekt, kein 'es', kein 'man' – einfach 'trzeba' + Infinitiv. Im Deutschen: 'Man muss lernen' oder 'Es ist nötig zu lernen'. Im Polnischen ein einziges Wort! Merken Sie sich die Abstufung: 'trzeba' (man muss) > 'należy' (man sollte) > 'warto' (es lohnt sich) > 'można' (man kann)."},
            {"id": "gp_impers2", "question": "Czy _____ tu palić?", "translation": "(Darf man hier rauchen?)", "options": ["można", "trzeba", "wolno", "warto"], "correct": "można", "explanation": "'Można' = 'man kann / man darf' – unpersönliche Erlaubnis oder Möglichkeit. 'Czy można?' ist eine der nützlichsten polnischen Fragen: 'Darf man? / Ist es möglich?' Im Restaurant: 'Czy można prosić rachunek?' (Kann ich um die Rechnung bitten?). Der Unterschied zu 'wolno': 'można' = physisch/praktisch möglich, 'wolno' = erlaubt (juristisch/moralisch). Beide ohne Subjekt!"},
            {"id": "gp_impers3", "question": "Jest _____ zimno.", "translation": "(Mir ist kalt.)", "options": ["mi", "ja", "mnie", "mną"], "correct": "mi", "explanation": "'Jest mi zimno' = 'Mir ist kalt' – eine der direktesten Parallelen zwischen Polnisch und Deutsch! Beide Sprachen verwenden Dativ + unpersönliches Verb. 'Mi' = mir (kurze Dativform). Weitere Beispiele: 'Jest mi gorąco' (mir ist heiß), 'Jest mi wstyd' (mir ist peinlich), 'Jest mi smutno' (mir ist traurig). Diese Konstruktion für Empfindungen ist in beiden Sprachen identisch!"},
            {"id": "gp_impers4", "question": "_____ to zobaczyć.", "translation": "(Es lohnt sich, das zu sehen.)", "options": ["Warto", "Trzeba", "Można", "Wolno"], "correct": "Warto", "explanation": "'Warto' = 'es lohnt sich / es ist wert' – eine unpersönliche Empfehlung. 'Warto zobaczyć' = 'es lohnt sich zu sehen'. Ein Reiseführer voller 'warto': 'Warto odwiedzić Kraków' (es lohnt sich, Krakau zu besuchen). Im Deutschen braucht man das reflexive 'sich lohnen', im Polnischen genügt ein Wort. Negation: 'nie warto' = es lohnt sich nicht."},
            {"id": "gp_impers5", "question": "_____ mnie głowa.", "translation": "(Mir tut der Kopf weh. / Ich habe Kopfschmerzen.)", "options": ["Boli", "Bolą", "Bolę", "Bolisz"], "correct": "Boli", "explanation": "'Boli mnie głowa' – wörtlich: 'Es schmerzt mich der Kopf'. 'Mnie' = Akkusativ (nicht Dativ wie im Deutschen!). Im Deutschen: 'Mir tut der Kopf weh' (Dativ). Im Polnischen: 'Boli mnie' (Akkusativ). Bei Plural: 'Bolą mnie oczy' (die Augen tun mir weh) – 'bolą' in der 3. Person Plural, weil 'oczy' Plural ist. Der Körperteil ist das grammatische Subjekt!"},
            {"id": "gp_impers6", "question": "Chce _____ się pić.", "translation": "(Ich habe Durst. / Mich dürstet.)", "options": ["mi", "mnie", "ja", "mną"], "correct": "mi", "explanation": "'Chce mi się pić' = wörtlich: 'es will sich mir trinken' – eine typisch polnische unpersönliche Konstruktion für Bedürfnisse. 'Mi' = Dativ. Im Deutschen: 'Ich habe Durst' (persönlich) oder das veraltete 'Mich dürstet'. Weitere: 'Chce mi się jeść' (ich habe Hunger), 'Chce mi się spać' (ich bin müde/schläfrig). Diese 'chce mi się' + Infinitiv-Konstruktion ist im Alltag sehr häufig!"},
            {"id": "gp_impers7", "question": "Wydaje _____ się, że to prawda.", "translation": "(Es scheint mir, dass das wahr ist.)", "options": ["mi", "mnie", "ja", "mną"], "correct": "mi", "explanation": "'Wydaje mi się' = 'es scheint mir / ich glaube' – eine höfliche Art, eine Meinung zu äußern. 'Mi' = Dativ (wie 'mir' im Deutschen). Diese Konstruktion macht Aussagen vorsichtiger: statt 'To jest prawda' (Das ist wahr) → 'Wydaje mi się, że to prawda' (Es scheint mir, dass das wahr ist). Im Deutschen: 'Mir scheint, dass...' – fast identische Struktur und Funktion!"},
            {"id": "gp_impers8", "question": "_____ to zrobić inaczej.", "translation": "(Man sollte das anders machen.)", "options": ["Należy", "Trzeba", "Można", "Warto"], "correct": "Należy", "explanation": "'Należy' = 'man sollte / es gehört sich' – formellere Notwendigkeit als 'trzeba'. 'Należy to zrobić' = 'Dies sollte getan werden'. Abstufung: 'trzeba' (man muss, neutral), 'należy' (man sollte, formell, z.B. in Vorschriften), 'wypada' (es gehört sich, soziale Norm), 'warto' (es lohnt sich). 'Należy' begegnet Ihnen in offiziellen Texten, Gebrauchsanweisungen und akademischen Arbeiten."},
            {"id": "gp_impers9", "question": "Zrobiło _____ ciemno.", "translation": "(Es wurde dunkel.)", "options": ["się", "to", "ono", "mi"], "correct": "się", "explanation": "'Zrobiło się ciemno' = 'es wurde dunkel' – unpersönliche Zustandsveränderung mit 'się'. Das 'się' macht das Verb unpersönlich. Weitere Beispiele: 'Zrobiło się zimno' (es wurde kalt), 'Zrobiło się późno' (es wurde spät). Im Deutschen verwendet man das unpersönliche 'es' + 'werden', im Polnischen 'zrobić się' in der Neutrumform. Kein 'es'-Äquivalent nötig!"},
            {"id": "gp_impers10", "question": "_____ się tego naprawić.", "translation": "(Das lässt sich nicht reparieren.)", "options": ["Nie da", "Nie może", "Nie wolno", "Nie trzeba"], "correct": "Nie da", "explanation": "'Nie da się' = 'es lässt sich nicht / es ist unmöglich'. Die positive Form: 'Da się' = 'es lässt sich / es ist möglich'. 'Nie da się tego naprawić' – beachten Sie 'tego' (Genitiv) statt 'to' (Akkusativ): nach der Verneinung wechselt das Objekt in den Genitiv! Das ist eine wichtige polnische Regel: Verneinung → Akkusativ wird zu Genitiv. Im Deutschen bleibt der Kasus gleich."},
            {"id": "gp_impers11", "question": "Nudzi _____ się.", "translation": "(Mir ist langweilig.)", "options": ["mi", "mnie", "ja", "mną"], "correct": "mi", "explanation": "'Nudzi mi się' = 'mir ist langweilig' – wieder Dativ wie im Deutschen! 'Nudzić się' (sich langweilen) wird hier unpersönlich mit Dativ des Experiencers. Vergleichen Sie die persönliche Form: 'Nudzę się' (ich langweile mich) vs. unpersönlich: 'Nudzi mi się' (mir ist langweilig). Beide sind korrekt, aber die unpersönliche Form betont das Gefühl stärker als die Handlung."},
            {"id": "gp_impers12", "question": "_____ się trochę odpocząć.", "translation": "(Es wäre gut, sich etwas auszuruhen.)", "options": ["Przydałoby", "Trzeba", "Można", "Warto"], "correct": "Przydałoby", "explanation": "'Przydałoby się' = 'es wäre nützlich / es wäre gut' – unpersönlicher Konditionalis. Das '-by' macht es zum Konjunktiv: 'przydałoby się' (es wäre nützlich) vs. 'przyda się' (es wird nützlich sein). Im Deutschen: 'Es wäre gut' oder 'Es würde nicht schaden'. Diese sanfte Empfehlung ist im Polnischen sehr gebräuchlich für höfliche Vorschläge."},
            {"id": "gp_impers13", "question": "Śmierdzi tu _____.", "translation": "(Hier stinkt es nach etwas.)", "options": ["czymś", "coś", "czegoś", "czemuś"], "correct": "czymś", "explanation": "'Śmierdzi czymś' = 'es stinkt nach etwas' – der Instrumental 'czymś' drückt aus, wonach es riecht/stinkt. 'Czymś' = Instrumental von 'coś' (etwas). Sinneseindrücke verwenden oft den Instrumental: 'pachnie kwiatami' (es duftet nach Blumen), 'trąci pleśnią' (es riecht nach Schimmel). Im Deutschen: 'nach + Dativ', im Polnischen: einfach Instrumental ohne Präposition!"},
            {"id": "gp_impers14", "question": "Nie _____ tu parkować.", "translation": "(Hier darf man nicht parken.)", "options": ["wolno", "można", "da się", "trzeba"], "correct": "wolno", "explanation": "'Nie wolno' = 'es ist verboten / man darf nicht' – das stärkste unpersönliche Verbot. 'Wolno' kommt von 'Wille/Freiheit' und bedeutet allein 'es ist erlaubt'. Mit 'nie': striktes Verbot. Unterschied: 'Nie wolno tu parkować' (Verbot! = 'Parken verboten!') vs. 'Nie można tu parkować' (geht nicht, z.B. weil kein Platz). 'Nie wolno' sehen Sie auf Verbotsschildern in ganz Polen!"},
            {"id": "gp_impers15", "question": "_____ mi się, że go gdzieś widziałem.", "translation": "(Es kommt mir vor, dass ich ihn irgendwo gesehen habe.)", "options": ["Zdaje", "Wydaje", "Chce", "Nudzi"], "correct": "Zdaje", "explanation": "'Zdaje mi się' = 'es scheint mir / mir kommt es vor' – ähnlich wie 'wydaje mi się', aber etwas umgangssprachlicher und unsicherer. 'Zdaje mi się, że...' drückt eine vage Erinnerung oder Vermutung aus. Im Deutschen: 'Mir scheint...' oder 'Ich glaube...'. Beide Verben ('zdawać się' und 'wydawać się') sind unpersönlich mit Dativ – ein Muster, das Sie sich merken sollten!"}
        ]
    },
    {
        "key": "verbal_nouns_gerunds",
        "name": "Rzeczowniki odczasownikowe (Verbalsubstantive)",
        "description": "Tworzenie rzeczowników z czasowników – odpowiedniki niemieckiego '-ung' i Nominalisierung",
        "icon": "textformat.abc",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_vnom1", "question": "_____ to moje hobby.", "translation": "(Lesen ist mein Hobby.)", "options": ["Czytanie", "Czytać", "Czytam", "Przeczytanie"], "correct": "Czytanie", "explanation": "'Czytanie' = 'das Lesen' – ein Verbalsubstantiv, gebildet mit '-anie/-enie'. Im Deutschen gibt es zwei Möglichkeiten: den Infinitiv als Substantiv ('das Lesen') oder '-ung'-Formen ('die Lesung'). Im Polnischen: '-anie' für -ać-Verben (czytać → czytanie), '-enie' für andere (robić → robienie). Diese Formen funktionieren wie normale Substantive und können dekliniert werden!"},
            {"id": "gp_vnom2", "question": "_____ wypracowań jest trudne.", "translation": "(Aufsätze zu schreiben ist schwer.)", "options": ["Pisanie", "Pisać", "Napisanie", "Piszę"], "correct": "Pisanie", "explanation": "'Pisanie' + Genitiv des Objekts – wenn das Verbalsubstantiv ein Objekt hat, steht es im Genitiv! 'Pisanie wypracowań' = 'das Schreiben von Aufsätzen'. Im Deutschen: 'Schreiben von...' oder 'das Aufschreiben...'. Im Polnischen ist die Genitivkonstruktion Standard: das Objekt des Verbs wird zum Genitiv-Attribut des Substantivs. 'Wypracowań' = Genitiv Plural von 'wypracowanie'."},
            {"id": "gp_vnom3", "question": "_____ jest zabronione.", "translation": "(Rauchen ist verboten.)", "options": ["Palenie", "Palić", "Spalenie", "Palimy"], "correct": "Palenie", "explanation": "'Palenie jest zabronione' – identische Struktur wie im Deutschen: 'Rauchen ist verboten'. Beachten Sie: 'zabronione' (verboten) ist Neutrum, weil 'palenie' als Verbalsubstantiv immer Neutrum ist! Alle polnischen Verbalsubstantive auf '-anie/-enie/-cie' sind Neutrum. Das macht die Kongruenz einfach. Sie sehen 'Palenie zabronione' auf Schildern in ganz Polen – ohne 'jest'!"},
            {"id": "gp_vnom4", "question": "_____ sprawia mi przyjemność.", "translation": "(Kochen macht mir Freude.)", "options": ["Gotowanie", "Gotować", "Ugotowanie", "Gotujemy"], "correct": "Gotowanie", "explanation": "'Gotowanie sprawia mi przyjemność' – das Verbalsubstantiv als Subjekt, genau wie 'Kochen macht mir Freude'. 'Sprawić przyjemność' = 'Freude machen/bereiten'. 'Mi' = Dativ (mir). Im Polnischen klingt es mit dem Verbalsubstantiv natürlicher als mit dem Infinitiv. 'Gotować sprawia mi przyjemność' wäre unnatürlich – im Deutschen können Sie beide verwenden."},
            {"id": "gp_vnom5", "question": "_____ w Warszawie jest drogie.", "translation": "(Das Wohnen in Warschau ist teuer.)", "options": ["Mieszkanie", "Mieszkać", "Zamieszkanie", "Mieszkamy"], "correct": "Mieszkanie", "explanation": "Achtung, Doppelbedeutung! 'Mieszkanie' kann heißen: 1) 'das Wohnen' (Verbalsubstantiv) oder 2) 'die Wohnung' (Substantiv). Kontext entscheidet: 'Mieszkanie w Warszawie jest drogie' = 'Das Wohnen in Warschau ist teuer' ODER 'Eine Wohnung in Warschau ist teuer'. 'Kupić mieszkanie' = eine Wohnung kaufen. Diese Doppeldeutigkeit entsteht, weil viele Verbalsubstantive zu eigenständigen Nomen geworden sind!"},
            {"id": "gp_vnom6", "question": "Po _____ książki oddałem ją.", "translation": "(Nach dem Lesen des Buches gab ich es zurück.)", "options": ["przeczytaniu", "czytaniu", "czytać", "przeczytać"], "correct": "przeczytaniu", "explanation": "'Po przeczytaniu' = 'nach dem Lesen' – Präposition 'po' + Lokativ des Verbalsubstantivs. 'Przeczytanie' (perfektiv: fertig gelesen) vs. 'czytanie' (imperfektiv: Prozess des Lesens). Hier passt 'przeczytaniu' besser: nach dem FERTIGEN Lesen. Der Lokativ von '-anie/-eniu' ist '-aniu/-eniu'. Zeitliche Abfolge mit Präposition + Verbalsubstantiv ist im Polnischen sehr üblich!"},
            {"id": "gp_vnom7", "question": "Przed _____ sprawdź pogodę.", "translation": "(Vor dem Weggehen prüfe das Wetter.)", "options": ["wyjściem", "wychodzeniem", "wyjść", "wychodzić"], "correct": "wyjściem", "explanation": "'Przed wyjściem' = 'vor dem Weggehen' – 'przed' + Instrumental. 'Wyjście' kommt von 'wyjść' (perfektiv: rausgehen) und endet auf '-cie' statt '-anie' (bei perfektiven Verben auf -ść/-źć). Der Instrumental von '-cie' ist '-ciem': 'wyjście → wyjściem'. Anders als deutsch 'vor dem Weggehen', wo '-en' unverändert bleibt, wird im Polnischen das Verbalsubstantiv dekliniert!"},
            {"id": "gp_vnom8", "question": "Bez _____ podjął decyzję.", "translation": "(Ohne Überlegung traf er eine Entscheidung.)", "options": ["zastanowienia", "zastanawiać", "zastanowić", "zastanowieniem"], "correct": "zastanowienia", "explanation": "'Bez zastanowienia' = 'ohne Überlegung' – 'bez' + Genitiv. Die Präposition 'bez' (ohne) verlangt immer den Genitiv, genau wie 'ohne' im Deutschen den Akkusativ verlangt. 'Zastanowienie' von 'zastanowić się' (sich überlegen) → Genitiv: 'zastanowienia'. Die Reflexivität ('się') fällt beim Verbalsubstantiv weg. Im Deutschen: 'Überlegung' mit dem Suffix '-ung'."},
            {"id": "gp_vnom9", "question": "Podczas _____ słuchałem muzyki.", "translation": "(Während des Spazierens hörte ich Musik.)", "options": ["spacerowania", "spacerować", "spaceru", "spacerem"], "correct": "spacerowania", "explanation": "'Podczas spacerowania' = 'während des Spazierens' – 'podczas' + Genitiv. 'Spacerowanie' → Genitiv: 'spacerowania'. Man könnte auch sagen: 'Podczas spaceru' (während des Spaziergangs) – hier mit dem eigenständigen Substantiv 'spacer' statt dem Verbalsubstantiv. Beide sind korrekt, aber 'spacerowania' betont die Tätigkeit, 'spaceru' das Ereignis."},
            {"id": "gp_vnom10", "question": "_____ nowego leku zajęło lata.", "translation": "(Die Entdeckung eines neuen Medikaments dauerte Jahre.)", "options": ["Odkrycie", "Odkrywanie", "Odkrywać", "Odkryto"], "correct": "Odkrycie", "explanation": "'Odkrycie' von 'odkryć' (entdecken, perfektiv) – perfektive Verbalsubstantive enden auf '-cie' statt '-anie'. 'Odkrycie' betont das Ergebnis (die Entdeckung als Ereignis), während 'odkrywanie' (imperfektiv) den Prozess betonen würde. Im Deutschen: 'Entdeckung' (-ung) kann beides bedeuten. Im Polnischen haben Sie die Wahl! 'Odkrycie leku' = Genitiv des Objekts."},
            {"id": "gp_vnom11", "question": "_____ nowych języków rozwija umysł.", "translation": "(Das Lernen neuer Sprachen entwickelt den Geist.)", "options": ["Uczenie się", "Uczę się", "Nauczenie", "Uczyć się"], "correct": "Uczenie się", "explanation": "'Uczenie się' – das reflexive 'się' bleibt beim Verbalsubstantiv erhalten! 'Uczyć się' (lernen) → 'uczenie się' (das Lernen). Die meisten reflexiven Verben behalten 'się' auch als Substantiv: 'martwienie się' (das Sich-Sorgen), 'śmianie się' (das Lachen). Im Deutschen fällt das 'sich' weg: 'das Lernen', nicht 'das Sich-Lernen'. Das 'się' im Polnischen bleibt immer!"},
            {"id": "gp_vnom12", "question": "Oczekiwanie _____ wynik było stresujące.", "translation": "(Das Warten auf das Ergebnis war stressig.)", "options": ["na", "o", "za", "do"], "correct": "na", "explanation": "Das Verbalsubstantiv behält die Rektion (Präpositionsanschluss) des Verbs! 'Oczekiwać na coś' (auf etwas warten) → 'oczekiwanie na coś' (das Warten auf etwas). Die Präposition 'na' bleibt gleich. Genau wie im Deutschen: 'warten auf' → 'das Warten auf'. Weitere Beispiele: 'myślenie o' (das Denken an), 'tęsknienie za' (das Sehnen nach), 'marzenie o' (das Träumen von)."},
            {"id": "gp_vnom13", "question": "_____ uczniów było wzorowe.", "translation": "(Das Verhalten der Schüler war vorbildlich.)", "options": ["Zachowanie", "Zachowywanie", "Zachować", "Zachowywać"], "correct": "Zachowanie", "explanation": "'Zachowanie' hat sich vom Verbalsubstantiv zum eigenständigen Substantiv entwickelt: 'das Verhalten'. Viele polnische Verbalsubstantive haben diesen Weg genommen: 'mieszkanie' (Wohnung), 'odkrycie' (Entdeckung), 'zachowanie' (Verhalten). Sie behalten die Neutrumform, funktionieren aber als normale Substantive mit eigener Bedeutung. Im Deutschen: '-ung'-Formen ('Wohnung', 'Entdeckung', 'Verhaltung' → 'Verhalten')."},
            {"id": "gp_vnom14", "question": "Sprzątanie _____ mi trzy godziny.", "translation": "(Das Aufräumen hat mich drei Stunden gekostet.)", "options": ["zajęło", "zajął", "zajęła", "zajęli"], "correct": "zajęło", "explanation": "Das Verbalsubstantiv 'sprzątanie' ist Neutrum → daher 'zajęło' (Neutrum-Vergangenheit). Im Deutschen: 'Das Aufräumen hat... gekostet' – 'hat' bleibt gleich. Im Polnischen muss das Verb mit dem Genus des Subjekts übereinstimmen: 'zajął' (mask.), 'zajęła' (fem.), 'zajęło' (neutr.). Da alle Verbalsubstantive Neutrum sind, ist 'zajęło' die richtige Form. Ein konsistentes Muster!"},
            {"id": "gp_vnom15", "question": "_____ domu trwa długo.", "translation": "(Ein Haus zu bauen dauert lange.)", "options": ["Budowanie", "Budowa", "Budować", "Wybudowanie"], "correct": "Budowanie", "explanation": "'Budowanie domu' = 'das Bauen eines Hauses' – imperfektives Verbalsubstantiv betont den langwierigen Prozess. Vergleichen Sie: 'Budowa domu' = 'der Bau des Hauses' (eigenständiges Substantiv, formeller). 'Wybudowanie domu' = 'das Fertigbauen' (perfektiv, betont Abschluss). Drei Möglichkeiten, wo das Deutsche nur 'Bau/Bauen' hat! Die Aspektunterscheidung bleibt auch bei Substantiven erhalten."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")
