#!/usr/bin/env python3
"""Batch 12b: Replacement category + Batch 13 (categories 67-72) for german_polish grammar."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "augmentatives",
        "name": "Zgrubienia (Vergrößerungsformen)",
        "description": "Augmentative und pejorative Wortformen im Polnischen – das Gegenteil der Diminutive",
        "icon": "arrow.up.left.and.arrow.down.right",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_aug1", "question": "Zgrubienie od 'dom' to _____.", "translation": "(Die Vergrößerungsform von 'Haus' ist...)", "options": ["domisko", "domek", "domnik", "domownik"], "correct": "domisko", "explanation": "Das Suffix '-isko' bildet Augmentative (Vergrößerungsformen) mit pejorativer Bedeutung: 'dom' (Haus) → 'domisko' (großes, hässliches Haus). Im Gegensatz zum Diminutiv 'domek' (Häuschen, niedlich) drückt 'domisko' negative Wertung aus. Im Deutschen gibt es kein vergleichbares Suffix – man müsste umschreiben: 'riesiges hässliches Haus'."},
            {"id": "gp_aug2", "question": "Duży, groźny pies to _____.", "translation": "(Ein großer, bedrohlicher Hund ist ein...)", "options": ["psisko", "piesek", "psiak", "psina"], "correct": "psisko", "explanation": "'Psisko' = großer, bedrohlicher Hund (Augmentativ von 'pies'). Das Suffix '-isko' drückt Größe und oft negative Eigenschaften aus. Vergleich der drei Formen: 'piesek' (Hündchen, liebevoll), 'pies' (Hund, neutral), 'psisko' (riesiger Hund, bedrohlich). Im Polnischen gibt es ein dreistufiges System: Diminutiv ↔ Neutralform ↔ Augmentativ, das im Deutschen fehlt."},
            {"id": "gp_aug3", "question": "Ale masz wielkie _____!", "translation": "(Was für riesige Pfoten/Hände du hast!)", "options": ["łapska", "łapki", "łapy", "łapeczki"], "correct": "łapska", "explanation": "'Łapska' (riesige Pfoten/Hände) ist der Augmentativ von 'łapy' (Pfoten/Hände umg.) mit dem Suffix '-sko/-ska'. Vergleich: 'łapki' (Pfötchen/Händchen, Diminutiv), 'łapy' (Pfoten, neutral/umg.), 'łapska' (Riesenpranken, Augmentativ). Im Polnischen können Augmentative auch humorvoll verwendet werden, nicht nur pejorativ."},
            {"id": "gp_aug4", "question": "On ma ogromny _____.", "translation": "(Er hat einen riesigen Wanst/Bauch.)", "options": ["brzuchol", "brzuszek", "brzuch", "brzusio"], "correct": "brzuchol", "explanation": "Das Suffix '-ol' bildet komische Augmentative: 'brzuch' (Bauch) → 'brzuchol' (dicker Wanst). Vergleich: 'brzuszek' (Bäuchlein, lieb), 'brzuch' (Bauch, neutral), 'brzuchol' (Wanst, komisch-pejorativ). Im Polnischen gibt es verschiedene Augmentativ-Suffixe: '-isko' (häufigster), '-ol' (komisch), '-sko' (stark pejorativ). Jedes Suffix hat eine eigene emotionale Färbung."},
            {"id": "gp_aug5", "question": "To jest ale _____!", "translation": "(Das ist aber ein Riesenkerl!)", "options": ["chłopisko", "chłopek", "chłopik", "chłopczyk"], "correct": "chłopisko", "explanation": "'Chłopisko' = Riesenkerl (Augmentativ von 'chłop' = Mann/Kerl). Interessanterweise kann 'chłopisko' je nach Kontext positiv (beeindruckend großer Mann) oder negativ (ungehobelter Kerl) sein. Das zeigt, dass Augmentative im Polnischen kontextabhängig sind. Im Diminutiv: 'chłopczyk' (kleiner Junge/Bübchen). Die Suffixe verraten die Einstellung des Sprechers."},
            {"id": "gp_aug6", "question": "Wielki, niezgrabny but to _____.", "translation": "(Ein großer, klobiger Schuh ist ein...)", "options": ["bucior", "bucik", "bucisko", "butonek"], "correct": "bucior", "explanation": "'Bucior' = großer, klobiger Schuh (Augmentativ). Vergleich: 'bucik' (Schühchen, niedlich), 'but' (Schuh, neutral), 'bucior' (Klotz/Treter, pejorativ). Das Suffix '-or' ist ein selteneres Augmentativ-Suffix. Im Polnischen gibt es auch Augmentative im Plural: 'buciory' (Treter/klobige Schuhe). Diese Formen kommen besonders in der Umgangssprache und Literatur vor."},
            {"id": "gp_aug7", "question": "Ta babsko jest bardzo _____.", "translation": "(Dieses Weibsbild ist sehr...)", "options": ["złośliwa", "miła", "ładna", "grzeczna"], "correct": "złośliwa", "explanation": "'Babsko' ist ein stark pejorativer Augmentativ von 'baba' (Frau, umg.) mit dem Suffix '-sko'. Es wird nur abwertend verwendet und beschreibt eine unangenehme Frau. Achtung: dieses Wort ist beleidigend! Im Polnischen sind Augmentative bei Personenbezeichnungen fast immer negativ, während Diminutive positiv/liebevoll sind. Im Deutschen müsste man 'Weibsbild' oder ähnlich Pejorative verwenden."},
            {"id": "gp_aug8", "question": "Wielki nos to _____.", "translation": "(Eine große Nase ist ein/eine...)", "options": ["nochal", "nosek", "nosik", "noseńka"], "correct": "nochal", "explanation": "Das Suffix '-al' bildet komische Augmentative: 'nos' (Nase) → 'nochal' (Riesenzinken). Vergleich: 'nosek/nosik' (Näschen, niedlich), 'nos' (Nase, neutral), 'nochal' (Riesennase, spöttisch). Im Polnischen werden Augmentative für Körperteile oft humorvoll verwendet. Der Stammwechsel 's' → 'ch' ist hier unregelmäßig – nicht alle Augmentative sind vorhersagbar."},
            {"id": "gp_aug9", "question": "Wiatr się wzmógł i teraz jest to prawdziwa _____.", "translation": "(Der Wind hat zugenommen und jetzt ist es ein richtiger Sturm.)", "options": ["wichura", "wietrzyk", "wiatr", "wiaterek"], "correct": "wichura", "explanation": "'Wichura' (Sturm) ist eine Intensivierung von 'wiatr' (Wind) – technisch kein Augmentativ, sondern ein eigenes Wort, aber es folgt dem Muster der Steigerung: 'wiaterek' (Lüftchen, Dim.) → 'wiatr' (Wind) → 'wichura' (Sturm). Im Polnischen gibt es für Naturphänomene oft dreistufige Skalen, die über einfache Augmentative hinausgehen."},
            {"id": "gp_aug10", "question": "To straszydło stoi w ogrodzie.", "translation": "(Diese Vogelscheuche/dieses Schreckgespenst steht im Garten.)", "options": ["Straszydło", "Straszek", "Straszny", "Straszak"], "correct": "Straszydło", "explanation": "Das Suffix '-ydło' bildet stark pejorative Substantive: 'straszyć' (erschrecken) → 'straszydło' (Schreckgespenst/Vogelscheuche). Weitere: 'babsztyl' → 'babsztyldło' (Schreckschraube). Das Suffix '-ydło' gehört zu den stärksten pejorativen Suffixen im Polnischen. Es wird auch figurativ verwendet: 'Wyglądasz jak straszydło!' (Du siehst aus wie eine Vogelscheuche!)."},
            {"id": "gp_aug11", "question": "Pejoratatywna forma od 'dziecko' to _____.", "translation": "(Die pejorative Form von 'Kind' ist...)", "options": ["dziecisko", "dzieciątko", "dziecinko", "dzidziuś"], "correct": "dziecisko", "explanation": "'Dziecisko' = ungezogenes Kind (Augmentativ von 'dziecko' mit '-isko'). Vergleich: 'dzidziuś' (Babchen, zärtlich), 'dzieciątko' (Kindlein, zärtlich), 'dziecko' (Kind, neutral), 'dzieciak' (Kid, umg.), 'dziecisko' (Balg, pejorativ). Im Polnischen zeigt das Suffix die Einstellung des Sprechers: '-ątko/-uszko' = Zärtlichkeit, '-isko' = Missbilligung."},
            {"id": "gp_aug12", "question": "Potężne, masywne ciało to _____.", "translation": "(Ein massiger, schwerer Körper ist ein...)", "options": ["cielsko", "ciałko", "ciałeczko", "cielęce"], "correct": "cielsko", "explanation": "'Cielsko' = massiger Körper (Augmentativ von 'ciało' mit '-sko'). Pejorative Beschreibung eines großen, schweren Körpers. Vergleich: 'ciałko' (Körperchen, neutral-wissenschaftlich), 'ciało' (Körper, neutral), 'cielsko' (Koloss, abwertend). Das Suffix '-sko' ist stärker pejorativ als '-isko'. Im Deutschen müsste man umschreiben: 'massiger Koloss'."},
            {"id": "gp_aug13", "question": "Ten dzieciak to prawdziwy _____.", "translation": "(Dieses Kind ist ein richtiger Raufbold/Lausbub.)", "options": ["urwis", "aniołek", "grzeczniś", "maleństwo"], "correct": "urwis", "explanation": "'Urwis' (Lausbub/Raufbold) – kein Augmentativ im engeren Sinne, aber ein pejorativer Ausdruck für ein ungezogenes Kind. Im Polnischen gibt es viele solcher expressiven Wörter: 'łobuz' (Lausbube), 'urwis' (Raufbold), 'nicpoń' (Taugenichts), 'szelma' (Schelm). Diese Wörter werden oft liebevoll-tadelnd verwendet – ähnlich wie 'Lausbub' im Süddeutschen."},
            {"id": "gp_aug14", "question": "Wielgachna to forma zgrubiała od _____.", "translation": "('Wielgachna' ist die augmentative Form von...)", "options": ["wielka", "mała", "szeroka", "długa"], "correct": "wielka", "explanation": "'Wielgachna' ist eine seltene augmentative Adjektivform von 'wielka' (groß, fem.) – 'riesengroß'. Im Polnischen können auch Adjektive Augmentative bilden, was im Deutschen unmöglich ist. Weitere: 'maluśki/malutki' (klitzeklein, Dim.), 'wielki' (groß, neutral), 'wielgachny' (riesengroß, Aug.). Diese Formen erscheinen hauptsächlich in der gesprochenen Sprache und Kinderliteratur."},
            {"id": "gp_aug15", "question": "Jakie wielgachne _____!", "translation": "(Was für riesige Augen!)", "options": ["oczyska", "oczka", "oczy", "oczęta"], "correct": "oczyska", "explanation": "'Oczyska' = riesige Augen (Augmentativ von 'oczy' mit '-yska'). Dreistufig: 'oczka' (Äuglein, Dim.) → 'oczy' (Augen, neutral) → 'oczyska' (Riesenaugen, Aug./expressiv). Im Märchen 'Rotkäppchen': 'Jakie masz wielkie oczy!' – hier könnte man 'oczyska' verwenden für noch stärkeren Ausdruck. Augmentative von Körperteilen sind im Polnischen expressiv und emotional geladen."}
        ]
    },
    {
        "key": "aspect_pairs_advanced",
        "name": "Aspektpaare – Fortgeschritten (Aspektpaare – Fortgeschritten)",
        "description": "Vertiefte Arbeit mit perfektiven und imperfektiven Verben und sekundärer Imperfektivierung",
        "icon": "arrow.left.arrow.right",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_aspa1", "question": "Codziennie _____ gazetę. (regelmäßig)", "translation": "(Ich lese jeden Tag eine Zeitung.)", "options": ["czytam", "przeczytam", "czytałem", "przeczytałem"], "correct": "czytam", "explanation": "'Czytać' (imperfektiv/unvollendet) für regelmäßige, wiederholte Handlungen. Im Deutschen: 'Ich lese' – kein Aspektunterschied sichtbar! Im Polnischen muss man IMMER zwischen imperfektiv (Prozess/Gewohnheit) und perfektiv (Ergebnis/Einmaligkeit) wählen. 'Codziennie' (jeden Tag) signalisiert Gewohnheit → imperfektiv. Das ist einer der schwierigsten Aspekte des Polnischen für Deutschsprachige."},
            {"id": "gp_aspa2", "question": "Wczoraj _____ całą książkę. (abgeschlossen)", "translation": "(Gestern habe ich das ganze Buch gelesen.)", "options": ["przeczytałem", "czytałem", "czytam", "przeczytam"], "correct": "przeczytałem", "explanation": "'Przeczytać' (perfektiv/vollendet) für eine abgeschlossene Handlung mit Ergebnis. 'Przeczytałem całą książkę' = Ich habe das ganze Buch durchgelesen (fertig!). 'Czytałem książkę' (imperfektiv) würde bedeuten: Ich las ein Buch (Prozess, unklar ob fertig). Der Aspekt ist im Polnischen grammatisch obligatorisch – im Deutschen drückt man das durch Kontext oder Adverbien aus."},
            {"id": "gp_aspa3", "question": "Kiedy ja _____, on oglądał telewizję. (gleichzeitig)", "translation": "(Während ich kochte, schaute er fern.)", "options": ["gotowałam", "ugotowałam", "gotuję", "ugotuję"], "correct": "gotowałam", "explanation": "Für gleichzeitige Handlungen (während) verwendet man den imperfektiven Aspekt: 'gotowałam' (ich kochte, Prozess). Wenn zwei Handlungen parallel ablaufen, müssen BEIDE imperfektiv sein. 'Ugotowałam' (perfektiv) würde bedeuten: 'nachdem ich fertig gekocht hatte'. Im Deutschen unterscheidet man das durch 'während' vs. 'nachdem', im Polnischen durch den Aspekt."},
            {"id": "gp_aspa4", "question": "Jutro _____ ten raport do końca.", "translation": "(Morgen werde ich diesen Bericht zu Ende schreiben.)", "options": ["napiszę", "będę pisać", "piszę", "pisałem"], "correct": "napiszę", "explanation": "Perfektive Verben im Präsens drücken die ZUKUNFT aus: 'napiszę' (ich werde schreiben/fertigschreiben). Im Polnischen gibt es zwei Zukunftsformen: perfektiv-Präsens ('napiszę' = werde fertigschreiben) und imperfektiv mit 'będę' ('będę pisać' = werde schreiben, Prozess). 'Napiszę' betont das Ergebnis, 'będę pisać' den Prozess. Im Deutschen: 'ich werde schreiben' – kein Aspektunterschied."},
            {"id": "gp_aspa5", "question": "Zapisywać to wtórna forma _____ od 'zapisać'.", "translation": "('Zapisywać' ist die sekundäre _____ Form von 'zapisać'.)", "options": ["niedokonana", "dokonana", "rozkazująca", "warunkowa"], "correct": "niedokonana", "explanation": "Sekundäre Imperfektivierung: 'zapisać' (perfektiv: aufschreiben) → 'zapisywać' (sekundär imperfektiv: aufzuschreiben pflegen). Im Polnischen kann ein perfektives Verb durch Suffixe ('-ywać', '-iwać', '-ać') wieder imperfektiv gemacht werden: 'kupić' → 'kupować', 'zrobić' → 'zrabiać'. Dieses Phänomen gibt es im Deutschen nicht – es ist eine der komplexesten Besonderheiten des Polnischen."},
            {"id": "gp_aspa6", "question": "Nie _____ tego robić! (Verbot)", "translation": "(Tu das nicht! / Mach das bloß nicht!)", "options": ["rób", "zrób", "robisz", "zrobisz"], "correct": "rób", "explanation": "Im negativen Imperativ (Verbot) verwendet man IMMER den imperfektiven Aspekt: 'Nie rób!' (Tu das nicht!). 'Nie zrób!' wäre grammatisch falsch oder würde 'Hoffentlich machst du das nicht' bedeuten (Warnung, nicht Verbot). Diese Regel ist absolut: positive Befehle können beide Aspekte verwenden, negative Befehle nur imperfektiv. Das ist eine klare Regel, die man einfach auswendig lernen muss."},
            {"id": "gp_aspa7", "question": "Zaczynam _____ nową książkę.", "translation": "(Ich fange an, ein neues Buch zu lesen.)", "options": ["czytać", "przeczytać", "czytanie", "przeczytanie"], "correct": "czytać", "explanation": "Nach Phasenverben ('zaczynać' = anfangen, 'kończyć' = aufhören, 'kontynuować' = fortsetzen) steht IMMER ein imperfektiver Infinitiv: 'zaczynać czytać' (anfangen zu lesen). Man kann nicht 'zaczynać przeczytać' sagen – das wäre ein logischer Widerspruch (anfangen, etwas zu beenden). Diese Regel gilt auch im Russischen und anderen slawischen Sprachen."},
            {"id": "gp_aspa8", "question": "Ciągle _____ ten sam błąd. (wiederholt)", "translation": "(Du machst ständig denselben Fehler.)", "options": ["robisz", "zrobisz", "robiłeś", "zrobiłeś"], "correct": "robisz", "explanation": "'Ciągle' (ständig/immer wieder) + imperfektives Verb: 'robisz' für wiederholte Handlungen. Signalwörter für imperfektiv: 'ciągle' (ständig), 'zawsze' (immer), 'często' (oft), 'codziennie' (täglich), 'zwykle' (gewöhnlich). Signalwörter für perfektiv: 'nagle' (plötzlich), 'wreszcie' (endlich), 'w końcu' (schließlich). Diese Adverbien helfen bei der Aspektwahl."},
            {"id": "gp_aspa9", "question": "Nagle _____ deszcz. (plötzlich, einmalig)", "translation": "(Plötzlich fing es an zu regnen.)", "options": ["spadł", "spadał", "spada", "spadnie"], "correct": "spadł", "explanation": "'Nagle' (plötzlich) + perfektiver Aspekt: 'spadł deszcz' (es fiel Regen = es fing plötzlich an zu regnen). 'Nagle' signalisiert eine einmalige, plötzliche Handlung → perfektiv. 'Spadał' (imperfektiv) würde 'es regnete (wiederholt/lange)' bedeuten. Im Polnischen bestimmt der Aspekt, ob etwas als Moment oder Prozess dargestellt wird – eine Perspektive, die im Deutschen fehlt."},
            {"id": "gp_aspa10", "question": "Przez godzinę _____ na autobus.", "translation": "(Ich habe eine Stunde lang auf den Bus gewartet.)", "options": ["czekałem", "poczekałem", "czekam", "poczekam"], "correct": "czekałem", "explanation": "'Przez godzinę' (eine Stunde lang) signalisiert Dauer → imperfektiver Aspekt: 'czekałem' (ich wartete). Zeitangaben mit 'przez' (durch/lang) verlangen imperfektiv, weil sie die Dauer der Handlung betonen. 'Poczekałem' (perfektiv) würde 'ich habe kurz gewartet' oder 'ich habe auf ein Ergebnis gewartet' bedeuten – eine andere Perspektive auf die gleiche Situation."},
            {"id": "gp_aspa11", "question": "W końcu _____ ten trudny egzamin!", "translation": "(Endlich habe ich diese schwere Prüfung bestanden!)", "options": ["zdałem", "zdawałem", "zdaję", "zdawać"], "correct": "zdałem", "explanation": "'W końcu' (endlich/schließlich) + perfektiver Aspekt: 'zdałem' (ich habe bestanden). 'W końcu' signalisiert ein Ergebnis nach längerem Warten → perfektiv. Vergleich: 'zdawałem egzamin' (ich legte eine Prüfung ab, Prozess, unklar ob bestanden) vs. 'zdałem egzamin' (ich habe bestanden, Ergebnis positiv). Der Aspekt verrät das Ergebnis!"},
            {"id": "gp_aspa12", "question": "Lubię _____ książki wieczorem.", "translation": "(Ich lese abends gerne Bücher.)", "options": ["czytać", "przeczytać", "czytanie", "przeczytanie"], "correct": "czytać", "explanation": "Nach Verben der Vorliebe ('lubić' = mögen, 'kochać' = lieben, 'preferować' = bevorzugen) steht der imperfektive Infinitiv: 'lubię czytać' (ich lese gerne). Man kann nicht 'lubię przeczytać' sagen – man mag den Prozess, nicht das einmalige Abschließen. Diese Regel gilt auch für: 'umieć' (können), 'potrafić' (imstande sein), 'wolę' (ich bevorzuge)."},
            {"id": "gp_aspa13", "question": "Czy możesz _____ okno? (einmalige Bitte)", "translation": "(Kannst du das Fenster öffnen?)", "options": ["otworzyć", "otwierać", "otworzenie", "otwieranie"], "correct": "otworzyć", "explanation": "Einmalige Bitte → perfektiver Infinitiv: 'otworzyć' (öffnen, einmalig). 'Czy możesz otwierać okno?' (imperfektiv) würde 'Kannst du das Fenster regelmäßig öffnen?' bedeuten. Bei Bitten unterscheidet der Aspekt zwischen einmalig (perfektiv) und wiederholt (imperfektiv). Diese Nuance ist im Deutschen nicht grammatisch markiert – man muss den Kontext nutzen."},
            {"id": "gp_aspa14", "question": "Długo _____ się do egzaminu.", "translation": "(Ich habe mich lange auf die Prüfung vorbereitet.)", "options": ["przygotowywałem", "przygotowałem", "przygotuję", "przygotowuję"], "correct": "przygotowywałem", "explanation": "'Długo' (lange) signalisiert Dauer → imperfektiver Aspekt. 'Przygotowywać się' ist die sekundäre imperfektive Form von 'przygotować się' (sich vorbereiten). Kette: 'gotować' (kochen/bereiten) → 'przygotować' (vorbereiten, perf.) → 'przygotowywać' (vorbereiten, sek. imperf.). Diese dreistufige Aspektkette ist typisch für das Polnische und eine der größten Herausforderungen."},
            {"id": "gp_aspa15", "question": "Proszę nie _____ drzwi.", "translation": "(Bitte schließen Sie die Tür nicht.)", "options": ["zamykać", "zamknąć", "zamykanie", "zamknięcie"], "correct": "zamykać", "explanation": "Negativer Imperativ/Bitte → IMMER imperfektiv: 'Proszę nie zamykać' (Bitte nicht schließen). 'Proszę nie zamknąć' wäre falsch oder würde 'Bitte achten Sie darauf, nicht versehentlich zu schließen' bedeuten (eine Warnung). Die Regel ist absolut: 'Proszę + nie + imperfektiver Infinitiv' für höfliche Verbote. Diese Aspektregel gehört zu den wichtigsten im Polnischen."}
        ]
    },
    {
        "key": "numerals_grammar",
        "name": "Grammatik der Zahlwörter (Zahlwortgrammatik)",
        "description": "Komplexe Grammatikregeln bei Zahlwörtern – Kasus und Kongruenz nach Zahlen",
        "icon": "number.circle",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_numg1", "question": "Mam jednego _____.", "translation": "(Ich habe einen Bruder.)", "options": ["brata", "braci", "bracie", "bratem"], "correct": "brata", "explanation": "Nach 'jeden/jedna/jedno' (eins) steht der reguläre Kasus wie ohne Zahlwort: 'mam brata' (Akkusativ Singular wie 'einen Bruder'). Bei 'jeden' (1) unterscheidet sich das Polnische nicht vom Deutschen – das Substantiv folgt den normalen Kasusregeln. Die Komplikationen beginnen erst bei 2-4 und ab 5. Die Zahl 'jeden' ist die einfachste."},
            {"id": "gp_numg2", "question": "Na stole leżą _____ książki.", "translation": "(Auf dem Tisch liegen zwei Bücher.)", "options": ["dwie", "dwaj", "dwóch", "dwu"], "correct": "dwie", "explanation": "'Dwie' ist die feminine Form von 'zwei' – 'książki' (Bücher) ist feminin. Die Zahl 2 hat im Polnischen verschiedene Genusformen: 'dwaj' (maskulin-personal: zwei Männer), 'dwie' (feminin: zwei Frauen/Bücher), 'dwa' (maskulin unbelebt/sächlich: zwei Häuser). Im Deutschen: immer 'zwei'. Nach 2-4 steht das Substantiv im Nominativ Plural – eine wichtige Regel!"},
            {"id": "gp_numg3", "question": "W klasie jest pięciu _____.", "translation": "(In der Klasse sind fünf Schüler.)", "options": ["uczniów", "uczni", "uczeń", "uczniami"], "correct": "uczniów", "explanation": "Ab 5 aufwärts steht das Substantiv im GENITIV PLURAL: 'pięciu uczniów' (fünf Schüler-Genitiv). Das ist die berüchtigte '5-und-mehr-Regel': 2-4 → Nominativ Plural, 5+ → Genitiv Plural. Das Verb steht dann in der 3. Person Singular: 'jest pięciu uczniów' (es ist fünf Schüler). Im Deutschen: 'fünf Schüler sind' – hier ist der Unterschied fundamental!"},
            {"id": "gp_numg4", "question": "Spotkałem _____ dziewczyny.", "translation": "(Ich habe drei Mädchen getroffen.)", "options": ["trzy", "trzech", "troje", "trzema"], "correct": "trzy", "explanation": "Nach 2-4 für nicht-maskulin-personale Substantive: Nominativ/Akkusativ Plural. 'Trzy dziewczyny' (drei Mädchen, Akk.Pl.). Aber: 'trzech chłopców' (drei Jungen, Gen.Pl. maskulin-personal!). Die Regel unterscheidet maskulin-personal (Männer/gemischte Gruppen) von allen anderen. Im Deutschen gibt es diese Geschlechterunterscheidung bei Zahlwörtern nicht – 'drei' bleibt immer 'drei'."},
            {"id": "gp_numg5", "question": "_____ dzieci bawi się w parku.", "translation": "(Fünf Kinder spielen im Park.)", "options": ["Pięcioro", "Pięć", "Piątka", "Pięciu"], "correct": "Pięcioro", "explanation": "'Pięcioro' ist die Sammelzahl (Kollektivzahl) – verwendet für Kindergruppen, gemischte Geschlechter und Pluralia tantum. 'Pięcioro dzieci' (fünf Kinder). Diese Sammelzahlen (dwoje, troje, czworo, pięcioro...) existieren nur im Polnischen und einigen slawischen Sprachen – sie haben kein deutsches Äquivalent. Das Substantiv steht im Genitiv Plural: 'dzieci' (Kinder, Gen.Pl.)."},
            {"id": "gp_numg6", "question": "Ta książka kosztuje dwadzieścia _____ złotych.", "translation": "(Dieses Buch kostet zweiundzwanzig Zloty.)", "options": ["dwa", "dwóch", "dwu", "dwaj"], "correct": "dwa", "explanation": "Bei zusammengesetzten Zahlen bestimmt die letzte Ziffer den Kasus: 22 → '...dwa' (2) → Nominativ Plural: 'dwadzieścia dwa złote'. Aber 25 → '...pięć' (5) → Genitiv Plural: 'dwadzieścia pięć złotych'. Im Polnischen zählt man: 'dwadzieścia dwa' (zwanzig-zwei, wie im Englischen!), nicht wie im Deutschen 'zweiundzwanzig' (umgekehrt). Die Wortstellung der Zahlen ist also anders!"},
            {"id": "gp_numg7", "question": "Czekałem na ciebie _____ godziny.", "translation": "(Ich habe zwei Stunden auf dich gewartet.)", "options": ["dwie", "dwóch", "dwa", "dwaj"], "correct": "dwie", "explanation": "Zeitangaben im Akkusativ: 'dwie godziny' (zwei Stunden, fem.Akk.Pl.). 'Godzina' (Stunde) ist feminin → 'dwie' (zwei, fem.). Nach 2-4: Akkusativ Plural. Nach 5+: Genitiv Plural ('pięć godzin'). Achtung: 'minuta' (Minute) ist auch feminin → 'dwie minuty', aber 'dzień' (Tag) ist maskulin → 'dwa dni'. Das Genus des Substantivs bestimmt die Form des Zahlworts."},
            {"id": "gp_numg8", "question": "W pokoju jest _____ studentów.", "translation": "(Im Zimmer sind sieben Studenten.)", "options": ["siedmiu", "siedem", "siedmio", "siódmy"], "correct": "siedmiu", "explanation": "'Siedmiu studentów' – maskulin-personale Form für 7 Studenten. Ab 5 bei maskulin-personalen Substantiven: spezielle Form auf '-u': 'pięciu' (5), 'sześciu' (6), 'siedmiu' (7). Das Verb steht dabei in der 3.Person Singular: 'jest siedmiu studentów' (es ist sieben Studenten). Für nicht-maskulin-personal: 'jest siedem dziewczyn' (mit 'siedem'). Zwei verschiedene Zahlwortformen je nach Genus!"},
            {"id": "gp_numg9", "question": "Ona ma _____ lat.", "translation": "(Sie ist dreißig Jahre alt.)", "options": ["trzydzieści", "trzydziestu", "trzydziesty", "trzydzieść"], "correct": "trzydzieści", "explanation": "'Trzydzieści lat' – 30 Jahre (Genitiv Plural 'lat' von 'rok'). Im Polnischen fragt man 'Ile masz lat?' (Wie viel Jahre hast du?). 'Rok' (Jahr) hat unregelmäßige Pluralformen: 2-4: 'lata' (Jahre, Nom.Pl.), 5+: 'lat' (Jahre, Gen.Pl.), 1: 'rok' (Jahr). Beachten Sie: 'lat' ist der Genitiv Plural – nach Zahlen ab 5 steht immer der Genitiv Plural."},
            {"id": "gp_numg10", "question": "Mam _____ kotów.", "translation": "(Ich habe vier Katzen.)", "options": ["cztery", "czterech", "czworo", "czwórka"], "correct": "cztery", "explanation": "'Cztery koty/cztery kotów' – Achtung! 'Kot' (Katze) ist maskulin-belebt, aber NICHT maskulin-personal! Daher: 'cztery koty' (Nom.Pl., nicht 'czterech'!). Die maskulin-personale Sonderform gilt NUR für männliche Personen, nicht für Tiere oder Gegenstände. 'Czterech' wäre nur für 'czterech mężczyzn' (vier Männer). Ein häufiger Fehler bei Lernenden!"},
            {"id": "gp_numg11", "question": "To jest pierwsza _____ tygodnia.", "translation": "(Das ist der erste Tag der Woche.)", "options": ["dzień", "dnia", "dniu", "dniowi"], "correct": "dzień", "explanation": "Ordnungszahlen (pierwszy, drugi, trzeci...) verhalten sich wie normale Adjektive – nach ihnen folgt der reguläre Kasus: 'pierwszy dzień' (erster Tag, Nominativ). Im Gegensatz zu Kardinalzahlen (1,2,3...), die komplexe Kasusregeln haben, sind Ordnungszahlen einfach: sie deklinieren wie Adjektive und das Substantiv folgt normal. Für Deutschsprachige ist das beruhigend einfach!"},
            {"id": "gp_numg12", "question": "Przyszło _____ osób.", "translation": "(Es kamen hundert Personen.)", "options": ["sto", "setka", "stówa", "stuch"], "correct": "sto", "explanation": "'Sto osób' (hundert Personen) – nach 'sto' (100) steht das Substantiv im Genitiv Plural (wie nach Zahlen ab 5). 'Sto' selbst ist undeklinierbar für den Nominativ/Akkusativ. In anderen Kasus: 'stu' (Gen./Dat./Lok.), 'stu/stem' (Instr.). Die Deklination der Hunderter ist eine eigene Herausforderung: 'dwieście' (200), 'trzysta' (300), 'czterysta' (400), 'pięćset' (500)."},
            {"id": "gp_numg13", "question": "Potrzebuję _____ minut.", "translation": "(Ich brauche fünfzehn Minuten.)", "options": ["piętnastu", "piętnaście", "piętnasta", "piętnaścioro"], "correct": "piętnastu", "explanation": "'Piętnastu minut' – die Zahl 'piętnaście' (15) im Genitiv (nach 'potrzebować' + Gen.): 'piętnastu'. Achtung: die Deklination der Zahlen 11-19 (-naście) ist komplex: 'piętnaście' (Nom./Akk.), 'piętnastu' (Gen./Dat./Lok.), 'piętnastu/piętnastoma' (Instr.). Zahlen ab 5 regieren den Genitiv Plural des Substantivs UND werden selbst im Satz dekliniert!"},
            {"id": "gp_numg14", "question": "Zamówiłem _____ kawy.", "translation": "(Ich habe zwei Kaffee bestellt.)", "options": ["dwie", "dwóch", "dwa", "dwoje"], "correct": "dwie", "explanation": "'Dwie kawy' (zwei Kaffee) – 'kawa' ist feminin, daher 'dwie' (fem. Form von 2). In der Gastronomie werden unzählbare Substantive wie 'kawa' (Kaffee) zählbar verwendet: 'dwie kawy' = zwei Tassen Kaffee. Das gleiche Phänomen gibt es im Deutschen: 'zwei Kaffee (bitte)'. Nach 2-4: Nominativ/Akkusativ Plural ('dwie kawy'), nach 5+: Genitiv Plural ('pięć kaw')."},
            {"id": "gp_numg15", "question": "Mamy _____ dzieci w przedszkolu.", "translation": "(Wir haben zwanzig Kinder im Kindergarten.)", "options": ["dwadzieścioro", "dwadzieścia", "dwudziestu", "dwudziestka"], "correct": "dwadzieścioro", "explanation": "Für 'dzieci' (Kinder) verwendet man die Sammelzahl: 'dwadzieścioro dzieci'. Sammelzahlen (dwoje, troje, czworo, pięcioro...) werden für Kinder, gemischtgeschlechtliche Gruppen und Pluralia tantum verwendet. Sie stehen mit dem Genitiv Plural. Diese Form existiert nur in slawischen Sprachen und hat kein deutsches Äquivalent – sie gehört zu den exotischsten Aspekten der polnischen Grammatik."}
        ]
    },
    {
        "key": "relative_clauses",
        "name": "Zdania względne (Relativsätze)",
        "description": "Polnische Relativsätze mit 'który' – kein Verbendstellung wie im Deutschen",
        "icon": "link.circle",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_rel1", "question": "Mężczyzna, _____ tam stoi, jest moim ojcem.", "translation": "(Der Mann, der dort steht, ist mein Vater.)", "options": ["który", "która", "które", "którzy"], "correct": "który", "explanation": "'Który' (der/welcher) ist das Relativpronomen für maskuline Substantive im Nominativ. Im Polnischen wird 'który' nach Genus, Numerus und Kasus dekliniert – genau wie deutsche Relativpronomen. Wichtiger Unterschied: im Polnischen bleibt das Verb in normaler Position ('który tam stoi'), im Deutschen geht es ans Ende ('der dort steht'). Die Wortstellung ist einfacher!"},
            {"id": "gp_rel2", "question": "Kobieta, _____ widziałeś, jest lekarką.", "translation": "(Die Frau, die du gesehen hast, ist Ärztin.)", "options": ["którą", "która", "którymi", "których"], "correct": "którą", "explanation": "'Którą' = Akkusativ Singular feminin (die/welche im Akk.). 'Widzieć' (sehen) verlangt den Akkusativ – das Relativpronomen übernimmt den Kasus, den es im Relativsatz einnimmt. Im Deutschen: 'die du gesehen hast' (ebenfalls Akkusativ). Die Kasuslogik ist in beiden Sprachen gleich – 'który' dekliniert wie ein Adjektiv: 'który, która, które, którzy, które'."},
            {"id": "gp_rel3", "question": "Dziecko, _____ dałem prezent, jest szczęśliwe.", "translation": "(Das Kind, dem ich ein Geschenk gegeben habe, ist glücklich.)", "options": ["któremu", "które", "którego", "którym"], "correct": "któremu", "explanation": "'Któremu' = Dativ Singular sächlich (dem). 'Dać' (geben) verlangt Dativ für den Empfänger. 'Dziecko' (Kind) ist sächlich → 'któremu' (Dativ sächl./mask.). Im Deutschen: 'dem ich... gegeben habe'. Die Dativform ist für Deutschsprachige logisch nachvollziehbar, da der Dativ in beiden Sprachen den Empfänger markiert. Nur die Endungen unterscheiden sich."},
            {"id": "gp_rel4", "question": "Dom, w _____ mieszkam, jest stary.", "translation": "(Das Haus, in dem ich wohne, ist alt.)", "options": ["którym", "który", "którego", "które"], "correct": "którym", "explanation": "'W którym' = Lokativ Singular maskulin (in dem/welchem). Nach der Präposition 'w' (in) steht der Lokativ. Im Polnischen werden Relativpronomen genau wie im Deutschen mit Präpositionen verwendet: 'w którym' (in dem), 'z którym' (mit dem), 'o którym' (über den). Die Präposition steht VOR dem Relativpronomen – genau wie im Deutschen. Das erleichtert das Lernen erheblich!"},
            {"id": "gp_rel5", "question": "Studenci, _____ zdali egzamin, są szczęśliwi.", "translation": "(Die Studenten, die die Prüfung bestanden haben, sind glücklich.)", "options": ["którzy", "które", "który", "których"], "correct": "którzy", "explanation": "'Którzy' = Nominativ Plural maskulin-personal (die/welche, für Männer/gemischte Gruppen). Im Polnischen hat der Plural zwei Formen: 'którzy' (maskulin-personal: für Männergruppen oder gemischte Gruppen) und 'które' (nicht-maskulin-personal: für Frauen, Dinge, Tiere). Diese Unterscheidung gibt es im Deutschen nicht – 'die' bleibt immer gleich."},
            {"id": "gp_rel6", "question": "Książki, _____ przeczytałem, są ciekawe.", "translation": "(Die Bücher, die ich gelesen habe, sind interessant.)", "options": ["które", "którzy", "który", "których"], "correct": "które", "explanation": "'Które' = Akkusativ Plural nicht-maskulin-personal (die/welche für Dinge). 'Książki' (Bücher) sind nicht-maskulin-personal → 'które' im Nominativ UND Akkusativ (gleiche Form). Vergleich: 'studentów, których poznałem' (Studenten, die ich kennengelernt habe – 'których' ist Gen.=Akk. für maskulin-personal). Die Belebtheitshierarchie beeinflusst auch Relativpronomen!"},
            {"id": "gp_rel7", "question": "Człowiek, _____ samochód jest czerwony, to mój sąsiad.", "translation": "(Der Mensch, dessen Auto rot ist, ist mein Nachbar.)", "options": ["którego", "który", "któremu", "którym"], "correct": "którego", "explanation": "'Którego' = Genitiv Singular maskulin (dessen). Im Polnischen drückt man 'dessen/deren' durch den Genitiv des Relativpronomens aus: 'którego samochód' (dessen Auto). Im Deutschen: Possessiv-Relativpronomen 'dessen'. Die Konstruktion ist parallel: 'człowiek, którego samochód...' = 'der Mensch, dessen Auto...' – die Wortstellung stimmt überein!"},
            {"id": "gp_rel8", "question": "To jest film, o _____ ci mówiłem.", "translation": "(Das ist der Film, von dem ich dir erzählt habe.)", "options": ["którym", "który", "którego", "które"], "correct": "którym", "explanation": "'O którym' = Lokativ Singular maskulin (von dem/über den). 'Mówić o' (sprechen über) verlangt Lokativ. Im Deutschen: 'von dem/über den'. Im Polnischen steht die Präposition 'o' direkt vor 'którym' – wie im Deutschen 'von dem'. Achtung: Im Englischen steht die Präposition oft am Satzende ('the film I told you about'), im Polnischen und Deutschen NIE – sie bleibt vor dem Pronomen."},
            {"id": "gp_rel9", "question": "Miasto, z _____ pochodzę, jest piękne.", "translation": "(Die Stadt, aus der ich komme, ist schön.)", "options": ["którego", "która", "którym", "które"], "correct": "którego", "explanation": "'Z którego' = aus + Genitiv Singular sächlich (aus dem). 'Miasto' (Stadt) ist sächlich → 'którego' (Gen. sächl. = Gen. mask.). 'Z' (aus) verlangt den Genitiv. Im Deutschen: 'aus der' (feminin, weil 'die Stadt' feminin ist). Achtung: das Genus unterscheidet sich! 'Miasto' ist sächlich im Polnischen, 'Stadt' ist feminin im Deutschen – das Relativpronomen folgt dem polnischen Genus!"},
            {"id": "gp_rel10", "question": "Ludzie, z _____ pracuję, są mili.", "translation": "(Die Leute, mit denen ich arbeite, sind nett.)", "options": ["którymi", "których", "którzy", "które"], "correct": "którymi", "explanation": "'Z którymi' = mit + Instrumental Plural (mit denen). 'Z' (mit) verlangt den Instrumental. 'Którymi' ist die Instrumentalform des Plurals – sie gilt für alle Genera. Im Deutschen: 'mit denen' (Dativ). Beachten Sie: im Polnischen steht nach 'z' (mit) der Instrumental, im Deutschen nach 'mit' der Dativ. Die Präposition bestimmt den Kasus des Relativpronomens."},
            {"id": "gp_rel11", "question": "To jest coś, _____ nie rozumiem.", "translation": "(Das ist etwas, das ich nicht verstehe.)", "options": ["czego", "co", "które", "którego"], "correct": "czego", "explanation": "'Czego' ist der Genitiv von 'co' (was) – nach 'nie rozumieć' (nicht verstehen) steht der Genitiv (Negationsgenitiv!). Für 'etwas, das/was' verwendet das Polnische 'co' (nicht 'który'!). 'Co' wird auch dekliniert: 'co' (Nom./Akk.), 'czego' (Gen.), 'czemu' (Dat.), 'czym' (Instr./Lok.). Im Deutschen: 'was' bleibt undekliniert – das Polnische ist hier komplexer."},
            {"id": "gp_rel12", "question": "Wszystko, _____ potrzebujesz, jest tutaj.", "translation": "(Alles, was du brauchst, ist hier.)", "options": ["czego", "co", "które", "którego"], "correct": "czego", "explanation": "Nach 'wszystko' (alles), 'nic' (nichts), 'coś' (etwas) verwendet man 'co' als Relativpronomen (nicht 'który'!). 'Potrzebować' (brauchen) verlangt den Genitiv → 'czego'. Das ist parallel zum Deutschen: 'alles, was du brauchst' – aber im Polnischen wird 'was' (co) dekliniert und im Deutschen nicht. Die Verbindung 'wszystko, co/czego...' ist eine sehr häufige Konstruktion."},
            {"id": "gp_rel13", "question": "Jest wielu ludzi, dla _____ to jest ważne.", "translation": "(Es gibt viele Menschen, für die das wichtig ist.)", "options": ["których", "którzy", "którymi", "którego"], "correct": "których", "explanation": "'Dla których' = für + Genitiv Plural (für die). 'Dla' (für) verlangt den Genitiv: 'których' (Gen.Pl.). Im Deutschen: 'für die' (Akkusativ). Hier unterscheiden sich die Kasus: Polnisch Genitiv nach 'dla', Deutsch Akkusativ nach 'für'. Die Präposition bestimmt in beiden Sprachen den Kasus – aber verschiedene Präpositionen verlangen verschiedene Kasus!"},
            {"id": "gp_rel14", "question": "Nauczycielka, _____ dzięki zdałem egzamin, jest świetna.", "translation": "(Die Lehrerin, dank der ich die Prüfung bestanden habe, ist großartig.)", "options": ["której", "która", "którą", "którym"], "correct": "której", "explanation": "'Dzięki której' = dank + Dativ feminin Singular (dank der/welcher). 'Dzięki' (dank) verlangt den Dativ: 'której' (Dat.Sg.fem.). 'Nauczycielka' ist feminin → 'której'. Im Deutschen: 'dank der' (Genitiv oder Dativ). Die Kasusrektion der Präposition 'dzięki' ist im Polnischen eindeutig Dativ – ein klares Muster, das man sich merken kann."},
            {"id": "gp_rel15", "question": "To jest powód, dla _____ się uczę.", "translation": "(Das ist der Grund, warum/weshalb ich lerne.)", "options": ["którego", "który", "którym", "którem"], "correct": "którego", "explanation": "'Dla którego' = für den/welchen (Genitiv Singular maskulin), im Deutschen oft 'warum/weshalb'. 'Powód' (Grund) ist maskulin → 'którego' (Gen.Sg.mask.). Diese Konstruktion wird im Polnischen häufiger als im Deutschen verwendet: statt 'warum' sagt man 'für welchen (Grund)'. Im Deutschen kann man 'der Grund, warum...' oder 'der Grund, aus dem...' sagen – beides wird im Polnischen zu 'dla którego'."}
        ]
    },
    {
        "key": "participles_advanced",
        "name": "Imiesłowy – Fortgeschritten (Partizipien – Fortgeschritten)",
        "description": "Vertiefte Übungen zu polnischen Partizipien – Adverbialpartizipien und ihre Verwendung",
        "icon": "text.word.spacing",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_ptca1", "question": "_____ książkę, zasnął.", "translation": "(Während er ein Buch las, schlief er ein.)", "options": ["Czytając", "Przeczytawszy", "Czytany", "Czytający"], "correct": "Czytając", "explanation": "'Czytając' ist das Adverbialpartizip der Gleichzeitigkeit (imperfektiv): Bildung mit '-ąc' vom Präsensstamm. Es drückt eine gleichzeitige Handlung aus: 'czytając książkę' = 'während er ein Buch las'. Im Deutschen: 'lesend' oder 'während er las'. Das polnische Adverbialpartizip ist häufiger als das deutsche Partizip I in adverbialer Funktion und klingt natürlicher."},
            {"id": "gp_ptca2", "question": "_____ obiad, poszedł na spacer.", "translation": "(Nachdem er das Mittagessen gegessen hatte, ging er spazieren.)", "options": ["Zjadłszy", "Jedząc", "Zjedzony", "Jedzący"], "correct": "Zjadłszy", "explanation": "'Zjadłszy' ist das Adverbialpartizip der Vorzeitigkeit (perfektiv): Bildung mit '-wszy/-łszy' vom Vergangenheitsstamm. Es drückt eine VOR der Haupthandlung abgeschlossene Handlung aus: 'zjadłszy obiad' = 'nachdem er gegessen hatte'. Im Deutschen: 'nachdem er gegessen hatte' oder 'gegessen habend' (sehr gehoben). Im Polnischen ist diese Form in der Literatur und gehobenen Sprache üblich."},
            {"id": "gp_ptca3", "question": "List _____ przez ojca leży na stole.", "translation": "(Der vom Vater geschriebene Brief liegt auf dem Tisch.)", "options": ["napisany", "napisana", "napisani", "piszący"], "correct": "napisany", "explanation": "'Napisany' ist das passive Partizip Perfekt (von 'napisać'): 'list napisany' = ein geschriebener Brief. Es dekliniert wie ein Adjektiv: mask. 'napisany', fem. 'napisana', sächl. 'napisane'. Im Deutschen: 'geschriebener Brief' – gleiche Struktur! Aber im Polnischen wird es auch als Prädikativ verwendet: 'List jest napisany' (Der Brief ist geschrieben), wo es im Genus mit dem Subjekt übereinstimmen muss."},
            {"id": "gp_ptca4", "question": "Kobieta _____ przy oknie to moja mama.", "translation": "(Die am Fenster sitzende Frau ist meine Mutter.)", "options": ["siedząca", "siedzący", "siedząc", "siadająca"], "correct": "siedząca", "explanation": "'Siedząca' ist das aktive Partizip Präsens (Adjektivpartizip, fem.): 'kobieta siedząca' = 'die sitzende Frau'. Bildung: Präsensstamm + '-ący/-ąca/-ące'. Es funktioniert wie ein Adjektiv und dekliniert in allen Kasus. Im Deutschen: 'die sitzende Frau' – identische Struktur! Im Polnischen wird diese Form häufiger als im Deutschen verwendet, besonders in Beschreibungen und formellen Texten."},
            {"id": "gp_ptca5", "question": "Ulica jest oświetlona _____ lampami.", "translation": "(Die Straße ist mit leuchtenden Lampen beleuchtet.)", "options": ["świecącymi", "świecące", "świecąc", "świeconym"], "correct": "świecącymi", "explanation": "'Świecącymi' = Instrumental Plural des aktiven Partizips 'świecący' (leuchtend). Im Instrumental nach 'lampami' (Lampen, Instr.Pl.). Das Partizip wird als Adjektiv dekliniert und stimmt in Kasus, Genus und Numerus mit dem Substantiv überein. Im Deutschen: 'leuchtenden Lampen' – auch hier stimmt das Partizip als Adjektiv mit dem Substantiv überein. Die Parallele ist offensichtlich."},
            {"id": "gp_ptca6", "question": "_____ do domu, zobaczyłem wypadek.", "translation": "(Nach Hause gehend/Als ich nach Hause ging, sah ich einen Unfall.)", "options": ["Wracając", "Wróciwszy", "Wracany", "Wracający"], "correct": "Wracając", "explanation": "'Wracając' (zurückkehrend/gehend) – Adverbialpartizip der Gleichzeitigkeit. Regel: das Subjekt des Partizips MUSS mit dem Subjekt des Hauptsatzes übereinstimmen! 'Wracając' und 'zobaczyłem' haben dasselbe Subjekt (ich). Im Deutschen: 'Als ich nach Hause ging' oder 'Nach Hause gehend'. Im Polnischen ist die Partizipkonstruktion kürzer und eleganter als ein Nebensatz."},
            {"id": "gp_ptca7", "question": "Dzieci _____ w parku są głośne.", "translation": "(Die im Park spielenden Kinder sind laut.)", "options": ["bawiące się", "bawiąc się", "bawione", "bawiący się"], "correct": "bawiące się", "explanation": "'Bawiące się' = aktives Partizip Präsens, Nom.Pl. nicht-mask.-personal (die spielenden). 'Dzieci' (Kinder) ist nicht-maskulin-personal → 'bawiące się'. Achtung: reflexive Partzipien behalten das 'się'! Im Plural gibt es: 'bawiący się' (mask.-personal), 'bawiące się' (alle anderen). Im Deutschen: 'die spielenden Kinder' – einfacher, weil keine Genus-Unterscheidung im Plural."},
            {"id": "gp_ptca8", "question": "_____ pracę, wziął prysznic.", "translation": "(Nachdem er die Arbeit beendet hatte, nahm er eine Dusche.)", "options": ["Skończywszy", "Kończąc", "Skończony", "Kończący"], "correct": "Skończywszy", "explanation": "'Skończywszy' – Adverbialpartizip der Vorzeitigkeit (perfektiv). Bildung: Vergangenheitsstamm + '-wszy' (nach Vokal) oder '-łszy' (nach Konsonant). 'Skończy-ć' → 'Skończy-wszy'. Diese Form wird hauptsächlich in geschriebener Sprache und Literatur verwendet. In der gesprochenen Sprache bevorzugt man: 'Kiedy skończył pracę...' (Als er die Arbeit beendet hatte...). Für Deutschsprachige ist der Nebensatz mit 'als/nachdem' natürlicher."},
            {"id": "gp_ptca9", "question": "Drzwi są _____.", "translation": "(Die Tür ist geschlossen.)", "options": ["zamknięte", "zamknięty", "zamkniętą", "zamykające"], "correct": "zamknięte", "explanation": "'Zamknięte' – passives Partizip Perfekt, sächl.Plural (geschlossen). 'Drzwi' (Tür) ist grammatisch Plural im Polnischen (wie 'pants' im Englischen) → 'zamknięte' (Plural nicht-mask.-personal). Vergleich: 'okno zamknięte' (geschlossenes Fenster, sächl.Sg.), 'drzwi zamknięte' (geschlossene Tür, Pl.). Im Deutschen: 'die Tür ist geschlossen' – kein Genus-/Numerusunterschied am Partizip."},
            {"id": "gp_ptca10", "question": "Film _____ wczoraj był świetny.", "translation": "(Der gestern gesehene Film war großartig.)", "options": ["obejrzany", "obejrzana", "oglądający", "oglądany"], "correct": "obejrzany", "explanation": "'Obejrzany' – passives Partizip Perfekt, mask.Sg. (gesehener/angeschauter). 'Film' ist maskulin → 'obejrzany'. Von 'obejrzeć' (ansehen, perfektiv). Unterschied: 'oglądany' (imperfektives Partizip: 'angeschaut werdend', wiederholte Handlung) vs. 'obejrzany' (perfektives Partizip: 'angeschaut habend', einmalig abgeschlossen). Der Aspekt des Partizips verrät, ob die Handlung einmalig oder wiederholbar ist."},
            {"id": "gp_ptca11", "question": "_____ na ulicy, spotkałem kolegę.", "translation": "(Auf der Straße stehend, traf ich einen Kollegen.)", "options": ["Stojąc", "Stawszy", "Stojący", "Stany"], "correct": "Stojąc", "explanation": "'Stojąc' – Adverbialpartizip der Gleichzeitigkeit von 'stać' (stehen): 'Stoj-ąc'. Es drückt gleichzeitige Handlungen aus: ich stand UND traf jemanden. Wichtig: das Subjekt muss identisch sein (ich stand, ich traf). Falsch wäre: 'Stojąc na ulicy, jechał autobus' (Stehend fuhr der Bus) – verschiedene Subjekte! Im Deutschen gilt dieselbe logische Regel, wird aber oft ignoriert."},
            {"id": "gp_ptca12", "question": "To jest dobrze _____ lekcja.", "translation": "(Das ist eine gut vorbereitete Stunde/Lektion.)", "options": ["przygotowana", "przygotowany", "przygotowując", "przygotowawszy"], "correct": "przygotowana", "explanation": "'Przygotowana' – passives Partizip Perfekt, fem.Sg. (vorbereitete). 'Lekcja' (Lektion/Stunde) ist feminin → 'przygotowana'. Das Adverb 'dobrze' (gut) modifiziert das Partizip. Im Deutschen: 'gut vorbereitete Stunde' – identische adjektivische Verwendung. Passive Partizipien als Adjektive sind in beiden Sprachen sehr produktiv und folgen dem gleichen Muster."},
            {"id": "gp_ptca13", "question": "Dzieci, _____ świeżym powietrzem, bawią się wesoło.", "translation": "(Die Kinder, die frische Luft atmen/genießen, spielen fröhlich.)", "options": ["ciesząc się", "ucieszone", "cieszące się", "ciesząca się"], "correct": "ciesząc się", "explanation": "'Ciesząc się' – Adverbialpartizip der Gleichzeitigkeit, reflexiv ('sich freuend'). Im Polnischen können Adverbialpartizipien mit 'się' (sich) verwendet werden: 'ciesząc się świeżym powietrzem' (sich an frischer Luft erfreuend). Achtung: 'ciesząc się' hat KEIN Genus/Numerus – es ist unveränderlich! Im Gegensatz zum Adjektivpartizip 'cieszący/ciesząca/cieszące się', das dekliniert wird."},
            {"id": "gp_ptca14", "question": "Nowo _____ dom wygląda pięknie.", "translation": "(Das neu gebaute Haus sieht schön aus.)", "options": ["zbudowany", "budowany", "budujący", "budując"], "correct": "zbudowany", "explanation": "'Zbudowany' – passives Partizip Perfekt von 'zbudować' (bauen, perfektiv): mask.Sg. 'Nowo zbudowany dom' = 'ein neu gebautes Haus'. Im Deutschen: 'neu gebautes'. Beide Sprachen verwenden passive perfektive Partizipien als Adjektive. Der Unterschied: im Polnischen markiert das Partizip klar den Aspekt ('zbudowany' = fertig gebaut vs. 'budowany' = im Bau befindlich)."},
            {"id": "gp_ptca15", "question": "Nie _____ odpowiedzi, wyszedł.", "translation": "(Keine Antwort erhalten habend/Da er keine Antwort erhielt, ging er.)", "options": ["otrzymawszy", "otrzymując", "otrzymany", "otrzymywać"], "correct": "otrzymawszy", "explanation": "'Nie otrzymawszy' – negiertes Adverbialpartizip der Vorzeitigkeit: 'nicht erhalten habend'. Partizipien können negiert werden: 'nie + Partizip'. Diese Konstruktion ist sehr formell/literarisch. In der Alltagssprache: 'Ponieważ nie otrzymał odpowiedzi, wyszedł' (Da er keine Antwort erhielt, ging er). Das Adverbialpartizip der Vorzeitigkeit ist in Geschäftsbriefen und akademischen Texten noch gebräuchlich."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")
