#!/usr/bin/env python3
"""Batch 9 FIXED: Word Order & Syntax (categories 48-52) - correct fill-in-the-blank format."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "word_order_basic",
        "name": "Szyk zdania (Wortstellung)",
        "description": "Grundlegende polnische Wortstellung – im Vergleich zur deutschen SVO/V2-Struktur",
        "icon": "text.alignleft",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_wob1", "question": "_____ czytam książkę.", "translation": "(Ich lese ein Buch.)", "options": ["Ja", "Mnie", "Mi", "Mój"], "correct": "Ja", "explanation": "Im Polnischen ist die Grundwortstellung SVO wie im Deutschen: Subjekt + Verb + Objekt. 'Ja czytam książkę' = 'Ich lese ein Buch'. Der große Unterschied: Im Polnischen kann das Pronomen 'ja' weggelassen werden, weil die Verbendung bereits die Person anzeigt. 'Czytam książkę' ist genauso korrekt und sogar natürlicher!"},
            {"id": "gp_wob2", "question": "Wczoraj _____ w kinie.", "translation": "(Gestern war ich im Kino.)", "options": ["byłem", "jestem", "będę", "bywam"], "correct": "byłem", "explanation": "Zeitangaben stehen oft am Satzanfang, genau wie im Deutschen. 'Wczoraj byłem w kinie' = 'Gestern war ich im Kino'. Der wichtige Unterschied: Im Deutschen muss das Verb an zweiter Stelle stehen (V2-Regel). Im Polnischen gibt es diese Regel nicht – das Verb kann flexibler positioniert werden. Das macht die polnische Wortstellung freier als die deutsche!"},
            {"id": "gp_wob3", "question": "_____ bawią się dzieci.", "translation": "(Im Park spielen die Kinder.)", "options": ["W parku", "Do parku", "Z parku", "Na parku"], "correct": "W parku", "explanation": "Ortsangaben können wie im Deutschen am Satzanfang stehen. 'W parku bawią się dzieci' betont den Ort. Beachten Sie: 'w parku' verwendet den Lokativ (w + Lok.), weil es einen Ort bezeichnet, an dem etwas stattfindet. Wenn man sich ZUM Park bewegt, wäre es 'do parku' (Genitiv). Diese Unterscheidung wo/wohin ist wie im Deutschen: im Park vs. in den Park."},
            {"id": "gp_wob4", "question": "To jest _____ brat.", "translation": "(Das ist mein Bruder.)", "options": ["mój", "moje", "moja", "moi"], "correct": "mój", "explanation": "'To jest mój brat' = 'Das ist mein Bruder'. Das Possessivpronomen 'mój' muss im Genus mit dem Substantiv übereinstimmen: mój brat (maskulin), moja siostra (feminin), moje dziecko (neutrum). Im Deutschen auch: mein Bruder, meine Schwester, mein Kind. Die Struktur 'To jest...' entspricht genau dem deutschen 'Das ist...' – eine der einfachsten Parallelen!"},
            {"id": "gp_wob5", "question": "Czy _____ polską kuchnię?", "translation": "(Magst du die polnische Küche?)", "options": ["lubisz", "lubię", "lubi", "lubią"], "correct": "lubisz", "explanation": "Ja/Nein-Fragen beginnen mit der Partikel 'czy'. Im Deutschen verwendet man Inversion (Verb an erster Stelle): 'Magst du...?' Im Polnischen bleibt die Wortstellung normal, man fügt einfach 'czy' hinzu! 'Czy lubisz polską kuchnię?' Das ist viel einfacher als die deutsche Inversion. 'Czy' hat keine wörtliche Übersetzung – es signalisiert nur, dass eine Frage kommt."},
            {"id": "gp_wob6", "question": "Kto to _____?", "translation": "(Wer hat das gemacht?)", "options": ["zrobił", "robił", "robi", "zrobi"], "correct": "zrobił", "explanation": "Fragewörter stehen am Satzanfang, wie im Deutschen: 'Kto' = 'Wer', 'Co' = 'Was', 'Gdzie' = 'Wo'. 'Kto to zrobił?' = 'Wer hat das gemacht?' Im Polnischen gibt es aber kein Hilfsverb 'hat' – die Vergangenheit wird direkt am Verb markiert: 'zrobił' (er hat gemacht, Perfektiv). Der Aspekt (dokonany/niedokonany) ersetzt teilweise die deutschen Zeitformen."},
            {"id": "gp_wob7", "question": "Bardzo _____ tę piosenkę.", "translation": "(Ich mag dieses Lied sehr.)", "options": ["lubię", "lubisz", "lubi", "lubią"], "correct": "lubię", "explanation": "Das Adverb 'bardzo' (sehr) steht im Polnischen VOR dem Verb: 'Bardzo lubię...' Im Deutschen steht 'sehr' oft am Satzende: 'Ich mag dieses Lied sehr'. Diese Platzierung der Adverbien ist ein wichtiger Unterschied! Im Polnischen: Adverb + Verb. Im Deutschen: Subjekt + Verb + Objekt + Adverb. Merken Sie sich: Im Polnischen kommen Adverbien näher zum Verb."},
            {"id": "gp_wob8", "question": "Jan lubi kawę, _____ Maria woli herbatę.", "translation": "(Jan mag Kaffee, aber Maria bevorzugt Tee.)", "options": ["ale", "i", "bo", "więc"], "correct": "ale", "explanation": "'Ale' = 'aber' – die wichtigste adversative Konjunktion. 'Jan lubi kawę, ale Maria woli herbatę'. Die Konjunktionen funktionieren ähnlich wie im Deutschen: 'i' = 'und', 'ale' = 'aber', 'lub/albo' = 'oder', 'bo' = 'weil' (umgangssprachlich). Der Unterschied: Nach 'weil' geht das Verb im Deutschen ans Ende, aber nach 'bo' im Polnischen bleibt die normale Wortstellung!"},
            {"id": "gp_wob9", "question": "_____ nie rozumiem.", "translation": "(Ich verstehe das nicht.)", "options": ["Tego", "To", "Ten", "Tym"], "correct": "Tego", "explanation": "Bei Verneinung wechselt das direkte Objekt in den Genitiv! 'Rozumiem to' (Akkusativ) → 'Nie rozumiem tego' (Genitiv). Das ist eine FUNDAMENTAL andere Regel als im Deutschen! In 'Ich verstehe das nicht' bleibt 'das' im Akkusativ. Im Polnischen verlangt die Verneinung den Genitiv. Diese Regel gilt für alle direkten Objekte nach verneinten Verben. Ein sehr wichtiges Muster zum Merken!"},
            {"id": "gp_wob10", "question": "Jemu to _____ .", "translation": "(Ihm habe ich das gegeben.)", "options": ["dałem", "daję", "dam", "dawałem"], "correct": "dałem", "explanation": "Im Polnischen kann man Satzteile frei umstellen, um Betonung auszudrücken. 'Jemu to dałem' betont 'jemu' (ihm) – er hat es bekommen, nicht jemand anderes. Die normale Reihenfolge wäre 'Dałem mu to'. Im Deutschen erreicht man den gleichen Effekt mit 'IHM habe ich das gegeben' und Inversion. Im Polnischen verschiebt man einfach das betonte Wort nach vorne, ohne die Verbstellung zu ändern."},
            {"id": "gp_wob11", "question": "Rano piję kawę, a _____ herbatę.", "translation": "(Morgens trinke ich Kaffee und abends Tee.)", "options": ["wieczorem", "wczoraj", "jutro", "dzisiaj"], "correct": "wieczorem", "explanation": "Ellipse: Das Verb 'piję' (trinke) wird im zweiten Teil weggelassen, weil es sich aus dem Kontext ergibt. 'Rano piję kawę, a wieczorem herbatę' = 'Morgens trinke ich Kaffee und abends Tee'. Beachten Sie 'a' statt 'i' – 'a' zeigt einen leichten Kontrast an (morgens vs. abends), während 'i' einfach verbindet. Diese Nuance gibt es in 'und' im Deutschen nicht!"},
            {"id": "gp_wob12", "question": "Dzisiaj _____ deszcz.", "translation": "(Heute regnet es.)", "options": ["pada", "padasz", "padają", "padał"], "correct": "pada", "explanation": "'Pada deszcz' = 'Es regnet'. Im Polnischen gibt es KEIN Wort für das deutsche Scheinsubjekt 'es'. 'Auf Polnisch 'regnet Regen' – direkt und ohne 'es'. Das gilt für alle Wetterausdrücke: 'Świeci słońce' (die Sonne scheint), 'Wieje wiatr' (der Wind weht). Im Deutschen braucht man immer 'es' als Platzhalter, im Polnischen ist das Subjekt das Wetterphänomen selbst."},
            {"id": "gp_wob13", "question": "On i ona _____ w Warszawie.", "translation": "(Er und sie wohnen in Warschau.)", "options": ["mieszkają", "mieszka", "mieszkam", "mieszkamy"], "correct": "mieszkają", "explanation": "Zusammengesetztes Subjekt: 'On i ona mieszkają' – zwei Personen der 3. Person = Pluralendung '-ają'. Genau wie im Deutschen: 'Er und sie wohnen'. Beachten Sie: 'w Warszawie' (in Warschau) – der Name steht im Lokativ mit veränderten Endungen. Städtenamen werden wie normale Substantive dekliniert! Warszawa → w Warszawie, Berlin → w Berlinie, Kraków → w Krakowie."},
            {"id": "gp_wob14", "question": "Szybko _____ ten chłopiec.", "translation": "(Schnell läuft dieser Junge.)", "options": ["biegnie", "biegnę", "biegniesz", "biegną"], "correct": "biegnie", "explanation": "Adverb am Satzanfang mit Subjekt am Ende – das ist eine emphatische Wortstellung zum Betonen der Geschwindigkeit. 'Szybko biegnie ten chłopiec' betont 'szybko' (schnell). Die neutrale Form wäre 'Ten chłopiec szybko biegnie'. Diese Flexibilität der Wortstellung gibt es im Deutschen auch teilweise, aber im Polnischen ist sie viel freier. Die Verbendung '-ie' zeigt die 3. Person Singular."},
            {"id": "gp_wob15", "question": "_____ lubię lody czekoladowe.", "translation": "(Ich mag Schokoladeneis am liebsten.)", "options": ["Najbardziej", "Bardziej", "Mniej", "Wcale"], "correct": "Najbardziej", "explanation": "'Najbardziej' = 'am meisten/am liebsten'. Im Polnischen bildet man den Superlativ von Adverbien mit 'naj-': bardzo → bardziej → najbardziej. Das entspricht dem deutschen 'sehr → mehr → am meisten'. 'Najbardziej lubię' = 'Ich mag am liebsten'. Beachten Sie: Das Adverb steht vor dem Verb, genau andersherum als im Deutschen, wo 'am liebsten' oft am Ende steht."}
        ]
    },
    {
        "key": "negation",
        "name": "Przeczenie (Verneinung)",
        "description": "Verneinung im Polnischen – doppelte Verneinung und Genitivregel nach Negation",
        "icon": "xmark.circle",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_neg1", "question": "_____ lubię kawy.", "translation": "(Ich mag keinen Kaffee.)", "options": ["Nie", "Tak", "Już", "Też"], "correct": "Nie", "explanation": "'Nie' steht IMMER direkt vor dem Verb – das ist die Grundregel der polnischen Verneinung. 'Nie lubię kawy' = 'Ich mag keinen Kaffee'. Beachten Sie: 'kawa' (Nominativ) wird zu 'kawy' (Genitiv) nach der Verneinung! Im Deutschen bleibt der Akkusativ: 'keinen Kaffee'. Im Polnischen wechselt das direkte Objekt bei Verneinung in den Genitiv. Das ist eine der wichtigsten Regeln!"},
            {"id": "gp_neg2", "question": "Nigdy _____ byłem w Polsce.", "translation": "(Ich war noch nie in Polen.)", "options": ["nie", "tak", "już", "też"], "correct": "nie", "explanation": "Doppelte Verneinung ist im Polnischen PFLICHT! 'Nigdy nie byłem' = wörtlich 'Niemals nicht war ich'. Im Deutschen wäre das ein Fehler ('Ich war nie nicht'), aber im Polnischen ist es grammatisch korrekt und ERFORDERLICH. 'Nigdy' (niemals) + 'nie' (nicht) – beides muss stehen! Das gilt für alle negativen Pronomen: 'nikt nie' (niemand nicht), 'nic nie' (nichts nicht), 'nigdzie nie' (nirgendwo nicht)."},
            {"id": "gp_neg3", "question": "Nikt nie _____.", "translation": "(Niemand ist gekommen.)", "options": ["przyszedł", "przyszli", "przychodzi", "przyjdzie"], "correct": "przyszedł", "explanation": "'Nikt nie przyszedł' – wieder doppelte Verneinung! 'Nikt' (niemand) braucht IMMER 'nie' vor dem Verb. Im Deutschen: 'Niemand ist gekommen' – nur ein Negationswort. Beachten Sie auch: 'przyszedł' ist maskulin Singular (er ist gekommen). Wenn es eine Frau wäre: 'Nikt nie przyszła'. Sogar 'niemand' hat im Polnischen ein grammatisches Geschlecht! Das gibt es im Deutschen nicht."},
            {"id": "gp_neg4", "question": "Nic nie _____.", "translation": "(Ich weiß nichts.)", "options": ["wiem", "wiesz", "wie", "wiedzą"], "correct": "wiem", "explanation": "'Nic nie wiem' = wörtlich 'Nichts nicht weiß-ich'. Das Polnische verlangt bei jedem negativen Pronomen ein zusätzliches 'nie'. Diese doppelte (oder sogar dreifache!) Verneinung ist einer der größten Unterschiede zum Deutschen. Man kann sogar sagen: 'Nigdy nikogo nigdzie nie widziałem' (Nie niemanden nirgendwo nicht habe-ich-gesehen). Vier Negationen – und grammatisch perfekt!"},
            {"id": "gp_neg5", "question": "To nie jest _____.", "translation": "(Das ist nicht wahr.)", "options": ["prawda", "prawdą", "prawdy", "prawd"], "correct": "prawda", "explanation": "Bei 'to nie jest + Substantiv' bleibt das Prädikativum im Nominativ: 'To nie jest prawda'. ACHTUNG: Das gilt nur für 'to jest/nie jest'! Bei anderen Verben wechselt das Objekt bei Verneinung in den Genitiv. Vergleichen Sie: 'Mam prawdę' → 'Nie mam prawdy' (Gen.). Aber: 'To jest prawda' → 'To nie jest prawda' (Nom. bleibt). Diese Ausnahme ist wichtig zu merken!"},
            {"id": "gp_neg6", "question": "Nie mam _____.", "translation": "(Ich habe keine Zeit.)", "options": ["czasu", "czas", "czasem", "czasie"], "correct": "czasu", "explanation": "'Nie mam czasu' – nach verneintem 'mieć' (haben) steht immer der Genitiv! 'Mam czas' (Akk.) → 'Nie mam czasu' (Gen.). Vergleich: 'Ich habe Zeit' → 'Ich habe keine Zeit' – im Deutschen bleibt der Akkusativ. Im Polnischen: Verneinung des Verbs → Objekt wechselt zum Genitiv. Das gilt für ALLE transitiven Verben: 'Widzę kota' → 'Nie widzę kota' (bleibt Gen., weil Akk. belebt = Gen.)."},
            {"id": "gp_neg7", "question": "Nie znam _____ tutaj.", "translation": "(Ich kenne hier niemanden.)", "options": ["nikogo", "ktoś", "kogoś", "wszyscy"], "correct": "nikogo", "explanation": "'Nikogo' = 'niemanden' im Genitiv. 'Nie znam nikogo' – doppelte Verneinung! Im Deutschen: 'Ich kenne niemanden' – ein Negationswort. Im Polnischen: 'nie' + 'nikogo'. 'Nikogo' ist die Genitiv/Akkusativ-Form von 'nikt'. Weil nach Verneinung der Genitiv steht, und bei belebten maskulinen Substantiven Akk. = Gen., funktioniert 'nikogo' hier perfekt. Die Kasus-Logik ist elegant, wenn auch komplex!"},
            {"id": "gp_neg8", "question": "Nie chcę ani kawy, _____ herbaty.", "translation": "(Ich möchte weder Kaffee noch Tee.)", "options": ["ani", "i", "ale", "lub"], "correct": "ani", "explanation": "'Ani...ani' = 'weder...noch'. 'Nie chcę ani kawy, ani herbaty' – beachten Sie drei Negationselemente: 'nie' + 'ani' + 'ani'! Im Deutschen: 'weder...noch' braucht kein extra 'nicht'. Im Polnischen steht 'nie' vor dem Verb UND 'ani' vor jedem aufgezählten Element. Auch hier: 'kawy' und 'herbaty' im Genitiv wegen der Verneinung (nicht Akkusativ 'kawę' und 'herbatę')."},
            {"id": "gp_neg9", "question": "_____ nie jestem zmęczony.", "translation": "(Ich bin überhaupt nicht müde.)", "options": ["Wcale", "Bardzo", "Trochę", "Zawsze"], "correct": "Wcale", "explanation": "'Wcale nie' = 'überhaupt nicht/gar nicht' – eine verstärkte Verneinung. 'Wcale nie jestem zmęczony' betont, dass man absolut nicht müde ist. Weitere Verstärkungen: 'w ogóle nie' (im Allgemeinen nicht), 'absolutnie nie' (absolut nicht), 'zupełnie nie' (völlig nicht). Diese Adverbien stehen vor 'nie', um die Verneinung zu intensivieren. Im Deutschen: 'überhaupt nicht', 'gar nicht', 'keineswegs'."},
            {"id": "gp_neg10", "question": "Jeszcze nie _____.", "translation": "(Ich bin noch nicht fertig.)", "options": ["skończyłem", "skończę", "kończę", "skończyłeś"], "correct": "skończyłem", "explanation": "'Jeszcze nie' = 'noch nicht'. 'Jeszcze nie skończyłem' = 'Ich habe noch nicht beendet'. Beachten Sie den perfektiven Aspekt: 'skończyłem' (ich habe beendet – abgeschlossen). Das Gegenstück 'już' (schon): 'Już skończyłem' = 'Ich habe schon beendet'. Die Paare 'jeszcze nie'/'już' sind wie 'noch nicht'/'schon' im Deutschen – sehr nützlich im Alltag!"},
            {"id": "gp_neg11", "question": "Już nie _____ w Berlinie.", "translation": "(Ich wohne nicht mehr in Berlin.)", "options": ["mieszkam", "mieszkasz", "mieszka", "mieszkamy"], "correct": "mieszkam", "explanation": "'Już nie' = 'nicht mehr'. 'Już nie mieszkam w Berlinie' = 'Ich wohne nicht mehr in Berlin'. Die Kombination 'już nie' drückt aus, dass ein Zustand aufgehört hat. Im Deutschen: 'nicht mehr'. Beachten Sie den Kontrast: 'Jeszcze nie' (noch nicht – etwas hat noch nicht angefangen) vs. 'Już nie' (nicht mehr – etwas hat aufgehört). Diese temporalen Verneinungen sind im Alltag unverzichtbar!"},
            {"id": "gp_neg12", "question": "Żaden student nie _____ egzaminu.", "translation": "(Kein Student hat die Prüfung bestanden.)", "options": ["zdał", "zdali", "zdaje", "zda"], "correct": "zdał", "explanation": "'Żaden' = 'kein' + 'nie' vor dem Verb – wieder doppelte Verneinung! 'Żaden student nie zdał egzaminu'. Im Deutschen reicht 'kein': 'Kein Student hat bestanden'. Im Polnischen: 'żaden' UND 'nie'. Beachten Sie auch: 'egzaminu' im Genitiv (nicht 'egzamin' im Akkusativ) wegen der Verneinung. Drei Merkmale: 1) żaden, 2) nie, 3) Genitiv statt Akkusativ."},
            {"id": "gp_neg13", "question": "Nie tylko mówi, ale też _____ po polsku.", "translation": "(Er spricht nicht nur, sondern schreibt auch Polnisch.)", "options": ["pisze", "piszę", "piszesz", "piszą"], "correct": "pisze", "explanation": "'Nie tylko...ale też' = 'nicht nur...sondern auch'. Hier ist 'nie' KEIN echtes Negationswort! Es ist Teil der zweiteiligen Konjunktion 'nie tylko...ale też'. Deshalb bleibt der Akkusativ erhalten (keine Genitivregel). Das ist eine wichtige Ausnahme: 'Nie tylko' verneint den Satz nicht wirklich, sondern drückt eine Erweiterung aus. Ähnlich wie im Deutschen: 'nicht nur' ist keine echte Verneinung."},
            {"id": "gp_neg14", "question": "Nigdzie nie mogę _____ kluczy.", "translation": "(Ich kann nirgendwo die Schlüssel finden.)", "options": ["znaleźć", "znajdować", "szukać", "widzieć"], "correct": "znaleźć", "explanation": "'Nigdzie nie mogę znaleźć kluczy' – dreifache Verneinung: 'nigdzie' (nirgendwo) + 'nie' + Genitiv 'kluczy' (statt Akk. 'klucze'). 'Znaleźć' (finden, perfektiv) vs. 'znajdować' (finden, imperfektiv) – hier perfektiv, weil es um das Ergebnis geht. 'Kluczy' im Genitiv Plural von 'klucz' (Schlüssel). Im Deutschen: 'Ich kann die Schlüssel nirgendwo finden' – nur ein Negationswort."},
            {"id": "gp_neg15", "question": "Nie ma go w _____.", "translation": "(Er ist nicht zu Hause.)", "options": ["domu", "dom", "domem", "domowi"], "correct": "domu", "explanation": "'Nie ma' = 'es gibt nicht' / 'ist nicht da'. 'Nie ma go w domu' = 'Er ist nicht zu Hause'. 'Nie ma' + Genitiv ist die Standardkonstruktion für Abwesenheit. 'Go' = Genitiv von 'on' (er). Im Deutschen: 'er ist nicht da'. Im Polnischen: 'ihn gibt-es-nicht' (Genitiv). 'W domu' = 'zu Hause' (im Lokativ). Diese Konstruktion 'nie ma + Gen.' ist extrem häufig im Alltag!"}
        ]
    },
    {
        "key": "questions",
        "name": "Pytania (Fragesätze)",
        "description": "Fragebildung im Polnischen – Ja/Nein-Fragen mit 'czy' und W-Fragen",
        "icon": "questionmark.circle",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_quest1", "question": "_____ mówisz po polsku?", "translation": "(Sprichst du Polnisch?)", "options": ["Czy", "Co", "Kto", "Jak"], "correct": "Czy", "explanation": "'Czy' ist die Fragepartikel für Ja/Nein-Fragen. Im Deutschen benutzt man Inversion: 'Sprichst du...?' Im Polnischen fügt man einfach 'czy' am Anfang hinzu und die Wortstellung bleibt gleich! 'Mówisz po polsku' (Aussage) → 'Czy mówisz po polsku?' (Frage). Das ist viel einfacher als im Deutschen. In der Umgangssprache kann man 'czy' sogar weglassen und nur die Intonation ändern."},
            {"id": "gp_quest2", "question": "_____ robisz?", "translation": "(Was machst du?)", "options": ["Co", "Kto", "Czy", "Jak"], "correct": "Co", "explanation": "'Co' = 'was' – eines der wichtigsten Fragewörter. 'Co robisz?' = 'Was machst du?' Die polnischen W-Fragewörter entsprechen den deutschen: 'co' = 'was', 'kto' = 'wer', 'gdzie' = 'wo', 'kiedy' = 'wann', 'jak' = 'wie', 'dlaczego' = 'warum'. Sie stehen am Satzanfang, genau wie im Deutschen. Der Unterschied: Im Polnischen folgt direkt das Verb, ohne Inversion des Subjekts."},
            {"id": "gp_quest3", "question": "_____ mieszkasz?", "translation": "(Wo wohnst du?)", "options": ["Gdzie", "Dokąd", "Skąd", "Kiedy"], "correct": "Gdzie", "explanation": "'Gdzie' = 'wo' (Ort/Position). ACHTUNG: Anders als im Deutschen unterscheidet das Polnische drei Richtungsfragen: 'Gdzie?' (wo? – Position), 'Dokąd?' (wohin? – Richtung hin), 'Skąd?' (woher? – Richtung her). Im Deutschen gibt es auch 'wo/wohin/woher', aber umgangssprachlich wird oft nur 'wo' benutzt. Im Polnischen ist diese Unterscheidung wichtiger und wird strenger eingehalten."},
            {"id": "gp_quest4", "question": "_____ przyjeżdżasz?", "translation": "(Wann kommst du?)", "options": ["Kiedy", "Gdzie", "Jak", "Ile"], "correct": "Kiedy", "explanation": "'Kiedy' = 'wann' – Frage nach dem Zeitpunkt. 'Kiedy przyjeżdżasz?' = 'Wann kommst du an?' Beachten Sie: 'przyjeżdżać' (ankommen, imperfektiv – regelmäßig/wiederholt) vs. 'przyjechać' (ankommen, perfektiv – einmalig). Im Deutschen gibt es diesen Unterschied nicht. 'Kiedy przyjedziesz?' (perfektiv, Futur) = 'Wann kommst du an?' (einmalig in der Zukunft). Der Aspekt ändert die Bedeutung!"},
            {"id": "gp_quest5", "question": "_____ się spóźniłeś?", "translation": "(Warum hast du dich verspätet?)", "options": ["Dlaczego", "Kiedy", "Gdzie", "Czy"], "correct": "Dlaczego", "explanation": "'Dlaczego' = 'warum' – Frage nach dem Grund. 'Dlaczego się spóźniłeś?' Beachten Sie: 'spóźnić się' ist ein reflexives Verb – 'się' kann flexibel positioniert werden. Man kann auch sagen 'Dlaczego spóźniłeś się?' Die Position von 'się' ist im Polnischen sehr flexibel, aber es steht nie am Satzanfang und selten am Satzende. Im Deutschen ist 'sich' auch flexibel, aber weniger als 'się'."},
            {"id": "gp_quest6", "question": "_____ się nazywasz?", "translation": "(Wie heißt du?)", "options": ["Jak", "Co", "Kto", "Czy"], "correct": "Jak", "explanation": "'Jak się nazywasz?' = 'Wie heißt du?' – wörtlich 'Wie nennst du dich?' Ein reflexives Verb wie 'sich nennen'. Man kann auch fragen: 'Jak masz na imię?' (Wie ist dein Vorname? – informell). Im formellen Kontext: 'Jak się Pan/Pani nazywa?' (Wie heißen Sie? – mit der Höflichkeitsform). Die Antwort: 'Nazywam się...' = 'Ich heiße...' (wörtlich: Ich nenne mich...)."},
            {"id": "gp_quest7", "question": "_____ masz lat?", "translation": "(Wie alt bist du?)", "options": ["Ile", "Jak", "Co", "Kiedy"], "correct": "Ile", "explanation": "'Ile masz lat?' = wörtlich 'Wie viele hast du Jahre?' Im Deutschen: 'Wie alt bist du?' Im Polnischen 'hat man Jahre' wie im Deutschen man 'Jahre alt ist'. 'Ile' = 'wie viele' – Mengenfrage. Antwort: 'Mam dwadzieścia pięć lat' (Ich habe 25 Jahre). 'Lat' ist der Genitiv Plural von 'rok' (Jahr). Die Konstruktion ist dem Deutschen ähnlich, nur mit 'haben' statt 'sein'."},
            {"id": "gp_quest8", "question": "_____ autobus jedzie do centrum?", "translation": "(Welcher Bus fährt ins Zentrum?)", "options": ["Który", "Jaki", "Ile", "Czy"], "correct": "Który", "explanation": "'Który' = 'welcher' – Auswahlfrage aus einer bekannten Menge. 'Który autobus?' = 'Welcher Bus?' Unterschied zu 'jaki' (was für ein): 'Jaki autobus?' fragt nach der Art/Beschreibung, 'Który autobus?' nach der spezifischen Auswahl. Im Deutschen: 'welcher' vs. 'was für ein'. 'Który' dekliniert wie ein Adjektiv: który (m.), która (f.), które (n.), którzy/które (Pl.)."},
            {"id": "gp_quest9", "question": "_____ to jest samochód?", "translation": "(Wessen Auto ist das?)", "options": ["Czyj", "Jaki", "Który", "Co"], "correct": "Czyj", "explanation": "'Czyj' = 'wessen' – Frage nach dem Besitz. 'Czyj to jest samochód?' = 'Wessen Auto ist das?' 'Czyj' dekliniert nach Genus: czyj samochód (m.), czyja książka (f.), czyje dziecko (n.). Im Deutschen: 'wessen' ändert sich nicht. Die Antwort: 'To jest samochód mojego brata' (Gen.) = 'Das ist das Auto meines Bruders'. Besitz wird im Polnischen durch den Genitiv ausgedrückt."},
            {"id": "gp_quest10", "question": "_____ jedziesz?", "translation": "(Wohin fährst du?)", "options": ["Dokąd", "Gdzie", "Skąd", "Jak"], "correct": "Dokąd", "explanation": "'Dokąd' = 'wohin' – Frage nach der Richtung/dem Ziel. 'Dokąd jedziesz?' = 'Wohin fährst du?' Unterschied: 'Gdzie jedziesz?' wäre umgangssprachlich akzeptabel, aber grammatisch korrekt ist 'dokąd' für die Richtung. 'Gdzie' = wo (statisch), 'Dokąd' = wohin (Bewegung hin), 'Skąd' = woher (Bewegung her). Diese dreifache Unterscheidung ist im Polnischen strenger als im Deutschen."},
            {"id": "gp_quest11", "question": "_____ pochodzisz?", "translation": "(Woher kommst du?)", "options": ["Skąd", "Dokąd", "Gdzie", "Kiedy"], "correct": "Skąd", "explanation": "'Skąd' = 'woher' – Frage nach der Herkunft. 'Skąd pochodzisz?' = 'Woher kommst du?' / 'Woher stammst du?' 'Pochodzić' = 'stammen/herkommen'. Antwort: 'Pochodzę z Niemiec' (Ich komme aus Deutschland) mit 'z' + Genitiv. 'Z Niemiec' – 'Niemcy' (Deutschland, Pl.) → Genitiv Plural 'Niemiec'. Ländernamen haben oft unregelmäße Genitivformen."},
            {"id": "gp_quest12", "question": "_____ co to kupiłeś?", "translation": "(Wozu hast du das gekauft?)", "options": ["Po", "Na", "Do", "Za"], "correct": "Po", "explanation": "'Po co' = 'wozu/wofür' – Frage nach dem Zweck. 'Po co to kupiłeś?' = 'Wozu hast du das gekauft?' Weitere Zweck-Fragen: 'Do czego to służy?' (Wozu dient das?), 'Na co to potrzebne?' (Wofür ist das nötig?). Jede Präposition hat eine andere Nuance: 'po co' (allgemeiner Zweck), 'do czego' (Funktion), 'na co' (spezifischer Bedarf). Diese Feinheiten lernt man mit der Zeit!"},
            {"id": "gp_quest13", "question": "Jak _____ ćwiczysz?", "translation": "(Wie oft übst du?)", "options": ["często", "dużo", "dobrze", "szybko"], "correct": "często", "explanation": "'Jak często' = 'wie oft' – Frage nach der Häufigkeit. 'Jak często ćwiczysz?' = 'Wie oft übst du?' Typische Antworten: 'codziennie' (täglich), 'co tydzień' (wöchentlich), 'dwa razy w tygodniu' (zweimal pro Woche), 'rzadko' (selten), 'nigdy' (nie). 'Jak' kombiniert mit vielen Adverbien: 'jak długo?' (wie lange?), 'jak daleko?' (wie weit?), 'jak dużo?' (wie viel?)."},
            {"id": "gp_quest14", "question": "Prawda, _____ to jest piękne?", "translation": "(Es ist schön, nicht wahr?)", "options": ["że", "co", "jak", "czy"], "correct": "że", "explanation": "'Prawda, że...?' = 'Nicht wahr?' / 'Stimmt's?' – eine Bestätigungsfrage (tag question). Im Polnischen ist das viel einfacher als im Deutschen! Man fügt einfach 'prawda?' am Satzende oder 'Prawda, że...?' am Anfang hinzu. Im Deutschen muss man je nach Verb die richtige tag question bilden: '...nicht wahr?', '...oder?', '...stimmt's?' Im Polnischen immer nur: 'prawda?'"},
            {"id": "gp_quest15", "question": "_____ to znaczy?", "translation": "(Was bedeutet das?)", "options": ["Co", "Jak", "Kto", "Czy"], "correct": "Co", "explanation": "'Co to znaczy?' = 'Was bedeutet das?' – eine Standardfrage beim Sprachenlernen! 'Znaczyć' = 'bedeuten'. Alternative: 'Co to jest?' (Was ist das?). Für Definitionen: 'Co znaczy słowo...?' (Was bedeutet das Wort...?). Im formellen Kontext: 'Co Pan/Pani ma na myśli?' (Was meinen Sie?). Diese Fragen sind unverzichtbar für jeden Lerner – benutzen Sie sie oft!"}
        ]
    },
    {
        "key": "subordinate_clauses",
        "name": "Zdania podrzędne (Nebensätze)",
        "description": "Nebensätze im Polnischen – ohne Verbendstellung wie im Deutschen!",
        "icon": "arrow.turn.down.right",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_sub1", "question": "Wiem, _____ on mówi po polsku.", "translation": "(Ich weiß, dass er Polnisch spricht.)", "options": ["że", "co", "jak", "czy"], "correct": "że", "explanation": "'Że' = 'dass' – die wichtigste Nebensatz-Konjunktion. 'Wiem, że on mówi po polsku'. DER GRÖSSTE UNTERSCHIED: Im Deutschen geht das Verb ans Ende ('...dass er Polnisch spricht'), im Polnischen bleibt die normale Wortstellung! Kein Verb am Ende! Das macht polnische Nebensätze viel einfacher als deutsche. Sie fügen einfach 'że' ein und behalten den Rest wie im Hauptsatz."},
            {"id": "gp_sub2", "question": "Myślę, że to dobry _____.", "translation": "(Ich denke, dass das eine gute Idee ist.)", "options": ["pomysł", "pomysłem", "pomysłu", "pomysłowi"], "correct": "pomysł", "explanation": "'To dobry pomysł' – 'pomysł' steht im Nominativ als Prädikativum nach 'to jest' (das 'jest' kann wegfallen). Im Deutschen: 'Das ist eine gute Idee'. Im Polnischen: Nach 'to jest' steht das Substantiv im Nominativ (oder Instrumental in formellerer Sprache). 'To dobry pomysł' (Nom.) oder 'To jest dobrym pomysłem' (Instr.) – beides korrekt, aber Nominativ ist im Alltag häufiger."},
            {"id": "gp_sub3", "question": "Kiedy _____ do domu, zadzwonię.", "translation": "(Wenn ich nach Hause komme, rufe ich an.)", "options": ["przyjdę", "przychodzę", "przyszedłem", "przychodziłem"], "correct": "przyjdę", "explanation": "'Kiedy przyjdę' – perfektives Futur! 'Kiedy' = 'wenn/als'. Im Polnischen markiert der Aspekt den Zeitbezug: 'przyjdę' (perfektiv = einmalig in der Zukunft). Im Deutschen braucht man Präsens für die Zukunft nach 'wenn'. Im Polnischen verwendet man tatsächlich eine Futurform! 'Przyjdę' = 'ich werde kommen/ankommen' (perfektiv). Die Verbendung '-ę' zeigt 1. Person Singular Futur."},
            {"id": "gp_sub4", "question": "_____ będzie ładna pogoda, pójdziemy na spacer.", "translation": "(Wenn das Wetter schön ist, gehen wir spazieren.)", "options": ["Jeśli", "Że", "Bo", "Więc"], "correct": "Jeśli", "explanation": "'Jeśli' = 'wenn/falls' (konditional). Im Polnischen unterscheidet man: 'kiedy' (wenn/als – zeitlich) vs. 'jeśli/jeżeli' (wenn/falls – Bedingung). Im Deutschen ist 'wenn' doppeldeutig (temporal und konditional). Das Polnische ist hier präziser! 'Jeśli' für Bedingungen, 'kiedy' für Zeitpunkte. 'Jeżeli' ist formeller als 'jeśli'. Beide sind korrekt und austauschbar."},
            {"id": "gp_sub5", "question": "_____ padał deszcz, zostaliśmy w domu.", "translation": "(Weil es geregnet hat, sind wir zu Hause geblieben.)", "options": ["Ponieważ", "Ale", "I", "Więc"], "correct": "Ponieważ", "explanation": "'Ponieważ' = 'weil/da' (kausal). 'Ponieważ padał deszcz, zostaliśmy w domu'. Im Deutschen schickt 'weil' das Verb ans Ende – im Polnischen bleibt die Wortstellung normal! Synonyme: 'bo' (umgangssprachlich, wie 'weil' in der Umgangssprache), 'ponieważ' (formell), 'gdyż' (literarisch), 'dlatego że' (deswegen weil). 'Bo' ist am häufigsten in der Alltagssprache."},
            {"id": "gp_sub6", "question": "Chociaż jest zmęczony, _____ pracuje.", "translation": "(Obwohl er müde ist, arbeitet er weiter.)", "options": ["nadal", "nigdy", "wcale", "jeszcze"], "correct": "nadal", "explanation": "'Chociaż' = 'obwohl' (konzessiv). 'Nadal' = 'weiterhin/immer noch'. 'Chociaż jest zmęczony, nadal pracuje' = 'Obwohl er müde ist, arbeitet er weiterhin'. Synonyme für 'chociaż': 'mimo że' (trotz dass), 'pomimo że' (trotzdem dass), 'choć' (Kurzform). Im Deutschen steht nach 'obwohl' das Verb am Ende – im Polnischen nicht! Die polnische Nebensatzstruktur ist in dieser Hinsicht einfacher."},
            {"id": "gp_sub7", "question": "Mężczyzna, _____ tam stoi, jest moim ojcem.", "translation": "(Der Mann, der dort steht, ist mein Vater.)", "options": ["który", "która", "które", "którzy"], "correct": "który", "explanation": "'Który' = 'der/welcher' – Relativpronomen. Es muss mit dem Bezugswort in Genus und Numerus übereinstimmen: 'mężczyzna' (maskulin) → 'który'. Im Deutschen: 'der Mann, der...' Im Polnischen: 'mężczyzna, który...' Der Kasus des Relativpronomens hängt von seiner Funktion im Nebensatz ab: hier Nominativ (Subjekt). 'Która' für feminin, 'które' für neutrum, 'którzy' für maskulin-personal Plural."},
            {"id": "gp_sub8", "question": "Kobieta, _____ widziałeś, jest lekarką.", "translation": "(Die Frau, die du gesehen hast, ist Ärztin.)", "options": ["którą", "która", "które", "który"], "correct": "którą", "explanation": "'Którą' = Akkusativ feminin des Relativpronomens. 'Kobieta, którą widziałeś' – 'którą' steht im Akkusativ, weil es das Objekt von 'widziałeś' (du hast gesehen) ist. Im Deutschen: 'die Frau, die du gesehen hast' – 'die' kann Nominativ oder Akkusativ sein. Im Polnischen ist der Kasus immer eindeutig durch die Endung: którA (Nom.f.) vs. którĄ (Akk.f.). Das polnische Kasussystem macht Relativsätze präziser!"},
            {"id": "gp_sub9", "question": "_____ wyjdziesz, zamknij okno.", "translation": "(Bevor du gehst, schließ das Fenster.)", "options": ["Zanim", "Kiedy", "Że", "Bo"], "correct": "Zanim", "explanation": "'Zanim' = 'bevor' – temporale Konjunktion. 'Zanim wyjdziesz, zamknij okno'. Beachten Sie: 'wyjdziesz' (perfektiv Futur, 2. Pers.) – im Polnischen Futur nach 'zanim', im Deutschen Präsens nach 'bevor'. Weitere temporale Konjunktionen: 'odkąd' (seit/seitdem), 'dopóki' (solange), 'gdy' (als/wenn), 'jak tylko' (sobald). Jede hat ihre eigene Zeitbedeutung."},
            {"id": "gp_sub10", "question": "Żeby zdać egzamin, musisz dużo się _____.", "translation": "(Um die Prüfung zu bestehen, musst du viel lernen.)", "options": ["uczyć", "uczysz", "uczę", "uczyłem"], "correct": "uczyć", "explanation": "'Żeby' = 'um...zu' (Finalsatz). 'Żeby zdać egzamin' = 'Um die Prüfung zu bestehen'. Im Deutschen: 'um...zu' + Infinitiv. Im Polnischen: 'żeby' + konjugiertes Verb (wenn anderes Subjekt) ODER 'żeby' + Infinitiv (wenn gleiches Subjekt). 'Musisz się uczyć' – 'uczyć się' = 'lernen' (reflexiv). 'Się' steht hier vor dem Infinitiv. 'Żeby' ist vielseitig: Zweck, Wunsch, Aufforderung."},
            {"id": "gp_sub11", "question": "Im więcej czytam, _____ więcej rozumiem.", "translation": "(Je mehr ich lese, desto mehr verstehe ich.)", "options": ["tym", "tak", "ten", "to"], "correct": "tym", "explanation": "'Im...tym' = 'je...desto' – proportionaler Vergleich. 'Im więcej czytam, tym więcej rozumiem'. Die Struktur ist dem Deutschen sehr ähnlich: 'je mehr...desto mehr'. 'Im' leitet den Bedingungsteil ein, 'tym' den Resultatsteil. Beide werden mit dem Komparativ verwendet: 'Im szybciej biegasz, tym szybciej dotrzesz' (Je schneller du läufst, desto schneller kommst du an)."},
            {"id": "gp_sub12", "question": "Nie wiem, _____ on przyjdzie.", "translation": "(Ich weiß nicht, ob er kommt.)", "options": ["czy", "że", "co", "jak"], "correct": "czy", "explanation": "'Czy' = 'ob' in indirekten Fragen. 'Nie wiem, czy on przyjdzie' = 'Ich weiß nicht, ob er kommt'. 'Czy' hat also ZWEI Funktionen: 1) Fragepartikel in direkten Fragen ('Czy lubisz...?'), 2) 'ob' in indirekten Fragen. Im Deutschen: direkte Frage = Inversion, indirekte Frage = 'ob' + Verb am Ende. Im Polnischen: in beiden Fällen 'czy' + normale Wortstellung. Viel einfacher!"},
            {"id": "gp_sub13", "question": "Powiedział, _____ przyszedł wcześniej.", "translation": "(Er sagte, ich solle früher kommen.)", "options": ["żebym", "żeby", "że", "bo"], "correct": "żebym", "explanation": "'Żebym' = 'dass ich soll/solle' – Aufforderung in der indirekten Rede. 'Żeby' verschmilzt mit den Personalendungen: żebym (dass ich), żebyś (dass du), żeby (dass er/sie), żebyśmy (dass wir), żebyście (dass ihr). Das ist ein polnisches Unikat! Es drückt Wunsch, Aufforderung oder Zweck aus. Im Deutschen braucht man 'dass...soll' oder Konjunktiv. Im Polnischen ist es ein einziges Wort!"},
            {"id": "gp_sub14", "question": "Zadzwonię, jak tylko _____ do domu.", "translation": "(Ich rufe an, sobald ich nach Hause komme.)", "options": ["wrócę", "wracam", "wróciłem", "wracałem"], "correct": "wrócę", "explanation": "'Jak tylko' = 'sobald' – temporale Konjunktion. 'Wrócę' = perfektives Futur von 'wrócić' (zurückkehren). Im Polnischen verwendet man nach 'jak tylko' das perfektive Futur – im Deutschen steht Präsens: 'sobald ich zurückkomme'. Der perfektive Aspekt betont den Abschluss der Handlung: 'wrócę' = ich werde zurückgekehrt sein. Das imperfektive 'wracam' würde 'ich bin gerade auf dem Rückweg' bedeuten."},
            {"id": "gp_sub15", "question": "Chociaż pada, _____ pójdziemy na spacer.", "translation": "(Obwohl es regnet, werden wir trotzdem spazieren gehen.)", "options": ["i tak", "ale nie", "więc nie", "bo nie"], "correct": "i tak", "explanation": "'I tak' = 'trotzdem/sowieso' – bekräftigt die Handlung trotz des Hindernisses. 'Chociaż pada, i tak pójdziemy' = 'Obwohl es regnet, gehen wir trotzdem'. 'I tak' ist eine feste Wendung und sehr häufig im Alltag. Synonyme: 'mimo to' (trotzdem), 'jednak' (dennoch). Im Deutschen: 'trotzdem', 'dennoch', 'nichtsdestotrotz'. Im Polnischen ist 'i tak' das umgangssprachlichste und häufigste."}
        ]
    },
    {
        "key": "conjunctions",
        "name": "Spójniki (Konjunktionen)",
        "description": "Koordinierende und subordinierende Konjunktionen im Polnischen",
        "icon": "link",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_conj1", "question": "Lubię kawę _____ herbatę.", "translation": "(Ich mag Kaffee und Tee.)", "options": ["i", "ale", "lub", "bo"], "correct": "i", "explanation": "'I' = 'und' – die häufigste koordinierende Konjunktion. 'Lubię kawę i herbatę' = 'Ich mag Kaffee und Tee'. Im Polnischen gibt es auch 'oraz' als formelleres 'und'. Unterschied: 'i' für alltägliche Aufzählungen, 'oraz' für formelle Texte und Dokumente. Wie im Deutschen hat 'und/i' keine Auswirkung auf die Wortstellung – der nächste Satzteil behält die normale Struktur."},
            {"id": "gp_conj2", "question": "Chcę iść, _____ nie mogę.", "translation": "(Ich will gehen, aber ich kann nicht.)", "options": ["ale", "i", "bo", "więc"], "correct": "ale", "explanation": "'Ale' = 'aber' – adversative Konjunktion. 'Chcę iść, ale nie mogę'. Wie im Deutschen drückt 'ale' einen Gegensatz aus. Subtypen im Polnischen: 'ale' (aber – allgemein), 'lecz' (aber/doch – literarisch), 'jednak' (jedoch – etwas formeller), 'natomiast' (hingegen – kontrastiv). Im Alltag dominiert 'ale'. Wortstellung bleibt nach 'ale' normal – kein Verb am Ende wie bei deutschen Nebensätzen."},
            {"id": "gp_conj3", "question": "Zostanę w domu _____ pójdę na spacer.", "translation": "(Ich bleibe zu Hause oder gehe spazieren.)", "options": ["lub", "i", "ale", "bo"], "correct": "lub", "explanation": "'Lub' = 'oder' (formeller), 'albo' = 'oder' (alltäglich). 'Zostanę w domu lub pójdę na spacer'. Der Unterschied: 'albo' ist die alltägliche Variante, 'lub' etwas formeller. Für 'entweder...oder': 'albo...albo...' Im Deutschen: 'entweder...oder'. Für 'weder...noch': 'ani...ani' (mit obligatorischer doppelter Verneinung!). Die Registerunterschiede sind im Polnischen ausgeprägt."},
            {"id": "gp_conj4", "question": "Jest mądry, _____ przy tym skromny.", "translation": "(Er ist klug und dabei bescheiden.)", "options": ["a", "i", "ale", "bo"], "correct": "a", "explanation": "'A' – eine besondere polnische Konjunktion ohne direkte deutsche Entsprechung! Sie steht zwischen 'und' und 'aber' – sie verbindet, deutet aber einen leichten Kontrast an. 'Jest mądry, a przy tym skromny' = 'Er ist klug, und dabei bescheiden'. Im Deutschen nutzt man 'und dabei', 'und gleichzeitig'. 'A' ist subtiler als 'ale' (aber) und kontrastiver als 'i' (und). Diese Nuance ist typisch polnisch!"},
            {"id": "gp_conj5", "question": "_____ ty, albo ja.", "translation": "(Entweder du oder ich.)", "options": ["Albo", "Ani", "I", "Ale"], "correct": "Albo", "explanation": "'Albo...albo' = 'entweder...oder'. 'Albo ty, albo ja' = 'Entweder du oder ich'. Im Polnischen wird 'albo' wiederholt, im Deutschen 'entweder...oder' (zwei verschiedene Wörter). Beachten Sie: 'lub' funktioniert nicht doppelt (*'lub...lub'). Für die exklusive Alternative verwendet man immer 'albo...albo'. In der Umgangssprache reicht auch ein einfaches 'albo': 'Ty albo ja' = 'Du oder ich'."},
            {"id": "gp_conj6", "question": "Ani nie czytam, _____ nie piszę.", "translation": "(Ich lese weder noch schreibe ich.)", "options": ["ani", "albo", "lub", "ale"], "correct": "ani", "explanation": "'Ani...ani' = 'weder...noch'. 'Ani nie czytam, ani nie piszę'. ACHTUNG: Im Polnischen steht vor JEDEM Verb ein 'nie'! 'Ani nie...ani nie...' – doppelte Verneinung in jedem Glied! Im Deutschen: 'weder...noch' ohne extra 'nicht'. Das ist ein häufiger Fehler für Deutsche: Sie vergessen das 'nie' nach 'ani'. Merken Sie sich: 'ani' + 'nie' gehören immer zusammen!"},
            {"id": "gp_conj7", "question": "_____ co robimy?", "translation": "(Also was machen wir?)", "options": ["Więc", "Bo", "Ale", "Że"], "correct": "Więc", "explanation": "'Więc' = 'also/so' – konsekutive Konjunktion (Schlussfolgerung). 'Więc co robimy?' = 'Also was machen wir?' Synonyme: 'zatem' (formeller), 'wobec tego' (angesichts dessen – sehr formell). In der Umgangssprache: 'no i co?' (und jetzt?), 'to co?' (was dann?). 'Więc' ist die neutralste Form und funktioniert in allen Registern. Es steht immer am Satzanfang, wie 'also' im Deutschen."},
            {"id": "gp_conj8", "question": "_____ nie przyszedłem na czas.", "translation": "(Deshalb bin ich nicht pünktlich gekommen.)", "options": ["Dlatego", "Więc", "Bo", "Że"], "correct": "Dlatego", "explanation": "'Dlatego' = 'deshalb/darum' – kausale Schlussfolgerung. 'Dlatego nie przyszedłem na czas' = 'Deshalb bin ich nicht pünktlich gekommen'. Unterschied: 'dlatego' (deshalb – Folge), 'dlatego że' (weil – Grund). 'Dlatego nie przyszedłem' = 'Deshalb kam ich nicht' (Folge). 'Nie przyszedłem, dlatego że padało' = 'Ich kam nicht, weil es regnete' (Grund). Ein Wort, zwei Funktionen mit 'że'!"},
            {"id": "gp_conj9", "question": "Zarówno Jan, _____ i Maria przyszli.", "translation": "(Sowohl Jan als auch Maria sind gekommen.)", "options": ["jak", "ale", "lub", "ani"], "correct": "jak", "explanation": "'Zarówno...jak i' = 'sowohl...als auch'. 'Zarówno Jan, jak i Maria przyszli'. Beachten Sie: 'przyszli' steht im maskulin-personalen Plural, weil mindestens eine männliche Person dabei ist (Jan). Wenn beide Frauen wären: 'przyszły'. Im Deutschen: 'Sowohl Jan als auch Maria sind gekommen' – kein Genusunterschied im Plural. Das polnische Pluralsystem unterscheidet maskulin-personal von allen anderen!"},
            {"id": "gp_conj10", "question": "Mimo _____ padało, wyszliśmy.", "translation": "(Obwohl es geregnet hat, sind wir rausgegangen.)", "options": ["że", "to", "bo", "więc"], "correct": "że", "explanation": "'Mimo że' = 'obwohl/trotzdem dass' – konzessive Konjunktion. 'Mimo że padało, wyszliśmy'. Varianten: 'chociaż' (obwohl), 'pomimo że' (obwohl – formeller), 'mimo to' (trotzdem – als Adverb). Im Deutschen geht nach 'obwohl' das Verb ans Ende. Im Polnischen bleibt die Wortstellung nach 'mimo że' normal – ein großer Vorteil! 'Padało' (es regnete) – beachten Sie: kein 'es' im Polnischen."},
            {"id": "gp_conj11", "question": "_____ żyję, będę walczyć.", "translation": "(Solange ich lebe, werde ich kämpfen.)", "options": ["Dopóki", "Kiedy", "Jeśli", "Zanim"], "correct": "Dopóki", "explanation": "'Dopóki' = 'solange' – temporale Konjunktion der Dauer. 'Dopóki żyję, będę walczyć' = 'Solange ich lebe, werde ich kämpfen'. Variante: 'dopóty...dopóki' (so lange...wie). Verwechslungsgefahr: 'dopóki' (solange – Dauer) vs. 'dopóki nie' (bis – Endpunkt). 'Dopóki nie przyjedzie' = 'Bis er ankommt'. Das 'nie' ändert die Bedeutung von 'solange' zu 'bis' – ein wichtiger Unterschied!"},
            {"id": "gp_conj12", "question": "Podczas _____ on pracuje, ona odpoczywa.", "translation": "(Während er arbeitet, ruht sie sich aus.)", "options": ["gdy", "że", "bo", "więc"], "correct": "gdy", "explanation": "'Podczas gdy' = 'während' – gleichzeitige oder kontrastierende Handlungen. 'Podczas gdy on pracuje, ona odpoczywa'. Wie im Deutschen hat 'während' zwei Bedeutungen: zeitlich (gleichzeitig) und adversativ (Gegensatz). Kürzere Variante: 'gdy' allein kann auch 'während/als/wenn' bedeuten. 'Gdy' ist ein Allzweck-Temporalwort und eines der häufigsten in der polnischen Sprache."},
            {"id": "gp_conj13", "question": "Nie przyszedł, _____ jest chory.", "translation": "(Er ist nicht gekommen, weil er krank ist.)", "options": ["bo", "ale", "i", "więc"], "correct": "bo", "explanation": "'Bo' = 'weil' (umgangssprachlich) – der häufigste kausale Konnektor im Alltag! 'Nie przyszedł, bo jest chory'. 'Bo' ist kürzer und häufiger als 'ponieważ' oder 'gdyż'. WICHTIG: Im Deutschen schickt 'weil' formal das Verb ans Ende (in der Umgangssprache oft nicht). Im Polnischen hat 'bo' KEINEN Einfluss auf die Wortstellung – der Nebensatz behält die normale SVO-Ordnung. Das macht polnische Kausalsätze einfacher!"},
            {"id": "gp_conj14", "question": "_____ tak mówisz, wierzę ci.", "translation": "(Da du das sagst, glaube ich dir.)", "options": ["Skoro", "Ale", "Chociaż", "Zanim"], "correct": "Skoro", "explanation": "'Skoro' = 'da/wenn (schon)' – kausale Konjunktion für bekannte/akzeptierte Gründe. 'Skoro tak mówisz, wierzę ci' = 'Da du das sagst, glaube ich dir'. Im Deutschen: 'da' (kausal, bekannter Grund) vs. 'weil' (neuer Grund). Im Polnischen: 'skoro' (bekannter Grund) vs. 'bo/ponieważ' (Erklärung). 'Skoro' impliziert: Ich akzeptiere deine Prämisse und ziehe daraus eine Schlussfolgerung."},
            {"id": "gp_conj15", "question": "Chyba _____ zmienisz zdanie.", "translation": "(Es sei denn, du änderst deine Meinung.)", "options": ["że", "bo", "jak", "więc"], "correct": "że", "explanation": "'Chyba że' = 'es sei denn' / 'außer wenn' – die Ausnahme-Konjunktion. 'Chyba że zmienisz zdanie' = 'Es sei denn, du änderst deine Meinung'. 'Chyba' allein bedeutet 'wahrscheinlich/wohl'. Mit 'że' zusammen wird es zur Konjunktion der Ausnahme. Diese Wendung ist im Polnischen extrem häufig und vielseitig. Im Deutschen ist 'es sei denn' eher formell, aber 'chyba że' wird auch in lockerer Umgangssprache verwendet."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")
