#!/usr/bin/env python3
"""Batch 14: cats 72-76 for german_polish grammar.
Categories: sentence_structure_advanced, cleft_sentences, emphasis_constructions, 
            comparison_structures, purpose_clauses
"""
import json
from collections import Counter

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "sentence_structure_advanced",
        "name": "Zaawansowany szyk zdania (Fortgeschrittene Satzstruktur)",
        "description": "Kompleksowe struktury zdaniowe w języku polskim – inwersja, topikalizacja i szyk emfatyczny",
        "icon": "text.line.first.and.arrowtriangle.forward",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_ssa1", "question": "_____ to zrobił, nie ja.", "translation": "Er hat das gemacht, nicht ich.", "options": ["On", "Jego", "Jemu", "Nim"], "correct": "On", "explanation": "Im Polnischen wird die Betonung durch die Stellung des Subjekts am Satzanfang erzielt. Wenn man betonen will, WER etwas getan hat, stellt man das Subjektpronomen 'on' an den Anfang. Im Deutschen würde man hier die Betonung durch Intonation oder Konstruktionen wie 'Er ist es, der...' erreichen. Das Pronomen 'on' steht im Nominativ als Subjekt des Satzes."},
            {"id": "gp_ssa2", "question": "To właśnie _____ chciałem powiedzieć.", "translation": "Genau das wollte ich sagen.", "options": ["to", "tego", "temu", "tym"], "correct": "to", "explanation": "Die Konstruktion 'to właśnie to' ist eine polnische Emphasestruktur, vergleichbar mit dem deutschen 'genau das'. Das Demonstrativpronomen 'to' wird im Nominativ verwendet, da es als Subjekt oder Prädikativ fungiert. 'Właśnie' verstärkt die Aussage (genau/eben). Diese Struktur ist im Polnischen sehr natürlich und wird häufig in der gesprochenen Sprache verwendet."},
            {"id": "gp_ssa3", "question": "Tę książkę _____ już dawno.", "translation": "Dieses Buch habe ich schon lange gelesen.", "options": ["przeczytałem", "przeczytam", "czytam", "czytałem"], "correct": "przeczytałem", "explanation": "Topikalisierung: Das Objekt 'tę książkę' (Akkusativ) wird an den Satzanfang gestellt, um es zu betonen. Im Deutschen geschieht dies ähnlich: 'Dieses Buch habe ich...' Im Polnischen bleibt der Verb an zweiter oder dritter Position. Der perfektive Aspekt 'przeczytałem' betont die Vollendung der Handlung – das Buch wurde komplett gelesen."},
            {"id": "gp_ssa4", "question": "Dopiero wczoraj _____ o tym.", "translation": "Erst gestern habe ich davon erfahren.", "options": ["dowiedziałem się", "dowiadywałem się", "dowiem się", "dowiaduję się"], "correct": "dowiedziałem się", "explanation": "'Dopiero' bedeutet 'erst' und steht am Satzanfang zur zeitlichen Betonung. Das reflexive Verb 'dowiedzieć się' (erfahren) steht im perfektiven Aspekt, um zu betonen, dass man es erst zu diesem Zeitpunkt erfahren hat. Im Deutschen wird 'erst' ähnlich verwendet. Beachten Sie, dass 'się' als reflexives Pronomen dem Verb folgt."},
            {"id": "gp_ssa5", "question": "Ani słowa nie _____ na ten temat.", "translation": "Kein einziges Wort sage ich zu diesem Thema.", "options": ["powiem", "mówię", "powiedziałem", "mówiłem"], "correct": "powiem", "explanation": "'Ani słowa' (kein einziges Wort) am Satzanfang erzeugt eine starke Emphase. Die doppelte Verneinung 'nie powiem' ist im Polnischen obligatorisch – im Deutschen reicht eine einfache Verneinung. 'Powiem' (perfektiv, Futur) drückt einen festen Entschluss aus: Ich werde definitiv nichts sagen. Diese emphatic construction ist typisch für emotionale oder bestimmte Aussagen."},
            {"id": "gp_ssa6", "question": "Jemu _____ nie ufam.", "translation": "Ihm vertraue ich nicht.", "options": ["wcale", "zawsze", "bardzo", "trochę"], "correct": "wcale", "explanation": "'Jemu' (Dativ, betonte Form) am Satzanfang betont, WEM man nicht vertraut. 'Wcale nie' bedeutet 'überhaupt nicht' – eine verstärkte Verneinung. Im Deutschen wird dasselbe durch Intonation oder Umstellung erreicht: 'Ihm vertraue ich überhaupt nicht.' Die betonte Dativform 'jemu' (statt unbetont 'mu') unterstreicht den Kontrast."},
            {"id": "gp_ssa7", "question": "Nie on, _____ ona to zrobiła.", "translation": "Nicht er, sondern sie hat das gemacht.", "options": ["lecz", "i", "albo", "więc"], "correct": "lecz", "explanation": "'Lecz' ist die formelle Variante von 'ale' (sondern/aber) und wird in kontrastierenden Strukturen verwendet. Die Konstruktion 'Nie X, lecz Y' entspricht dem Deutschen 'Nicht X, sondern Y'. Im Polnischen steht 'lecz' häufiger in der Schriftsprache, während 'ale' in der Umgangssprache bevorzugt wird. Beachten Sie: 'ona to zrobiła' – das Pronomen 'to' verstärkt den Bezug."},
            {"id": "gp_ssa8", "question": "Z pewnością _____ na czas.", "translation": "Mit Sicherheit kommen wir rechtzeitig.", "options": ["zdążymy", "zdążamy", "zdążyliśmy", "zdążaliśmy"], "correct": "zdążymy", "explanation": "'Z pewnością' (mit Sicherheit) am Satzanfang als modale Bestimmung. 'Zdążymy' ist die 1. Person Plural Futur des perfektiven Verbs 'zdążyć' (rechtzeitig schaffen). Im Polnischen steht die modale Bestimmung typischerweise am Satzanfang, ähnlich wie im Deutschen. Der perfektive Aspekt betont das erfolgreiche Ergebnis."},
            {"id": "gp_ssa9", "question": "Nigdy _____ tego nie zapomnę.", "translation": "Niemals werde ich das vergessen.", "options": ["przenigdy", "zawsze", "kiedyś", "często"], "correct": "przenigdy", "explanation": "'Nigdy przenigdy' ist eine verstärkte Verneinungsstruktur (niemals, absolut nie). Die doppelte Negation 'nie zapomnę' ist im Polnischen obligatorisch bei negativen Adverbien. 'Przenigdy' verstärkt 'nigdy' – im Deutschen gibt es keine direkte Entsprechung, man würde 'absolut nie/niemals' sagen. Der perfektive Aspekt 'zapomnę' betont die Endgültigkeit."},
            {"id": "gp_ssa10", "question": "To ja _____ pierwszy.", "translation": "Ich war es, der als Erster kam.", "options": ["przyszedłem", "przychodzę", "przyjdę", "przychodziłem"], "correct": "przyszedłem", "explanation": "Spaltsatz-Konstruktion: 'To ja' (Das bin ich/Ich war es) betont das Subjekt. Im Deutschen: 'Ich war es, der...' Der perfektive Aspekt 'przyszedłem' weist auf eine einmalige, abgeschlossene Handlung hin. 'Pierwszy' (als Erster) steht im Nominativ als prädikative Bestimmung. Diese Emphasestruktur ist im Polnischen alltäglich."},
            {"id": "gp_ssa11", "question": "Co do mnie, _____ się zgadzam.", "translation": "Was mich betrifft, stimme ich zu.", "options": ["w pełni", "nigdy", "wcale", "rzadko"], "correct": "w pełni", "explanation": "'Co do mnie' (was mich betrifft) ist eine topikalisierende Wendung, die den Sprecher in den Fokus rückt. 'W pełni się zgadzam' bedeutet 'ich stimme voll und ganz zu'. Im Deutschen: 'Was mich betrifft/angeht...' Diese Konstruktion wird sowohl schriftlich als auch mündlich verwendet und signalisiert einen persönlichen Standpunkt im Kontrast zu anderen."},
            {"id": "gp_ssa12", "question": "Jakże _____ tam nie pojechać!", "translation": "Wie kann man dort nicht hinfahren!", "options": ["można", "trzeba", "wolno", "warto"], "correct": "można", "explanation": "'Jakże' ist ein emphatisches Fragewort (wie nur/wie kann man) und drückt Verwunderung oder rhetorische Empörung aus. 'Można' (man kann) bildet eine unpersönliche Konstruktion. Die doppelte Verneinung 'nie pojechać' mit dem rhetorischen 'jakże' erzeugt eine starke affirmative Bedeutung: Man MUSS hinfahren! Im Deutschen: rhetorische Frage."},
            {"id": "gp_ssa13", "question": "O ile wiem, _____ już wyjechał.", "translation": "Soweit ich weiß, ist er schon abgereist.", "options": ["on", "ona", "ono", "oni"], "correct": "on", "explanation": "'O ile wiem' (soweit ich weiß) ist eine einschränkende Einleitung, die Unsicherheit signalisiert. Im Deutschen: 'Soweit ich weiß/Meines Wissens nach'. Das perfektive 'wyjechał' zeigt eine abgeschlossene Handlung. Im Polnischen werden solche modalen Einleitungen häufig verwendet, um Aussagen abzuschwächen oder als unsicher zu markieren."},
            {"id": "gp_ssa14", "question": "Tak czy _____, musimy to zrobić.", "translation": "So oder so, wir müssen es tun.", "options": ["inaczej", "owak", "siak", "nie"], "correct": "inaczej", "explanation": "'Tak czy inaczej' (so oder so/auf jeden Fall) ist eine feststehende Redewendung, die Unvermeidlichkeit ausdrückt. Im Deutschen: 'So oder so/Wie dem auch sei'. 'Musimy' (wir müssen) + 'to zrobić' (das tun) bildet eine modale Konstruktion mit Infinitiv. Diese Wendung wird häufig in Diskussionen verwendet, um ein Fazit zu ziehen."},
            {"id": "gp_ssa15", "question": "Im szybciej, _____ lepiej.", "translation": "Je schneller, desto besser.", "options": ["tym", "ten", "to", "ta"], "correct": "tym", "explanation": "Die Struktur 'im...tym' entspricht dem Deutschen 'je...desto'. 'Im' leitet den Komparativ ein (je schneller), 'tym' den zweiten Teil (desto besser). Im Deutschen ist die Struktur 'je + Komparativ, desto + Komparativ' identisch. 'Szybciej' ist der Komparativ von 'szybko' (schnell), 'lepiej' der Komparativ von 'dobrze' (gut). Diese Korrelativstruktur ist in beiden Sprachen sehr produktiv."}
        ]
    },
    {
        "key": "cleft_sentences",
        "name": "Zdania rozszczepione (Spaltsätze)",
        "description": "Zdania rozszczepione i konstrukcje emfatyczne z 'to' – podkreślanie elementów zdania",
        "icon": "arrow.triangle.branch",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_cleft1", "question": "To Maria _____ ten list.", "translation": "Es war Maria, die diesen Brief geschrieben hat.", "options": ["napisała", "pisała", "pisze", "napisze"], "correct": "napisała", "explanation": "Polnischer Spaltsatz mit 'to' + Subjekt + Verb. 'To Maria napisała' betont, DASS es Maria war (nicht jemand anderes). Im Deutschen wird dies durch 'Es war Maria, die...' oder 'Maria war es, die...' ausgedrückt. Der perfektive Aspekt 'napisała' (sie hat geschrieben) zeigt die abgeschlossene Handlung. Die weibliche Endung '-ła' stimmt mit 'Maria' überein."},
            {"id": "gp_cleft2", "question": "To właśnie _____ szukałem.", "translation": "Genau das habe ich gesucht.", "options": ["tego", "to", "temu", "tym"], "correct": "tego", "explanation": "'To właśnie tego szukałem' – Emphase auf das Objekt. 'Tego' steht im Genitiv, weil 'szukać' (suchen) den Genitiv regiert (nicht den Akkusativ wie im Deutschen!). 'Właśnie' (genau/eben) verstärkt die Emphase. Im Deutschen: 'Genau das habe ich gesucht' – 'das' im Akkusativ. Die unterschiedliche Kasusrektion ist ein typischer Fehler für deutschsprachige Lernende."},
            {"id": "gp_cleft3", "question": "To w Krakowie _____ się urodziłem.", "translation": "In Krakau bin ich geboren, (nicht woanders).", "options": ["właśnie", "może", "chyba", "prawie"], "correct": "właśnie", "explanation": "Emphase auf den Ort: 'To w Krakowie właśnie...' betont, WO man geboren wurde. 'To' + Präpositionalphrase + 'właśnie' ist eine typisch polnische Spaltsatz-Konstruktion. Im Deutschen: 'In Krakau, da bin ich geboren' oder 'Es war in Krakau, wo ich geboren wurde.' 'Urodziłem się' (ich wurde geboren) ist reflexiv im Polnischen, anders als im Deutschen."},
            {"id": "gp_cleft4", "question": "To dlatego _____ się spóźnił.", "translation": "Deshalb hat er sich verspätet.", "options": ["on", "ona", "pan", "my"], "correct": "on", "explanation": "'To dlatego' (deshalb/aus diesem Grund) betont den KAUSALZUSAMMENHANG. 'To' leitet den emphatischen Satz ein. Im Deutschen: 'Deshalb...' oder 'Aus diesem Grund hat er sich...' 'Spóźnił się' ist ein reflexives Verb im Perfektiv – die Verspätung ist eingetreten. Die männliche Endung '-ił' und 'się' nach dem Verb folgen der polnischen Wortstellung."},
            {"id": "gp_cleft5", "question": "To nie pieniądze _____ szczęście.", "translation": "Nicht Geld bringt Glück (sondern etwas anderes).", "options": ["dają", "daje", "dał", "dała"], "correct": "dają", "explanation": "'To nie pieniądze dają szczęście' – Verneinung im Spaltsatz. 'Pieniądze' (Geld) steht im Plural (im Polnischen immer Plural!), daher das Verb in der 3. Person Plural 'dają'. Im Deutschen ist 'Geld' Singular. Die Konstruktion 'to nie X...' betont, dass X NICHT der Grund/die Ursache ist. 'Szczęście' (Glück) steht im Akkusativ als direktes Objekt."},
            {"id": "gp_cleft6", "question": "To dzięki _____ udało się to zrobić.", "translation": "Dank dir ist es gelungen, das zu tun.", "options": ["tobie", "ty", "ciebie", "tobą"], "correct": "tobie", "explanation": "'Dzięki' (dank) regiert den Dativ. 'Tobie' ist die betonte Dativform von 'ty'. Im Deutschen: 'dank dir' (auch Dativ!). 'Udało się' ist eine unpersönliche Konstruktion: 'es ist gelungen'. Die emphatische Stellung 'to dzięki tobie' betont, WEGEN WEM es gelungen ist. Vergleich: unbetont 'ci', betont 'tobie'."},
            {"id": "gp_cleft7", "question": "To w poniedziałek _____ spotkanie.", "translation": "Am Montag findet das Treffen statt.", "options": ["mamy", "mam", "macie", "mają"], "correct": "mamy", "explanation": "'To w poniedziałek' betont den WOCHENTAG. 'Mamy spotkanie' (wir haben ein Treffen) – 'mieć' wird im Polnischen oft verwendet, wo im Deutschen 'stattfinden' steht. Die 1. Person Plural 'mamy' impliziert Zugehörigkeit zur Gruppe. Im Deutschen: 'Am Montag haben wir das Treffen' oder 'Am Montag findet das Treffen statt.' Der Spaltsatz fokussiert den Zeitpunkt."},
            {"id": "gp_cleft8", "question": "To on jest _____, kto to wie.", "translation": "Er ist derjenige, der das weiß.", "options": ["tym", "ten", "tego", "temu"], "correct": "tym", "explanation": "'To on jest tym, kto...' – Spaltsatz mit Relativsatz. 'Tym' steht im Instrumentalis, da nach 'jest' (sein) das Prädikativ im Instrumentalis steht – eine Besonderheit des Polnischen! Im Deutschen: Nominativ. 'Kto' (wer/der) leitet den Relativsatz ein. Die ganze Konstruktion betont die Person emphatisch."},
            {"id": "gp_cleft9", "question": "To nie ja _____ te błędy.", "translation": "Nicht ich habe diese Fehler gemacht.", "options": ["zrobiłem", "robię", "zrobię", "robiłem"], "correct": "zrobiłem", "explanation": "'To nie ja' – emphatische Verneinung des Subjekts. Im Deutschen: 'Nicht ich habe...' oder 'Ich bin es nicht, der...' 'Zrobiłem' (perfektiv, 1. Pers. Sg. m.) – abgeschlossene Handlung. 'Te błędy' (diese Fehler) im Akkusativ Plural. Die Konstruktion dient der Verteidigung oder Klarstellung: Jemand anderes hat die Fehler gemacht."},
            {"id": "gp_cleft10", "question": "To tam _____ najlepsza pizza.", "translation": "Dort gibt es die beste Pizza.", "options": ["jest", "są", "była", "będzie"], "correct": "jest", "explanation": "'To tam jest...' betont den ORT. Im Deutschen: 'Dort gibt es die beste Pizza.' 'Najlepsza' ist der Superlativ von 'dobra' (gut) in der weiblichen Form, passend zu 'pizza' (feminin). Im Polnischen wird 'jest' (es gibt/ist) für Existenzsätze verwendet, wo im Deutschen 'es gibt' + Akkusativ steht. Die Lokalisierung wird emphatisch hervorgehoben."},
            {"id": "gp_cleft11", "question": "To o tym _____ ci wczoraj.", "translation": "Davon habe ich dir gestern erzählt.", "options": ["mówiłem", "mówię", "powiem", "mówiono"], "correct": "mówiłem", "explanation": "'To o tym' – Emphase auf das Thema ('davon/darüber'). 'O tym' steht im Lokativ nach der Präposition 'o' (über/von). 'Mówiłem ci' (ich habe dir gesagt) – imperfektiver Aspekt, da es um einen Gesprächsprozess geht, nicht um eine einzelne Aussage. 'Ci' ist die unbetonte Dativform von 'ty'. Diese Konstruktion wird oft verwendet, um auf etwas Bekanntes zu verweisen."},
            {"id": "gp_cleft12", "question": "To z tego powodu _____ zrezygnować.", "translation": "Aus diesem Grund musste ich aufgeben.", "options": ["musiałem", "muszę", "będę musiał", "musiałbym"], "correct": "musiałem", "explanation": "'To z tego powodu' (aus diesem Grund/deswegen) betont die URSACHE emphatisch. 'Z tego powodu' wörtlich: 'aus diesem Grund' – 'tego' im Genitiv nach 'z'. 'Musiałem' (ich musste) + Infinitiv 'zrezygnować' (aufgeben/verzichten). Im Deutschen: 'Aus diesem Grund musste ich...' Die polnische Spaltsatz-Konstruktion hebt den kausalen Zusammenhang hervor."},
            {"id": "gp_cleft13", "question": "To _____ jest problem, nie rozwiązanie.", "translation": "Das ist das Problem, nicht die Lösung.", "options": ["to", "ten", "ta", "ci"], "correct": "to", "explanation": "'To to jest problem' – doppeltes 'to': erstes als Emphase-Partikel, zweites als Demonstrativpronomen. Im Deutschen nicht direkt wiederzugeben. Die Kontraststruktur 'nie rozwiązanie' (nicht die Lösung) verdeutlicht den Gegensatz. Im Polnischen ist diese Doppelung natürlich und häufig in der gesprochenen Sprache – im Deutschen würde man Intonation oder 'genau DAS' verwenden."},
            {"id": "gp_cleft14", "question": "To dla ciebie _____ ten prezent.", "translation": "Für dich habe ich dieses Geschenk gekauft.", "options": ["kupiłem", "kupuję", "kupię", "kupowałem"], "correct": "kupiłem", "explanation": "'To dla ciebie' – Emphase auf den Empfänger. 'Dla' (für) + Genitiv: 'ciebie' (betonte Form) statt 'cię' (unbetont). 'Kupiłem' (perfektiv, ich habe gekauft) betont die abgeschlossene Handlung. 'Ten prezent' (dieses Geschenk) im Akkusativ als direktes Objekt. Im Deutschen: 'Für dich habe ich...' Die Betonung durch Spaltsatz unterstreicht die persönliche Widmung."},
            {"id": "gp_cleft15", "question": "To wtedy _____ ją po raz pierwszy.", "translation": "Damals habe ich sie zum ersten Mal gesehen.", "options": ["zobaczyłem", "widziałem", "widzę", "zobaczę"], "correct": "zobaczyłem", "explanation": "'To wtedy' (damals/zu jener Zeit) betont den ZEITPUNKT. 'Zobaczyłem' (perfektiv: ich erblickte/sah) vs. 'widziałem' (imperfektiv: ich sah/pflegte zu sehen). Der perfektive Aspekt betont den Moment des ERSTMALIGEN Erblickens – ein einmaliges Ereignis. 'Po raz pierwszy' (zum ersten Mal) verstärkt die Einmaligkeit. Im Deutschen wird der Unterschied durch Kontext, nicht durch Verbform ausgedrückt."}
        ]
    },
    {
        "key": "comparison_advanced",
        "name": "Zaawansowane porównania (Fortgeschrittene Vergleiche)",
        "description": "Komplexe Vergleichsstrukturen – so...wie, je...desto, und Superlativkonstruktionen",
        "icon": "arrow.left.arrow.right",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_cmpa1", "question": "On jest tak samo _____ jak jego brat.", "translation": "Er ist genauso groß wie sein Bruder.", "options": ["wysoki", "wysokiego", "wysokim", "wysoką"], "correct": "wysoki", "explanation": "'Tak samo...jak' entspricht dem Deutschen 'genauso...wie'. Das Adjektiv 'wysoki' (groß/hoch) steht im Nominativ Maskulin Singular, da es sich auf 'on' (er) bezieht. Im Deutschen: 'genauso groß wie' – der Positiv wird verwendet, genau wie im Polnischen. Die Konstruktion ist strukturell identisch in beiden Sprachen: Subj. + sein + genauso + Adj. + wie + Vergleichsobjekt."},
            {"id": "gp_cmpa2", "question": "Ta książka jest _____ ciekawa niż tamta.", "translation": "Dieses Buch ist interessanter als jenes.", "options": ["bardziej", "mniej", "tak", "najbardziej"], "correct": "bardziej", "explanation": "'Bardziej' (mehr) + Adjektiv bildet den analytischen Komparativ für mehrsilbige Adjektive. 'Ciekawa' (interessant) kann nicht mit dem synthetischen Suffix '-sza' versehen werden, daher 'bardziej ciekawa'. 'Niż' (als) leitet den Vergleich ein – im Deutschen 'als'. Beachten Sie: bei kurzen Adjektiven wird der Komparativ synthetisch gebildet: 'ładna → ładniejsza', bei langen analytisch."},
            {"id": "gp_cmpa3", "question": "To jest _____ restauracja w mieście.", "translation": "Das ist das beste Restaurant in der Stadt.", "options": ["najlepsza", "lepsza", "dobra", "najlepszą"], "correct": "najlepsza", "explanation": "Superlativ 'najlepsza' (die beste) – femininum, weil 'restauracja' weiblich ist. Die Superlativbildung: 'naj-' + Komparativ ('lepsza' von 'dobra'). Im Deutschen: 'das beste'. 'W mieście' (in der Stadt) steht im Lokativ nach 'w'. Der Superlativ wird im Polnischen immer mit dem Präfix 'naj-' gebildet – eine einfache und regelmäßige Regel, anders als im Deutschen mit 'am ...sten/-ste'."},
            {"id": "gp_cmpa4", "question": "Wolę kawę _____ herbaty.", "translation": "Ich ziehe Kaffee dem Tee vor.", "options": ["od", "niż", "jak", "do"], "correct": "od", "explanation": "'Woleć A od B' (A dem B vorziehen) – 'od' + Genitiv für Vergleiche bei Präferenzen. 'Herbaty' ist Genitiv von 'herbata'. Im Deutschen: 'vorziehen' + Dativ oder 'lieber mögen als'. ACHTUNG: Bei 'woleć' wird NICHT 'niż' verwendet, sondern 'od' + Genitiv! Dies ist ein häufiger Fehler deutschsprachiger Lernender, die 'niż' (als) erwarten würden."},
            {"id": "gp_cmpa5", "question": "Im dłużej czekam, _____ bardziej się denerwuję.", "translation": "Je länger ich warte, desto nervöser werde ich.", "options": ["tym", "ten", "to", "ta"], "correct": "tym", "explanation": "'Im...tym' = 'je...desto/umso'. 'Im dłużej' (je länger) – 'dłużej' ist Komparativ von 'długo' (lang). 'Tym bardziej' (desto mehr/umso mehr). Die Struktur ist im Polnischen und Deutschen sehr ähnlich: je + Komparativ, desto + Komparativ. 'Denerwuję się' (ich bin nervös/rege mich auf) ist reflexiv. Diese Korrelativstruktur drückt proportionale Veränderung aus."},
            {"id": "gp_cmpa6", "question": "Jest o wiele _____ niż myślałem.", "translation": "Es ist viel schwieriger als ich dachte.", "options": ["trudniejsze", "trudne", "najtrudniejsze", "trudnego"], "correct": "trudniejsze", "explanation": "'O wiele' (um vieles/viel) verstärkt den Komparativ – im Deutschen: 'viel schwieriger'. 'Trudniejsze' ist Komparativ Neutrum von 'trudne' (schwierig). 'Niż myślałem' (als ich dachte). Im Polnischen können Komparative durch 'o wiele', 'znacznie', 'dużo' verstärkt werden – ähnlich wie im Deutschen 'viel', 'bedeutend', 'wesentlich' + Komparativ."},
            {"id": "gp_cmpa7", "question": "Jest coraz _____ na ulicach.", "translation": "Es wird immer lauter auf den Straßen.", "options": ["głośniej", "głośno", "najgłośniej", "głośnego"], "correct": "głośniej", "explanation": "'Coraz' + Komparativ = 'immer' + Komparativ (zunehmend). 'Głośniej' ist Komparativ des Adverbs 'głośno' (laut). Im Deutschen: 'immer lauter'. Die Konstruktion drückt eine graduelle Veränderung aus. 'Na ulicach' (auf den Straßen) steht im Lokativ Plural. Diese progressive Vergleichsstruktur ist in beiden Sprachen sehr ähnlich aufgebaut."},
            {"id": "gp_cmpa8", "question": "Nie jest tak _____, jak się wydaje.", "translation": "Es ist nicht so schlimm, wie es scheint.", "options": ["źle", "zły", "złego", "złym"], "correct": "źle", "explanation": "'Nie jest tak źle, jak...' – Adverb 'źle' (schlecht/schlimm), nicht das Adjektiv 'zły'. Nach 'jest' in der unpersönlichen Konstruktion steht das Adverb! 'Jak się wydaje' (wie es scheint) – reflexive Konstruktion. Im Deutschen: 'so schlimm, wie...' Diese abschwächende Vergleichsstruktur wird oft tröstend verwendet: Die Realität ist besser als der Anschein."},
            {"id": "gp_cmpa9", "question": "On jest _____ ze wszystkich studentów.", "translation": "Er ist der klügste aller Studenten.", "options": ["najmądrzejszy", "mądrzejszy", "mądry", "najmądrzejszym"], "correct": "najmądrzejszy", "explanation": "Superlativ 'najmądrzejszy' (der klügste) + 'ze wszystkich' (von allen) + Genitiv Plural. 'Studentów' ist Genitiv Plural von 'student'. Im Deutschen: 'der klügste aller/von allen Studenten'. Die Konstruktion 'naj- + Komparativ' + 'ze wszystkich' + Gen.Pl. ist die typische Superlativstruktur zum Hervorheben innerhalb einer Gruppe."},
            {"id": "gp_cmpa10", "question": "Wygląda dużo _____ niż na swoje lata.", "translation": "Er/Sie sieht viel jünger aus, als er/sie ist.", "options": ["młodziej", "młodo", "najmłodziej", "młodego"], "correct": "młodziej", "explanation": "'Dużo młodziej' (viel jünger) – verstärkter Komparativ des Adverbs. 'Wyglądać' (aussehen) + Adverb (nicht Adjektiv!). 'Niż na swoje lata' (als für seine/ihre Jahre) – idiomatische Wendung. Im Deutschen: 'viel jünger aussehen'. Beachten Sie: Nach 'wyglądać' steht im Polnischen das Adverb, im Deutschen das Adjektiv ('jünger aussehen' vs. 'wyglądać młodziej')."},
            {"id": "gp_cmpa11", "question": "Ten dom jest trzy razy _____ od tamtego.", "translation": "Dieses Haus ist dreimal größer als jenes.", "options": ["większy", "wielki", "największy", "większym"], "correct": "większy", "explanation": "'Trzy razy większy' (dreimal größer) – multiplikativer Vergleich. 'Od tamtego' (als jenes) – bei Adjektiv-Komparativen kann 'od' + Genitiv ODER 'niż' verwendet werden. 'Tamtego' ist Genitiv von 'tamten' (jener). Im Deutschen: 'dreimal größer als'. Der multiplikative Vergleich folgt in beiden Sprachen demselben Muster: Multiplikator + Komparativ + Vergleichsobjekt."},
            {"id": "gp_cmpa12", "question": "Minimalnie _____ wynik niż ostatnio.", "translation": "Ein minimal besseres Ergebnis als beim letzten Mal.", "options": ["lepszy", "dobry", "najlepszy", "lepszym"], "correct": "lepszy", "explanation": "'Minimalnie lepszy' (minimal besser) – der Komparativ wird durch 'minimalnie' (minimal/kaum) abgeschwächt. Im Deutschen: 'ein geringfügig/minimal besseres Ergebnis'. 'Niż ostatnio' (als beim letzten Mal/als zuletzt). Abschwächende Adverbien bei Komparativen: 'trochę' (ein bisschen), 'odrobinę' (ein wenig), 'nieco' (etwas), 'minimalnie' (minimal). Im Deutschen ähnlich vielfältig."},
            {"id": "gp_cmpa13", "question": "Nic _____ niż dobre jedzenie.", "translation": "Nichts Besseres als gutes Essen.", "options": ["lepszego", "lepsze", "lepszy", "najlepszego"], "correct": "lepszego", "explanation": "'Nic lepszego' – nach 'nic' (nichts) steht der Genitiv! Dies ist eine wichtige Regel im Polnischen: pronominale Quantifikatoren wie 'nic', 'coś', 'dużo' regieren den Genitiv. 'Lepszego' ist Genitiv Neutrum Singular. Im Deutschen: 'nichts Besseres' (Nominativ mit substantiviertem Adjektiv). Die Kasusrektion nach 'nic' ist ein typischer Fehlerbereich."},
            {"id": "gp_cmpa14", "question": "To tym _____, im więcej wiesz.", "translation": "Je mehr du weißt, desto besser.", "options": ["lepiej", "lepsze", "lepszy", "najlepiej"], "correct": "lepiej", "explanation": "'Tym lepiej, im więcej' – umgekehrte Reihenfolge der 'je...desto'-Konstruktion (desto besser, je mehr). 'Lepiej' ist Komparativ des Adverbs 'dobrze' (gut). 'Więcej' ist Komparativ von 'dużo' (viel). Im Deutschen: 'Je mehr du weißt, desto besser' – die Reihenfolge kann im Polnischen variieren. Beide Sprachen verwenden den Komparativ in dieser korrelativen Struktur."},
            {"id": "gp_cmpa15", "question": "Jest zdecydowanie _____ od swoich rówieśników.", "translation": "Er/Sie ist entschieden reifer als seine/ihre Altersgenossen.", "options": ["dojrzalszy", "dojrzały", "najdojrzalszy", "dojrzałym"], "correct": "dojrzalszy", "explanation": "'Zdecydowanie dojrzalszy' (entschieden/deutlich reifer) – verstärkter Komparativ. 'Od swoich rówieśników' (als seine Altersgenossen) – 'od' + Genitiv Plural. 'Swoich' ist Genitiv Plural des Reflexivpossessivs 'swój'. Im Deutschen: 'deutlich reifer als'. Verstärkungsadverbien wie 'zdecydowanie' (entschieden), 'znacznie' (bedeutend) heben den Komparativ emphatisch hervor."}
        ]
    },
    {
        "key": "purpose_result_clauses",
        "name": "Zdania celowe i skutkowe (Zweck- und Folgesätze)",
        "description": "Wyrażanie celu i skutku w zdaniach złożonych – żeby, aby, tak że, dlatego",
        "icon": "arrow.right.to.line",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_purp1", "question": "Uczę się, _____ zdać egzamin.", "translation": "Ich lerne, um die Prüfung zu bestehen.", "options": ["żeby", "bo", "gdy", "choć"], "correct": "żeby", "explanation": "'Żeby' + Infinitiv = 'um...zu' + Infinitiv – Finalsatz (Zwecksatz). 'Żeby zdać' (um zu bestehen) – bei gleichem Subjekt kann der Infinitiv folgen. Im Deutschen: 'um die Prüfung zu bestehen'. WICHTIG: Bei verschiedenen Subjekten muss die konjugierte Form stehen: 'żebym zdał' (damit ich bestehe). Die Unterscheidung gleiches/verschiedenes Subjekt ist im Polnischen grammatisch relevant."},
            {"id": "gp_purp2", "question": "Mówię cicho, _____ nie obudzić dziecka.", "translation": "Ich spreche leise, um das Kind nicht zu wecken.", "options": ["żeby", "bo", "kiedy", "ale"], "correct": "żeby", "explanation": "'Żeby nie' + Infinitiv = 'um...nicht zu' – verneinender Finalsatz. 'Obudzić' (wecken, perfektiv) im Infinitiv, weil das Subjekt identisch ist (ich spreche = ich will nicht wecken). 'Dziecka' im Genitiv – nach verneinten transitiven Verben steht im Polnischen der Genitiv statt des Akkusativs! Im Deutschen: Akkusativ 'das Kind'. Diese Genitivregel bei Verneinung ist typisch polnisch."},
            {"id": "gp_purp3", "question": "Dał mi klucz, _____ mogła wejść.", "translation": "Er gab mir den Schlüssel, damit ich eintreten konnte.", "options": ["żebym", "że", "bo", "kiedy"], "correct": "żebym", "explanation": "'Żebym' = 'żeby' + '-m' (1. Person-Endung) – Finalsatz mit verschiedenem Subjekt. 'Żebym mogła' (damit ich konnte) – weibliche Form '-ła' zeigt, dass die Sprecherin eine Frau ist. Im Deutschen: 'damit ich eintreten konnte'. Personalendungen an 'żeby': żebym (ich), żebyś (du), żeby (er/sie), żebyśmy (wir), żebyście (ihr), żeby (sie). Das ist eine Besonderheit des Polnischen!"},
            {"id": "gp_purp4", "question": "Pracuje ciężko, _____ zapewnić rodzinie dobry byt.", "translation": "Er arbeitet hart, um der Familie ein gutes Leben zu sichern.", "options": ["aby", "i", "albo", "gdyby"], "correct": "aby", "explanation": "'Aby' ist die formelle/schriftliche Variante von 'żeby' (um zu/damit). In offiziellen Texten, Gesetzen und wissenschaftlichen Arbeiten wird 'aby' bevorzugt. Im Polnischen gibt es drei Synonyme: 'żeby' (neutral), 'aby' (formell), 'ażeby' (veraltet). 'Zapewnić' (sichern/gewährleisten) + Dativ (rodzinie) + Akkusativ (dobry byt) – doppelte Rektion wie im Deutschen."},
            {"id": "gp_purp5", "question": "Było tak ciemno, _____ nic nie widziałem.", "translation": "Es war so dunkel, dass ich nichts sehen konnte.", "options": ["że", "żeby", "bo", "gdy"], "correct": "że", "explanation": "'Tak...że' = 'so...dass' – konsekutiver Nebensatz (Folgesatz). 'Tak ciemno, że nic nie widziałem' (so dunkel, dass ich nichts sah). Im Deutschen identische Struktur. Die doppelte Verneinung 'nic nie' (nichts nicht) ist im Polnischen obligatorisch, im Deutschen ein Fehler. 'Widziałem' (imperfektiv) – der Zustand des Nicht-Sehens dauerte an."},
            {"id": "gp_purp6", "question": "Padało tak mocno, _____ nie można było wyjść.", "translation": "Es regnete so stark, dass man nicht rausgehen konnte.", "options": ["że", "żeby", "bo", "ale"], "correct": "że", "explanation": "Konsekutivsatz: 'tak mocno, że...' (so stark, dass...). 'Nie można było' (man konnte nicht) – unpersönliche Vergangenheitsform: 'można' (man kann) + 'było' (war). 'Wyjść' (rausgehen, perfektiv). Im Deutschen: 'dass man nicht rausgehen konnte'. Die unpersönliche Konstruktion mit 'można było' ist typisch polnisch – im Deutschen wird 'man konnte' verwendet."},
            {"id": "gp_purp7", "question": "Wstał wcześnie po to, _____ zdążyć na pociąg.", "translation": "Er stand früh auf, um den Zug noch zu erreichen.", "options": ["żeby", "bo", "więc", "jednak"], "correct": "żeby", "explanation": "'Po to, żeby' (dafür, um zu / zu dem Zweck, dass) – verstärkte Finalstruktur. Im Deutschen: 'um...zu' oder 'dafür, dass'. 'Zdążyć na pociąg' (den Zug schaffen/rechtzeitig sein) – 'zdążyć' mit 'na' + Akkusativ. Die Konstruktion 'po to, żeby' ist emphatischer als einfaches 'żeby' und betont die Absichtlichkeit der Handlung stärker."},
            {"id": "gp_purp8", "question": "Zrobił to w _____ celu, żeby pomóc przyjaciołom.", "translation": "Er tat es zu dem Zweck, seinen Freunden zu helfen.", "options": ["tym", "ten", "tego", "temu"], "correct": "tym", "explanation": "'W tym celu, żeby...' (zu dem Zweck, dass...) – formale Zweckkonstruktion. 'W tym celu' – 'w' + Lokativ: 'tym' ist Lokativ von 'ten', 'celu' Lokativ von 'cel' (Ziel/Zweck). Im Deutschen: 'zu dem Zweck', 'mit dem Ziel'. 'Pomóc' (helfen) + Dativ: 'przyjaciołom' (den Freunden, Dativ Plural). Die doppelte Kasusrektion muss beachtet werden."},
            {"id": "gp_purp9", "question": "Dlatego _____ się na studia.", "translation": "Deshalb hat er sich für das Studium entschieden.", "options": ["zdecydował", "decyduje", "zdecyduje", "decydował"], "correct": "zdecydował", "explanation": "'Dlatego' (deshalb/darum) leitet einen Konsekutivsatz ein – die FOLGE einer vorher genannten Ursache. 'Zdecydował się na' (sich entschieden für) – reflexives Verb + 'na' + Akkusativ. Im Deutschen: 'sich entscheiden für' + Akkusativ – ähnliche Rektion! Der perfektive Aspekt 'zdecydował' zeigt den endgültigen Entschluss. 'Dlatego' steht typischerweise am Satzanfang."},
            {"id": "gp_purp10", "question": "W rezultacie _____ pracę.", "translation": "Infolgedessen verlor er die Arbeit.", "options": ["stracił", "traci", "straci", "tracił"], "correct": "stracił", "explanation": "'W rezultacie' (infolgedessen/als Ergebnis) – formaler konsekutiver Konnektor. Im Deutschen: 'infolgedessen/folglich/als Ergebnis'. 'Stracił pracę' (er verlor die Arbeit) – perfektiver Aspekt. Im Polnischen wird 'stracić pracę' (die Arbeit verlieren) verwendet, während im Deutschen auch 'entlassen werden' möglich ist. 'Pracę' im Akkusativ als direktes Objekt."},
            {"id": "gp_purp11", "question": "Tyle ćwiczę, _____ moje wyniki się poprawiły.", "translation": "Ich übe so viel, dass sich meine Ergebnisse verbessert haben.", "options": ["że", "żeby", "bo", "gdy"], "correct": "że", "explanation": "'Tyle...że' (so viel...dass) – quantitativer Konsekutivsatz. 'Tyle' (so viel) korreliert mit 'że' (dass). 'Poprawiły się' (haben sich verbessert, perfektiv Plural feminin) – das reflexive 'się' steht am Ende. Im Deutschen: 'so viel, dass'. Die Verbindung 'tyle...że' zeigt Ursache-Wirkung: Die Menge an Übung führt zu besseren Ergebnissen."},
            {"id": "gp_purp12", "question": "Przyjechał specjalnie, _____ ją zobaczyć.", "translation": "Er kam extra, um sie zu sehen.", "options": ["żeby", "bo", "jak", "więc"], "correct": "żeby", "explanation": "'Specjalnie' (extra/speziell) verstärkt den Zweck. 'Żeby ją zobaczyć' (um sie zu sehen) – 'ją' (sie, Akkusativ). Gleiches Subjekt → Infinitiv nach 'żeby'. Im Deutschen: 'extra kommen, um...zu sehen'. 'Zobaczyć' (sehen/erblicken, perfektiv) betont das einmalige, gezielte Sehen – er wollte sie treffen. 'Specjalnie' unterstreicht die Absichtlichkeit der Reise."},
            {"id": "gp_purp13", "question": "Skutek był _____, że zamknięto szkołę.", "translation": "Die Folge war, dass die Schule geschlossen wurde.", "options": ["taki", "ten", "to", "tym"], "correct": "taki", "explanation": "'Skutek był taki, że...' (die Folge war die, dass...) – formale Konsekutivstruktur. 'Taki' (solch/derartig) im Nominativ Maskulin, bezogen auf 'skutek' (die Folge, maskulin). 'Zamknięto' – unpersönliche Vergangenheitsform auf '-no/-to': 'man schloss'. Im Deutschen: passiv 'wurde geschlossen'. Die '-no/-to'-Form ist eine polnische Besonderheit ohne direkte deutsche Entsprechung."},
            {"id": "gp_purp14", "question": "Wyszedł, nie _____ ani słowa.", "translation": "Er ging, ohne ein Wort zu sagen.", "options": ["mówiąc", "mówić", "mówił", "powiedział"], "correct": "mówiąc", "explanation": "'Nie mówiąc' (ohne zu sagen) – Adverbialpartizip der Gleichzeitigkeit (imiesłów przysłówkowy współczesny). Im Deutschen: 'ohne zu sagen' oder 'ohne ein Wort zu sagen'. Diese Partizipialkonstruktion ersetzt einen Nebensatz: 'wyszedł, nie mówiąc' = 'er ging, ohne dass er sagte'. 'Ani słowa' (kein einziges Wort) – verstärkte Verneinung mit 'ani' + Genitiv."},
            {"id": "gp_purp15", "question": "Zadzwoń, _____ się nie martwili.", "translation": "Ruf an, damit sie sich keine Sorgen machen.", "options": ["żeby", "bo", "ale", "gdy"], "correct": "żeby", "explanation": "'Żeby' + verneintes Verb – Finalsatz mit Verneinung. 'Żeby się nie martwili' (damit sie sich nicht sorgen) – 3. Person Plural. Verschiedene Subjekte: du (rufst an), sie (machen sich Sorgen). Im Deutschen: 'damit sie sich keine Sorgen machen'. Die Personalendung ist im Verb 'martwili' enthalten (3. Pl.), nicht an 'żeby'. 'Się' steht zwischen 'żeby' und 'nie' – typische Wortstellung."}
        ]
    },
    {
        "key": "cause_reason_clauses",
        "name": "Zdania przyczynowe (Kausalsätze)",
        "description": "Wyrażanie przyczyny i uzasadnienia – bo, ponieważ, dlatego że, z powodu",
        "icon": "arrow.turn.right.up",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_caus1", "question": "Nie przyszedłem, _____ byłem chory.", "translation": "Ich bin nicht gekommen, weil ich krank war.", "options": ["bo", "ale", "i", "więc"], "correct": "bo", "explanation": "'Bo' = 'weil' (umgangssprachlich) – der häufigste Kausalkonnektor im Polnischen. Im Gegensatz zum Deutschen ändert 'bo' die Wortstellung NICHT – das Verb bleibt an seiner üblichen Position. Im Deutschen schickt 'weil' das Verb ans Satzende. 'Bo' wird in der gesprochenen Sprache und in einfachen Texten bevorzugt. 'Byłem chory' (ich war krank) – Vergangenheit von 'być' + Adjektiv."},
            {"id": "gp_caus2", "question": "_____ padał deszcz, zostaliśmy w domu.", "translation": "Da es regnete, blieben wir zu Hause.", "options": ["Ponieważ", "Ale", "Więc", "Jednak"], "correct": "Ponieważ", "explanation": "'Ponieważ' = 'da/weil' (formell) – steht häufig am Satzanfang, wenn die Ursache zuerst genannt wird. Im Deutschen: 'Da es regnete...' (bekannte Information). 'Ponieważ' ist formeller als 'bo' – in offiziellen Texten, Aufsätzen und Vorträgen bevorzugt. 'Zostaliśmy' (wir blieben) – perfektiv, die Entscheidung zu bleiben war abgeschlossen. 'W domu' – Lokativ nach 'w'."},
            {"id": "gp_caus3", "question": "Spóźnił się z _____ korka na drodze.", "translation": "Er kam wegen des Staus auf der Straße zu spät.", "options": ["powodu", "powód", "powodem", "powodom"], "correct": "powodu", "explanation": "'Z powodu' + Genitiv = 'wegen' + Genitiv – Präpositionale Kausalkonstruktion. 'Powodu' ist Genitiv von 'powód' (Grund/Ursache). 'Korka' (Genitiv von 'korek' = Stau) steht ebenfalls im Genitiv als Attribut. Im Deutschen: 'wegen des Staus' – beide Sprachen verwenden den Genitiv! 'Na drodze' (auf der Straße) – Lokativ. Diese nominale Kausalkonstruktion ist formeller als ein Nebensatz."},
            {"id": "gp_caus4", "question": "Dlatego _____ to zrobił, że chciał pomóc.", "translation": "Er hat das deshalb getan, weil er helfen wollte.", "options": ["że", "bo", "aby", "czy"], "correct": "że", "explanation": "'Dlatego...że' (deshalb...weil) – kausale Korrelation. Im Hauptsatz steht 'dlatego' (deshalb), im Nebensatz 'że' (dass/weil). Im Deutschen: 'deshalb...weil'. Beachten Sie die Struktur: Hauptsatz mit 'dlatego' erklärt die TATSACHE, der 'że'-Satz liefert den GRUND. 'Chciał pomóc' (er wollte helfen) – Modalverb im Präteritum + Infinitiv."},
            {"id": "gp_caus5", "question": "_____ temu, że ćwiczył, zdał egzamin.", "translation": "Dadurch, dass er geübt hat, hat er die Prüfung bestanden.", "options": ["Dzięki", "Przez", "Mimo", "Przed"], "correct": "Dzięki", "explanation": "'Dzięki temu, że...' (dank der Tatsache, dass...) – positive Kausalverknüpfung. 'Dzięki' (dank) impliziert ein POSITIVES Ergebnis – man ist dankbar dafür. Im Gegensatz dazu: 'przez to, że' für negative Folgen. Im Deutschen: 'dadurch, dass' oder 'dank der Tatsache, dass'. 'Zdał egzamin' (bestand die Prüfung) – 'zdać' ist perfektiv und zeigt den erfolgreichen Abschluss."},
            {"id": "gp_caus6", "question": "Przez _____, że nie słuchał, popełnił błąd.", "translation": "Dadurch, dass er nicht zuhörte, machte er einen Fehler.", "options": ["to", "ten", "tego", "temu"], "correct": "to", "explanation": "'Przez to, że...' (dadurch, dass... / weil...) – kausale Verknüpfung mit NEGATIVEM Ergebnis. 'Przez' (durch/wegen) + 'to' (das). Im Gegensatz zu 'dzięki temu, że' (positiv) wird 'przez to, że' für unerwünschte Folgen verwendet. 'Popełnił błąd' (machte einen Fehler) – 'popełnić' wird nur mit negativen Substantiven verwendet: błąd, przestępstwo, samobójstwo."},
            {"id": "gp_caus7", "question": "_____ że pada, wezmę parasol.", "translation": "Da es regnet, nehme ich einen Regenschirm.", "options": ["Skoro", "Ale", "Więc", "Chociaż"], "correct": "Skoro", "explanation": "'Skoro' = 'da/wenn schon' – kausaler Konnektor für bekannte/offensichtliche Fakten. Im Deutschen: 'da' (nicht 'weil'!) für bereits bekannte Gründe. 'Skoro pada' impliziert: Wir SEHEN beide, dass es regnet, also ist die Konsequenz klar. 'Wezmę' (ich werde nehmen, perfektiv Futur) zeigt den Entschluss. Diese Feinnuance zwischen 'skoro' und 'bo/ponieważ' ist wichtig für natürliches Polnisch."},
            {"id": "gp_caus8", "question": "Nie mógł spać ze _____ na sytuację.", "translation": "Er konnte vor Sorge über die Situation nicht schlafen.", "options": ["strachu", "strach", "strachem", "strachowi"], "correct": "strachu", "explanation": "'Ze strachu' (vor Angst/aus Angst) – 'z/ze' + Genitiv für kausale Bedeutung emotionaler Zustände. Im Deutschen: 'vor Angst/aus Angst'. Ähnlich: 'z radości' (vor Freude), 'z nudów' (aus Langeweile), 'ze zmęczenia' (vor Müdigkeit). Diese Konstruktion mit 'z' + Genitiv für emotionale Ursachen ist im Polnischen sehr produktiv. 'Na sytuację' (über die Situation) – Akkusativ nach 'na'."},
            {"id": "gp_caus9", "question": "Wskutek _____ wielu ludzi straciło domy.", "translation": "Infolge der Überschwemmung verloren viele Menschen ihre Häuser.", "options": ["powodzi", "powódź", "powodzią", "powodziom"], "correct": "powodzi", "explanation": "'Wskutek' + Genitiv = 'infolge' + Genitiv – formaler Kausalkonnektor, typisch für Schriftsprache und Nachrichten. 'Powodzi' ist Genitiv von 'powódź' (Überschwemmung, feminin). Im Deutschen: 'infolge der Überschwemmung'. 'Straciło' – neutrales Verb für 'domy' (Häuser) als Subjekt? Nein: 'ludzi' ist Subjekt. Korrektur der Analyse: 'wielu ludzi' regiert das Verb."},
            {"id": "gp_caus10", "question": "Na skutek _____ firma zbankrutowała.", "translation": "Infolge der Krise ging die Firma bankrott.", "options": ["kryzysu", "kryzys", "kryzysem", "kryzysowi"], "correct": "kryzysu", "explanation": "'Na skutek' + Genitiv = 'infolge/als Folge' – formaler kausaler Konnektor. 'Kryzysu' ist Genitiv von 'kryzys'. Synonyme Konstruktionen: 'wskutek' (infolge), 'na skutek' (als Folge von), 'w wyniku' (als Ergebnis von) – alle mit Genitiv! Im Deutschen: 'infolge der Krise'. 'Zbankrutowała' (ging bankrott) – perfektiv, weibliche Form wegen 'firma'."},
            {"id": "gp_caus11", "question": "Jako _____ jest odpowiedzialny za budżet.", "translation": "Als Direktor ist er für das Budget verantwortlich.", "options": ["dyrektor", "dyrektora", "dyrektorem", "dyrektorowi"], "correct": "dyrektor", "explanation": "'Jako' (als) + Nominativ – kausale Funktion (in der Eigenschaft als). ACHTUNG: Im Polnischen steht nach 'jako' der Nominativ, nicht der Nominativ wie man erwarten könnte! Im Deutschen: 'als Direktor' (Nominativ). 'Jest odpowiedzialny za' (ist verantwortlich für) + Akkusativ. Die Konstruktion 'jako + Nominativ' ist eine wichtige strukturelle Regel."},
            {"id": "gp_caus12", "question": "Z uwagi _____ pogodę odwołano mecz.", "translation": "Aufgrund des Wetters wurde das Spiel abgesagt.", "options": ["na", "do", "w", "za"], "correct": "na", "explanation": "'Z uwagi na' + Akkusativ = 'aufgrund/angesichts' + Genitiv – formaler Kausalkonnektor. Beachten Sie den Kasusunterschied: Polnisch Akkusativ, Deutsch Genitiv! 'Odwołano' – unpersönliche Vergangenheitsform auf '-no': 'man sagte ab'. Im Deutschen: Passiv 'wurde abgesagt'. 'Pogodę' im Akkusativ nach 'na'. Die '-no/-to'-Konstruktion ist im Polnischen eine typische Alternative zum Passiv."},
            {"id": "gp_caus13", "question": "Ze _____ na wiek nie może pracować.", "translation": "Aufgrund des Alters kann er nicht arbeiten.", "options": ["względu", "względ", "względem", "względowi"], "correct": "względu", "explanation": "'Ze względu na' + Akkusativ = 'aufgrund/mit Rücksicht auf' – formaler Kausalkonnektor. 'Względu' ist Genitiv von 'wzgląd' (Rücksicht/Hinsicht). Im Deutschen: 'aufgrund des Alters' oder 'mit Rücksicht auf das Alter'. 'Na wiek' (auf das Alter) – Akkusativ nach 'na'. 'Nie może pracować' (kann nicht arbeiten) – Modalverb + Infinitiv wie im Deutschen."},
            {"id": "gp_caus14", "question": "Dlaczego to zrobiłeś? – _____ tak chciałem.", "translation": "Warum hast du das getan? – Weil ich es so wollte.", "options": ["Bo", "Więc", "Ale", "Czy"], "correct": "Bo", "explanation": "'Bo' als Antwort auf 'dlaczego?' (warum?) – die direkteste kausale Antwort im Polnischen. Im Deutschen: 'Weil ich es so wollte.' 'Tak chciałem' (ich wollte es so) – 'tak' (so) verstärkt den Willen. In der gesprochenen Sprache wird 'bo' als kurze kausale Begründung bevorzugt. Formeller: 'Ponieważ tak chciałem' oder 'Dlatego, że tak chciałem'. Der simpelste Kausalsatz."},
            {"id": "gp_caus15", "question": "W związku _____ tym proszę o wyjaśnienie.", "translation": "In diesem Zusammenhang bitte ich um eine Erklärung.", "options": ["z", "do", "na", "w"], "correct": "z", "explanation": "'W związku z tym' (in diesem Zusammenhang/hierbei) – formaler Konnektor für offizielle Korrespondenz. 'Z' + Instrumentalis: 'tym' ist Instrumentalis von 'to'. Im Deutschen: 'in diesem Zusammenhang' oder 'diesbezüglich'. 'Proszę o wyjaśnienie' (ich bitte um eine Erklärung) – 'prosić o' + Akkusativ = 'bitten um' + Akkusativ. Dieser Konnektor ist typisch für Geschäftsbriefe und formelle Anfragen."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k: v for k, v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")

# Validate format
issues = 0
for c in data:
    for item in c['items']:
        if '_____' not in item.get('question', ''):
            issues += 1
        if len(item.get('explanation', '')) < 200:
            issues += 1
if issues:
    print(f"FORMAT ISSUES: {issues}")
else:
    print("All format checks passed!")
