#!/usr/bin/env python3
"""Batch 12: Word Formation (categories 63-67) for german_polish grammar.
Correct format: question with _____, translation, options(4), correct, explanation(200+ chars in German)."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "diminutives",
        "name": "Zdrobnienia (Verkleinerungsformen)",
        "description": "Tworzenie zdrobnień w polskim – bogaty system sufiksów zdrabniających",
        "icon": "arrow.down.right.and.arrow.up.left",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_dim1", "question": "Zdrobnienie od 'kot' to _____.", "translation": "(Die Verkleinerungsform von 'Katze' ist...)", "options": ["kotek", "kotisko", "kocur", "kotny"], "correct": "kotek", "explanation": "Das Suffix '-ek' ist die häufigste Verkleinerungsform für maskuline Substantive im Polnischen. 'Kot' (Katze) wird zu 'kotek' (Kätzchen). Im Deutschen verwendet man '-chen' oder '-lein', im Polnischen gibt es ein viel reicheres System mit '-ek', '-ik', '-czek' und weiteren Suffixen, die Zärtlichkeit oder kleine Größe ausdrücken."},
            {"id": "gp_dim2", "question": "Mój mały _____ bawi się w ogrodzie.", "translation": "(Mein kleines Hündchen spielt im Garten.)", "options": ["piesek", "psisko", "psiarz", "psina"], "correct": "piesek", "explanation": "'Piesek' ist die Verkleinerungsform von 'pies' (Hund). Das Suffix '-ek' wird mit dem eingeschobenen '-e-' verbunden. Im Polnischen drücken Diminutive nicht nur kleine Größe aus, sondern auch Zärtlichkeit und emotionale Nähe – 'piesek' klingt liebevoller als das neutrale 'pies'. Ähnlich wie 'Hündchen' im Deutschen."},
            {"id": "gp_dim3", "question": "Chcesz kawałek _____?", "translation": "(Möchtest du ein Stückchen Kuchen?)", "options": ["ciasteczka", "ciastka", "ciastyska", "ciasta"], "correct": "ciasteczka", "explanation": "Doppelte Verkleinerung: 'ciasto' (Kuchen) → 'ciastko' (Küchlein) → 'ciasteczko' (süßes kleines Küchlein). Hier im Genitiv: 'ciasteczka'. Im Polnischen kann man Diminutive stapeln – je mehr Suffixe, desto zärtlicher klingt es. Das ist ein typisches Merkmal slawischer Sprachen, das im Deutschen so nicht existiert."},
            {"id": "gp_dim4", "question": "Mama kupiła mi nowe _____.", "translation": "(Mama hat mir neue Schühchen gekauft.)", "options": ["buciki", "buciory", "buty", "butowiska"], "correct": "buciki", "explanation": "'Buciki' ist die Verkleinerungsform von 'buty' (Schuhe). Das Suffix '-ik/-iki' wird für die Pluralform verwendet. Im Polnischen haben Diminutive im Plural eigene Formen – 'buciki' klingt niedlich (für Kinderschuhe), während 'buty' neutral ist und 'buciory' (Augmentativ) große, klobige Schuhe beschreibt."},
            {"id": "gp_dim5", "question": "Dobranoc, moje _____!", "translation": "(Gute Nacht, mein Sonnenscheinchen!)", "options": ["słoneczko", "słońce", "słonecznik", "słonko"], "correct": "słoneczko", "explanation": "'Słoneczko' ist die Verkleinerungsform von 'słońce' (Sonne) mit dem Suffix '-eczko' für sächliche Substantive. Es wird als liebevolles Kosewort verwendet, ähnlich wie 'Sonnenscheinchen' im Deutschen. 'Słonecznik' wäre die Sonnenblume – aufpassen bei der Verwechslungsgefahr! Im Polnischen sind Diminutive als Kosenamen sehr verbreitet."},
            {"id": "gp_dim6", "question": "Poczekaj _____, zaraz wrócę.", "translation": "(Warte ein Momentchen, ich komme gleich zurück.)", "options": ["chwileczkę", "chwilę", "chwilisko", "momentalnie"], "correct": "chwileczkę", "explanation": "Dreifache Verkleinerung: 'chwila' (Moment) → 'chwilka' → 'chwileczka' → hier im Akkusativ 'chwileczkę'. Je mehr Diminutiv-Suffixe gestapelt werden, desto höflicher und weicher klingt die Bitte. Im Deutschen gibt es kein Äquivalent für diese gestufte Verkleinerung – 'Momentchen' ist die einzige Stufe."},
            {"id": "gp_dim7", "question": "To jest _____ mojej córki.", "translation": "(Das ist das Händchen meiner Tochter.)", "options": ["rączka", "ręka", "rękawica", "ręcznik"], "correct": "rączka", "explanation": "'Rączka' ist die Verkleinerungsform von 'ręka' (Hand). Beachten Sie den Stammwechsel: ę → ą → ącz. Im Polnischen verändern sich bei der Diminutivbildung oft die Stammvokale – das ist eine Besonderheit, die es im Deutschen nicht gibt. 'Ręcznik' (Handtuch) und 'rękawica' (Handschuh) sind Ableitungen, aber keine Diminutive."},
            {"id": "gp_dim8", "question": "Kup mi _____ zupy, proszę.", "translation": "(Kauf mir eine kleine Dose Suppe, bitte.)", "options": ["puszkę", "puszeczkę", "puszkisko", "puszka"], "correct": "puszeczkę", "explanation": "'Puszeczka' ist die Verkleinerungsform von 'puszka' (Dose) – hier im Akkusativ 'puszeczkę'. Das Suffix '-eczka' für feminine Substantive drückt kleine Größe aus. Im Alltagspolnisch werden Diminutive häufig verwendet, um Bitten höflicher zu machen – 'kup mi puszeczkę' klingt weicher und lieber als 'kup mi puszkę'."},
            {"id": "gp_dim9", "question": "Chodź tu, _____!", "translation": "(Komm her, Kätzchen!)", "options": ["kotku", "kotek", "kotisko", "kocur"], "correct": "kotku", "explanation": "'Kotku' ist der Vokativ (Anredefall) von 'kotek' (Kätzchen). Im Polnischen wechselt die Endung '-ek' im Vokativ zu '-ku'. Der Vokativ wird bei direkter Ansprache verwendet – ein grammatischer Fall, den es im Deutschen nicht gibt. 'Kotku' wird auch als Kosewort für nahestehende Personen benutzt (ähnlich wie 'Schatz')."},
            {"id": "gp_dim10", "question": "Mała _____ biegała po podwórku.", "translation": "(Ein kleines Mädchen lief im Hof herum.)", "options": ["dziewczynka", "dziewczyna", "dziewucha", "dziewczysko"], "correct": "dziewczynka", "explanation": "'Dziewczynka' (kleines Mädchen) ist die Verkleinerungsform von 'dziewczyna' (Mädchen/junge Frau). Das Suffix '-ka' ist typisch für feminine Diminutive. Im Polnischen unterscheidet die Diminutivform oft das Alter: 'dziewczyna' = junge Frau/Freundin, 'dziewczynka' = kleines Mädchen. 'Dziewczysko' wäre ein pejorativer Augmentativ."},
            {"id": "gp_dim11", "question": "Daj mi _____ cukru do kawy.", "translation": "(Gib mir ein Löffelchen Zucker in den Kaffee.)", "options": ["łyżeczkę", "łyżkę", "łyżysko", "łyżkarz"], "correct": "łyżeczkę", "explanation": "'Łyżeczka' ist die Verkleinerungsform von 'łyżka' (Löffel) – ein Teelöffel. Im Akkusativ: 'łyżeczkę'. Im Polnischen unterscheidet man durch Diminutive auch Größen bei Küchengeräten: 'łyżka' = Esslöffel, 'łyżeczka' = Teelöffel. Dies hat also nicht nur emotionale, sondern auch praktische Bedeutung in der Alltagssprache."},
            {"id": "gp_dim12", "question": "Lalka córki ma malutkie _____.", "translation": "(Die Puppe der Tochter hat ganz kleine Äuglein.)", "options": ["oczka", "oczy", "oczyszcza", "okucia"], "correct": "oczka", "explanation": "'Oczka' ist die Diminutiv-Pluralform von 'oko' (Auge): oko → oczko → oczka (Plural). Im Polnischen gibt es unregelmäßige Pluralformen bei Körperteilen – 'oczy' (Augen) wird im Diminutiv zu 'oczka' (Äuglein). Dieses Wort kann auch 'Maschen' (beim Stricken) oder 'Punkte' (auf einem Würfel) bedeuten."},
            {"id": "gp_dim13", "question": "Zjedz jeszcze trochę _____.", "translation": "(Iss noch ein bisschen Süppchen.)", "options": ["zupki", "zupy", "zupiska", "zupeczki"], "correct": "zupki", "explanation": "'Zupka' ist die Verkleinerungsform von 'zupa' (Suppe) – hier im Genitiv 'zupki' nach 'trochę'. Diminutive werden im Polnischen besonders bei Essen und Trinken verwendet, um Speisen appetitlicher klingen zu lassen: 'zupka', 'kawka' (Kaffee-chen), 'herbatka' (Teelein). Diese Gewohnheit gibt es im Deutschen kaum."},
            {"id": "gp_dim14", "question": "Popatrz, jaki ładny _____!", "translation": "(Schau, was für ein hübsches Häuschen!)", "options": ["domek", "domisko", "domownik", "domina"], "correct": "domek", "explanation": "'Domek' ist die Verkleinerungsform von 'dom' (Haus) mit dem Suffix '-ek'. 'Domek' kann sowohl ein buchstäblich kleines Haus (Ferienhaus, Gartenhaus) als auch eine liebevolle Bezeichnung sein. Im Deutschen: 'Häuschen'. 'Domisko' wäre der Augmentativ (großes, hässliches Haus), 'domownik' bedeutet Hausbewohner."},
            {"id": "gp_dim15", "question": "Mój _____ jest bardzo grzeczny.", "translation": "(Mein Söhnchen ist sehr brav.)", "options": ["synek", "syn", "synisko", "synowiec"], "correct": "synek", "explanation": "'Synek' ist die Verkleinerungsform von 'syn' (Sohn) mit dem Suffix '-ek'. Wird liebevoll verwendet, besonders von Eltern über jüngere Söhne. Im Polnischen signalisieren Diminutive bei Familienbezeichnungen emotionale Wärme: 'synek' (Söhnchen), 'córeczka' (Töchterchen), 'mamusia' (Mutti), 'tatuś' (Vati). Im Deutschen sind solche Formen seltener."}
        ]
    },
    {
        "key": "prefixes_verbs",
        "name": "Przedrostki czasownikowe (Verbpräfixe)",
        "description": "Wie Präfixe die Bedeutung polnischer Verben verändern – Parallelen zu deutschen trennbaren/untrennbaren Verben",
        "icon": "textformat.abc.dottedunderline",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_pvb1", "question": "Muszę _____ ten list do końca.", "translation": "(Ich muss diesen Brief zu Ende schreiben.)", "options": ["dopisać", "napisać", "wpisać", "spisać"], "correct": "dopisać", "explanation": "Das Präfix 'do-' bedeutet 'hinzu/zu Ende' – 'dopisać' = 'zu Ende schreiben' oder 'etwas hinzufügen'. Vergleichen Sie: 'pisać' (schreiben), 'napisać' (aufschreiben/fertigschreiben), 'wpisać' (eintragen), 'dopisać' (dazuschreiben). Polnische Verbpräfixe funktionieren ähnlich wie deutsche trennbare Vorsilben und verändern die Bedeutung grundlegend."},
            {"id": "gp_pvb2", "question": "Proszę _____ swoje nazwisko w formularzu.", "translation": "(Bitte tragen Sie Ihren Nachnamen ins Formular ein.)", "options": ["wpisać", "opisać", "przepisać", "podpisać"], "correct": "wpisać", "explanation": "Das Präfix 'w-/we-' bedeutet 'hinein' – 'wpisać' = 'eintragen' (wie 'eintragen' im Deutschen). Vergleich: 'pisać' (schreiben) → 'wpisać' (eintragen), 'wejść' (eintreten), 'wjechać' (einfahren). Das Präfix 'w-' entspricht dem deutschen 'ein-' und gibt die Richtung 'nach innen' an. Die Parallele hilft beim Merken."},
            {"id": "gp_pvb3", "question": "Musisz _____ ten dokument.", "translation": "(Du musst dieses Dokument unterschreiben.)", "options": ["podpisać", "opisać", "zapisać", "dopisać"], "correct": "podpisać", "explanation": "Das Präfix 'pod-' bedeutet 'unter' – 'podpisać' = 'unterschreiben' (wörtlich: unter-schreiben). Die Parallele zum Deutschen ist hier perfekt! Weitere 'pod-' Verben: 'podejść' (herangehen), 'podnieść' (hochheben), 'podstawić' (unterstellen). Das Präfix 'pod-' kann 'unter', 'heran' oder 'ein wenig' bedeuten."},
            {"id": "gp_pvb4", "question": "Lekarz mi _____ nowe lekarstwo.", "translation": "(Der Arzt hat mir ein neues Medikament verschrieben.)", "options": ["przepisał", "opisał", "wpisał", "zapisał"], "correct": "przepisał", "explanation": "Das Präfix 'prze-' bedeutet 'durch/über/um-' – 'przepisać' = 'verschreiben' (im medizinischen Sinne) oder 'abschreiben/umschreiben'. Weitere 'prze-' Verben: 'przeczytać' (durchlesen), 'przejechać' (überfahren/durchfahren), 'przerobić' (umarbeiten). Im Deutschen gibt es ähnliche Bedeutungsvielfalt bei 'über-' und 'um-'."},
            {"id": "gp_pvb5", "question": "Pociąg _____ ze stacji o ósmej.", "translation": "(Der Zug fährt um acht vom Bahnhof ab.)", "options": ["odjeżdża", "przyjeżdża", "wyjeżdża", "przejeżdża"], "correct": "odjeżdża", "explanation": "Das Präfix 'od-' bedeutet 'weg/ab' – 'odjechać/odjeżdżać' = 'abfahren'. Perfekte Parallele zum deutschen 'ab-fahren'! Gegenteil: 'przyjechać/przyjeżdżać' (ankommen, wie 'an-kommen'). Die Präfixe 'od-' und 'przy-' bilden ein Gegensatzpaar: 'od-' = weg, 'przy-' = heran. Diese Systematik erleichtert das Lernen erheblich."},
            {"id": "gp_pvb6", "question": "Samolot _____ o godzinie dziesiątej.", "translation": "(Das Flugzeug hebt um zehn Uhr ab.)", "options": ["odlatuje", "przylatuje", "wylatuje", "przelatuje"], "correct": "odlatuje", "explanation": "'Odlatywać/odlecieć' = 'abfliegen' – das Präfix 'od-' (weg) + 'latać/lecieć' (fliegen). Systematik: 'odlatywać' (abfliegen), 'przylatywać' (anfliegen/ankommen), 'wylatywać' (rausfliegen), 'przelatywać' (überfliegen). Die Präfixe funktionieren mit verschiedenen Bewegungsverben nach dem gleichen logischen Muster. Das erleichtert das Lernen."},
            {"id": "gp_pvb7", "question": "Dzieci _____ z domu o siódmej.", "translation": "(Die Kinder gehen um sieben aus dem Haus.)", "options": ["wychodzą", "przychodzą", "odchodzą", "zachodzą"], "correct": "wychodzą", "explanation": "Das Präfix 'wy-' bedeutet 'heraus/aus' – 'wychodzić' = 'ausgehen/hinausgehen' (wie dt. 'aus-gehen'). Gegensatz: 'wchodzić' (hineingehen, 'ein-treten'). Dieses Grundmuster 'w-' (rein) vs. 'wy-' (raus) ist eines der wichtigsten Präfixpaare im Polnischen und hat eine perfekte Parallele im Deutschen: 'ein-' vs. 'aus-'."},
            {"id": "gp_pvb8", "question": "Muszę _____ ten tekst na polski.", "translation": "(Ich muss diesen Text ins Polnische übersetzen.)", "options": ["przetłumaczyć", "wytłumaczyć", "dotłumaczyć", "podtłumaczyć"], "correct": "przetłumaczyć", "explanation": "'Prze-' + 'tłumaczyć' = 'übersetzen' (wörtlich: über-setzen!). Im Gegensatz dazu: 'wytłumaczyć' = 'erklären' (heraus-klären). Das Präfix verändert die Bedeutung grundlegend: gleicher Stamm, völlig andere Bedeutung. Im Polnischen ist das Präfixsystem ähnlich produktiv wie im Deutschen – ein großer Vorteil für deutschsprachige Lernende."},
            {"id": "gp_pvb9", "question": "Trzeba _____ te śmieci.", "translation": "(Man muss diesen Müll wegwerfen.)", "options": ["wyrzucić", "wrzucić", "zrzucić", "porzucić"], "correct": "wyrzucić", "explanation": "'Wy-' (heraus) + 'rzucić' (werfen) = 'wyrzucić' (wegwerfen/rauswerfen). Vergleich: 'wrzucić' (einwerfen/reinwerfen), 'zrzucić' (herunterwerfen), 'porzucić' (aufgeben/verlassen). Alle verwenden den Stamm 'rzucić' (werfen) – das Präfix bestimmt die Richtung. Dieses System ist dem deutschen Trennbare-Verben-System sehr ähnlich."},
            {"id": "gp_pvb10", "question": "Nie mogę _____ tego zadania.", "translation": "(Ich kann diese Aufgabe nicht lösen.)", "options": ["rozwiązać", "zawiązać", "związać", "przywiązać"], "correct": "rozwiązać", "explanation": "'Roz-' bedeutet 'auseinander/los-' – 'rozwiązać' = 'lösen' (ein Problem lösen, wörtlich: auseinanderbinden). Gegensatz: 'zawiązać' (zubinden/zusammenbinden). Weitere 'roz-' Verben: 'rozmawiać' (sich unterhalten, auseinander-sprechen), 'rozbić' (zerbrechen), 'rozumieć' (verstehen, auseinander-nehmen). Wie dt. 'zer-' oder 'aus-'."},
            {"id": "gp_pvb11", "question": "Chcę _____ prezent dla mamy.", "translation": "(Ich möchte ein Geschenk für Mama kaufen.)", "options": ["kupić", "odkupić", "skupić", "wykupić"], "correct": "kupić", "explanation": "Das Grundverb 'kupić' (kaufen) ohne Präfix für einfaches Kaufen. Aber mit Präfixen: 'odkupić' (zurückkaufen), 'skupić' (aufkaufen/zusammenkaufen), 'wykupić' (freikaufen/auskaufen). Das zeigt, wie Präfixe ein Basisverb in viele Bedeutungsvarianten verwandeln – genau wie im Deutschen: kaufen, verkaufen, einkaufen, aufkaufen, auskaufen."},
            {"id": "gp_pvb12", "question": "Proszę _____ ten formularz.", "translation": "(Bitte füllen Sie dieses Formular aus.)", "options": ["wypełnić", "napełnić", "zapełnić", "dopełnić"], "correct": "wypełnić", "explanation": "'Wy-' + 'pełnić' (füllen) = 'wypełnić' (ausfüllen) – perfekte Parallele zu 'aus-füllen'! Vergleich: 'napełnić' (auffüllen/anfüllen), 'zapełnić' (voll-füllen), 'dopełnić' (ergänzen/vervollständigen). Deutschsprachige Lernende können hier die Logik der Präfixe direkt übertragen: 'wy-' = 'aus-', 'na-' = 'an-/auf-', 'za-' = 'voll-/zu-'."},
            {"id": "gp_pvb13", "question": "Samochód _____ przez most.", "translation": "(Das Auto fährt über die Brücke.)", "options": ["przejeżdża", "dojeżdża", "wyjeżdża", "odjeżdża"], "correct": "przejeżdża", "explanation": "'Prze-' (durch/über) + 'jeżdżać' (fahren) = 'przejeżdżać' (durchfahren/überfahren). Wie dt. 'durch-fahren' oder 'über-fahren'. System: 'dojeżdżać' (hin-fahren zu), 'wyjeżdżać' (weg-fahren/ausfahren), 'odjeżdżać' (ab-fahren). Die Bewegungsverben mit Präfixen bilden ein komplett logisches System der Richtungsangaben."},
            {"id": "gp_pvb14", "question": "Deszcz nie _____.", "translation": "(Der Regen hört nicht auf.)", "options": ["przestaje", "zostaje", "nastaje", "powstaje"], "correct": "przestaje", "explanation": "'Prze-' + 'stawać' = 'przestawać' (aufhören). Vergleich: 'zostawać' (bleiben), 'nastawać' (anbrechen, z.B. Nacht), 'powstawać' (entstehen/aufstehen). Alle vom Stamm 'stać/stawać' (stehen/werden). Im Polnischen kann ein Stamm mit verschiedenen Präfixen dutzende verschiedene Verben bilden – wie im Deutschen mit 'stehen': bestehen, verstehen, aufstehen, entstehen."},
            {"id": "gp_pvb15", "question": "Nie _____ tego słowa.", "translation": "(Ich erinnere mich nicht an dieses Wort.)", "options": ["przypomnę", "zapomnę", "wypomnę", "napomnę"], "correct": "przypomnę", "explanation": "'Przy-' + 'pomnieć' = 'przypomnieć' (sich erinnern, wörtlich: heran-denken). Gegensatz: 'zapomnieć' (vergessen, wörtlich: weg-denken). Weitere: 'wypomnieć' (vorwerfen/vorhalten), 'napomnieć' (ermahnen). Beachten Sie: 'przypomnę sobie' (sich erinnern) vs. 'przypomnę komuś' (jemanden erinnern) – die Reflexivität verändert die Bedeutung."}
        ]
    },
    {
        "key": "word_derivation",
        "name": "Słowotwórstwo (Wortbildung)",
        "description": "Tworzenie nowych słów przez sufiksy i złożenia – odpowiedniki niemieckich Suffixe wie -er, -heit, -ung",
        "icon": "puzzlepiece",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_wder1", "question": "Osoba, która uczy, to _____.", "translation": "(Eine Person, die unterrichtet, ist ein/e...)", "options": ["nauczyciel", "uczyciel", "naukarz", "ucznik"], "correct": "nauczyciel", "explanation": "Das Suffix '-ciel' bildet Berufsbezeichnungen von Verben: 'nauczyć' (unterrichten) → 'nauczyciel' (Lehrer). Im Deutschen: '-er' (Lehrer). Weitere Beispiele: 'zbawiciel' (Retter/Erlöser), 'przyjaciel' (Freund). Das Präfix 'na-' + 'uczyć' (lehren) = 'nauczyć' (beibringen). Weibliche Form: 'nauczycielka' (Lehrerin, mit Suffix '-ka' wie dt. '-in')."},
            {"id": "gp_wder2", "question": "Osoba, która pisze książki, to _____.", "translation": "(Eine Person, die Bücher schreibt, ist ein/e...)", "options": ["pisarz", "pisaczka", "pisarnik", "piszący"], "correct": "pisarz", "explanation": "Das Suffix '-arz' bildet Berufsbezeichnungen: 'pisać' (schreiben) → 'pisarz' (Schriftsteller). Wie dt. '-er' in 'Schreiber'. Weitere '-arz' Berufe: 'lekarz' (Arzt), 'piekarz' (Bäcker), 'stolarz' (Tischler). Weibliche Formen: 'pisarka', 'lekarka', 'piekarka'. Im Polnischen gibt es mehrere Suffixe für Berufe: '-arz', '-ciel', '-nik', '-ista'."},
            {"id": "gp_wder3", "question": "Stan bycia wolnym to _____.", "translation": "(Der Zustand, frei zu sein, ist...)", "options": ["wolność", "wolnienie", "wolnik", "wolarz"], "correct": "wolność", "explanation": "Das Suffix '-ość' bildet abstrakte Substantive aus Adjektiven: 'wolny' (frei) → 'wolność' (Freiheit). Direkte Parallele zum Deutschen: '-heit/-keit' (Freiheit). Weitere Beispiele: 'piękny' → 'piękność' (Schönheit), 'ciemny' → 'ciemność' (Dunkelheit), 'pewny' → 'pewność' (Sicherheit). Dieses Muster ist sehr produktiv und regelmäßig."},
            {"id": "gp_wder4", "question": "Lekarka to _____ forma słowa 'lekarz'.", "translation": "(Ärztin ist die _____ Form des Wortes 'Arzt'.)", "options": ["żeńska", "męska", "nijaka", "podwójna"], "correct": "żeńska", "explanation": "Das Suffix '-ka' bildet weibliche Berufsformen: 'lekarz' → 'lekarka' (Ärztin), wie dt. '-in' (Arzt → Ärztin). Im Polnischen ist die feminine Berufsform grammatisch immer feminin und verändert die Deklination. Weitere Paare: 'nauczyciel/nauczycielka', 'sprzedawca/sprzedawczyni', 'aktor/aktorka'. Dies ist ein sehr produktives Wortbildungsmuster."},
            {"id": "gp_wder5", "question": "Stół drewniany jest zrobiony z _____.", "translation": "(Ein Holztisch ist aus _____ gemacht.)", "options": ["drewna", "drzewa", "drewnianości", "drewniku"], "correct": "drewna", "explanation": "'Drewno' (Holz, Genitiv: drewna) → 'drewniany' (hölzern/aus Holz). Das Suffix '-any/-iany' bildet Materialadjektive: 'skóra' → 'skórzany' (aus Leder), 'szkło' → 'szklany' (aus Glas), 'metal' → 'metalowy' (aus Metall). Im Deutschen verwendet man oft Komposita (Holztisch) oder 'aus + Material', im Polnischen spezielle Adjektivsuffixe."},
            {"id": "gp_wder6", "question": "Osoba z Niemiec to _____.", "translation": "(Eine Person aus Deutschland ist ein/e...)", "options": ["Niemiec", "Niemca", "Niemiecko", "Niemczak"], "correct": "Niemiec", "explanation": "'Niemiec' (Deutscher) – Nationalitätsbezeichnung. Ableitungen: 'Niemiec' (Deutscher) → 'niemiecki' (deutsch, Adjektiv) → 'po niemiecku' (auf Deutsch, Adverb). Weiblich: 'Niemka' (Deutsche). Deutschland: 'Niemcy' (wörtlich: die Deutschen, Plural!). Im Polnischen werden Nationalitäten immer großgeschrieben, Adjektive und Adverbien aber klein."},
            {"id": "gp_wder7", "question": "Człowiek bez pracy to osoba _____.", "translation": "(Ein Mensch ohne Arbeit ist eine _____ Person.)", "options": ["bezrobotna", "bezrobocza", "niepracowa", "odrobotna"], "correct": "bezrobotna", "explanation": "Das Präfix 'bez-' (ohne) + 'robota' (Arbeit) + '-ny' (Adjektivsuffix) = 'bezrobotny' (arbeitslos). Perfekte Parallele zum Deutschen: 'arbeits-los'. Weitere 'bez-' Ableitungen: 'bezdomny' (obdachlos), 'bezsilny' (kraftlos), 'bezsenny' (schlaflos). Das Muster 'bez- + Substantiv + -ny' ist produktiv und dem deutschen '-los' sehr ähnlich."},
            {"id": "gp_wder8", "question": "Przeciwieństwo słowa 'możliwy' to _____.", "translation": "(Das Gegenteil von 'möglich' ist...)", "options": ["niemożliwy", "bezmożliwy", "odmożliwy", "przemożliwy"], "correct": "niemożliwy", "explanation": "Das Präfix 'nie-' negiert Adjektive: 'możliwy' (möglich) → 'niemożliwy' (unmöglich). Genau wie dt. 'un-': 'möglich' → 'un-möglich'. Weitere: 'dobry' → 'niedobry' (ungut), 'pewny' → 'niepewny' (unsicher), 'cierpliwy' → 'niecierpliwy' (ungeduldig). Im Polnischen werden diese Formen zusammengeschrieben, im Gegensatz zu 'nie' als separates Wort bei Verben."},
            {"id": "gp_wder9", "question": "Miejsce, gdzie piecze się chleb, to _____.", "translation": "(Der Ort, wo Brot gebacken wird, ist...)", "options": ["piekarnia", "piekarz", "piekło", "piekarnia"], "correct": "piekarnia", "explanation": "Das Suffix '-arnia/-alnia' bildet Ortsbezeichnungen: 'piec' (backen) → 'piekarnia' (Bäckerei). Wie dt. '-ei' (Bäcker-ei). Weitere: 'kawiarnia' (Café, von 'kawa'), 'księgarnia' (Buchhandlung, von 'księga'), 'pralnia' (Wäscherei, von 'prać'). Im Polnischen kann man am Suffix erkennen, ob es sich um eine Person (-arz), einen Ort (-arnia) oder eine Eigenschaft (-ość) handelt."},
            {"id": "gp_wder10", "question": "Samochód = samo + _____.", "translation": "(Automobil = selbst + _____.)", "options": ["chód", "jazda", "ruch", "bieg"], "correct": "chód", "explanation": "'Samochód' (Auto) = 'samo' (selbst) + 'chód' (Gang/Gehen). Genau wie 'Auto-mobil' = 'selbst-beweglich'. Im Polnischen gibt es weniger Komposita als im Deutschen, aber wenn sie existieren, folgen sie ähnlichen Mustern: 'parowóz' (Dampflok: Dampf+Fuhrwerk), 'lodołamacz' (Eisbrecher: Eis+Brecher), 'samolot' (Flugzeug: selbst+Flug)."},
            {"id": "gp_wder11", "question": "Czynność czytania to _____.", "translation": "(Die Tätigkeit des Lesens ist...)", "options": ["czytanie", "czytarka", "czytnictwo", "czytka"], "correct": "czytanie", "explanation": "Das Suffix '-anie/-enie' bildet Verbalsubstantive (Gerundien): 'czytać' (lesen) → 'czytanie' (das Lesen). Wie die Nominalisierung im Deutschen: 'das Lesen', 'das Schreiben'. Weitere: 'pisanie' (das Schreiben), 'gotowanie' (das Kochen), 'uczenie' (das Lernen). Im Polnischen sind diese Formen Neutra und werden wie normale Substantive dekliniert."},
            {"id": "gp_wder12", "question": "Mieszkaniec Warszawy to _____.", "translation": "(Ein Einwohner Warschaus ist ein...)", "options": ["warszawiak", "warszawianin", "warszawczyk", "warszawiec"], "correct": "warszawiak", "explanation": "'Warszawiak' = Bewohner Warschaus (umgangssprachlich). Formal: 'warszawianin'. Die Suffixe '-ak', '-anin', '-czyk' bilden Einwohnerbezeichnungen: 'krakowiak/krakowianin' (Krakauer), 'poznaniak' (Posener). Im Deutschen: '-er' (Berliner, Warschauer). '-ak' ist umgangssprachlicher und emotionaler, '-anin' ist die formelle Literaturform."},
            {"id": "gp_wder13", "question": "Urządzenie do prania to _____.", "translation": "(Ein Gerät zum Waschen ist eine...)", "options": ["pralka", "praczka", "pranie", "prarka"], "correct": "pralka", "explanation": "Das Suffix '-ka' (für Geräte) + Verbstamm: 'prać' (waschen) → 'pralka' (Waschmaschine). Weitere Gerätesuffixe: 'zmywarka' (Spülmaschine, von 'zmywać'), 'suszarka' (Trockner, von 'suszyć'), 'drukarka' (Drucker, von 'drukować'). Im Deutschen bildet man Komposita (Wasch-Maschine), im Polnischen verwendet man Suffixe zur Gerätebildung."},
            {"id": "gp_wder14", "question": "Nauka o gwiazdach to _____.", "translation": "(Die Wissenschaft von den Sternen ist...)", "options": ["astronomia", "gwiazdoznawstwo", "gwiazdarnia", "gwiazdówka"], "correct": "astronomia", "explanation": "Im Polnischen gibt es zwei Strategien für Wissenschaftsbezeichnungen: internationale Wörter ('astronomia', 'biologia') und slawische Formen mit '-znawstwo' oder '-ologia'. 'Gwiazdoznawstwo' existiert als rein polnische Alternative (gwiazda + znawstwo = Stern + Kunde). In der Praxis werden internationale Formen bevorzugt, ähnlich wie im Deutschen."},
            {"id": "gp_wder15", "question": "Liczba mnoga od 'dziecko' to _____.", "translation": "(Der Plural von 'Kind' ist...)", "options": ["dzieci", "dziecka", "dzieciaki", "dzieciska"], "correct": "dzieci", "explanation": "'Dziecko' → 'dzieci' – ein unregelmäßiger Plural mit Stammwechsel (wie dt. 'Kind' → 'Kinder'). Im Polnischen gibt es bei der Wortbildung häufig Stammwechsel (Ablaut) – ein Phänomen, das auch im Deutschen existiert. 'Dzieciaki' (Kinder/Kids) ist eine umgangssprachliche Ableitung mit dem Suffix '-ak/-aki'. Die richtige Pluralform ist entscheidend für korrekte Deklination."}
        ]
    },
    {
        "key": "compound_words",
        "name": "Złożenia (Zusammensetzungen)",
        "description": "Polnische Komposita und Mehrwortausdrücke – im Vergleich zu den deutschen Riesenwörtern",
        "icon": "rectangle.split.2x1",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_comp1", "question": "Polskie słowo na 'Flugzeug' to _____.", "translation": "(Das polnische Wort für 'Flugzeug' ist...)", "options": ["samolot", "samolatacz", "lotnik", "latawiec"], "correct": "samolot", "explanation": "'Samolot' = 'samo' (selbst) + 'lot' (Flug) = Flugzeug. Wie dt. 'Flug-zeug' oder 'Aero-plan'. Im Polnischen gibt es weniger Komposita als im Deutschen, aber die existierenden folgen logischen Mustern. 'Lotnik' wäre der Flieger/Pilot, 'latawiec' der Drachen (Spielzeug). Das Wort 'samolot' zeigt das polonische Kompositionsmuster Adverb + Substantiv."},
            {"id": "gp_comp2", "question": "Niemieckie 'Zahnbürste' to po polsku _____.", "translation": "(Die deutsche 'Zahnbürste' heißt auf Polnisch...)", "options": ["szczoteczka do zębów", "zęboszczotka", "szczotka zębowa", "zębówka"], "correct": "szczoteczka do zębów", "explanation": "Im Polnischen: 'szczoteczka do zębów' (Bürstchen zu Zähnen) – eine Nominalphrase mit Präposition statt eines Kompositums. Im Deutschen: ein Wort 'Zahnbürste'. Das ist der Hauptunterschied: Deutsch bildet lange Komposita, Polnisch verwendet Mehrwortausdrücke mit Präpositionen ('do', 'na', 'z') oder Adjektive. Dies macht polnische Ausdrücke länger, aber transparenter."},
            {"id": "gp_comp3", "question": "Niemiecki 'Kühlschrank' to po polsku _____.", "translation": "(Der deutsche 'Kühlschrank' heißt auf Polnisch...)", "options": ["lodówka", "zimnioszafka", "chłodniczka", "mrożarka"], "correct": "lodówka", "explanation": "'Lodówka' (Kühlschrank) kommt von 'lód' (Eis) + Suffix '-ówka'. Im Polnischen werden viele Haushaltsgeräte durch Suffixe gebildet statt durch Komposition: 'lodówka' (Kühlschrank), 'zmywarka' (Geschirrspüler), 'suszarka' (Trockner). Das deutsche System der Komposita (Kühl-Schrank) beschreibt Funktion + Form, das polnische leitet vom Material oder der Funktion ab."},
            {"id": "gp_comp4", "question": "Niemiecki 'Geburtstagskuchen' to po polsku _____.", "translation": "(Der deutsche 'Geburtstagskuchen' heißt auf Polnisch...)", "options": ["tort urodzinowy", "urodzinociasto", "tortodzień", "ciasto urodzin"], "correct": "tort urodzinowy", "explanation": "'Tort urodzinowy' = Substantiv + Adjektiv (Geburtstags-Kuchen). Im Polnischen wird das deutsche Kompositum in Substantiv + Adjektiv aufgelöst: 'urodzinowy' (Geburtstags-) von 'urodziny' (Geburtstag). Das Adjektiv stimmt mit dem Substantiv in Genus, Numerus und Kasus überein – das ist ein fundamentaler Unterschied zum Deutschen, wo Komposita unveränderlich sind."},
            {"id": "gp_comp5", "question": "'Haftpflichtversicherung' to po polsku ubezpieczenie od _____ cywilnej.", "translation": "('Haftpflichtversicherung' ist auf Polnisch eine Versicherung von _____ Haftung.)", "options": ["odpowiedzialności", "odpowiedzi", "odpowiedzialnej", "odpowiedzenia"], "correct": "odpowiedzialności", "explanation": "'Ubezpieczenie od odpowiedzialności cywilnej' (OC) – ein Fünf-Wort-Ausdruck für ein deutsches Kompositum. 'Odpowiedzialność' (Verantwortung/Haftung) im Genitiv nach 'od'. Im Deutschen wird alles in ein Wort gepackt, im Polnischen in eine Nominalphrase mit Kasus und Adjektiv aufgelöst. Die Abkürzung 'OC' wird im Alltag verwendet."},
            {"id": "gp_comp6", "question": "Maszyna do _____  to 'Waschmaschine'.", "translation": "(Eine Maschine zum _____ ist eine 'Waschmaschine'.)", "options": ["prania", "prać", "pralki", "pranego"], "correct": "prania", "explanation": "'Maszyna do prania' (Maschine zum Waschen) – wörtliche Übersetzung, aber im Alltag sagt man 'pralka' (Kurzform mit Suffix '-ka'). 'Prania' ist der Genitiv des Verbalsubstantivs 'pranie' (das Waschen). Nach der Präposition 'do' (zu/für) steht immer der Genitiv. Diese Konstruktion 'do + Genitiv' ist im Polnischen sehr häufig, um Zweck/Funktion auszudrücken."},
            {"id": "gp_comp7", "question": "Człowiek z innego kraju to _____.", "translation": "(Ein Mensch aus einem anderen Land ist ein...)", "options": ["cudzoziemiec", "obcokrajnik", "zagranicznik", "innoziemca"], "correct": "cudzoziemiec", "explanation": "'Cudzoziemiec' = 'cudzo' (fremd) + 'ziemia' (Land/Erde) + '-iec' (Suffix). Wie dt. 'Aus-länder'. Das ist eines der wenigen echten Komposita im Polnischen. 'Obcokrajowiec' ist ein Synonym (obcy + kraj + -owiec). Beide Wörter zeigen, dass Polnisch durchaus Komposita bilden kann, dies aber seltener tut als Deutsch."},
            {"id": "gp_comp8", "question": "Polskie określenie na 'schwarz-weiß' to _____.", "translation": "(Der polnische Ausdruck für 'schwarz-weiß' ist...)", "options": ["czarno-biały", "czarnobiały", "czarny-biały", "biało-czarny"], "correct": "czarno-biały", "explanation": "'Czarno-biały' (schwarz-weiß) – Adverb + Adjektiv mit Bindestrich. Im Polnischen werden zusammengesetzte Adjektive mit Bindestrich geschrieben: 'ciemno-niebieski' (dunkelblau), 'jasno-zielony' (hellgrün), 'północno-wschodni' (nordöstlich). Der erste Teil steht als Adverb, der zweite als dekliniertes Adjektiv. Ähnliche Struktur wie im Deutschen."},
            {"id": "gp_comp9", "question": "Pokój, w którym się sypia, to _____.", "translation": "(Ein Zimmer, in dem man schläft, ist ein...)", "options": ["sypialnia", "spalniak", "śpiochownia", "nocownia"], "correct": "sypialnia", "explanation": "'Sypialnia' (Schlafzimmer) = 'sypiać' (schlafen) + '-alnia' (Raum-Suffix). Wie dt. 'Schlaf-zimmer'. Weitere '-alnia' Räume: 'jadalnia' (Esszimmer, von 'jadać'), 'pralnia' (Waschküche, von 'prać'), 'czytelnia' (Lesesaal, von 'czytać'). Das Suffix '-alnia/-elnia' markiert Räume, in denen eine Tätigkeit ausgeführt wird. Im Deutschen: Kompositum mit '-zimmer' oder '-raum'."},
            {"id": "gp_comp10", "question": "Ktoś, kto łamie lód, to _____.", "translation": "(Jemand/etwas, der/das Eis bricht, ist ein...)", "options": ["lodołamacz", "lodowiec", "lodówa", "lodołom"], "correct": "lodołamacz", "explanation": "'Lodołamacz' (Eisbrecher) = 'lód' (Eis) + 'o' (Bindeglied) + 'łamacz' (Brecher). Perfektes Kompositum wie dt. 'Eis-brecher'. Das Bindeglied '-o-' verbindet die zwei Teile – es erscheint bei den meisten polnischen Komposita: 'parowóz' (Dampflok: Dampf + Wagen), 'samolot' (Flugzeug: selbst + Flug). Im Polnischen sind solche Komposita selten, aber wenn sie existieren, folgen sie diesem Muster."},
            {"id": "gp_comp11", "question": "Miejsce, gdzie sprzedaje się książki, to _____.", "translation": "(Ein Ort, wo Bücher verkauft werden, ist ein...)", "options": ["księgarnia", "książkownia", "książkosklep", "bibliownia"], "correct": "księgarnia", "explanation": "'Księgarnia' (Buchhandlung) = 'księga' (Buch, alte Form) + '-arnia' (Geschäfts-/Ortsuffix). Nicht vom modernen 'książka' (Buch), sondern von der älteren 'księga' abgeleitet. Im Deutschen: 'Buchhandlung' (Kompositum). Polnische Geschäftsbezeichnungen verwenden Suffixe: '-arnia' (piekarnia/Bäckerei), '-ernia' (cukiernia/Konditorei), '-ownia' (kwiaciarnia/Blumenladen)."},
            {"id": "gp_comp12", "question": "Urządzenie, które mierzy temperaturę, to _____.", "translation": "(Ein Gerät, das die Temperatur misst, ist ein...)", "options": ["termometr", "ciepłomierz", "temperówka", "mierniczka"], "correct": "termometr", "explanation": "Wie im Deutschen werden auch im Polnischen viele technische/wissenschaftliche Begriffe aus dem Griechischen/Lateinischen übernommen: 'termometr' = 'Thermometer'. Die rein polnische Alternative 'ciepłomierz' (ciepło + mierz = Wärme + Messer) existiert, wird aber seltener verwendet. Im Alltag dominieren internationale Wörter bei technischen Begriffen – ein Vorteil für Deutschsprachige!"},
            {"id": "gp_comp13", "question": "Urządzenie do odkurzania to _____.", "translation": "(Ein Gerät zum Staubsaugen ist ein...)", "options": ["odkurzacz", "kurzowyciąg", "pylozbiór", "kurzarka"], "correct": "odkurzacz", "explanation": "'Odkurzacz' (Staubsauger) = 'od-' (weg/ent-) + 'kurz' (Staub) + '-acz' (Agentiv-Suffix). Wörtlich: 'Ent-stauber'. Im Deutschen: 'Staub-sauger' (Staub + saugen). Beide Sprachen bilden das Wort logisch, aber mit unterschiedlichen Strategien: Polnisch mit Präfix + Suffix, Deutsch als Kompositum. Das Suffix '-acz' bildet Ausführende: 'nadawca' (Sender), 'odbiorca' (Empfänger)."},
            {"id": "gp_comp14", "question": "Osoba, która gra na scenie, to _____.", "translation": "(Eine Person, die auf der Bühne spielt, ist ein/e...)", "options": ["aktor", "scenowiec", "gracznik", "odtwarzacz"], "correct": "aktor", "explanation": "'Aktor' (Schauspieler) – internationales Lehnwort aus dem Lateinischen. Im Polnischen werden viele Berufe mit internationalen Wörtern bezeichnet: 'aktor', 'reżyser', 'muzyk'. Weiblich: 'aktorka' (Schauspielerin, Suffix '-ka'). Das rein polnische Äquivalent wäre 'odtwórca' (Nachschöpfer), aber 'aktor' ist gebräuchlicher. Für Deutschsprachige ist das vorteilhaft – viele Wörter sind ähnlich!"},
            {"id": "gp_comp15", "question": "Dwie części złożenia 'samochód' to 'samo' i _____.", "translation": "(Die zwei Teile der Zusammensetzung 'samochód' sind 'samo' und...)", "options": ["chód", "jechać", "ruch", "auto"], "correct": "chód", "explanation": "'Samochód' (Auto) = 'samo' (selbst) + 'chód' (Gang/Lauf, von 'chodzić' = gehen). Wörtlich: 'Selbstgänger'. Wie 'Auto-mobil' (selbst-beweglich). Das Verständnis der Bestandteile hilft beim Vokabellernen: wenn Sie 'chód' (Gang) kennen, verstehen Sie auch 'piechota' (Infanterie/zu Fuß), 'przechodzień' (Passant), 'chodnik' (Gehweg/Bürgersteig). Etymologie erleichtert das Merken!"}
        ]
    },
    {
        "key": "passive_voice",
        "name": "Strona bierna (Passiv)",
        "description": "Bildung und Verwendung des Passivs im Polnischen – mit und ohne die unpersönliche -no/-to Form",
        "icon": "arrow.uturn.left",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_pass1", "question": "Książka została _____ przez autora.", "translation": "(Das Buch wurde vom Autor geschrieben.)", "options": ["napisana", "napisany", "napisane", "napisani"], "correct": "napisana", "explanation": "Im Passiv mit 'zostać' (werden) muss das Partizip mit dem Subjekt in Genus und Numerus übereinstimmen: 'książka' (Buch) ist feminin → 'napisana' (geschrieben, fem.). Maskulin wäre 'napisany', sächlich 'napisane'. Im Deutschen bleibt das Partizip unveränderlich ('geschrieben'), im Polnischen wird es dekliniert – ein wichtiger Unterschied!"},
            {"id": "gp_pass2", "question": "W Polsce mówi _____ po polsku.", "translation": "(In Polen spricht man Polnisch.)", "options": ["się", "oni", "ktoś", "to"], "correct": "się", "explanation": "Die Reflexivform 'mówi się' (man spricht) ist die häufigste Alternative zum deutschen 'man + Verb'. Im Polnischen gibt es kein Wort für 'man' – stattdessen verwendet man 'się' (sich) mit der 3. Person Singular. 'Mówi się' = es spricht sich = man spricht. Diese Konstruktion ist im Alltagspolnisch viel häufiger als das formale Passiv mit 'zostać'."},
            {"id": "gp_pass3", "question": "Okno _____ otwarte przez nauczyciela.", "translation": "(Das Fenster wurde vom Lehrer geöffnet.)", "options": ["zostało", "została", "został", "zostali"], "correct": "zostało", "explanation": "'Okno' (Fenster) ist sächlich (neutrum) → 'zostało' (wurde, sächlich). Das Hilfsverb 'zostać' im Passiv stimmt mit dem Subjekt in Genus überein: 'został' (mask.), 'została' (fem.), 'zostało' (sächl.), 'zostali/zostały' (Plural). Im Deutschen ist 'wurde' immer gleich – das polnische Passiv erfordert Genus-Bewusstsein, was für Deutschsprachige oft schwierig ist."},
            {"id": "gp_pass4", "question": "Zbudowano nowy _____.", "translation": "(Man hat eine neue Brücke gebaut.)", "options": ["most", "mostu", "mostem", "moście"], "correct": "most", "explanation": "Die Form '-no/-to' ist eine einzigartige polnische unpersönliche Vergangenheitsform: 'zbudowano' (man hat gebaut). Nach dieser Form steht das Objekt im Akkusativ: 'most' (Brücke, Akk. = Nom. bei maskulin unbelebt). Diese Form hat kein deutsches Äquivalent – sie kombiniert Passiv + Vergangenheit + Unpersönlichkeit in einer einzigen Verbform. Sehr häufig in Nachrichten und offiziellen Texten."},
            {"id": "gp_pass5", "question": "Nie _____ tu palić.", "translation": "(Hier darf nicht geraucht werden.)", "options": ["wolno", "można", "trzeba", "warto"], "correct": "wolno", "explanation": "'Nie wolno' (es ist nicht erlaubt/man darf nicht) – unpersönliches Verbot. Im Polnischen gibt es eine ganze Reihe unpersönlicher Modalausdrücke: 'wolno' (erlaubt), 'można' (möglich/darf), 'trzeba' (muss/soll), 'warto' (lohnt sich). Diese ersetzen oft das deutsche Passiv: 'Hier darf nicht geraucht werden' → 'Nie wolno tu palić' – viel kürzer und natürlicher."},
            {"id": "gp_pass6", "question": "Ta piosenka jest _____ na całym świecie.", "translation": "(Dieses Lied wird auf der ganzen Welt gesungen.)", "options": ["śpiewana", "śpiewany", "śpiewane", "śpiewani"], "correct": "śpiewana", "explanation": "Zustandspassiv mit 'być' (sein) + Partizip: 'piosenka' (Lied) ist feminin → 'jest śpiewana' (wird gesungen). Das Zustandspassiv mit 'być' beschreibt wiederholte/andauernde Handlungen, während 'zostać' einmalige abgeschlossene Handlungen beschreibt. Vergleich: 'jest śpiewana' (wird gesungen) vs. 'została zaśpiewana' (wurde gesungen, einmal)."},
            {"id": "gp_pass7", "question": "Dyrektor _____ wybrany przez pracowników.", "translation": "(Der Direktor wurde von den Mitarbeitern gewählt.)", "options": ["został", "została", "zostało", "zostali"], "correct": "został", "explanation": "'Dyrektor' ist maskulin-belebt → 'został' (wurde, mask.). Bei männlichen Personen im Passiv: 'został wybrany' (wurde gewählt). Beachten Sie den Agens (Handelnden): 'przez pracowników' (von den Mitarbeitern) – 'przez' + Akkusativ, wie dt. 'von' + Dativ im Passiv. Die Präposition ist anders: Polnisch 'przez' (durch), Deutsch 'von'."},
            {"id": "gp_pass8", "question": "_____ wszystko, co było do zrobienia.", "translation": "(Man hat alles getan, was zu tun war.)", "options": ["Zrobiono", "Zrobiło się", "Zostało zrobione", "Zrobili"], "correct": "Zrobiono", "explanation": "Die '-no/-to' Form ist die natürlichste Art, unpersönliche Vergangenheit auszudrücken: 'zrobiono' (man hat getan). Sie ist kürzer und idiomatischer als das volle Passiv 'zostało zrobione'. Bildung: Infinitivstamm + '-no' (nach Vokal) oder '-to' (nach Konsonant): 'zrobić' → 'zrobiono', 'wypić' → 'wypito', 'przeczytać' → 'przeczytano'. Eine der markantesten Besonderheiten der polnischen Grammatik."},
            {"id": "gp_pass9", "question": "Te książki _____ czytane przez studentów.", "translation": "(Diese Bücher werden von Studenten gelesen.)", "options": ["są", "jest", "było", "został"], "correct": "są", "explanation": "'Książki' (Bücher) ist Plural → 'są czytane' (werden gelesen, Pl.). Das Partizip im Plural: 'czytane' (nicht-maskulin-personal Plural). Im Polnischen gibt es im Plural zwei Formen: 'czytani' (maskulin-personal, für Männergruppen) und 'czytane' (alle anderen). Diese Unterscheidung existiert im Deutschen nicht und ist eine Besonderheit des polnischen Pluralsystems."},
            {"id": "gp_pass10", "question": "Czy da _____ to naprawić?", "translation": "(Kann man das reparieren? / Lässt sich das reparieren?)", "options": ["się", "on", "im", "nam"], "correct": "się", "explanation": "'Da się' (es lässt sich / man kann) ist eine sehr häufige unpersönliche Konstruktion: 'Da się to naprawić?' (Lässt sich das reparieren?). Negation: 'Nie da się' (es lässt sich nicht). Diese Konstruktion entspricht dem deutschen 'sich lassen' + Infinitiv. Sie drückt Machbarkeit aus, ohne einen Handelnden zu nennen – ein typisch polnisches Muster für Alltagsfragen."},
            {"id": "gp_pass11", "question": "List _____ pisany przez godzinę.", "translation": "(Der Brief wurde eine Stunde lang geschrieben.)", "options": ["był", "została", "zostało", "byli"], "correct": "był", "explanation": "'List' (Brief) ist maskulin → 'był pisany' (wurde geschrieben, mask.). Zustandspassiv 'był pisany' (imperfektiv) betont die Dauer der Handlung (eine Stunde lang). Vergleich: 'był pisany' (war am Geschriebenwerden, Dauer) vs. 'został napisany' (wurde fertig geschrieben, Abschluss). Diese Aspektunterscheidung im Passiv ist typisch für das Polnische."},
            {"id": "gp_pass12", "question": "Wszystkie bilety zostały _____.", "translation": "(Alle Tickets wurden verkauft.)", "options": ["sprzedane", "sprzedany", "sprzedana", "sprzedani"], "correct": "sprzedane", "explanation": "'Bilety' (Tickets) ist Plural nicht-maskulin-personal → 'sprzedane' (verkauft, Pl. nicht-mask.-pers.). Im Polnischen hat der Plural zwei Formen: 'sprzedani' (für maskulin-personale Gruppen, z.B. Männer, die verkauft wurden) und 'sprzedane' (für alle anderen: Dinge, Tiere, Frauen). Diese Unterscheidung ist im Passiv besonders wichtig und fehlt im Deutschen komplett."},
            {"id": "gp_pass13", "question": "Ojciec jest _____ przez dzieci.", "translation": "(Der Vater wird von den Kindern geliebt.)", "options": ["kochany", "kochana", "kochane", "kochani"], "correct": "kochany", "explanation": "'Ojciec' (Vater) ist maskulin-belebt → 'kochany' (geliebt, mask.). Das Zustandspassiv 'jest kochany' beschreibt einen andauernden Zustand (wird geliebt). 'Kochany' wird auch als Anrede verwendet: 'Kochany Janie!' (Lieber Jan!). Im Polnischen verschmelzen Partizipien und Adjektive oft – 'kochany' kann Partizip (geliebt) oder Adjektiv (lieb/beliebt) sein."},
            {"id": "gp_pass14", "question": "_____ nam tu wejść?", "translation": "(Dürfen wir hier eintreten?)", "options": ["Czy można", "Czy trzeba", "Czy warto", "Czy należy"], "correct": "Czy można", "explanation": "'Czy można' (darf/kann man?) ist die unpersönliche Erlaubnisfrage – viel häufiger als Passiv. 'Można' (man kann/darf) ist eines der wichtigsten unpersönlichen Modalwörter: 'Można tu parkować?' (Darf man hier parken?). Im Deutschen würde man 'Darf man...?' oder Passiv verwenden. Das polnische 'można' ist kürzer und idiomatischer als jede Passivkonstruktion."},
            {"id": "gp_pass15", "question": "Tort _____ upieczony przez babcię.", "translation": "(Die Torte wurde von der Großmutter gebacken.)", "options": ["został", "została", "zostało", "zostali"], "correct": "został", "explanation": "'Tort' (Torte) ist maskulin im Polnischen (!) → 'został upieczony' (wurde gebacken, mask.). Achtung: 'tort' ist im Polnischen maskulin, obwohl 'die Torte' im Deutschen feminin ist! Das grammatische Geschlecht unterscheidet sich oft zwischen den Sprachen. Im Passiv muss 'zostać' und das Partizip immer zum polnischen Genus passen, nicht zum deutschen – ein häufiger Fehler bei Deutschsprachigen."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")
