#!/usr/bin/env python3
"""Batch 15: cats 77-81 for german_polish grammar.
Categories: concession_clauses, time_clauses_advanced, polish_formal_register,
            polish_colloquial, idiomatic_expressions
"""
import json
from collections import Counter

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "concession_clauses",
        "name": "Zdania przyzwalające (Konzessivsätze)",
        "description": "Wyrażanie ustępstwa i kontrastu – chociaż, mimo że, pomimo, choć",
        "icon": "arrow.triangle.swap",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_conc1", "question": "_____ padało, poszliśmy na spacer.", "translation": "Obwohl es regnete, gingen wir spazieren.", "options": ["Chociaż", "Dlatego", "Więc", "Bo"], "correct": "Chociaż", "explanation": "'Chociaż' = 'obwohl' – der häufigste konzessive Konnektor im Polnischen. Im Gegensatz zum Deutschen ändert 'chociaż' die Wortstellung nicht – das Verb bleibt an seiner normalen Position. Im Deutschen schickt 'obwohl' das Verb ans Ende des Nebensatzes: 'obwohl es regnete'. 'Poszliśmy' (wir gingen, perfektiv) zeigt die abgeschlossene Handlung des Spazierengehens trotz des Regens."},
            {"id": "gp_conc2", "question": "Mimo _____ pracował ciężko, nie zdał egzaminu.", "translation": "Obwohl er schwer gearbeitet hat, hat er die Prüfung nicht bestanden.", "options": ["że", "gdy", "bo", "jak"], "correct": "że", "explanation": "'Mimo że' = 'obwohl/trotz der Tatsache, dass' – formellere Variante von 'chociaż'. Im Deutschen: 'obwohl' oder 'trotzdem, dass'. 'Mimo że' betont stärker den Widerspruch zwischen Ursache und Ergebnis. 'Nie zdał egzaminu' – Genitiv 'egzaminu' nach verneintem Verb (statt Akkusativ 'egzamin'). Diese Genitivregel bei Verneinung ist eine typisch polnische Grammatikbesonderheit."},
            {"id": "gp_conc3", "question": "_____ jest zmęczony, nadal pracuje.", "translation": "Obgleich er müde ist, arbeitet er weiter.", "options": ["Choć", "Więc", "Bo", "Ale"], "correct": "Choć", "explanation": "'Choć' ist die verkürzte Form von 'chociaż' (obwohl/obgleich) – etwas literarischer und eleganter. Im Deutschen: 'obgleich' als gehobene Variante von 'obwohl'. 'Nadal pracuje' (arbeitet weiter/nach wie vor) – 'nadal' betont die Fortdauer trotz des Hindernisses. Die drei Synonyme für konzessive Konnektoren: 'chociaż' (neutral), 'mimo że' (formell), 'choć' (literarisch/kurz)."},
            {"id": "gp_conc4", "question": "Pomimo _____ trudności, udało mu się.", "translation": "Trotz der vielen Schwierigkeiten ist es ihm gelungen.", "options": ["wielu", "wiele", "wieloma", "wielom"], "correct": "wielu", "explanation": "'Pomimo' + Genitiv = 'trotz' + Genitiv – präpositionale Konzessivkonstruktion (kein Nebensatz!). 'Wielu trudności' – Genitiv Plural: 'wielu' (Genitiv von 'wiele') + 'trudności' (Schwierigkeiten, Genitiv Plural). Im Deutschen: 'trotz vieler Schwierigkeiten'. 'Udało mu się' (es gelang ihm) – unpersönliche Konstruktion mit Dativ 'mu' (ihm). Beide Sprachen verwenden den Genitiv nach 'trotz/pomimo'."},
            {"id": "gp_conc5", "question": "Nawet _____ miał rację, nikt go nie słuchał.", "translation": "Selbst wenn er Recht hatte, hörte ihm niemand zu.", "options": ["jeśli", "że", "bo", "więc"], "correct": "jeśli", "explanation": "'Nawet jeśli' = 'selbst wenn/auch wenn' – verstärkte Konzession mit hypothetischem Element. Im Deutschen: 'selbst wenn' oder 'sogar wenn'. 'Nawet' (sogar/selbst) verstärkt die konzessive Bedeutung. 'Nikt go nie słuchał' – dreifache Negation: 'nikt' (niemand) + 'nie' (nicht) + Verb, was im Polnischen grammatisch korrekt ist, im Deutschen aber unmöglich wäre."},
            {"id": "gp_conc6", "question": "Jakkolwiek _____ na to patrzysz, nie ma dobrego wyjścia.", "translation": "Wie auch immer du es betrachtest, es gibt keinen guten Ausweg.", "options": ["by", "bo", "że", "i"], "correct": "by", "explanation": "'Jakkolwiek by' = 'wie auch immer' – genereller Konzessivkonnektor. 'Jakkolwiek by patrzysz' (wie auch immer du schaust). Die Partikel 'by' signalisiert Irrealis/Hypothese. Im Deutschen: 'wie auch immer'. 'Nie ma dobrego wyjścia' – 'nie ma' + Genitiv (es gibt kein/keinen): 'dobrego wyjścia' (keinen guten Ausweg, Genitiv). Diese generalisierte Konzession zeigt, dass alle Perspektiven zum gleichen Ergebnis führen."},
            {"id": "gp_conc7", "question": "Wprawdzie jest drogo, _____ jakość jest doskonała.", "translation": "Zwar ist es teuer, aber die Qualität ist ausgezeichnet.", "options": ["ale", "bo", "więc", "że"], "correct": "ale", "explanation": "'Wprawdzie...ale' = 'zwar...aber' – konzessive Korrelation. Diese zweiteilige Struktur entspricht exakt dem Deutschen 'zwar...aber'. 'Wprawdzie' (zwar/allerdings) räumt einen Punkt ein, 'ale' (aber) liefert den Gegenargument. 'Doskonała' (ausgezeichnet, weibliche Form) bezieht sich auf 'jakość' (Qualität, feminin). Diese korrelative Konzessivstruktur ist in formellen Diskussionen sehr nützlich."},
            {"id": "gp_conc8", "question": "Co _____, jest uczciwy.", "translation": "Was auch immer man über ihn sagt, er ist ehrlich.", "options": ["prawda", "powiedzieć", "by nie powiedzieć", "mówią"], "correct": "by nie powiedzieć", "explanation": "'Co by nie powiedzieć' (was man auch immer sagen mag) – generalisierende Konzession mit irrealer Partikel 'by'. Im Deutschen: 'was auch immer man sagt'. Die Konstruktion 'co by nie + Infinitiv' ist eine feste Wendung im Polnischen. 'Uczciwy' (ehrlich) im Nominativ als Prädikativ. Diese Struktur wird oft verwendet, um trotz möglicher Kritik eine positive Eigenschaft hervorzuheben."},
            {"id": "gp_conc9", "question": "_____ tego, że jest bogaty, żyje skromnie.", "translation": "Ungeachtet dessen, dass er reich ist, lebt er bescheiden.", "options": ["Niezależnie od", "Dzięki", "Z powodu", "Według"], "correct": "Niezależnie od", "explanation": "'Niezależnie od tego, że...' (ungeachtet dessen, dass...) – hochformaler Konzessivkonnektor. 'Niezależnie od' + Genitiv = 'unabhängig von/ungeachtet'. Im Deutschen: 'ungeachtet dessen, dass' oder 'unabhängig davon, dass'. 'Żyje skromnie' (lebt bescheiden) – Präsens mit Adverb. Diese Konstruktion ist typisch für juristische und wissenschaftliche Texte und unterstreicht die Irrelevanz des genannten Faktors."},
            {"id": "gp_conc10", "question": "Aczkolwiek rozumiem twój punkt widzenia, nie _____ się z nim.", "translation": "Obgleich ich deinen Standpunkt verstehe, stimme ich ihm nicht zu.", "options": ["zgadzam", "zgodzę", "zgodziłem", "zgadzałem"], "correct": "zgadzam", "explanation": "'Aczkolwiek' = 'obgleich/wenngleich' – sehr formeller, literarischer Konzessivkonnektor. Im Deutschen: 'obgleich' oder 'wenngleich'. Wird hauptsächlich in gehobener Schriftsprache verwendet. 'Zgadzam się z nim' (ich stimme ihm zu) – 'z' + Instrumentalis: 'nim' (ihm, betonte Form). 'Punkt widzenia' (Standpunkt/Blickwinkel) – wörtlich: 'Punkt des Sehens'. Die formelle Stilebene ist durchgehend konsistent."},
            {"id": "gp_conc11", "question": "Bez _____ na koszty, kontynuowali projekt.", "translation": "Ohne Rücksicht auf die Kosten führten sie das Projekt fort.", "options": ["względu", "wzgląd", "względem", "względowi"], "correct": "względu", "explanation": "'Bez względu na' + Akkusativ = 'ohne Rücksicht auf/ungeachtet' – konzessive Präpositionalphrase. 'Względu' ist Genitiv von 'wzgląd' (Rücksicht/Hinsicht) nach 'bez' (ohne). 'Na koszty' (auf die Kosten) – Akkusativ nach 'na'. Im Deutschen: 'ohne Rücksicht auf die Kosten'. 'Kontynuowali' (sie setzten fort) – 3. Person Plural Maskulin Vergangenheit."},
            {"id": "gp_conc12", "question": "I tak _____ zrobi po swojemu.", "translation": "Er wird es sowieso auf seine Art machen.", "options": ["to", "tego", "temu", "tym"], "correct": "to", "explanation": "'I tak to zrobi' (er wird es sowieso tun) – die Partikel 'i tak' hat konzessive Bedeutung: 'sowieso/ohnehin'. Im Deutschen: 'sowieso' oder 'ohnehin'. 'Po swojemu' (auf seine Art) – Adverbialphrase mit reflexivem Possessivpronomen. 'To' als Pronomen für 'es'. Die Wendung 'i tak' drückt aus, dass das Ergebnis unabhängig von allen Umständen feststeht – eine resignative oder trotzige Konzession."},
            {"id": "gp_conc13", "question": "Bądź co _____, muszę spróbować.", "translation": "Komme was wolle, ich muss es versuchen.", "options": ["bądź", "będzie", "było", "jest"], "correct": "bądź", "explanation": "'Bądź co bądź' (komme was wolle/sei es wie es sei) – feste Redewendung mit konzessiver Bedeutung. 'Bądź' ist Imperativ von 'być' (sein): wörtlich 'sei was sei'. Im Deutschen: 'komme was wolle' oder 'wie dem auch sei'. 'Muszę spróbować' (ich muss es versuchen) – Modalverb + perfektiver Infinitiv. Diese idiomatische Wendung drückt Entschlossenheit trotz Hindernissen aus."},
            {"id": "gp_conc14", "question": "_____ wszystko, co zrobił, nadal mu ufam.", "translation": "Trotz allem, was er getan hat, vertraue ich ihm weiterhin.", "options": ["Mimo", "Dzięki", "Według", "Przed"], "correct": "Mimo", "explanation": "'Mimo wszystko, co...' (trotz allem, was...) – Konzession mit Relativsatz. 'Mimo' (trotz) ist kürzer als 'pomimo' und etwas informeller. 'Nadal mu ufam' (ich vertraue ihm weiterhin) – 'ufać' (vertrauen) + Dativ: 'mu' (ihm, unbetont). Im Deutschen: 'trotz allem, was' + Verb. 'Nadal' (weiterhin/nach wie vor) betont, dass das Vertrauen ungebrochen ist."},
            {"id": "gp_conc15", "question": "Choćby _____ prosił, nie zmienię zdania.", "translation": "Selbst wenn er mich bitten sollte, werde ich meine Meinung nicht ändern.", "options": ["mnie", "mi", "mną", "moje"], "correct": "mnie", "explanation": "'Choćby' = 'selbst wenn/auch wenn' + Konjunktiv – hypothetische Konzession. 'Prosił mnie' (er würde mich bitten) – 'prosić' + Akkusativ: 'mnie' (mich). 'Nie zmienię zdania' (ich werde meine Meinung nicht ändern) – 'zdania' im Genitiv nach Verneinung. 'Choćby' (verkürzt aus 'chociażby') enthält die Partikel 'by' für den Irrealis und drückt eine rein hypothetische Situation aus."}
        ]
    },
    {
        "key": "time_clauses_advanced",
        "name": "Zaawansowane zdania czasowe (Fortgeschrittene Temporalsätze)",
        "description": "Komplexe Zeitausdrücke und Temporalsätze – bevor, nachdem, bis, während, sobald",
        "icon": "clock.badge.checkmark",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_tca1", "question": "_____ wyjdziesz, zamknij okno.", "translation": "Bevor du gehst, schließ das Fenster.", "options": ["Zanim", "Kiedy", "Gdy", "Dopóki"], "correct": "Zanim", "explanation": "'Zanim' = 'bevor' – temporaler Konnektor für eine Handlung, die VOR einer anderen stattfinden soll. Im Deutschen: 'bevor du gehst'. 'Wyjdziesz' (du wirst gehen, perfektiv) – nach 'zanim' steht im Polnischen das Präsens oder Futur, NICHT die Vergangenheit. 'Zamknij' ist der Imperativ von 'zamknąć' (schließen). Die Aufforderung gilt für den Zeitpunkt vor dem Weggehen."},
            {"id": "gp_tca2", "question": "_____ skończył mówić, wszyscy zaczęli klaskać.", "translation": "Nachdem er aufgehört hatte zu reden, begannen alle zu klatschen.", "options": ["Gdy", "Zanim", "Dopóki", "Choć"], "correct": "Gdy", "explanation": "'Gdy' + perfektiver Aspekt = 'nachdem/als' – temporaler Konnektor für abgeschlossene Handlungen. Im Deutschen: 'nachdem er aufgehört hatte' (Plusquamperfekt). Im Polnischen gibt es KEIN Plusquamperfekt – der Aspekt (perfektiv 'skończył') drückt die Vorzeitigkeit aus! 'Zaczęli klaskać' (begannen zu klatschen) – 'zacząć' + Infinitiv. Die Aspektunterscheidung ersetzt die deutschen Zeitformen."},
            {"id": "gp_tca3", "question": "Będę czekać, _____ przyjdziesz.", "translation": "Ich werde warten, bis du kommst.", "options": ["aż", "gdy", "zanim", "bo"], "correct": "aż", "explanation": "'Aż' = 'bis' – temporaler Konnektor für das ENDE eines Wartens. Im Deutschen: 'bis du kommst'. 'Przyjdziesz' (du wirst kommen, perfektiv) – nach 'aż' steht das perfektive Futur, da der Zeitpunkt des Kommens ein punktuelles Ereignis ist. 'Będę czekać' (ich werde warten, imperfektiv) – das Warten DAUERT AN. Der Aspektkontrast (imperfektiv im Hauptsatz, perfektiv im Nebensatz) ist typisch für 'aż'-Sätze."},
            {"id": "gp_tca4", "question": "_____ tylko go zobaczę, przekażę mu wiadomość.", "translation": "Sobald ich ihn sehe, werde ich ihm die Nachricht übermitteln.", "options": ["Jak", "Bo", "Choć", "Mimo"], "correct": "Jak", "explanation": "'Jak tylko' = 'sobald' – betont die UNMITTELBARE Abfolge zweier Handlungen. Im Deutschen: 'sobald ich ihn sehe'. 'Jak' (wie/wenn) + 'tylko' (nur) bilden zusammen 'sobald'. 'Zobaczę' (ich werde sehen/erblicken, perfektiv) – punktuelles Ereignis. 'Przekażę' (ich werde übermitteln, perfektiv) – die Folgehandlung ist ebenfalls einmalig. Beide Verben im perfektiven Futur zeigen schnelle Abfolge."},
            {"id": "gp_tca5", "question": "_____ pracowała, dzieci bawiły się w ogrodzie.", "translation": "Während sie arbeitete, spielten die Kinder im Garten.", "options": ["Podczas gdy", "Zanim", "Aż", "Bo"], "correct": "Podczas gdy", "explanation": "'Podczas gdy' = 'während' – temporaler Konnektor für GLEICHZEITIGE Handlungen. Im Deutschen: 'während sie arbeitete'. 'Pracowała' (sie arbeitete, imperfektiv) – andauernde Handlung. 'Bawiły się' (sie spielten, imperfektiv) – ebenfalls andauernd. BEIDE Verben im imperfektiven Aspekt, weil die Handlungen parallel ANDAUERN. 'W ogrodzie' (im Garten) – Lokativ nach 'w'. Der imperfektive Aspekt ist obligatorisch bei Gleichzeitigkeit."},
            {"id": "gp_tca6", "question": "Od _____ tu mieszkam, nauczyłem się polskiego.", "translation": "Seit ich hier wohne, habe ich Polnisch gelernt.", "options": ["kiedy", "tego", "dawna", "lat"], "correct": "kiedy", "explanation": "'Od kiedy' = 'seit/seitdem' – temporaler Konnektor für den ANFANGSPUNKT einer Handlung. Im Deutschen: 'seit ich hier wohne'. 'Mieszkam' (ich wohne, imperfektiv Präsens) – die Handlung dauert an. 'Nauczyłem się' (ich habe gelernt, perfektiv) – abgeschlossenes Ergebnis. Der Aspektunterschied ist entscheidend: 'od kiedy' + imperfektiv (andauernd) im Temporalsatz, perfektiv (Ergebnis) im Hauptsatz."},
            {"id": "gp_tca7", "question": "Nie ruszę się stąd, _____ nie dostanę odpowiedzi.", "translation": "Ich bewege mich nicht von hier, bis ich eine Antwort bekomme.", "options": ["dopóki", "gdy", "zanim", "bo"], "correct": "dopóki", "explanation": "'Dopóki nie' = 'solange nicht/bis' – temporaler Konnektor für das Andauern eines Zustands bis zu einem Ereignis. 'Dopóki' (solange) + 'nie' (nicht) – doppelte Verneinung im Temporalsatz! Im Deutschen: einfach 'bis'. 'Ruszę się' (ich werde mich bewegen, perfektiv) – einmaliges Aufbrechen. 'Odpowiedzi' im Genitiv wegen 'nie dostanę' (Genitiv nach verneintem Verb)."},
            {"id": "gp_tca8", "question": "Ledwie _____, rozległ się telefon.", "translation": "Kaum hatte er sich hingesetzt, klingelte das Telefon.", "options": ["usiadł", "siedział", "siada", "usiądzie"], "correct": "usiadł", "explanation": "'Ledwie' = 'kaum' – temporaler Konnektor für UNMITTELBARE Abfolge (noch schneller als 'jak tylko'). Im Deutschen: 'kaum hatte er sich hingesetzt'. 'Usiadł' (er setzte sich, perfektiv) – punktuelles Ereignis. 'Rozległ się' (erklang/ertönte) – reflexives perfektives Verb. 'Ledwie' impliziert, dass die zweite Handlung fast gleichzeitig mit der ersten stattfand. Literarischer Konnektor, typisch für Erzählungen."},
            {"id": "gp_tca9", "question": "Za każdym _____, gdy tu przychodzę, jest inaczej.", "translation": "Jedes Mal, wenn ich hierherkomme, ist es anders.", "options": ["razem", "raz", "razu", "razy"], "correct": "razem", "explanation": "'Za każdym razem, gdy...' (jedes Mal, wenn...) – iterativer Temporalausdruck. 'Razem' ist Instrumentalis von 'raz' (Mal) nach 'za' + Instrumentalis. Im Deutschen: 'jedes Mal, wenn'. 'Przychodzę' (ich komme, imperfektiv) – wiederholte Handlung, daher imperfektiv. 'Jest inaczej' (ist es anders) – Zustandsbeschreibung. Die Konstruktion drückt Regelmäßigkeit aus: bei JEDEM Besuch ändert sich etwas."},
            {"id": "gp_tca10", "question": "Ilekroć _____ na nią patrzę, myślę o morzu.", "translation": "Sooft ich sie ansehe, denke ich an das Meer.", "options": ["tylko", "wcale", "bardzo", "nigdy"], "correct": "tylko", "explanation": "'Ilekroć' = 'sooft/jedes Mal wenn' – literarischer iterativer Temporalkonnektor. 'Ilekroć tylko' verstärkt die Bedeutung (sooft ich nur). Im Deutschen: 'sooft/wann immer'. 'Patrzę na nią' (ich schaue sie an) – 'patrzeć na' + Akkusativ = 'schauen auf/ansehen'. 'Myślę o morzu' (ich denke an das Meer) – 'myśleć o' + Lokativ: 'morzu'. Beide Verben imperfektiv für wiederholte Handlungen."},
            {"id": "gp_tca11", "question": "Nim _____ się obejrzał, minęły trzy godziny.", "translation": "Ehe er sich versah, waren drei Stunden vergangen.", "options": ["się", "go", "mu", "je"], "correct": "się", "explanation": "'Nim się obejrzał' (ehe er sich versah) – 'nim' = literarische Variante von 'zanim' (bevor). Die Wendung 'nim się obejrzał' ist idiomatisch und bedeutet 'bevor er es merkte/im Nu'. 'Minęły trzy godziny' (drei Stunden vergingen) – 'minąć' (vergehen) im Plural Femininum, da 'godziny' weiblich sind. Im Deutschen: 'ehe er sich versah'. Literarischer Stil."},
            {"id": "gp_tca12", "question": "Po _____ zadania, poszli na przerwę.", "translation": "Nachdem sie die Aufgabe beendet hatten, gingen sie in die Pause.", "options": ["wykonaniu", "wykonać", "wykonanie", "wykonując"], "correct": "wykonaniu", "explanation": "'Po' + Lokativ des Verbalsubstantivs = 'nach' + Nominalisierung – temporale Präpositionalkonstruktion. 'Po wykonaniu' (nach der Ausführung) – 'wykonaniu' ist Lokativ von 'wykonanie' (Ausführung/Erledigung). Im Deutschen: 'nach Erledigung der Aufgabe'. Diese nominale Temporalkonstruktion ersetzt einen Nebensatz und ist typisch für formelle Sprache. 'Poszli' (sie gingen, perfektiv) zeigt den Übergang zur nächsten Handlung."},
            {"id": "gp_tca13", "question": "W _____ gdy ja gotowałem, ona sprzątała.", "translation": "Während ich kochte, räumte sie auf.", "options": ["czasie", "czas", "czasu", "czasem"], "correct": "czasie", "explanation": "'W czasie gdy' = 'während' – alternative Form zu 'podczas gdy'. 'Czasie' ist Lokativ von 'czas' (Zeit) nach 'w'. Im Deutschen: 'während ich kochte'. Die parallelen imperfektiven Verben 'gotowałem' (ich kochte) und 'sprzątała' (sie räumte auf) zeigen Gleichzeitigkeit. Die Genusformen zeigen deutlich: '-łem' (maskulin, ich) vs. '-ła' (feminin, sie). Diese Unterscheidung hat im Deutschen keine Entsprechung."},
            {"id": "gp_tca14", "question": "Dotąd _____ szczęście, ale teraz się skończyło.", "translation": "Bis jetzt hatten wir Glück, aber jetzt ist es vorbei.", "options": ["mieliśmy", "mamy", "będziemy mieli", "mielibyśmy"], "correct": "mieliśmy", "explanation": "'Dotąd' = 'bis jetzt/bisher' – temporaler Adverb für den Zeitraum bis zur Gegenwart. Im Deutschen: 'bis jetzt' oder 'bisher'. 'Mieliśmy szczęście' (wir hatten Glück) – imperfektiver Aspekt, da der Glückszustand über einen Zeitraum andauerte. 'Ale teraz się skończyło' (aber jetzt ist es vorbei) – perfektiv. Der Kontrast 'dotąd' (Vergangenheit bis jetzt) vs. 'teraz' (jetzt) markiert den Wendepunkt."},
            {"id": "gp_tca15", "question": "Odtąd _____ siebie tylko w weekendy.", "translation": "Seitdem sehen wir uns nur noch am Wochenende.", "options": ["widujemy", "widzimy", "zobaczymy", "widzieliśmy"], "correct": "widujemy", "explanation": "'Odtąd' = 'seitdem/von da an' – temporaler Adverb für den Zeitpunkt, ab dem etwas gilt. 'Widujemy' (wir sehen uns, frequentativ-imperfektiv) – NICHT 'widzimy'! 'Widywać' ist die frequentative Form von 'widzieć' und drückt regelmäßiges, aber nicht ständiges Sehen aus. Im Deutschen fehlt diese Nuance. 'Tylko w weekendy' (nur am Wochenende) – Einschränkung der Frequenz."}
        ]
    },
    {
        "key": "formal_register",
        "name": "Rejestr formalny (Formelles Register)",
        "description": "Formelle Sprache im Polnischen – Pan/Pani-System, Amtssprache und höfliche Formen",
        "icon": "person.crop.circle.badge.checkmark",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_form1", "question": "Czy _____ życzy sobie coś do picia?", "translation": "Möchten Sie etwas zu trinken?", "options": ["Pan", "ty", "on", "ktoś"], "correct": "Pan", "explanation": "'Pan' (Herr) wird als formelle Anrede in der 3. Person verwendet – im Deutschen entspricht dies 'Sie'. Im Polnischen wird die 3. Person Singular benutzt: 'Pan życzy sobie' (der Herr wünscht sich), nicht die 2. Person wie beim deutschen 'Sie'. Dies ist der GRUNDLEGENDE Unterschied im Höflichkeitssystem: Deutsch 'Sie' = 3. Person Plural, Polnisch 'Pan/Pani' = 3. Person Singular. Für Frauen: 'Pani'."},
            {"id": "gp_form2", "question": "Szanowny _____, piszę w sprawie...", "translation": "Sehr geehrter Herr, ich schreibe in der Angelegenheit...", "options": ["Panie", "Pan", "Pana", "Panem"], "correct": "Panie", "explanation": "'Szanowny Panie' (Sehr geehrter Herr) – Vokativ (Anredeform) von 'Pan'. Der Vokativ ist ein polnischer Kasus ohne deutsche Entsprechung – im Deutschen bleibt es 'Herr' (Nominativ). In formellen Briefen: 'Szanowny Panie Dyrektorze' (Sehr geehrter Herr Direktor) – BEIDE Substantive im Vokativ! 'W sprawie' (in der Angelegenheit) + Genitiv zeigt den formellen Kontext."},
            {"id": "gp_form3", "question": "Proszę o _____ terminu spotkania.", "translation": "Ich bitte um Bestätigung des Besprechungstermins.", "options": ["potwierdzenie", "potwierdzeniu", "potwierdzenia", "potwierdzeniem"], "correct": "potwierdzenie", "explanation": "'Proszę o' + Akkusativ = 'ich bitte um' + Akkusativ – formelle Bitte. 'Potwierdzenie' (Bestätigung) im Akkusativ (= Nominativ bei Neutra). 'Terminu spotkania' – Genitiv-Kette: 'termin' (Termin, Genitiv: 'terminu') + 'spotkanie' (Treffen/Besprechung, Genitiv: 'spotkania'). Im Deutschen: 'Bestätigung des Besprechungstermins' – ebenfalls Genitivkette. Amtssprachliche Konstruktion."},
            {"id": "gp_form4", "question": "Zwracam się z _____ o udzielenie informacji.", "translation": "Ich wende mich mit der Bitte um Auskunft.", "options": ["prośbą", "prośba", "prośbie", "prośbę"], "correct": "prośbą", "explanation": "'Zwracam się z prośbą' (ich wende mich mit einer Bitte) – hochformelle Wendung. 'Z' + Instrumentalis: 'prośbą' (Instrumentalis von 'prośba' = Bitte). 'O udzielenie informacji' (um Erteilung von Auskunft) – 'o' + Akkusativ. Im Deutschen: 'Ich wende mich an Sie mit der Bitte um...' Die Nominalisierung 'udzielenie' (Erteilung) ist typisch für Amtssprache. Diese Wendung wird in offiziellen Briefen und Anträgen verwendet."},
            {"id": "gp_form5", "question": "Uprzejmie _____ o odpowiedź.", "translation": "Ich bitte höflich um eine Antwort.", "options": ["proszę", "prosi", "prosimy", "proszą"], "correct": "proszę", "explanation": "'Uprzejmie proszę' (ich bitte höflich) – formelle Verstärkung der Bitte. 'Uprzejmie' (höflich/freundlich) als Adverb verstärkt die Höflichkeit. Im Deutschen: 'Ich bitte höflich um...' oder 'Ich bitte freundlicherweise um...'. 'O odpowiedź' (um eine Antwort) – 'o' + Akkusativ. Diese Konstruktion wird in Geschäftskorrespondenz und behördlichen Schreiben als Standardformel verwendet. Der Ton ist respektvoll und professionell."},
            {"id": "gp_form6", "question": "Czy mógłby _____ mi pomóc?", "translation": "Könnten Sie mir bitte helfen?", "options": ["Pan", "ty", "on", "kto"], "correct": "Pan", "explanation": "'Czy mógłby Pan' (könnten Sie, zu einem Mann) – Konjunktiv + Pan-Anrede. 'Mógłby' ist der Konjunktiv (tryb przypuszczający) von 'móc' (können), maskuline Form. Für eine Frau: 'Czy mogłaby Pani'. Im Deutschen: 'Könnten Sie...' (keine Genusunterscheidung!). Die geschlechtsspezifische Verbform ist im Polnischen obligatorisch und muss zum Geschlecht des Angesprochenen passen. 'Mi pomóc' – Dativ + Infinitiv."},
            {"id": "gp_form7", "question": "Z poważaniem, _____ Jan Kowalski.", "translation": "Mit freundlichen Grüßen, Jan Kowalski.", "options": ["dr", "pan", "mgr", "inż."], "correct": "dr", "explanation": "'Z poważaniem' (mit Hochachtung) = 'Mit freundlichen Grüßen' – Abschlussformel in formellen Briefen. Im Polnischen werden akademische Titel IMMER angegeben: 'dr' (Doktor), 'mgr' (Magister), 'inż.' (Ingenieur), 'prof.' (Professor). Im Deutschen verwendet man Titel seltener in der Unterschrift. Alternative Schlussformeln: 'Z wyrazami szacunku' (mit Ausdrücken des Respekts), 'Łączę wyrazy szacunku' (ich sende Ausdrücke des Respekts)."},
            {"id": "gp_form8", "question": "W nawiązaniu _____ Pana pisma z dnia 5 marca...", "translation": "Bezugnehmend auf Ihr Schreiben vom 5. März...", "options": ["do", "na", "w", "z"], "correct": "do", "explanation": "'W nawiązaniu do' + Genitiv = 'bezugnehmend auf/in Bezug auf'. 'Do Pana pisma' (auf Ihr Schreiben) – 'Pana' (Ihr, formell maskulin, Genitiv von 'Pan'). Im Deutschen: 'Bezugnehmend auf Ihr Schreiben vom...' 'Z dnia' (vom Tag/vom Datum) + Genitiv. Diese Wendung ist eine Standardformel in Geschäftsbriefen und behördlicher Korrespondenz. Der formelle Stil erfordert Nominalisierungen und indirekte Ausdrucksweisen."},
            {"id": "gp_form9", "question": "Niniejszym _____ o przyjęcie mojej rezygnacji.", "translation": "Hiermit bitte ich um die Annahme meiner Kündigung.", "options": ["proszę", "prosząc", "prosiłem", "poproszę"], "correct": "proszę", "explanation": "'Niniejszym' (hiermit) – höchst formeller performativer Ausdruck, typisch für juristische und behördliche Dokumente. Im Deutschen: 'hiermit'. 'Proszę o przyjęcie' (ich bitte um Annahme) – 'przyjęcie' (Annahme, Akkusativ) von 'przyjąć' (annehmen). 'Mojej rezygnacji' (meiner Kündigung/meines Rücktritts, Genitiv). Diese Sprache wird in offiziellen Kündigungsschreiben, Anträgen und Erklärungen verwendet."},
            {"id": "gp_form10", "question": "Państwo _____ zaproszeni na konferencję.", "translation": "Sie (alle) sind zur Konferenz eingeladen.", "options": ["są", "jest", "jesteś", "jesteście"], "correct": "są", "explanation": "'Państwo' (Sie, Plural formal) – Anrede für eine Gruppe, die Männer und Frauen enthält. Im Deutschen: 'Sie' (keine Unterscheidung Singular/Plural formell). 'Państwo są' (Sie sind) – 3. Person Plural! Im Polnischen: 'Pan' (ein Mann), 'Pani' (eine Frau), 'Państwo' (gemischte Gruppe), 'Panowie' (nur Männer), 'Panie' (nur Frauen). Dieses differentielle System ist viel komplexer als das deutsche 'Sie'."},
            {"id": "gp_form11", "question": "Czy _____ dyrektorze, mogę prosić o chwilę rozmowy?", "translation": "Herr Direktor, darf ich um ein kurzes Gespräch bitten?", "options": ["Panie", "Pan", "Pana", "Panem"], "correct": "Panie", "explanation": "'Panie Dyrektorze' – doppelter Vokativ! Sowohl 'Pan' → 'Panie' als auch 'Dyrektor' → 'Dyrektorze' stehen im Vokativ (Anredeform). Im Deutschen bleibt es beim Nominativ: 'Herr Direktor'. Der Vokativ ist im Polnischen lebendig und wird bei Anreden immer verwendet. 'Mogę prosić o chwilę rozmowy' (darf ich um einen Moment Gespräch bitten) – höfliche, indirekte Bitte um ein Treffen."},
            {"id": "gp_form12", "question": "Byłbym _____, gdyby Pan mógł odpowiedzieć.", "translation": "Ich wäre dankbar, wenn Sie antworten könnten.", "options": ["wdzięczny", "wdzięczna", "wdzięczni", "wdzięczne"], "correct": "wdzięczny", "explanation": "'Byłbym wdzięczny' (ich wäre dankbar) – Konjunktiv als höfliche Formulierung. 'Wdzięczny' (dankbar, maskulin) für einen männlichen Sprecher, 'wdzięczna' für eine Frau. Im Deutschen: 'Ich wäre dankbar' (geschlechtsneutral!). 'Gdyby Pan mógł' (wenn Sie könnten) – hypothetische Höflichkeitsformel mit 'gdyby' + Konjunktiv. Diese Konstruktion ist die höflichste Form einer Bitte im Polnischen."},
            {"id": "gp_form13", "question": "W _____ z powyższym, proszę o rozpatrzenie sprawy.", "translation": "Im Zusammenhang mit dem Obigen bitte ich um Prüfung der Angelegenheit.", "options": ["związku", "związek", "związkiem", "związkowi"], "correct": "związku", "explanation": "'W związku z powyższym' (im Zusammenhang mit dem Obigen) – formelle Verknüpfung zum vorherigen Text. 'Związku' ist Lokativ von 'związek' (Zusammenhang) nach 'w'. 'Powyższym' (dem Obigen, Instrumentalis nach 'z'). Im Deutschen: 'in diesem Zusammenhang'. 'Rozpatrzenie sprawy' (Prüfung der Angelegenheit, Genitiv-Nominalisierung) ist typische Amtssprache. Diese Formel erscheint in jedem formellen polnischen Schreiben."},
            {"id": "gp_form14", "question": "Pozwolę _____ nie zgodzić się z Pana opinią.", "translation": "Ich erlaube mir, Ihrer Meinung zu widersprechen.", "options": ["sobie", "siebie", "się", "sobą"], "correct": "sobie", "explanation": "'Pozwolę sobie' (ich erlaube mir) – höfliche Einleitung eines Widerspruchs oder einer Initiative. 'Sobie' ist Dativ des Reflexivpronomens. Im Deutschen: 'Ich erlaube mir...' 'Nie zgodzić się z' + Instrumentalis (Pana opinią = Ihrer Meinung). Die Verwendung von 'pozwolę sobie' mildert den Widerspruch ab – man zeigt Respekt, bevor man widerspricht. Typisch für Debatten und formelle Diskussionen."},
            {"id": "gp_form15", "question": "Wyrażam _____ nadzieję na dalszą współpracę.", "translation": "Ich bringe die Hoffnung auf weitere Zusammenarbeit zum Ausdruck.", "options": ["głęboką", "głęboka", "głęboko", "głębokiej"], "correct": "głęboką", "explanation": "'Wyrażam głęboką nadzieję' (ich drücke tiefe Hoffnung aus) – formelle Abschlussformel. 'Głęboką' (tiefe, Akkusativ feminin) bezieht sich auf 'nadzieję' (Hoffnung, feminin). 'Na dalszą współpracę' (auf weitere Zusammenarbeit) – 'na' + Akkusativ. Im Deutschen: 'Ich bringe die Hoffnung zum Ausdruck' oder 'Ich hoffe auf weitere Zusammenarbeit'. Diese hochformelle Wendung findet sich in Geschäftsbriefen und diplomatischer Korrespondenz."}
        ]
    },
    {
        "key": "colloquial_polish",
        "name": "Potoczny język polski (Umgangspolnisch)",
        "description": "Umgangssprachliche Strukturen, Abkürzungen und informelle Wendungen im Polnischen",
        "icon": "bubble.left",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_coll1", "question": "_____ idziesz?", "translation": "Wohin gehst du? (umgangssprachlich)", "options": ["Gdzie", "Dokąd", "Kiedy", "Jak"], "correct": "Gdzie", "explanation": "In der Umgangssprache wird 'gdzie' (wo) oft anstelle von 'dokąd' (wohin) verwendet – obwohl grammatisch 'dokąd' korrekt wäre für die Richtung. Im Deutschen: 'Wo gehst du hin?' statt 'Wohin gehst du?' – dasselbe Phänomen! In der Standardsprache: 'Dokąd idziesz?' (wohin). Diese Vereinfachung der wo/wohin-Unterscheidung ist in beiden Sprachen umgangssprachlich verbreitet."},
            {"id": "gp_coll2", "question": "No _____, co u ciebie?", "translation": "Na und, was gibt's bei dir? (umgangssprachlich)", "options": ["dobra", "dobrze", "dobrą", "dobre"], "correct": "dobra", "explanation": "'No dobra' (na gut/okay) – informelle Gesprächseröffnung oder Themenwechsel. 'No' ist eine polnische Partikel ohne direkte deutsche Entsprechung (ähnlich 'na/nun'). 'Dobra' (unflektiertes Adjektiv feminin) wird umgangssprachlich als 'okay/gut' verwendet. 'Co u ciebie?' (was bei dir? = wie geht's?) – typische informelle Begrüßung unter Freunden. Im Deutschen: 'Na, was gibt's bei dir?'"},
            {"id": "gp_coll3", "question": "Fajnie, że _____ !", "translation": "Cool, dass du gekommen bist!", "options": ["przyszedłeś", "przychodzisz", "przyjdziesz", "chodził"], "correct": "przyszedłeś", "explanation": "'Fajnie' (cool/toll) – umgangssprachliches Adverb, das Begeisterung ausdrückt. Entspricht dem deutschen 'cool/toll/super'. 'Że przyszedłeś' (dass du gekommen bist) – perfektiver Aspekt. Im formellen Polnisch: 'Cieszę się, że przyszedłeś' (Ich freue mich, dass du gekommen bist). Die verkürzte Form mit 'fajnie' ist typisch für Jugendsprache und informelle Gespräche. 'Fajnie' kann fast universell als positiver Ausruf verwendet werden."},
            {"id": "gp_coll4", "question": "_____ mi się nie chce.", "translation": "Ich habe einfach keine Lust. (umgangssprachlich)", "options": ["Kompletnie", "Trochę", "Bardzo", "Może"], "correct": "Kompletnie", "explanation": "'Kompletnie mi się nie chce' (ich habe absolut keine Lust) – verstärkte informelle Ablehnung. 'Nie chce mi się' ist eine unpersönliche Konstruktion: wörtlich 'es will sich mir nicht' = 'ich habe keine Lust'. 'Kompletnie' (komplett/total) verstärkt die Aussage umgangssprachlich. Im Deutschen: 'Ich hab null Bock'. Die Konstruktion 'nie chce mi się' + Infinitiv ist typisch polnisch und hat keine direkte deutsche Entsprechung."},
            {"id": "gp_coll5", "question": "Daj _____!", "translation": "Hör auf! / Lass das! (umgangssprachlich)", "options": ["spokój", "spokojny", "spokoju", "spokojem"], "correct": "spokój", "explanation": "'Daj spokój!' (lass es sein!/hör auf!) – idiomatische umgangssprachliche Aufforderung. Wörtlich: 'Gib Ruhe!' 'Spokój' (Ruhe/Frieden) im Akkusativ nach 'dać' (geben). Im Deutschen: 'Hör auf!' oder 'Lass das!' Je nach Kontext kann es Ungeduld, Ungläubigkeit oder milden Ärger ausdrücken. Alternative: 'Daj spokój, serio?' (Hör auf, im Ernst?) – zeigt Überraschung oder Skepsis."},
            {"id": "gp_coll6", "question": "_____ się stało?", "translation": "Was ist passiert? (umgangssprachlich)", "options": ["Co", "Kto", "Jak", "Gdzie"], "correct": "Co", "explanation": "'Co się stało?' (was ist passiert?) – direkte, umgangssprachliche Frage nach dem Geschehen. Im förmlichen Polnisch: 'Co się wydarzyło?' oder 'Co miało miejsce?' 'Stało się' (es passierte) – reflexives Verb. Im Deutschen: 'Was ist passiert?' oder umgangssprachlich: 'Was ist los?' Die Kurzform 'co się stało?' wird in alltäglichen Situationen wie Unfällen, Problemen oder Überraschungen verwendet."},
            {"id": "gp_coll7", "question": "Spoko, _____ problemów.", "translation": "Alles klar, kein Problem. (umgangssprachlich)", "options": ["bez", "z", "do", "na"], "correct": "bez", "explanation": "'Spoko' – umgangssprachliche Kurzform von 'spokojnie' (ruhig/alles klar). Im Deutschen: 'kein Ding' oder 'alles klar'. 'Bez problemów' (ohne Probleme) – 'bez' + Genitiv Plural. Im förmlichen Polnisch: 'Nie ma problemu' (es gibt kein Problem). 'Spoko' ist im Jugendjargon weit verbreitet und wird als Zustimmung, Beruhigung oder lockere Bestätigung verwendet: 'Spoko, ogarnę to' (Klar, ich kriege das hin)."},
            {"id": "gp_coll8", "question": "Strasznie _____ jestem.", "translation": "Ich bin wahnsinnig müde. (umgangssprachlich)", "options": ["zmęczony", "zmęczona", "zmęczeni", "zmęczone"], "correct": "zmęczony", "explanation": "'Strasznie' (furchtbar/wahnsinnig) als umgangssprachlicher Verstärker – wörtlich 'schrecklich'. Im Deutschen: 'wahnsinnig/irre/mega müde'. In der Standardsprache: 'bardzo zmęczony' (sehr müde). 'Strasznie' als Intensifizierer ist informell und drückt Übertreibung aus. Ähnlich: 'okropnie' (schrecklich) als Verstärker. 'Zmęczony' (müde, maskulin) – für eine Frau: 'zmęczona'. Die informelle Verstärkung mit Negativwörtern ist in beiden Sprachen üblich."},
            {"id": "gp_coll9", "question": "No _____, powodzenia!", "translation": "Na dann, viel Glück! (umgangssprachlich)", "options": ["to", "ten", "tego", "temu"], "correct": "to", "explanation": "'No to' (na dann/also dann) – informeller Gesprächsabschluss oder Überleitung. 'No' (Partikel) + 'to' (dann/so) = lockere Einleitung einer Schlussfolgerung. Im Deutschen: 'na dann' oder 'also dann'. 'Powodzenia' (viel Glück) ist Genitiv von 'powodzenie' (Erfolg/Glück) – steht im Genitiv als Ellipse von 'życzę ci powodzenia' (ich wünsche dir Glück). Informelle Verabschiedung zwischen Freunden."},
            {"id": "gp_coll10", "question": "Ale _____ !", "translation": "Na sowas! / Wow! (umgangssprachlich)", "options": ["numer", "liczba", "cyfra", "ilość"], "correct": "numer", "explanation": "'Ale numer!' (Na sowas!/Was für eine Geschichte!) – umgangssprachlicher Ausruf der Überraschung. Wörtlich: 'Was für eine Nummer!' Im Deutschen: 'Na sowas!' oder 'Das ist echt stark!' 'Numer' (Nummer) wird metaphorisch für eine überraschende Situation verwendet. Ähnliche Ausrufe: 'Ale jazda!' (Was für ein Ritt! = aufregend!), 'Ale jaja!' (Was für Eier! = Das ist ein Witz!). Diese idiomatischen Ausrufe sind rein umgangssprachlich."},
            {"id": "gp_coll11", "question": "Ogarnij _____ !", "translation": "Reiß dich zusammen! / Krieg's auf die Reihe! (umgangssprachlich)", "options": ["się", "siebie", "sobie", "sobą"], "correct": "się", "explanation": "'Ogarnij się!' (reiß dich zusammen!/bring Ordnung rein!) – umgangssprachlicher Imperativ von 'ogarnąć się'. 'Ogarnąć' bedeutet wörtlich 'umfassen/erfassen', umgangssprachlich: 'auf die Reihe kriegen'. Im Deutschen: 'Reiß dich zusammen!' oder 'Krieg's gebacken!' 'Się' als reflexives Pronomen. 'Ogarnąć' kann auch transitiv sein: 'ogarnij pokój' (räum das Zimmer auf). Ein sehr produktives Slangwort in der heutigen polnischen Sprache."},
            {"id": "gp_coll12", "question": "Nie _____ mi to.", "translation": "Das sagt mir nichts. / Davon hab ich keine Ahnung.", "options": ["kumam", "kumasz", "kuma", "kumają"], "correct": "kumam", "explanation": "'Nie kumam' (ich peile das nicht/ich verstehe nicht) – sehr informell, Slang. 'Kumać' = umgangssprachlich für 'verstehen'. Im formellen Polnisch: 'nie rozumiem' (ich verstehe nicht). Im Deutschen: 'Ich check das nicht' oder 'Davon hab ich keinen Plan'. 'Kumać' stammt wahrscheinlich aus dem Romani ('kum' = Verstand). Die 1. Person Singular 'kumam' zeigt die reguläre Konjugation der '-ać'-Klasse."},
            {"id": "gp_coll13", "question": "Wyluzuj, nie _____ się.", "translation": "Entspann dich, stress dich nicht. (umgangssprachlich)", "options": ["stresuj", "stresować", "stresuje", "stresowałem"], "correct": "stresuj", "explanation": "'Wyluzuj' (chill/entspann dich) – Jugendslang-Imperativ von 'wyluzować' (sich entspannen). 'Nie stresuj się' (stress dich nicht) – Imperativ vernein. Im Deutschen: 'Chill mal, stress dich nicht'. 'Stresować się' (sich stressen) ist ein Lehnwort aus dem Englischen/Deutschen und wird besonders von jüngeren Polen verwendet. 'Wyluzuj' kommt von 'luz' (Lockerheit/locker) mit dem Präfix 'wy-'. Typischer Jugendsprachgebrauch."},
            {"id": "gp_coll14", "question": "Siema, co _____?", "translation": "Hey, was geht? (Jugendslang)", "options": ["tam", "tu", "jest", "masz"], "correct": "tam", "explanation": "'Siema' = extrem informelle Begrüßung unter jungen Leuten, verkürzt aus '(jak się ma)sz?'. Im Deutschen: 'Hey/Yo, was geht?' 'Co tam?' (was da? = was geht ab?) – die lockerste Form der Begrüßungsfrage. Formeller: 'cześć' (hallo), noch formeller: 'dzień dobry' (guten Tag). Die Hierarchie der Grüße: 'siema/elo' (Slang) < 'cześć' (informal) < 'dzień dobry' (formal) < 'szanowny Panie' (hochformell)."},
            {"id": "gp_coll15", "question": "To jest mega _____!", "translation": "Das ist mega cool!", "options": ["fajne", "fajny", "fajną", "fajnego"], "correct": "fajne", "explanation": "'Mega fajne' (mega cool) – Jugendverstärker 'mega' + 'fajne' (cool, Neutrum weil 'to' = es). Im Deutschen: 'mega cool/geil'. 'Mega' wird als undekliniertes Präfix-Adverb verwendet – ein Anglizismus/Internationalismus. 'Fajne' im Neutrum, weil es sich auf 'to' (das/es) bezieht. Alternative Verstärker: 'ekstra' (extra), 'super', 'ultra', 'turbo'. Die Jugendsprache beider Länder verwendet ähnliche internationale Verstärker."}
        ]
    },
    {
        "key": "idiomatic_expressions",
        "name": "Idiomatische Wendungen (Redewendungen)",
        "description": "Polnische Redewendungen und idiomatische Ausdrücke mit grammatischer Analyse",
        "icon": "text.quote",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_idiom1", "question": "Mieć coś na _____ języka.", "translation": "Etwas auf der Zungenspitze haben. (Es liegt mir auf der Zunge.)", "options": ["końcu", "końcówce", "końcy", "koniec"], "correct": "końcu", "explanation": "'Mieć na końcu języka' (auf der Zungenspitze haben) – identische Redewendung im Deutschen! 'Końcu' ist Lokativ von 'koniec' (Ende/Spitze) nach 'na'. 'Języka' ist Genitiv von 'język' (Zunge/Sprache). Bedeutung: Man weiß etwas, kann sich aber nicht daran erinnern. Diese Redewendung existiert in vielen europäischen Sprachen und ist ein seltenes Beispiel für perfekte Übereinstimmung."},
            {"id": "gp_idiom2", "question": "Wziąć _____ za rogi.", "translation": "Den Stier bei den Hörnern packen.", "options": ["byka", "byk", "byku", "bykiem"], "correct": "byka", "explanation": "'Wziąć byka za rogi' = 'den Stier bei den Hörnern packen' – identische Redewendung! 'Byka' ist Akkusativ von 'byk' (Stier), 'za rogi' (bei den Hörnern) mit 'za' + Akkusativ. Bedeutung: ein Problem mutig und direkt angehen. Im Polnischen und Deutschen wird dieselbe Metapher verwendet. Der Akkusativ 'byka' zeigt das direkte Objekt von 'wziąć' (nehmen/packen). Ein weiteres Beispiel für kulturelle und sprachliche Verwandtschaft."},
            {"id": "gp_idiom3", "question": "Nie mój cyrk, nie moje _____.", "translation": "Nicht mein Zirkus, nicht meine Affen. (Nicht mein Problem.)", "options": ["małpy", "konie", "psy", "koty"], "correct": "małpy", "explanation": "'Nie mój cyrk, nie moje małpy' – berühmtes polnisches Sprichwort! Im Deutschen bekannt geworden als: 'Nicht mein Zirkus, nicht meine Affen.' Bedeutung: Die Probleme anderer gehen mich nichts an. Im Deutschen gibt es kein originales Äquivalent – 'Nicht mein Problem/Nicht mein Bier' sind die Entsprechungen. 'Moje małpy' im Nominativ Plural feminin. Dieses Sprichwort ist international populär geworden als Beispiel polnischer Weisheit."},
            {"id": "gp_idiom4", "question": "Robić z igły _____.", "translation": "Aus einer Mücke einen Elefanten machen.", "options": ["widły", "igłę", "widelec", "drzwi"], "correct": "widły", "explanation": "'Robić z igły widły' (aus einer Nadel eine Heugabel machen) – im Deutschen: 'Aus einer Mücke einen Elefanten machen.' Verschiedene Bilder, gleiche Bedeutung: eine Kleinigkeit übertreiben. 'Z igły' (aus einer Nadel, Genitiv) → 'widły' (Heugabel, Akkusativ). Die polnische Version verwendet den Reim: 'igły-widły'. Im Deutschen ist die Metapher mit Tier-Größenunterschied (Mücke vs. Elefant) typisch."},
            {"id": "gp_idiom5", "question": "Być w _____ wodzie.", "translation": "Im siebten Himmel sein. (Überglücklich sein.)", "options": ["siódmym niebie", "gorącej", "zimnej", "głębokiej"], "correct": "siódmym niebie", "explanation": "'Być w siódmym niebie' (im siebten Himmel sein) – identische Redewendung im Deutschen! 'Siódmym' ist Lokativ von 'siódmy' (siebter), 'niebie' Lokativ von 'niebo' (Himmel). Die idiomatische Wendung stammt aus religiöser Tradition (sieben Himmel im Islam/Judentum). Bedeutung: überglücklich sein. ACHTUNG: Die Option 'w gorącej wodzie' (in heißem Wasser) wäre eine ANDERE Redewendung: kąpany = ungestüm/hitzig."},
            {"id": "gp_idiom6", "question": "Mieć _____ na karku.", "translation": "Jemanden auf dem Hals haben. (Von jemandem belästigt werden.)", "options": ["kogoś", "coś", "ktoś", "komuś"], "correct": "kogoś", "explanation": "'Mieć kogoś na karku' (jemanden auf dem Nacken haben) – im Deutschen: 'jemanden auf dem Hals haben'. Ähnliche Körpermetapher! 'Kogoś' (jemanden, Akkusativ belebt von 'ktoś'). 'Na karku' (auf dem Nacken, Lokativ). Bedeutung: von jemandem belästigt oder kontrolliert werden. Im Polnischen 'kark' (Nacken), im Deutschen 'Hals' – leicht unterschiedliche Körperteile, aber dieselbe Metapher für unerwünschte Last."},
            {"id": "gp_idiom7", "question": "Wpaść jak _____ po szynkę.", "translation": "Direkt ins Fettnäpfchen treten. / In die Falle tappen.", "options": ["śliwka", "jabłko", "gruszka", "śliwki"], "correct": "śliwka", "explanation": "'Wpaść jak śliwka w kompot' (wie eine Pflaume ins Kompott fallen) – typisch polnische Redewendung ohne direkte deutsche Entsprechung. Bedeutung: in eine peinliche oder unerwartete Situation geraten. Im Deutschen: 'ins Fettnäpfchen treten' oder 'in die Falle tappen'. Die Pflaume-im-Kompott-Metapher ist humorvoll und bildreich. 'Wpaść' (hineinfallen, perfektiv) + 'jak' (wie) – Vergleichskonstruktion."},
            {"id": "gp_idiom8", "question": "Mieć muchy w _____.", "translation": "Eine Laune haben. / Schlecht gelaunt sein.", "options": ["nosie", "głowie", "oku", "uchu"], "correct": "nosie", "explanation": "'Mieć muchy w nosie' (Fliegen in der Nase haben) – im Deutschen: 'eine Laus über die Leber gelaufen haben' oder 'Flausen im Kopf haben'. Bedeutung: schlecht gelaunt oder launisch sein. 'Nosie' ist Lokativ von 'nos' (Nase) nach 'w'. Die Fliegen-in-der-Nase-Metapher ist rein polnisch – im Deutschen wird ein anderes Insekt (Laus) und ein anderer Körperteil verwendet. Beide Sprachen nutzen aber Insekten-Metaphern für Launenhaftigkeit."},
            {"id": "gp_idiom9", "question": "Z deszczu pod _____.", "translation": "Vom Regen in die Traufe. (Von einer schlechten Situation in eine schlimmere.)", "options": ["rynnę", "parasol", "dach", "niebo"], "correct": "rynnę", "explanation": "'Z deszczu pod rynnę' (vom Regen unter die Regenrinne) – im Deutschen: 'vom Regen in die Traufe'. Fast identische Redewendung! 'Z deszczu' (vom Regen, Genitiv) + 'pod rynnę' (unter die Regenrinne, Akkusativ). Bedeutung: eine schlechte Situation durch eine noch schlimmere ersetzen. 'Rynna' (Regenrinne) = 'Traufe' – die Metapher verwendet in beiden Sprachen Regen und Dachelemente."},
            {"id": "gp_idiom10", "question": "Trzymać kciuki za _____.", "translation": "Jemandem die Daumen drücken.", "options": ["kogoś", "komuś", "kimś", "ktoś"], "correct": "kogoś", "explanation": "'Trzymać kciuki za kogoś' (für jemanden die Daumen halten) – im Deutschen: 'jemandem die Daumen drücken'. 'Trzymać' (halten) vs. 'drücken' – leicht anderes Verb, aber dieselbe Geste! 'Kciuki' (Daumen, Nominativ Plural von 'kciuk'). 'Za kogoś' (für jemanden, 'za' + Akkusativ belebt). Im Deutschen: Dativ ('jemandem'). Identischer Aberglaube in beiden Kulturen: Daumen bringen Glück!"},
            {"id": "gp_idiom11", "question": "Być między _____ a kowadłem.", "translation": "Zwischen Hammer und Amboss sein. (In einer Zwickmühle sein.)", "options": ["młotem", "młot", "młota", "młotowi"], "correct": "młotem", "explanation": "'Między młotem a kowadłem' (zwischen Hammer und Amboss) – identische Redewendung! 'Młotem' ist Instrumentalis von 'młot' (Hammer) nach 'między'. 'Kowadłem' (Instrumentalis von 'kowadło' = Amboss). 'Między' + Instrumentalis Plural/beider Seiten. Im Deutschen: 'zwischen Hammer und Amboss'. Bedeutung: in einer aussichtslosen Lage zwischen zwei gefährlichen Alternativen. Gemeinsame europäische Handwerksmetapher."},
            {"id": "gp_idiom12", "question": "Gdzie kucharek sześć, tam nie ma co _____.", "translation": "Viele Köche verderben den Brei.", "options": ["jeść", "pić", "gotować", "robić"], "correct": "jeść", "explanation": "'Gdzie kucharek sześć, tam nie ma co jeść' (wo es sechs Köchinnen gibt, gibt es nichts zu essen) – im Deutschen: 'Viele Köche verderben den Brei.' Verschiedene Formulierung, gleiche Bedeutung: Zu viele Verantwortliche verhindern ein gutes Ergebnis. 'Kucharek' (Köchinnen, Genitiv Plural von 'kucharka'). Die polnische Version reimt sich (sześć-jeść), was sie besonders einprägsam macht. Die deutsche Version ist kürzer und direkter."},
            {"id": "gp_idiom13", "question": "Kto rano wstaje, temu _____ daje.", "translation": "Morgenstund hat Gold im Mund.", "options": ["Pan Bóg", "los", "noc", "świat"], "correct": "Pan Bóg", "explanation": "'Kto rano wstaje, temu Pan Bóg daje' (wer früh aufsteht, dem gibt der Herrgott) – im Deutschen: 'Morgenstund hat Gold im Mund.' Verschiedene Metaphern, gleiche Botschaft: Frühaufstehen wird belohnt. 'Temu' (dem, Dativ) – der Dativ zeigt den Empfänger. Die polnische Version ist explizit religiös ('Pan Bóg' = Herrgott), die deutsche abstrakt ('Gold im Mund'). Dieses Sprichwort zeigt kulturelle Unterschiede in der Weltanschauung."},
            {"id": "gp_idiom14", "question": "Leje jak z _____.", "translation": "Es gießt wie aus Eimern. (Es regnet in Strömen.)", "options": ["cebra", "wiadra", "nieba", "kranu"], "correct": "cebra", "explanation": "'Leje jak z cebra' (es gießt wie aus einem Zuber/Fass) – im Deutschen: 'Es gießt wie aus Eimern/Kübeln'. 'Cebra' ist Genitiv von 'ceber' (Zuber/großer Kübel), ein älteres polnisches Wort. 'Z cebra' (aus dem Zuber) – 'z' + Genitiv. Bedeutung: starker Regen. Beide Sprachen verwenden Behälter-Metaphern für Starkregen. Die polnische Variante mit 'ceber' klingt expressiver. Alternative: 'leje jak z wiadra' (aus dem Eimer)."},
            {"id": "gp_idiom15", "question": "Co dwie głowy, to nie _____.", "translation": "Zwei Köpfe sind besser als einer. (Vier Augen sehen mehr als zwei.)", "options": ["jedna", "dwie", "trzy", "żadna"], "correct": "jedna", "explanation": "'Co dwie głowy, to nie jedna' (zwei Köpfe sind nicht einer) – im Deutschen: 'Vier Augen sehen mehr als zwei' oder 'Zwei Köpfe sind besser als einer'. 'Co' (was/wenn) als verallgemeinernder Konnektor. 'Głowy' (Köpfe, Nominativ Plural von 'głowa'). Die polnische Version betont die Quantität (nicht einer, sondern zwei), die deutsche Version das Sehen (Augen). Bedeutung: Zusammenarbeit führt zu besseren Ergebnissen als allein."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k: v for k, v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")

issues = 0
for c in data:
    for item in c['items']:
        if '_____' not in item.get('question', ''):
            issues += 1
        if len(item.get('explanation', '')) < 200:
            issues += 1
if issues:
    print(f"FORMAT ISSUES: {issues}")
else:
    print("All format checks passed!")
