#!/usr/bin/env python3
"""Batch 11: Everyday Communication (categories 58-62) - greetings, opinions, time/frequency, emotions, directions."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "greetings_politeness",
        "name": "Powitania i grzeczność (Begrüßungen und Höflichkeit)",
        "description": "Formy grzecznościowe, powitania i pożegnania – Pan/Pani vs du/Sie",
        "icon": "hand.wave",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_greet1", "question": "_____ dobry!", "translation": "(Guten Tag!)", "options": ["Dzień", "Dobry", "Czas", "Rano"], "correct": "Dzień", "explanation": "'Dzień dobry' = 'Guten Tag' – die universelle formelle Begrüßung im Polnischen. Wörtlich: 'Tag guter' (umgekehrte Wortstellung!). Im Deutschen steht das Adjektiv vor dem Substantiv ('guten Tag'), im Polnischen kommt es nach dem Substantiv. Verwendet für Fremde, ältere Personen, in Geschäften und am Arbeitsplatz. Ab ca. 18:00 wechselt man zu 'Dobry wieczór!' (Guten Abend!)."},
            {"id": "gp_greet2", "question": "Do _____!", "translation": "(Auf Wiedersehen!)", "options": ["widzenia", "spotkania", "zobaczenia", "jutra"], "correct": "widzenia", "explanation": "'Do widzenia' = 'Auf Wiedersehen' – wörtlich: 'bis zum Sehen'. 'Do' = bis (+ Genitiv), 'widzenia' = Genitiv von 'widzenie' (das Sehen). Genau wie 'Auf Wiedersehen' = 'auf ein Wiedersehen'. Varianten: 'Do zobaczenia' (Bis bald, etwas weniger formell), 'Do jutra' (Bis morgen). Die informelle Alternative: 'Cześć!' (Tschüss/Hallo) – das gleiche Wort für Begrüßung UND Verabschiedung!"},
            {"id": "gp_greet3", "question": "Jak się Pan _____?", "translation": "(Wie geht es Ihnen?)", "options": ["miewa", "masz", "czujesz", "miewasz"], "correct": "miewa", "explanation": "'Jak się Pan miewa?' = 'Wie geht es Ihnen?' (an einen Mann). Beachten Sie: 'Pan' (Herr) + 3. Person Singular! Im Polnischen ist die Höflichkeitsform NICHT die 3. Person Plural (wie 'Sie' im Deutschen), sondern 3. Person Singular mit 'Pan' (Herr) oder 'Pani' (Dame). 'Pan miewa' = der Herr befindet sich. Für eine Frau: 'Jak się Pani miewa?'. Das ist ein fundamentaler Unterschied zum Deutschen!"},
            {"id": "gp_greet4", "question": "_____ bardzo.", "translation": "(Bitte sehr. / Gern geschehen.)", "options": ["Proszę", "Dziękuję", "Przepraszam", "Witam"], "correct": "Proszę", "explanation": "'Proszę' ist das vielseitigste polnische Wort! Es bedeutet: 1) 'bitte' (Höflichkeit), 2) 'hier, bitte' (beim Überreichen), 3) 'bitte, nehmen Sie Platz' (Einladung), 4) 'ja, bitte?' (am Telefon), 5) 'kommen Sie rein' (Aufforderung). Im Deutschen brauchen Sie verschiedene Wörter, im Polnischen deckt 'proszę' all dies ab. Es ist die Grundlage polnischer Höflichkeit!"},
            {"id": "gp_greet5", "question": "_____ bardzo.", "translation": "(Vielen Dank.)", "options": ["Dziękuję", "Proszę", "Przepraszam", "Witam"], "correct": "Dziękuję", "explanation": "'Dziękuję bardzo' = 'Danke sehr/Vielen Dank'. 'Dziękuję' kommt von 'dziękować' (danken). Informell: 'Dzięki!' (Danke!) oder 'Dzięks!' (noch lockerer, von Jugendlichen). Formell: 'Dziękuję Panu/Pani' (Ich danke Ihnen – an einen Mann/eine Frau). Die Antwort: 'Proszę' (Bitte) oder 'Nie ma za co' (Nichts zu danken, wörtlich: es gibt nichts wofür)."},
            {"id": "gp_greet6", "question": "Miło mi Pana _____.", "translation": "(Es freut mich, Sie kennenzulernen.)", "options": ["poznać", "znać", "widzieć", "spotykać"], "correct": "poznać", "explanation": "'Miło mi Pana poznać' = 'Es freut mich, Sie (einen Mann) kennenzulernen'. 'Miło mi' = 'es freut mich' (wörtlich: angenehm mir). 'Pana' = Genitiv/Akkusativ von 'Pan' (Sie/Herr). Für eine Frau: 'Miło mi Panią poznać' (Panią = Akkusativ von 'Pani'). Beachten Sie: Die Höflichkeitsform verlangt verschiedene Kasus je nach Verb – eine Herausforderung für Deutsche!"},
            {"id": "gp_greet7", "question": "_____, nie rozumiem.", "translation": "(Entschuldigung, ich verstehe nicht.)", "options": ["Przepraszam", "Proszę", "Dziękuję", "Witam"], "correct": "Przepraszam", "explanation": "'Przepraszam' vereint zwei deutsche Bedeutungen: 'Entschuldigung' (um Aufmerksamkeit bitten) UND 'Es tut mir leid' (Bedauern). 'Przepraszam, nie rozumiem' = 'Entschuldigung, ich verstehe nicht'. Auch: 'Przepraszam za spóźnienie' (Ich entschuldige mich für die Verspätung). Im Deutschen sind 'Entschuldigung' und 'Es tut mir leid' verschiedene Ausdrücke, im Polnischen reicht ein Wort!"},
            {"id": "gp_greet8", "question": "Proszę _____.", "translation": "(Bitte setzen Sie sich.)", "options": ["usiąść", "siada", "siadaj", "usiądź"], "correct": "usiąść", "explanation": "'Proszę' + Infinitiv ist die höflichste Befehlsform im Polnischen – höflicher als der Imperativ! 'Proszę usiąść' = 'Bitte setzen Sie sich' (wörtlich: ich bitte sich zu setzen). Vergleichen Sie: 'Usiądź!' (Setz dich! – Imperativ, informell), 'Proszę usiąść' (Bitte setzen Sie sich – formell), 'Niech Pan usiądzie' (Setzen Sie sich bitte – höflicher Imperativ mit 'niech Pan')."},
            {"id": "gp_greet9", "question": "Nie ma _____ co.", "translation": "(Keine Ursache. / Gern geschehen.)", "options": ["za", "na", "do", "o"], "correct": "za", "explanation": "'Nie ma za co' = 'Keine Ursache / Nichts zu danken' – wörtlich: 'es gibt nicht wofür'. 'Za co' = wofür (za + Akkusativ). Das ist die natürlichste Antwort auf 'Dziękuję'. Alternativen: 'Proszę' (Bitte), 'Cała przyjemność po mojej stronie' (Das Vergnügen ist ganz auf meiner Seite – sehr formell). 'Nie ma za co' ist perfekt für den Alltag – weder zu formell noch zu locker."},
            {"id": "gp_greet10", "question": "Czy mógłby Pan _____?", "translation": "(Könnten Sie das bitte wiederholen?)", "options": ["powtórzyć", "powtarza", "powtórzył", "powtarzać"], "correct": "powtórzyć", "explanation": "'Czy mógłby Pan powtórzyć?' = 'Könnten Sie (Herr) wiederholen?' – höfliche Bitte mit Konjunktiv. 'Mógłby' = er könnte (Konditionalis von 'móc'). Für eine Frau: 'Czy mogłaby Pani powtórzyć?'. Beachten Sie: Im Deutschen ändert sich 'könnten Sie' nicht nach Geschlecht, im Polnischen haben 'mógłby' (mask.) und 'mogłaby' (fem.) verschiedene Formen. Die Höflichkeit ist geschlechtsspezifisch!"},
            {"id": "gp_greet11", "question": "_____!", "translation": "(Prost! / Gesundheit!)", "options": ["Na zdrowie", "Smacznego", "Cześć", "Dzień dobry"], "correct": "Na zdrowie", "explanation": "'Na zdrowie!' hat ZWEI Bedeutungen: 1) 'Prost!' (beim Anstoßen) und 2) 'Gesundheit!' (nach dem Niesen). Wörtlich: 'auf die Gesundheit'. Im Deutschen sind das zwei verschiedene Ausdrücke. 'Na zdrowie' ist auch die Antwort auf 'Dziękuję' nach dem Essen: wenn jemand für das Essen dankt, kann der Koch sagen 'Na zdrowie!' (Zur Gesundheit! / Gern geschehen!). Drei Funktionen, ein Ausdruck!"},
            {"id": "gp_greet12", "question": "_____!", "translation": "(Guten Appetit!)", "options": ["Smacznego", "Na zdrowie", "Proszę", "Dzień dobry"], "correct": "Smacznego", "explanation": "'Smacznego!' = 'Guten Appetit!' – wörtlich: 'des Schmackhaften' (Genitiv!). Es kommt von 'smaczny' (schmackhaft/lecker) im Genitiv. Warum Genitiv? Es ist eine Verkürzung von 'Życzę smacznego jedzenia' (Ich wünsche schmackhaftes Essen). Polnische Wünsche stehen oft im Genitiv: 'Wesołych Świąt!' (Frohe Weihnachten!), 'Wszystkiego najlepszego!' (Alles Gute!)."},
            {"id": "gp_greet13", "question": "Jak się _____?", "translation": "(Wie heißt du?)", "options": ["nazywasz", "zowiesz", "mówisz", "wołasz"], "correct": "nazywasz", "explanation": "'Jak się nazywasz?' = 'Wie heißt du?' – wörtlich: 'Wie nennst du dich?' ('jak' = wie, 'się' = sich, 'nazywasz' = du nennst). Die formelle Version: 'Jak się Pan/Pani nazywa?' (Wie heißen Sie?). Im Deutschen: 'heißen' (intransitiv), im Polnischen: 'nazywać się' (reflexiv, sich nennen). Die Antwort: 'Nazywam się Jan' (Ich heiße Jan) oder kurz: 'Jestem Jan' (Ich bin Jan)."},
            {"id": "gp_greet14", "question": "Wszystkiego _____!", "translation": "(Alles Gute!)", "options": ["najlepszego", "dobrego", "najlepsze", "najlepszy"], "correct": "najlepszego", "explanation": "'Wszystkiego najlepszego!' = 'Alles Gute!' – wörtlich: 'alles des Besten' (Genitiv!). 'Wszystkiego' = Genitiv von 'wszystko' (alles), 'najlepszego' = Genitiv von 'najlepsze' (das Beste). Wie bei 'Smacznego!' stehen Glückwünsche im Genitiv. Der volle Satz wäre: 'Życzę ci wszystkiego najlepszego' (Ich wünsche dir alles Gute). Am Geburtstag: 'Wszystkiego najlepszego z okazji urodzin!'"},
            {"id": "gp_greet15", "question": "Proszę mi mówić _____.", "translation": "(Nennen Sie mich bitte Anna.)", "options": ["Anna", "Annę", "Annie", "Anny"], "correct": "Anna", "explanation": "'Proszę mi mówić Anna' = 'Bitte nennen Sie mich Anna' – beim Übergang von förmlich zu informell. 'Mi' = Dativ (mir). Beachten Sie: Der Name steht im Nominativ (Anna), nicht im Instrumental! Bei 'Ich bin Anna' dagegen: 'Jestem Anną' (Instrumental) oder 'Mam na imię Anna' (Nominativ). Das polnische Anredesystem ist komplex: 'Pan/Pani' (formell) → Vorname (informell) → 'ty'-Form (vertraut)."}
        ]
    },
    {
        "key": "expressions_of_opinion",
        "name": "Wyrażanie opinii (Meinungsäußerung)",
        "description": "Jak wyrażać opinie, zgadzać się i nie zgadzać po polsku",
        "icon": "bubble.left.and.bubble.right",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_opin1", "question": "Moim _____ to dobry pomysł.", "translation": "(Meiner Meinung nach ist das eine gute Idee.)", "options": ["zdaniem", "opinia", "myśleniem", "poglądem"], "correct": "zdaniem", "explanation": "'Moim zdaniem' = 'meiner Meinung nach' – wörtlich: 'meinem Urteil nach'. 'Zdaniem' ist der Instrumental von 'zdanie' (Meinung/Satz). Struktur: Possessivpronomen im Instrumental + 'zdaniem'. Im Deutschen: 'meiner Meinung nach' (Genitiv + nach). Im Polnischen reicht der Instrumental ohne Präposition! Alternativen: 'Według mnie' (laut mir, + Genitiv), 'W mojej opinii' (in meiner Meinung)."},
            {"id": "gp_opin2", "question": "_____, że masz rację.", "translation": "(Ich finde, dass du Recht hast.)", "options": ["Uważam", "Uważasz", "Uważa", "Uważamy"], "correct": "Uważam", "explanation": "'Uważam, że' = 'Ich finde/denke, dass' – persönliche Meinung mit voller Überzeugung. 'Uważać' bedeutet auch 'aufpassen' (Achtung!), aber mit 'że' wird es zu 'meinen/finden'. Abstufung der Sicherheit: 'Uważam, że' (ich bin überzeugt) > 'Myślę, że' (ich denke) > 'Wydaje mi się, że' (mir scheint) > 'Chyba' (wahrscheinlich). Im Polnischen kann man die Sicherheitsstufe sehr präzise ausdrücken!"},
            {"id": "gp_opin3", "question": "Zgadzam się _____ tobą.", "translation": "(Ich stimme dir zu.)", "options": ["z", "na", "do", "o"], "correct": "z", "explanation": "'Zgadzać się z' + Instrumental = 'zustimmen' + Dativ. 'Z tobą' = 'mit dir' (Instrumental). Im Deutschen: 'Ich stimme DIR zu' (Dativ), im Polnischen: 'Zgadzam się Z TOBĄ' (mit + Instrumental). Beachten Sie den Unterschied! 'Zgadzam się z twoją opinią' (Ich stimme deiner Meinung zu) – 'opinią' im Instrumental. Negation: 'Nie zgadzam się z tobą' (Ich stimme dir nicht zu)."},
            {"id": "gp_opin4", "question": "To _____ od sytuacji.", "translation": "(Das hängt von der Situation ab.)", "options": ["zależy", "zależa", "zależę", "zależysz"], "correct": "zależy", "explanation": "'To zależy od' + Genitiv = 'Das hängt ab von' + Dativ. 'Od sytuacji' = 'von der Situation' (Genitiv). Im Deutschen: 'von' + Dativ, im Polnischen: 'od' + Genitiv – verschiedene Kasus! 'To zależy' allein ist eine nützliche Antwort: 'Das kommt darauf an'. 'Zależy mi na czymś' = 'mir liegt etwas daran' – eine andere Bedeutung! 'Zależy' ist eines der nützlichsten polnischen Wörter."},
            {"id": "gp_opin5", "question": "Masz absolutną _____!", "translation": "(Du hast vollkommen Recht!)", "options": ["rację", "prawdę", "słuszność", "opinię"], "correct": "rację", "explanation": "'Mieć rację' = 'Recht haben' – ein fester Ausdruck. 'Rację' ist Akkusativ von 'racja' (Recht/Vernunft). Im Deutschen: 'Recht haben' (ohne Artikel), im Polnischen: 'mieć rację' (mit Objekt im Akkusativ). Die Verneinung: 'Nie masz racji' – nach 'nie' wechselt der Akkusativ zum Genitiv! 'Racji' statt 'rację'. Diese Genitivregel nach Verneinung ist eine fundamentale polnische Grammatikregel!"},
            {"id": "gp_opin6", "question": "Jestem _____ tym, żeby pojechać nad morze.", "translation": "(Ich bin dafür, ans Meer zu fahren.)", "options": ["za", "na", "o", "przy"], "correct": "za", "explanation": "'Być za' + Instrumental = 'dafür sein'. 'Za tym' = 'dafür' (wörtlich: 'für dem'). 'Być za' (dafür sein) vs. 'być przeciw' (dagegen sein) + Dativ. 'Jestem za tym, żeby...' = 'Ich bin dafür, dass...' Das 'żeby' leitet den Zwecksatz ein. Im Deutschen: 'dafür sein + zu + Infinitiv', im Polnischen: 'być za + żeby + konjugiertes Verb'. Der Zwecksatz hat im Polnischen ein konjugiertes Verb!"},
            {"id": "gp_opin7", "question": "_____ herbatę od kawy.", "translation": "(Ich bevorzuge Tee gegenüber Kaffee.)", "options": ["Wolę", "Lubię", "Chcę", "Piję"], "correct": "Wolę", "explanation": "'Woleć A od B' = 'A gegenüber B bevorzugen'. 'Wolę herbatę' (Akkusativ) + 'od kawy' (od + Genitiv). Im Deutschen: 'Tee gegenüber Kaffee', im Polnischen: 'herbatę OD kawy' (Tee VOM Kaffee – wörtlich). Die Präposition 'od' (von, ab) markiert das weniger Bevorzugte. Auch möglich: 'Wolę herbatę niż kawę' (Ich bevorzuge Tee als Kaffee) – 'niż' = als (bei Vergleichen)."},
            {"id": "gp_opin8", "question": "Szczerze _____, nie podoba mi się to.", "translation": "(Ehrlich gesagt, gefällt mir das nicht.)", "options": ["mówiąc", "mówić", "mówię", "mów"], "correct": "mówiąc", "explanation": "'Szczerze mówiąc' = 'ehrlich gesagt' – ein Adverbialpartizip (Gerundium). 'Mówiąc' ist das gegenwärtige Adverbialpartizip von 'mówić' (sprechen). Im Deutschen: 'gesagt' (Partizip Perfekt), im Polnischen: 'mówiąc' (Partizip Präsens). Weitere nützliche Wendungen: 'Ogólnie mówiąc' (allgemein gesagt), 'Krótko mówiąc' (kurz gesagt), 'Delikatnie mówiąc' (gelinde gesagt). Das '-ąc'-Partizip ist sehr produktiv!"},
            {"id": "gp_opin9", "question": "_____ o to mi chodzi!", "translation": "(Genau das meine ich!)", "options": ["Właśnie", "Także", "Chyba", "Może"], "correct": "Właśnie", "explanation": "'Właśnie o to mi chodzi!' = 'Genau darum geht es mir!' 'Właśnie' = genau/eben, ein vielseitiges Wort. 'Chodzić o' = 'es geht um' (unpersönlich). 'O to mi chodzi' = 'darum geht es mir' – 'o' + Akkusativ, 'mi' = Dativ. Im Deutschen: 'Es geht mir darum'. 'Właśnie' verstärkt wie 'genau/eben'. Auch: 'Właśnie przyszedłem' (Ich bin gerade gekommen) – hier bedeutet es 'gerade' (zeitlich). Kontextabhängig!"},
            {"id": "gp_opin10", "question": "Nie mam nic _____ temu.", "translation": "(Ich habe nichts dagegen.)", "options": ["przeciwko", "za", "na", "do"], "correct": "przeciwko", "explanation": "'Nie mieć nic przeciwko' + Dativ = 'nichts dagegen haben'. 'Przeciwko temu' = 'dagegen/gegen dem' (Dativ). Im Deutschen: 'dagegen' (Pronomen), im Polnischen: 'przeciwko' + Dativ. Beachten Sie: 'przeciwko' (gegen, bei Meinungen) vs. 'przeciw' (kürzer, gleiche Bedeutung). 'Nie mam nic przeciwko temu' ist eine höfliche Zustimmung – wörtlich: 'Ich habe nichts gegen dem'. Formeller als einfaches 'Dobrze' (Gut/OK)."},
            {"id": "gp_opin11", "question": "Z jednej strony tak, z _____ nie.", "translation": "(Einerseits ja, andererseits nein.)", "options": ["drugiej", "innej", "trzeciej", "mojej"], "correct": "drugiej", "explanation": "'Z jednej strony... z drugiej strony' = 'einerseits... andererseits'. Wörtlich: 'von einer Seite... von der zweiten Seite'. 'Z' + Genitiv (von), 'jednej' = einer, 'drugiej' = zweiter/anderer, 'strony' = Seite (Genitiv). Im Deutschen: 'einerseits/andererseits' (Adverbien), im Polnischen: vollständige Präpositionalphrasen. Diese Struktur ist nützlich für ausgewogene Argumentation und Diplomatie."},
            {"id": "gp_opin12", "question": "_____ mi się ta muzyka.", "translation": "(Diese Musik gefällt mir.)", "options": ["Podoba", "Podoba się", "Lubię", "Podobam"], "correct": "Podoba", "explanation": "'Podoba mi się' = 'es gefällt mir' – fast identisch mit dem Deutschen! Subjekt ('ta muzyka') + 'podoba' (gefällt) + Dativ ('mi' = mir) + 'się'. Die Struktur ist parallel: 'Diese Musik gefällt mir' ↔ 'Ta muzyka podoba mi się'. Im Plural: 'Podobają mi się te książki' (Diese Bücher gefallen mir). Negation: 'Nie podoba mi się' (Es gefällt mir nicht). Die reflexive Partikel 'się' ist obligatorisch!"},
            {"id": "gp_opin13", "question": "To jest bez _____.", "translation": "(Das ergibt keinen Sinn. / Das ist Unsinn.)", "options": ["sensu", "sens", "sensem", "sensowi"], "correct": "sensu", "explanation": "'Bez sensu' = 'ohne Sinn / sinnlos' – 'bez' (ohne) + Genitiv. 'Sensu' ist der Genitiv von 'sens'. Im Deutschen: 'ohne + Akkusativ' (ohne den Sinn), im Polnischen: 'bez + Genitiv' (ohne des Sinns). 'To jest bez sensu' = 'Das ist Unsinn/sinnlos'. Weitere 'bez'-Ausdrücke: 'bez problemu' (kein Problem), 'bez wątpienia' (ohne Zweifel), 'bez żartów' (ohne Witze / im Ernst)."},
            {"id": "gp_opin14", "question": "Jestem _____ temu pomysłowi.", "translation": "(Ich bin gegen diese Idee.)", "options": ["przeciwny", "przeciwna", "za", "przy"], "correct": "przeciwny", "explanation": "'Być przeciwnym' + Dativ = 'gegen etwas sein'. 'Przeciwny temu pomysłowi' = 'gegen dieser Idee' (Dativ). Im Deutschen: 'gegen + Akkusativ', im Polnischen: Adjektiv 'przeciwny' + Dativ! Beachten Sie: 'przeciwny' (mask.), 'przeciwna' (fem.), 'przeciwne' (neutr.) – das Adjektiv stimmt mit dem Sprecher überein. Eine Frau sagt: 'Jestem przeciwna'. Wieder die geschlechtsspezifische Grammatik!"},
            {"id": "gp_opin15", "question": "Nie _____ się z tym zgodzić.", "translation": "(Ich kann dem nicht zustimmen.)", "options": ["mogę", "mogą", "może", "możesz"], "correct": "mogę", "explanation": "'Nie mogę się z tym zgodzić' = 'Ich kann dem nicht zustimmen' – höfliche Ablehnung. 'Móc' (können) + 'się zgodzić z' + Instrumental (zustimmen mit). 'Z tym' = 'damit' (Instrumental). Diese Formulierung ist diplomatischer als direktes 'Nie zgadzam się!' (Ich stimme nicht zu!). In Diskussionen und Meetings nützlich. 'Mogę' konjugiert unregelmäßig: mogę, możesz, może, możemy, możecie, mogą."}
        ]
    },
    {
        "key": "time_frequency",
        "name": "Czas i częstotliwość (Zeit und Häufigkeit)",
        "description": "Wyrażanie czasu, częstotliwości i sekwencji zdarzeń po polsku",
        "icon": "clock.arrow.circlepath",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_tfreq1", "question": "_____ piję kawę rano.", "translation": "(Ich trinke immer morgens Kaffee.)", "options": ["Zawsze", "Nigdy", "Czasami", "Rzadko"], "correct": "Zawsze", "explanation": "'Zawsze' = 'immer' – das Frequenzadverb für 100% Häufigkeit. Position: flexibel, meist am Satzanfang oder vor dem Verb. Im Deutschen kann 'immer' auch mitten im Satz stehen, im Polnischen ist die Anfangsposition am natürlichsten. Skala der Häufigkeit: 'zawsze' (immer) > 'zwykle' (gewöhnlich) > 'często' (oft) > 'czasami' (manchmal) > 'rzadko' (selten) > 'nigdy' (nie)."},
            {"id": "gp_tfreq2", "question": "_____ nie jem mięsa.", "translation": "(Ich esse nie Fleisch.)", "options": ["Nigdy", "Zawsze", "Często", "Czasami"], "correct": "Nigdy", "explanation": "'Nigdy nie' = 'nie/niemals' – doppelte Verneinung ist im Polnischen PFLICHT! Im Deutschen: 'Ich esse nie Fleisch' (einfache Verneinung), im Polnischen: 'Nigdy NIE jem mięsa' (doppelte Verneinung). Wenn Sie 'Nigdy jem mięsa' sagen (ohne 'nie'), klingt es falsch und unvollständig. Die doppelte Verneinung ist kein Fehler wie im Deutschen, sondern eine grammatische Regel!"},
            {"id": "gp_tfreq3", "question": "_____ chodzę do kina.", "translation": "(Manchmal gehe ich ins Kino.)", "options": ["Czasami", "Zawsze", "Nigdy", "Codziennie"], "correct": "Czasami", "explanation": "'Czasami' = 'manchmal' – mittlere Häufigkeit. Varianten: 'czasem' (kürzer, gleiche Bedeutung), 'niekiedy' (gelegentlich, etwas formeller), 'od czasu do czasu' (ab und zu, wörtlich: von Zeit zu Zeit). 'Czasami' ist das geläufigste Wort für unregelmäßige Häufigkeit. Es steht meist am Satzanfang: 'Czasami chodzę do kina' – gleiche Position wie das deutsche 'Manchmal + V2'."},
            {"id": "gp_tfreq4", "question": "Co _____ gram w piłkę.", "translation": "(Jede Woche spiele ich Fußball.)", "options": ["tydzień", "dzień", "miesiąc", "rok"], "correct": "tydzień", "explanation": "'Co tydzień' = 'jede Woche' – das Muster 'co + Zeiteinheit' drückt regelmäßige Intervalle aus. Im Deutschen: 'jede(r/s) + Substantiv', im Polnischen: 'co' + Substantiv im Akkusativ. Weitere: 'co dzień' (jeden Tag), 'co miesiąc' (jeden Monat), 'co rok' (jedes Jahr), 'co godzinę' (jede Stunde). ACHTUNG: 'codziennie' (täglich) ist ein eigenes Adverb – eleganter als 'co dzień'."},
            {"id": "gp_tfreq5", "question": "_____ uczę się polskiego.", "translation": "(Ich lerne jeden Tag Polnisch.)", "options": ["Codziennie", "Co dziennie", "Dziennie", "Codzienny"], "correct": "Codziennie", "explanation": "'Codziennie' = 'jeden Tag / täglich' – ein zusammengesetztes Adverb aus 'co' + 'dziennie'. Es ist EIN Wort (zusammengeschrieben!), nicht zu verwechseln mit 'codzienny' (täglich – Adjektiv!). 'Codziennie' = Adverb (wie?), 'codzienny' = Adjektiv (welcher?). 'Codziennie ćwiczę' (Ich übe täglich) vs. 'codzienna praca' (tägliche Arbeit). Im Deutschen: 'täglich' ist beides."},
            {"id": "gp_tfreq6", "question": "Najpierw zjem śniadanie, _____ pójdę do pracy.", "translation": "(Zuerst esse ich Frühstück, dann gehe ich zur Arbeit.)", "options": ["potem", "przedtem", "teraz", "wtedy"], "correct": "potem", "explanation": "'Najpierw... potem' = 'zuerst... dann' – Sequenzkonnektoren. 'Najpierw' = zuerst (Superlativ von 'pierw-' = erst), 'potem' = dann/danach. Im Deutschen: 'zuerst... dann', fast identisch. Weitere Sequenzmarker: 'następnie' (anschließend, formeller), 'później' (später), 'na końcu' (am Ende/zuletzt). Die Sequenz ist im Polnischen genauso logisch aufgebaut wie im Deutschen."},
            {"id": "gp_tfreq7", "question": "_____ skończyłem pracę.", "translation": "(Ich habe gerade die Arbeit beendet.)", "options": ["Właśnie", "Zaraz", "Potem", "Kiedyś"], "correct": "Właśnie", "explanation": "'Właśnie' = 'gerade / eben' (zeitlich) – eine Handlung, die SOEBEN abgeschlossen wurde. 'Właśnie skończyłem' = 'Ich habe gerade beendet'. Nicht verwechseln mit 'gerade' als 'geradeaus' = 'prosto'! 'Właśnie' hat auch die Bedeutung 'genau/eben' (bestätigend): 'Właśnie tak!' (Genau so!). Im Deutschen: 'gerade' kann beides, im Polnischen hat 'właśnie' ebenfalls beide Funktionen."},
            {"id": "gp_tfreq8", "question": "_____ wrócę.", "translation": "(Ich komme gleich zurück.)", "options": ["Zaraz", "Właśnie", "Dawno", "Kiedyś"], "correct": "Zaraz", "explanation": "'Zaraz' = 'gleich / sofort' – in der nächsten Zukunft. 'Zaraz wrócę' = 'Ich komme gleich zurück'. Abstufung der Nähe: 'natychmiast' (sofort, am dringendsten) > 'zaraz' (gleich, in Kürze) > 'wkrótce' (bald) > 'niedługo' (in nicht langer Zeit). ACHTUNG: 'zaraz' wird manchmal etwas... großzügig verwendet. 'Zaraz wrócę' kann auch 5-15 Minuten bedeuten, je nach Person!"},
            {"id": "gp_tfreq9", "question": "_____ często ćwiczysz?", "translation": "(Wie oft übst du?)", "options": ["Jak", "Ile", "Co", "Kiedy"], "correct": "Jak", "explanation": "'Jak często' = 'wie oft' – Frage nach der Häufigkeit. 'Jak' = 'wie', 'często' = 'oft'. Im Deutschen: 'wie oft' – exakt gleiche Struktur! Andere Häufigkeitsfragen: 'Ile razy?' (Wie viele Male?), 'Co ile?' (In welchen Abständen?). Typische Antworten: 'dwa razy w tygodniu' (zweimal pro Woche), 'raz na miesiąc' (einmal im Monat), 'co drugi dzień' (jeden zweiten Tag)."},
            {"id": "gp_tfreq10", "question": "Do tej _____ wszystko szło dobrze.", "translation": "(Bis jetzt lief alles gut.)", "options": ["pory", "chwili", "czasu", "godziny"], "correct": "pory", "explanation": "'Do tej pory' = 'bis jetzt / bisher' – wörtlich: 'bis dieser Zeit'. 'Do' + Genitiv, 'tej pory' = Genitiv von 'ta pora' (diese Zeit/Jahreszeit). Varianten: 'dotąd' (bis hierher, kürzer), 'dotychczas' (bisher, formeller), 'jak dotąd' (wie bisher). 'Do tej pory' ist das geläufigste und neutralste. Im Deutschen: 'bis jetzt' ist ebenfalls die universellste Form unter den Alternativen."},
            {"id": "gp_tfreq11", "question": "_____ będę punktualny.", "translation": "(Von nun an werde ich pünktlich sein.)", "options": ["Odtąd", "Dotąd", "Stąd", "Skąd"], "correct": "Odtąd", "explanation": "'Odtąd' = 'von nun an / ab jetzt' – markiert den Beginn eines neuen Zustands. 'Od' (von/ab) + 'tąd' (hier/da). Verwechslungsgefahr: 'odtąd' (von nun an, zeitlich) vs. 'dotąd' (bis jetzt/hierher) vs. 'stąd' (von hier, örtlich). Drei Richtungsadverbien mit demselben Stamm '-tąd': 'od' = von... weg, 'do' = bis... hin, 's-/z-' = von diesem Ort. Im Deutschen: drei verschiedene Wörter ohne gemeinsamen Stamm."},
            {"id": "gp_tfreq12", "question": "W tym _____ jestem zajęty.", "translation": "(Im Moment bin ich beschäftigt.)", "options": ["momencie", "moment", "czasu", "chwila"], "correct": "momencie", "explanation": "'W tym momencie' = 'in diesem Moment' – 'w' + Lokativ. 'Momencie' ist der Lokativ von 'moment'. Im Deutschen: 'im Moment/Augenblick' – identische Präpositionalstruktur! Alternativen: 'w tej chwili' (in diesem Augenblick), 'teraz' (jetzt, kürzer), 'aktualnie' (aktuell). 'W tym momencie' klingt etwas dramatischer als einfaches 'teraz' – es betont den genauen Zeitpunkt."},
            {"id": "gp_tfreq13", "question": "Już _____ mieszkam w Berlinie.", "translation": "(Ich wohne nicht mehr in Berlin.)", "options": ["nie", "tak", "tu", "teraz"], "correct": "nie", "explanation": "'Już nie' = 'nicht mehr' – Ende eines Zustands. 'Już' = schon/bereits, 'już nie' = nicht mehr (wörtlich: schon nicht). Im Deutschen: 'nicht mehr', im Polnischen: 'już nie' – umgekehrte Reihenfolge! 'Jeszcze' (noch) ist das Gegenstück: 'Jeszcze mieszkam' (Ich wohne noch). Paar: 'jeszcze' (noch) ↔ 'już nie' (nicht mehr), 'jeszcze nie' (noch nicht) ↔ 'już' (schon). Diese vier bilden ein logisches System!"},
            {"id": "gp_tfreq14", "question": "_____ nie skończyłem.", "translation": "(Ich bin noch nicht fertig.)", "options": ["Jeszcze", "Już", "Dopiero", "Zaraz"], "correct": "Jeszcze", "explanation": "'Jeszcze nie' = 'noch nicht' – ein Zustand, der andauert, aber sich ändern wird. 'Jeszcze nie skończyłem' = 'Ich habe noch nicht beendet / Ich bin noch nicht fertig'. 'Jeszcze' allein = 'noch': 'Jeszcze pracuję' (Ich arbeite noch). 'Jeszcze' hat auch die Bedeutung 'noch (dazu)': 'Jeszcze jedno piwo' (Noch ein Bier). Kontext bestimmt: 'noch' (temporal) oder 'noch/zusätzlich' (additiv)."},
            {"id": "gp_tfreq15", "question": "Na co _____ pracuję z domu.", "translation": "(Im Alltag arbeite ich von zu Hause.)", "options": ["dzień", "tydzień", "rano", "miesiąc"], "correct": "dzień", "explanation": "'Na co dzień' = 'im Alltag / alltäglich' – wörtlich: 'für jeden Tag'. Eine feste Wendung, die den gewöhnlichen Tagesablauf beschreibt. 'Na co dzień pracuję z domu' = 'Alltäglich arbeite ich von zu Hause'. Nicht verwechseln mit 'codziennie' (jeden Tag – Frequenz) vs. 'na co dzień' (im Alltag – Gewohnheit). 'Na co dzień' beschreibt den Standard, 'codziennie' die Regelmäßigkeit."}
        ]
    },
    {
        "key": "emotions_feelings",
        "name": "Emocje i uczucia (Emotionen und Gefühle)",
        "description": "Wyrażanie emocji i stanów uczuciowych – konstrukcje z celownikiem i narzędnikiem",
        "icon": "heart.circle",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_emot1", "question": "Cieszę się _____ twojego sukcesu.", "translation": "(Ich freue mich über deinen Erfolg.)", "options": ["z", "na", "o", "za"], "correct": "z", "explanation": "'Cieszyć się z' + Genitiv = 'sich freuen über' + Akkusativ. 'Z twojego sukcesu' = 'aus deinem Erfolg' (wörtlich). Im Deutschen: 'über + Akkusativ', im Polnischen: 'z + Genitiv'. ACHTUNG: 'Cieszyć się na' + Akkusativ = 'sich freuen auf' (Zukunft): 'Cieszę się na wakacje' (Ich freue mich auf die Ferien). Die Präposition ändert die Bedeutung: 'z' = retroaktive Freude, 'na' = vorausschauende Freude!"},
            {"id": "gp_emot2", "question": "Boję się _____.", "translation": "(Ich habe Angst vor Spinnen.)", "options": ["pająków", "pająki", "pająkom", "pająkami"], "correct": "pająków", "explanation": "'Bać się' + Genitiv = 'Angst haben vor' + Dativ. 'Pająków' = Genitiv Plural von 'pająk' (Spinne). Im Deutschen: 'vor + Dativ', im Polnischen: Genitiv ohne Präposition! Weitere Beispiele: 'Boję się ciemności' (Ich fürchte die Dunkelheit), 'Boję się egzaminu' (Ich habe Angst vor der Prüfung). 'Bać się' ist reflexiv (się), wie 'sich fürchten', aber mit Genitiv statt 'vor + Dativ'."},
            {"id": "gp_emot3", "question": "Tęsknię _____ rodziną.", "translation": "(Ich vermisse meine Familie.)", "options": ["za", "z", "o", "na"], "correct": "za", "explanation": "'Tęsknić za' + Instrumental = 'vermissen / sich sehnen nach'. 'Za rodziną' = 'nach der Familie' (Instrumental). Im Deutschen: 'vermissen' (direkt + Akkusativ), im Polnischen: 'tęsknić za' (sich sehnen nach). 'Tęsknię za Polską' (Ich vermisse Polen / Ich sehne mich nach Polen). Dieses Wort drückt ein tiefes emotionales Verlangen aus – stärker als nur 'vermissen'. Es gibt dafür sogar ein eigenes polnisches Konzept: 'tęsknota'."},
            {"id": "gp_emot4", "question": "Martwię się _____ ciebie.", "translation": "(Ich mache mir Sorgen um dich.)", "options": ["o", "za", "z", "na"], "correct": "o", "explanation": "'Martwić się o' + Akkusativ = 'sich Sorgen machen um' + Akkusativ. 'O ciebie' = 'um dich'. Hier stimmen die Kasus überein! Im Deutschen: 'um + Akkusativ', im Polnischen: 'o + Akkusativ'. Das reflexive 'się' (sich) ist obligatorisch. Die persönliche Form: 'Martwię się' (Ich mache mir Sorgen), die unpersönliche: 'Martwi mnie to' (Das macht mir Sorgen / Das beunruhigt mich) – 'mnie' im Akkusativ."},
            {"id": "gp_emot5", "question": "Jest mi _____.", "translation": "(Mir ist traurig.)", "options": ["smutno", "smutny", "smutna", "smutek"], "correct": "smutno", "explanation": "'Jest mi smutno' = 'Mir ist traurig' – unpersönliche Gefühlskonstruktion mit Dativ + Adverb. NICHT Adjektiv ('smutny'), sondern ADVERB ('smutno')! Im Deutschen: 'Mir ist traurig/kalt/warm' + Adjektiv. Im Polnischen: 'Jest mi' + Adverb auf '-o'. Die '-o'-Endung macht den Unterschied: 'smutny' (traurig – Adjektiv, beschreibt Person), 'smutno' (traurig – Adverb, beschreibt Gefühlszustand). Unpersönlich = immer Adverb!"},
            {"id": "gp_emot6", "question": "Jestem _____ na siebie.", "translation": "(Ich bin wütend auf mich selbst.)", "options": ["zły", "zła", "źle", "złość"], "correct": "zły", "explanation": "'Zły na' + Akkusativ = 'wütend/böse auf' + Akkusativ. 'Na siebie' = 'auf sich selbst'. Hier stimmen die Konstruktionen perfekt überein! Beachten Sie: 'zły' (mask.) vs. 'zła' (fem.) – eine Frau sagt: 'Jestem zła na siebie'. 'Zły' hat auch die Bedeutung 'schlecht/böse': 'zły człowiek' (böser Mensch). Im Deutschen: 'böse' und 'schlecht' sind verschieden, im Polnischen: 'zły' deckt beides ab."},
            {"id": "gp_emot7", "question": "Jestem dumny _____ mojego syna.", "translation": "(Ich bin stolz auf meinen Sohn.)", "options": ["z", "na", "o", "za"], "correct": "z", "explanation": "'Dumny z' + Genitiv = 'stolz auf' + Akkusativ. 'Z mojego syna' = 'aus meinem Sohn' (wörtlich). Im Deutschen: 'auf + Akkusativ', im Polnischen: 'z + Genitiv'. Die Präpositionen sind komplett verschieden! Das muss man auswendig lernen. Weitere Gefühle mit verschiedenen Präpositionen: 'zadowolony z' (zufrieden mit), 'zaskoczony' + Instrumental (überrascht von), 'zainteresowany' + Instrumental (interessiert an)."},
            {"id": "gp_emot8", "question": "_____ mi go.", "translation": "(Er tut mir leid.)", "options": ["Żal", "Smutno", "Szkoda", "Boli"], "correct": "Żal", "explanation": "'Żal mi go' = 'Er tut mir leid' – eine unpersönliche Mitleidskonstruktion. 'Żal' (Bedauern/Leid) + Dativ ('mi' = mir) + Genitiv ('go' = seiner). Kein Verb nötig! Im Deutschen: 'tun + leid' (Verb), im Polnischen: nur ein Substantiv ('żal') + Kasus. Auch: 'Żal mi, że...' (Es tut mir leid, dass...). 'Szkoda' ist ähnlich: 'Szkoda mi go' (Schade um ihn / Er tut mir leid)."},
            {"id": "gp_emot9", "question": "_____ mi się ta muzyka.", "translation": "(Diese Musik gefällt mir.)", "options": ["Podoba", "Lubię", "Cieszy", "Bawi"], "correct": "Podoba", "explanation": "'Podoba mi się' = 'es gefällt mir' – die Standardkonstruktion für Gefallen/Anziehung. Subjekt ('ta muzyka') + 'podoba' + Dativ ('mi') + 'się'. Im Deutschen: identische Struktur! 'Die Musik gefällt mir'. ACHTUNG: Der Unterschied zu 'lubić': 'Podoba mi się' = erster Eindruck/Anziehung, 'Lubię to' = ich mag es (kenne es bereits). Bei Menschen: 'Podoba mi się' = ich finde sie/ihn attraktiv, 'Lubię ją/go' = ich mag sie/ihn."},
            {"id": "gp_emot10", "question": "Nie mogę się _____ wakacji!", "translation": "(Ich kann die Ferien kaum erwarten!)", "options": ["doczekać", "cieszyć", "spodziewać", "bać"], "correct": "doczekać", "explanation": "'Nie móc się doczekać' + Genitiv = 'es kaum erwarten können'. 'Doczekać' = 'erwarten/erleben' (perfektiv). 'Nie mogę się doczekać wakacji' = 'Ich kann die Ferien kaum erwarten!' 'Wakacji' = Genitiv Plural von 'wakacje' (Ferien, immer Plural!). Diese Konstruktion drückt freudige Ungeduld aus. Im Deutschen: 'kaum erwarten können' – die doppelte Verneinung ('Ich kann nicht nicht erwarten') wird zu 'kaum'."},
            {"id": "gp_emot11", "question": "Mam _____ tej pogody.", "translation": "(Ich habe genug von diesem Wetter.)", "options": ["dość", "dużo", "mało", "trochę"], "correct": "dość", "explanation": "'Mieć dość' + Genitiv = 'genug haben von' + Dativ – Frustration/Sättigung. 'Dość' = genug. 'Tej pogody' = Genitiv von 'ta pogoda' (dieses Wetter). Im Deutschen: 'von + Dativ', im Polnischen: direkt Genitiv. Stärkere Variante: 'Mam serdecznie dość!' (Ich habe herzlich genug!). 'Dość' hat auch die neutrale Bedeutung 'genug/ziemlich': 'dość dobrze' (ziemlich gut). Kontext bestimmt: Frustration oder neutrale Menge."},
            {"id": "gp_emot12", "question": "Denerwuję się _____ egzaminem.", "translation": "(Ich bin vor der Prüfung nervös.)", "options": ["przed", "na", "o", "z"], "correct": "przed", "explanation": "'Denerwować się przed' + Instrumental = 'nervös sein vor' + Dativ. 'Przed egzaminem' = 'vor der Prüfung' (Instrumental). Im Deutschen: 'vor + Dativ', im Polnischen: 'przed + Instrumental'. 'Przed' (vor, zeitlich/räumlich) verlangt immer den Instrumental. 'Denerwować się' = 'sich aufregen/nervös sein' – reflexiv mit 'się'. Auch: 'Denerwuje mnie to' (Das regt mich auf) – 'mnie' im Akkusativ (persönliche Konstruktion)."},
            {"id": "gp_emot13", "question": "Czuję się _____.", "translation": "(Ich fühle mich einsam.)", "options": ["samotny", "samotna", "samotnie", "samotność"], "correct": "samotny", "explanation": "'Czuć się' + Adjektiv = 'sich fühlen' + Adjektiv – eine persönliche Konstruktion (anders als 'jest mi' + Adverb!). Das Adjektiv muss zum Geschlecht des Sprechers passen: 'Czuję się samotny' (Mann) vs. 'Czuję się samotna' (Frau). Vergleichen Sie: 'Jest mi samotno' (unpersönlich, mit Adverb) vs. 'Czuję się samotny' (persönlich, mit Adjektiv). Beide bedeuten dasselbe, haben aber verschiedene Grammatik!"},
            {"id": "gp_emot14", "question": "Wstyd _____ za to zachowanie.", "translation": "(Ich schäme mich für dieses Verhalten.)", "options": ["mi", "mnie", "ja", "się"], "correct": "mi", "explanation": "'Wstyd mi' = 'mir ist peinlich / ich schäme mich' – unpersönlich mit Dativ. 'Mi' = Dativ (mir). 'Za to zachowanie' = 'für dieses Verhalten' ('za' + Akkusativ). Im Deutschen: 'Ich schäme mich' (persönlich + reflexiv), im Polnischen: 'Wstyd mi' (unpersönlich + Dativ). Es gibt auch die persönliche Form: 'Wstydzę się tego zachowania' (reflexiv + Genitiv). Die unpersönliche Form ist häufiger und natürlicher."},
            {"id": "gp_emot15", "question": "_____ mi się pić.", "translation": "(Ich habe Durst.)", "options": ["Chce", "Chcę", "Pić", "Mogę"], "correct": "Chce", "explanation": "'Chce mi się pić' = 'Ich habe Durst' – wörtlich: 'es will sich mir trinken'. 'Chce' (3. Person, unpersönlich!) + 'mi' (Dativ) + 'się' + Infinitiv. ACHTUNG: Nicht 'chcę' (1. Person = ich will)! 'chce' (3. Person = es will). Der Unterschied ist nur ein Buchstabe, aber grammatisch fundamental: 'Chcę pić' (Ich will trinken – bewusste Entscheidung) vs. 'Chce mi się pić' (Ich habe Durst – körperliches Bedürfnis). Im Deutschen gibt es diesen Unterschied nicht!"}
        ]
    },
    {
        "key": "directions_location",
        "name": "Kierunki i lokalizacja (Richtungen und Ortsangaben)",
        "description": "Wyrażanie kierunku, położenia i ruchu – różnica między 'gdzie' a 'dokąd'",
        "icon": "location.circle",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_dir1", "question": "Idę _____ sklepu.", "translation": "(Ich gehe zum Geschäft.)", "options": ["do", "w", "na", "z"], "correct": "do", "explanation": "'Do' + Genitiv = Richtung ZU einem Ort (wohin?). 'Do sklepu' = 'zum Geschäft'. Im Deutschen: 'zum/zur' (zu + Dativ), im Polnischen: 'do' + Genitiv. 'Do' ist die universellste Richtungspräposition: 'do domu' (nach Hause), 'do pracy' (zur Arbeit), 'do lekarza' (zum Arzt), 'do Polski' (nach Polen). Merken Sie sich: 'do' = Bewegung HINEIN, 'na' = Bewegung AUF (für einige spezielle Orte)."},
            {"id": "gp_dir2", "question": "Jestem _____ sklepie.", "translation": "(Ich bin im Geschäft.)", "options": ["w", "do", "na", "z"], "correct": "w", "explanation": "'W' + Lokativ = Befindlichkeit IN einem Ort (wo?). 'W sklepie' = 'im Geschäft'. Beachten Sie den Kasuswechsel: 'do sklepu' (Genitiv = wohin?) vs. 'w sklepie' (Lokativ = wo?). Im Deutschen: 'in + Akkusativ' (wohin?) vs. 'in + Dativ' (wo?) – ein ähnliches System! Aber die Präpositionen wechseln im Polnischen: 'do' (wohin) → 'w' (wo) → 'z' (woher). Drei verschiedene Präpositionen für drei Richtungen!"},
            {"id": "gp_dir3", "question": "Wracam _____ sklepu.", "translation": "(Ich komme vom Geschäft zurück.)", "options": ["ze", "do", "w", "na"], "correct": "ze", "explanation": "'Ze' (= z) + Genitiv = Richtung VON einem Ort (woher?). 'Ze sklepu' = 'vom Geschäft'. 'Ze' statt 'z' vor Konsonantenhäufungen (wie 'sk-'). Das Dreiersystem: 'do sklepu' (zum, wohin?) → 'w sklepie' (im, wo?) → 'ze sklepu' (vom, woher?). Im Deutschen: 'zum' → 'im' → 'vom'. Die Präpositionen wechseln in beiden Sprachen, aber die Kasus sind verschieden!"},
            {"id": "gp_dir4", "question": "Idę _____ pocztę.", "translation": "(Ich gehe zur Post.)", "options": ["na", "do", "w", "z"], "correct": "na", "explanation": "'Na' + Akkusativ = Richtung zu bestimmten Orten! Einige Orte verlangen 'na' statt 'do': 'na pocztę' (zur Post), 'na dworzec' (zum Bahnhof), 'na lotnisko' (zum Flughafen), 'na uniwersytet' (zur Universität), 'na rynek' (zum Marktplatz). Es gibt keine klare Regel – man muss diese Orte lernen! Tendenziell: offene/öffentliche Plätze = 'na', geschlossene Gebäude = 'do'. Aber es gibt Ausnahmen!"},
            {"id": "gp_dir5", "question": "Jestem _____ poczcie.", "translation": "(Ich bin auf der Post.)", "options": ["na", "w", "do", "z"], "correct": "na", "explanation": "'Na' + Lokativ = Befindlichkeit bei 'na'-Orten. 'Na poczcie' = 'auf der Post'. Wenn der Richtungsbegriff 'na' + Akkusativ ist (na pocztę), dann ist der Ortsbegriff auch 'na' + Lokativ (na poczcie)! Das System: 'na pocztę' (wohin?, Akk.) → 'na poczcie' (wo?, Lok.) → 'z poczty' (woher?, Gen.). Vergleichen Sie: 'do domu' → 'w domu' → 'z domu'. Zwei parallele Systeme: 'do/w/z' vs. 'na/na/z'."},
            {"id": "gp_dir6", "question": "Skręć w _____.", "translation": "(Biegen Sie rechts ab.)", "options": ["prawo", "prawa", "prawym", "prawą"], "correct": "prawo", "explanation": "'Skręcić w prawo' = 'rechts abbiegen' – 'w' + Akkusativ für Richtungen. 'W prawo' (nach rechts), 'w lewo' (nach links). Im Deutschen: einfach 'rechts/links', im Polnischen: 'w prawo/w lewo' (wörtlich: in das Rechte/Linke). Nützlich für Navigation: 'Proszę skręcić w prawo' (Bitte biegen Sie rechts ab) – höfliche Form mit 'proszę' + Infinitiv. 'Proszę jechać prosto' (Bitte fahren Sie geradeaus)."},
            {"id": "gp_dir7", "question": "Poczta jest _____ banku.", "translation": "(Die Post ist gegenüber der Bank.)", "options": ["naprzeciwko", "obok", "przed", "za"], "correct": "naprzeciwko", "explanation": "'Naprzeciwko' + Genitiv = 'gegenüber' + Dativ/Genitiv. 'Naprzeciwko banku' = 'gegenüber der Bank'. Im Deutschen: 'gegenüber + Dativ', im Polnischen: 'naprzeciwko + Genitiv'. Weitere Lagebeziehungen: 'obok' + Gen. (neben), 'blisko' + Gen. (nahe), 'daleko od' + Gen. (weit von), 'w pobliżu' + Gen. (in der Nähe von). Alle statischen Lageadverbien verlangen den Genitiv!"},
            {"id": "gp_dir8", "question": "Mieszkam _____ parku.", "translation": "(Ich wohne neben dem Park.)", "options": ["obok", "naprzeciwko", "w", "do"], "correct": "obok", "explanation": "'Obok' + Genitiv = 'neben' + Dativ. 'Obok parku' = 'neben dem Park'. Im Deutschen: 'neben + Dativ' (wo?) oder 'neben + Akkusativ' (wohin?). Im Polnischen: 'obok' + Genitiv ist immer gleich – kein Kasuswechsel! Das vereinfacht die Sache. ACHTUNG: 'obok' (neben/daneben) vs. 'koło' (neben, informeller) vs. 'przy' + Lokativ (bei/an). 'Przy parku' betont mehr Nähe, 'obok parku' betont das Nebeneinander."},
            {"id": "gp_dir9", "question": "Szkoła jest _____ kościołem a biblioteką.", "translation": "(Die Schule ist zwischen der Kirche und der Bibliothek.)", "options": ["między", "obok", "przed", "za"], "correct": "między", "explanation": "'Między' + Instrumental = 'zwischen' + Dativ. 'Między kościołem a biblioteką' = 'zwischen der Kirche und der Bibliothek'. 'A' verbindet die beiden Objekte (wie 'und', aber nur nach 'między'). Im Deutschen: 'zwischen + Dativ', im Polnischen: 'między + Instrumental'. Beide Objekte im Instrumental! 'Kościołem' = Instr. von 'kościół', 'biblioteką' = Instr. von 'biblioteka'. 'Między' kann auch 'unter' bedeuten: 'między nami' (unter uns/zwischen uns)."},
            {"id": "gp_dir10", "question": "Samochód stoi _____ domem.", "translation": "(Das Auto steht vor dem Haus.)", "options": ["przed", "za", "nad", "pod"], "correct": "przed", "explanation": "'Przed' + Instrumental = 'vor' + Dativ. 'Przed domem' = 'vor dem Haus'. Im Deutschen: 'vor + Dativ (wo?) / Akkusativ (wohin?)', im Polnischen: 'przed' + Instrumental (immer gleich!). Das Gegenteil: 'za domem' (hinter dem Haus), 'nad domem' (über dem Haus), 'pod domem' (unter dem Haus). Alle Lagebeziehungen mit Instrumental – ein konsistentes System!"},
            {"id": "gp_dir11", "question": "Połóż to _____ stole.", "translation": "(Leg das auf den Tisch.)", "options": ["na", "w", "do", "pod"], "correct": "na", "explanation": "'Na' + Lokativ = 'auf' (wo?), 'na' + Akkusativ = 'auf' (wohin?). 'Na stole' = 'auf dem Tisch' (Lokativ, wo?). ABER: 'Połóż na stole' – hier ist es die Zieloberfläche (wohin?), trotzdem Lokativ! Im gesprochenen Polnisch wird hier oft Lokativ verwendet, obwohl Akkusativ ('na stół') logischer wäre. Im Deutschen: 'auf den Tisch' (Akkusativ/wohin) vs. 'auf dem Tisch' (Dativ/wo). Die polnische Alltagssprache vereinfacht hier."},
            {"id": "gp_dir12", "question": "_____ stąd jest dworzec?", "translation": "(Ist der Bahnhof weit von hier?)", "options": ["Daleko", "Blisko", "Obok", "Gdzie"], "correct": "Daleko", "explanation": "'Daleko stąd' = 'weit von hier'. 'Daleko' = weit, 'stąd' = von hier ('z + tąd'). Im Deutschen: 'weit von hier' – fast identische Struktur! Nützliche Fragen zur Orientierung: 'Jak daleko jest do...?' (Wie weit ist es bis...?), 'Czy to blisko?' (Ist das nah?), 'Ile minut stąd?' (Wie viele Minuten von hier?). 'Daleko' + 'od' + Genitiv: 'daleko od centrum' (weit vom Zentrum)."},
            {"id": "gp_dir13", "question": "Wejdź do _____.", "translation": "(Komm rein. / Tritt ein.)", "options": ["środka", "dom", "wnętrza", "drzwi"], "correct": "środka", "explanation": "'Do środka' = 'hinein / nach innen' – 'do' + Genitiv. 'Środka' = Genitiv von 'środek' (Mitte/Inneres). 'Wejdź' = Imperativ von 'wejść' (hineingehen). Im Deutschen: 'rein/herein/hinein' – ein Adverb, im Polnischen: eine Präpositionalphrase. Gegenteil: 'Wyjdź na zewnątrz' (Go raus). 'Wejść' (hineingehen) vs. 'wyjść' (rausgehen) – die Präfixe 'w-' (hinein) und 'wy-' (heraus) sind systematisch!"},
            {"id": "gp_dir14", "question": "Jedź _____, a potem w lewo.", "translation": "(Fahren Sie geradeaus und dann links.)", "options": ["prosto", "prawo", "lewo", "daleko"], "correct": "prosto", "explanation": "'Prosto' = 'geradeaus' (als Richtungsangabe). ACHTUNG: 'prosto' hat auch andere Bedeutungen: 'einfach' ('To proste!' = 'Das ist einfach!'), 'direkt' ('prosto z lotniska' = 'direkt vom Flughafen'). Für Wegbeschreibungen: 'Jedź prosto' (Fahren Sie geradeaus), 'Idź prosto' (Gehen Sie geradeaus). Im Deutschen: 'geradeaus' (zusammengesetztes Adverb), im Polnischen: ein einfaches Wort 'prosto'."},
            {"id": "gp_dir15", "question": "_____ pochodzisz?", "translation": "(Woher kommst du?)", "options": ["Skąd", "Dokąd", "Gdzie", "Kiedy"], "correct": "Skąd", "explanation": "'Skąd' = 'woher' – Frage nach dem Ursprung/der Herkunft. Das polnische Richtungstriad: 'gdzie?' (wo?), 'dokąd?' (wohin?), 'skąd?' (woher?). Im Deutschen: 'wo?', 'wohin?', 'woher?' – drei separate Fragewörter. Im Polnischen genauso! 'Skąd pochodzisz?' = 'Woher stammst du?' ist eine der häufigsten Kennenlernfragen. Antwort mit 'z' + Genitiv: 'Z Niemiec' (Aus Deutschland), 'Z Berlina' (Aus Berlin)."}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

data.extend(new_categories)

with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_categories)} categories")
print(f"Total categories: {len(data)}")
print(f"Total items: {sum(len(c['items']) for c in data)}")

from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
if dupes:
    print(f"DUPLICATES FOUND: {dupes}")
else:
    print("No duplicate IDs - all clean!")
