#!/usr/bin/env python3
"""Batch 18: cats 92-96 for german_polish grammar."""
import json

GRAMMAR_FILE = 'LumenLingo/LumenLingo/Resources/Content/german_polish/grammar_german_polish.json'

new_categories = [
    {
        "key": "shopping_money",
        "name": "Einkaufen und Geld (Zakupy i pieniądze)",
        "description": "Grammatik und Wortschatz rund um Einkaufen, Preise und Geld",
        "icon": "cart",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_shop1", "question": "Ile _____ ta książka?", "translation": "Wie viel kostet dieses Buch?", "options": ["kosztuje", "kosztować", "kosztują", "kosztował"], "correct": "kosztuje", "explanation": "'Kosztować' (kosten) – 3. Person Singular Präsens: 'kosztuje'. 'Ile kosztuje...?' (Wie viel kostet...?) ist die Standardfrage beim Einkaufen. 'Ta książka' (dieses Buch) – Nominativ feminin als Subjekt. Beachte: 'ile' regiert formal den Genitiv, aber hier ist 'ta książka' das Subjekt des Verbs 'kosztować'.", "difficulty": "beginner"},
            {"id": "gp_shop2", "question": "Chciałbym kupić _____ buty.", "translation": "Ich würde gerne diese Schuhe kaufen.", "options": ["te", "tych", "tymi", "tym"], "correct": "te", "explanation": "'Te buty' (diese Schuhe) – Akkusativ Plural: 'te' als Demonstrativpronomen im Akkusativ Plural (= Nominativ bei unbelebten maskulinen und allen femininen/neutralen Pluralen). 'Kupić' (kaufen, vollendet) + Akkusativ. 'Chciałbym' (ich würde gerne) – Konditional von 'chcieć'. Im Polnischen höflicher als 'chcę' (ich will).", "difficulty": "beginner"},
            {"id": "gp_shop3", "question": "Zapłacę _____ kartą.", "translation": "Ich werde mit Karte bezahlen.", "options": ["za to", "to", "tego", "temu"], "correct": "za to", "explanation": "'Zapłacić za' + Akkusativ (bezahlen für): 'zapłacę za to' (ich werde dafür bezahlen). 'Kartą' – Instrumental: 'karta' → 'kartą' (mit Karte). Die Zahlungsmethode steht im Instrumental ohne Präposition! 'Zapłacę' – Futur vollendet, 1. Pers. Sing. Im Deutschen: 'mit Karte bezahlen' – 'mit' + Dativ, im Polnischen: Instrumental.", "difficulty": "intermediate"},
            {"id": "gp_shop4", "question": "Czy jest jakaś _____ na ten produkt?", "translation": "Gibt es einen Rabatt auf dieses Produkt?", "options": ["zniżka", "zniżki", "zniżką", "zniżkę"], "correct": "zniżka", "explanation": "'Zniżka' (Rabatt) im Nominativ als Subjekt des Existenzsatzes: 'czy jest zniżka?' (gibt es einen Rabatt?). 'Na ten produkt' – 'na' + Akkusativ: 'ten produkt' (dieses Produkt). 'Jakaś' (irgendein/eine) – Indefinitpronomen feminin Nominativ. Die Fragepartikel 'czy' leitet Ja/Nein-Fragen ein (kein Gegenstück im Deutschen, wo Inversion verwendet wird).", "difficulty": "beginner"},
            {"id": "gp_shop5", "question": "Ten sweter jest _____ drogi.", "translation": "Dieser Pullover ist zu teuer.", "options": ["za", "zbyt", "bardzo", "dość"], "correct": "za", "explanation": "'Za drogi' (zu teuer) – 'za' als Adverb der Überschreitung (zu). Im Deutschen: 'zu teuer'. 'Zbyt' ist das formellere Synonym: 'zbyt drogi'. Beachte: 'Za' als Präposition (für/hinter) vs. 'za' als Adverb (zu/allzu) – gleiche Schreibung, verschiedene Funktion! 'Ten sweter' – Demonstrativpronomen + Substantiv im Nominativ.", "difficulty": "beginner"},
            {"id": "gp_shop6", "question": "Poproszę _____ chleba.", "translation": "Ich hätte gerne ein Kilo Brot.", "options": ["kilogram", "kilograma", "kilogramem", "kilogramy"], "correct": "kilogram", "explanation": "'Poproszę' (ich hätte gerne) – höfliche Bestellformel vom Verb 'poprosić'. 'Kilogram chleba' – 'kilogram' im Akkusativ (= Nominativ bei mask. unbelebt), 'chleba' im Genitiv als Maßangabe. Mengenangaben regieren den Genitiv: 'kilogram + Gen.' 'Chleb' → 'chleba' (Gen. mask.). Im Laden: 'Poproszę...' statt 'Ich möchte...'", "difficulty": "beginner"},
            {"id": "gp_shop7", "question": "Mogę _____ przymierzyć?", "translation": "Kann ich das anprobieren?", "options": ["to", "tę", "tego", "temu"], "correct": "to", "explanation": "'Przymierzyć' (anprobieren) + Akkusativ: 'to' (das, Neutrum Akk. = Nom.). 'Mogę' (ich kann) + Infinitiv. 'To' als universelles Demonstrativpronomen in neutraler Form. Im Geschäft: 'Mogę to przymierzyć?' – höfliche Frage ohne 'czy', nur durch Intonation als Frage erkennbar. Im Deutschen: 'Kann ich das anprobieren?'", "difficulty": "beginner"},
            {"id": "gp_shop8", "question": "Szukam _____ na prezent.", "translation": "Ich suche etwas als Geschenk.", "options": ["czegoś", "coś", "czymś", "czemuś"], "correct": "czegoś", "explanation": "'Szukać' (suchen) regiert den Genitiv: 'szukam czegoś' (ich suche etwas). 'Coś' (etwas) → 'czegoś' (Gen.). Im Deutschen: 'suchen' + Akkusativ; im Polnischen: 'szukać' + Genitiv – unterschiedliche Rektion! 'Na prezent' (als Geschenk/für ein Geschenk) – 'na' + Akkusativ in der Bedeutung 'zu/für den Zweck'.", "difficulty": "intermediate"},
            {"id": "gp_shop9", "question": "Ten sklep jest otwarty _____ dziewiątej do dwudziestej.", "translation": "Dieses Geschäft ist von neun bis zwanzig Uhr geöffnet.", "options": ["od", "z", "od godziny", "w"], "correct": "od", "explanation": "'Od dziewiątej do dwudziestej' (von neun bis zwanzig) – 'od' + Genitiv ... 'do' + Genitiv für Zeitspannen. 'Dziewiąta' → 'dziewiątej' (Gen. fem.), 'dwudziesta' → 'dwudziestej' (Gen. fem.) – Ordinalzahlen als Uhrzeiten im Genitiv feminin (wegen 'godzina'). Im Polnischen oft ohne 'godziny': 'od dziewiątej'.", "difficulty": "intermediate"},
            {"id": "gp_shop10", "question": "Czy mogę _____ paragon?", "translation": "Kann ich einen Kassenbon bekommen?", "options": ["dostać", "dostawać", "dostaję", "dostałem"], "correct": "dostać", "explanation": "'Dostać' (bekommen, vollendet) – nach 'mogę' steht der vollendete Infinitiv für eine einmalige konkrete Bitte. 'Paragon' (Kassenbon) im Akkusativ (= Nominativ, maskulin unbelebt). 'Czy mogę dostać...?' ist die höfliche Standardfrage. Vergleiche: 'dostawać' (unvollendet) für wiederholtes Bekommen.", "difficulty": "beginner"},
            {"id": "gp_shop11", "question": "To kosztuje pięćdziesiąt _____ złotych.", "translation": "Das kostet fünfzig Zloty.", "options": ["pięć", "pięciu", "pięcioma", "piątka"], "correct": "pięć", "explanation": "'Pięćdziesiąt pięć złotych' (fünfundfünfzig Zloty) – Zahlwörter ab 5 regieren den Genitiv Plural: 'złoty' → 'złotych'. Die Zahl 'pięćdziesiąt pięć' (55) ist ein zusammengesetztes Zahlwort. 'Złoty' (der Zloty) → 'złotych' (Gen. Pl.). Beachte: 2-4: 'złote' (Nom. Pl.), ab 5: 'złotych' (Gen. Pl.).", "difficulty": "intermediate"},
            {"id": "gp_shop12", "question": "Chcę wymienić ten towar, bo jest _____.", "translation": "Ich möchte diese Ware umtauschen, weil sie defekt ist.", "options": ["wadliwy", "wadliwa", "wadliwe", "wadliwą"], "correct": "wadliwy", "explanation": "'Wadliwy' (defekt/fehlerhaft) – Nominativ maskulin Singular als Prädikatsadjektiv: 'jest wadliwy'. 'Towar' (Ware) ist maskulin, daher maskuline Endung. 'Wymienić' (umtauschen, vollendet) + Akkusativ: 'ten towar'. 'Bo' (weil, umgangssprachlich) = 'dlatego że' / 'ponieważ' (formell). Wie dt. 'weil' leitet es einen Kausalsatz ein.", "difficulty": "intermediate"},
            {"id": "gp_shop13", "question": "Nie stać _____ na taki luksus.", "translation": "Ich kann mir solchen Luxus nicht leisten.", "options": ["mnie", "ja", "mi", "mną"], "correct": "mnie", "explanation": "'Nie stać mnie na' (ich kann mir nicht leisten) – unpersönliche Konstruktion: 'stać' + Akkusativ der Person + 'na' + Akkusativ. 'Mnie' ist die volle Akkusativform (betont). Im Deutschen: 'sich etwas leisten können' – persönliche Konstruktion; im Polnischen: unpersönlich mit 'stać'. 'Taki luksus' – Demonstrativpronomen + Substantiv.", "difficulty": "advanced"},
            {"id": "gp_shop14", "question": "Proszę o _____ w mniejszym rozmiarze.", "translation": "Ich bitte um diese Bluse in einer kleineren Größe.", "options": ["tę bluzkę", "ta bluzka", "tej bluzki", "tą bluzką"], "correct": "tę bluzkę", "explanation": "'Prosić o' + Akkusativ (bitten um): 'proszę o tę bluzkę' (bitte um diese Bluse). 'Ta bluzka' → 'tę bluzkę' (Akk. fem. Sing.). 'W mniejszym rozmiarze' – 'w' + Lokativ: 'mniejszy rozmiar' → 'mniejszym rozmiarze'. 'Mniejszy' (kleiner) – Komparativ von 'mały' (klein) im Lokativ. Beachte: 'Proszę o' – höfliche Bittform.", "difficulty": "intermediate"},
            {"id": "gp_shop15", "question": "Gdzie jest najbliższy _____ spożywczy?", "translation": "Wo ist der nächste Lebensmittelladen?", "options": ["sklep", "sklepu", "sklepie", "sklepem"], "correct": "sklep", "explanation": "'Sklep' (Geschäft/Laden) im Nominativ als Subjekt: 'gdzie jest najbliższy sklep?' 'Najbliższy' (nächster) – Superlativ von 'bliski' (nah): 'bliski' → 'bliższy' → 'najbliższy'. 'Spożywczy' (Lebensmittel-) – Adjektiv von 'spożywka/spożycie'. Die Frage 'gdzie jest...?' entspricht dem deutschen 'wo ist...?' – identische Struktur.", "difficulty": "beginner"}
        ]
    },
    {
        "key": "housing_home",
        "name": "Wohnen und Zuhause (Mieszkanie i dom)",
        "description": "Grammatik und Wortschatz rund um Wohnung, Haushalt und Wohnen",
        "icon": "house",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_hous1", "question": "Mieszkam w _____ na trzecim piętrze.", "translation": "Ich wohne in einer Wohnung im dritten Stock.", "options": ["mieszkaniu", "mieszkanie", "mieszkania", "mieszkaniem"], "correct": "mieszkaniu", "explanation": "'W mieszkaniu' (in einer Wohnung) – 'w' + Lokativ: 'mieszkanie' → 'mieszkaniu'. 'Na trzecim piętrze' – 'na' + Lokativ für Stockwerke: 'trzecie piętro' → 'trzecim piętrze'. Beachte: In Polen wird anders gezählt – 'trzecie piętro' entspricht dem dritten Stockwerk (über dem Erdgeschoss 'parter').", "difficulty": "beginner"},
            {"id": "gp_hous2", "question": "Szukamy _____ do wynajęcia.", "translation": "Wir suchen eine Wohnung zur Miete.", "options": ["mieszkania", "mieszkanie", "mieszkaniu", "mieszkaniem"], "correct": "mieszkania", "explanation": "'Szukać' (suchen) + Genitiv: 'szukamy mieszkania' (wir suchen eine Wohnung). Im Deutschen: 'suchen' + Akkusativ; im Polnischen: 'szukać' + Genitiv! 'Do wynajęcia' (zur Miete/zu vermieten) – 'do' + Genitiv: 'wynajęcie' → 'wynajęcia'. Vergleiche: 'do kupienia' (zu kaufen), 'do sprzedania' (zu verkaufen).", "difficulty": "intermediate"},
            {"id": "gp_hous3", "question": "W _____ pokoju stoi duże biurko.", "translation": "In meinem Zimmer steht ein großer Schreibtisch.", "options": ["moim", "mój", "mojego", "mojemu"], "correct": "moim", "explanation": "'W moim pokoju' – 'w' + Lokativ: 'mój pokój' → 'moim pokoju'. 'Mój' → 'moim' (Lok. mask. Sing.). 'Stoi' (steht) – 3. Pers. Sing. von 'stać' (stehen). 'Duże biurko' (großer Schreibtisch) – Nominativ Neutrum als Subjekt: 'duże' = Nom. Neutr. Im Deutschen: auch 'in meinem Zimmer' – Lokativ ≈ Dativ.", "difficulty": "beginner"},
            {"id": "gp_hous4", "question": "Muszę _____ rachunki za prąd.", "translation": "Ich muss die Stromrechnungen bezahlen.", "options": ["zapłacić", "płacić", "płacę", "zapłacę"], "correct": "zapłacić", "explanation": "'Musieć' (müssen) + Infinitiv: 'muszę zapłacić'. 'Zapłacić' (bezahlen, vollendet) für eine konkrete, einmalige Handlung. 'Rachunki za prąd' (Stromrechnungen) – 'za' + Akkusativ: 'za prąd' (für Strom). 'Rachunki' im Akkusativ (= Nominativ bei maskulin unbelebt Plural: '-i'). Vergleiche: 'płacić' (regelmäßig bezahlen).", "difficulty": "beginner"},
            {"id": "gp_hous5", "question": "Kuchnia jest _____ salonem.", "translation": "Die Küche ist neben dem Wohnzimmer.", "options": ["obok salonu", "obok salon", "przy salonie", "koło salon"], "correct": "obok salonu", "explanation": "'Obok' (neben) + Genitiv: 'obok salonu'. 'Salon' → 'salonu' (Gen. mask.). Beachte: 'obok' (neben) ≠ 'przy' (bei/an). 'Obok' betont die räumliche Nachbarschaft, 'przy' eher die Nähe/Anlehnung. 'Kuchnia' (Küche, feminin) als Subjekt im Nominativ. Andere Raumpräpositionen: 'naprzeciwko' (gegenüber) + Gen.", "difficulty": "intermediate"},
            {"id": "gp_hous6", "question": "Wprowadziliśmy się do _____ domu miesiąc temu.", "translation": "Wir sind vor einem Monat in das neue Haus eingezogen.", "options": ["nowego", "nowy", "nowym", "nowe"], "correct": "nowego", "explanation": "'Do nowego domu' (in das neue Haus) – 'do' + Genitiv: 'nowy dom' → 'nowego domu'. 'Wprowadzić się' (einziehen) + 'do' + Genitiv. 'Wprowadziliśmy się' – Vergangenheit mask.-personal Plural: '-liśmy' = wir. 'Miesiąc temu' (vor einem Monat) – 'temu' (ago) steht nach der Zeitangabe. Im Deutschen: 'vor einem Monat'.", "difficulty": "intermediate"},
            {"id": "gp_hous7", "question": "Trzeba _____ ścian w sypialni.", "translation": "Man muss die Wände im Schlafzimmer streichen.", "options": ["pomalować", "malować", "pomaluje", "pomalował"], "correct": "pomalować", "explanation": "'Trzeba' (man muss) + Infinitiv: 'trzeba pomalować'. 'Pomalować' (streichen, vollendet) – konkreter Auftrag. 'Ścian' – Genitiv Plural: 'ściana' → 'ścian' (Gen. Pl. fem. auf '-a' → Nullendung im Gen. Pl.). 'W sypialni' – 'w' + Lokativ: 'sypialnia' → 'sypialni'. Nach 'trzeba' kann Genitiv des Objekts stehen (statt Akkusativ).", "difficulty": "intermediate"},
            {"id": "gp_hous8", "question": "Ogrzewanie _____ bardzo dużo.", "translation": "Die Heizung kostet sehr viel.", "options": ["kosztuje", "kosztują", "kosztować", "kosztowało"], "correct": "kosztuje", "explanation": "'Ogrzewanie' (Heizung, Neutrum) – Verbalsubstantiv von 'ogrzewać' (heizen). 'Kosztuje' – 3. Pers. Sing. von 'kosztować'. 'Bardzo dużo' (sehr viel) – Steigerung des Adverbs 'dużo'. Im Polnischen: 'ogrzewanie kosztuje dużo' (unpersönlich). Im Deutschen: 'Die Heizung kostet viel' – gleiche unpersönliche Struktur.", "difficulty": "beginner"},
            {"id": "gp_hous9", "question": "Wczoraj przeprowadziłem się do _____ mieszkania.", "translation": "Gestern bin ich in eine andere Wohnung umgezogen.", "options": ["innego", "inne", "innym", "innej"], "correct": "innego", "explanation": "'Do innego mieszkania' (in eine andere Wohnung) – 'do' + Genitiv: 'inne mieszkanie' → 'innego mieszkania'. 'Inne' → 'innego' (Gen. Neutr. Sing.). 'Przeprowadzić się' (umziehen) – reflexives Verb, vollendeter Aspekt. 'Przeprowadziłem się' – mask. Vergangenheit, 1. Pers. Sing. Beachte: '-łem' = maskulin, '-łam' = feminin.", "difficulty": "intermediate"},
            {"id": "gp_hous10", "question": "Na balkonie postawiłam _____ z kwiatami.", "translation": "Auf dem Balkon habe ich Töpfe mit Blumen aufgestellt.", "options": ["doniczki", "doniczek", "doniczkami", "doniczkach"], "correct": "doniczki", "explanation": "'Postawić' (aufstellen, vollendet) + Akkusativ: 'doniczki' (Töpfe). 'Doniczka' → 'doniczki' (Akk. Pl. fem.). 'Z kwiatami' (mit Blumen) – 'z' + Instrumental Plural: 'kwiat' → 'kwiatami'. 'Na balkonie' – 'na' + Lokativ: 'balkon' → 'balkonie'. 'Postawiłam' – feminin Vergangenheit (die Sprecherin ist weiblich: '-łam').", "difficulty": "intermediate"},
            {"id": "gp_hous11", "question": "Czy masz _____ pokój dla gości?", "translation": "Hast du ein Gästezimmer?", "options": ["wolny", "wolnego", "wolnym", "wolną"], "correct": "wolny", "explanation": "'Wolny pokój' (freies/verfügbares Zimmer) – Akkusativ mask. unbelebt = Nominativ: 'wolny'. 'Mieć' (haben) + Akkusativ. 'Dla gości' (für Gäste) – 'dla' + Genitiv Plural: 'gość' → 'gości'. 'Pokój dla gości' (Gästezimmer) – im Polnischen beschreibende Phrase statt Kompositum wie im Deutschen.", "difficulty": "beginner"},
            {"id": "gp_hous12", "question": "W łazience jest _____ i prysznic.", "translation": "Im Badezimmer gibt es eine Badewanne und eine Dusche.", "options": ["wanna", "wannę", "wanny", "wanną"], "correct": "wanna", "explanation": "'Wanna' (Badewanne) im Nominativ als Subjekt des Existenzsatzes: 'jest wanna i prysznic'. 'W łazience' – 'w' + Lokativ: 'łazienka' → 'łazience'. Beachte die Konsonantenalternation: -k- → -c- im Lokativ (typisch für Feminina auf '-ka'). 'Prysznic' (Dusche, maskulin) ebenfalls im Nominativ.", "difficulty": "beginner"},
            {"id": "gp_hous13", "question": "Czynsz za mieszkanie wynosi dwa _____ złotych.", "translation": "Die Miete für die Wohnung beträgt zweitausend Zloty.", "options": ["tysiące", "tysięcy", "tysiąc", "tysiącem"], "correct": "tysiące", "explanation": "'Dwa tysiące złotych' (zweitausend Zloty) – 'dwa' + Nominativ Plural: 'tysiąc' → 'tysiące'. Zahlwort-Deklination: 1 tysiąc, 2-4 tysiące, 5+ tysięcy. 'Złotych' im Genitiv Plural nach 'tysiące'. 'Wynosić' (betragen) – 3. Pers. Sing.: 'wynosi'. 'Czynsz za' + Akkusativ (Miete für): 'za mieszkanie'.", "difficulty": "intermediate"},
            {"id": "gp_hous14", "question": "Potrzebuję _____ do naprawy kranu.", "translation": "Ich brauche einen Klempner für die Reparatur des Wasserhahns.", "options": ["hydraulika", "hydraulik", "hydraulikiem", "hydrauliku"], "correct": "hydraulika", "explanation": "'Potrzebować' (brauchen) + Genitiv: 'potrzebuję hydraulika'. 'Hydraulik' (Klempner) → 'hydraulika' (Gen. mask. belebt). Bei belebten maskulinen Substantiven: Genitiv = Akkusativ, beide enden auf '-a'. 'Do naprawy' (zur Reparatur) – 'do' + Gen.: 'naprawa' → 'naprawy'. 'Kranu' – Gen.: 'kran' → 'kranu'.", "difficulty": "intermediate"},
            {"id": "gp_hous15", "question": "Sąsiedzi _____ się na hałas.", "translation": "Die Nachbarn beschweren sich über den Lärm.", "options": ["skarżą", "skarży", "skarżyć", "skarżyli"], "correct": "skarżą", "explanation": "'Skarżyć się na' + Akkusativ (sich beschweren über): 'skarżą się na hałas'. 'Skarżyć się' – reflexives Verb, 3. Pers. Plural: 'skarżą się'. 'Sąsiedzi' (Nachbarn) – mask.-personal Plural: 'sąsiad' → 'sąsiedzi' (Konsonantenalternation d → dzi). 'Hałas' (Lärm) im Akkusativ = Nominativ (maskulin unbelebt).", "difficulty": "intermediate"}
        ]
    },
    {
        "key": "family_relationships",
        "name": "Familie und Beziehungen (Rodzina i relacje)",
        "description": "Grammatik rund um Familienmitglieder, Beziehungen und soziale Bindungen",
        "icon": "person.3",
        "difficulty": "beginner",
        "items": [
            {"id": "gp_fam1", "question": "Mam dwoje _____.", "translation": "Ich habe zwei Kinder.", "options": ["dzieci", "dziecko", "dzieciom", "dziećmi"], "correct": "dzieci", "explanation": "'Dwoje dzieci' (zwei Kinder) – 'dwoje' als Sammelzahlwort für gemischte Geschlechter + Genitiv Plural: 'dziecko' → 'dzieci'. Sammelzahlwörter (dwoje, troje, czworo) werden für Kinder und gemischtgeschlechtliche Gruppen verwendet – einzigartig im Polnischen, kein Gegenstück im Deutschen!", "difficulty": "beginner"},
            {"id": "gp_fam2", "question": "Moja _____ jest lekarzem.", "translation": "Meine Mutter ist Ärztin.", "options": ["mama", "mamę", "mamy", "mamą"], "correct": "mama", "explanation": "'Mama' im Nominativ als Subjekt: 'moja mama jest lekarzem'. Beachte: 'Jest lekarzem' – nach 'być' steht der Beruf im Instrumental! 'Lekarz' → 'lekarzem' (Instr. mask.). Obwohl die Mutter weiblich ist, kann man 'lekarzem' (mask.) oder 'lekarką' (fem.) verwenden. Ersteres ist formeller und traditioneller.", "difficulty": "beginner"},
            {"id": "gp_fam3", "question": "Jestem _____ na swojego brata.", "translation": "Ich bin auf meinen Bruder stolz.", "options": ["dumny", "dumna", "dumne", "dumnego"], "correct": "dumny", "explanation": "'Dumny z' + Genitiv (stolz auf): 'dumny z brata'. Aber hier steht 'na' + Akkusativ – eine alternative Rektion für 'dumny' in manchen Kontexten. 'Swojego brata' – Akkusativ/Genitiv belebt: 'swój brat' → 'swojego brata'. 'Swój' (sein eigener) – reflexives Possessivpronomen, bezieht sich auf das Subjekt. 'Dumny' – mask. Nom. Prädikatsadjektiv.", "difficulty": "intermediate"},
            {"id": "gp_fam4", "question": "Moi rodzice _____ się trzydzieści lat temu.", "translation": "Meine Eltern haben vor dreißig Jahren geheiratet.", "options": ["pobrali", "pobrały", "pobrał", "pobrała"], "correct": "pobrali", "explanation": "'Pobrać się' (heiraten) – Vergangenheitsform maskulin-personal Plural: 'pobrali się'. 'Rodzice' (Eltern) ist maskulin-personal Plural (enthält 'ojciec'), daher die Endung '-li'. Vergleiche: '-ły' wäre für nicht-personale oder nur-feminine Gruppen. 'Trzydzieści lat temu' – 'temu' (ago); 'lat' = Gen. Pl. von 'rok' (Jahr).", "difficulty": "intermediate"},
            {"id": "gp_fam5", "question": "Zaprosiłem całą _____ na obiad.", "translation": "Ich habe die ganze Familie zum Mittagessen eingeladen.", "options": ["rodzinę", "rodzina", "rodziny", "rodziną"], "correct": "rodzinę", "explanation": "'Zaprosić' (einladen) + Akkusativ: 'całą rodzinę'. 'Cała rodzina' → 'całą rodzinę' (Akk. fem. Sing.). 'Na obiad' – 'na' + Akkusativ (zu/für): 'obiad' (Mittagessen). 'Zaprosiłem' – mask. Vergangenheit, 1. Pers. In Polen ist 'obiad' die Hauptmahlzeit, traditionell mittags/nachmittags – nicht 'Abendessen'!", "difficulty": "beginner"},
            {"id": "gp_fam6", "question": "Mój _____ brat jest starszy ode mnie.", "translation": "Mein älterer Bruder ist älter als ich.", "options": ["starszy", "starszego", "starszym", "starsza"], "correct": "starszy", "explanation": "'Starszy brat' (älterer Bruder) – 'starszy' im Nominativ als Attribut: Adjektiv vor dem Substantiv. 'Starszy ode mnie' (älter als ich) – 'ode mnie' = verstärkte Form von 'od mnie' (phonetischer Vokal vor 'mn'). 'Od' + Genitiv für den Vergleich: 'od mnie'. Im Deutschen: 'als ich' – anders konstruiert.", "difficulty": "beginner"},
            {"id": "gp_fam7", "question": "Babcia opowiada _____ bajki.", "translation": "Oma erzählt den Enkeln Märchen.", "options": ["wnukom", "wnuki", "wnuków", "wnukami"], "correct": "wnukom", "explanation": "'Opowiadać' + Dativ (Person) + Akkusativ (Sache): 'opowiada wnukom bajki'. 'Wnuk' → 'wnukom' (Dat. Pl.). 'Bajki' (Märchen) im Akkusativ Plural. Im Deutschen: 'erzählen + Dativ + Akkusativ' – identische Kasusstruktur! 'Babcia' (Oma) – liebevoll, 'babka' wäre pejorativ. Die Höflichkeitsebene der Familienbezeichnungen ist wichtig.", "difficulty": "intermediate"},
            {"id": "gp_fam8", "question": "Wychowuję _____ sama.", "translation": "Ich erziehe die Kinder allein.", "options": ["dzieci", "dziecko", "dzieciom", "dziećmi"], "correct": "dzieci", "explanation": "'Wychowywać' (erziehen) + Akkusativ: 'dzieci' (Kinder, Akk. = Nom. Pl.). 'Sama' (allein, feminin) zeigt, dass die Sprecherin weiblich ist. 'Sam/sama/samo' (allein) richtet sich nach dem Geschlecht des Subjekts. 'Wychowywać' (unvollendet) drückt eine fortlaufende Tätigkeit aus – Erziehung als dauerhafter Prozess.", "difficulty": "beginner"},
            {"id": "gp_fam9", "question": "Moja siostra jest _____ do mamy.", "translation": "Meine Schwester ist der Mama ähnlich.", "options": ["podobna", "podobny", "podobne", "podobną"], "correct": "podobna", "explanation": "'Podobna do' + Genitiv (ähnlich): 'podobna do mamy'. 'Podobny/a/e' (ähnlich) richtet sich nach dem Subjekt: 'siostra' ist feminin → 'podobna'. 'Do mamy' – 'do' + Genitiv: 'mama' → 'mamy'. Im Deutschen: 'ähnlich' + Dativ (der Mama ähnlich). Im Polnischen: 'podobny do' + Genitiv – verschiedene Rektion!", "difficulty": "intermediate"},
            {"id": "gp_fam10", "question": "Dziadek _____ nam o wojnie.", "translation": "Opa erzählt uns vom Krieg.", "options": ["opowiada", "opowiadać", "opowiedzieć", "opowiedział"], "correct": "opowiada", "explanation": "'Opowiadać o' + Lokativ (erzählen von/über): 'opowiada o wojnie'. 'O wojnie' – 'o' + Lokativ: 'wojna' → 'wojnie'. 'Nam' (uns) im Dativ. 'Opowiadać' (unvollendet) – regelmäßige, gewohnheitsmäßige Erzählung. 'Dziadek' (Opa) – die liebevolle Form; auch 'dziadziu' als Anrede. 3. Pers. Sing. Präsens: 'opowiada'.", "difficulty": "beginner"},
            {"id": "gp_fam11", "question": "Urodziłam się _____ lipca.", "translation": "Ich bin am zehnten Juli geboren.", "options": ["dziesiątego", "dziesiąty", "dziesiątym", "dziesiątą"], "correct": "dziesiątego", "explanation": "'Dziesiątego lipca' (am zehnten Juli) – Datumsangaben stehen im Genitiv: 'dziesiąty' → 'dziesiątego' (Gen. mask.), 'lipiec' → 'lipca' (Gen., Juli). 'Urodziłam się' (ich bin geboren, fem.) – reflexives Verb 'urodzić się'. Die '-łam'-Endung zeigt feminines Geschlecht. Im Deutschen: 'am zehnten' mit Dativ, im Polnischen: Genitiv.", "difficulty": "intermediate"},
            {"id": "gp_fam12", "question": "Kocham swoją _____ nad życie.", "translation": "Ich liebe meine Frau über alles.", "options": ["żonę", "żona", "żony", "żoną"], "correct": "żonę", "explanation": "'Kochać' (lieben) + Akkusativ: 'swoją żonę'. 'Żona' → 'żonę' (Akk. fem.). 'Swoją' – Akkusativ fem. des reflexiven Possessivs 'swój' (mein eigenes). 'Nad życie' (über das Leben/über alles) – 'nad' + Akkusativ in phraseologischer Wendung. Beachte: 'swój' bezieht sich immer auf das Subjekt und vermeidet Ambiguität.", "difficulty": "beginner"},
            {"id": "gp_fam13", "question": "Moje rodzeństwo jest _____ ode mnie.", "translation": "Meine Geschwister sind jünger als ich.", "options": ["młodsze", "młodsi", "młodsza", "młodszy"], "correct": "młodsze", "explanation": "'Młodsze' (jünger) – Nominativ Neutrum Singular/Plural. 'Rodzeństwo' (Geschwister) ist grammatisch Neutrum Singular (Kollektivum!), obwohl es mehrere Personen bezeichnet. Daher: 'rodzeństwo jest młodsze' (nicht 'są młodsi'!). Dies ist eine Besonderheit des Polnischen – Kollektiva werden grammatisch als Singular behandelt.", "difficulty": "intermediate"},
            {"id": "gp_fam14", "question": "Tata zawsze _____ nam w lekcjach.", "translation": "Papa hilft uns immer bei den Hausaufgaben.", "options": ["pomaga", "pomóc", "pomoże", "pomagał"], "correct": "pomaga", "explanation": "'Pomagać' (helfen) + Dativ + 'w' + Lokativ: 'pomaga nam w lekcjach'. 'Nam' (uns, Dativ). 'W lekcjach' (bei den Aufgaben) – 'lekcja' → 'lekcjach' (Lok. Pl.). 'Pomagać' (unvollendet) für gewohnheitsmäßiges Helfen. 'Zawsze' (immer) als Frequenzadverb. Im Deutschen: 'helfen bei + Dativ' – ähnliche Konstruktion.", "difficulty": "beginner"},
            {"id": "gp_fam15", "question": "Na weselu _____ cała rodzina.", "translation": "Auf der Hochzeit war die ganze Familie.", "options": ["była", "byli", "było", "były"], "correct": "była", "explanation": "'Rodzina była' (die Familie war) – 'rodzina' ist feminin Singular, daher 'była' (fem. Sing. Verg.). Obwohl die Familie aus vielen Personen besteht, bleibt es grammatisch Singular. 'Na weselu' (auf der Hochzeit) – 'na' + Lokativ: 'wesele' → 'weselu'. 'Cała' (ganze, fem. Nom.) bezieht sich auf 'rodzina'. Vergleiche: 'wszyscy byli' (alle waren) = Plural.", "difficulty": "beginner"}
        ]
    },
    {
        "key": "media_communication",
        "name": "Medien und Kommunikation (Media i komunikacja)",
        "description": "Grammatik und Wortschatz rund um Medien, Internet und Kommunikation",
        "icon": "antenna.radiowaves.left.and.right",
        "difficulty": "intermediate",
        "items": [
            {"id": "gp_med1", "question": "Codziennie czytam _____ w internecie.", "translation": "Ich lese jeden Tag Nachrichten im Internet.", "options": ["wiadomości", "wiadomość", "wiadomościom", "wiadomościami"], "correct": "wiadomości", "explanation": "'Wiadomości' (Nachrichten) im Akkusativ Plural (= Nominativ Plural). 'Czytać' (lesen) + Akkusativ: 'czytam wiadomości'. 'W internecie' – 'w' + Lokativ: 'internet' → 'internecie'. 'Codziennie' (täglich) – Adverb am Satzanfang. 'Wiadomość' (einzelne Nachricht, fem.) → 'wiadomości' (Plural) – ein Standardwort der Mediensprache.", "difficulty": "beginner"},
            {"id": "gp_med2", "question": "Oglądamy _____ wieczorne.", "translation": "Wir sehen die Abendnachrichten.", "options": ["wiadomości", "wiadomość", "wiadomościach", "wiadomościom"], "correct": "wiadomości", "explanation": "'Oglądać' (ansehen/schauen) + Akkusativ: 'oglądamy wiadomości wieczorne'. 'Wieczorne' (abendliche) – Adjektiv im Akkusativ Plural: 'wieczorny' → 'wieczorne'. 'Wiadomości wieczorne' (Abendnachrichten) – im Polnischen: Adjektiv nach dem Substantiv als natürlichere Reihenfolge. Im Deutschen: zusammengesetztes Wort.", "difficulty": "beginner"},
            {"id": "gp_med3", "question": "Dostałem wiadomość _____ nieznanego nadawcy.", "translation": "Ich habe eine Nachricht von einem unbekannten Absender erhalten.", "options": ["od", "z", "przez", "u"], "correct": "od", "explanation": "'Od' + Genitiv (von, Absender): 'od nieznanego nadawcy'. 'Nieznany nadawca' → 'nieznanego nadawcy' (Gen. mask. belebt). 'Od' wird für Personen/Absender verwendet (von jemandem). Vergleiche: 'z' (aus/von einem Ort). 'Dostałem' – mask. Vergangenheit von 'dostać' (erhalten). 'Wiadomość' (Nachricht, fem.) im Akkusativ = Nominativ (fem. auf Konsonant).", "difficulty": "intermediate"},
            {"id": "gp_med4", "question": "Ten artykuł został _____ przez dziennikarza.", "translation": "Dieser Artikel wurde von einem Journalisten geschrieben.", "options": ["napisany", "napisana", "napisane", "napisanych"], "correct": "napisany", "explanation": "'Napisany' (geschrieben, mask.) – Partizip Passiv im Nominativ, kongruiert mit 'artykuł' (maskulin). Passivkonstruktion: 'został napisany' (wurde geschrieben, Vorgangspassiv). 'Przez dziennikarza' (von einem Journalisten) – 'przez' + Akkusativ für den Agens im Passiv (mask. belebt: 'dziennikarz' → 'dziennikarza'). Im Deutschen: 'von' + Dativ.", "difficulty": "intermediate"},
            {"id": "gp_med5", "question": "Czy słyszałeś _____ nowym filmie?", "translation": "Hast du von dem neuen Film gehört?", "options": ["o", "na", "z", "w"], "correct": "o", "explanation": "'Słyszeć o' + Lokativ (hören von/über): 'o nowym filmie'. 'Nowy film' → 'nowym filmie' (Lok. mask.). Im Deutschen: 'hören von' + Dativ. Die Rektionen sind parallel! 'Słyszałeś' – 2. Pers. Sing. mask. Vergangenheit: '-łeś'. Beachte: 'Czy' leitet die Ja/Nein-Frage ein – im Deutschen wird das durch Verbstellung (Inversion) gelöst.", "difficulty": "beginner"},
            {"id": "gp_med6", "question": "Zadzwonię do _____ wieczorem.", "translation": "Ich werde dich abends anrufen.", "options": ["ciebie", "tobie", "tobą", "ty"], "correct": "ciebie", "explanation": "'Zadzwonić do' + Genitiv (anrufen): 'zadzwonię do ciebie'. 'Ty' → 'ciebie' (Gen./Akk. volle Form). Im Deutschen: 'jemanden anrufen' + Akkusativ; im Polnischen: 'zadzwonić do' + Genitiv – verschiedene Konstruktionen! 'Wieczorem' (abends) – Instrumental ohne Präposition als Zeitangabe. 'Zadzwonię' – Futur vollendet, 1. Pers.", "difficulty": "intermediate"},
            {"id": "gp_med7", "question": "Na tym kanale _____ ciekawe programy.", "translation": "Auf diesem Kanal laufen interessante Programme.", "options": ["lecą", "leci", "leciał", "lata"], "correct": "lecą", "explanation": "'Lecieć' (laufen/laufen im TV, wörtl.: fliegen) – umgangssprachlich für Sendungen: 'lecą programy' (Programme laufen). 3. Pers. Plural: 'lecą'. 'Na tym kanale' – 'na' + Lokativ: 'ten kanał' → 'tym kanale'. 'Ciekawe programy' (interessante Programme) im Nominativ Plural als Subjekt. Die Verwendung von 'lecieć' für TV ist typisch polnischer Slang.", "difficulty": "intermediate"},
            {"id": "gp_med8", "question": "Napisz do _____ maila.", "translation": "Schreib mir eine E-Mail.", "options": ["mnie", "ja", "mi", "mną"], "correct": "mnie", "explanation": "'Napisz do mnie' (schreib mir) – Imperativ 2. Pers. Sing. von 'napisać'. 'Do mnie' (an mich) – 'do' + Genitiv: 'ja' → 'mnie'. Beachte: 'do mnie maila' (Akkusativ: 'mail/e-mail' → 'maila', mask. belebt behandelt!). In Polen wird 'mail' oft als belebt maskulin dekliniert: 'maila' (Akk.), obwohl es kein Lebewesen ist – Lehnwortadaption.", "difficulty": "beginner"},
            {"id": "gp_med9", "question": "Ten podcast jest bardzo _____ wśród młodzieży.", "translation": "Dieser Podcast ist sehr beliebt unter Jugendlichen.", "options": ["popularny", "popularna", "popularne", "popularnych"], "correct": "popularny", "explanation": "'Popularny' (beliebt/populär) – Nominativ maskulin als Prädikatsadjektiv, kongruiert mit 'podcast' (maskulin). 'Wśród' (unter/inmitten) + Genitiv: 'wśród młodzieży'. 'Młodzież' (Jugend, feminin Kollektivum) → 'młodzieży' (Gen. fem.). 'Bardzo' (sehr) als Intensivierer. Im Deutschen: 'beliebt bei' + Dativ.", "difficulty": "beginner"},
            {"id": "gp_med10", "question": "Wyłącz telefon, bo _____ do kina.", "translation": "Schalte das Telefon aus, weil wir ins Kino gehen.", "options": ["idziemy", "iść", "pójdziemy", "idą"], "correct": "idziemy", "explanation": "'Idziemy' (wir gehen) – 1. Pers. Plural Präsens von 'iść' (gehen, einmalig). 'Wyłącz' – Imperativ 2. Pers. Sing. von 'wyłączyć' (ausschalten). 'Bo' (weil, umgangssprachlich) – kausale Konjunktion. 'Do kina' – 'do' + Genitiv: 'kino' → 'kina' (ins Kino). Beachte: 'iść do kina' (jetzt/gleich), 'chodzić do kina' (regelmäßig).", "difficulty": "beginner"},
            {"id": "gp_med11", "question": "Informacja została _____ przez media.", "translation": "Die Information wurde von den Medien verbreitet.", "options": ["rozpowszechniona", "rozpowszechniony", "rozpowszechnione", "rozpowszechnionych"], "correct": "rozpowszechniona", "explanation": "'Rozpowszechniona' (verbreitet, fem.) – Partizip Passiv im Nominativ feminin, kongruiert mit 'informacja' (feminin). 'Zostać' + Partizip = Vorgangspassiv: 'została rozpowszechniona'. 'Przez media' (durch die Medien) – 'przez' + Akkusativ: 'media' (Neutr. Pl., Akk.=Nom.). Beachte: 'media' im Polnischen ist Neutr. Plural (wie im Lateinischen).", "difficulty": "advanced"},
            {"id": "gp_med12", "question": "Subskrybuję ten kanał od _____ roku.", "translation": "Ich abonniere diesen Kanal seit einem Jahr.", "options": ["jednego", "jeden", "jednym", "jednego"], "correct": "jednego", "explanation": "'Od jednego roku' (seit einem Jahr) – 'od' + Genitiv: 'jeden rok' → 'jednego roku'. 'Subskrybować' (abonnieren, Lehnwort) – 1. Pers. Sing.: 'subskrybuję'. 'Ten kanał' (diesen Kanal) im Akkusativ = Nominativ (mask. unbelebt). Die temporale Konstruktion 'od + Gen.' entspricht dem deutschen 'seit + Dativ'.", "difficulty": "intermediate"},
            {"id": "gp_med13", "question": "W internecie jest dużo _____ informacji.", "translation": "Im Internet gibt es viele falsche Informationen.", "options": ["fałszywych", "fałszywe", "fałszywą", "fałszywy"], "correct": "fałszywych", "explanation": "'Dużo' (viel) + Genitiv: 'dużo fałszywych informacji'. 'Fałszywy' → 'fałszywych' (Gen. Pl.), 'informacja' → 'informacji' (Gen. Pl.). Mengenangaben regieren den Genitiv: 'dużo/mało/wiele + Gen. Pl.' Im Deutschen: 'viele falsche Informationen' – Nominativ/Akkusativ; im Polnischen nach Quantifikator: Genitiv.", "difficulty": "intermediate"},
            {"id": "gp_med14", "question": "Czy możesz mi _____ ten link?", "translation": "Kannst du mir diesen Link schicken?", "options": ["wysłać", "wysyłać", "wyślę", "wysyłam"], "correct": "wysłać", "explanation": "'Wysłać' (schicken/senden, vollendet) – nach 'możesz' steht der Infinitiv. 'Mi' (mir) – kurze Dativform. 'Ten link' (diesen Link) im Akkusativ (= Nom., mask. unbelebt). 'Wysłać' (vollendet, einmalig) vs. 'wysyłać' (unvollendet, wiederholt). Nach 'możesz' bei konkreter Bitte: vollendeter Aspekt bevorzugt.", "difficulty": "beginner"},
            {"id": "gp_med15", "question": "Korzystam z mediów _____ codziennie.", "translation": "Ich nutze täglich soziale Medien.", "options": ["społecznościowych", "społecznościowe", "społecznościowy", "społecznościowym"], "correct": "społecznościowych", "explanation": "'Korzystać z' + Genitiv (nutzen/verwenden): 'korzystam z mediów społecznościowych'. 'Media społecznościowe' → 'mediów społecznościowych' (Gen. Pl.). 'Społecznościowy' (sozial/Community-) → 'społecznościowych' (Gen. Pl., Endung '-ych'). Im Deutschen: 'soziale Medien' – im Polnischen: 'media społecznościowe' mit gleicher Adjektiv-nach-Substantiv-Reihenfolge.", "difficulty": "intermediate"}
        ]
    },
    {
        "key": "crime_justice",
        "name": "Recht und Gerechtigkeit (Prawo i sprawiedliwość)",
        "description": "Grammatik und Wortschatz rund um Recht, Verbrechen und Justiz",
        "icon": "building.columns",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_just1", "question": "Oskarżony został _____ winnym.", "translation": "Der Angeklagte wurde für schuldig befunden.", "options": ["uznany za", "uznany na", "uznany z", "uznany do"], "correct": "uznany za", "explanation": "'Uznany za' + Akkusativ (für etwas befunden/gehalten): 'uznany za winnego' → im Satz: 'uznany za winnym' (Instrumental nach 'zostać'). 'Za winnego' = für schuldig. 'Oskarżony' (der Angeklagte) – substantiviertes Partizip im Nominativ. 'Zostać' + Partizip = Vorgangspassiv. Im Deutschen: 'für schuldig befinden'.", "difficulty": "advanced"},
            {"id": "gp_just2", "question": "Sąd _____ wyrok w piątek.", "translation": "Das Gericht hat am Freitag das Urteil verkündet.", "options": ["ogłosił", "ogłosiła", "ogłosili", "ogłosiło"], "correct": "ogłosił", "explanation": "'Ogłosić' (verkünden, vollendet) – 'sąd' (Gericht) ist maskulin: 'ogłosił' (mask. Sing. Verg.). 'Wyrok' (Urteil, maskulin) im Akkusativ (= Nom., unbelebt). 'W piątek' – 'w' + Akkusativ für Wochentage: 'piątek' (Freitag). Im Polnischen sind Wochentage maskulin und stehen nach 'w' im Akkusativ (nicht Lokativ!).", "difficulty": "intermediate"},
            {"id": "gp_just3", "question": "Złodziej został _____ przez policję.", "translation": "Der Dieb wurde von der Polizei gefasst.", "options": ["złapany", "złapana", "złapane", "złapani"], "correct": "złapany", "explanation": "'Złapany' (gefasst/gefangen) – Partizip Passiv mask. Nominativ, kongruiert mit 'złodziej' (Dieb, maskulin). 'Został złapany' – Vorgangspassiv (Perfekt). 'Przez policję' (von der Polizei) – 'przez' + Akkusativ als Agens im Passiv: 'policja' → 'policję'. 'Złodziej' (Dieb) von 'złodziejstwo' (Diebstahl) – typische Ableitung.", "difficulty": "intermediate"},
            {"id": "gp_just4", "question": "Adwokat broni _____ klienta.", "translation": "Der Anwalt verteidigt seinen Mandanten.", "options": ["swojego", "swój", "swoim", "swojemu"], "correct": "swojego", "explanation": "'Bronić' (verteidigen) + Genitiv: 'broni swojego klienta'. 'Swój klient' → 'swojego klienta' (Gen. mask. belebt). 'Bronić' ist ein Verb, das den Genitiv regiert – im Deutschen: 'verteidigen' + Akkusativ. 'Adwokat' (Anwalt/Rechtsanwalt). 'Swój' bezieht sich auf das Subjekt – vermeidet Mehrdeutigkeit: 'jego klienta' könnte jemand anderen meinen.", "difficulty": "intermediate"},
            {"id": "gp_just5", "question": "Za kradzież grozi kara _____ trzech lat.", "translation": "Für Diebstahl droht eine Strafe von bis zu drei Jahren.", "options": ["do", "od", "na", "za"], "correct": "do", "explanation": "'Kara do trzech lat' (Strafe bis zu drei Jahren) – 'do' + Genitiv: 'trzy lata' → 'trzech lat'. 'Grozić' (drohen) + Dativ (implizit, für die bedrohte Person). 'Za kradzież' – 'za' + Akkusativ: wegen/für Diebstahl. 'Kradzież' (Diebstahl, feminin) bleibt im Akkusativ unverändert. Im Deutschen: 'für + Akk.' – parallele Konstruktion.", "difficulty": "intermediate"},
            {"id": "gp_just6", "question": "Świadek zeznał, że _____ wypadek.", "translation": "Der Zeuge sagte aus, dass er den Unfall gesehen hat.", "options": ["widział", "widzieć", "widziałem", "widzi"], "correct": "widział", "explanation": "'Widzieć' (sehen) – 'widział' (3. Pers. mask. Verg.) in indirekter Rede: 'zeznał, że widział'. 'Zeznać' (aussagen) – juristischer Terminus. 'Świadek' (Zeuge, maskulin). 'Wypadek' (Unfall) im Akkusativ = Nominativ (mask. unbelebt). Beachte: Im Polnischen keine Tempusverschiebung in indirekter Rede (anders als im Deutschen/Englischen!).", "difficulty": "intermediate"},
            {"id": "gp_just7", "question": "Prawo _____ wszystkich obywateli.", "translation": "Das Gesetz schützt alle Bürger.", "options": ["chroni", "chronić", "chronią", "chronił"], "correct": "chroni", "explanation": "'Chronić' (schützen) – 3. Pers. Sing.: 'chroni'. 'Prawo' (Gesetz/Recht, Neutrum) als Subjekt. 'Wszystkich obywateli' – Akkusativ = Genitiv bei mask. belebt Plural: 'obywatel' → 'obywateli', 'wszystkich' (alle, Gen./Akk. mask.-personal). Die belebte Akkusativform = Genitiv ist obligatorisch für mask. personale Plurale.", "difficulty": "intermediate"},
            {"id": "gp_just8", "question": "Podejrzany ma prawo do _____.", "translation": "Der Verdächtige hat das Recht auf einen Anwalt.", "options": ["adwokata", "adwokat", "adwokatem", "adwokacie"], "correct": "adwokata", "explanation": "'Prawo do' + Genitiv (Recht auf): 'prawo do adwokata'. 'Adwokat' → 'adwokata' (Gen. mask. belebt). 'Podejrzany' (der Verdächtige) – substantiviertes Adjektiv im Nominativ. Im Deutschen: 'Recht auf + Akkusativ'. 'Mieć prawo do' (ein Recht haben auf) – die polnische Konstruktion mit 'do' + Genitiv ist juristischer Standard.", "difficulty": "intermediate"},
            {"id": "gp_just9", "question": "Policjant wylegitymował _____ samochodu.", "translation": "Der Polizist hat den Fahrer des Autos kontrolliert.", "options": ["kierowcę", "kierowca", "kierowcy", "kierowcą"], "correct": "kierowcę", "explanation": "'Wylegitymować' (kontrollieren/ausweisen) + Akkusativ: 'kierowcę'. 'Kierowca' (Fahrer) ist maskulin, endet aber auf '-a' (wie feminine Substantive!). Daher: Akkusativ = 'kierowcę' (wie bei Feminina auf '-a'). Dies ist eine Besonderheit der maskulinen Substantive auf '-a' (wie 'tata', 'kolega'). 'Samochodu' – Gen.: 'samochód' → 'samochodu'.", "difficulty": "advanced"},
            {"id": "gp_just10", "question": "Sędzia _____ obradom.", "translation": "Der Richter leitet die Verhandlung.", "options": ["przewodniczy", "przewodniczył", "przewodniczyć", "przewodniczą"], "correct": "przewodniczy", "explanation": "'Przewodniczyć' (leiten/vorsitzen) + Dativ: 'przewodniczy obradom'. 'Obrady' (Verhandlung, nur Plural) → 'obradom' (Dat. Pl.). 'Sędzia' (Richter) ist maskulin, endet aber auf '-a' – wie 'kierowca'. 3. Pers. Sing.: 'przewodniczy'. Die formelle Rektion 'przewodniczyć' + Dativ entspricht dem deutschen 'einer Sache vorsitzen'.", "difficulty": "advanced"},
            {"id": "gp_just11", "question": "Przestępca został skazany na pięć _____ więzienia.", "translation": "Der Verbrecher wurde zu fünf Jahren Gefängnis verurteilt.", "options": ["lat", "lata", "roku", "rokiem"], "correct": "lat", "explanation": "'Pięć lat' (fünf Jahre) – 'lat' im Genitiv Plural. 'Rok' hat einen suppletiven Plural: 'rok' → 'lata' (Nom. Pl.) → 'lat' (Gen. Pl.). Zahlwörter ab 5 regieren den Genitiv: 'pięć lat'. 'Skazany na' + Akkusativ (verurteilt zu): 'na pięć lat więzienia'. 'Więzienie' → 'więzienia' (Gen.): fünf Jahre Gefängnis.", "difficulty": "intermediate"},
            {"id": "gp_just12", "question": "Każdy jest _____ wobec prawa.", "translation": "Alle sind vor dem Gesetz gleich.", "options": ["równy", "równa", "równe", "równi"], "correct": "równy", "explanation": "'Równy wobec' + Genitiv (gleich vor): 'równy wobec prawa'. 'Każdy' (jeder) ist maskulin Singular, daher 'równy' (mask. Nom.). 'Wobec' (gegenüber/vor) + Genitiv: 'prawo' → 'prawa'. 'Każdy jest równy' – im Polnischen: Singular (jeder Einzelne); im Deutschen kann man auch Plural verwenden (alle sind gleich).", "difficulty": "intermediate"},
            {"id": "gp_just13", "question": "Nie zgadzam się z tym _____.", "translation": "Ich bin mit diesem Urteil nicht einverstanden.", "options": ["wyrokiem", "wyrok", "wyroku", "wyroki"], "correct": "wyrokiem", "explanation": "'Zgadzać się z' + Instrumental (einverstanden sein mit): 'z tym wyrokiem'. 'Ten wyrok' → 'tym wyrokiem' (Instr. mask. Sing.). 'Nie zgadzam się' – negiertes reflexives Verb. Im Deutschen: 'einverstanden sein mit + Dativ'. Die polnische Rektion mit Instrumental nach 'z' ist parallel zur deutschen mit Dativ nach 'mit'.", "difficulty": "intermediate"},
            {"id": "gp_just14", "question": "Prokuratura wszczęła _____ w tej sprawie.", "translation": "Die Staatsanwaltschaft hat in dieser Sache eine Ermittlung eingeleitet.", "options": ["śledztwo", "śledztwa", "śledztwie", "śledztwem"], "correct": "śledztwo", "explanation": "'Wszcząć' (einleiten, vollendet) + Akkusativ: 'wszczęła śledztwo'. 'Śledztwo' (Ermittlung, Neutrum) – Akk. = Nom. bei Neutra. 'Prokuratura' (Staatsanwaltschaft, fem.) → 'wszczęła' (fem. Verg.). 'W tej sprawie' – 'w' + Lokativ: 'ta sprawa' → 'tej sprawie'. 'Wszcząć' – unregelmäßiges Verb mit Vokalwechsel.", "difficulty": "advanced"},
            {"id": "gp_just15", "question": "Ofiara zgłosiła _____ na policji.", "translation": "Das Opfer hat bei der Polizei eine Anzeige erstattet.", "options": ["przestępstwo", "przestępstwa", "przestępstwu", "przestępstwem"], "correct": "przestępstwo", "explanation": "'Zgłosić' (melden/anzeigen) + Akkusativ: 'zgłosiła przestępstwo'. 'Przestępstwo' (Verbrechen/Straftat, Neutrum) – Akk.=Nom. 'Na policji' (bei der Polizei) – 'na' + Lokativ: 'policja' → 'policji'. Beachte: man sagt 'na policji', nicht 'w policji' – feste Präpositionswahl. 'Ofiara' (Opfer, feminin!) → 'zgłosiła' (fem. Vergangenheit). Im Deutschen ist 'Opfer' Neutrum!", "difficulty": "intermediate"}
        ]
    },
    {
        "key": "politics_society",
        "name": "Politik und Gesellschaft (Polityka i społeczeństwo)",
        "description": "Grammatik und Wortschatz rund um Politik, Wahlen und gesellschaftliches Leben",
        "icon": "person.2.circle",
        "difficulty": "advanced",
        "items": [
            {"id": "gp_pol1", "question": "Obywatele głosują na _____ kandydata.", "translation": "Die Bürger stimmen für ihren Kandidaten.", "options": ["swojego", "swój", "swoim", "swojemu"], "correct": "swojego", "explanation": "'Głosować na' + Akkusativ (stimmen für): 'na swojego kandydata'. 'Swój kandydat' → 'swojego kandydata' (Akk. mask. belebt = Gen.). 'Swój' (sein/ihr eigener) bezieht sich auf das Subjekt 'obywatele'. 'Obywatele' (Bürger) – mask.-personal Plural: 'obywatel' → 'obywatele'. 'Głosują' – 3. Pers. Pl. Präsens.", "difficulty": "intermediate"},
            {"id": "gp_pol2", "question": "Wybory parlamentarne _____ się co cztery lata.", "translation": "Parlamentswahlen finden alle vier Jahre statt.", "options": ["odbywają", "odbywa", "odbył", "odbywała"], "correct": "odbywają", "explanation": "'Odbywać się' (stattfinden) – 'wybory' (Wahlen) ist Pluraliatantum, daher 3. Pers. Plural: 'odbywają się'. Unvollendeter Aspekt für wiederholte Handlung. 'Co cztery lata' (alle vier Jahre) – 'co' + Zahlwort + Akkusativ: 'lata' (Jahre). 'Parlamentarne' (parlamentarisch) – Adjektiv im Nom. Plural.", "difficulty": "intermediate"},
            {"id": "gp_pol3", "question": "Rząd _____ nową ustawę.", "translation": "Die Regierung hat ein neues Gesetz verabschiedet.", "options": ["uchwalił", "uchwaliła", "uchwalili", "uchwaliło"], "correct": "uchwalił", "explanation": "'Uchwalić' (verabschieden/beschließen) – 'rząd' (Regierung) ist maskulin: 'uchwalił' (mask. Sing. Verg.). 'Nową ustawę' – Akkusativ feminin: 'nowa ustawa' → 'nową ustawę'. 'Ustawa' (Gesetz im legislativen Sinne) vs. 'prawo' (Recht/Gesetz allgemein). Die grammatische Kongruenz folgt dem Genus des Subjekts, nicht der logischen Mehrzahl.", "difficulty": "intermediate"},
            {"id": "gp_pol4", "question": "Prezydent wygłosił _____ do narodu.", "translation": "Der Präsident hat eine Rede an die Nation gehalten.", "options": ["przemówienie", "przemówienia", "przemówieniu", "przemówieniem"], "correct": "przemówienie", "explanation": "'Wygłosić przemówienie' (eine Rede halten) – feste Wendung. 'Przemówienie' (Rede, Neutrum) im Akkusativ = Nominativ. 'Do narodu' (an die Nation) – 'do' + Genitiv: 'naród' → 'narodu'. 'Wygłosił' – mask. Verg. von 'wygłosić'. Im Polnischen: 'wygłosić przemówienie'; im Deutschen: 'eine Rede halten' – unterschiedliche Verben!", "difficulty": "intermediate"},
            {"id": "gp_pol5", "question": "Posłowie debatowali _____ nowym budżetem.", "translation": "Die Abgeordneten haben über den neuen Haushalt debattiert.", "options": ["nad", "o", "z", "w"], "correct": "nad", "explanation": "'Debatować nad' + Instrumental (debattieren über): 'nad nowym budżetem'. 'Nowy budżet' → 'nowym budżetem' (Instr. mask.). Beachte: 'debatować nad' (Instrumental) vs. 'dyskutować o' (Lokativ) – beide bedeuten 'diskutieren über', aber mit verschiedenen Präpositionen und Kasus! 'Posłowie' (Abgeordnete) – mask.-personal Plural: 'poseł' → 'posłowie'.", "difficulty": "advanced"},
            {"id": "gp_pol6", "question": "Opozycja _____ politykę rządu.", "translation": "Die Opposition kritisiert die Politik der Regierung.", "options": ["krytykuje", "krytykują", "krytykować", "krytykowała"], "correct": "krytykuje", "explanation": "'Krytykować' (kritisieren) – 'opozycja' ist feminin Singular (Kollektivum): 'krytykuje' (3. Pers. Sing.). 'Politykę rządu' – Akkusativ + Genitiv: 'polityka' → 'politykę', 'rząd' → 'rządu'. Die Genitivkette ('polityka rządu' = Politik der Regierung) entspricht dem deutschen Genitiv oder Kompositum ('Regierungspolitik').", "difficulty": "intermediate"},
            {"id": "gp_pol7", "question": "Demonstranci protestowali _____ podwyżkom cen.", "translation": "Die Demonstranten haben gegen die Preiserhöhungen protestiert.", "options": ["przeciwko", "przeciw", "na", "za"], "correct": "przeciwko", "explanation": "'Protestować przeciwko' + Dativ (protestieren gegen): 'przeciwko podwyżkom cen'. 'Podwyżka' → 'podwyżkom' (Dat. Pl.). 'Cen' – Genitiv Plural: 'cena' → 'cen' (Nullendung im Gen. Pl. fem.). 'Przeciwko' und 'przeciw' sind synonym (beide + Dativ). Im Deutschen: 'gegen + Akkusativ'. 'Demonstranci' – mask.-personal Plural.", "difficulty": "advanced"},
            {"id": "gp_pol8", "question": "Konstytucja gwarantuje wolność _____.", "translation": "Die Verfassung garantiert die Meinungsfreiheit.", "options": ["słowa", "słowo", "słowu", "słowem"], "correct": "słowa", "explanation": "'Wolność słowa' (Meinungsfreiheit, wörtl.: Freiheit des Wortes) – 'słowa' im Genitiv als Attribut. 'Wolność' + Genitiv = 'Freiheit des/der...' 'Gwarantować' (garantieren) + Akkusativ: 'gwarantuje wolność'. 'Konstytucja' (Verfassung, fem.) als Subjekt. 'Wolność słowa' ist ein juristisch-politischer Terminus, der den Genitiv der Erklärung nutzt.", "difficulty": "intermediate"},
            {"id": "gp_pol9", "question": "Minister złożył _____ z pełnionej funkcji.", "translation": "Der Minister hat seinen Rücktritt vom Amt eingereicht.", "options": ["rezygnację", "rezygnacja", "rezygnacji", "rezygnacją"], "correct": "rezygnację", "explanation": "'Złożyć rezygnację' (den Rücktritt einreichen) – feste Wendung. 'Rezygnacja' → 'rezygnację' (Akk. fem.). 'Z pełnionej funkcji' (vom ausgeübten Amt) – 'z' + Genitiv: 'pełniona funkcja' → 'pełnionej funkcji'. 'Pełniony' (ausgeübt) – Partizip Passiv als Attribut. Im Polnischen: 'złożyć rezygnację'; im Deutschen: 'den Rücktritt einreichen'.", "difficulty": "advanced"},
            {"id": "gp_pol10", "question": "Społeczeństwo jest _____ w tej kwestii.", "translation": "Die Gesellschaft ist in dieser Frage gespalten.", "options": ["podzielone", "podzielony", "podzielona", "podzieleni"], "correct": "podzielone", "explanation": "'Podzielone' (gespalten/geteilt) – Nominativ Neutrum, kongruiert mit 'społeczeństwo' (Gesellschaft, Neutrum). 'W tej kwestii' – 'w' + Lokativ: 'ta kwestia' → 'tej kwestii'. Beachte: 'kwestia' → 'kwestii' (Lok.) – Doppel-i am Ende! 'Podzielony' wäre maskulin, 'podzielona' feminin. Das Genus des Substantivs bestimmt die Endung.", "difficulty": "intermediate"},
            {"id": "gp_pol11", "question": "Podatki powinny być _____ sprawiedliwie.", "translation": "Steuern sollten gerecht verteilt werden.", "options": ["rozdzielane", "rozdzielany", "rozdzielana", "rozdzielani"], "correct": "rozdzielane", "explanation": "'Rozdzielane' (verteilt) – Partizip Passiv Plural Neutrum/unbelebt für 'podatki' (Steuern, mask. unbelebt Pl. → nicht-personale Pluralform). 'Powinny być' (sollten sein/werden) – 'powinien/powinna/powinno/powinni/powinny' kongruiert mit dem Subjekt. 'Sprawiedliwie' (gerecht) Adverb. 'Podatki' – mask. unbelebt Plural: 'podatek' → 'podatki'.", "difficulty": "advanced"},
            {"id": "gp_pol12", "question": "Premier spotkał się z _____ państw europejskich.", "translation": "Der Premierminister traf sich mit den Vertretern der europäischen Staaten.", "options": ["przedstawicielami", "przedstawiciele", "przedstawicieli", "przedstawicielom"], "correct": "przedstawicielami", "explanation": "'Spotkać się z' + Instrumental (sich treffen mit): 'z przedstawicielami'. 'Przedstawiciel' → 'przedstawicielami' (Instr. Pl. mask.). 'Państw europejskich' – Genitiv Plural: 'państwo' → 'państw', 'europejski' → 'europejskich'. Die Genitivkette als Attribution. 'Premier' (Premierminister) – Kurzform, maskulin. 'Spotkał się' – mask. Verg.", "difficulty": "advanced"},
            {"id": "gp_pol13", "question": "Frekwencja w wyborach _____ pięćdziesiąt procent.", "translation": "Die Wahlbeteiligung betrug fünfzig Prozent.", "options": ["wyniosła", "wyniosło", "wyniósł", "wyniosły"], "correct": "wyniosła", "explanation": "'Wynosić' (betragen) → 'wyniosła' – Vergangenheit feminin, kongruiert mit 'frekwencja' (Wahlbeteiligung, feminin). 'W wyborach' – 'w' + Lokativ Plural: 'wybory' → 'wyborach'. 'Pięćdziesiąt procent' – 'procent' im Genitiv nach Zahlwörtern ab 5: 'pięćdziesiąt procent' (Gen. Pl. von 'procent'). Die Zahlregelung ist hier besonders wichtig.", "difficulty": "intermediate"},
            {"id": "gp_pol14", "question": "Organizacja walczy _____ prawa człowieka.", "translation": "Die Organisation kämpft für die Menschenrechte.", "options": ["o", "za", "na", "do"], "correct": "o", "explanation": "'Walczyć o' + Akkusativ (kämpfen für/um): 'walczy o prawa człowieka'. 'Prawa' (Rechte) im Akkusativ Plural (= Nominativ, Neutrum). 'Człowieka' – Genitiv: 'człowiek' → 'człowieka' (des Menschen). 'Prawa człowieka' (Menschenrechte) – im Polnischen beschreibende Phrase, im Deutschen Kompositum. Vergleiche: 'walczyć z' (kämpfen gegen).", "difficulty": "intermediate"},
            {"id": "gp_pol15", "question": "Nowa reforma dotyczy _____ edukacji.", "translation": "Die neue Reform betrifft das Bildungssystem.", "options": ["systemu", "system", "systemem", "systemie"], "correct": "systemu", "explanation": "'Dotyczyć' (betreffen) + Genitiv: 'dotyczy systemu edukacji'. 'System' → 'systemu' (Gen. mask.). 'Edukacji' – Genitiv: 'edukacja' → 'edukacji'. 'Dotyczyć' regiert immer den Genitiv – eines der wichtigsten Verben mit Genitivrektion (wie 'szukać', 'potrzebować', 'unikać'). Im Deutschen: 'betreffen' + Akkusativ. 'Nowa reforma' – fem. Nom.", "difficulty": "intermediate"}
        ]
    }
]

with open(GRAMMAR_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)
data.extend(new_categories)
with open(GRAMMAR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"Added {len(new_categories)} categories")
print(f"Total: {len(data)} categories, {sum(len(c['items']) for c in data)} items")
from collections import Counter
all_ids = [item['id'] for c in data for item in c['items']]
dupes = {k:v for k,v in Counter(all_ids).items() if v > 1}
print(f"Duplicates: {dupes if dupes else 'None'}")
# Validate format
issues = []
for c in data:
    for item in c['items']:
        if '_____' not in item.get('question',''):
            issues.append(f"{item['id']}: missing _____")
        if len(item.get('options',[])) != 4:
            issues.append(f"{item['id']}: wrong options count")
        if len(item.get('explanation','')) < 200:
            issues.append(f"{item['id']}: short explanation ({len(item.get('explanation',''))} chars)")
if issues:
    print(f"Format issues ({len(issues)}):")
    for i in issues[:10]:
        print(f"  {i}")
else:
    print("All items pass format validation!")
