import json

FILE = "LumenLingo/LumenLingo/Resources/Content/english_french/grammar_english_french.json"

new_categories = [
  {
    "key": "si_clauses_type1",
    "items": [
      {"id": "ef_si1_1", "question": "Si tu _____ le temps, viens me voir.", "translation": "(If you have time, come see me.)", "options": ["as", "auras", "avais", "aurais"], "correct": "as", "explanation": "Type 1 'si' clauses (real/likely condition) use the present tense after 'si' — never the future. English speakers often want to say 'si tu auras' mirroring 'if you will have,' but French strictly forbids the future tense in the si-clause. The result clause can use the present, imperative, or future. Here 'viens' (imperative) pairs naturally with 'si tu as.'"},
      {"id": "ef_si1_2", "question": "Si elle _____ malade, elle restera à la maison.", "translation": "(If she is sick, she will stay at home.)", "options": ["est", "sera", "était", "serait"], "correct": "est", "explanation": "In Type 1 conditionals, the si-clause takes the present indicative while the main clause uses the future ('restera'). The pattern is: Si + présent → futur simple. This is crucial for expressing realistic, plausible scenarios. Note that 'sera' (future) cannot follow 'si' — a golden rule in French grammar that prevents many common learner errors."},
      {"id": "ef_si1_3", "question": "Nous irons au parc si le temps _____ beau.", "translation": "(We will go to the park if the weather is nice.)", "options": ["est", "sera", "était", "soit"], "correct": "est", "explanation": "Even when the si-clause comes after the main clause, the rule remains: present tense after 'si' in Type 1 conditions. 'Si le temps est beau' expresses a realistic possibility. The main clause 'nous irons' uses futur simple, showing the expected outcome. Word order is flexible in French — si-clause first or second — but the tense agreement never changes."},
      {"id": "ef_si1_4", "question": "Si vous _____ français, vous comprendrez ce film.", "translation": "(If you speak French, you will understand this film.)", "options": ["parlez", "parlerez", "parliez", "parleriez"], "correct": "parlez", "explanation": "The si + présent → futur pattern is demonstrated again here. 'Si vous parlez français' states a realistic condition. Notice that 'comprendrez' (future of comprendre) follows in the result clause. This structure is used for logical consequences: knowing French leads to understanding a French film. The subjunctive ('parliez') and conditional ('parleriez') are incorrect in this Type 1 context."},
      {"id": "ef_si1_5", "question": "Si j'_____ de l'argent, j'achèterai ce livre.", "translation": "(If I have money, I will buy this book.)", "options": ["ai", "aurai", "avais", "aurais"], "correct": "ai", "explanation": "Type 1 conditional with 'avoir': Si + j'ai (présent) → j'achèterai (futur). This expresses a plausible future scenario. The speaker considers it genuinely possible that they'll have money. Contrast this with Type 2's 'Si j'avais... j'achèterais' which implies it's unlikely. Choosing between Type 1 and 2 conveys the speaker's attitude toward the likelihood of the condition."},
      {"id": "ef_si1_6", "question": "Si tu _____ ce soir, apporte du vin.", "translation": "(If you come tonight, bring some wine.)", "options": ["viens", "viendras", "venais", "viendrais"], "correct": "viens", "explanation": "Si + présent paired with an imperative is a natural Type 1 variant. 'Si tu viens' (if you come) introduces a real possibility, and 'apporte du vin' (bring some wine) is the associated request. The imperative in the result clause makes this structure very common in everyday conversation — giving advice or instructions contingent on a likely situation."},
      {"id": "ef_si1_7", "question": "On peut sortir si la pluie _____.", "translation": "(We can go out if the rain stops.)", "options": ["s'arrête", "s'arrêtera", "s'arrêtait", "s'arrêterait"], "correct": "s'arrête", "explanation": "The reflexive verb 's'arrêter' (to stop) takes the present tense after 'si' just like any other verb. The result clause uses 'on peut' (present), showing another Type 1 variant where both clauses are in the present to express a general truth or immediate possibility. This is common when the result is presented as an ability or permission rather than a future action."},
      {"id": "ef_si1_8", "question": "Si les enfants _____ sages, ils auront un dessert.", "translation": "(If the children are well-behaved, they will have dessert.)", "options": ["sont", "seront", "étaient", "soient"], "correct": "sont", "explanation": "Si + présent (sont) → futur (auront) follows the standard Type 1 pattern. 'Sage' means well-behaved/good when applied to children — a uniquely French usage since 'sage' literally means wise. This sentence shows a typical parental conditional promise. Note that 'soient' (subjunctive) is never used after 'si' in French, unlike some other Romance languages."},
      {"id": "ef_si1_9", "question": "Si mon ami _____ d'accord, nous partirons demain.", "translation": "(If my friend agrees, we will leave tomorrow.)", "options": ["est", "sera", "était", "soit"], "correct": "est", "explanation": "'Être d'accord' (to agree/be in agreement) is a key French expression using 'être.' In this Type 1 conditional, 'si mon ami est d'accord' presents a realistic condition with 'partirons' (futur simple) as the result. The expression doesn't use 'agréer' or 'convenir' — French prefers 'être d'accord' in everyday speech, making it essential vocabulary alongside the grammar pattern."},
      {"id": "ef_si1_10", "question": "Je te prêterai ma voiture si tu _____ prudemment.", "translation": "(I will lend you my car if you drive carefully.)", "options": ["conduis", "conduiras", "conduisais", "conduirais"], "correct": "conduis", "explanation": "Conduire (to drive) is an irregular verb that becomes 'conduis' in the present tense (tu form). After 'si' in Type 1, present tense is mandatory. The adverb 'prudemment' (carefully/prudently) is placed after the verb, following French adverb placement rules. This sentence combines the si-clause grammar rule with practical vocabulary about driving and lending."},
      {"id": "ef_si1_11", "question": "Si le professeur _____ absent, le cours sera annulé.", "translation": "(If the teacher is absent, the class will be canceled.)", "options": ["est", "sera", "était", "serait"], "correct": "est", "explanation": "Si + présent → futur simple: a textbook Type 1 conditional. 'Annulé' is the past participle of 'annuler' (to cancel), used here with 'sera' to form the future passive. This structure is very common in academic and professional contexts. Note 'le cours' means 'the class/lesson' while 'la cour' means 'the courtyard' — a spelling distinction learners should master early."},
      {"id": "ef_si1_12", "question": "Si nous _____ assez tôt, nous attraperons le train.", "translation": "(If we leave early enough, we will catch the train.)", "options": ["partons", "partirons", "partions", "partirions"], "correct": "partons", "explanation": "'Partir' (to leave) takes the present form 'partons' after 'si' in a Type 1 conditional. 'Attraper le train' (to catch the train) is an idiomatic expression. 'Assez tôt' means 'early enough,' with 'assez' placed before the adverb it modifies. The entire sentence models practical travel-related French while reinforcing the si + présent → futur rule."},
      {"id": "ef_si1_13", "question": "Si tu ne _____ pas, tu vas rater l'examen.", "translation": "(If you don't study, you're going to fail the exam.)", "options": ["étudies", "étudieras", "étudiais", "étudierais"], "correct": "étudies", "explanation": "Negation in si-clauses follows the same tense rules: 'si tu n'étudies pas' uses the present. The result here uses 'aller + infinitif' (futur proche) instead of futur simple, which is perfectly valid and common in spoken French for immediate or very likely outcomes. 'Rater' (to fail/miss) is more colloquial than 'échouer à' and widely used in everyday speech."},
      {"id": "ef_si1_14", "question": "Si ça te _____, on peut dîner ensemble.", "translation": "(If that suits you, we can have dinner together.)", "options": ["convient", "conviendra", "convenait", "conviendrait"], "correct": "convient", "explanation": "'Convenir' (to suit/be convenient) is an irregular verb conjugated like 'venir.' 'Si ça te convient' is an extremely useful conversational phrase for making plans. The result clause uses 'on peut' (present), creating a Type 1 variant where both clauses are present tense — common when offering possibilities. 'Dîner ensemble' (to dine together) completes this practical social French expression."},
      {"id": "ef_si1_15", "question": "Si le magasin _____ ouvert, j'irai acheter du pain.", "translation": "(If the store is open, I will go buy some bread.)", "options": ["est", "sera", "était", "soit"], "correct": "est", "explanation": "Final reinforcement of the cardinal rule: si + présent → futur. 'Ouvert' (open) is the past participle of 'ouvrir,' used here as an adjective. 'J'irai acheter' combines futur simple of 'aller' with an infinitive — a common construction meaning 'I will go buy.' 'Du pain' uses the partitive article, essential in French when talking about some/any of an uncountable noun like bread."}
    ]
  },
  {
    "key": "si_clauses_type2",
    "items": [
      {"id": "ef_si2_1", "question": "Si j'_____ riche, je voyagerais autour du monde.", "translation": "(If I were rich, I would travel around the world.)", "options": ["étais", "suis", "serais", "serai"], "correct": "étais", "explanation": "Type 2 'si' clauses express unreal or unlikely present/future conditions. The formula is: Si + imparfait → conditionnel présent. 'Si j'étais riche' (if I were rich) implies the speaker is NOT rich — it's hypothetical. English uses 'were' for all persons in formal registers ('if I were'), while French consistently uses the imparfait. This is the most common hypothetical structure in French."},
      {"id": "ef_si2_2", "question": "Si nous _____ en France, nous parlerions français tous les jours.", "translation": "(If we lived in France, we would speak French every day.)", "options": ["vivions", "vivons", "vivrions", "vivrons"], "correct": "vivions", "explanation": "'Vivre' (to live) in the imparfait gives 'vivions' for 'nous.' This Type 2 conditional presents an imaginary scenario — the speakers don't actually live in France. The conditionnel présent 'parlerions' shows the hypothetical result. Notice 'tous les jours' (every day) is a fixed expression — never 'chaque jours' (chaque is always singular). This sentence beautifully combines grammar with motivational language-learning content."},
      {"id": "ef_si2_3", "question": "Si tu _____ le temps, tu pourrais apprendre le piano.", "translation": "(If you had the time, you could learn the piano.)", "options": ["avais", "as", "aurais", "auras"], "correct": "avais", "explanation": "Si + imparfait (avais) → conditionnel (pourrais): the speaker suggests the listener probably doesn't have enough time. 'Pouvoir' in the conditionnel ('pourrais') softens the suggestion — 'you could' rather than 'you would.' This polite/tentative use of the conditional is extremely common in French. 'Apprendre le piano' uses the definite article before instruments, unlike English."},
      {"id": "ef_si2_4", "question": "Si elle _____ plus grande, elle serait mannequin.", "translation": "(If she were taller, she would be a model.)", "options": ["était", "est", "serait", "sera"], "correct": "était", "explanation": "Si + imparfait → conditionnel for an unreal present condition. 'Plus grande' means taller (or bigger, depending on context). Note that French doesn't use an article before professions after 'être': 'elle serait mannequin' (not 'une mannequin'). This is a specific French rule — no article with être + profession unless qualified by an adjective. 'Mannequin' is masculine even when referring to a woman."},
      {"id": "ef_si2_5", "question": "Nous _____ à la plage s'il faisait beau.", "translation": "(We would go to the beach if the weather were nice.)", "options": ["irions", "allons", "irons", "allions"], "correct": "irions", "explanation": "When the si-clause comes second, the main clause still takes the conditionnel présent. 'Irions' is the conditionnel of 'aller' (irregular). 'S'il faisait beau' uses the imparfait of 'faire' — weather expressions in French use 'faire': il fait beau, il fait chaud, il fait froid. The contraction 's'il' (si + il) is mandatory; you never write 'si il' in French."},
      {"id": "ef_si2_6", "question": "Si je _____ toi, j'accepterais cette offre.", "translation": "(If I were you, I would accept this offer.)", "options": ["étais", "suis", "serais", "serai"], "correct": "étais", "explanation": "'Si j'étais toi' (if I were you) is a fixed expression used to give advice — one of the most practical Type 2 constructions. In English, 'were' is used instead of 'was' in formal registers, but French simply uses the imparfait 'étais.' The conditionnel 'j'accepterais' gives the recommended action. This phrase is invaluable for politely offering opinions or suggestions in French conversation."},
      {"id": "ef_si2_7", "question": "Si on me _____ le choix, je prendrais le rouge.", "translation": "(If someone gave me the choice, I would take the red one.)", "options": ["donnait", "donne", "donnerait", "donnera"], "correct": "donnait", "explanation": "'On' used as an indefinite subject (someone/people) takes third-person singular conjugation. 'Donnait' (imparfait) creates the hypothetical condition. 'Je prendrais' (conditionnel of prendre) expresses the imagined result. 'Le rouge' (the red one) uses an adjective as a noun with the definite article — a common French construction that English learners need to master for everyday situations."},
      {"id": "ef_si2_8", "question": "Si tu _____ plus souvent, tu serais en meilleure forme.", "translation": "(If you exercised more often, you would be in better shape.)", "options": ["faisais", "fais", "ferais", "feras"], "correct": "faisais", "explanation": "'Faire du sport/de l'exercice' uses 'faire' for physical activity. 'Si tu faisais' (imparfait) implies the person doesn't currently exercise enough. 'En meilleure forme' (in better shape) uses the comparative of 'bon' → 'meilleur.' Note: 'plus bon' is incorrect in French — the comparative of 'bon' is always 'meilleur,' similar to how English uses 'better' not 'more good.' This is a common exam pitfall."},
      {"id": "ef_si2_9", "question": "Si les gens _____ plus aimables, le monde serait meilleur.", "translation": "(If people were kinder, the world would be better.)", "options": ["étaient", "sont", "seraient", "seront"], "correct": "étaient", "explanation": "A philosophical Type 2 conditional using 'les gens' (people) with the imparfait plural 'étaient.' 'Plus aimables' (kinder) uses the regular comparative. The result 'le monde serait meilleur' again uses 'meilleur' (not 'plus bon'). This type of hypothetical statement about improving society is common in essays and discussions, making it excellent practice for both grammar and academic French expression."},
      {"id": "ef_si2_10", "question": "Si nous _____ plus d'argent, nous déménagerions.", "translation": "(If we had more money, we would move.)", "options": ["avions", "avons", "aurions", "aurons"], "correct": "avions", "explanation": "'Déménager' means 'to move (house)' — not to be confused with 'bouger' (to move physically) or 'déplacer' (to move an object). Si + imparfait (avions) → conditionnel (déménagerions). 'Plus d'argent' uses 'de' after 'plus' — a key quantity expression rule. This sentence illustrates how Type 2 conditionals express wishes about one's current situation that are unlikely to come true."},
      {"id": "ef_si2_11", "question": "Si je _____ conduire, je t'emmènerais à l'aéroport.", "translation": "(If I could drive, I would take you to the airport.)", "options": ["savais", "sais", "saurais", "saurai"], "correct": "savais", "explanation": "'Savoir conduire' (to know how to drive) uses 'savoir' for learned abilities, not 'pouvoir.' This distinction is crucial: 'savoir' = knowing how (skills), 'pouvoir' = being able to (permission/possibility). 'Emmener' (to take someone somewhere) differs from 'amener' (to bring someone) and 'emporter/apporter' (for things). The conditionnel 'emmènerais' shows the hypothetical result."},
      {"id": "ef_si2_12", "question": "Si cette robe _____ moins chère, je l'achèterais.", "translation": "(If this dress were cheaper, I would buy it.)", "options": ["était", "est", "serait", "soit"], "correct": "était", "explanation": "'Moins cher/chère' (less expensive/cheaper) is the inverse comparative. Note 'chère' has the feminine 'e' agreeing with 'robe' (feminine). 'Je l'achèterais' uses the direct object pronoun 'l'' replacing 'la robe' — essential in French to avoid repetition. Acheter takes an accent change: j'achète/j'achèterais (è before silent syllable). This demonstrates how grammar rules interconnect in natural sentences."},
      {"id": "ef_si2_13", "question": "Si mon patron me _____ une augmentation, je serais content.", "translation": "(If my boss gave me a raise, I would be happy.)", "options": ["donnait", "donne", "donnerait", "donnera"], "correct": "donnait", "explanation": "'Patron' (boss) and 'augmentation' (raise/pay increase) are essential workplace vocabulary. Si + imparfait (donnait) creates the unlikely condition. 'Content' (happy/pleased) is simpler than 'heureux' and very common in spoken French. The entire sentence models workplace conversation — discussing hypothetical scenarios about salary is a natural context for Type 2 conditionals. Note 'me donnait' — indirect object pronoun placement before the verb."},
      {"id": "ef_si2_14", "question": "Si tu _____ à ma place, que ferais-tu ?", "translation": "(If you were in my place, what would you do?)", "options": ["étais", "es", "serais", "seras"], "correct": "étais", "explanation": "'Être à la place de quelqu'un' (to be in someone's place/shoes) is an idiomatic expression. 'Que ferais-tu ?' uses inversion for the question in the conditionnel — very natural in French for seeking advice. This combines Type 2 conditional grammar with question formation and inversion, showing how multiple grammar points work together. Compare with the less formal 'Tu ferais quoi ?' used in casual speech."},
      {"id": "ef_si2_15", "question": "Si j'_____ le choix, je vivrais à la campagne.", "translation": "(If I had the choice, I would live in the countryside.)", "options": ["avais", "ai", "aurais", "aurai"], "correct": "avais", "explanation": "'Avoir le choix' (to have the choice) uses the definite article, unlike English. 'La campagne' means the countryside — 'à la campagne' for location, like 'à la montagne' (in the mountains) and 'à la mer' (at the sea). These fixed preposition + article combinations are essential French geography vocabulary. The conditionnel 'vivrais' (from vivre) expresses an unrealized dream about an alternative lifestyle."}
    ]
  },
  {
    "key": "si_clauses_type3",
    "items": [
      {"id": "ef_si3_1", "question": "Si j'avais su, je ne _____ pas venu.", "translation": "(If I had known, I would not have come.)", "options": ["serais", "suis", "serai", "étais"], "correct": "serais", "explanation": "Type 3 conditionals express regret about past events using: Si + plus-que-parfait → conditionnel passé. 'Si j'avais su' (if I had known) describes an impossible past condition. The result uses conditionnel passé: 'je ne serais pas venu' (I would not have come). 'Venir' uses 'être' as its auxiliary — one of the DR MRS VANDERTRAMP verbs. This is one of French's most common expressions of regret."},
      {"id": "ef_si3_2", "question": "Si tu avais étudié, tu _____ réussi l'examen.", "translation": "(If you had studied, you would have passed the exam.)", "options": ["aurais", "avais", "auras", "as"], "correct": "aurais", "explanation": "Si + plus-que-parfait (avais étudié) → conditionnel passé (aurais réussi). This expresses a past regret: the person didn't study and therefore failed. 'Réussir' (to pass/succeed) takes 'avoir' as its auxiliary. Contrast with 'rater' (to fail) which appeared earlier. The conditionnel passé is formed with the conditional of the auxiliary (aurais/serais) + past participle. This is one of the most challenging but essential French structures."},
      {"id": "ef_si3_3", "question": "Si nous étions partis plus tôt, nous _____ arrivés à l'heure.", "translation": "(If we had left earlier, we would have arrived on time.)", "options": ["serions", "sommes", "serons", "étions"], "correct": "serions", "explanation": "Both 'partir' and 'arriver' are DR MRS VANDERTRAMP verbs using 'être.' The si-clause uses plus-que-parfait with être: 'étions partis.' The result uses conditionnel passé: 'serions arrivés.' Note the past participle agreement with 'nous': 'arrivés' (masculine plural). 'À l'heure' (on time) contrasts with 'en retard' (late) and 'en avance' (early) — three essential time-related expressions."},
      {"id": "ef_si3_4", "question": "Elle _____ venue si on l'avait invitée.", "translation": "(She would have come if she had been invited.)", "options": ["serait", "est", "sera", "était"], "correct": "serait", "explanation": "The result clause comes first here, taking conditionnel passé: 'serait venue.' Note the feminine agreement on 'venue' (elle). The si-clause 'si on l'avait invitée' uses plus-que-parfait with the direct object pronoun 'l'' (la → l' before vowel). Past participle 'invitée' agrees with the preceding direct object pronoun (feminine). This sentence demonstrates three rules simultaneously: Type 3 conditions, être verbs, and participle agreement."},
      {"id": "ef_si3_5", "question": "Si j'avais _____ la vérité, je t'aurais prévenu.", "translation": "(If I had known the truth, I would have warned you.)", "options": ["su", "savoir", "sachant", "savais"], "correct": "su", "explanation": "'Savoir' has the irregular past participle 'su.' In the plus-que-parfait: 'j'avais su.' The result 'je t'aurais prévenu' uses 'prévenir' (to warn/inform) — conjugated like 'venir' but taking 'avoir' as its auxiliary because it's transitive. The direct object pronoun 'te' → 't'' precedes the auxiliary. Knowing irregular past participles is essential for forming compound tenses correctly."},
      {"id": "ef_si3_6", "question": "Si vous aviez _____ attention, vous n'auriez pas fait cette erreur.", "translation": "(If you had paid attention, you would not have made this mistake.)", "options": ["fait", "faire", "faisant", "fais"], "correct": "fait", "explanation": "'Faire attention' (to pay attention) uses 'fait' as the past participle of 'faire' (irregular). The plus-que-parfait 'aviez fait attention' creates the unrealized condition. 'Auriez fait' in the result is also from 'faire' — the same verb appears in both clauses with different tense functions. 'Cette erreur' uses the demonstrative adjective 'cette' (feminine), matching 'erreur' which is always feminine in French."},
      {"id": "ef_si3_7", "question": "Si le train n'avait pas eu de retard, je _____ arrivé à temps.", "translation": "(If the train hadn't been delayed, I would have arrived on time.)", "options": ["serais", "suis", "serai", "étais"], "correct": "serais", "explanation": "'Avoir du retard' (to be delayed/running late) becomes 'avait eu' in the plus-que-parfait. Negation wraps around the auxiliary: 'n'avait pas eu.' The result uses conditionnel passé with être (arriver is a DR MRS VANDERTRAMP verb): 'serais arrivé.' 'À temps' (on time/in time) is slightly different from 'à l'heure' (at the scheduled time). This transport scenario is realistic and tests multiple grammar rules simultaneously."},
      {"id": "ef_si3_8", "question": "Si elle avait pris son parapluie, elle ne se _____ pas mouillée.", "translation": "(If she had taken her umbrella, she wouldn't have gotten wet.)", "options": ["serait", "sera", "est", "était"], "correct": "serait", "explanation": "'Se mouiller' (to get wet) is reflexive, so it uses 'être' in compound tenses: 'se serait mouillée.' The negation 'ne... pas' surrounds the reflexive pronoun and auxiliary: 'ne se serait pas mouillée.' Note the feminine agreement 'mouillée' with 'elle.' 'Prendre son parapluie' (to take one's umbrella) uses the possessive adjective 'son' — feminine nouns starting with a vowel/h use 'son' not 'sa.'"},
      {"id": "ef_si3_9", "question": "Si nous avions réservé, nous _____ eu une meilleure table.", "translation": "(If we had booked, we would have had a better table.)", "options": ["aurions", "avons", "aurons", "avions"], "correct": "aurions", "explanation": "'Réserver' (to book/reserve) forms a regular plus-que-parfait: 'avions réservé.' The result 'aurions eu' is conditionnel passé of 'avoir' — 'eu' being the past participle of avoir. 'Une meilleure table' uses 'meilleure' (better, feminine), the irregular comparative of 'bonne.' Remember: bon → meilleur, not 'plus bon.' This restaurant scenario is practical for real-world use of Type 3 conditionals."},
      {"id": "ef_si3_10", "question": "Si j'avais lu les instructions, je n'_____ pas cassé la machine.", "translation": "(If I had read the instructions, I wouldn't have broken the machine.)", "options": ["aurais", "avais", "ai", "aurai"], "correct": "aurais", "explanation": "'Lire' has the past participle 'lu' (irregular). 'Casser' (to break) is regular: 'cassé.' The negation 'n'aurais pas cassé' wraps around the auxiliary in the conditionnel passé. This sentence perfectly models a common regret scenario — not reading instructions. Note 'les instructions' uses the definite article for specific instructions, and 'la machine' similarly uses the definite article for a specific machine."},
      {"id": "ef_si3_11", "question": "Si tu avais _____ la porte, le chat ne serait pas sorti.", "translation": "(If you had closed the door, the cat wouldn't have gone out.)", "options": ["fermé", "fermer", "fermant", "fermes"], "correct": "fermé", "explanation": "'Fermer' (to close) has the regular past participle 'fermé.' 'Sortir' uses être as its auxiliary: 'serait sorti' in the conditionnel passé. The negation 'ne serait pas sorti' wraps around the auxiliary. This everyday domestic scenario — a cat escaping through an open door — makes Type 3 conditionals feel natural and relatable, not just academic. Past participle 'sorti' doesn't agree because 'chat' is masculine singular (default form)."},
      {"id": "ef_si3_12", "question": "Si on m'avait demandé, j'_____ dit oui.", "translation": "(If they had asked me, I would have said yes.)", "options": ["aurais", "avais", "ai", "aurai"], "correct": "aurais", "explanation": "'On' as indefinite subject (they/someone) + plus-que-parfait: 'on m'avait demandé.' The indirect object pronoun 'me' → 'm'' before a vowel. 'Dire' has the irregular past participle 'dit': 'j'aurais dit.' This simple but powerful sentence shows how Type 3 conditionals express missed opportunities. 'Dire oui/non' (to say yes/no) is more natural in French than 'accepter/refuser' in casual conversation."},
      {"id": "ef_si3_13", "question": "Si les joueurs avaient mieux _____, ils auraient gagné le match.", "translation": "(If the players had played better, they would have won the match.)", "options": ["joué", "jouer", "jouant", "jouent"], "correct": "joué", "explanation": "'Jouer' → 'joué' (regular past participle). 'Mieux' (better, adverb — comparative of 'bien') is placed between the auxiliary and the participle: 'avaient mieux joué.' Compare 'mieux' (adverb: better) with 'meilleur' (adjective: better). 'Gagner le match' (to win the match) — 'gagner' is regular. This sports context shows Type 3 conditionals in post-game analysis, a very natural real-world application."},
      {"id": "ef_si3_14", "question": "Si j'avais _____ que c'était si loin, j'aurais pris un taxi.", "translation": "(If I had known it was so far, I would have taken a taxi.)", "options": ["su", "savoir", "sachant", "savais"], "correct": "su", "explanation": "'Savoir' → 'su' in the plus-que-parfait: 'j'avais su.' 'Que c'était si loin' is a noun clause — note the imparfait 'était' (not plus-que-parfait) in the embedded clause, describing the simultaneous state. 'Prendre un taxi' → 'aurais pris' uses the irregular past participle 'pris.' 'Si loin' (so far) — 'si' before adjectives/adverbs means 'so.' This sentence layers subordinate clauses within a Type 3 conditional."},
      {"id": "ef_si3_15", "question": "Si elle s'était levée plus tôt, elle n'_____ pas raté son bus.", "translation": "(If she had gotten up earlier, she wouldn't have missed her bus.)", "options": ["aurait", "avait", "a", "aura"], "correct": "aurait", "explanation": "'Se lever' (to get up) is reflexive, using être in compound tenses: 's'était levée' (plus-que-parfait, feminine agreement). 'Rater son bus' (to miss one's bus) uses 'avoir': 'aurait raté.' This sentence uniquely combines a reflexive être-verb in the si-clause with an avoir-verb in the result clause, testing whether students can correctly choose different auxiliaries within one sentence. 'Plus tôt' (earlier) — two words, unlike 'plutôt' (rather) — one word."}
    ]
  },
  {
    "key": "question_formation",
    "items": [
      {"id": "ef_qf_1", "question": "_____ est-ce que tu fais ce soir ?", "translation": "(What are you doing tonight?)", "options": ["Qu'", "Que", "Quoi", "Comment"], "correct": "Qu'", "explanation": "'Qu'est-ce que' is the standard way to ask 'what' in French when the answer is a direct object. Before a vowel, 'que' elides to 'qu'.' This phrase literally means 'what is it that' — a fixed interrogative construction. There are three levels of formality: 'Tu fais quoi ?' (informal), 'Qu'est-ce que tu fais ?' (standard), 'Que fais-tu ?' (formal with inversion). Master all three for natural communication."},
      {"id": "ef_qf_2", "question": "_____ habites-tu ?", "translation": "(Where do you live?)", "options": ["Où", "Quand", "Comment", "Pourquoi"], "correct": "Où", "explanation": "'Où' (where) is one of the key interrogative words in French. With inversion, the structure is: Où + verb + hyphen + subject pronoun. 'Où habites-tu ?' is formal register. The informal equivalent is 'Tu habites où ?' or 'Où est-ce que tu habites ?' The accent grave on 'où' distinguishes it from 'ou' (or) — a critical spelling difference. 'Habiter' can be transitive or intransitive: 'habiter à Paris' or 'habiter Paris.'"},
      {"id": "ef_qf_3", "question": "_____ de frères et sœurs as-tu ?", "translation": "(How many brothers and sisters do you have?)", "options": ["Combien", "Comment", "Quand", "Pourquoi"], "correct": "Combien", "explanation": "'Combien de' (how many/how much) is followed directly by the noun without an article — never 'combien des.' 'Frères et sœurs' (brothers and sisters / siblings) — French doesn't have a single common word for 'siblings' like English does. 'Combien' can also mean 'how much' for prices: 'Combien ça coûte ?' The inversion here ('as-tu') makes this formal; informally: 'Tu as combien de frères et sœurs ?'"},
      {"id": "ef_qf_4", "question": "À _____ heure commence le film ?", "translation": "(At what time does the film start?)", "options": ["quelle", "quel", "quels", "quelles"], "correct": "quelle", "explanation": "'Quel/quelle' (which/what) agrees in gender and number with the noun it modifies. 'Heure' is feminine singular → 'quelle.' The forms are: quel (m.sg.), quelle (f.sg.), quels (m.pl.), quelles (f.pl.). This question uses the est-ce que-free format with standard word order. 'Commencer' (to start/begin) is regular but has a cedilla in some forms: 'commençons.' 'À quelle heure' is the standard way to ask about time in French."},
      {"id": "ef_qf_5", "question": "_____ est-ce qu'il pleut toujours ici ?", "translation": "(Why does it always rain here?)", "options": ["Pourquoi", "Comment", "Quand", "Combien"], "correct": "Pourquoi", "explanation": "'Pourquoi' (why) is unique among French interrogatives because it CANNOT be used with simple inversion when there's a noun subject (only with pronoun subjects). 'Pourquoi est-ce que' is the safest construction. Note: 'Pourquoi pleut-il ?' is correct (pronoun inversion), but 'Pourquoi pleut la pluie ?' is not. 'Toujours' (always) is placed after the conjugated verb. 'Ici' (here) comes at the end as a place adverb."},
      {"id": "ef_qf_6", "question": "_____ vas-tu au travail, en bus ou en voiture ?", "translation": "(How do you go to work, by bus or by car?)", "options": ["Comment", "Pourquoi", "Quand", "Combien"], "correct": "Comment", "explanation": "'Comment' (how) asks about manner or method. 'En bus' and 'en voiture' use 'en' for enclosed transport (bus, car, train, avion) while 'à' is used for open transport (à vélo, à pied, à cheval). This is a fundamental transport preposition rule in French. The formal inversion 'vas-tu' could be replaced by 'est-ce que tu vas' (standard) or 'tu vas comment ?' (informal). Note the 's' in 'vas' before 'tu' for pronunciation."},
      {"id": "ef_qf_7", "question": "_____ est ton anniversaire ?", "translation": "(When is your birthday?)", "options": ["Quand", "Comment", "Combien", "Où"], "correct": "Quand", "explanation": "'Quand' (when) asks about time. 'Ton anniversaire' (your birthday) uses the possessive adjective 'ton' before a vowel — even though 'anniversaire' is masculine, it could be confusing because feminine nouns beginning with a vowel also use 'ton' (not 'ta'). With 'être,' inversion is simple: 'Quand est ton anniversaire ?' No hyphen is needed when inverting with a noun subject after 'être' in short questions. This is a high-frequency social question."},
      {"id": "ef_qf_8", "question": "De _____ couleur sont tes yeux ?", "translation": "(What color are your eyes?)", "options": ["quelle", "quel", "quels", "quelles"], "correct": "quelle", "explanation": "'De quelle couleur' (what color/of what color) is a fixed interrogative phrase. 'Couleur' is feminine → 'quelle.' Even though 'yeux' (eyes, irregular plural of 'œil') is masculine plural, 'quelle' agrees with 'couleur,' not 'yeux.' This shows that 'quel' agrees with its accompanying noun, not the sentence subject. 'Tes yeux' uses the plural possessive. The verb 'sont' agrees with 'tes yeux' (plural subject)."},
      {"id": "ef_qf_9", "question": "_____ préfères-tu, le thé ou le café ?", "translation": "(Which do you prefer, tea or coffee?)", "options": ["Lequel", "Quel", "Qui", "Que"], "correct": "Lequel", "explanation": "'Lequel' (which one) is a pronoun replacing 'quel + noun.' Its forms agree in gender and number: lequel (m.sg.), laquelle (f.sg.), lesquels (m.pl.), lesquelles (f.pl.). It's used when the noun is understood from context. With prepositions, contractions occur: à + lequel = auquel, de + lequel = duquel. 'Préférer' has accent changes: je préfère but nous préférons. This question format is very common for choices between options."},
      {"id": "ef_qf_10", "question": "À _____ parles-tu ?", "translation": "(Who are you talking to?)", "options": ["qui", "que", "quoi", "lequel"], "correct": "qui", "explanation": "'Qui' after a preposition refers to people: 'à qui' (to whom), 'avec qui' (with whom), 'pour qui' (for whom). In informal French, the preposition often moves to the end: 'Tu parles à qui ?' Unlike English, where ending with a preposition is standard ('Who are you talking to?'), formal French requires the preposition before 'qui.' 'Parler à quelqu'un' (to talk to someone) takes the preposition 'à' — a key verb construction to memorize."},
      {"id": "ef_qf_11", "question": "De _____ as-tu besoin ?", "translation": "(What do you need?)", "options": ["quoi", "que", "qui", "quel"], "correct": "quoi", "explanation": "'Quoi' is used after prepositions when referring to things: 'de quoi' (of what), 'à quoi' (to what), 'avec quoi' (with what). Contrast: 'qui' for people after prepositions, 'quoi' for things. 'Avoir besoin de' (to need) is a fixed expression — never 'avoir besoin pour' or just 'besoin.' The inversion 'as-tu' makes this formal. Informally: 'Tu as besoin de quoi ?' This distinction between 'qui' and 'quoi' after prepositions is essential."},
      {"id": "ef_qf_12", "question": "_____ est-ce qui fait ce bruit ?", "translation": "(What is making that noise?)", "options": ["Qu'", "Qui", "Quoi", "Comment"], "correct": "Qu'", "explanation": "'Qu'est-ce qui' asks 'what' as the SUBJECT of the verb. Compare: 'Qu'est-ce que' (what as object) vs. 'Qu'est-ce qui' (what as subject). 'Qu'est-ce QUI fait ce bruit' = what is making this noise (the 'what' does the action). 'Qu'est-ce QUE tu fais' = what are you doing (the 'what' receives the action). This subject/object distinction is one of the trickiest aspects of French question formation for English speakers."},
      {"id": "ef_qf_13", "question": "_____ est-ce qui a téléphoné ?", "translation": "(Who called?)", "options": ["Qui", "Qu'", "Quoi", "Quel"], "correct": "Qui", "explanation": "'Qui est-ce qui' asks 'who' as the SUBJECT — the person performing the action. 'Qui' appears twice: once as the interrogative word and once as the relative pronoun introducing the verb. In simpler form, just 'Qui a téléphoné ?' works perfectly. 'Téléphoner' (to call/phone) is intransitive in French — you 'téléphoner à quelqu'un' (call someone), unlike English where 'call' is transitive. This verb construction difference is a common error source."},
      {"id": "ef_qf_14", "question": "Tu viens, _____ ?", "translation": "(You're coming, right?)", "options": ["n'est-ce pas", "est-ce que", "qu'est-ce que", "pourquoi"], "correct": "n'est-ce pas", "explanation": "'N'est-ce pas' is a tag question added to the end of a statement to seek confirmation — equivalent to English 'right?', 'isn't it?', 'don't you?' It works with any statement regardless of the verb: 'Il fait beau, n'est-ce pas ?' (It's nice, isn't it?). In informal speech, 'non ?' or 'hein ?' serve the same purpose. Unlike English tag questions which change form (isn't it/don't you/haven't they), 'n'est-ce pas' is universal."},
      {"id": "ef_qf_15", "question": "_____ s'appelle ton professeur ?", "translation": "(What is your teacher's name?)", "options": ["Comment", "Quel", "Qui", "Que"], "correct": "Comment", "explanation": "In French, you ask someone's name with 'Comment s'appelle...?' (literally 'How does... call himself?'), not 'Quel est le nom de...?' (though that exists, it's more formal). 'S'appeler' is reflexive and has spelling changes: je m'appelle, tu t'appelles, il s'appelle. 'Ton professeur' uses 'ton' — even if the teacher is female, 'professeur' was traditionally masculine (though 'professeure' is increasingly used). This is a foundational French social question."}
    ]
  },
  {
    "key": "inversion_questions",
    "items": [
      {"id": "ef_inv_1", "question": "Parlez-_____ français ?", "translation": "(Do you speak French?)", "options": ["vous", "tu", "ils", "nous"], "correct": "vous", "explanation": "Subject-verb inversion is the formal way to ask questions in French. The subject pronoun moves after the verb, connected by a hyphen: 'Parlez-vous.' This is the formal equivalent of 'Est-ce que vous parlez français ?' or the informal 'Vous parlez français ?' (rising intonation). Inversion with 'vous' is the most common in professional and formal contexts. Mastering all three question levels is essential for appropriate register."},
      {"id": "ef_inv_2", "question": "Aime-t-_____ le chocolat ?", "translation": "(Does he/she like chocolate?)", "options": ["il", "elle", "on", "tu"], "correct": "il", "explanation": "When inversion creates a vowel-vowel clash (aime + il), a euphonic 't' is inserted between hyphens: 'aime-t-il.' This only happens with third-person singular (il/elle/on) when the verb ends in a vowel. It doesn't happen with 'tu' (consonant) or plural forms. 'Aime-t-il' / 'aime-t-elle' / 'aime-t-on' all follow this pattern. This euphonic 't' has no meaning — it exists purely for smooth pronunciation. All options could be correct contextually, but the canonical form uses 'il.'"},
      {"id": "ef_inv_3", "question": "Les enfants, sont-_____ prêts ?", "translation": "(Are the children ready?)", "options": ["ils", "elles", "on", "nous"], "correct": "ils", "explanation": "When the subject is a noun (les enfants), French uses 'complex inversion': the noun stays before the verb and a pronoun is added after it: 'Les enfants, sont-ils prêts ?' The comma after 'les enfants' is important. You cannot simply say 'Sont les enfants prêts ?' — that's ungrammatical in French. This double-subject structure is unique to French and essential for formal written and spoken discourse. 'Prêts' agrees with the masculine plural subject."},
      {"id": "ef_inv_4", "question": "Comment a-t-_____ fait cela ?", "translation": "(How did he/she do that?)", "options": ["il", "vous", "tu", "nous"], "correct": "il", "explanation": "Interrogative word + inversion: 'Comment a-t-il fait cela ?' Again, the euphonic 't' appears because 'a' (avoir) ends in a vowel before 'il.' With compound tenses (passé composé here), the subject pronoun goes after the auxiliary: 'a-t-il fait,' not after the past participle. 'Cela' (that) is more formal than 'ça.' This question structure — interrogative + auxiliary-pronoun + participle — is the formal standard for past-tense questions."},
      {"id": "ef_inv_5", "question": "N'avez-_____ pas compris la question ?", "translation": "(Didn't you understand the question?)", "options": ["vous", "tu", "ils", "nous"], "correct": "vous", "explanation": "Negative inversion wraps 'ne...pas' around the inverted verb-pronoun: 'N'avez-vous pas.' The word order is: ne + verb + hyphen + pronoun + pas. This is very formal and common in writing, exams, and professional speech. The informal equivalent would be 'Vous n'avez pas compris ?' (rising intonation). Mastering negative inversion is crucial for formal French — it appears frequently in literature, journalism, and academic texts."},
      {"id": "ef_inv_6", "question": "Pourrait-_____ me passer le sel ?", "translation": "(Could you pass me the salt?)", "options": ["on", "tu", "il", "nous"], "correct": "on", "explanation": "'Pourrait-on' is an extremely useful polite inversion structure. Using 'on' (one/we/someone) with the conditionnel creates an impersonal, very courteous request. 'Pourrait-on' is softer than 'pourriez-vous' because 'on' depersonalizes the request. 'Me passer le sel' — 'passer' means to pass, and the indirect object 'me' (to me) precedes the infinitive. This type of polite request with inversion is quintessentially French formal dining etiquette."},
      {"id": "ef_inv_7", "question": "Quand reviendras-_____ de vacances ?", "translation": "(When will you come back from vacation?)", "options": ["tu", "vous", "il", "nous"], "correct": "tu", "explanation": "'Revenir' in the futur simple: 'reviendras' (tu form, irregular stem 'reviendr-'). Inversion with 'tu' uses a hyphen: 'reviendras-tu.' Note that 'tu' inversion is less common than 'vous' in everyday speech — it appears mainly in literature or between close acquaintances being deliberately formal or playful. 'De vacances' — French says 'revenir de vacances' (plural, no article), while 'être en vacances' means 'to be on vacation.'"},
      {"id": "ef_inv_8", "question": "Votre fils, a-t-_____ réussi ses examens ?", "translation": "(Did your son pass his exams?)", "options": ["il", "elle", "on", "tu"], "correct": "il", "explanation": "Complex inversion with a noun subject: 'Votre fils' (your son) stays in place, and the pronoun 'il' is added after the verb. Euphonic 't' between 'a' and 'il': 'a-t-il.' 'Réussir ses examens' (to pass one's exams) — 'réussir' takes a direct object in French (no preposition), unlike 'réussir à + infinitif.' The possessive 'ses' (his) agrees with 'examens' (plural). This is a typical concerned-parent question structure."},
      {"id": "ef_inv_9", "question": "Où irons-_____ en vacances cette année ?", "translation": "(Where will we go on vacation this year?)", "options": ["nous", "vous", "ils", "on"], "correct": "nous", "explanation": "'Aller' in the futur simple: 'irons' (nous, irregular stem 'ir-'). The inversion 'irons-nous' is a natural way to plan activities together. 'En vacances' (on vacation) — remember the preposition 'en' for 'vacances' in this expression. 'Cette année' (this year) uses the demonstrative adjective 'cette' (feminine, agreeing with 'année'). This planning question demonstrates how inversion works smoothly with 'nous' in future-tense questions."},
      {"id": "ef_inv_10", "question": "Peut-_____ entrer ?", "translation": "(May I come in?)", "options": ["on", "il", "elle", "tu"], "correct": "on", "explanation": "'Peut-on entrer ?' is a supremely polite way to ask permission to enter. Using 'on' (impersonal) instead of 'je peux entrer ?' adds formal distance. No euphonic 't' is needed because 'peut' ends in a consonant. This short question is used when knocking on a door or requesting access. Compare: 'Puis-je entrer ?' (very formal, using the archaic first-person inversion form 'puis-je' instead of 'peux-je,' which is considered incorrect)."},
      {"id": "ef_inv_11", "question": "Combien coûte-t-_____ ce manteau ?", "translation": "(How much does this coat cost?)", "options": ["il", "elle", "on", "tu"], "correct": "il", "explanation": "When asking about price with inversion: 'Combien coûte-t-il ?' The euphonic 't' appears between 'coûte' (ends in vowel sound -e) and 'il.' 'Ce manteau' (this coat) is the real subject, so complex inversion applies: noun before, pronoun after. In casual speech, 'Combien ça coûte ?' or 'C'est combien ?' is far more common. Note: recent French spelling reform makes 'couter' acceptable without the circumflex, but 'coûter' remains standard."},
      {"id": "ef_inv_12", "question": "Savez-_____ où se trouve la gare ?", "translation": "(Do you know where the station is?)", "options": ["vous", "tu", "ils", "on"], "correct": "vous", "explanation": "'Savez-vous' is a formal inversion frequently used to begin polite questions to strangers. 'Où se trouve la gare' is an indirect question (no inversion inside it — the word order is normal after 'où'). 'Se trouver' (to be located) is more formal than 'être': 'Où est la gare ?' is simpler but less elegant. Asking for directions is one of the most practical applications of inversion, making 'savez-vous où...' an essential travel phrase."},
      {"id": "ef_inv_13", "question": "Marie, est-_____ arrivée ?", "translation": "(Has Marie arrived?)", "options": ["elle", "il", "on", "tu"], "correct": "elle", "explanation": "Complex inversion with a feminine noun subject: 'Marie, est-elle arrivée ?' The pronoun 'elle' mirrors the feminine subject. Past participle 'arrivée' agrees in gender with the subject (feminine singular: -ée). 'Arriver' uses 'être' in compound tenses (DR MRS VANDERTRAMP verb). This sentence tests three things simultaneously: complex inversion, auxiliary choice (être), and past participle agreement — a challenging but common combination in formal French."},
      {"id": "ef_inv_14", "question": "Puis-_____ vous poser une question ?", "translation": "(May I ask you a question?)", "options": ["je", "nous", "on", "tu"], "correct": "je", "explanation": "'Puis-je' is the ONLY correct first-person inversion form of 'pouvoir.' You cannot say 'peux-je' — it's considered ungrammatical despite seeming logical. 'Puis' is an archaic form of 'peux' preserved solely for inversion. 'Poser une question à quelqu'un' (to ask someone a question) — note French uses 'poser' (to place/put), not 'demander' for questions. 'Demander' means to ask for/request something. This distinction is a frequent error for English speakers."},
      {"id": "ef_inv_15", "question": "Ne serait-_____ pas mieux de partir maintenant ?", "translation": "(Wouldn't it be better to leave now?)", "options": ["il", "elle", "on", "tu"], "correct": "il", "explanation": "'Ne serait-il pas mieux de...' is an impersonal construction using 'il' (impersonal it) — like 'il faut,' 'il est possible.' The negative inversion 'Ne serait-il pas' wraps ne...pas around the inverted verb-pronoun. The conditionnel 'serait' makes this a tentative suggestion rather than a direct statement. 'Partir maintenant' (to leave now) is the proposed action. This structure is quintessentially French for making subtle, diplomatic suggestions in formal discourse."}
    ]
  }
]

with open(FILE, 'r') as f:
    data = json.load(f)

existing_ids = set()
for c in data:
    for item in c['items']:
        existing_ids.add(item['id'])

# Validate new categories
new_ids = set()
errors = []
for cat in new_categories:
    for item in cat['items']:
        if item['id'] in existing_ids:
            errors.append(f"DUPLICATE with existing: {item['id']}")
        if item['id'] in new_ids:
            errors.append(f"DUPLICATE within new: {item['id']}")
        new_ids.add(item['id'])
        if '_____' not in item['question']:
            errors.append(f"Missing blank in {item['id']}: {item['question'][:50]}")
        if len(item['options']) != 4:
            errors.append(f"Wrong option count in {item['id']}")
        if item['correct'] not in item['options']:
            errors.append(f"Correct not in options: {item['id']}")
        if len(item['explanation']) < 200:
            errors.append(f"Short explanation ({len(item['explanation'])} chars) in {item['id']}")

if errors:
    print("ERRORS:")
    for e in errors:
        print(f"  {e}")
else:
    data.extend(new_categories)
    with open(FILE, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    total_cats = len(data)
    total_items = sum(len(c['items']) for c in data)
    print(f"SUCCESS: {total_cats} categories, {total_items} items, 0 duplicates")
    print(f"New categories: {', '.join(c['key'] for c in new_categories)}")
